### ISSUE TITLE
[Bug]: Kafka pods are crashing and zookeeper reports unresolved address exception after machine restarts

### ISSUE THREAD

**Issue by kreetanshu** [strimzi/strimzi-kafka-operator#10179]
### Bug Description

It has been observed that after a machine/VM re-start the Kafka pods are crashing and zookeeper pod reports an Unresolved address exception. 

<img width="786" alt="image" src="https://github.com/strimzi/strimzi-kafka-operator/assets/15065832/00ac200f-704a-4168-b48b-b5e8b1071922">

This is occuring after we moved from Kafka version 3.4.0 to 3.7.0 which is supported with Strimzi Operator version 0.40(0.40.0-kafka-3.7.0). In the Strimzi-operator log we can see Session lost/Expired exception.

This issue is not very consistent it happens say 6/10 times after a machine re-start but we have seen this issue only after moving kafka from 3.4.0 to a higher version and we had to do this upgrade as stimzi operator 0.40.0-kafka-3.7.0 doesn't supports using previous Kafka version 3.4.0. As this issue is more prominent with newer version of Strimzi/Kafka, please can this be looked upon ?

The workaround we used was to re-start zookeeper pods and then kafka pods(if they are not up automatically). We had to re-start zookeeper pod multiple times. Another workaround was to uninstall and re-install kafka.

### Steps to reproduce

1. Install Strimzi Operator, Kafka and Zookeeper
2. Re-Start Machine/VM (You may need to re-start machine multiple times to hit this issue)
3. Watch for kafka pods in the namespace where kafka is installed
4. Check logs for zookeeper pod

### Expected behavior

Kafka pods should not crash and zookeeper should not report unresolved address exception after a machine/VM re-start

### Strimzi version

0.40

### Kubernetes version

v1.29.1+rke2r1

### Installation method

Helm Chart

### Infrastructure

Amazon EC2

### Configuration files and logs

[zookeeper-log.txt](https://github.com/user-attachments/files/15509758/zookeeper-log.txt)
[strimzi-operator.txt](https://github.com/user-attachments/files/15509759/strimzi-operator.txt)
[kafka-log.txt](https://github.com/user-attachments/files/15509761/kafka-log.txt)
[kafka-entity-operator.txt](https://github.com/user-attachments/files/15509762/kafka-entity-operator.txt)
[kafka-kafka-exporter.txt](https://github.com/user-attachments/files/15509763/kafka-kafka-exporter.txt)
[report-31-05-2024_07-08-46.zip](https://github.com/user-attachments/files/15509764/report-31-05-2024_07-08-46.zip)

### Additional context

Zookeeper Exception:
2024-05-31 06:22:46,870 INFO Created server with tickTime 500 ms minSessionTimeout 1000 ms maxSessionTimeout 10000 ms clientPortListenBacklog -1 datadir /var/lib/zookeeper/data/version-2 snapdir /var/lib/zookeeper/data/version-2 (org.apache.zookeeper.server.ZooKeeperServer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=[0:0:0:0:0:0:0:0]:2181)]
2024-05-31 06:22:46,870 ERROR Couldn't bind to kafka-cluster-zookeeper-0.kafka-cluster-zookeeper-nodes.foundation-env-default.svc/<unresolved>:2888 (org.apache.zookeeper.server.quorum.Leader) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=[0:0:0:0:0:0:0:0]:2181)]
java.net.SocketException: Unresolved address
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:380)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
	at org.apache.zookeeper.server.quorum.Leader.createServerSocket(Leader.java:322)
	at org.apache.zookeeper.server.quorum.Leader.lambda$new$0(Leader.java:301)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.apache.zookeeper.server.quorum.Leader.<init>(Leader.java:304)
	at org.apache.zookeeper.server.quorum.QuorumPeer.makeLeader(QuorumPeer.java:1340)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1551)
2024-05-31 06:22:46,870 WARN Unexpected exception (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=[0:0:0:0:0:0:0:0]:2181)]
java.io.IOException: Leader failed to initialize any of the following sockets: [kafka-cluster-zookeeper-0.kafka-cluster-zookeeper-nodes.foundation-env-default.svc/<unresolved>:2888]
	at org.apache.zookeeper.server.quorum.Leader.<init>(Leader.java:307)
	at org.apache.zookeeper.server.quorum.QuorumPeer.makeLeader(QuorumPeer.java:1340)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1551)
2024-05-31 06:22:46,870 INFO Peer state changed: looking (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=[0:0:0:0:0:0:0:0]:2181)]

**Comment by kreetanshu** [comment]
I have incorrectly tagged this issue as Bug, please can this be changed to Question as the root cause ?
