### ISSUE TITLE
NPE raised by deprecated TO rolling update on certificates renewal

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1027]
This issue is slightly related to #1026

When a certificate renewal happens (i.e. forcing it for testing) after the first "round" of the rolling update due to `rollingUpdateForNewCaCert method` method in the `KafkaAssemblyOperator`, the following NPE happens.
It's related to the call at `topicOperatorDeployment` method (during a normal rolling update in a reconcile cycle) but the "deprecated old" topic operator wasn't deployed and the related instance is null.
It also causes the rolling update on EO isn't called (at the next reconciliation the `certsRenewed` is false and it never happens again).

```
2018-10-24 17:27:06 ERROR AbstractAssemblyOperator:161 - Reconciliation #10(timer) Kafka(myproject/my-cluster): createOrUpdate failed
java.lang.NullPointerException: null
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.incrementGeneration(DeploymentOperator.java:57) ~[classes/:?]
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.lambda$rollingUpdate$0(DeploymentOperator.java:52) ~[classes/:?]
	at io.vertx.core.Future.lambda$compose$1(Future.java:265) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by ppatierno** [comment]
Following the watch on restarting pods, the EO is never restarted for getting new cluster CA:

```
NAME                                         READY     STATUS        RESTARTS   AGE
my-cluster-entity-operator-ddcbbfbb7-d4cs4   3/3       Running       1          3m
my-cluster-kafka-0                           2/2       Terminating   1          4m
my-cluster-zookeeper-0                       2/2       Running       0          1m
my-cluster-kafka-0   0/2       Terminating   1         4m
my-cluster-kafka-0   0/2       Terminating   1         5m
my-cluster-kafka-0   0/2       Terminating   1         5m
my-cluster-kafka-0   0/2       Pending   0         0s
my-cluster-kafka-0   0/2       Pending   0         0s
my-cluster-kafka-0   0/2       ContainerCreating   0         0s
my-cluster-kafka-0   1/2       Error     0         28s
my-cluster-kafka-0   1/2       Running   1         41s
my-cluster-kafka-0   2/2       Running   1         56s
my-cluster-zookeeper-0   2/2       Terminating   0         2m
my-cluster-zookeeper-0   0/2       Terminating   0         2m
my-cluster-zookeeper-0   0/2       Terminating   0         3m
my-cluster-zookeeper-0   0/2       Terminating   0         3m
my-cluster-zookeeper-0   0/2       Pending   0         0s
my-cluster-zookeeper-0   0/2       Pending   0         0s
my-cluster-zookeeper-0   0/2       ContainerCreating   0         0s
my-cluster-zookeeper-0   1/2       Running   0         25s
my-cluster-zookeeper-0   2/2       Running   0         30s
my-cluster-kafka-0   2/2       Terminating   1         1m
my-cluster-kafka-0   0/2       Terminating   1         2m
my-cluster-kafka-0   0/2       Terminating   1         3m
my-cluster-kafka-0   0/2       Terminating   1         3m
my-cluster-kafka-0   0/2       Pending   0         0s
my-cluster-kafka-0   0/2       Pending   0         0s
my-cluster-kafka-0   0/2       ContainerCreating   0         0s
my-cluster-kafka-0   1/2       Error     0         27s
my-cluster-kafka-0   1/2       Running   1         42s
my-cluster-kafka-0   2/2       Running   1         1m
```
