### ISSUE TITLE
EO doesn't have generation annotation since creation

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1029]
While trying to start a rolling update of EO because a cluster CA is renewed, the following NPE is raised.
The null value is about the annotations map which is null. The EO doesn't have the annotation about generation "0" on the creation. We should add that.

```
2018-10-25 12:53:52 ERROR AbstractAssemblyOperator:161 - Reconciliation #8(timer) Kafka(myproject/my-cluster): createOrUpdate failed
java.lang.NullPointerException: null
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.incrementGeneration(DeploymentOperator.java:57) ~[classes/:?]
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.lambda$rollingUpdate$0(DeploymentOperator.java:52) ~[classes/:?]
	at io.vertx.core.Future.lambda$compose$1(Future.java:265) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by ppatierno** [comment]
This issue came up investigating #1026 and #1027

**Comment by stanlyDoge** [comment]
This issue was after Paolo's deeper investigation marked as unneeded and the changes have been reverted. (:cry:)
