### ISSUE TITLE
Kafka topic creation fails if KafkaTopic yaml does not specify partitions or replicas

### ISSUE THREAD

**Issue by asaintsever** [strimzi/strimzi-kafka-operator#1049]
If you try to create a topic using following yaml:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-aa
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
```

Then `kubectl get kt` will list topic-aa but no topic-aa will be created internally. You can check this using this command:
```
kubectl exec -it my-cluster-zookeeper-0 -c zookeeper -n kafka -- bin/kafka-topics.sh --zookeeper localhost:21810 --list
```
Pod Entity Operator will display exception:

```
[2018-10-31 14:34:57,654] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event ADDED on resource topic-aa with labels {strimzi.io/cluster=my-cluster}
[2018-10-31 14:34:57,665] WARN  <ctionManager:192> [ault.svc/...] Exec Failure
java.lang.NullPointerException: null
	at io.strimzi.operator.topic.TopicSerialization.getReplicas(TopicSerialization.java:110) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.TopicSerialization.fromTopicResource(TopicSerialization.java:89) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.TopicOperator.onResourceAdded(TopicOperator.java:752) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.K8sTopicWatcher.eventReceived(K8sTopicWatcher.java:56) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.K8sTopicWatcher.eventReceived(K8sTopicWatcher.java:18) ~[topic-operator-0.8.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:227) [topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310) ~[topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) ~[topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) [topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) [topic-operator-0.8.2.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) [topic-operator-0.8.2.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [topic-operator-0.8.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 
```

Same thing if you do not specify partitions like this:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-dd
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
```

Pod Entity Operator will display exception:

```
 [2018-10-31 15:03:47,502] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event ADDED on resource topic-dd with labels {strimzi.io/cluster=my-cluster}
[2018-10-31 15:03:47,502] WARN  <ctionManager:192> [ault.svc/...] Exec Failure
java.lang.NullPointerException: null
	at io.strimzi.operator.topic.TopicSerialization.getPartitions(TopicSerialization.java:118) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.TopicSerialization.fromTopicResource(TopicSerialization.java:88) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.TopicOperator.onResourceAdded(TopicOperator.java:752) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.K8sTopicWatcher.eventReceived(K8sTopicWatcher.java:56) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.K8sTopicWatcher.eventReceived(K8sTopicWatcher.java:18) ~[topic-operator-0.8.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:227) [topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310) ~[topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) ~[topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) [topic-operator-0.8.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) [topic-operator-0.8.2.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) [topic-operator-0.8.2.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [topic-operator-0.8.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 
```

Strimzi documentation states:

- for partitions: If unspecified this will default to the broker’s num.partitions config.

- for replicas: If unspecified this will default to the broker’s default.replication.factor config.

This is not the case as TopicSerialization.getReplicas() and TopicSerialization.getPartitions() raise null pointer exceptions.

As a result, Strimzi and Kafka cluster are out of sync (Strimzi sees topics that do not exist from Kafka point of view).

**Comment by scholzj** [comment]
Thanks for raising this. I'm not sure it is so easy to get the defaults from the broker. But I agree it should be handled better.

@stanlyDoge Are you still looking for some issues to work on? ;-)

**Comment by murthy95** [comment]
hello I am not sure why this issue is closed. 

I am facing the same issue.

**Comment by scholzj** [comment]
@murthy95 What exactly do you think is not fixed on this issue? What you describe does not seem in any way related to it as you have both replicas and partitions configured.

**Comment by murthy95** [comment]
@scholzj thank you for the quick reply. 
I am facing the same issue even after configuring both replicas and paritions.

**Comment by scholzj** [comment]
Ok, then please share your log from the operator with the exception above -> I'm sure the stack trace changes since the original issue.
