### ISSUE TITLE
[Bug]: Unable to downgrade KRaft-based Kafka version 3.8.0 to 3.7.0 

### ISSUE THREAD

**Issue by alita1991** [strimzi/strimzi-kafka-operator#10735]
### Bug Description

```
2024-10-18 12:35:14,302 ERROR Encountered fatal fault: Unable to apply FeatureLevelRecord record at offset 1609 on standby controller, from the batch with baseOffset 1609 (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler) [quorum-controller-0-event-handler]
java.lang.RuntimeException: Tried to apply FeatureLevelRecord FeatureLevelRecord(name='metadata.version', featureLevel=20), but this controller only supports versions 1-19
        at org.apache.kafka.controller.FeatureControlManager.replay(FeatureControlManager.java:394)
        at org.apache.kafka.controller.QuorumController.replay(QuorumController.java:1521)
        at org.apache.kafka.controller.QuorumController.access$1600(QuorumController.java:179)
        at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$handleCommit$0(QuorumController.java:1088)
        at org.apache.kafka.controller.QuorumController$QuorumMetaLogListener.lambda$appendRaftEvent$3(QuorumController.java:1197)
        at org.apache.kafka.controller.QuorumController$ControllerEvent.run(QuorumController.java:580)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:127)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:210)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:181)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps to reproduce

https://strimzi.io/docs/operators/in-development/deploying#proc-downgrade-kafka-kraft-str

### Expected behavior

Should downgrade Kafka version successfully

### Strimzi version

0.43.0

### Kubernetes version

v1.26.12+k3s1

### Installation method

Helm Chart

### Infrastructure

K3S

### Configuration files and logs

```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: my-cluster
  namespace: kafka-test
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    version: 3.8.0
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: dual-role
  namespace: kafka-test
spec:
  replicas: 1
  roles:
  - controller
  - broker
  storage:
    type: jbod
    volumes:
    - deleteClaim: true
      id: 0
      kraftMetadata: shared
      size: 100Gi
      type: persistent-claim
```

**Comment by scholzj** [comment]
This is not a bug. Apache Kafka in KRaft does not support downgrading once the metadata version was downgraded.

**Comment by alita1991** [comment]
Hi @scholzj,

Thank you for the feedback, everything is working now. Is there any documentation available about the metadata version? I'm trying to understand how to determine the range of supported versions for each Kafka version, so I can automate and streamline the version update process with Renovate Bot.

**Comment by scholzj** [comment]
I'm not completely sure what documentation do you have in mind. I do not think Kafka has any documentation for it. In general, ever KAfka version has its own metadata version such as `3.8`. That has often multiple subversions (e.g. `3.8-IV0`). But in general they are documented only in Kafka source codes as far as I know.
