### ISSUE TITLE
[Bug]: Kafka Pod Unhealthy: Readiness Probe Fails to Connect to Port 8080 in combined mode

### ISSUE THREAD

**Issue by dannotes** [strimzi/strimzi-kafka-operator#10761]
### Bug Description

The Kafka readiness probe is attempting to connect to localhost:8080, resulting in connection failures. 
`curl: (7) Failed to connect to localhost port 8080: Connection refused`.

### Steps to reproduce

1. Deploy a Kafka cluster using Strimzi with KRaft combined (Controller + Broker) mode enabled.
2. Monitor the pod events and logs for the Kafka broker.
3. Observe the readiness probe attempts connecting to localhost:8080.

### Expected behavior

The readiness probe should check the appropriate Kafka listener ports (e.g., 9092 or 9093) instead of attempting to connect to port 8080.

### Strimzi version

0.43.0

### Kubernetes version

1.31

### Installation method

YAML files

### Infrastructure

Azure Linux servers

## Configuration File

```YAML
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        deleteClaim: false
        size: 240Gi
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0  # Latest version with KRaft support
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true  # Enable TLS for internal communication
    config:
      min.insync.replicas: 2
      default.replication.factor: 3
      producer.default.acks: "all"
      log.retention.hours: 168  # Example retention period
      offsets.topic.replication.factor: 3  # Ensure offsets topic replication
      transaction.state.log.replication.factor: 3  # Replication for transaction logs
      transaction.state.log.min.isr: 2
    resources:
      requests:
        cpu: "3"  # Resource requests for brokers
        memory: "12Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
  cruiseControl:
    config:
      num.partition.metrics.windows: 5
      partition.metrics.window.ms: 300000
      num.broker.metrics.windows: 5
      broker.metrics.window.ms: 300000
    resources:
      requests:
        cpu: "1"  # Resources for Cruise Control
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
  entityOperator:
    topicOperator: {}  # Manage Kafka topics
    userOperator: {}  # Manage Kafka users
```
 ## Events from pods
```bash
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  23m                  default-scheduler  Successfully assigned kafka/my-cluster-dual-role-1 to k8s-worker1.k8s.local
  Normal   Pulled     21m (x2 over 23m)    kubelet            Container image "quay.io/strimzi/kafka:0.43.0-kafka-3.8.0" already present on machine
  Normal   Created    21m (x2 over 23m)    kubelet            Created container kafka
  Normal   Started    21m (x2 over 23m)    kubelet            Started container kafka
  Warning  Unhealthy  3m2s (x84 over 22m)  kubelet            Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8080: Connection refused

```

**Comment by scholzj** [comment]
I guess sharing the full logs from the Kafka pods and operator as well as the YAMLs of the Pods would be a good start.

**Comment by scholzj** [comment]
If the "full" log is all you have, then the Kafka node never started and you will need to figure out why. Normally, CPU starvation would be my guess. But with `3` CPU request, that should not be the case unless you are on some very strange CPU. So I'm not sure what the issue would be. Maybe some broken storage as the command where it stops might be the first one using the Kafka log directory?

**Comment by dannotes** [comment]
> If the "full" log is all you have, then the Kafka node never started and you will need to figure out why. Normally, CPU starvation would be my guess. But with `3` CPU request, that should not be the case unless you are on some very strange CPU. So I'm not sure what the issue would be. Maybe some broken storage as the command where it stops might be the first one using the Kafka log directory?

Thank you, it seem the issue was earlier related to the disk as you suspected. Our set up is like hosting Kafka with Kraft in 3 worker nodes (different availability zones). I tried to figure out the issue and modified the YAML file and deployed again. But now it is showing another issue. Could you please throw some insights or any such link which covers our scenario would be helpful. Thank you :)

## Configuration File
### storage-class.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: az1-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: az2-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: az3-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

###  pv.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-worker0
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: az1-storage-class
  local:
    path: /mnt/disk1  # Path to the mounted logical volume on worker1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker1.local  # Worker1 node hostname
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-worker1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: az2-storage-class
  local:
    path: /mnt/disk1  # Path to the mounted logical volume on worker1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker2.local  # Worker1 node hostname
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-worker2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: az3-storage-class
  local:
    path: /mnt/disk1  # Path to the mounted logical volume on worker1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker3.local  # Worker1 node hostname
```
### kafka-cluster.yaml
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kraft
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        deleteClaim: false
        size: 100Gi
        overrides:
        - broker: 0
          class: az1-storage-class
        - broker: 1
          class: az2-storage-class
        - broker: 2
          class: az3-storage-class

---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0  # Latest version with KRaft support
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true  # Enable TLS for internal communication
    config:
      min.insync.replicas: 2
      default.replication.factor: 3
      producer.default.acks: "all"
      log.retention.hours: 168  # Example retention period
      offsets.topic.replication.factor: 3  # Ensure offsets topic replication
      transaction.state.log.replication.factor: 3  # Replication for transaction logs
      transaction.state.log.min.isr: 2
    resources:
      requests:
        cpu: "3"  # Resource requests for brokers
        memory: "12Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
  entityOperator:
    topicOperator: {}  # Manage Kafka topics
    userOperator: {}   # Manage Kafka users
```

#### Pod Status
```bash
azureuser@k8s-master:~/strimzi$ k get pods -n kafka
NAME                                        READY   STATUS    RESTARTS        AGE
kafka-cluster-kraft-0                       0/1     Running   7 (5m52s ago)   20m
kafka-cluster-kraft-1                       0/1     Running   1 (4m1s ago)    20m
kafka-cluster-kraft-2                       0/1     Running   0               9m27s
strimzi-cluster-operator-7599c657cc-v2hrk   1/1     Running   0               21m
```

#### Logs from kafka-cluster-kraft-0
```bash
2024-10-26T06:59:39.750246524Z stdout F 2024-10-26 06:59:39,750 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:39.850692364Z stdout F 2024-10-26 06:59:39,850 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:39.952985559Z stdout F 2024-10-26 06:59:39,950 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.050888425Z stdout F 2024-10-26 06:59:40,050 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.151226762Z stdout F 2024-10-26 06:59:40,150 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.251507098Z stdout F 2024-10-26 06:59:40,251 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.35167283Z stdout F 2024-10-26 06:59:40,351 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.45217365Z stdout F 2024-10-26 06:59:40,451 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.494222368Z stdout F 2024-10-26 06:59:40,493 INFO [RaftManager id=0] Disconnecting from node 2 due to socket connection setup timeout. The timeout value is 24551 ms. (org.apache.kafka.clients.NetworkClient) [kafka-0-raft-outbound-request-thread]
2024-10-26T06:59:40.552369552Z stdout F 2024-10-26 06:59:40,552 INFO [MetadataLoader id=0] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader) [kafka-0-metadata-loader-event-handler]
2024-10-26T06:59:40.629379083Z stdout F 2024-10-26 06:59:40,629 ERROR [BrokerLifecycleManager id=0] Shutting down because we were unable to register with the controller quorum. (kafka.server.BrokerLifecycleManager) [broker-0-lifecycle-manager-event-handler]
2024-10-26T06:59:40.629418784Z stdout F 2024-10-26 06:59:40,629 INFO [BrokerLifecycleManager id=0] registrationTimeout: shutting down event queue. (org.apache.kafka.queue.KafkaEventQueue) [broker-0-lifecycle-manager-event-handler]
2024-10-26T06:59:40.629694992Z stdout F 2024-10-26 06:59:40,629 INFO [BrokerLifecycleManager id=0] Transitioning from STARTING to SHUTTING_DOWN. (kafka.server.BrokerLifecycleManager) [broker-0-lifecycle-manager-event-handler]
2024-10-26T06:59:40.629922698Z stdout F 2024-10-26 06:59:40,629 INFO [broker-0-to-controller-heartbeat-channel-manager]: Shutting down (kafka.server.NodeToControllerRequestThread) [broker-0-lifecycle-manager-event-handler]
2024-10-26T06:59:40.630184506Z stdout F 2024-10-26 06:59:40,630 INFO [broker-0-to-controller-heartbeat-channel-manager]: Stopped (kafka.server.NodeToControllerRequestThread) [broker-0-to-controller-heartbeat-channel-manager]
2024-10-26T06:59:40.630188706Z stdout F 2024-10-26 06:59:40,630 INFO [broker-0-to-controller-heartbeat-channel-manager]: Shutdown completed (kafka.server.NodeToControllerRequestThread) [broker-0-lifecycle-manager-event-handler]
2024-10-26T06:59:40.632910085Z stdout F 2024-10-26 06:59:40,630 ERROR [BrokerServer id=0] Received a fatal error while waiting for the controller to acknowledge that we are caught up (kafka.server.BrokerServer) [main]
2024-10-26T06:59:40.632924385Z stdout F java.util.concurrent.CancellationException
2024-10-26T06:59:40.632926585Z stdout F         at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
2024-10-26T06:59:40.632928186Z stdout F         at kafka.server.BrokerLifecycleManager$ShutdownEvent.run(BrokerLifecycleManager.scala:638)
2024-10-26T06:59:40.632929986Z stdout F         at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:190)
2024-10-26T06:59:40.632931886Z stdout F         at java.base/java.lang.Thread.run(Thread.java:840)
2024-10-26T06:59:40.632934186Z stdout F 2024-10-26 06:59:40,631 INFO [BrokerServer id=0] Transition from STARTING to STARTED (kafka.server.BrokerServer) [main]
2024-10-26T06:59:40.634358227Z stdout F 2024-10-26 06:59:40,633 ERROR [BrokerServer id=0] Fatal error during broker startup. Prepare to shutdown (kafka.server.BrokerServer) [main]
2024-10-26T06:59:40.634399928Z stdout F java.lang.RuntimeException: Received a fatal error while waiting for the controller to acknowledge that we are caught up
2024-10-26T06:59:40.634402328Z stdout F         at org.apache.kafka.server.util.FutureUtils.waitWithLogging(FutureUtils.java:72)
2024-10-26T06:59:40.634404328Z stdout F         at kafka.server.BrokerServer.startup(BrokerServer.scala:508)
2024-10-26T06:59:40.634406128Z stdout F         at kafka.server.KafkaRaftServer.$anonfun$startup$2(KafkaRaftServer.scala:97)
2024-10-26T06:59:40.634407828Z stdout F         at kafka.server.KafkaRaftServer.$anonfun$startup$2$adapted(KafkaRaftServer.scala:97)
2024-10-26T06:59:40.634410528Z stdout F         at scala.Option.foreach(Option.scala:437)
2024-10-26T06:59:40.634412028Z stdout F         at kafka.server.KafkaRaftServer.startup(KafkaRaftServer.scala:97)
2024-10-26T06:59:40.634413629Z stdout F         at kafka.Kafka$.main(Kafka.scala:112)
2024-10-26T06:59:40.634415129Z stdout F         at kafka.Kafka.main(Kafka.scala)
2024-10-26T06:59:40.634416629Z stdout F Caused by: java.util.concurrent.CancellationException
2024-10-26T06:59:40.634418129Z stdout F         at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
2024-10-26T06:59:40.634419629Z stdout F         at kafka.server.BrokerLifecycleManager$ShutdownEvent.run(BrokerLifecycleManager.scala:638)
2024-10-26T06:59:40.634421229Z stdout F         at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:190)
2024-10-26T06:59:40.634422729Z stdout F         at java.base/java.lang.Thread.run(Thread.java:840)
2024-10-26T06:59:40.634517132Z stdout F 2024-10-26 06:59:40,634 INFO [BrokerServer id=0] Transition from STARTED to SHUTTING_DOWN (kafka.server.BrokerServer) [main]
2024-10-26T06:59:40.634520432Z stdout F 2024-10-26 06:59:40,634 INFO [BrokerServer id=0] shutting down (kafka.server.BrokerServer) [main]
2024-10-26T06:59:40.63618008Z stdout F 2024-10-26 06:59:40,635 INFO [SocketServer listenerType=BROKER, nodeId=0] Stopping socket server request processors (kafka.network.SocketServer) [main]
2024-10-26T06:59:40.63619368Z stdout F 2024-10-26 06:59:40,635 INFO Node to controller channel manager for heartbeat shutdown (kafka.server.NodeToControllerChannelManagerImpl) [broker-0-lifecycle-manager-event-handler]
2024-10-26T06:59:40.63824734Z stdout F 2024-10-26 06:59:40,637 ERROR Cannot invoke "java.nio.channels.ServerSocketChannel.close()" because the return value of "kafka.network.Acceptor.serverChannel()" is null (kafka.network.DataPlaneAcceptor) [main]
2024-10-26T06:59:40.63826084Z stdout F java.lang.NullPointerException: Cannot invoke "java.nio.channels.ServerSocketChannel.close()" because the return value of "kafka.network.Acceptor.serverChannel()" is null
2024-10-26T06:59:40.63826334Z stdout F  at kafka.network.Acceptor.$anonfun$closeAll$2(SocketServer.scala:712)
2024-10-26T06:59:40.63826564Z stdout F  at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:68)
2024-10-26T06:59:40.63826744Z stdout F  at kafka.network.Acceptor.closeAll(SocketServer.scala:712)
2024-10-26T06:59:40.63826924Z stdout F  at kafka.network.Acceptor.close(SocketServer.scala:679)
2024-10-26T06:59:40.63827134Z stdout F  at kafka.network.SocketServer.$anonfun$stopProcessingRequests$4(SocketServer.scala:288)
2024-10-26T06:59:40.63827324Z stdout F  at kafka.network.SocketServer.$anonfun$stopProcessingRequests$4$adapted(SocketServer.scala:288)
2024-10-26T06:59:40.63827534Z stdout F  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
2024-10-26T06:59:40.63827714Z stdout F  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
2024-10-26T06:59:40.638279041Z stdout F         at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
```

**Comment by scholzj** [comment]
I'm afraid I never saw this particular error. Does your networking work? Can the pods talk with each other? Was the storage clean (empty) when you started the cluster?

**Comment by dannotes** [comment]
> I'm afraid I never saw this particular error. Does your networking work? Can the pods talk with each other? Was the storage clean (empty) when you started the cluster?

Apologies for the confusion caused. It seems the issue was related to the underlying storage. I tried using Azure Disk with AKS, and now it works! 😊

Thank you.
