### ISSUE TITLE
[Bug]: Zookeeper can fail to bind port 3888 and 2888 because it cannot resolve its own full hostname.

### ISSUE THREAD

**Issue by avb-systematic** [strimzi/strimzi-kafka-operator#10977]
### Bug Description

If the pod only has a short hostname (i.e. no domain), `hostname -f` will resolve according to the DNS search domains.
If these search domains have not been set yet (as these are created/updated) by Istio, the domain name will be set to `/<unresolved>`

Then the log will fill with errors like

```
2024-12-16T03:44:38.969474713+01:00 stdout F {"exception":{"stacktrace":"java.net.SocketException: Unresolved address
at java.base/java.net.ServerSocket.bind(ServerSocket.java:380)
at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
at org.apache.zookeeper.server.quorum.Leader.createServerSocket(Leader.java:326)
at org.apache.zookeeper.server.quorum.Leader.lambda$new$0(Leader.java:301)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
at org.apache.zookeeper.server.quorum.Leader.<init>(Leader.java:304)
at org.apache.zookeeper.server.quorum.QuorumPeer.makeLeader(QuorumPeer.java:1340)
at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1551)",
"exception_class":"java.net.SocketException",
"exception_message":"Unresolved address"},
"source_host":"insight-zookeeper-0",
"method":"createServerSocket",
"level":"ERROR",
"message":"Couldn't bind to insight-zookeeper-0./<unresolved>:2888",
"mdc":{"myid":"1"},
"@timestamp":"2024-12-16T02:44:38.969Z",
"file":"Leader.java",
"line_number":"329",
"thread_name":"QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=[0:0:0:0:0:0:0:0]:2181)",
"@version":1,
"logger_name":"org.apache.zookeeper.server.quorum.Leader",
"class":"org.apache.zookeeper.server.quorum.Leader"}
```

### Steps to reproduce

1. Ensure that the zookeeper pod does not have search domains defined
2. Ensure that the zookeeper pod has an Unqualified hostname
3. Start the pod

### Expected behavior

Zookeeper should fail to startup, or wait for the DNS system to come online. 

It should NOT think that my domain name is `/<unresolved>`

### Strimzi version

0.41.0

### Kubernetes version

1.29.6+rke2r1

### Installation method

Helm chart

### Additional context

We fixed the problem by adding an ENTRYPOINT to the strimzi-zookeeper image calling `waitForDNS.sh`

`waitForDNS.sh`
```bash
#!/usr/bin/env sh
set -e

echo "Starting up $1"
sleep 10
# If it should run a check on DNS name resolving before starting ZooKeeper
# This is useful in environment (i.e. minikube) where DNS registration is slow
# Related to https://github.com/strimzi/strimzi-kafka-operator/issues/8675
# It is also related to https://issues.apache.org/jira/browse/ZOOKEEPER-4708

# This code is inspired by https://github.com/strimzi/strimzi-kafka-operator/pull/8702
# which fixes the case where hostname is correct, but DNS is not ready to resolve it

# This fixes the case where the FQDN hostname cannot be resolved
# (as the hostname is short and qualified from /etc/resolv.conf search domains)
while ! nslookup "$(hostname -f)"; do
  sleep 1
  echo "Trying to resolve $(hostname -f) ..."
done

exec "$1"
```

**Comment by avb-systematic** [comment]
We also expanded `zookeeper_healthcheck.sh` to actually check if the 3888 port was opened

```
#!/usr/bin/env bash
set -e
# Adapted from https://github.com/strimzi/strimzi-kafka-operator/blob/release-0.41.x/docker-images/kafka-based/kafka/scripts/zookeeper_healthcheck.sh

OK=$(echo ruok | nc 127.0.0.1 12181)
if [ "$OK" != "imok" ]; then
   exit 1
fi

# Check if port 3888 is open
# We cannot use netcat as we only open on localhost when using a single zookeeper and
# only open on (hostname -f) when using multiple servers
if ! netstat -l -t | grep -q -F ":3888 " && echo true ; then
    exit 1
fi
```
