### ISSUE TITLE
user-operator needs jaas file for zookeeper

### ISSUE THREAD

**Issue by BradyWiseman** [strimzi/strimzi-kafka-operator#1118]
Running recent build of strimzi-user-operator against a secure kafka cluster.  
Running a standalone deployment.
Error thrown as follows:
`2018-11-27 13:51:02 DEBUG ClientCnxn:846 - Reading reply sessionid:0x10009765d180392, packet:: clientPath:/kafka-acl/Topic serverPath:/kafka-acl/Topic finished:false header:: 2,1  replyHeader:: 2,8589943071,-102  request:: '/kafka-acl/Topic,,v{s{31,s{'world,'anyone}}},0  response::
Exception in thread "main" org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /kafka-acl/Topic
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:116)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at kafka.zookeeper.AsyncResponse.maybeThrow(ZooKeeperClient.scala:499)
	at kafka.zk.KafkaZkClient.createRecursive(KafkaZkClient.scala:1449)
	at kafka.zk.KafkaZkClient.$anonfun$createAclPaths$2(KafkaZkClient.scala:957)
	at kafka.zk.KafkaZkClient.$anonfun$createAclPaths$2$adapted(KafkaZkClient.scala:957)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at kafka.zk.KafkaZkClient.$anonfun$createAclPaths$1(KafkaZkClient.scala:957)
	at kafka.zk.KafkaZkClient.$anonfun$createAclPaths$1$adapted(KafkaZkClient.scala:955)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
	at kafka.zk.KafkaZkClient.createAclPaths(KafkaZkClient.scala:955)
	at kafka.security.auth.SimpleAclAuthorizer.configure(SimpleAclAuthorizer.scala:99)
	at io.strimzi.operator.user.Main.createSimpleAclAuthorizer(Main.java:96)
	at io.strimzi.operator.user.Main.main(Main.java:46)`

When running kafka command-line utilities against the zookeeper brokers, we set
`export KAFKA_OPTS="-Djava.security.auth.login.config=/etc/zk-jaas/zookeeper_jaas.conf"`

How can I hand this jaas file to the user operator?

**Comment by BradyWiseman** [comment]
Having read the code, I tried adding the following as an ENV in the user-operator pod spec:
            - name: JAVA_OPTS
              value: "-Djava.security.auth.login.config=/etc/zk-jaas/zookeeper_jaas.conf"

The user-operator code inherits the JAVA_OPTS env variable and uses it in the on-board launch_java.sh, which starts the container.
The logs indicate that the zk client is recognizing this setting, switching to DIGEST-MD5 as SASL mechanism, and connecting successfully to the zookeeper broker.

So we're good to go here.
