### ISSUE TITLE
NPE in KafkaMirrorMakerCluster when `spec` is null on version 0.8.0

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1208]
If the `KafkaMirrorMaker` resource YAML file doesn't have the `spec` field, the following NPE is raised (in version 0.8.0).

```
2019-01-08 10:45:26 INFO  AbstractAssemblyOperator:152 - Reconciliation #45(timer) Kafka(kafka-02/strimzi): Assembly strimzi should be created or updated
2019-01-08 10:45:26 INFO  AbstractAssemblyOperator:152 - Reconciliation #46(timer) KafkaMirrorMaker(kafka-02/mirrormakertest): Assembly mirrormakertest should be created or updated
2019-01-08 10:45:26 ERROR AbstractAssemblyOperator:161 - Reconciliation #46(timer) KafkaMirrorMaker(kafka-02/mirrormakertest): createOrUpdate failed
java.lang.NullPointerException: null
                at io.strimzi.operator.cluster.model.KafkaMirrorMakerCluster.fromCrd(KafkaMirrorMakerCluster.java:181) ~[cluster-operator.jar:?]
                at io.strimzi.operator.cluster.operator.assembly.KafkaMirrorMakerAssemblyOperator.createOrUpdate(KafkaMirrorMakerAssemblyOperator.java:78) ~[cluster-operator.jar:?]
                at io.strimzi.operator.cluster.operator.assembly.KafkaMirrorMakerAssemblyOperator.createOrUpdate(KafkaMirrorMakerAssemblyOperator.java:42) ~[cluster-operator.jar:?]
                at io.strimzi.operator.cluster.operator.assembly.AbstractAssemblyOperator.lambda$reconcileAssembly$2(AbstractAssemblyOperator.java:153) ~[cluster-operator.jar:?]
                at io.vertx.core.shareddata.impl.AsynchronousLock.lambda$lockAcquired$0(AsynchronousLock.java:61) ~[cluster-operator.jar:?]
                at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[cluster-operator.jar:?]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [cluster-operator.jar:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [cluster-operator.jar:?]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [cluster-operator.jar:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [cluster-operator.jar:?]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator.jar:?]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

It's still true on master as well.

**Comment by ppatierno** [comment]
Actually on master it's not a bug because the `createOrUpdate` in the `KafkaMirrorMakerAssemblyOperator` checks is spec is null.
