### ISSUE TITLE
Version `2.1` is not a valid version

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#1216]
Running in minishift I am getting:

```
2019-01-10 12:55:07,924 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main]
java.lang.IllegalArgumentException: Version `2.1` is not a valid version
	at kafka.api.ApiVersion$.$anonfun$apply$1(ApiVersion.scala:91)
	at scala.collection.MapLike.getOrElse(MapLike.scala:128)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at kafka.api.ApiVersion$.apply(ApiVersion.scala:91)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1138)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1028)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1008)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:59)
	at kafka.Kafka.main(Kafka.scala)
Heap
```

is that related to #1196

**Comment by matzew** [comment]
looks like the log format issue is not supported w/ 0.8.2 of Strimzi
