### ISSUE TITLE
Creating new kafka topic fails

### ISSUE THREAD

**Issue by tomas12** [strimzi/strimzi-kafka-operator#1221]
We are using kafka in open shift together with strimzi and the strimzi operator. Our problem is the creation of a topic. We upload an yaml file like this one to the strimzi operator
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-user
  labels:
    strimzi.io/cluster: development
spec:
  partitions: 2
  replicas: 2
  topicName: topic-user
  config:
    cleanup.policy: compact
```
and the operator is trying to create a topic in kafka, but he fails often. Then he removes the topic and tries it again and again. After some minutes (sometimes takes it even ~20 minutes) he succeeds in creating the topic and the operator adds some alpha numeric values to it: 
```
topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19
```
What can be the reason for the problem of creating a topic and why renames the operator the topic?

My log file:
```
[2019-01-10 13:06:26,765] INFO  <opicOperator:191> [oop-thread-0] Created topic 'topic-user' for KafkaTopic 'topic-user'
[2019-01-10 13:06:26,768] INFO  <TopicWatcher:40> [oop-thread-1] Success processing KafkaTopic watch event ADDED on resource topic-user with labels {strimzi.io/cluster=development}
2019-01-10T13:06:26.865+0000: [GC (Allocation Failure) 2019-01-10T13:06:26.865+0000: [DefNew: 109320K->104K(122880K), 0.0023183 secs] 118801K->9586K(395968K), 0.0024115 secs] [Times: user=0.00 sys=0.00, real=0.00 secs] 
[2019-01-10 13:06:26,981] INFO  <opicOperator:416> [oop-thread-0] Reconciling topic topic-user, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2019-01-10 13:06:26,981] INFO  <opicOperator:556> [oop-thread-0] All three topics are identical
[2019-01-10 13:09:36,547] INFO  <opicsWatcher:79> [oop-thread-0] Deleted topics: [topic-user]
[2019-01-10 13:09:36,560] INFO  <opicsWatcher:94> [oop-thread-0] Created topics: [topic-user]
[2019-01-10 13:09:36,634] INFO  <opicOperator:191> [oop-thread-1] Created topic 'topic-user' for KafkaTopic 'topic-user'
[2019-01-10 13:09:36,650] INFO  <opicOperator:362> [oop-thread-1] Success reconciling KafkaTopic development/topic-user
[2019-01-10 13:09:36,654] INFO  <opicOperator:416> [oop-thread-0] Reconciling topic topic-user, k8sTopic:nonnull, kafkaTopic:null, privateTopic:nonnull
[2019-01-10 13:09:36,664] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event MODIFIED on resource topic-user with labels {strimzi.io/cluster=development}
[2019-01-10 13:09:36,674] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event DELETED on resource topic-user with labels {strimzi.io/cluster=development}
[2019-01-10 13:09:36,676] INFO  <opicOperator:416> [oop-thread-0] Reconciling topic topic-user, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2019-01-10 13:09:36,681] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event ADDED on resource topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19 with labels {strimzi.io/cluster=development}
[2019-01-10 13:09:36,686] INFO  <opicOperator:416> [oop-thread-1] Reconciling topic topic-user, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2019-01-10 13:09:36,686] ERROR <TopicWatcher:49> [oop-thread-1] Failure processing KafkaTopic watch event MODIFIED on resource topic-user with labels {strimzi.io/cluster=development}: Topic 'topic-user' is already managed via KafkaTopic 'topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19' it cannot also be managed via the KafkaTopic 'topic-user'
io.strimzi.operator.topic.OperatorException: Topic 'topic-user' is already managed via KafkaTopic 'topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19' it cannot also be managed via the KafkaTopic 'topic-user'
	at io.strimzi.operator.topic.TopicOperator.update3Way(TopicOperator.java:539) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.TopicOperator.reconcile(TopicOperator.java:482) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.TopicOperator.lambda$reconcileOnResourceChange$17(TopicOperator.java:818) ~[topic-operator-0.8.2.jar:?]
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49) ~[topic-operator-0.8.2.jar:?]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[topic-operator-0.8.2.jar:?]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[topic-operator-0.8.2.jar:?]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[topic-operator-0.8.2.jar:?]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl.lambda$topicMetadata$0(BaseKafkaImpl.java:244) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$MetadataWork.complete(BaseKafkaImpl.java:186) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$Work.run(BaseKafkaImpl.java:54) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$Work.handle(BaseKafkaImpl.java:61) ~[topic-operator-0.8.2.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$Work.handle(BaseKafkaImpl.java:51) ~[topic-operator-0.8.2.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[topic-operator-0.8.2.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [topic-operator-0.8.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [topic-operator-0.8.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [topic-operator-0.8.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [topic-operator-0.8.2.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [topic-operator-0.8.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[2019-01-10 13:09:36,687] WARN  <opicOperator:95> [oop-thread-1] Failure processing KafkaTopic watch event MODIFIED on resource topic-user with labels {strimzi.io/cluster=development}: Topic 'topic-user' is already managed via KafkaTopic 'topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19' it cannot also be managed via the KafkaTopic 'topic-user'
[2019-01-10 13:09:36,689] INFO  <opicOperator:416> [oop-thread-1] Reconciling topic topic-user, k8sTopic:null, kafkaTopic:nonnull, privateTopic:nonnull
[2019-01-10 13:09:36,689] INFO  <opicOperator:316> [oop-thread-1] Deleting topic 'topic-user'
[2019-01-10 13:09:36,699] INFO  <TopicWatcher:40> [oop-thread-0] Success processing KafkaTopic watch event DELETED on resource topic-user with labels {strimzi.io/cluster=development}
[2019-01-10 13:09:36,700] INFO  <opicOperator:416> [oop-thread-0] Reconciling topic topic-user, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
[2019-01-10 13:09:36,702] ERROR <TopicWatcher:49> [oop-thread-0] Failure processing KafkaTopic watch event ADDED on resource topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19 with labels {strimzi.io/cluster=development}: Topic 'topic-user' already exists.
org.apache.kafka.common.errors.TopicExistsException: Topic 'topic-user' already exists.
[2019-01-10 13:09:36,703] WARN  <opicOperator:95> [oop-thread-0] Failure processing KafkaTopic watch event ADDED on resource topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19 with labels {strimzi.io/cluster=development}: Topic 'topic-user' already exists.
[2019-01-10 13:09:36,769] INFO  <opicsWatcher:79> [oop-thread-0] Deleted topics: [topic-user]
[2019-01-10 13:09:36,773] INFO  <opicOperator:416> [oop-thread-1] Reconciling topic topic-user, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
[2019-01-10 13:09:36,784] INFO  <opicsWatcher:94> [oop-thread-0] Created topics: [topic-user]
[2019-01-10 13:09:36,798] INFO  <opicOperator:191> [oop-thread-1] Created topic 'topic-user' for KafkaTopic 'topic-user---2dd9ef0ec24fb469195054fa5dc8d7f8a0bb0c19'
```

**Comment by tombentley** [comment]
The Topic Operator will append a hash like this if the topic name in Kafka is not a valid kube resource name. That doesn't seem to be the case here because both the `KafkaTopic` and the name of the Kafka topic is `topic-user`, which should be valid in both. It's not clear why this is happening.

**Comment by tombentley** [comment]
Since both names are the same, have you tried omitting the `topicName: topic-user` part?

**Comment by mccraigmccraig** [comment]
i'm seeing the same issue - only in my case the `topicName:` wasn't a valid kube resource name

when i remove the `topicName:` it works as expected, so it looks like specifying a `topicName:` (whether a valid kube resource name or otherwise) is what breaks it

so workaround seems to be only to use topic names which are also valid kube resource names, and always omit `topicName:`
