### ISSUE TITLE
SocketTimeoutException and Thread blocked

### ISSUE THREAD

**Issue by chonton** [strimzi/strimzi-kafka-operator#1326]
I have a strimzi-cluster-operator with the following exceptions recurring in the logs.  (The lines numbers possibly don't quite line up, this is from a HEAD build.)

I can list Kafka clusters and Topics.  However, stateful sets and pods to service those resources aren't being launched.

After restarting the operator, stateful sets and pods are created.

```Feb 12, 2019 10:56:38 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 9184 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.1/java.lang.Object.wait(Native Method)
	at java.base@11.0.1/java.lang.Object.wait(Unknown Source)
	at app//okhttp3.internal.http2.Http2Stream.waitForIo(Http2Stream.java:577)
	at app//okhttp3.internal.http2.Http2Stream$FramingSource.waitUntilReadable(Http2Stream.java:371)
	at app//okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:337)
	at app//okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
	at app//okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
	at java.base@11.0.1/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base@11.0.1/java.io.BufferedInputStream.read(Unknown Source)
	at app//io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:227)
	at app//io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
	at app//io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:384)
	at app//io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at app//io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:193)
	at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:618)
	at app//io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:68)
	at app//io.strimzi.operator.common.operator.resource.AbstractResourceOperator.listInNamespace(AbstractResourceOperator.java:237)
	at app//io.strimzi.operator.common.operator.resource.AbstractResourceOperator.list(AbstractResourceOperator.java:212)
	at app//io.strimzi.operator.cluster.operator.assembly.AbstractAssemblyOperator.reconcileAll(AbstractAssemblyOperator.java:212)
	at app//io.strimzi.operator.cluster.ClusterOperator.reconcileAll(ClusterOperator.java:145)
	at app//io.strimzi.operator.cluster.ClusterOperator.lambda$start$3(ClusterOperator.java:119)
	at app//io.strimzi.operator.cluster.ClusterOperator$$Lambda$121/0x000000010035c840.handle(Unknown Source)
	at app//io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at app//io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at app//io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$99/0x0000000100264040.run(Unknown Source)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.1/java.lang.Thread.run(Unknown Source)
```
```Feb 12, 2019 10:56:39 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:384)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:193)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:618)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:68)
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.listInNamespace(AbstractResourceOperator.java:237)
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.list(AbstractResourceOperator.java:212)
	at io.strimzi.operator.cluster.operator.assembly.AbstractAssemblyOperator.reconcileAll(AbstractAssemblyOperator.java:212)
	at io.strimzi.operator.cluster.ClusterOperator.reconcileAll(ClusterOperator.java:145)
	at io.strimzi.operator.cluster.ClusterOperator.lambda$start$3(ClusterOperator.java:119)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
	at okhttp3.internal.http2.Http2Stream$FramingSource.waitUntilReadable(Http2Stream.java:374)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:337)
	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:227)
	... 21 more
```

**Comment by scholzj** [comment]
This looks like some error in communication with the Kubernetes API. If this is something what is persistent, the DEBUG or TRACE logging in the cluster operator might give us some more details.

**Comment by chonton** [comment]
Is it possible to catch Exceptions in some base class, count the number of failures, and respond differently to the health endpoint?

**Comment by tombentley** [comment]
I think the first thing to fix here is the warning about the blocked thread. `AbstractResourceOperator.list()` is synchronous which means in the case of a socket timeout we're blocking the vertx event loop. We should add a `listAsync()` method and use that instead.

The won't prevent the socket timeout, of course. It's not clear to me what kind of different response we can use. It we cannot connect to the API server the operator can't function. When the apiserver becomes available again the operator should recover. It seems reasonable to me to just keep trying and logging errors.

**Comment by chonton** [comment]
Tracked this down to a certificate change preventing communication with ZooKeeper cluster.
