### ISSUE TITLE
DEBUG ClusterRoleBindingOperator:110 - Got GET response Response{protocol=http/1.1, code=404

### ISSUE THREAD

**Issue by ludurr** [strimzi/strimzi-kafka-operator#1362]
Hello,

operator reconciliation loop is failing.
 i am kind of struggle to actually find within a strimzi repo any clusterrolebinding with the specified name "kafka-init" under install folder for where all clusterrolebindings should be located.

Please could you help me out.

Thank you in advance.

2019-02-21 14:41:48 DEBUG ClusterRoleBindingOperator:107 - Making GET request Request{method=GET, url=https://***************.io/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/strimzi-dev-kafka-cluster-kafka-init, tag=null}
2019-02-21 14:41:48 DEBUG ClusterRoleBindingOperator:110 - Got GET response Response{protocol=http/1.1, code=404, message=Not Found, url=https://***************.io/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/strimzi-dev-kafka-cluster-kafka-init}

**Comment by scholzj** [comment]
Can you share your complete log from the cluster operator? This ClusterRoleBinding is created dynamically by the cluster operator.But this message just says that the cluster role binding doesn't exist - that it self is not an error. It just tells the operator to go and create it. So I expect there will be some other error which will fail your operator loop (for example related to RBAC rights not allowing to create it or something like that).

**Comment by ludurr** [comment]
Thank you for your support. Below is the complete log from kafkaOperator POD :
I have create kafka operator via k8s cluster Admin role


2019-02-21 21:13:16 INFO  ClusterOperator:118 - Triggering periodic reconciliation for namespace dev...
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:216 - reconcileAll(Kafka, timer): desired resources with labels Labels{}: [dev/kafka-cluster]
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:231 - reconcileAll(Kafka, timer): Other resources with labels Labels{strimzi.io/kind=Kafka}: []
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:216 - reconcileAll(KafkaMirrorMaker, timer): desired resources with labels Labels{}: []
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:231 - reconcileAll(KafkaMirrorMaker, timer): Other resources with labels Labels{strimzi.io/kind=KafkaMirrorMaker}: []
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:216 - reconcileAll(KafkaConnect, timer): desired resources with labels Labels{}: []
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:231 - reconcileAll(KafkaConnect, timer): Other resources with labels Labels{strimzi.io/kind=KafkaConnect}: []
2019-02-21 21:13:16 DEBUG AbstractAssemblyOperator:150 - Reconciliation #4(timer) Kafka(dev/kafka-cluster): Lock lock::dev::Kafka::kafka-cluster acquired
2019-02-21 21:13:16 INFO  AbstractAssemblyOperator:158 - Reconciliation #4(timer) Kafka(dev/kafka-cluster): Assembly kafka-cluster should be created or updated
2019-02-21 21:13:16 DEBUG Ca:456 - cluster-ca: The CA certificate in secret kafka-cluster-cluster-ca-cert already exists and does not need renewing
2019-02-21 21:13:16 DEBUG Ca:357 - cluster-ca renewalType NOOP
2019-02-21 21:13:16 DEBUG Ca:456 - clients-ca: The CA certificate in secret kafka-cluster-clients-ca-cert already exists and does not need renewing
2019-02-21 21:13:16 DEBUG Ca:357 - clients-ca renewalType NOOP
2019-02-21 21:13:16 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-cluster-ca-cert already exists, patching it
2019-02-21 21:13:16 DEBUG SecretOperator:140 - Secret kafka-cluster-cluster-ca-cert in namespace dev has been patched
2019-02-21 21:13:16 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-cluster-ca already exists, patching it
2019-02-21 21:13:16 DEBUG SecretOperator:140 - Secret kafka-cluster-cluster-ca in namespace dev has been patched
2019-02-21 21:13:16 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-clients-ca-cert already exists, patching it
2019-02-21 21:13:16 DEBUG SecretOperator:140 - Secret kafka-cluster-clients-ca-cert in namespace dev has been patched
2019-02-21 21:13:16 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-clients-ca already exists, patching it
2019-02-21 21:13:16 DEBUG SecretOperator:140 - Secret kafka-cluster-clients-ca in namespace dev has been patched
2019-02-21 21:13:16 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-cluster-operator-certs already exists, patching it
2019-02-21 21:13:16 DEBUG SecretOperator:140 - Secret kafka-cluster-cluster-operator-certs in namespace dev has been patched
2019-02-21 21:13:16 DEBUG KafkaAssemblyOperator:995 - Reconciliation #4(timer) Kafka(dev/kafka-cluster): Cleaning Pods for StatefulSet kafka-cluster-zookeeper to manual pod cleaning
2019-02-21 21:13:16 DEBUG StatefulSetOperator:95 - Considering manual deletion and restart of pods for dev/kafka-cluster-zookeeper
2019-02-21 21:13:16 DEBUG ServiceOperator:93 - Service dev/kafka-cluster-zookeeper-client already exists, patching it
2019-02-21 21:13:16 DEBUG ServiceOperator:140 - Service kafka-cluster-zookeeper-client in namespace dev has been patched
2019-02-21 21:13:16 DEBUG ServiceOperator:93 - Service dev/kafka-cluster-zookeeper-nodes already exists, patching it
2019-02-21 21:13:16 DEBUG ServiceOperator:140 - Service kafka-cluster-zookeeper-nodes in namespace dev has been patched
2019-02-21 21:13:16 DEBUG ConfigMapOperator:93 - ConfigMap dev/kafka-cluster-zookeeper-config already exists, patching it
2019-02-21 21:13:16 DEBUG ConfigMapOperator:47 - ConfigMap kafka-cluster-zookeeper-config in namespace dev has not been patched because resources are equal
2019-02-21 21:13:16 DEBUG AbstractModel:335 - Generating certificates
2019-02-21 21:13:16 DEBUG AbstractModel:338 - Cluster communication certificates
2019-02-21 21:13:16 DEBUG Ca:128 - cluster-ca: Reconciling zookeeper certificates
2019-02-21 21:13:16 DEBUG Ca:268 - Certificate for kafka-cluster-zookeeper-0 already exists
2019-02-21 21:13:16 DEBUG Ca:268 - Certificate for kafka-cluster-zookeeper-1 already exists
2019-02-21 21:13:16 DEBUG Ca:268 - Certificate for kafka-cluster-zookeeper-2 already exists
2019-02-21 21:13:16 DEBUG AbstractModel:340 - End generating certificates
2019-02-21 21:13:16 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-zookeeper-nodes already exists, patching it
2019-02-21 21:13:16 DEBUG SecretOperator:140 - Secret kafka-cluster-zookeeper-nodes in namespace dev has been patched
2019-02-21 21:13:16 DEBUG NetworkPolicyOperator:93 - NetworkPolicy dev/kafka-cluster-network-policy-zookeeper already exists, patching it
2019-02-21 21:13:16 DEBUG NetworkPolicyOperator:140 - NetworkPolicy kafka-cluster-network-policy-zookeeper in namespace dev has been patched
2019-02-21 21:13:16 DEBUG PodDisruptionBudgetOperator:93 - PodDisruptionBudget dev/kafka-cluster-zookeeper already exists, patching it
2019-02-21 21:13:16 DEBUG PodDisruptionBudgetOperator:121 - PodDisruptionBudget kafka-cluster-zookeeper in namespace dev has been deleted
2019-02-21 21:13:16 DEBUG PodDisruptionBudgetOperator:166 - PodDisruptionBudget kafka-cluster-zookeeper in namespace dev has been created
2019-02-21 21:13:16 DEBUG ZookeeperSetOperator:93 - StatefulSet dev/kafka-cluster-zookeeper already exists, patching it
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/revisionHistoryLimit"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:82 - StatefulSet dev/kafka-cluster-zookeeper differs: {"op":"remove","path":"/spec/template/metadata/annotations/strimzi.io~1generation"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:83 - Current StatefulSet path /spec/template/metadata/annotations/strimzi.io~1generation has value null
2019-02-21 21:13:16 DEBUG StatefulSetDiff:84 - Desired StatefulSet path /spec/template/metadata/annotations/strimzi.io~1generation has value null
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/imagePullPolicy"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/livenessProbe/failureThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/livenessProbe/periodSeconds"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/livenessProbe/successThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/readinessProbe/failureThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/readinessProbe/periodSeconds"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/readinessProbe/successThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/resources"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/terminationMessagePath"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/terminationMessagePolicy"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/imagePullPolicy"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/livenessProbe/failureThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/livenessProbe/periodSeconds"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/livenessProbe/successThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/readinessProbe/failureThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/readinessProbe/periodSeconds"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/readinessProbe/successThreshold"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/resources"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/terminationMessagePath"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/containers/1/terminationMessagePolicy"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/dnsPolicy"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/restartPolicy"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/schedulerName"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/template/spec/volumes/0/configMap/defaultMode"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/spec/volumeClaimTemplates/0/status"}
2019-02-21 21:13:16 DEBUG StatefulSetDiff:77 - StatefulSet dev/kafka-cluster-zookeeper ignoring diff {"op":"remove","path":"/status"}
2019-02-21 21:13:16 DEBUG StatefulSetOperator:312 - Patching StatefulSet dev/kafka-cluster-zookeeper
2019-02-21 21:13:16 DEBUG ZookeeperSetOperator:140 - StatefulSet kafka-cluster-zookeeper in namespace dev has been patched
2019-02-21 21:13:16 DEBUG ZookeeperSetOperator:116 - Considering rolling update of dev/kafka-cluster-zookeeper
2019-02-21 21:13:16 DEBUG KafkaAssemblyOperator:1674 - Rolling update of dev/kafka-cluster-zookeeper: pod kafka-cluster-zookeeper-0 has strimzi.io/generation=0; ss has strimzi.io/generation=0
2019-02-21 21:13:16 DEBUG KafkaAssemblyOperator:1674 - Rolling update of dev/kafka-cluster-zookeeper: pod kafka-cluster-zookeeper-1 has strimzi.io/generation=0; ss has strimzi.io/generation=0
2019-02-21 21:13:16 DEBUG KafkaAssemblyOperator:1674 - Rolling update of dev/kafka-cluster-zookeeper: pod kafka-cluster-zookeeper-2 has strimzi.io/generation=0; ss has strimzi.io/generation=0
2019-02-21 21:13:16 DEBUG Util:31 - Waiting for Endpoints resource kafka-cluster-zookeeper-client in namespace dev to get ready
2019-02-21 21:13:16 DEBUG Util:53 - Endpoints resource kafka-cluster-zookeeper-client in namespace dev is ready
2019-02-21 21:13:16 DEBUG Util:31 - Waiting for Endpoints resource kafka-cluster-zookeeper-nodes in namespace dev to get ready
2019-02-21 21:13:16 DEBUG Util:53 - Endpoints resource kafka-cluster-zookeeper-nodes in namespace dev is ready
2019-02-21 21:13:16 DEBUG PvcOperator:93 - PersistentVolumeClaim dev/data-kafka-cluster-zookeeper-0 already exists, patching it
2019-02-21 21:13:16 DEBUG PvcOperator:93 - PersistentVolumeClaim dev/data-kafka-cluster-zookeeper-1 already exists, patching it
2019-02-21 21:13:16 DEBUG PvcOperator:93 - PersistentVolumeClaim dev/data-kafka-cluster-zookeeper-2 already exists, patching it
2019-02-21 21:13:16 DEBUG PvcOperator:140 - PersistentVolumeClaim data-kafka-cluster-zookeeper-0 in namespace dev has been patched
2019-02-21 21:13:16 DEBUG PvcOperator:140 - PersistentVolumeClaim data-kafka-cluster-zookeeper-2 in namespace dev has been patched
2019-02-21 21:13:16 DEBUG PvcOperator:140 - PersistentVolumeClaim data-kafka-cluster-zookeeper-1 in namespace dev has been patched
2019-02-21 21:13:16 WARN  AbstractModel:332 - logger.name is not a valid logger
2019-02-21 21:13:16 DEBUG ServiceAccountOperator:93 - ServiceAccount dev/kafka-cluster-kafka already exists, patching it
2019-02-21 21:13:16 DEBUG ClusterRoleBindingOperator:107 - Making GET request Request{method=GET, url=https://---------------------.io/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/strimzi-dev-kafka-cluster-kafka-init, tag=null}
2019-02-21 21:13:16 DEBUG ClusterRoleBindingOperator:110 - Got GET response Response{protocol=http/1.1, code=404, message=Not Found, url=https://----------------.io/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/strimzi-dev-kafka-cluster-kafka-init}
2019-02-21 21:13:16 DEBUG ClusterRoleBindingOperator:76 - No-op (deletion requested, but does not exist)
2019-02-21 21:13:16 DEBUG ServiceOperator:93 - Service dev/kafka-cluster-kafka-bootstrap already exists, patching it
2019-02-21 21:13:16 DEBUG ServiceOperator:140 - Service kafka-cluster-kafka-bootstrap in namespace dev has been patched
2019-02-21 21:13:16 DEBUG ServiceOperator:93 - Service dev/kafka-cluster-kafka-brokers already exists, patching it
2019-02-21 21:13:16 DEBUG ServiceOperator:140 - Service kafka-cluster-kafka-brokers in namespace dev has been patched
2019-02-21 21:13:16 DEBUG ServiceOperator:102 - Service dev/kafka-cluster-kafka-external-bootstrap does not exist, noop
2019-02-21 21:13:16 DEBUG ServiceOperator:102 - Service dev/kafka-cluster-kafka-2 does not exist, noop
2019-02-21 21:13:16 DEBUG ServiceOperator:102 - Service dev/kafka-cluster-kafka-1 does not exist, noop
2019-02-21 21:13:16 DEBUG ServiceOperator:102 - Service dev/kafka-cluster-kafka-0 does not exist, noop
2019-02-21 21:13:16 DEBUG AbstractModel:379 - Generating certificates
2019-02-21 21:13:16 DEBUG Ca:171 - cluster-ca: Reconciling kafka broker certificates
2019-02-21 21:13:16 DEBUG Ca:268 - Certificate for kafka-cluster-kafka-0 already exists
2019-02-21 21:13:16 DEBUG Ca:268 - Certificate for kafka-cluster-kafka-1 already exists
2019-02-21 21:13:16 DEBUG Ca:268 - Certificate for kafka-cluster-kafka-2 already exists
2019-02-21 21:13:16 DEBUG AbstractModel:387 - End generating certificates
2019-02-21 21:13:17 DEBUG ConfigMapOperator:93 - ConfigMap dev/kafka-cluster-kafka-config already exists, patching it
2019-02-21 21:13:17 DEBUG ConfigMapOperator:47 - ConfigMap kafka-cluster-kafka-config in namespace dev has not been patched because resources are equal
2019-02-21 21:13:17 DEBUG SecretOperator:93 - Secret dev/kafka-cluster-kafka-brokers already exists, patching it
2019-02-21 21:13:17 DEBUG SecretOperator:140 - Secret kafka-cluster-kafka-brokers in namespace dev has been patched
2019-02-21 21:13:17 DEBUG NetworkPolicyOperator:93 - NetworkPolicy dev/kafka-cluster-network-policy-kafka already exists, patching it
2019-02-21 21:13:17 DEBUG NetworkPolicyOperator:140 - NetworkPolicy kafka-cluster-network-policy-kafka in namespace dev has been patched
2019-02-21 21:13:17 DEBUG PodDisruptionBudgetOperator:93 - PodDisruptionBudget dev/kafka-cluster-kafka already exists, patching it
2019-02-21 21:13:17 DEBUG PodDisruptionBudgetOperator:121 - PodDisruptionBudget kafka-cluster-kafka in namespace dev has been deleted
2019-02-21 21:13:17 DEBUG PodDisruptionBudgetOperator:166 - PodDisruptionBudget kafka-cluster-kafka in namespace dev has been created
2019-02-21 21:13:17 DEBUG AbstractAssemblyOperator:162 - Reconciliation #4(timer) Kafka(dev/kafka-cluster): Lock lock::dev::Kafka::kafka-cluster released
2019-02-21 21:13:17 ERROR AbstractAssemblyOperator:167 - Reconciliation #4(timer) Kafka(dev/kafka-cluster): createOrUpdate failed
java.lang.NumberFormatException: For input string: "2.5m"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_191]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_191]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_191]
	at io.strimzi.api.kafka.model.Quantities.parseCpuAsMilliCpus(Quantities.java:129) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.strimzi.api.kafka.model.CpuMemory.milliCpuAsInt(CpuMemory.java:68) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.strimzi.operator.cluster.model.ModelUtils.resources(ModelUtils.java:171) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.strimzi.operator.cluster.model.KafkaCluster.getContainers(KafkaCluster.java:789) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.strimzi.operator.cluster.model.KafkaCluster.generateStatefulSet(KafkaCluster.java:593) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.kafkaStatefulSet(KafkaAssemblyOperator.java:1415) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$createOrUpdate$41(KafkaAssemblyOperator.java:200) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.Future.lambda$compose$1(Future.java:265) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.Future.lambda$map$3(Future.java:328) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by scholzj** [comment]
I think there is something wrong in your Kafka resource in the section where you configure CPU resources:

```
java.lang.NumberFormatException: For input string: "2.5m"
```

Could you please share your custom resource? (`kubectl get kafka kafka-cluster -o yaml`)

**Comment by ludurr** [comment]
Of course, below is the output. Actually i am running it on AKS azure / Kubernetes 1.11.4.

apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1alpha1","kind":"Kafka","metadata":{"annotations":{},"name":"kafka-cluster","namespace":"dev"},"spec":{"entityOperator":{"topicOperator":{"reconciliationIntervalSeconds":60,"watchedNamespace":"dev"},"userOperator":{"reconciliationIntervalSeconds":60,"watchedNamespace":"dev"}},"kafka":{"config":{"log.message.format.version":"2.1","offsets.topic.replication.factor":1,"transaction.state.log.min.isr":1,"transaction.state.log.replication.factor":1},"listeners":{"plain":{}},"logging":{"loggers":{"logger.name":""},"type":"inline"},"replicas":3,"resources":{"limits":{"cpu":"2.5m","memory":"4Gi"},"requests":{"cpu":"1m","memory":"2Gi"}},"storage":{"class":"default","deleteClaim":true,"size":"1Gi","type":"persistent-claim"},"version":"2.1.0"},"zookeeper":{"replicas":3,"storage":{"class":"default","deleteClaim":true,"size":"1Gi","type":"persistent-claim"}}}}
  creationTimestamp: "2019-02-21T21:06:36Z"
  generation: 1
  name: kafka-cluster
  namespace: dev
  resourceVersion: "9374065"
  selfLink: /apis/kafka.strimzi.io/v1alpha1/namespaces/dev/kafkas/kafka-cluster
  uid: 930495bd-361c-11e9-8393-92ac50d79894
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 60
      watchedNamespace: dev
    userOperator:
      reconciliationIntervalSeconds: 60
      watchedNamespace: dev
  kafka:
    config:
      log.message.format.version: "2.1"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
    logging:
      loggers:
        logger.name: ""
      type: inline
    replicas: 3
    resources:
      limits:
        cpu: 2.5m
        memory: 4Gi
      requests:
        cpu: 1m
        memory: 2Gi
    storage:
      class: default
      deleteClaim: true
      size: 1Gi
      type: persistent-claim
    version: 2.1.0
  zookeeper:
    replicas: 3
    storage:
      class: default
      deleteClaim: true
      size: 1Gi
      type: persistent-claim

**Comment by scholzj** [comment]
Yeah ... I think you cannot use `2.5m` of CPU ... from the [Kubernetes docs](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu): _A request with a decimal point, like 0.1, is converted to 100m by the API, and **precision finer than 1m is not allowed**. For this reason, the form 100m might be preferred._

Also 2.5m and 1m is very small amount of CPU. I doubt Kafka would work with it anyway (`1m` means you are giving Kafka 0.1% of one CPU core). Are you sure you didn't wanted to set it to `cpu: 2.5` and `cpu: 1` which would give Kafka 1 CPU as request and 2.5 CPU as limit?

**Comment by ludurr** [comment]
Hello Jakub,

thanks! 
It works now! 
I will close this issue now.
