### ISSUE TITLE
There is no rolling update for Zk after renewal for certificates .key

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#1372]
This issue was opened by failed ST `testAutoReplaceCaKeysTriggeredByAnno` to renew .key certificates. The problem is that we don't have a rolling update for Zk after the renewal of .key certificate by setting the annotation `"strimzi.io/force-replace=true"` to ca.key in secrets "my-cluster-cluster-ca", "my-cluster-clients-ca"

After discussion with @tombentley we found, that now we try to find the ZK leader when doing a rolling update the CO is talking TLS with the ZK pods, but in this case, we just replaced the ZK cert, but haven't rolled yet, so CO needs to trust the old ZK certs in this specific case, rather than just the new ones.

CO log:
```
2019-02-21 16:27:14 DEBUG DnsNameResolver:86 - [id: 0x168b7c72] RECEIVED: [272: /172.30.0.2:53], DatagramDnsResponse(from: /172.30.0.2:53, to: /0.0.0.0:41403, 272, QUERY(0), NoError(0), RD AA RA)
	DefaultDnsQuestion(my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.security-cluster-test.svc.cluster.local. IN AAAA)
	DefaultDnsRawRecord(cluster.local. 60 IN SOA 42B)
2019-02-21 16:27:14 DEBUG DnsNameResolver:86 - [id: 0x168b7c72] RECEIVED: [65432: /172.30.0.2:53], DatagramDnsResponse(from: /172.30.0.2:53, to: /0.0.0.0:41403, 65432, QUERY(0), NoError(0), RD AA RA)
	DefaultDnsQuestion(my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.security-cluster-test.svc.cluster.local. IN A)
	DefaultDnsRawRecord(my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.security-cluster-test.svc.cluster.local. 30 IN A 4B)
2019-02-21 16:27:14 WARN  ZookeeperLeaderFinder:252 - ZK my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.security-cluster-test.svc.cluster.local:2181: failed to connect to zookeeper:
2019-02-21 16:27:14 DEBUG ZookeeperLeaderFinder:173 - Ignoring error

javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521) ~[?:1.8.0_191]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528) ~[?:1.8.0_191]
.......
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_191]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709) ~[?:1.8.0_191]
........
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[?:1.8.0_191]
..............
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:1.8.0_191]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:1.8.0_191]
```

**Comment by scholzj** [comment]
Triaged on 21st June: This has been fixed in the past.
