### ISSUE TITLE
NPE while deploying Kafka cluster without TO and UO

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#1396]
NPE in CO logs while deploying Kafka cluster without TO and UO.

Step to reproduce:
1. Deploying the Cluster Operator
2. Remove `topicOperator: {}` and `userOperator: {}` form `kafka-ephemeral.yaml`
Yaml should looks like ```   entityOperator: {} ```
3. Deploy Kafka cluster via commend `oc apply -f examples/kafka/kafka-ephemeral.yaml`

CO has NPE:
```
2019-03-01 13:54:19 ERROR AbstractAssemblyOperator:179 - Reconciliation #0(watch) Kafka(myproject/my-cluster): createOrUpdate failed
java.lang.NullPointerException: null
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$getEntityOperatorDescription$82(KafkaAssemblyOperator.java:1622) ~[cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.12.0-SNAPSHOT.jar:0.12.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by scholzj** [comment]
The NPEs seem to be there even when only from of TO or UO is configured. I opened a PR to fix it.
