### ISSUE TITLE
Cluster operator start fail on PKS | Error: PKIX path validation failed: java.security.cert.CertPathValidatorException

### ISSUE THREAD

**Issue by hkumarmk** [strimzi/strimzi-kafka-operator#1432]
I am trying to deploy cluster operator in PKS managed kubenetes cluster, and cluster operator start fail with below error. It seems it is failing with trusting CA Cert, but not sure what it is trying to connect on this failure. BUT when I try the same in my local kubernetes cluster setup by docker for desktop (Mac) (kubernetes vesion 1.13) it just works!

please suggest! 

Here are the details:

I am using https://github.com/strimzi/strimzi-kafka-operator/tree/0.11.1.

Here is the kubenetes version running on failed environment
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

The stacktrace shows it throws exception at https://github.com/strimzi/strimzi-kafka-operator/blob/0.11.1/cluster-operator/src/main/java/io/strimzi/operator/cluster/Main.java#L215 where it seems it is trying to connect to kubernetes api, but I see it get kubernetes CA certs in service account secret.

Here is the logs/exceptions from cluster operator container:

```
$ kubectl -n kafka logs strimzi-cluster-operator-658b8b68b4-76hqv
+ JAR=/cluster-operator-0.11.1.jar
+ shift
+ . /bin/dynamic_resources.sh
++ get_heap_size
+++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
++ CONTAINER_MEMORY_IN_BYTES=268435456
++ DEFAULT_MEMORY_CEILING=32505856
++ '[' 268435456 -lt 32505856 ']'
+ MAX_HEAP=
+ '[' -n '' ']'
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -jar /cluster-operator-0.11.1.jar
2019-03-12 11:36:48 INFO  Main:72 - ClusterOperator 0.11.1 is starting
2019-03-12 11:36:50 ERROR Main:215 - OpenShift detection failed
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_191]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.Main.lambda$isOnOpenShift$4(Main.java:204) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[cluster-operator-0.11.1.jar:0.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.11.1.jar:0.11.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259) ~[?:1.8.0_191]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[?:1.8.0_191]
	... 42 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:154) ~[?:1.8.0_191]
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80) ~[?:1.8.0_191]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259) ~[?:1.8.0_191]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[?:1.8.0_191]
	... 42 more
2019-03-12 11:36:50 ERROR Main:88 - Failed to distinguish between Kubernetes and OpenShift
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[?:1.8.0_191]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_191]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_191]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:107) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[cluster-operator-0.11.1.jar:0.11.1]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.Main.lambda$isOnOpenShift$4(Main.java:204) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[cluster-operator-0.11.1.jar:0.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.11.1.jar:0.11.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:362) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259) ~[?:1.8.0_191]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[?:1.8.0_191]
	... 42 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:154) ~[?:1.8.0_191]
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80) ~[?:1.8.0_191]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:357) ~[?:1.8.0_191]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:259) ~[?:1.8.0_191]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_191]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_191]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[?:1.8.0_191]
	... 42 more

```

**Comment by scholzj** [comment]
TBH, I have never used PKS. So I might not be aware of some differences it has compared to _usual_ Kubernetes. But this kind of error normally means that the `ca.crt` provided through the service account does not match the certificate used by the Kubernetes API.

**Comment by hkumarmk** [comment]
@scholzj Thanks for quick response. I tested this as follows and I see ca.crt in serrvice account work to connect to kubenetes api. I could not do kubectl exec in cluster operator container to test this as it just fail to start.

Could you please let me know if there any steps I can follow to debug this?

```
Started a test pod/container in same namespace (kafka) and same serrvice account as of cluster controller and run curl to kubernetes.default/api
```
$ kubectl -n kafka run -it --serviceaccount=strimzi-cluster-operator --image ubuntu:latest test -- bash
curl without cacert fail
$ curl https://kubernetes.default
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

 Curl with cacert from serrvice account just work! (I get 403 as I did not provide auth token)
$ curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc/api
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "172.20.3.4:8443"
    }
  ]
}
```

**Comment by scholzj** [comment]
TBH, I have not much clue. The Fabric8 Kubernetes client used in Strimzi uses pretty much standard Java stuff to deal with SSL. Java can be a bit strict sometimes, I'm not sure how it compares to `curl`. I'm afraid it is quite hard for me to help when I don't have the certificates and cannot try things inside the cluster.

If I were you I would start by looking into the CRT file (often the parsing of the CRT file which has slightly different formatting might be an issue) and into the certificates to make sure there are no expirations (as I said, I'm not sure how strict `curl` is with these things).

If needed, there are some [configuration options](https://github.com/fabric8io/kubernetes-client#configuring-the-client) for the Kubernetes client we use. You can easily apply them to the cluster operator as environment variables. But we currently don't have a way how to apply these to the other components. So using them might give you only limited set of features. But it might help with the investigation.

**Comment by tombentley** [comment]
If you can manually run the cluster operator with the `-Djavax.net.debug=ssl,handshake` JVM options that might also help you find the cause.

**Comment by scholzj** [comment]
Yeah, running the cluster operator pod into the debug mode and running it with the options Tom suggested might give us a lot of interesting info.

**Comment by hkumarmk** [comment]
Thanks So much for quick response @scholzj @tombentley, I will check this and update the outcome.

**Comment by leonj1** [comment]
@hkumarmk Did anything come from your investigation?

**Comment by alokhom** [comment]
i am facing the same issue.
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors

**Comment by scholzj** [comment]
@alokhom can you share more context and full logs? Your error seems not to be related to any of the points described above.

**Comment by mugugnu** [comment]
Did anybody manage to use strimzi ingress with PKS ? I'm getting the same error and trying to figure out if it has something to do with ssl-passthough being available or not on pks provided ingress controller..

**Comment by alokhom** [comment]
I solved it in my case. In my view it should work no matter which kubernetes, you need to make java keystore and truststore at your client side (post making a kafkaUser with a running strimzi) . https://github.com/strimzi/strimzi-kafka-operator/issues/2141 and https://docs.confluent.io/2.0.0/kafka/ssl.html

**Comment by mugugnu** [comment]
Interesting, i skipped the kafkauser part as
I havent setup any. Buy i actually forgot to generate certs on for all brokers!
Anyway, you didnt have VMware nsx-t in place too, did you?
I have just been told that it doesnt support ssl passthrough, only ssl offloading..so i think i'm stuck anyway.

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________
