### ISSUE TITLE
Failed to set memory requirements in kafka spec

### ISSUE THREAD

**Issue by stijndehaes** [strimzi/strimzi-kafka-operator#1435]
I changed the kafka spec to include the following:

```
spec:
  kafka:
    resources:
      requests:
        cpu: 500m
        memory: 3500Mi
```

And I got the following error:

```2019-03-12 14:20:34 ERROR AbstractAssemblyOperator:176 - Reconciliation #85(timer) Kafka(strimzi/strimzi-cluster): createOrUpdate failed
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://k8ssetupdev-c13169a8.hcp.westeurope.azmk8s.io/apis/apps/v1/namespaces/strimzi/statefulsets. Message: StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|"3670016K"}},"volume|..., bigger context ...|s":{},"requests":{"cpu":"500m","memory":"3670016K"}},"volumeMounts":[{"mountPath":"/var/lib/kafka/da|.... Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|"3670016K"}},"volume|..., bigger context ...|s":{},"requests":{"cpu":"500m","memory":"3670016K"}},"volumeMounts":[{"mountPath":"/var/lib/kafka/da|..., metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:478) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:417) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:812) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:382) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalCreate(AbstractResourceOperator.java:165) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.operator.resource.StatefulSetOperator.internalCreate(StatefulSetOperator.java:271) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.operator.resource.StatefulSetOperator.internalCreate(StatefulSetOperator.java:39) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:91) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[cluster-operator-0.11.1.jar:0.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.11.1.jar:0.11.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]```

**Comment by scholzj** [comment]
@tombentley Any idea? This looks like some issue when converting the values between units.

@stijndehaes While this looks like a bug, I think you should be able to try to use `Gi` - e.g. `memory: 3Gi` or `memory: 4Gi` ... I'm not sure it would take decimals to set 3.5Gi, but integers normally work fine.

**Comment by tombentley** [comment]
Using K as the suffix should be fine (see, e.g. [docs](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory)). The cluster operator does reformat the memory given in the resource, but it converts it to a plain number, not a number in kilobytes, so I cannot explain how the number "3670016K" got into the request.

Looking at the exception message in detail it says `v1.Container.VolumeMounts: []v1.VolumeMount: Resources: v1.ResourceRequirements.Requests` which looks like the resources is somehow being interpreted as a child of a volume mount, though it's unclear how that could happen assuming the cluster operator is the only thing touching the statefulset. @stijndehaes could you post the full JSON of the statefulset just to confirm what the structure that it's trying to parse actually is?

**Comment by stijndehaes** [comment]
I have made a git repo containing some minimal setup that gives the error:

https://github.com/stijndehaes/strimzi-issue

Running it with 3.5Gi gives the following error:

```
2019-03-13 16:42:04 ERROR AbstractAssemblyOperator:176 - Reconciliation #2(watch) Kafka(default/strimzi-cluster): createOrUpdate failed
java.lang.IllegalArgumentException: Invalid memory suffix: .5Gi
	at io.strimzi.api.kafka.model.Quantities.memoryFactor(Quantities.java:75) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.api.kafka.model.Quantities.parseMemory(Quantities.java:28) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.api.kafka.model.CpuMemory.memoryAsLong(CpuMemory.java:46) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.model.ModelUtils.resources(ModelUtils.java:187) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.model.KafkaCluster.getContainers(KafkaCluster.java:853) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.model.KafkaCluster.generateStatefulSet(KafkaCluster.java:655) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.kafkaStatefulSet(KafkaAssemblyOperator.java:1485) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$createOrUpdate$41(KafkaAssemblyOperator.java:206) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.Future.lambda$compose$1(Future.java:265) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.Future.lambda$map$3(Future.java:328) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[cluster-operator-0.11.1.jar:0.11.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [cluster-operator-0.11.1.jar:0.11.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [cluster-operator-0.11.1.jar:0.11.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [cluster-operator-0.11.1.jar:0.11.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [cluster-operator-0.11.1.jar:0.11.1]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [cluster-operator-0.11.1.jar:0.11.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by stijndehaes** [comment]
@tombentley We don't even have a statefulset at the point it is failing right now. Hopefully my repo with an example can help you guys further

**Comment by scholzj** [comment]
I can confirm this ... it's interesting ... `500Mi` seems to get converted to `524288K`. `K` should be a valid unit according to the docs, but my OpenShift 3.9 rejects it as invalid suffix (=unit). `1.1Gi` is also interesting. First of all, it seems we do not support the decimal point here. But also `1.1Gi` is `1181116006,4` bytes ... and obviously there is no `0,4` bytes :-). My OpenShfit 3.9 will translate it as `1181116006400m`. I think this is something we should be able to deal with ideally.

**Comment by armisz** [comment]
Hi,
I ran into the same issue using Strimzi 0.17.0. This is the Kafka CR:

```
spec:
  kafka:
    resources:
      limits:
        cpu: '2'
        memory: 2.85Gi
```

The StatefulSet can be created initially but the reconciliation fails afterwards:

```
...
          resources:
            limits:
              cpu: '2'
              memory: 3060164198400m
```
```
java.lang.IllegalArgumentException: Invalid memory suffix: m
  at io.strimzi.operator.cluster.operator.resource.Quantities.memoryFactor(Quantities.java:79)
```

I expected this to be working as this issue has been closed with a fix.

**Comment by scholzj** [comment]
@armisz I will have a look. TBH, these conversions are a bit mess since Kubernetes sometimes decide to convert things differently than you would expect. Maybe as a workaround you can try `3Gi` or maybe `2850Mi` or something like that.

**Comment by scholzj** [comment]
@armisz I finally got to this and opened #3729 to fix this.
