### ISSUE TITLE
Cannot list kafka topics using bin/kafka-topics.sh --list

### ISSUE THREAD

**Issue by kargakis** [strimzi/strimzi-kafka-operator#1470]
Steps to reproduce:
1. Follow instructions to deploy kafka operator
2. Once everything is installed, try to list topics via a kafka pod. I am not entirely sure which zookeeper service is the appropriate to use for a client (I would guess `my-cluster-zookeeper-client`) but I tried both anyway (`my-cluster-zookeeper-client` and `my-cluster-zookeeper-nodes`) and got the same result in both cases.
```
$ kc exec -it my-cluster-kafka-1 -- ./bin/kafka-topics.sh --list --zookeeper my-cluster-zookeeper-client
Defaulting container name to kafka.
Use 'kubectl describe pod/my-cluster-kafka-1 -n kafka' to see all of the containers in this pod.
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[2019-03-24 15:01:56,473] WARN Session 0x0 for server my-cluster-zookeeper-client/10.103.106.39:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1145)
[2019-03-24 15:01:58,435] WARN Session 0x0 for server my-cluster-zookeeper-client/10.103.106.39:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)

```
3. On the zookeeper pod, the following lines are logged in the tls sidecar container
```
2019.03.24 15:01:56 LOG5[1:139993757214464]: Service [listener-2181] accepted connection from 10.40.0.7:59370
2019.03.24 15:01:56 LOG3[1:139993757214464]: SSL_accept: 1408F10B: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
2019.03.24 15:01:56 LOG5[1:139993757214464]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
```
Not sure what I am doing wrong, any help would be appreciated!
```
$ kc version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-20T16:54:39Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by scholzj** [comment]
The connection to Zookeeper is protected by TLS sidecar. So to use the command line tools still relying on Zookeeper, you have to:
* Exec into the Kafka pod (as you did)
* Use the tool with the Zookeeper address as `localhost:2181`. That will connect you to the sidecar in the same pod which will route the connection to Zookeeper.

E.g. `kc exec -it my-cluster-kafka-1 -- ./bin/kafka-topics.sh --list --zookeeper localhost:2181`

**Comment by kargakis** [comment]
@scholzj awesome, thanks a lot for your help!

**Comment by vutkin** [comment]
Hi @scholzj, and what about using --bootstrap-server my-cluster-kafka-bootstrap:9092 param with enabled authorization and authentication?
For me it shows empty response.
I guess I should use --command-config? Do you have examples with this param?
For example `--under-min-isr-partitions` doesn't work with --zookeeper param at all.

**Comment by scholzj** [comment]
I think that should work ... at the time of this issue `kafka-topics.sh` might not have supported connecting directly to Kafka yet, so it was not an option. However, I do not know the options out of my head. AFAIK they will e the same as with consumers and producers, so you have to configure it according to your broker configuration.

**Comment by Zeka13** [comment]
```
kubectl -n kafka exec -it my-kafka-0 -- ./bin/kafka-topics.sh --list --zookeeper localhost:2181
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:262)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:258)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:119)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1863)
	at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:341)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
command terminated with exit code 1

```

**Comment by scholzj** [comment]
@Zeka13 What version of Strimzi / KAfka do you use? You should preferably use the `--bootstrap-server` option and connect to Kafka instead of Zookeeper (ideally from a separate pod). If you need to use Zookeeper, you can now run the command from the Zookeeper pods to `localhost:12181`.

**Comment by Zeka13** [comment]
@scholzj thx for a quick answer, I sucseed with

`kubectl -n kafka exec -it my-kafka-0 -- ./bin/kafka-topics.sh --list --bootstrap-server my-kafka-bootstrap:9092` 

with 9093 tls it wont work for me, but I dont need it right now

btw strimzi is latest version

**Comment by scholzj** [comment]
Well, it would work even with 9093. But you would need to configure the TLS for it. So 9092 without TLS is easier obviously.
