### ISSUE TITLE
[Bug] Cannot update Kafka resource to remove TO 

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1777]
**Describe the bug**
Spin up a Kafka cluster with the TO and UO deployed. Later edit the `Kafka` to remove the TO. The TO container will remain running (not be removed from the EO pod) and an error will be logged by the CO.

**To Reproduce**
1. `kubectl apply -f example/kafka/kafka-persistent.yaml`
2. wait for cluster to come up
3. `kubectl edit k my-cluster` to remove the `topicOperator: {}` line

**Expected behavior**
The EO pod should be restarted without the TO container. There should not be a stacktrace.

**Environment (please complete the following information):**
 - Strimzi version: master
 - Installation method: YAML files
 - Kubernetes cluster: openshift 3.11
 - Infrastructure: oc cluster up

**YAML files and logs**

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.30.0.1/apis/apps/v1/namespaces/myproject/deployments/my-cluster-entity-operator. Message: Deployment.apps "my-cluster-entity-operator" is invalid: spec.template.spec.containers[0].env[8].name: Required value. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.containers[0].env[8].name, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=apps, kind=Deployment, name=my-cluster-entity-operator, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "my-cluster-entity-operator" is invalid: spec.template.spec.containers[0].env[8].name: Required value, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:503) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:442) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:406) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:365) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:293) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:745) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:145) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.api.model.apps.DoneableDeployment.done(DoneableDeployment.java:27) ~[io.fabric8.kubernetes-model-4.3.0.jar:4.3.0]
	at io.fabric8.kubernetes.api.model.apps.DoneableDeployment.done(DoneableDeployment.java:6) ~[io.fabric8.kubernetes-model-4.3.0.jar:4.3.0]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:151) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.patch(RollableScalableResourceOperation.java:167) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:109) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:45) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:107) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:45) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:163) ~[io.strimzi.operator-common-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.internalPatch(DeploymentOperator.java:85) ~[io.strimzi.operator-common-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.internalPatch(DeploymentOperator.java:22) ~[io.strimzi.operator-common-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:158) ~[io.strimzi.operator-common-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:99) ~[io.strimzi.operator-common-0.13.0-SNAPSHOT.jar:0.13.0-SNAPSHOT]

**Comment by stanlyDoge** [comment]
The EO can be started with only UO or TO, so this can be closed.

**Comment by scholzj** [comment]
@stanlyDoge So does the scenario described above work now?

**Comment by stanlyDoge** [comment]
Yes, without any issue
