### ISSUE TITLE
Cluster creation remains pending (NullPointerException)

### ISSUE THREAD

**Issue by bgranvea** [strimzi/strimzi-kafka-operator#1807]
After creating Kafka custom resource, cluster creation is stuck and there is a NullPointerException in cluster operator logs:

2019-07-17 12:14:19 INFO  AbstractAssemblyOperator:184 - Reconciliation #1(watch) Kafka(vs/my-cluster): Assembly my-cluster should be created or updated
2019-07-17 12:14:20 ERROR AbstractAssemblyOperator:193 - Reconciliation #1(watch) Kafka(vs/my-cluster): createOrUpdate failed
java.lang.NullPointerException: null
        at io.strimzi.operator.cluster.model.AbstractModel.determineImagePullPolicy(AbstractModel.java:1107) ~[io.strimzi.cluster-operator-0.12.1.jar:0.12.1]
        at io.strimzi.operator.cluster.model.ZookeeperCluster.getContainers(ZookeeperCluster.java:475) ~[io.strimzi.cluster-operator-0.12.1.jar:0.12.1]
        at io.strimzi.operator.cluster.model.ZookeeperCluster.generateStatefulSet(ZookeeperCluster.java:423) ~[io.strimzi.cluster-operator-0.12.1.jar:0.12.1]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.zkStatefulSet(KafkaAssemblyOperator.java:1115) ~[io.strimzi.cluster-operator-0.12.1.jar:0.12.1]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$reconcile$17(KafkaAssemblyOperator.java:241) ~[io.strimzi.cluster-operator-0.12.1.jar:0.12.1]

I'm not sure how to reproduce, but I've installed/uninstalled the operator several times (with different namespaces). I deleted the namespace where the operator was installed and all clusterroles and clusterrolebindings objects related to strimzi then reinstalled, but with no change.

 - Strimzi version: 0.12.1
 - Installation method: YAML
 - Kubernetes cluster: Kubernetes 1.15
 - Infrastructure: none (installation with kubeadm)
[report-17-07-2019_14-31-52.zip](https://github.com/strimzi/strimzi-kafka-operator/files/3401858/report-17-07-2019_14-31-52.zip)

**Comment by scholzj** [comment]
Can you share the custom resource you used to create Kafka cluster? Unfortunately there seems to be a bug in the script for collecting the logs and information and it doesn't add it to the ZIP. Just a guess - did you used the example custom resource from master which configures Kafka 2.3.0? 2.3.0 is not supported in 0.12.1, so you will need to use Kafka 2.2.1 / leg version 2.1.

**Comment by bgranvea** [comment]
yes, you are right, I used the sample which references Kafka 2.3.0. I don't know why it worked with first tests, maybe I used a different custom resource.
Thanks for the quick help!

**Comment by scholzj** [comment]
Anyway, thanks for reporting this. It should for sure give better error message than NPE. So we will look into that part.
