### ISSUE TITLE
[Question] Server name value of host_name cannot have the trailing dot

### ISSUE THREAD

**Issue by xiongmaodada** [strimzi/strimzi-kafka-operator#1924]
Hi,

I'm running into an issue where the connection to the nodes is failing authentication due to SSL handshake failure.
The logs show that it is an issue with the hostname, 

my-cluster-kafka-0  kafka log:
```
2019-08-26 01:52:36,363 INFO [SocketServer brokerId=0] Failed authentication with /172.30.56.8 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION)-SSL-0]
2019-08-26 01:52:36,475 INFO [Controller id=0, targetBrokerId=0] Failed authentication with my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local./172.30.56.8 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [Controller-0-to-broker-0-send-thread]
2019-08-26 01:52:36,475 ERROR [Controller id=0, targetBrokerId=0] Connection to node 0 (my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local./172.30.56.8:9091) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient) [Controller-0-to-broker-0-send-thread]
2019-08-26 01:52:36,475 WARN [RequestSendThread controllerId=0] Controller 0's connection to broker my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.:9091 (id: 0 rack: ) was unsuccessful (kafka.controller.RequestSendThread) [Controller-0-to-broker-0-send-thread]
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
        at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
        at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
        at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeWrap(SslTransportLayer.java:448)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:313)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:265)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:170)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:539)
        at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:74)
        at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:295)
        at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:402)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:484)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:340)
        ... 9 more
Caused by: java.security.cert.CertificateException: Illegal given domain name: my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.
        at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:195)
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:462)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:442)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:261)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
        ... 18 more
Caused by: java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot
        at javax.net.ssl.SNIHostName.checkHostName(SNIHostName.java:319)
        at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:108)
        at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:193)
        ... 24 more
```
my-cluster-kafka-0  tls-sidecar log:
```
Starting Stunnel with configuration:
pid = /usr/local/var/run/stunnel.pid
foreground = yes
debug = notice
[zookeeper-2181]
client = yes
CAfile = /tmp/cluster-ca.crt
cert = /etc/tls-sidecar/kafka-brokers/my-cluster-kafka-0.crt
key = /etc/tls-sidecar/kafka-brokers/my-cluster-kafka-0.key
accept = 127.0.0.1:2181
connect = my-cluster-zookeeper-client:2181
delay = yes
verify = 2


2019.08.26 01:52:23 LOG5[1:139927439534144]: stunnel 4.56 on x86_64-redhat-linux-gnu platform
2019.08.26 01:52:23 LOG5[1:139927439534144]: Compiled/running with OpenSSL 1.0.1e-fips 11 Feb 2013
2019.08.26 01:52:23 LOG5[1:139927439534144]: Threading:PTHREAD Sockets:POLL,IPv6 SSL:ENGINE,OCSP,FIPS Auth:LIBWRAP
2019.08.26 01:52:23 LOG5[1:139927439534144]: Reading configuration from file /tmp/stunnel.conf
2019.08.26 01:52:23 LOG5[1:139927439534144]: FIPS mode is enabled
2019.08.26 01:52:23 LOG4[1:139927439534144]: Insecure file permissions on /etc/tls-sidecar/kafka-brokers/my-cluster-kafka-0.key
2019.08.26 01:52:23 LOG5[1:139927439534144]: Configuration successful
2019.08.26 01:52:27 LOG5[1:139927439529728]: Service [zookeeper-2181] accepted connection from 127.0.0.1:37078
2019.08.26 01:52:27 LOG5[1:139927439529728]: connect_blocking: connected 172.16.141.39:2181
2019.08.26 01:52:27 LOG5[1:139927439529728]: Service [zookeeper-2181] connected remote server from 172.30.56.8:53290
2019.08.26 01:52:27 LOG5[1:139927439529728]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2019.08.26 01:52:27 LOG5[1:139927439529728]: Certificate accepted: depth=0, /O=io.strimzi/CN=my-cluster-zookeeper
```
does anyone have any solutions or workarounds for this?

I am running strimzi v0.13.0.

Thank you!

**Comment by scholzj** [comment]
Could you please share the whole broker log from the beginning when the broker starts? It prints the configuration there.

**Comment by xiongmaodada** [comment]
thanks for you very much. 

kubectl logs my-cluster-kafka-0  -c kafka   -n kafka  |head -n 100
```
KAFKA_BROKER_ID=0
KAFKA_LOG_DIRS=/var/lib/kafka/data/kafka-log0
Preparing truststore for replication listener
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/kafka/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for replication listener is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for replication and clienttls listener
Preparing keystore for replication and clienttls listener is complete
Preparing truststore for clienttls listener
Adding /opt/kafka/client-ca-certs/ca.crt to truststore /tmp/kafka/clients.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for clienttls listener is complete
Starting Kafka with configuration:
broker.id=0
broker.rack=

# Listeners
listeners=REPLICATION://0.0.0.0:9091,CLIENT://0.0.0.0:9092,CLIENTTLS://0.0.0.0:9093
advertised.listeners=REPLICATION://my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.:9091,CLIENT://my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.:9092,CLIENTTLS://my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local.:9093
listener.security.protocol.map=REPLICATION:SSL,CLIENT:PLAINTEXT,CLIENTTLS:SSL
inter.broker.listener.name=REPLICATION

# Zookeeper
zookeeper.connect=localhost:2181

# Logs
log.dirs=/var/lib/kafka/data/kafka-log0

# TLS / SSL
ssl.keystore.password=LNeD3yupLXd5RBI-2WW3fvtSDuVd7p5a
ssl.truststore.password=LNeD3yupLXd5RBI-2WW3fvtSDuVd7p5a
ssl.keystore.type=PKCS12
ssl.truststore.type=PKCS12
ssl.endpoint.identification.algorithm=HTTPS
ssl.secure.random.implementation=SHA1PRNG

listener.name.replication.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
listener.name.replication.ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
listener.name.replication.ssl.client.auth=required

sasl.enabled.mechanisms=


# TLS interface configuration
listener.name.clienttls.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
listener.name.clienttls.ssl.truststore.location=/tmp/kafka/clients.truststore.p12
# CLIENTTLS listener authentication
listener.name.clienttls.ssl.client.auth=none


# Authorization configuration
authorizer.class.name=


# Provided configuration
log.message.format.version=2.3
offsets.topic.replication.factor=1
transaction.state.log.min.isr=1
transaction.state.log.replication.factor=1


OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2019-08-26T10:11:09.416+0000: 1.036: [GC pause (G1 Evacuation Pause) (young), 0.0069619 secs]
   [Parallel Time: 5.6 ms, GC Workers: 1]
      [GC Worker Start (ms):  1036.4]
      [Ext Root Scanning (ms):  2.9]
      [Update RS (ms):  0.0]
         [Processed Buffers:  0]
      [Scan RS (ms):  0.0]
      [Code Root Scanning (ms):  0.0]
      [Object Copy (ms):  2.6]
      [Termination (ms):  0.0]
         [Termination Attempts:  1]
      [GC Worker Other (ms):  0.0]
      [GC Worker Total (ms):  5.5]
      [GC Worker End (ms):  1041.9]
   [Code Root Fixup: 0.0 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 0.1 ms]
   [Other: 1.3 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 1.0 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.0 ms]
      [Humongous Register: 0.0 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 0.0 ms]
   [Eden: 6144.0K(6144.0K)->0.0B(5120.0K) Survivors: 0.0B->1024.0K Heap: 6144.0K(128.0M)->1271.0K(128.0M)]
 [Times: user=0.01 sys=0.00, real=0.01 secs] 
2019-08-26T10:11:10.026+0000: 1.646: [GC pause (G1 Evacuation Pause) (young), 0.0085513 secs]
   [Parallel Time: 8.2 ms, GC Workers: 1]
      [GC Worker Start (ms):  1646.3]
      [Ext Root Scanning (ms):  2.3]
      [Update RS (ms):  0.2]
         [Processed Buffers:  1]
      [Scan RS (ms):  0.0]
      [Code Root Scanning (ms):  0.1]
      [Object Copy (ms):  5.6]
```

**Comment by scholzj** [comment]
Hmm. The way we get the hostname is just a simple `hostname -f`. I never saw it anywhere else to return the hostname with the dot at the end. The hostname should be set by Kubernetes. I wonder whether your cluster is configured to have the DNS suffix configured already witht he `.` at the end.

**Comment by xiongmaodada** [comment]
ps -ef | grep kubelet

```
/usr/local/bin/kubelet --address=10.122.219.206 --hostname-override=10.122.219.206 --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster-dns=172.16.0.2 --cluster-domain=cluster.local. --hairpin-mode promiscuous-bridge --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --v=2 --cgroup-driver=systemd
```
 --cluster-domain=cluster.local.   ??

**Comment by scholzj** [comment]
Exactly that. In all cluster I saw it was always set without the trailing dot. I.e. just `--cluster-domain=cluster.local`.

**Comment by xiongmaodada** [comment]
Ah, Thanks a lot!
