### ISSUE TITLE
kafka cluster operator setup failed

### ISSUE THREAD

**Issue by immusk** [strimzi/strimzi-kafka-operator#1929]
Hi 
I have downloaded the latest release of cluster operator 
and executed `kubectl apply -f strimzi-cluster-operator-0.13.0.yaml -n kafka`
I see that all the roles and role bindings are created, but cluster operator pod is now starting up
seeing the below error

`io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:283) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfo$5(PlatformFeaturesAvailability.java:74) ~[io.strimzi.operator-common-0.13.0.jar:0.13.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: KeyUsage does not allow digital signatures
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[?:1.8.0_222]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[?:1.8.0_222]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[?:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[?:1.8.0_222]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[?:1.8.0_222]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[?:1.8.0_222]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_222]`

`Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: KeyUsage`

can someone please suggest

**Comment by scholzj** [comment]
It looks like there is something _wrong_ with the certificate used by your Kubernetes API server. _Wring_ in a sense that Java TLS implementation does not seem to like it. From the exact error, I would guess that there is something wrong with the KeyUsage section in the certificate. 

Ideal solution would be to solve the issue with the certificate by fixing it. Possibly, you can maybe try to use the `KUBERNETES_TRUST_CERTIFICATES` environment variable to disable the checking of the certificate (not entirely secure, but might work around the issue). Although I'm not 100% this would work since it will still need to use the KeyUsage features for communication.

**Comment by immusk** [comment]
@scholzj 
That really helped, and cluster operator is running now.
we are using `openebs` as persistent, can you please help me how can I use `openebs in kafka`
https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.13.0/examples/kafka/kafka-persistent.yaml
This example uses `persistent-claim`. But I need openebs.
please help

**Comment by scholzj** [comment]
My understanding (I never used OpenEBS personally) is that OpenEBS supports provisioning of storage through Storage Classes and Persistent Volume Claims. So you should have an OpenEBS storage class in your cluster whcih you either can set as the default storage class (in which case you can just use the example without any changes) or you can speicify the name of the StorageClass in the Kafka CR liek this:

```yaml
# ...
storage:
  type: persistent-claim
  size: 1Gi
  class: my-openebs-storage-class
# ...
```

Where `my-openebs-storage-class` is the name of your OpenEBS storage class. 

There is also nice blog post which includes OpenEBS: https://blog.kubernauts.io/apache-kafka-on-kubernetes-4425e18daba5 ... so that might be helpful for you as well.

**Comment by scholzj** [comment]
@immusk Can this be closed? Or do you have something more to this?

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
