### ISSUE TITLE
[Question] Actual Communication flow for Zookepper access by broker

### ISSUE THREAD

**Issue by Framstag** [strimzi/strimzi-kafka-operator#1934]
Background: We are using the zookeeper-shell.sh script to check for Kafka cluster stability (checking for controller and completeness of brokers). During analysis we got repeately connection errors.

Since for cluster stability high network quality is important, we further analysed this using attached script. We have configured three brokers, for two of the broker container we got a success rate of only around 50% for the third 100% success.

Since we assume that connectivity errors using zookeeper-shell are similar to broker<=>zookeeper communication we se this result as urgent hint to further analyse the problem.

We do not see such high error rate in the broker logs itself though.

Question: We need further information regarding Kafka/Zookeeper setup to judge how we further analyse above problem. Especially: How is localhost:2181 actually provided in the broker container? We only see the Kafka broker process itself, but are rather sure that the broker itself does not listen to the zookeeper port ;-) We do see the mqcluster-zookeeper-client service, but this service should not map to localhost (ClientIP given)!? Looks like there is some magic I do not see. 

Goal: Clearify which hardware/softare elements communication between brokers and zookeeper passes, if the broker is configured to access zookeeper under localhost:2181to check who is to blame (possible targets: badly behaving java processes, network problems on individual openshift workers, hardware, overload situations).

**Comment by Framstag** [comment]
[zookeeper_pressure.sh.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3550484/zookeeper_pressure.sh.txt)

**Comment by scholzj** [comment]
The communication within Zookeeper cluster and between KAfka and Zookeeper is done using TLS sidecars based on Stunnel. These facilitate encryption and authentication of all communication. 

If you check the Kafka and Zookeeper pods, they have always two containers. In Kafka, the TLS sidcar listenes on localhost:2181 for unencrypted and unauthenticated connections from Kafka. It encrypts them and opens a new connection to the Zookeeper cluster which uses TLS client authentication. In the Zookeeper pods, there is another TLS sidecar listening on 2181 which takes the incomming TLS connection, authenticates it, decrypts it and forwards it to the Zookeeper node. The Zookeeper node is always listening on port `2181X` were `X` is the stateful set index.

the connections within the Zookeeper cluster are done in a similar way. Local TLS sidecar has listeners which handly encryption/decryption and TLS client authneitcation of the communication between the different ZK nodes on all the different ZK ports.

**Comment by Framstag** [comment]
Thanks, this is definitely helpful (and an overesight of me, since I was in principle aware of the sidecar containers). Would be nice if this could be part of the documentation.

Not a strict Strimsi question: Are connections issues during ./zookeeper-shell.sh localhost:2181 something we should further investigate, since these are problems that the cluster itself will also have. From your description infrastructure elements should be the same for the shell and the broker. A simple yes is enough ;-)

```
Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /controller
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1221)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1250)
        at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:726)
        at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:600)
        at org.apache.zookeeper.ZooKeeperMain.executeLine(ZooKeeperMain.java:372)
        at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:358)
        at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:291)
```

```
2019-08-27 09:28:53,087 INFO Accepted socket connection from /127.0.0.1:60744 (org.apache.zookeeper.server.NIOServerCnxnFactory) [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:21810]
2019-08-27 09:28:53,088 INFO Client attempting to establish new session at /127.0.0.1:60744 (org.apache.zookeeper.server.ZooKeeperServer) [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:21810]
2019-08-27 09:28:53,094 INFO Established session 0x101e7556c54003e with negotiated timeout 30000 for client /127.0.0.1:60744 (org.apache.zookeeper.server.ZooKeeperServer) [CommitProcessor:1]
2019-08-27 09:28:53,438 WARN Unable to read additional data from client sessionid 0x101e7556c54003e, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:21810]
2019-08-27 09:28:53,438 INFO Closed socket connection for client /127.0.0.1:60744 which had sessionid 0x101e7556c54003e (org.apache.zookeeper.server.NIOServerCnxn) [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:21810]
```

You can close the question, thanks for your (repeated) help!

**Comment by scholzj** [comment]
Honestly, i do not know much about `zookeeper-shell.sh` quality. Also AFAIU it is starting a new JVM withing the container. So I wonder if it couldhave also some resource issues etc. which might impact it (most of the memory might be alread taken by the broker). So I think it would be good to check that. Also in general, limited resources can cause a lot of issues which are seemingly unrelated. Are you using any resource request / limits configuration? If not, it might be good to set them and make sure they are reasonable.

I would agree that a problem like this is suspitios that it might affect the broker as well. Ig nothing else you should monitor the brokers to see if they have similar issues as well or not.

**Comment by scholzj** [comment]
Can this be closed? Or do you have something more to this?

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
