### ISSUE TITLE
[Enhancement] Investigate possibilities to run Strimzi on K3S

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1976]
We should investigate the possibilities to run Strimzi on K3S and if within a reasonable effort make it possible to use it there. Currently, it seems it fails in Platform detection:

```
2019-09-11 20:48:34 INFO  Main:145 - Creating cluster role strimzi-cluster-operator-namespaced
2019-09-11 20:48:35 ERROR PlatformFeaturesAvailability:76 - Detection of Kuberetes version failed.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
Caused by: java.text.ParseException: Unparseable date: "2019-08-19T16:12+00:00Z"
    at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_222]
    at io.fabric8.kubernetes.client.VersionInfo.<init>(VersionInfo.java:86) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
    at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:49) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
```

**Comment by meierale** [comment]
Just to be a tiny bit more specific, here's the full error:
```
ERROR PlatformFeaturesAvailability:76 - Detection of Kuberetes version failed.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:283) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfo$5(PlatformFeaturesAvailability.java:74) ~[io.strimzi.operator-common-0.13.0.jar:0.13.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.text.ParseException: Unparseable date: "2019-08-19T16:12+00:00Z"
	at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_222]
	at io.fabric8.kubernetes.client.VersionInfo.<init>(VersionInfo.java:86) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:49) ~[io.fabric8.kubernetes-client-4.3.0.jar:?]
```

**Comment by meierale** [comment]
kubectl version on a cluster set up with k3s results in the following:
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6-k3s.1", GitCommit:"4cd85f14854d942e9016cc15f399785c103242e9", GitTreeState:"clean", BuildDate:"2019-08-19T16:12+00:00Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6-k3s.1", GitCommit:"4cd85f14854d942e9016cc15f399785c103242e9", GitTreeState:"clean", BuildDate:"2019-08-19T16:12+00:00Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Looks like detecting the version has issues with the Datetime format of the BuildDate

**Comment by tombentley** [comment]
IMHO that's a pretty bogus date format. The +00:00 is trying to specify a UTC offset, but that's also what the Z is supposed to mean. Having both rather suggests a bug in k3s to me.

**Comment by meierale** [comment]
That does seem like a weird datedime format when taking a closer look... I opened https://github.com/rancher/k3s/issues/808

**Comment by meierale** [comment]
Just a quick update: Tried again with 0.9.1 which (from my point of view) contains a valid build date: 2019-09-19T22:36Z
However the fabric8 kubernetes client still fails to parse the date.
Guess I'll have to open an issue there now, do you agree?

**Comment by tombentley** [comment]
Looking at the sources it uses 

```java
public static final String BUILD_DATE_FORMAT = "YYYY-MM-dd'T'HH:mm:ss'Z'";
```

So I guess what's "missing" is the seconds. IDK whether it's specificed by kubernetes exactly what the build date should look like, but if not then I think it would be reasonable to expect fabric8 to be tolerant of a build date with only minute precision.

**Comment by scholzj** [comment]
@meierale I oepned a PR which allows you to override the `/version` endpoint. It can be used to get Strimzi to work on K3S. Once the initial issue with the version detection is solved, Strimzi seems to work fine. Sorry it took so long.

**Comment by tombentley** [comment]
Isn't it worth opening a fabric8 issue, so eventually this workaround becomes unnecessary?
