### ISSUE TITLE
[Question] ...oath feature does not seem to set env variables in broker

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#2111]
I set the below for turning on oauth for a listener. 

```  kafka:
    version: 2.3.0
    replicas: 5
    listeners:
      plain:
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            secretName: kafka-broker-secret
            key: clientSecret
          disableTlsHostnameVerification: true
          introspectionEndpointUri: http://keycloak.dev.ingress.aws.exchsys.company.com/auth/realms/demo/protocol/openid-connect/token/introspect
          jwksEndpointUri: http://keycloak.dev.ingress.aws.exchsys.company.com/auth/realms/demo/protocol/openid-connect/certs
          validIssuerUri: http://keycloak.dev.ingress.aws.exchsys.company.com/auth/realms/demo
          userNameClaim: preferred_username```

When the kafka broker starts up I receive errors that environmental variables are not set. 


```2019-10-18 21:44:58,229 INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor) [main]
2019-10-18 21:44:58,242 ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
org.apache.kafka.common.KafkaException: java.lang.RuntimeException: OAuth validator configuration error - one of the two should be specified: OAUTH_JWKS_ENDPOINT_URI (for fast local signature validation) or OAUTH_INTROSPECTION_ENDPOINT_URI (for using authorization server during validation)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:85)
	at kafka.network.Processor.<init>(SocketServer.scala:726)
	at kafka.network.SocketServer.newProcessor(SocketServer.scala:367)
	at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:261)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:260)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:223)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:220)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:220)
	at kafka.network.SocketServer.startup(SocketServer.scala:120)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:255)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:84)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.RuntimeException: OAuth validator configuration error - one of the two should be specified: OAUTH_JWKS_ENDPOINT_URI (for fast local signature validation) or OAUTH_INTROSPECTION_ENDPOINT_URI (for using authorization server during validation)
	at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.validateConfig(JaasServerOauthValidatorCallbackHandler.java:113)
	at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.configure(JaasServerOauthValidatorCallbackHandler.java:70)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:130)
	... 18 more
```

Do you have to separately set env variables for the brokers?

**Comment by scholzj** [comment]
You should use either the introspection endpoint or the JWKS endpoint. The
environment variables are set - the error is trying to say that it should
be one or the other.

If you are using 0.14.0, there should be already better validation if the
oaraneters in master.

**Comment by jrivers96** [comment]
Thanks!

**Comment by scholzj** [comment]
FYI: I opened a PR strimzi/strimzi-kafka-oauth#13 to improve the error message.
