### ISSUE TITLE
[Bug] Zookeeper-Certificates/Keys wiped out

### ISSUE THREAD

**Issue by iceman91176** [strimzi/strimzi-kafka-operator#2183]
**Describe the bug**
The zookeeper certificates and private key got wiped out twice in one of our kafka-deployments. The secrect <cluster-name>-zookeeper-nodes ist still there, but contains no data.
As a result kafka-brokers are crashing, kafka-clients are crashing - nothig is working any more.
We are able to recover from the issue when deleting the <cluster-name>-zookeeper-nodes secret. After the next reconciliation the secret is created & populated with certs/keys.

We are not sure what triggers the issue, but in both cases the kafka-strimzi-operator pod was restarted after a crash. Manually deleting the pod does not trigger the issue.

**To Reproduce**
UNKNOWN

**Expected behavior**
The certificates and keys should not be wiped out.

**Environment (please complete the following information):**
 - Strimzi version: [0.14.0]
 - Installation method: [Helm chart]
 - Kubernetes cluster: [Kubernetes 1.15.2]
 - Infrastructure: [BareMetal with kubeadm]

**YAML files and logs**

Report is attached to issue.

Since previous logs of operator are not included in the report, here is what got logged every 2 minutes

```
2019-11-13 10:23:44 ERROR AbstractAssemblyOperator:195 - Reconciliation #464(timer) Kafka(messaging/test-cluster): createOrUpdate failed
java.lang.NullPointerException: null
        at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:294) ~[io.strimzi.operator-common-0.14.0.jar:0.14.0]
        at io.strimzi.operator.cluster.model.ClusterCa.generateZkCerts(ClusterCa.java:136) ~[io.strimzi.cluster-operator-0.14.0.jar:0.14.0]
        at io.strimzi.operator.cluster.model.ZookeeperCluster.generateNodesSecret(ZookeeperCluster.java:461) ~[io.strimzi.cluster-operator-0.14.0.jar:0.14.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.zkNodesSecret(KafkaAssemblyOperator.java:1124) ~[io.strimzi.cluster-operator-0.14.0.jar:0.14.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$reconcile$15(KafkaAssemblyOperator.java:245) ~[io.strimzi.cluster-operator-0.14.0.jar:0.14.0]
        at io.vertx.core.Future.lambda$compose$1(Future.java:265) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$null$45(KafkaAssemblyOperator.java:1106) ~[io.strimzi.cluster-operator-0.14.0.jar:0.14.0]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.Future.lambda$map$2(Future.java:306) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [io.netty.netty-transport-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by scholzj** [comment]
That is weird. Did it happened out of nothing on an existing cluster which was working fine before?

**Comment by iceman91176** [comment]
Yes, exactly. It happenend twice. "before" ist a bit of a stretch, because ist was anyl running for 60 days or so.
In both cases the operator crashed.

**Comment by scholzj** [comment]
That is a bit weird. I saw similar problem due to some bug in Kubernetes with handling ownerReferences. When a user _copied_ the secret to another namespace including the ownerReference which in theory should not work accross namespaces, but got the original secret deleted the CO in some cases just recreates the secret without the content.

This might be a bit similar to #2044 - which was originally more about Kafka secrets.

**Comment by gamer22026** [comment]
I had same thin when upgrading the kafka cluster to 2.3.1 after updating operator to 0.15.0. My zookeeper-nodes secret was also empty and a similar stack track trace ```2019-12-03 19:03:57 ERROR AbstractOperator:129 - Reconciliation #3(watch) Kafka(test2/ko-kafka): createOrUpdate failed
java.lang.NullPointerException: null
	at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:357) ~[io.strimzi.operator-common-0.15.0.jar:0.15.0]
	at io.strimzi.operator.cluster.model.ClusterCa.generateZkCerts(ClusterCa.java:138) ~[io.strimzi.cluster-operator-0.15.0.jar:0.15.0]
	at io.strimzi.operator.cluster.model.ZookeeperCluster.generateNodesSecret(ZookeeperCluster.java:463) ~[io.strimzi.cluster-operator-0.15.0.jar:0.15.0]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.zkNodesSecret(KafkaAssemblyOperator.java:1137) ~[io.strimzi.cluster-operator-0.15.0.jar:0.15.0]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$reconcile$15(KafkaAssemblyOperator.java:250) ~[io.strimzi.cluster-operator-0.15.0.jar:0.15.0]
	at io.vertx.core.Future.lambda$compose$1(Future.java:265) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$null$44(KafkaAssemblyOperator.java:1119) ~[io.strimzi.cluster-operator-0.15.0.jar:0.15.0]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.Future.lambda$map$2(Future.java:306) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:284) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [io.netty.netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]```
I posted about it yesterday in Slack.

**Comment by holinnn** [comment]
We are experiencing a similar issue, with version 0.15.
We got our kafka certificates (CA and clients) regenerated multiple times, in different k8s clusters.
We tried to reproduce the issue but without success so far.
We know that once it happened while we were rotating all the nodes of the cluster.

We enabled DEBUG log level of the operator to get more insights and we saw:
```
2020-02-25 10:30:56 DEBUG Ca:615 - cluster-ca: CA key (in xxxx-cluster-ca) and certificate (in xxxx-cluster-ca-cert) needs to be created: CA key secret xxxx-cluster-ca is missing or lacking data.ca\.key
```
The secret was there and not missing the `data.ca.key` key. But everything we regenerated and we can’t understand why.
We have 2 questions:
- what happens if some secrets containing certificates had been duplicated in other namespaces ? Usually we just keep the `data` and remove all other unecessary keys like `ownerReference` when we copy the secrets, but what happen if someone forgets to remove it ?
- what happens if KubeAPI is not able to answer when [this line](https://github.com/strimzi/strimzi-kafka-operator/blob/fcb85b6be653d7580f0efbf1186920a5a2f02b1b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java#L551) is called ? Does it throw an error or return an empty list ?

**Comment by scholzj** [comment]
It is not really a fix - but in Strimzi 0.21.0 you will be able to disable the owner reference on the CA secrets.

> what happens if some secrets containing certificates had been duplicated in other namespaces ? Usually we just keep the data and remove all other unecessary keys like ownerReference when we copy the secrets, but what happen if someone forgets to remove it ?

My expectations would be that it either ignores it or deletes just the copy with invalid owner reference. But I do not know the code doing this in Kube. I recently heard someone else suggest there might be some bugs around this in Kube. But I do not have any link to some particular issue.

> what happens if KubeAPI is not able to answer when this line is called ? Does it throw an error or return an empty list ?

It should throw and fail the reconciliation.
