### ISSUE TITLE
kafka container not starting up in kubernetes

### ISSUE THREAD

**Issue by ndzalamachabalala** [strimzi/strimzi-kafka-operator#2197]
I am struggling to deploy kafka on kubernetes. all seems well until the kafka container crushed. The log shows : 
$ kubectl logs my-cluster-kafka-0 tls-sidecar 

2019.11.15 14:04:39 LOG5[1:140018009462528]: Service [zookeeper-2181] accepted connection from 127.0.0.1:34868
2019.11.15 14:04:49 LOG3[1:140018009462528]: Error resolving 'my-cluster-zookeeper-client': Neither nodename nor servname known (EAI_NONAME)
2019.11.15 14:04:49 LOG3[1:140018009462528]: No host resolved
2019.11.15 14:04:49 LOG5[1:140018009462528]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
2019.11.15 14:10:00 LOG5[1:140018009462528]: Service [zookeeper-2181] accepted connection from 127.0.0.1:35882
2019.11.15 14:10:00 LOG3[1:140018009462528]: connect_blocking: connect 10.101.76.218:2181: Connection refused (111)
2019.11.15 14:10:00 LOG5[1:140018009462528]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
2019.11.15 14:10:02 LOG5[1:140018009462528]: Service [zookeeper-2181] accepted connection from 127.0.0.1:35898
2019.11.15 14:10:02 LOG3[1:140018009462528]: connect_blocking: connect 10.101.76.218:2181: Connection refused (111)
2019.11.15 14:10:02 LOG5[1:140018009462528]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
2019.11.15 14:10:03 LOG5[1:140018009462528]: Service [zookeeper-2181] accepted connection from 127.0.0.1:35904
2019.11.15 14:10:23 LOG3[1:140018009462528]: Error resolving 'my-cluster-zookeeper-client': Neither nodename nor servname known (EAI_NONAME)
2019.11.15 14:10:23 LOG3[1:140018009462528]: No host resolved
2019.11.15 14:10:23 LOG5[1:140018009462528]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket

$ kubectl logs my-cluster-kafka-0 kafka

2019-11-15 14:10:02,103 INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-11-15 14:10:02,109 WARN Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
2019-11-15 14:10:03,764 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-11-15 14:10:03,766 INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-11-15 14:10:06,907 INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient) [main]
2019-11-15 14:10:09,769 WARN Client session timed out, have not heard from server in 6003ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-11-15 14:10:09,873 INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper) [main]
2019-11-15 14:10:09,873 INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn) [main-EventThread]
2019-11-15 14:10:09,876 INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient) [main]
2019-11-15 14:10:09,880 ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:258)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:254)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:112)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1826)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:364)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:387)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:84)
	at kafka.Kafka.main(Kafka.scala)
2019-11-15 14:10:09,881 INFO shutting down (kafka.server.KafkaServer) [main]
2019-11-15 14:10:09,889 INFO shut down completed (kafka.server.KafkaServer) [main]
2019-11-15 14:10:09,890 ERROR Exiting Kafka. (kafka.server.KafkaServerStartable) [main]
2019-11-15 14:10:09,893 INFO shutting down (kafka.server.KafkaServer) [kafka-shutdown-hook

**Comment by scholzj** [comment]
The `my-cluster-zookeeper-client` name should resolve to the Zookeeper service. Could you check if the service exists and if the Zookeeper pods are ready? Assuming they are, this looks like some issue with DNS in your cluster. Can you check if DNS works for other services and if you can resolve the Zookeeper service DNS from inside some other pode? (A good tool to check DNS is Kuard: https://github.com/kubernetes-up-and-running/kuard)

**Comment by ndzalamachabalala** [comment]
My zookeeper pods are all running and ready and the services that I have are: 
- my-cluster-kafka-0 
- my-cluster-kafka-bootstrap
- my-cluster-kafka-brokers
- my-cluster-kafka-external-bootstrap
- my-cluster-zookeeper-client
- my-cluster-zookeeper-nodes
All the services can have the right IP address detected as the endpoint except for my-cluster-kafka-bootstrap and my-cluster-kafka-0 service which has no endpoint

**Comment by scholzj** [comment]
Right ... but can you resolve the DNS of the services? That is different from whether the service has or hasn't endpoints.

**Comment by garymabin** [comment]
@ndzalamachabalala Did you by any chance resolve your issue? I'm facing a similar problem.

**Comment by puneetloya** [comment]
I had the same issue using strimzi. The load on the system is pretty high, not sure why the hostname could not be resolved all of a sudden while other services running in kubernetes. 

So I found there was one mistake on my side, I was creating a kafka user using strimzi operator with SCRAM-SHA-512 auth but I was not using the listener with SCRAM-SHA-512 auth. I did see that my zookeeper was being hammered by attempting to create that user again and again. Deleting that user kind of helped.

**Comment by scholzj** [comment]
@puneetloya This is a bit weird. Do you have any logs form the User Operator doing that? The listener with SCRAM-SHA-512 and the Zookeeper storage for SCRAM-SHA-512 users is fully independent. There should be no dependnecy between them. You would of course not be able to use the user when you didn't enabled it in the listeners - but that should not cause any problems with creating the users.

**Comment by puneetloya** [comment]
User operator I think is not doing anything wrong
```
[2020-03-15 23:20:05,972] INFO  <UserOperator:62> [oop-thread-0] Triggering periodic reconciliation for namespace my_namespace...
[2020-03-15 23:22:05,972] INFO  <UserOperator:62> [oop-thread-0] Triggering periodic reconciliation for namespace my_namespace...
[2020-03-15 23:24:05,973] INFO  <UserOperator:62> [oop-thread-0] Triggering periodic reconciliation for namespace my_namespace...
```
These are kafka logs across pods:
```
INFO Removing PRODUCE quota for user my-kafka-user (kafka.server.ClientQuotaManager) [/config/changes-event-process-thread]
INFO Removing FETCH quota for user my-kafka-user (kafka.server.ClientQuotaManager) [/config/changes-event-process-thread]
INFO Removing REQUEST quota for user my-kafka-user (kafka.server.ClientRequestQuotaManager) [/config/changes-event-process-thread]
INFO Removing FETCH quota for user my-kafka-user (kafka.server.ClientQuotaManager) [/config/changes-event-process-thread]
INFO Removing REQUEST quota for user my-kafka-user (kafka.server.ClientRequestQuotaManager) [/config/changes-event-process-thread]
INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener) [/config/changes-event-process-thread]
INFO Processing override for entityPath: users/my-kafka-user with config: Map(SCRAM-SHA-512 -> [hidden]) (kafka.server.DynamicConfigManager) [/config/changes-event-process-thread]
INFO Removing PRODUCE quota for user my-kafka-user (kafka.server.ClientQuotaManager) [/config/changes-event-process-thread]
INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener) [/config/changes-event-process-thread]
INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener) [/config/changes-event-process-thread]
INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener) [/config/changes-event-process-thread]
INFO Processing notification(s) to /config/changes (kafka.common.ZkNodeChangeNotificationListener) [/config/changes-event-process-thread]
```

**Comment by puneetloya** [comment]
I think it is worth putting something like this in the base docker for strimzi, 
```
echo 'networkaddress.cache.ttl=20' >> $JAVA_HOME/jre/lib/security/java.security
```
So that java does not have issues with dns caching

**Comment by scholzj** [comment]
Well, doing reocnciliation every 2 minutes should nto everload any service. Configuration of DNS caching is done in #2409 - that should be released in 0.17.0.

**Comment by puneetloya** [comment]
you guys are fast man!! Thats good 👍

**Comment by puneetloya** [comment]
Also wanted to ask is there like an optimal resource sizing for kafka and zookeeper, in terms of heap, RAM, CPU. Is there like a strimzi recommendation to follow?

**Comment by scholzj** [comment]
The sizing is very dependent on the use cases, traffic, infrastructure etc. So we do not have anything and I'm not sure how feasible is some _universal_ sizing guide.

**Comment by scholzj** [comment]
_(In general, our Kafka is still Kafka - Strimzi uses binaries from kafka.apache.org without any modifications etc. So whatever sizing applies to that should work also with Strimzi.)_

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
