### ISSUE TITLE
[Question] Crash loop after upgrade to v0.14.0

### ISSUE THREAD

**Issue by mariusstaicu** [strimzi/strimzi-kafka-operator#2245]
The kafka pod does not start after operator upgrade to 0.14.0.
Operator upgrade goes ok, zk upgrade goes ok, however kafka does not start.

Error:
```bash
2019-11-26 14:40:49,348 INFO [kafka-log-cleaner-thread-0: Shutdown completed (kafka.log.LogCleaner) [main__consumer_offsets-23/00000000000000000007.snapshot' (kafka.log.ProducerStateManager) [pool-4-thread-1
2019-11-26 14:40:41,155 INFO [Log partition=__consumer_offsets-23, dir=/var/lib/kafka/data/kafka-log0] Completed load of log with 2 segments, log start offset 0 and log end offset 7 in 104 ms (kafka.log.Log) [pool-4-thread-1
2019-11-26 14:40:41,261 INFO [Log partition=__consumer_offsets-7, dir=/var/lib/kafka/data/kafka-log0] Loading producer state till offset 7 with message format version 2 (kafka.log.Log) [pool-4-thread-1
2019-11-26 14:40:41,262 INFO [ProducerStateManager partition=__consumer_offsets-7] Loading producer state from snapshot file '/var/lib/kafka/data/kafka-log0/__consumer_offsets-7/00000000000000000007.snapshot' (kafka.log.ProducerStateManager) [pool-4-thread-1
2019-11-26 14:40:41,263 INFO [Log partition=__consumer_offsets-7, dir=/var/lib/kafka/data/kafka-log0] Completed load of log with 2 segments, log start offset 0 and log end offset 7 in 96 ms (kafka.log.Log) [pool-4-thread-1
2019-11-26 14:40:41,349 INFO [Log partition=__consumer_offsets-43, dir=/var/lib/kafka/data/kafka-log0] Loading producer state till offset 18 with message format version 2 (kafka.log.Log) [pool-4-thread-1
2019-11-26 14:40:41,350 INFO [ProducerStateManager partition=__consumer_offsets-43] Loading producer state from snapshot file '/var/lib/kafka/data/kafka-log0/__consumer_offsets-43/00000000000000000018.snapshot' (kafka.log.ProducerStateManager) [pool-4-thread-1
2019-11-26 14:40:41,350 INFO [Log partition=__consumer_offsets-43, dir=/var/lib/kafka/data/kafka-log0] Completed load of log with 3 segments, log start offset 0 and log end offset 18 in 8 ms (kafka.log.Log) [pool-4-thread-1
2019-11-26 14:40:41,450 INFO Logs loading complete in 8108 ms. (kafka.log.LogManager) [main
2019-11-26 14:40:41,648 INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager) [main
2019-11-26 14:40:41,649 INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager) [main
2019-11-26 14:40:41,651 INFO Starting the log cleaner (kafka.log.LogCleaner) [main
2019-11-26 14:40:42,547 INFO [kafka-log-cleaner-thread-0: Starting (kafka.log.LogCleaner) [kafka-log-cleaner-thread-0
2019-11-26 14:40:45,560 INFO Awaiting socket connections on 0.0.0.0:9091. (kafka.network.Acceptor) [main
2019-11-26 14:40:49,148 ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main
java.lang.NoSuchMethodError: org.apache.kafka.common.network.Selector.<init>(IJILorg/apache/kafka/common/metrics/Metrics;Lorg/apache/kafka/common/utils/Time;Ljava/lang/String;Ljava/util/Map;ZZLorg/apache/kafka/common/network/ChannelBuilder;Lorg/apache/kafka/common/memory/MemoryPool;Lorg/apache/kafka/common/utils/LogContext;)V
    at kafka.network.Processor.createSelector(SocketServer.scala:577)
    at kafka.network.Processor.<init>(SocketServer.scala:558)
    at kafka.network.SocketServer.newProcessor(SocketServer.scala:255)
    at kafka.network.SocketServer.$anonfun$addProcessors$1(SocketServer.scala:160)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:155)
    at kafka.network.SocketServer.addProcessors(SocketServer.scala:159)
    at kafka.network.SocketServer.$anonfun$createAcceptorAndProcessors$1(SocketServer.scala:147)
    at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
    at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at kafka.network.SocketServer.createAcceptorAndProcessors(SocketServer.scala:142)
    at kafka.network.SocketServer.startup(SocketServer.scala:91)
    at kafka.server.KafkaServer.startup(KafkaServer.scala:250)
    at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
    at kafka.Kafka$.main(Kafka.scala:75)
    at kafka.Kafka.main(Kafka.scala)
2019-11-26 14:40:49,158 INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer) [main
2019-11-26 14:40:49,160 INFO [SocketServer brokerId=0] Stopping socket server request processors (kafka.network.SocketServer) [main
2019-11-26 14:40:49,241 INFO [SocketServer brokerId=0] Stopped socket server request processors (kafka.network.SocketServer) [main
2019-11-26 14:40:49,344 INFO Shutting down. (kafka.log.LogManager) [main
2019-11-26 14:40:50,761 INFO Shutdown complete. (kafka.log.LogManager) [main
2019-11-26 14:40:50,772 INFO [ZooKeeperClient Closing. (kafka.zookeeper.ZooKeeperClient) [main
2019-11-26 14:40:50,844 INFO EventThread shut down for session: 0x100ddb754e70005 (org.apache.zookeeper.ClientCnxn) [main-EventThread
2019-11-26 14:40:50,844 INFO Session: 0x100ddb754e70005 closed (org.apache.zookeeper.ZooKeeper) [main
2019-11-26 14:40:50,846 INFO [ZooKeeperClient Closed. (kafka.zookeeper.ZooKeeperClient) [main
2019-11-26 14:40:50,847 INFO [ThrottledChannelReaper-Fetch: Shutting down (kafka.server.ClientQuotaManager$ThrottledChannelReaper) [main
```

kafka config is:

```yml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kf
  namespace: infrastructure
spec:
  kafka:
    version: 2.1.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      delete.topic.enable: true
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.1"
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
    jvmOptions:
      gcLoggingEnabled: false
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    resources:
      requests:
        memory: "1G"
        cpu: "50m"
      limits:
        memory: "2G"
        cpu: "200m"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
    resources:
      requests:
        memory: "400M"
        cpu: "20m"
      limits:
        memory: "600M"
        cpu: "400m"
  entityOperator:
    topicOperator: {}
    userOperator: {}


```

**Comment by tombentley** [comment]
@mariusstaicu can you share your Cluster Operator `Deployment`, i.e. `kubectl get deployment strimzi-cluster-operator -o yaml`?

**Comment by mariusstaicu** [comment]
```bash
kubectl get deployment strimzi-cluster-operator -o yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"strimzi"},"name":"strimzi-cluster-operator","namespace":"infrastructure"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"strimzi-cluster-operator","strimzi.io/kind":"cluster-operator"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"name":"strimzi-cluster-operator","strimzi.io/kind":"cluster-operator"}},"spec":{"containers":[{"args":["/opt/strimzi/bin/cluster_operator_run.sh"],"env":[{"name":"STRIMZI_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"STRIMZI_FULL_RECONCILIATION_INTERVAL_MS","value":"120000"},{"name":"STRIMZI_OPERATION_TIMEOUT_MS","value":"300000"},{"name":"STRIMZI_DEFAULT_ZOOKEEPER_IMAGE","value":"strimzi/kafka:0.14.0-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE","value":"strimzi/kafka:0.14.0-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE","value":"strimzi/kafka:0.14.0-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE","value":"strimzi/kafka:0.14.0-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE","value":"strimzi/kafka:0.14.0-kafka-2.3.0"},{"name":"STRIMZI_KAFKA_IMAGES","value":"2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0\n2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1\n2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0\n2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1\n2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0\n"},{"name":"STRIMZI_KAFKA_CONNECT_IMAGES","value":"2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0\n2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1\n2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0\n2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1\n2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0\n"},{"name":"STRIMZI_KAFKA_CONNECT_S2I_IMAGES","value":"2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0\n2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1\n2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0\n2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1\n2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0\n"},{"name":"STRIMZI_KAFKA_MIRROR_MAKER_IMAGES","value":"2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0\n2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1\n2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0\n2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1\n2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0\n"},{"name":"STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE","value":"strimzi/operator:0.14.0"},{"name":"STRIMZI_DEFAULT_USER_OPERATOR_IMAGE","value":"strimzi/operator:0.14.0"},{"name":"STRIMZI_DEFAULT_KAFKA_INIT_IMAGE","value":"strimzi/operator:0.14.0"},{"name":"STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE","value":"strimzi/kafka-bridge:0.14.0"},{"name":"STRIMZI_LOG_LEVEL","value":"INFO"}],"image":"strimzi/operator:0.14.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthy","port":8080},"initialDelaySeconds":10,"periodSeconds":30},"name":"strimzi-cluster-operator","readinessProbe":{"httpGet":{"path":"/ready","port":8080},"initialDelaySeconds":10,"periodSeconds":30},"resources":{"limits":{"cpu":"1000m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"256Mi"}}}],"serviceAccountName":"strimzi-cluster-operator"}}}}
  creationTimestamp: "2019-11-26T14:09:34Z"
  generation: 5
  labels:
    app: strimzi
  name: strimzi-cluster-operator
  namespace: infrastructure
  resourceVersion: "107746697"
  selfLink: /apis/extensions/v1beta1/namespaces/infrastructure/deployments/strimzi-cluster-operator
  uid: 5f7c3a41-1056-11ea-9e5b-42010a9a010e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      containers:
      - args:
        - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
          value: strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          value: strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE
          value: strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0
            2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1
            2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0
            2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1
            2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_KAFKA_CONNECT_IMAGES
          value: |
            2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0
            2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1
            2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0
            2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1
            2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0
            2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1
            2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0
            2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1
            2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0
            2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1
            2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0
            2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1
            2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: strimzi/operator:0.14.0
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: strimzi/operator:0.14.0
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: strimzi/operator:0.14.0
        - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
          value: strimzi/kafka-bridge:0.14.0
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        image: strimzi/operator:0.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthy
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: strimzi-cluster-operator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: strimzi-cluster-operator
      serviceAccountName: strimzi-cluster-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-26T14:09:34Z"
    lastUpdateTime: "2019-11-26T14:16:14Z"
    message: ReplicaSet "strimzi-cluster-operator-7ff64d4b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-11-26T16:12:34Z"
    lastUpdateTime: "2019-11-26T16:12:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by tombentley** [comment]
This was caused by the Strimzi 0.14 images for kafka 2.1.0 and 2.1.1 containing duplicate kafka-clients jars. A workaround is to downgrade the cluster operator to 0.13 and from there upgrade to Kafka `2.2.0` or higher. The images for 2.2.0 and higher are unaffected in Strimzi 0.14.

**Comment by mariusstaicu** [comment]
Thanks, very useful info. I will consider studying the impact of upgrading kafka to 2.2.0.

**Comment by mariusstaicu** [comment]
> A workaround is to downgrade the cluster operator to 0.13 and from there upgrade to Kafka 2.2.0 or higher.
Downgraded to 0.13.0, upgraded kafka to 2.2.0 and the upgraded with no problems to 0.14.0. Thanks.
