### ISSUE TITLE
[Bug] Install through helm chart fails

### ISSUE THREAD

**Issue by AndyDunnings** [strimzi/strimzi-kafka-operator#2278]
**Describe the bug**
When trying to install using the helm chart (from master) on OpenShift 4.2 and 3.11, the operator fails to start with either a 404 or a 403 response when opening a watch for the `KafkaConnectS2I` operator. I can't seem to replicate the 403 response issue, but the 404 is very repeatable.

The install is set to a specific namespace e.g. `helm install --name andy --namespace es helm-charts/strimzi-kafka-operator`.

**To Reproduce**
1. Install using the helm charts into a specific namespace on OpenShift 3.11 or 4.2

**Expected behavior**
Operator should install without any issues.

**Environment (please complete the following information):**
 - Strimzi version: master
 - Installation method: Helm chart
 - Kubernetes cluster: OpenShift 3.11 and OpenShift 4.2
 - Infrastructure: IBM Fyre with ICP Common Services

**YAML files and logs**

For the 403 case I do not have logs but the error was returned when starting one of the operator verticles because it didnt have permission to watch resources of type connectors.

```
2019-12-04 14:32:30 INFO  ClusterOperator:69 - Creating ClusterOperator for namespace es
2019-12-04 14:32:30 INFO  ClusterOperator:82 - Starting ClusterOperator for namespace es
2019-12-04 14:32:30 INFO  ClusterOperator:96 - Opened watch for Kafka operator
2019-12-04 14:32:31 INFO  ClusterOperator:96 - Opened watch for KafkaMirrorMaker operator
2019-12-04 14:32:31 INFO  ClusterOperator:96 - Opened watch for KafkaConnect operator
2019-12-04 14:32:31 INFO  ClusterOperator:96 - Opened watch for KafkaBridge operator
2019-12-04 14:32:31 INFO  ClusterOperator:96 - Opened watch for KafkaConnectS2I operator
2019-12-04 14:32:31 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) [com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@68c23b76 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1f390387[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:314)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:221)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-12-04 14:32:31 ERROR Main:127 - Cluster Operator verticle in namespace es failed to start
io.fabric8.kubernetes.client.KubernetesClientException: 404 page not found

	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:206) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571) ~[com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198) ~[com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) ~[com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:135) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
		at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:350) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:759) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:738) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:69) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
		at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watchInNamespace(AbstractWatchableResourceOperator.java:46) ~[io.strimzi.operator-common-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
		at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResourceOperator.java:53) ~[io.strimzi.operator-common-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
		at io.strimzi.operator.cluster.operator.assembly.AbstractConnectOperator.lambda$createConnectorWatch$2(AbstractConnectOperator.java:137) ~[io.strimzi.cluster-operator-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
		at io.strimzi.operator.common.Util.lambda$async$0(Util.java:30) ~[io.strimzi.operator-common-0.16.0-SNAPSHOT.jar:0.16.0-SNAPSHOT]
		at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
		at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Additional context**
This has been affecting the install since the 28th Nov, and I belive this commit may be what is causing the problem: https://github.com/strimzi/strimzi-kafka-operator/commit/339a278b6aff001466efb3b1dbdf98d1488d5a23.

**Comment by scholzj** [comment]
Thanks for reporting this. I guess this is related to #2273. I'm going to merge it today to fix it. For the rexcord, you seem to be using the master version of Strimzi, which is always a bit work in progress.

**Comment by scholzj** [comment]
I merged the PR. Could you please recheck if it is solved? (You would need to get the latest master and install the Helm Chart again, as the bug was in the Helm Chart it self). Thanks.

**Comment by AndyDunnings** [comment]
@scholzj your commit fixes the issue, thank you
