### ISSUE TITLE
Kafka operator error: No image for version 2.3.1

### ISSUE THREAD

**Issue by hreidar** [strimzi/strimzi-kafka-operator#2292]
**Describe the bug**
My operator started crashing with the following error:
```Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.3.1```

**To Reproduce**
Not sure, I have upgraded two times without any problems but noticed this behavior just now 

**Expected behavior**
For everything to run smooth :-)

**Environment (please complete the following information):**
 - Strimzi version: master, 0.15.0
 - Installation method: Edited YAML files from Strimzi repo
 - Kubernetes cluster: Kubernetes v1.15.4
 - Infrastructure: vSphere

**YAML files and logs**
```kubectl get kafka -n strimzi-kafka -oyaml
apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1beta1","kind":"Kafka","metadata":{"annotations":{},"name":"virkir","namespace":"strimzi-kafka"},"spec":{"entityOperator":{"topicOperator":{},"userOperator":{}},"kafka":{"config":{"log.message.format.version":"2.1","offsets.topic.replication.factor":3,"transaction.state.log.min.isr":2,"transaction.state.log.replication.factor":3},"listeners":{"external":{"tls":false,"type":"nodeport"}},"metrics":{"lowercaseOutputName":true,"rules":[{"labels":{"clientId":"$3","partition":"$5","topic":"$4"},"name":"kafka_server_$1_$2","pattern":"kafka.server\u003ctype=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)\u003e\u003c\u003eValue","type":"GAUGE"},{"labels":{"broker":"$4:$5","clientId":"$3"},"name":"kafka_server_$1_$2","pattern":"kafka.server\u003ctype=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)\u003e\u003c\u003eValue","type":"GAUGE"},{"name":"kafka_$1_$2_$3_percent","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)Percent\\w*\u003e\u003c\u003eMeanRate","type":"GAUGE"},{"name":"kafka_$1_$2_$3_percent","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)Percent\\w*\u003e\u003c\u003eValue","type":"GAUGE"},{"labels":{"$4":"$5"},"name":"kafka_$1_$2_$3_percent","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)Percent\\w*, (.+)=(.+)\u003e\u003c\u003eValue","type":"GAUGE"},{"labels":{"$4":"$5","$6":"$7"},"name":"kafka_$1_$2_$3_total","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)PerSec\\w*, (.+)=(.+), (.+)=(.+)\u003e\u003c\u003eCount","type":"COUNTER"},{"labels":{"$4":"$5"},"name":"kafka_$1_$2_$3_total","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)PerSec\\w*, (.+)=(.+)\u003e\u003c\u003eCount","type":"COUNTER"},{"name":"kafka_$1_$2_$3_total","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)PerSec\\w*\u003e\u003c\u003eCount","type":"COUNTER"},{"labels":{"$4":"$5","$6":"$7"},"name":"kafka_$1_$2_$3","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+), (.+)=(.+), (.+)=(.+)\u003e\u003c\u003eValue","type":"GAUGE"},{"labels":{"$4":"$5"},"name":"kafka_$1_$2_$3","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+), (.+)=(.+)\u003e\u003c\u003eValue","type":"GAUGE"},{"name":"kafka_$1_$2_$3","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)\u003e\u003c\u003eValue","type":"GAUGE"},{"labels":{"$4":"$5","$6":"$7"},"name":"kafka_$1_$2_$3_count","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+), (.+)=(.+), (.+)=(.+)\u003e\u003c\u003eCount","type":"COUNTER"},{"labels":{"$4":"$5","$6":"$7","quantile":"0.$8"},"name":"kafka_$1_$2_$3","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+), (.+)=(.*), (.+)=(.+)\u003e\u003c\u003e(\\d+)thPercentile","type":"GAUGE"},{"labels":{"$4":"$5"},"name":"kafka_$1_$2_$3_count","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+), (.+)=(.+)\u003e\u003c\u003eCount","type":"COUNTER"},{"labels":{"$4":"$5","quantile":"0.$6"},"name":"kafka_$1_$2_$3","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+), (.+)=(.*)\u003e\u003c\u003e(\\d+)thPercentile","type":"GAUGE"},{"name":"kafka_$1_$2_$3_count","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)\u003e\u003c\u003eCount","type":"COUNTER"},{"labels":{"quantile":"0.$4"},"name":"kafka_$1_$2_$3","pattern":"kafka.(\\w+)\u003ctype=(.+), name=(.+)\u003e\u003c\u003e(\\d+)thPercentile","type":"GAUGE"}]},"replicas":3,"storage":{"class":"local-storage","deleteClaim":false,"size":"100Gi","type":"persistent-claim"},"version":"2.1.1"},"zookeeper":{"metrics":{"lowercaseOutputName":true,"rules":[{"name":"zookeeper_$2","pattern":"org.apache.ZooKeeperService\u003cname0=ReplicatedServer_id(\\d+)\u003e\u003c\u003e(\\w+)"},{"labels":{"replicaId":"$2"},"name":"zookeeper_$3","pattern":"org.apache.ZooKeeperService\u003cname0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)\u003e\u003c\u003e(\\w+)"},{"labels":{"memberType":"$3","replicaId":"$2"},"name":"zookeeper_$4","pattern":"org.apache.ZooKeeperService\u003cname0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)\u003e\u003c\u003e(\\w+)"},{"labels":{"memberType":"$3","replicaId":"$2"},"name":"zookeeper_$4_$5","pattern":"org.apache.ZooKeeperService\u003cname0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)\u003e\u003c\u003e(\\w+)"},{"name":"zookeeper_$2","pattern":"org.apache.ZooKeeperService\u003cname0=StandaloneServer_port(\\d+)\u003e\u003c\u003e(\\w+)"},{"name":"zookeeper_$2_$3","pattern":"org.apache.ZooKeeperService\u003cname0=StandaloneServer_port(\\d+), name1=(InMemoryDataTree)\u003e\u003c\u003e(\\w+)"}]},"replicas":3,"storage":{"class":"local-storage","deleteClaim":false,"size":"50Gi","type":"persistent-claim"}}}}
    creationTimestamp: "2019-04-10T08:30:15Z"
    generation: 12
    name: virkir
    namespace: strimzi-kafka
    resourceVersion: "46543944"
    selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/strimzi-kafka/kafkas/virkir
    uid: ddb35a23-5b6a-11e9-9a2a-0050569c885f
  spec:
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      config:
        default.replication.factor: 3
        log.message.format.version: "2.3"
        offsets.topic.replication.factor: 3
        transaction.state.log.min.isr: 2
        transaction.state.log.replication.factor: 3
      listeners:
        external:
          tls: false
          type: nodeport
      metrics:
        lowercaseOutputName: true
        rules:
        - labels:
            clientId: $3
            partition: $5
            topic: $4
          name: kafka_server_$1_$2
          pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
          type: GAUGE
        - labels:
            broker: $4:$5
            clientId: $3
          name: kafka_server_$1_$2
          pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+),
            brokerPort=(.+)><>Value
          type: GAUGE
        - name: kafka_$1_$2_$3_percent
          pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate
          type: GAUGE
        - name: kafka_$1_$2_$3_percent
          pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_percent
          pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value
          type: GAUGE
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3_total
          pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+), (.+)=(.+)><>Count
          type: COUNTER
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_total
          pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count
          type: COUNTER
        - name: kafka_$1_$2_$3_total
          pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
          type: COUNTER
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3
          pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3
          pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value
          type: GAUGE
        - name: kafka_$1_$2_$3
          pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
          type: GAUGE
        - labels:
            $4: $5
            $6: $7
          name: kafka_$1_$2_$3_count
          pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count
          type: COUNTER
        - labels:
            $4: $5
            $6: $7
            quantile: 0.$8
          name: kafka_$1_$2_$3
          pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*), (.+)=(.+)><>(\d+)thPercentile
          type: GAUGE
        - labels:
            $4: $5
          name: kafka_$1_$2_$3_count
          pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count
          type: COUNTER
        - labels:
            $4: $5
            quantile: 0.$6
          name: kafka_$1_$2_$3
          pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile
          type: GAUGE
        - name: kafka_$1_$2_$3_count
          pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
          type: COUNTER
        - labels:
            quantile: 0.$4
          name: kafka_$1_$2_$3
          pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
          type: GAUGE
      replicas: 3
      storage:
        class: local-storage
        deleteClaim: false
        size: 100Gi
        type: persistent-claim
      version: 2.3.0
    zookeeper:
      metrics:
        lowercaseOutputName: true
        rules:
        - name: zookeeper_$2
          pattern: org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+)><>(\w+)
        - labels:
            replicaId: $2
          name: zookeeper_$3
          pattern: org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+), name1=replica.(\d+)><>(\w+)
        - labels:
            memberType: $3
            replicaId: $2
          name: zookeeper_$4
          pattern: org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+), name1=replica.(\d+),
            name2=(\w+)><>(\w+)
        - labels:
            memberType: $3
            replicaId: $2
          name: zookeeper_$4_$5
          pattern: org.apache.ZooKeeperService<name0=ReplicatedServer_id(\d+), name1=replica.(\d+),
            name2=(\w+), name3=(\w+)><>(\w+)
        - name: zookeeper_$2
          pattern: org.apache.ZooKeeperService<name0=StandaloneServer_port(\d+)><>(\w+)
        - name: zookeeper_$2_$3
          pattern: org.apache.ZooKeeperService<name0=StandaloneServer_port(\d+), name1=(InMemoryDataTree)><>(\w+)
      replicas: 3
      storage:
        class: local-storage
        deleteClaim: false
        size: 50Gi
        type: persistent-claim
  status:
    conditions:
    - lastTransitionTime: 2019-12-03T13:33:03+0000
      status: "True"
      type: Ready
    listeners:
    - addresses:
      - host: <AnyNodeAddress>
        port: 30529
      type: external
    observedGeneration: 12
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""


kubectl get pods -n strimzi-kafka strimzi-cluster-operator-7b86b58555-dl99v
NAME                                        READY   STATUS             RESTARTS   AGE
strimzi-cluster-operator-7b86b58555-dl99v   0/1     CrashLoopBackOff   441        60d


kubectl logs -f strimzi-cluster-operator-7b86b58555-dl99v -n strimzi-kafka
+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
++ get_heap_size
+++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
++ CONTAINER_MEMORY_IN_BYTES=268435456
++ DEFAULT_MEMORY_CEILING=32505856
++ '[' 268435456 -lt 32505856 ']'
+ MAX_HEAP=
+ '[' -n '' ']'
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.16.0-SNAPSHOT.jar:lib/io.netty.netty-codec-dns-4.1.34.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.jar:lib/org.keycloak.keycloak-core-7.0.0.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.jar:lib/org.quartz-scheduler.quartz-2.2.1.jar:lib/io.strimzi.crd-annotations-0.16.0-SNAPSHOT.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.vertx.vertx-core-3.7.1.jar:lib/io.strimzi.operator-common-0.16.0-SNAPSHOT.jar:lib/io.netty.netty-handler-proxy-4.1.34.Final.jar:lib/org.junit.platform.junit-platform-engine-1.5.1.jar:lib/io.netty.netty-transport-4.1.34.Final.jar:lib/org.opentest4j.opentest4j-1.2.0.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.9.10.jar:lib/com.fasterxml.jackson.core.jackson-core-2.9.10.jar:lib/org.keycloak.keycloak-common-7.0.0.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.9.10.1.jar:lib/io.fabric8.kubernetes-model-common-4.6.2.jar:lib/io.strimzi.config-model-0.16.0-SNAPSHOT.jar:lib/io.netty.netty-codec-socks-4.1.34.Final.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.9.10.jar:lib/io.netty.netty-resolver-4.1.34.Final.jar:lib/io.netty.netty-codec-4.1.34.Final.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.jar:lib/io.fabric8.kubernetes-client-4.6.2.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.kafka-oauth-client-0.1.0.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.jar:lib/org.apache.kafka.kafka-clients-2.3.1.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/org.junit.platform.junit-platform-launcher-1.5.1.jar:lib/io.strimzi.certificate-manager-0.16.0-SNAPSHOT.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.jar:lib/io.strimzi.kafka-oauth-common-0.1.0.jar:lib/io.fabric8.kubernetes-model-4.6.2.jar:lib/org.junit.jupiter.junit-jupiter-engine-5.5.1.jar:lib/io.strimzi.api-0.16.0-SNAPSHOT.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/com.github.luben.zstd-jni-1.4.0-1.jar:lib/io.netty.netty-handler-4.1.34.Final.jar:lib/io.netty.netty-resolver-dns-4.1.34.Final.jar:lib/org.apiguardian.apiguardian-api-1.1.0.jar:lib/io.fabric8.openshift-client-4.6.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.netty.netty-buffer-4.1.34.Final.jar:lib/io.netty.netty-codec-http-4.1.34.Final.jar:lib/io.strimzi.kafka-oauth-server-0.1.0.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/io.netty.netty-common-4.1.34.Final.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/io.netty.netty-codec-http2-4.1.34.Final.jar:lib/org.junit.platform.junit-platform-commons-1.5.1.jar:lib/org.yaml.snakeyaml-1.23.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.9.10.jar io.strimzi.operator.cluster.Main
2019-12-09 13:49:45 INFO  Main:51 - ClusterOperator 0.16.0-SNAPSHOT is starting
Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.3.1
        at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:202)
        at io.strimzi.operator.cluster.ClusterOperatorConfig.fromMap(ClusterOperatorConfig.java:94)
        at io.strimzi.operator.cluster.Main.main(Main.java:52)
Caused by: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.3.1
        at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.image(KafkaVersion.java:150)
        at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.validateKafkaImages(KafkaVersion.java:182)
        at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:197)
        ... 2 more
```

**Additional context**
My Kafka cluster is running without problems

**Comment by scholzj** [comment]
Could you please share the YAML of your Cluster operator deployment? (`kubectl get deployment strimzi-cluster-operator -o yaml`)

**Comment by hreidar** [comment]
Yes, sure, forgot that one

```
kubectl get deployment strimzi-cluster-operator -o yaml -n strimzi-kafka
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"strimzi"},"name":"strimzi-cluster-operator","namespace":"strimzi-kafka"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"name":"strimzi-cluster-operator","strimzi.io/kind":"cluster-operator"}},"spec":{"containers":[{"args":["/opt/strimzi/bin/cluster_operator_run.sh"],"env":[{"name":"STRIMZI_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"STRIMZI_FULL_RECONCILIATION_INTERVAL_MS","value":"120000"},{"name":"STRIMZI_OPERATION_TIMEOUT_MS","value":"300000"},{"name":"STRIMZI_DEFAULT_ZOOKEEPER_IMAGE","value":"strimzi/kafka:latest-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE","value":"strimzi/kafka:latest-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE","value":"strimzi/kafka:latest-kafka-2.3.0"},{"name":"STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE","value":"strimzi/kafka:latest-kafka-2.3.0"},{"name":"STRIMZI_KAFKA_IMAGES","value":"2.1.0=strimzi/kafka:latest-kafka-2.1.0\n2.1.1=strimzi/kafka:latest-kafka-2.1.1\n2.2.0=strimzi/kafka:latest-kafka-2.2.0\n2.2.1=strimzi/kafka:latest-kafka-2.2.1\n2.3.0=strimzi/kafka:latest-kafka-2.3.0\n"},{"name":"STRIMZI_KAFKA_CONNECT_IMAGES","value":"2.1.0=strimzi/kafka:latest-kafka-2.1.0\n2.1.1=strimzi/kafka:latest-kafka-2.1.1\n2.2.0=strimzi/kafka:latest-kafka-2.2.0\n2.2.1=strimzi/kafka:latest-kafka-2.2.1\n2.3.0=strimzi/kafka:latest-kafka-2.3.0\n"},{"name":"STRIMZI_KAFKA_CONNECT_S2I_IMAGES","value":"2.1.0=strimzi/kafka:latest-kafka-2.1.0\n2.1.1=strimzi/kafka:latest-kafka-2.1.1\n2.2.0=strimzi/kafka:latest-kafka-2.2.0\n2.2.1=strimzi/kafka:latest-kafka-2.2.1\n2.3.0=strimzi/kafka:latest-kafka-2.3.0\n"},{"name":"STRIMZI_KAFKA_MIRROR_MAKER_IMAGES","value":"2.1.0=strimzi/kafka:latest-kafka-2.1.0\n2.1.1=strimzi/kafka:latest-kafka-2.1.1\n2.2.0=strimzi/kafka:latest-kafka-2.2.0\n2.2.1=strimzi/kafka:latest-kafka-2.2.1\n2.3.0=strimzi/kafka:latest-kafka-2.3.0\n"},{"name":"STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE","value":"strimzi/operator:latest"},{"name":"STRIMZI_DEFAULT_USER_OPERATOR_IMAGE","value":"strimzi/operator:latest"},{"name":"STRIMZI_DEFAULT_KAFKA_INIT_IMAGE","value":"strimzi/operator:latest"},{"name":"STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE","value":"strimzi/kafka-bridge:latest"},{"name":"STRIMZI_LOG_LEVEL","value":"INFO"}],"image":"strimzi/operator:latest","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthy","port":8080},"initialDelaySeconds":10,"periodSeconds":30},"name":"strimzi-cluster-operator","readinessProbe":{"httpGet":{"path":"/ready","port":8080},"initialDelaySeconds":10,"periodSeconds":30},"resources":{"limits":{"cpu":"1000m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"256Mi"}}}],"serviceAccountName":"strimzi-cluster-operator"}}}}
  creationTimestamp: "2019-04-09T10:38:16Z"
  generation: 2
  labels:
    app: strimzi
  name: strimzi-cluster-operator
  namespace: strimzi-kafka
  resourceVersion: "47653696"
  selfLink: /apis/extensions/v1beta1/namespaces/strimzi-kafka/deployments/strimzi-cluster-operator
  uid: 958ddd1e-5ab3-11e9-bafd-0050569cdf25
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      containers:
      - args:
        - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
          value: strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          value: strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE
          value: strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.1.0=strimzi/kafka:latest-kafka-2.1.0
            2.1.1=strimzi/kafka:latest-kafka-2.1.1
            2.2.0=strimzi/kafka:latest-kafka-2.2.0
            2.2.1=strimzi/kafka:latest-kafka-2.2.1
            2.3.0=strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_KAFKA_CONNECT_IMAGES
          value: |
            2.1.0=strimzi/kafka:latest-kafka-2.1.0
            2.1.1=strimzi/kafka:latest-kafka-2.1.1
            2.2.0=strimzi/kafka:latest-kafka-2.2.0
            2.2.1=strimzi/kafka:latest-kafka-2.2.1
            2.3.0=strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.1.0=strimzi/kafka:latest-kafka-2.1.0
            2.1.1=strimzi/kafka:latest-kafka-2.1.1
            2.2.0=strimzi/kafka:latest-kafka-2.2.0
            2.2.1=strimzi/kafka:latest-kafka-2.2.1
            2.3.0=strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.1.0=strimzi/kafka:latest-kafka-2.1.0
            2.1.1=strimzi/kafka:latest-kafka-2.1.1
            2.2.0=strimzi/kafka:latest-kafka-2.2.0
            2.2.1=strimzi/kafka:latest-kafka-2.2.1
            2.3.0=strimzi/kafka:latest-kafka-2.3.0
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
          value: strimzi/kafka-bridge:latest
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        image: strimzi/operator:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthy
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: strimzi-cluster-operator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: strimzi-cluster-operator
      serviceAccountName: strimzi-cluster-operator
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-12-08T00:14:32Z"
    lastUpdateTime: "2019-12-08T00:14:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

**Comment by scholzj** [comment]
It looks like your operator is not 0.15.0 but was installed from `master` branch some time ago. 
* If you want to use 0.15.0, you should use the installation files from here: https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.15.0
* If you want to use the master version (possibly bugy and less stable), you can just pull the lastest from GitHub and update the deployment by `kubectl apply -f install/cluster-operator`.

**Comment by hreidar** [comment]
Thank you for the info @scholzj. I thought I followed the steps in the docs but maybe I have missed something. How did you see which version of Strimzi I'm running?

**Comment by scholzj** [comment]
The `:latest` tag in our case actually points to master - the latest stable uses always the version numbers. So seeing images like `strimzi/operator:latest` or `strimzi/kafka:latest-kafka-2.3.0` suggests that. Also, in  the 0.15.0 version or in latest master, the environemnt variables are different. E.g.:

```yaml
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.2.1=strimzi/kafka:latest-kafka-2.2.1
            2.3.0=strimzi/kafka:latest-kafka-2.3.0
            2.3.1=strimzi/kafka:latest-kafka-2.3.1
```

or

```yaml
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.2.1=strimzi/kafka:0.15.0-kafka-2.2.1
            2.3.0=strimzi/kafka:0.15.0-kafka-2.3.0
            2.3.1=strimzi/kafka:0.15.0-kafka-2.3.1
```

This is what caused the actual error you have.

**Comment by hreidar** [comment]
Thanks, it seems a little bit confusing but I will figure it out. Thank you for your time and help.
