### ISSUE TITLE
How to check the status of kafka cluster? How to debug Filesystem issues and Kafka port issues?

### ISSUE THREAD

**Issue by adityacs** [strimzi/strimzi-kafka-operator#2380]
I have deployed the Kafka cluster using below configuration. However, cluster is not coming up. How can I check the status of the cluster and what is the error for cluster not coming up?

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    version: 2.3.1
    replicas: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
    storage:
      type: persistent-claim
      size: 20Gi
      class: $custom-class-name
      deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      class: $custom-class-name
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

Thanks

**Comment by scholzj** [comment]
If the cluster operator doesn't manage to deploy the cluster, it will after some time (5 minutes by default) add some status to the custom resource. But in general, the fastest way would be to have a look into the log of the cluster operator and try to share it here - it should give some more insitghs. 

The Kafka CR here looks good assuming the `$custom-class-name` is replaced for some actual name of the class before it is deployed. I do not see any other obvious issues.

**Comment by adityacs** [comment]
@scholzj Cluster operator logs is not giving me any error.
```
+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
++ get_heap_size
+++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
++ CONTAINER_MEMORY_IN_BYTES=268435456
++ DEFAULT_MEMORY_CEILING=32505856
++ '[' 268435456 -lt 32505856 ']'
+ MAX_HEAP=
+ '[' -n '' ']'
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.15.0.jar:lib/io.netty.netty-codec-dns-4.1.34.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.jar:lib/org.keycloak.keycloak-core-7.0.0.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.jar:lib/org.quartz-scheduler.quartz-2.2.1.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.vertx.vertx-core-3.7.1.jar:lib/io.netty.netty-handler-proxy-4.1.34.Final.jar:lib/org.junit.platform.junit-platform-engine-1.5.1.jar:lib/io.strimzi.operator-common-0.15.0.jar:lib/io.netty.netty-transport-4.1.34.Final.jar:lib/org.opentest4j.opentest4j-1.2.0.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.9.10.jar:lib/com.fasterxml.jackson.core.jackson-core-2.9.10.jar:lib/io.strimzi.api-0.15.0.jar:lib/org.keycloak.keycloak-common-7.0.0.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.9.10.1.jar:lib/io.fabric8.kubernetes-model-common-4.6.2.jar:lib/io.netty.netty-codec-socks-4.1.34.Final.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.9.10.jar:lib/io.netty.netty-resolver-4.1.34.Final.jar:lib/io.netty.netty-codec-4.1.34.Final.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.jar:lib/io.fabric8.kubernetes-client-4.6.2.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.config-model-0.15.0.jar:lib/io.strimzi.kafka-oauth-client-0.1.0.jar:lib/io.strimzi.crd-annotations-0.15.0.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.jar:lib/org.apache.kafka.kafka-clients-2.3.1.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/org.junit.platform.junit-platform-launcher-1.5.1.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.jar:lib/io.strimzi.kafka-oauth-common-0.1.0.jar:lib/io.fabric8.kubernetes-model-4.6.2.jar:lib/org.junit.jupiter.junit-jupiter-engine-5.5.1.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/com.github.luben.zstd-jni-1.4.0-1.jar:lib/io.netty.netty-handler-4.1.34.Final.jar:lib/io.netty.netty-resolver-dns-4.1.34.Final.jar:lib/org.apiguardian.apiguardian-api-1.1.0.jar:lib/io.fabric8.openshift-client-4.6.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.netty.netty-buffer-4.1.34.Final.jar:lib/io.netty.netty-codec-http-4.1.34.Final.jar:lib/io.strimzi.kafka-oauth-server-0.1.0.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/io.netty.netty-common-4.1.34.Final.jar:lib/io.strimzi.certificate-manager-0.15.0.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/io.netty.netty-codec-http2-4.1.34.Final.jar:lib/org.junit.platform.junit-platform-commons-1.5.1.jar:lib/org.yaml.snakeyaml-1.23.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.9.10.jar io.strimzi.operator.cluster.Main
2020-01-09 12:56:08 INFO  Main:51 - ClusterOperator 0.15.0 is starting
2020-01-09 12:56:09 INFO  Main:60 - Environment facts gathered: ClusterOperatorConfig(KubernetesVersion=1.11,OpenShiftRoutes=true,OpenShiftBuilds=true,OpenShiftImageStreams=true,OpenShiftDeploymentConfigs=true)
2020-01-09 12:56:09 INFO  Main:189 - Using config:
	STRIMZI_DEFAULT_ZOOKEEPER_IMAGE: strimzi/kafka:0.15.0-kafka-2.3.1
	PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
	STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE: strimzi/kafka-bridge:0.15.0
	KUBERNETES_PORT_53_UDP_PROTO: udp
	KUBERNETES_PORT_53_UDP_ADDR: 172.21.0.1
	KUBERNETES_PORT_53_TCP: tcp://172.21.0.1:53
	STRIMZI_KAFKA_MIRROR_MAKER_IMAGES: 2.2.1=strimzi/kafka:0.15.0-kafka-2.2.1
2.3.0=strimzi/kafka:0.15.0-kafka-2.3.0
2.3.1= strimzi/kafka:0.15.0-kafka-2.3.1

	KUBERNETES_PORT: tcp://172.21.0.1:443
	KUBERNETES_PORT_53_TCP_PROTO: tcp
	STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE: strimzi/operator:0.15.0
	TERM: xterm
	STRIMZI_FULL_RECONCILIATION_INTERVAL_MS: 120000
	KUBERNETES_SERVICE_HOST: 172.21.0.1
	JAVA_CLASSPATH: lib/io.strimzi.cluster-operator-0.15.0.jar:lib/io.netty.netty-codec-dns-4.1.34.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.jar:lib/org.keycloak.keycloak-core-7.0.0.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.jar:lib/org.quartz-scheduler.quartz-2.2.1.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.vertx.vertx-core-3.7.1.jar:lib/io.netty.netty-handler-proxy-4.1.34.Final.jar:lib/org.junit.platform.junit-platform-engine-1.5.1.jar:lib/io.strimzi.operator-common-0.15.0.jar:lib/io.netty.netty-transport-4.1.34.Final.jar:lib/org.opentest4j.opentest4j-1.2.0.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.9.10.jar:lib/com.fasterxml.jackson.core.jackson-core-2.9.10.jar:lib/io.strimzi.api-0.15.0.jar:lib/org.keycloak.keycloak-common-7.0.0.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.9.10.1.jar:lib/io.fabric8.kubernetes-model-common-4.6.2.jar:lib/io.netty.netty-codec-socks-4.1.34.Final.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.9.10.jar:lib/io.netty.netty-resolver-4.1.34.Final.jar:lib/io.netty.netty-codec-4.1.34.Final.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.jar:lib/io.fabric8.kubernetes-client-4.6.2.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.config-model-0.15.0.jar:lib/io.strimzi.kafka-oauth-client-0.1.0.jar:lib/io.strimzi.crd-annotations-0.15.0.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.jar:lib/org.apache.kafka.kafka-clients-2.3.1.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/org.junit.platform.junit-platform-launcher-1.5.1.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.jar:lib/io.strimzi.kafka-oauth-common-0.1.0.jar:lib/io.fabric8.kubernetes-model-4.6.2.jar:lib/org.junit.jupiter.junit-jupiter-engine-5.5.1.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/com.github.luben.zstd-jni-1.4.0-1.jar:lib/io.netty.netty-handler-4.1.34.Final.jar:lib/io.netty.netty-resolver-dns-4.1.34.Final.jar:lib/org.apiguardian.apiguardian-api-1.1.0.jar:lib/io.fabric8.openshift-client-4.6.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.netty.netty-buffer-4.1.34.Final.jar:lib/io.netty.netty-codec-http-4.1.34.Final.jar:lib/io.strimzi.kafka-oauth-server-0.1.0.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/io.netty.netty-common-4.1.34.Final.jar:lib/io.strimzi.certificate-manager-0.15.0.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/io.netty.netty-codec-http2-4.1.34.Final.jar:lib/org.junit.platform.junit-platform-commons-1.5.1.jar:lib/org.yaml.snakeyaml-1.23.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.9.10.jar
	KUBERNETES_PORT_53_UDP_PORT: 53
	STRIMZI_KAFKA_CONNECT_S2I_IMAGES: 2.2.1=strimzi/kafka:0.15.0-kafka-2.2.1
2.3.0=strimzi/kafka:0.15.0-kafka-2.3.0
2.3.1=strimzi/kafka:0.15.0-kafka-2.3.1

	STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE: strimzi/kafka:0.15.0-kafka-2.3.1
	KUBERNETES_SERVICE_PORT_DNS: 53
	STRIMZI_HOME: /opt/strimzi
	PWD: /opt/strimzi
	KUBERNETES_PORT_443_TCP: tcp://172.21.0.1:443
	STRIMZI_OPERATION_TIMEOUT_MS: 300000
	JAVA_MAIN: io.strimzi.operator.cluster.Main
	KUBERNETES_PORT_443_TCP_ADDR: 172.21.0.1
	STRIMZI_VERSION: 0.15.0
	KUBERNETES_PORT_53_UDP: udp://172.21.0.1:53
	STRIMZI_NAMESPACE: kafka
	KUBERNETES_PORT_443_TCP_PROTO: tcp
	KUBERNETES_PORT_53_TCP_ADDR: 172.21.0.1
	STRIMZI_DEFAULT_USER_OPERATOR_IMAGE: strimzi/operator:0.15.0
	KUBERNETES_SERVICE_PORT: 443
	STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE: strimzi/kafka:0.15.0-kafka-2.3.1
	STRIMZI_DEFAULT_KAFKA_INIT_IMAGE: strimzi/operator:0.15.0
	STRIMZI_LOG_LEVEL: INFO
	KUBERNETES_PORT_53_TCP_PORT: 53
	HOSTNAME: strimzi-cluster-operator-68cfddcf4-wsjkj
	STRIMZI_KAFKA_CONNECT_IMAGES: 2.2.1=strimzi/kafka:0.15.0-kafka-2.2.1
2.3.0=strimzi/kafka:0.15.0-kafka-2.3.0
2.3.1=trimzi/kafka:0.15.0-kafka-2.3.1

	KUBERNETES_SERVICE_PORT_DNS_TCP: 53
	STRIMZI_KAFKA_IMAGES: 2.2.1=strimzi/kafka:0.15.0-kafka-2.2.1
2.3.0=strimzi/kafka:0.15.0-kafka-2.3.0
2.3.1=strimzi/kafka:0.15.0-kafka-2.3.1

	KUBERNETES_PORT_443_TCP_PORT: 443
	STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE: strimzi/kafka:0.15.0-kafka-2.3.1
	KUBERNETES_SERVICE_PORT_HTTPS: 443
	SHLVL: 0
	HOME: /
	STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE: strimzi/kafka:0.15.0-kafka-2.3.1
	MALLOC_ARENA_MAX: 2

2020-01-09 12:56:09 INFO  ClusterOperator:62 - Creating ClusterOperator for namespace kafka
2020-01-09 12:56:09 INFO  ClusterOperator:75 - Starting ClusterOperator for namespace kafka
2020-01-09 12:56:09 INFO  ClusterOperator:82 - Started operator for Kafka kind
2020-01-09 12:56:10 INFO  ClusterOperator:86 - Started operator for KafkaMirrorMaker kind
2020-01-09 12:56:10 INFO  ClusterOperator:90 - Started operator for KafkaConnect kind
2020-01-09 12:56:10 INFO  ClusterOperator:100 - Started operator for KafkaConnectS2I kind
2020-01-09 12:56:10 INFO  ClusterOperator:105 - Started operator for KafkaBridge kind
2020-01-09 12:56:10 INFO  ClusterOperator:107 - Setting up periodic reconciliation for namespace kafka
2020-01-09 12:56:10 INFO  ClusterOperator:163 - ClusterOperator is now ready (health server listening on 8080)
2020-01-09 12:56:10 INFO  Main:125 - Cluster Operator verticle started in namespace kafka
2020-01-09 12:58:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-09 12:58:10 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta1'
2020-01-09 12:58:10 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormakers' with unstable version 'v1beta1'
2020-01-09 12:58:10 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaconnects' with unstable version 'v1beta1'
2020-01-09 12:58:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkabridges' with unstable version 'v1alpha1'
2020-01-09 12:58:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaconnects2is' with unstable version 'v1beta1'
2020-01-09 13:00:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-09 13:02:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-09 13:04:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-09 13:06:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-09 13:08:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-09 13:10:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace 

```

**Comment by adityacs** [comment]
Recent logs
```
2020-01-10 06:33:09 INFO  OperatorWatcher:39 - Reconciliation #0(watch) Kafka(kafka/my-kafka-cluster): Kafka my-kafka-cluster in namespace kafka was ADDED
2020-01-10 06:33:09 INFO  AbstractOperator:123 - Reconciliation #0(watch) Kafka(kafka/my-kafka-cluster): Kafka my-kafka-cluster should be created or updated
2020-01-10 06:33:10 INFO  ClusterOperator:109 - Triggering periodic reconciliation for namespace kafka...
2020-01-10 06:33:12 WARN  VersionUsageUtils:60 - The client is using resource type 'poddisruptionbudgets' with unstable version 'v1beta1'
2020-01-10 06:33:20 WARN  AbstractOperator:161 - Reconciliation #1(timer) Kafka(kafka/my-kafka-cluster): Failed to acquire lock lock::kafka::Kafka::my-kafka-cluster.
```

**Comment by scholzj** [comment]
The security context configuration is always specific for your cluster. It might be possible that some cluster policy blocks you from running the pod as root for example. Best would be to check the events on the StatefuSet if it was created for example.

**Comment by adityacs** [comment]
@scholzj No statefulset gets created when I give template configurations. Also, operator doesn't show any logs. How should I debug?

**Comment by scholzj** [comment]
That is a bit weird. I would expect the STS to be created. You can enable the debug log in the operator by setting the `STRIMZI_LOG_LEVEL` environment variable to `DEBUG` (in the cluster operator deployment). Let it run for few minutes and share the log. Maybe it would show something.

**Comment by adityacs** [comment]
@scholzj You were right. Statefulset is created. My problem is with `uid` and `gid`. My PV needs uid and gid of 1000:1000. Kafka cluster image has 1001:0. I can use initcontainer to own the PV volume to 1001:0. How can I add initcontainer configurations to Kafka cluster yaml?

**Comment by adityacs** [comment]
@scholzj Looking forward for your help here. Any way to change mount path of zookeper from `/var/lib/zookeeper/data` to other path? or any way to configure initcontainer args in kafka cluster yaml?

**Comment by scholzj** [comment]
Normally the fsGroup should tell Kubernetes which group should be allowed to use the storage. It is strange it is ignored in your environment. But maybe you can try to set the UID and GID to what you storage expects than?

```
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
```

Could you give it a try?

**Comment by adityacs** [comment]
@scholzj Below is my storage permission.
```
drwxr-xr-x. 2 nobody nobody 4096 Jan 14 11:33 zookeeper
```
I have tried setting below two options both doesn't work for me. 

```
securityContext:
    runAsUser: 1000
    runAsGroup: 1000
```

also

``` 
securityContext:
   fsGroup: 0
```

Strange thing is when try outside of operator with just statefulset it works fine for me with just `fsGroup: 0`. Below will be storage permissions
```
drwxr-xr-x. 2 kafka nobody 4096 Jan 14 10:57 zookeeper
```

**Comment by scholzj** [comment]
That is weird. I never saw it before. What kind of storahe is that? I think NFS has often nobody in the permissions. NFS doesn't work well with Kafka.

In general, I think you should try to find out whether the `nobody` has some user ID and if it does try to run under it. Another alternative might be to try `runAsUser: 0` to run as root. But I cannot test this since I do not have your environment with the same storage issue.So you have to give it a try if it helps.

**Comment by adityacs** [comment]
@scholzj We can do something like this
```
initContainers:
- name: initcontainer # Or replace the name
  image: alpine:latest
  command: ["/bin/sh", "-c"]
  args:
    - chown <UID>:<GID> /mount; # Replace UID and GID with values from the Dockerfile
  volumeMounts:
  - name: volume # Or you can replace with any name
    mountPath: /mount # Must match the mount path in the args line
```

Is there a way I can configure initContainers in kafka cluster yaml?

**Comment by scholzj** [comment]
No, I'm afraid Strimzi doesn't support configuring custom init containers.

**Comment by adityacs** [comment]
@scholzj It would be good if we can support that. Also, after setting `runAsUser: 0` it worked for me. It solves my problem for now. However, we don't want to run as root. I will debug more on this with the PV I am using

Thanks for the help

**Comment by adityacs** [comment]
@scholzj One more query. `kafka-cluster-kafka-brokers` gives me 
```
nslookup kafka-cluster-kafka-brokers  
Server:		172.20.0.1
Address:	172.20.0.1#53

Name:	kafka-cluster-kafka-brokers.kafka.svc.cluster.local
Address: 172.30.228.99
Name:	kafka-cluster-kafka-brokers.kafka.svc.cluster.local
Address: 172.30.59.231
Name:	kafka-cluster-kafka-brokers.kafka.svc.cluster.local
Address: 172.30.69.75
```

It has to give me 
```
kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc.cluster.local
kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local
kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local
```

When I use `./kafka-console-producer.sh --broker-list kafka-cluster-kafka-brokers:9092  --topic my-topic` it gives me `leader not available error`

When I use `./kafka-console-producer.sh --broker-list kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092,kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092 --topic my-topic`. I can produce and consume messages

**Comment by scholzj** [comment]
No, the DNS is correct. I do not think there is any service in Kubernetes that works like you want. The service `kafka-cluster-kafka-brokers` is headless and that normally resolves as the nslookup listed it. (which in either case is Kubernetes thing, not Strimzi thing so I cannot change much about it). 

AFAIK clients normally don't have problems with using `kafka-cluster-kafka-brokers`. But to be honest I normally recommend clients to use `kafka-cluster-kafka-bootstrap` service as the bootstrap service. This service is ClusterIP type and resolves differently.

**Comment by adityacs** [comment]
@scholzj Got you. 
I intermittently see this issue
```
./kafka-console-producer.sh --broker-list kafka-cluster-kafka-bootstrap:9092 --topic my-topic
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
>dasd
[2020-01-22 09:09:03,131] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 5 : {my-topic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2020-01-22 09:09:03,238] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 6 : {my-topic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2020-01-22 09:09:03,351] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 7 : {my-topic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
```

Sometimes it doesn't say `leader_not_available` and sometimes it throws this warning

**Comment by scholzj** [comment]
I guess it depends whether it keeps going or whether it stops and starts working after a while. These messages are for example normal when the topic is being created only at the point the ocnsumer connects, because it might take some time to connect. But it really depends on a lot of conditions of the cluster etc.

**Comment by adityacs** [comment]
@scholzj The warning message keeps going. In my case topic was created before starting the consumer

**Comment by scholzj** [comment]
Ok. In that case, what are the broker logs showing? And what do you get when you list the topics? Do they show a leader for the topic?

**Comment by adityacs** [comment]
Nodes not able to communicate on 9091. 
```
root@kafka-cluster-kafka-1 kafka]# nc -vz kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local 9092
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 172.30.69.75:9092.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds
```

```
[root@kafka-cluster-kafka-1 kafka]# nc -vz kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local 9091
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connection timed out.
```

```
2020-01-23 14:18:23,751 WARN [ReplicaFetcher replicaId=0, leaderId=1, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=0, maxWait=500, minBytes=1, maxBytes=10485760, fetchData={my-replicated-topic-0=(fetchOffset=0, logStartOffset=0, maxBytes=1048576, currentLeaderEpoch=Optional[0])}, isolationLevel=READ_UNCOMMITTED, toForget=, metadata=(sessionId=INVALID, epoch=INITIAL)) (kafka.server.ReplicaFetcherThread) [ReplicaFetcherThread-0-1]
java.io.IOException: Connection to kafka-cluster-kafka-1.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9091 (id: 1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:95)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:193)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:280)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:131)
	at scala.Option.foreach(Option.scala:274)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:131)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:113)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
2020-01-23 14:18:29,382 WARN [Controller id=0, targetBrokerId=2] Connection to node 2 (kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local/172.30.69.75:9091) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient) [Controller-0-to-broker-2-send-thread]
2020-01-23 14:18:29,382 WARN [RequestSendThread controllerId=0] Controller 0's connection to broker kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9091 (id: 2 rack: ) was unsuccessful (kafka.controller.RequestSendThread) [Controller-0-to-broker-2-send-thread]
java.io.IOException: Connection to kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9091 (id: 2 rack: ) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:282)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:236)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
```

**Comment by scholzj** [comment]
What is the environment you are running it in? What version of Kubernetes? Does it use SDN with a network policy defaulting to deny? Does the Topic Operator and Uaer Oeprator seem to work? If now, do they show some different exception?

**Comment by adityacs** [comment]
@scholzj I am on Openshift. There is no default network policy. Below is the output of kafka-cluster-network-policy.

```
oc describe networkpolicy kafka-cluster-network-policy-kafka -n kafka
Name:         kafka-cluster-network-policy-kafka
Namespace:    kafka
Created on:   2020-01-21 07:45:49 +0000 UTC
Labels:       app.kubernetes.io/instance=kafka-cluster
              app.kubernetes.io/managed-by=strimzi-cluster-operator
              app.kubernetes.io/name=strimzi
              strimzi.io/cluster=kafka-cluster
              strimzi.io/kind=Kafka
Annotations:  <none>
Spec:
  PodSelector:     strimzi.io/name=kafka-cluster-kafka
  Allowing ingress traffic:
    To Port: 9092/TCP
    From: <any> (traffic not restricted by source)
    ----------
    To Port: 9093/TCP
    From: <any> (traffic not restricted by source)
    ----------
    To Port: 9094/TCP
    From: <any> (traffic not restricted by source)
  Allowing egress traffic:
    <none> (Selected pods are isolated for egress connectivity)
  Policy Types: Ingress
```

Even `9091` should be allowed right?

**Comment by adityacs** [comment]
@scholzj I added port `9091` to ingress rule. Everything is working fine for me now. Not sure why `9091` was not added. Bug?

**Comment by scholzj** [comment]
Are you OCP 3.11 by any chance? If yes, this should have the fix: https://github.com/strimzi/strimzi-kafka-operator/pull/2388.

**Comment by scholzj** [comment]
As a workaround until it is released, you can simply create your own policy opening the 9091 port.

**Comment by adityacs** [comment]
@scholzj Yes I am 3.11. Yeah, I modified the existing policy and opened 9091 port.

**Comment by adityacs** [comment]
@scholzj Finally Kafka cluster is working. Only thing I have to fix is the `fsGroup` thing. I will debug that separately. 
Thanks a ton for all your inputs. To be frank I troubled you a lot 😉. Your patience is appreciated.

**Comment by adityacs** [comment]
Since we discussed multiple things like Kafka logs, network policy , fsGroup etc.. I will change the issue title to something more relevant so that it would be helpful for other users.

**Comment by scholzj** [comment]
> Yeah, I modified the existing policy and opened 9091 port.

Be careful, if you modify it, the operator will overwirte it back. It might help temporarily because the connection will be established and will stay open. But next restart or something might stop working again. So you should create a separate policy for the 9091 until the 0.17 release with the fix.

If this is it, can we close the issue?

And sorry for all the issues you run into, usually the experience is more smooth :-(.

**Comment by adityacs** [comment]
@scholzj Yes the issue can be closed.
