### ISSUE TITLE
[Bug] Kafka Connect deployed in NotReady state (0.16.0)

### ISSUE THREAD

**Issue by lancerdima** [strimzi/strimzi-kafka-operator#2417]
**Describe the bug**
I am deploying a Kafka Connect instance, with a new Kafka Connector. I'am verifying deployment with Kafka Connect REST API interface (/connectors), and do not see any connectors in the Kafka Connect.

Inspecting Kafka Connect resource, it yields an interesting status:
```
status:
  conditions:
  - lastTransitionTime: "2020-01-17T13:43:41.276Z"
    message: 'failed to resolve ''kafka-connect-internal-cluster-connect-api'' after
      2 queries '
    reason: UnknownHostException
    status: "True"
    type: NotReady
  observedGeneration: 1
  url: http://kafka-connect-internal-cluster-connect-api.kafka-internal.svc:8083
```
I believe that this NotReady status, prevents deployment of the Connector, as the error message is the same.
Having a closer look at `url`, I see that URL (and the one probably used by operator) is FQDN with _kafka-internal.svc_ part.
I confirm that Kafka Connect REST API is working, as there is meaningful response from the API on url without FQDN (url is proxied to localhost from AKS):
`http://localhost:8001/api/v1/namespaces/kafka-internal/services/http:**kafka-connect-internal-cluster-connect-api:8083**/proxy/`
Attempting the same URL with FQDN indicate that resource is not reachable:
`http://localhost:8001/api/v1/namespaces/kafka-internal/services/http:**kafka-connect-internal-cluster-connect-api.kafka-internal.svc**:8083/proxy/`

**Expected behavior**
Kafka Connect should be deployed with Ready status.

**Environment (please complete the following information):**
 - Strimzi version: 0.16.0
 - Installation method: YAML
 - Kubernetes cluster: Azure AKS 1.15.7
 - Infrastructure: Azure AKS

**YAML files and logs**
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kafka-connect-internal-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.4.0
  replicas: 1
  bootstrapServers: kafka-internal-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-internal-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    plugin.path: /opt/kafka/plugins/
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
```

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: "true"
  creationTimestamp: "2020-01-17T13:42:34Z"
  generation: 1
  name: kafka-connect-internal-cluster
  namespace: kafka-internal
  resourceVersion: "1888754"
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/kafka-internal/kafkaconnects/kafka-connect-internal-cluster
  uid: 47c444ad-3aad-452e-9533-47d3bf37fd0d
spec:
  bootstrapServers: kafka-internal-cluster-kafka-bootstrap:9092
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    offset.storage.replication.factor: 1
    plugin.path: /opt/kafka/plugins/
    status.storage.replication.factor: 1
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: true
  externalConfiguration:
    volumes:
    - configMap:
        name: streaming-debezium-internal-config
      name: streaming-debezium-internal
  image: lancerdima.azurecr.io/strimzi-connect-debezium:latest-beta
  replicas: 1
status:
  conditions:
  - lastTransitionTime: "2020-01-17T13:43:41.276Z"
    message: 'failed to resolve ''kafka-connect-internal-cluster-connect-api'' after
      2 queries '
    reason: UnknownHostException
    status: "True"
    type: NotReady
  observedGeneration: 1
  url: http://kafka-connect-internal-cluster-connect-api.kafka-internal.svc:8083

```

**Additional context**

**Comment by scholzj** [comment]
I do not think the proxying works this way. In the URL you are entering a service name, not DNS name. The namespace part is already elsewhere in the URL. Some ideas what might cause this:

* Some strange DNS issue - but than it would probably cause also other problems to other apps.
* DNS caching (I would try to restart the cluster operator to see if it helps)
* A bug in the code - are you running the custer operator in the same namespace as the KafkaConnect cluster? I.e. both in `kafka-internal`?

**Comment by lancerdima** [comment]
* Restarting both operator and AKS worker nodes does not help.
* Operator and Kafka resources are being deployed to different namespaces. (additional instructions from deployment flow were executed: https://strimzi.io/docs/0.16.0/full.html#deploying-cluster-operator-to-watch-multiple-namespacesstr)

Here is a log snippet from the operator pod, after that there are just "failed to reconcile" error messages:
```
2020-01-17 15:46:03 ERROR AbstractOperator:124 - Reconciliation #5(watch) KafkaConnect(kafka-internal/kafka-connect-internal-cluster): createOrUpdate failed
java.net.UnknownHostException: failed to resolve 'kafka-connect-internal-cluster-connect-api' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:543) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:64) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:400) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:204) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:196) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1320) ~[io.netty.netty-resolver-dns-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[io.netty.netty-codec-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by scholzj** [comment]
Ok. I'm afraid this is a bug. It looks like we try to connect only to `kafka-connect-internal-cluster-connect-api` instead of `kafka-connect-internal-cluster-connect-api.<namespace>.svc` and that we cannot connect there when you run in different namespace. Sorry for that. I will have a look at a fix.
