### ISSUE TITLE
[Bug] Reconciliation loop for Cruise control topics (starting with a _ ) 

### ISSUE THREAD

**Issue by sebdoido** [strimzi/strimzi-kafka-operator#2451]
Currently running 0.15.0 version with kafka 2.3.1
i got this exception in pod `entity-operator` container `topic-operator` after deploying Cruisecontrol tool (from linkedIn : https://github.com/linkedin/cruise-control ) 

```
2020-01-24 16:15:06,803] INFO  <opicOperator:1134> [oop-thread-0] Starting periodic  reconciliation
[2020-01-24 16:15:06,832] INFO  <opicOperator:474> [oop-thread-0] 410|periodic -__KafkaCruiseControlPartitionMetricSamples: Reconciling topic __KafkaCruiseControlPartitionMetricSamples, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2020-01-24 16:15:06,833] INFO  <opicOperator:474> [oop-thread-0] 412|periodic -__CruiseControlMetrics: Reconciling topic __CruiseControlMetrics, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2020-01-24 16:15:06,837] INFO  <opicOperator:474> [oop-thread-0] 411|periodic -__KafkaCruiseControlModelTrainingSamples: Reconciling topic __KafkaCruiseControlModelTrainingSamples, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2020-01-24 16:15:06,840] ERROR <opicOperator:1297> [oop-thread-0] Error reconciling KafkaTopic null
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.108.0.1/apis/kafka.strimzi.io/v1beta1/namespaces/dbre/kafkatopics. Message: KafkaTopic.kafka.strimzi.io "kafkacruisecontrolpartitionmetricsamples---f2112b6959de42479b672fb9f3f421b7a6d0a137" is invalid: metadata.labels: Invalid value: "__KafkaCruiseControlPartitionMetricSamples": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "__KafkaCruiseControlPartitionMetricSamples": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=kafka.strimzi.io, kind=KafkaTopic, name=kafkacruisecontrolpartitionmetricsamples---f2112b6959de42479b672fb9f3f421b7a6d0a137, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=KafkaTopic.kafka.strimzi.io "kafkacruisecontrolpartitionmetricsamples---f2112b6959de42479b672fb9f3f421b7a6d0a137" is invalid: metadata.labels: Invalid value: "__KafkaCruiseControlPartitionMetricSamples": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:449) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:241) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:819) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:330) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.strimzi.operator.topic.K8sImpl.lambda$createResource$0(K8sImpl.java:50) ~[io.strimzi.topic-operator-0.15.0.jar:0.15.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[2020-01-24 16:15:06,845] ERROR <opicOperator:1297> [oop-thread-0] Error reconciling KafkaTopic null
```
Certainly because of the name starting with _ which is forbidden regarding DNS rfc.

Any workaround ?

**Comment by ppatierno** [comment]
@kyguy can you help on this?

**Comment by kyguy** [comment]
Hey @sebdoido, I think this may be related to this issue [1],  which I believe has been patched in Strimzi 0.16.0 [2]. Can you try a later Strimzi version and let me know how it goes?

If this is not the issue, as a temporary workaround (until we figure out the issue), we could try setting the `metric.reporter.topic` and `partition.metric.sample.store.topic` fields in the Cruise Control configuration and `cruise.control.metrics.topic` field in the Kafka configuration to topic names that don't have the flagged characters e.g. "_".

[1] https://github.com/strimzi/strimzi-kafka-operator/issues/2401
[2] https://github.com/strimzi/strimzi-kafka-operator/pull/2302

**Comment by sebdoido** [comment]
Ok thanks !
0.16.0 should fix the issue :)

**Comment by tomncooper** [comment]
I hope that 0.16 sorted your issue @sebdoido? FYI Cruise Control has been integrated into Strimzi as of the 0.18 release. See [this blog post](https://strimzi.io/blog/2020/06/15/cruise-control/) for more information.
