### ISSUE TITLE
Strimzi User Operator fails 

### ISSUE THREAD

**Issue by patsadow2** [strimzi/strimzi-kafka-operator#2456]
Should strimzi user operator fails when i use examples/kafka/kafka-ephemeral.yaml ?

Is it the problem ? 

v0.14 
sed -i ‘s/namespace: .*/namespace: default/’ install/cluster-operator/*RoleBinding*.yaml
kubectl apply -f install/cluster-operator
kubectl apply -f examples/kafka/kafka-ephemeral.yaml
kubectl apply -f examples/kafka-connect/kafka-connect.yaml

Should i add some -java settings to make it work and garbage collector working correctly ?

i've got 3 VM B2s = 2G CPU + 4G RAM

Should i use some kind of configuration like that ?

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    version: 2.3.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "1"
        limits:
          memory: 256Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "1"
        limits:
          memory: 256Mi
          cpu: "1"


```

```
+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
++ get_heap_size
+++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
++ CONTAINER_MEMORY_IN_BYTES=9223372036854771712
++ DEFAULT_MEMORY_CEILING=32505856
++ '[' 9223372036854771712 -lt 32505856 ']'
+ MAX_HEAP=
+ '[' -n '' ']'
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dlog4j2.configurationFile=file:/opt/user-operator/custom-config/log4j2.properties -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' true == true ']'
+++ java -version
+++ sed -E -n 's/.* version "([0-9]*).*$/\1/p'
++ JAVA_MAJOR_VERSION=1
++ '[' 1 -ge 9 ']'
++ echo '-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:NativeMemoryTracking=summary'
+ JAVA_OPTS=' -Dlog4j2.configurationFile=file:/opt/user-operator/custom-config/log4j2.properties -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:NativeMemoryTracking=summary'
+ exec java -Dlog4j2.configurationFile=file:/opt/user-operator/custom-config/log4j2.properties -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:NativeMemoryTracking=summary -classpath lib/io.strimzi.user-operator-0.14.0.jar:lib/io.netty.netty-codec-dns-4.1.34.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.jar:lib/com.101tec.zkclient-0.11.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.9.10.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.vertx.vertx-core-3.7.1.jar:lib/com.thoughtworks.paranamer.paranamer-2.8.jar:lib/io.netty.netty-handler-proxy-4.1.34.Final.jar:lib/javax.validation.validation-api-2.0.1.Final.jar:lib/org.apache.zookeeper.zookeeper-3.4.14.jar:lib/io.netty.netty-transport-4.1.34.Final.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.9.10.jar:lib/com.fasterxml.jackson.core.jackson-core-2.9.10.jar:lib/org.apache.kafka.kafka-clients-2.3.0.jar:lib/io.strimzi.certificate-manager-0.14.0.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-csv-2.9.9.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/io.fabric8.kubernetes-client-4.3.0.jar:lib/io.netty.netty-codec-socks-4.1.34.Final.jar:lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.9.9.jar:lib/io.fabric8.kubernetes-model-common-4.3.0.jar:lib/io.netty.netty-resolver-4.1.34.Final.jar:lib/io.netty.netty-codec-4.1.34.Final.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.operator-common-0.14.0.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.jar:lib/org.slf4j.jul-to-slf4j-1.7.26.jar:lib/io.strimzi.crd-annotations-0.14.0.jar:lib/org.scala-lang.scala-reflect-2.12.8.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/com.github.luben.zstd-jni-1.4.0-1.jar:lib/com.fasterxml.jackson.module.jackson-module-scala_2.12-2.9.9.jar:lib/io.ne
tty.netty-handler-4.1.34.Final.jar:lib/com.yammer.metrics.metrics-core-2.2.0.jar:lib/io.fabric8.openshift-client-4.3.0.jar:lib/io.netty.netty-resolver-dns-4.1.34.Final.jar:lib/net.sf.jopt-simple.jopt-simple-5.0.4.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.netty.netty-buffer-4.1.34.Final.jar:lib/io.netty.netty-codec-http-4.1.34.Final.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.0.jar:lib/com.typesafe.scala-logging.scala-logging_2.12-3.9.0.jar:lib/org.scala-lang.scala-library-2.12.8.jar:lib/io.netty.netty-common-4.1.34.Final.jar:lib/io.fabric8.kubernetes-model-4.3.0.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.9.8.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/io.netty.netty-codec-http2-4.1.34.Final.jar:lib/io.strimzi.api-0.14.0.jar:lib/org.apache.kafka.kafka_2.12-2.3.0.jar:lib/com.fasterxml.jackson.module.jackson-module-paranamer-2.9.9.jar:lib/org.yaml.snakeyaml-1.23.jar:lib/org.glassfish.javax.el-3.0.1-b11.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.9.10.jar io.strimzi.operator.user.Main
2020-01-26T19:00:15.089+0000: 0.349: [GC (Allocation Failure) 2020-01-26T19:00:15.089+0000: 0.349: [DefNew: 16896K->2111K(19008K), 0.0051726 secs] 16896K->2789K(61376K), 0.0052210 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-01-26T19:00:15.462+0000: 0.723: [GC (Allocation Failure) 2020-01-26T19:00:15.462+0000: 0.723: [DefNew: 19007K->2111K(19008K), 0.0106868 secs] 19685K->4314K(61376K), 0.0107332 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
[2020-01-26 19:00:15,459] INFO <Main :44> [main ] UserOperator 0.14.0 is starting
2020-01-26T19:00:15.767+0000: 1.027: [GC (Allocation Failure) 2020-01-26T19:00:15.767+0000: 1.028: [DefNew: 19007K->2112K(19008K), 0.0097469 secs] 21210K->6809K(61376K), 0.0101548 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-01-26T19:00:16.240+0000: 1.500: [GC (Allocation Failure) 2020-01-26T19:00:16.240+0000: 1.500: [DefNew: 19008K->2112K(19008K), 0.0092096 secs] 23705K->9428K(61376K), 0.0092613 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
[2020-01-26 19:00:16,352] INFO <egistration$:31> [main ] Registered kafka:type=kafka.Log4jController MBean
2020-01-26T19:00:16.425+0000: 1.686: [Full GC (Metadata GC Threshold) 2020-01-26T19:00:16.425+0000: 1.686: [Tenured: 7316K->7833K(42368K), 0.0240605 secs] 15485K->7833K(61376K), [Metaspace: 20714K->20714K(1069056K)], 0.0241573 secs] [Times: user=0.02 sys=0.00, real=0.02 secs]
[2020-01-26 19:00:16,791] INFO <KeeperClient:66> [main ] [ZooKeeperClient Simple ACL authorizer] Initializing a new session to localhost:2181.
[2020-01-26 19:00:16,800] INFO <ZooKeeper :100> [main ] Client environment:zookeeper.version=3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf, built on 03/06/2019 16:18 GMT
[2020-01-26 19:00:16,800] INFO <ZooKeeper :100> [main ] Client environment:host.name=my-cluster-entity-operator-7494f55b87-6nrqn
[2020-01-26 19:00:16,800] INFO <ZooKeeper :100> [main ] Client environment:java.version=1.8.0_222
[2020-01-26 19:00:16,800] INFO <ZooKeeper :100> [main ] Client environment:java.vendor=Oracle Corporation
[2020-01-26 19:00:16,800] INFO <ZooKeeper :100> [main ] Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-1.el7_7.x86_64/jre
[2020-01-26 19:00:16,801] INFO <ZooKeeper :100> [main ] Client environment:java.class.path=lib/io.strimzi.user-operator-0.14.0.jar:lib/io.netty.netty-codec-dns-4.1.34.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.jar:lib/com.101tec.zkclient-0.11.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.9.10.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.vertx.vertx-core-3.7.1.jar:lib/com.thoughtworks.paranamer.paranamer-2.8.jar:lib/io.netty.netty-handler-proxy-4.1.34.Final.jar:lib/javax.validation.validation-api-2.0.1.Final.jar:lib/org.apache.zookeeper.zookeeper-3.4.14.jar:lib/io.netty.netty-transport-4.1.34.Final.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.9.10.jar:lib/com.fasterxml.jackson.core.jackson-core-2.9.10.jar:lib/org.apache.kafka.kafka-clients-2.3.0.jar:lib/io.strimzi.certificate-manager-0.14.0.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-csv-2.9.9.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/io.fabric8.kubernetes-client-4.3.0.jar:lib/io.netty.netty-codec-socks-4.1.34.Final.jar:lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.9.9.jar:lib/io.fabric8.kubernetes-model-common-4.3.0.jar:lib/io.netty.netty-resolver-4.1.34.Final.jar:lib/io.netty.netty-codec-4.1.34.Final.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.operator-common-0.14.0.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.jar:lib/org.slf4j.jul-to-slf4j-1.7.26.jar:lib/io.strimzi.crd-annotations-0.14.0.jar:lib/org.scala-lang.scala-reflect-2.12.8.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/com.github.luben.zstd-jni-1.4.0-1.jar:lib/com.fasterxml.jackson.module.jackson-module-scala_2.12-2.9.9.jar:lib/io.netty.netty-handler-4.1.34.Final.jar:lib/com.yammer.metrics.metrics-core-2.2.0.jar:lib/io.fabric8.openshift-client-4.3.0.jar:lib/io.netty.netty-resolver-dns-4.1.34.Final.jar:lib/net.sf
.jopt-simple.jopt-simple-5.0.4.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.netty.netty-buffer-4.1.34.Final.jar:lib/io.netty.netty-codec-http-4.1.34.Final.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.0.jar:lib/com.typesafe.scala-logging.scala-logging_2.12-3.9.0.jar:lib/org.scala-lang.scala-library-2.12.8.jar:lib/io.netty.netty-common-4.1.34.Final.jar:lib/io.fabric8.kubernetes-model-4.3.0.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.9.8.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/io.netty.netty-codec-http2-4.1.34.Final.jar:lib/io.strimzi.api-0.14.0.jar:lib/org.apache.kafka.kafka_2.12-2.3.0.jar:lib/com.fasterxml.jackson.module.jackson-module-paranamer-2.9.9.jar:lib/org.yaml.snakeyaml-1.23.jar:lib/org.glassfish.javax.el-3.0.1-b11.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.9.10.jar
[2020-01-26 19:00:16,801] INFO <ZooKeeper :100> [main ] Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[2020-01-26 19:00:16,801] INFO <ZooKeeper :100> [main ] Client environment:java.io.tmpdir=/tmp
[2020-01-26 19:00:16,802] INFO <ZooKeeper :100> [main ] Client environment:java.compiler=<NA>
[2020-01-26 19:00:16,802] INFO <ZooKeeper :100> [main ] Client environment:os.name=Linux
[2020-01-26 19:00:16,802] INFO <ZooKeeper :100> [main ] Client environment:os.arch=amd64
[2020-01-26 19:00:16,802] INFO <ZooKeeper :100> [main ] Client environment:os.version=4.15.0-1066-azure
[2020-01-26 19:00:16,803] INFO <ZooKeeper :100> [main ] Client environment:user.name=strimzi
[2020-01-26 19:00:16,803] INFO <ZooKeeper :100> [main ] Client environment:user.home=/home/strimzi
[2020-01-26 19:00:16,803] INFO <ZooKeeper :100> [main ] Client environment:user.dir=/opt/strimzi
[2020-01-26 19:00:16,804] INFO <ZooKeeper :442> [main ] Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@416c58f5
[2020-01-26 19:00:16,820] INFO <ClientCnxn :1025> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[2020-01-26 19:00:16,825] INFO <ClientCnxn :879> [alhost:2181)] Socket connection established to localhost/127.0.0.1:2181, initiating session
[2020-01-26 19:00:16,831] INFO <KeeperClient:66> [main ] [ZooKeeperClient Simple ACL authorizer] Waiting until connected.
[2020-01-26 19:00:17,859] WARN <ClientCnxn :1164> [alhost:2181)] Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_222]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_222]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_222]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_222]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_222]
at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68) ~[org.apache.zookeeper.zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366) ~[org.apache.zookeeper.zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) [org.apache.zookeeper.zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
[2020-01-26 19:00:19,253] INFO <ClientCnxn :1025> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[2020-01-26 19:00:19,254] INFO <ClientCnxn :879> [alhost:2181)] Socket connection established to localhost/127.0.0.1:2181, initiating session
[2020-01-26 19:00:20,258] WARN <ClientCnxn :1164> [alhost:2181)] Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_222]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_222]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_222]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_222]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_222]
at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68) ~[org.apache.zookeeper.zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366) ~[org.apache.zookeeper.zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) [org.apache.zookeeper.zookeeper-3.4.14.jar:3.4.14-4c25d480e66aadd371de8bd2fd8da255ac140bcf]
[2020-01-26 19:00:22,285] INFO <ClientCnxn :1025> [alhost:2181)] Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[2020-01-26 19:00:22,286] INFO <ClientCnxn :879> [alhost:2181)] Socket connection established to localhost/127.0.0.1:2181, initiating session
[2020-01-26 19:00:22,833] INFO <KeeperClient:66> [main ] [ZooKeeperClient Simple ACL authorizer] Closing.
[2020-01-26 19:00:23,400] INFO <ZooKeeper :693> [main ] Session: 0x0 closed
[2020-01-26 19:00:23,400] INFO <ClientCnxn :522> [-EventThread] EventThread shut down for session: 0x0
[2020-01-26 19:00:23,403] INFO <KeeperClient:66> [main ] [ZooKeeperClient Simple ACL authorizer] Closed.
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:258)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:254)
at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:112)
at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1826)
at kafka.security.auth.SimpleAclAuthorizer.configure(SimpleAclAuthorizer.scala:101)
at io.strimzi.operator.user.Main.createSimpleAclAuthorizer(Main.java:100)
at io.strimzi.operator.user.Main.main(Main.java:48)
Heap
def new generation total 19136K, used 16971K [0x00000000c2a00000, 0x00000000c3ec0000, 0x00000000d7150000)
eden space 17024K, 99% used [0x00000000c2a00000, 0x00000000c3a92f10, 0x00000000c3aa0000)
from space 2112K, 0% used [0x00000000c3aa0000, 0x00000000c3aa0000, 0x00000000c3cb0000)
to space 2112K, 0% used [0x00000000c3cb0000, 0x00000000c3cb0000, 0x00000000c3ec0000)
tenured generation total 42368K, used 7833K [0x00000000d7150000, 0x00000000d9ab0000, 0x0000000100000000)
the space 42368K, 18% used [0x00000000d7150000, 0x00000000d78f6648, 0x00000000d78f6800, 0x00000000d9ab0000)
Metaspace used 24270K, capacity 24954K, committed 25088K, reserved 1071104K
class space used 3148K, capacity 3278K, committed 3328K, reserved 1048576K
```

**Comment by scholzj** [comment]
TBH, I'm not sure what the problem is. Can you share more about your environment (version of Kubernetes / OpenShift etc.)? Can you also share the logs form the other pods / containers? In this case specifically from the tls-sidecar container in the Entity Operator pod? Are the other compoenents such as Kafka or Topic Operator working fine?

**Comment by patsadow2** [comment]
It's look like user operator use to much CPU and then node fail and cannot get up for 10-30 mins

**Comment by scholzj** [comment]
I normally use the Entity operator with configuration like this:

```yaml
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "0.1"
        limits:
          memory: 256Mi
          cpu: "0.5"
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "0.1"
        limits:
          memory: 256Mi
          cpu: "0.5"
```

And never had a problem.

**Comment by patsadow2** [comment]
how about jvmOptions for kafka and resources ? do you use some special ?

**Comment by scholzj** [comment]
So this is all my development environment, not some production env. But I use this for KAfka:

```yaml
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
```

And this for Zoo (no JVM options here):

```yaml
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
      limits:
        memory: 1Gi
        cpu: "0.5"
```

**Comment by patsadow2** [comment]
It help in development
