### ISSUE TITLE
kafka-exporter "Cannot get describe groups"

### ISSUE THREAD

**Issue by Amojow** [strimzi/strimzi-kafka-operator#2480]
My Kafka exporter can't connect to the broker and can't describe groups. So I have **missing metrics** in my prometheus instance. 

The **error** in the kafka-exporter logs is : 
```
time="2020-01-30T11:22:53Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
```

**Expected behavior**
Not having this error and get all my metrics. 

**Environment (please complete the following information):**
 - Strimzi version: 0.16.2
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.14
 - Infrastructure: Bare metal

Related issue : https://github.com/danielqsj/kafka_exporter/issues/54

**Comment by Amojow** [comment]
I fixed this error momentarily by reloading the kafka exporter until this error doesn't appear.

**Comment by alesj** [comment]
@Amojow can you try this branch / pr ?
* https://github.com/danielqsj/kafka_exporter/pull/213

**Comment by XBeg9** [comment]
I am getting this on 0.22.1, my log:
```log
time="2021-05-08T12:28:32Z" level=info msg="Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=830660212e6c109e69dcb1cb58f5159fe3b38903)" source="kafka_exporter.go:474"
time="2021-05-08T12:28:32Z" level=info msg="Build context (go=go1.10.3, user=root@981cde178ac4, date=20180707-14:34:48)" source="kafka_exporter.go:475"
time="2021-05-08T12:28:33Z" level=info msg="Done Init Clients" source="kafka_exporter.go:213"
time="2021-05-08T12:28:33Z" level=info msg="Listening on :9404" source="kafka_exporter.go:499"
time="2021-05-08T12:29:39Z" level=error msg="Cannot get offset of group cluster-connect-cluster: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:29:39Z" level=error msg="Cannot get offset of group __strimzi-topic-operator-kstreams: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:29:39Z" level=error msg="Cannot get offset of group group-bmw-vin-mongo.cars.auctions: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:29:39Z" level=error msg="Cannot get offset of group group-copart-sales: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:30:27Z" level=error msg="Cannot get offset of group group-copart-sales: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:30:27Z" level=error msg="Cannot get offset of group group-autoria-scrape: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:30:27Z" level=error msg="Cannot get offset of group group-images-mongo.cars.auctions: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:30:27Z" level=error msg="Cannot get offset of group cluster-connect-cluster: kafka: broker not connected" source="kafka_exporter.go:384"
time="2021-05-08T12:30:27Z" level=error msg="Cannot get offset of group __strimzi-topic-operator-kstreams: kafka: broker not connected" source="kafka_exporter.go:384"
```

**Comment by scholzj** [comment]
Have you tried the patch from @alesj?

**Comment by alesj** [comment]
https://hub.docker.com/repository/docker/alesj/kafka_exporter

**Comment by alesj** [comment]
@XBeg9 does this one `docker.io/alesj/kafka-exporter-server:latest` also work for you?
(this is my Java / Quarkus based rewrite of original kafka_exporter ...)

**Comment by chengkuangan** [comment]
@alesj Having same problem. Using ocp 4.7, operator 1.7.1. Tried docker.io/alesj/kafka-exporter-server:latest, problem persists  with the following error:

Cannot get GetMemberAssignment of group member
Refreshing client metadata" source="kafka_exporter.go:255"

**Comment by alesj** [comment]
@chengkuangan this is then not the right exporter (image) -- as the error shows Golang code, not Java ...

**Comment by alesj** [comment]
I've pushed new fork2 image
* https://hub.docker.com/repository/docker/alesj/kafka_exporter

It's rebased fork1 against upstream master.

**Comment by chengkuangan** [comment]
@alesj Yup, my mistake. Redeploy and got the following error during POD deployment

Error: container create failed: time="2021-06-03T11:17:27Z" level=error msg="container_linux.go:366: starting container process caused: exec: \"--kafka.server=kafka-cluster-kafka-bootstrap.paygate.svc:9092\": executable file not found in $PATH"

**Comment by alesj** [comment]
@chengkuangan the image you're using doesn't take those args
It's a Java/Quarkus based mock of the original kafka_exporter,
and the image is prepared to be used by Strimzi -- the kafka_exporter_run.sh scrit prepares the right env vars.

Perhaps try removing the args, and only set these 2 env vars
```
QUARKUS_HTTP_PORT=9308
QUARKUS_PROFILE=strimzi
```

**Comment by alesj** [comment]
Or try this image:
* `docker.io/alesj/kafka_exporter:fork2`

**Comment by chengkuangan** [comment]
> Or try this image:
> 
> * `docker.io/alesj/kafka_exporter:fork2`

The container crashed

**Comment by chengkuangan** [comment]
> @chengkuangan the image you're using doesn't take those args
> It's a Java/Quarkus based mock of the original kafka_exporter,
> and the image is prepared to be used by Strimzi -- the kafka_exporter_run.sh script prepares the right env vars.
> 
> Perhaps try removing the args, and only set these 2 env vars
> 
> ```
> QUARKUS_HTTP_PORT=9308
> QUARKUS_PROFILE=strimzi
> ```

How about bootstrap-servers env? 
Using this template: https://github.com/chengkuangan/pgwdemo/blob/master/templates/kafka/kafka-exporter/deployment-alesj.yaml

I tried with only the above 2 env and logs with the errors:

exec java -Dquarkus.http.host=0.0.0.0 -javaagent:/opt/agent-bond/agent-bond.jar=jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/quarkus-run.jar
Jun 03, 2021 12:38:25 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.2.0.Final
Jun 03, 2021 12:38:26 PM io.quarkus.netty.runtime.NettyRecorder$1 run
WARN: Netty DefaultChannelId initialization (with io.netty.machineId system property set to f4:72:85:58:e6:b4:be:43) took more than a second
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-06-03 12:38:29,468 INFO  [io.str.kaf.ser.ver.VertxConfiguration] (main) Adding custom metrics paths '/metrics', scheduled collect 'true' ...
2021-06-03 12:38:30,269 INFO  [org.apa.kaf.cli.adm.AdminClientConfig] (pool-7-thread-1) AdminClientConfig values:
	bootstrap.servers = [localhost:9092]
	client.dns.lookup = use_all_dns_ips
	client.id =
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 60000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = [hidden]
	ssl.keystore.key = [hidden]
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = PEM
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = [hidden]
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = PEM

2021-06-03 12:38:31,971 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2100 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:97)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:213)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:143)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:148)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:921)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:889)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.DeploymentManager$$Lambda$217/0x00000001002c9040.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:40)
	at io.vertx.core.impl.EventLoopContext$$Lambda$218/0x00000001002c9c40.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.4/java.lang.Thread.run(Thread.java:834)

2021-06-03 12:38:31,972 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2100 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.netty.channel.DefaultChannelPipeline$HeadContext.<init>(DefaultChannelPipeline.java:1311)
	at io.netty.channel.DefaultChannelPipeline.<init>(DefaultChannelPipeline.java:98)
	at io.netty.channel.AbstractChannel.newChannelPipeline(AbstractChannel.java:108)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:75)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:80)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:89)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:75)
	at io.vertx.core.net.impl.transport.Transport$$Lambda$248/0x0000000100307440.newChannel(Unknown Source)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$doBind$2(AsyncResolveConnectHelper.java:58)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper$$Lambda$249/0x0000000100306840.handle(Unknown Source)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:71)
	at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:130)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:213)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:143)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:148)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:921)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:889)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.DeploymentManager$$Lambda$217/0x00000001002c9040.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:40)
	at io.vertx.core.impl.EventLoopContext$$Lambda$218/0x00000001002c9c40.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.4/java.lang.Thread.run(Thread.java:834)

Jun 03, 2021 12:38:32 PM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: kafka-exporter-server 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.0.0.Alpha2) started in 17.195s. Listening on: http://0.0.0.0:9308
Jun 03, 2021 12:38:32 PM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Profile strimzi activated.
Jun 03, 2021 12:38:32 PM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Installed features: [cdi, micrometer, smallrye-context-propagation, vertx]
2021-06-03 12:38:33,774 INFO  [org.apa.kaf.com.met.Metrics] (pool-7-thread-1) Metrics scheduler closed
2021-06-03 12:38:33,774 INFO  [org.apa.kaf.com.met.Metrics] (pool-7-thread-1) Closing reporter org.apache.kafka.common.metrics.JmxReporter
2021-06-03 12:38:33,774 INFO  [org.apa.kaf.com.met.Metrics] (pool-7-thread-1) Metrics reporters closed

**Comment by alesj** [comment]
Set this one: KAFKA_EXPORTER_KAFKA_SERVER ... for bootstrap servers
And remove that one QUARKUS_PROFILE

**Comment by alesj** [comment]
> > Or try this image:
> > 
> > * `docker.io/alesj/kafka_exporter:fork2`
> 
> The container crashed

How / why did it crash?

**Comment by chengkuangan** [comment]
> Set this one: KAFKA_EXPORTER_KAFKA_SERVER ... for bootstrap servers
> And remove that one QUARKUS_PROFILE

This works with docker.io/alesj/kafka-exporter-server:latest

QUARKUS_HTTP_PORT=9308
KAFKA_EXPORTER_KAFKA_SERVER=<bootstraps:9092>

**Comment by chengkuangan** [comment]
> > > Or try this image:
> > > 
> > > * `docker.io/alesj/kafka_exporter:fork2`
> > 
> > 
> > The container crashed
> 
> How / why did it crash?

The POD not able to start... so there is no log message available. not sure why then....
