### ISSUE TITLE
[Question] OAuth 2.0 token based authentication

### ISSUE THREAD

**Issue by klalafaryan** [strimzi/strimzi-kafka-operator#2526]
Hello!

We are trying to setup OAuth 2.0 token based authentication with Strimzi.  (we followed the official documentation)

The kafka configuration that we have is following:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 2.4.0 # Kafka version
    replicas: 3 # Replicas specifies the number of broker nodes.
    listeners: # Listeners configure how clients connect to the Kafka cluster
      plain: {} # 9092
      tls:
        authentication: # not yet tested
          type: oauth
          disableTlsHostnameVerification: true
          validIssuerUri: -----
          introspectionEndpointUri: -----
          clientId: 5erq448rdnkncpn2vtte8taihp
          clientSecret:
            secretName: oauth-client-secret
            key: secret
      external:
        type: loadbalancer
        tls: false
        overrides: # to be checked as the hostname doesn't seem to be applied
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.int.test.io.
            address: kafka-bootstrap.int.test.io
    config:
....
```

And we are getting following error: 

```
2020-02-10 13:43:08,419 INFO [SocketServer brokerId=2] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9092,ListenerName(PLAIN-9092),PLAINTEXT) (kafka.network.SocketServer) [main]
2020-02-10 13:43:08,419 INFO Awaiting socket connections on 0.0.0.0:9093. (kafka.network.Acceptor) [main]
2020-02-10 13:43:08,463 ERROR [KafkaServer id=2] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
java.lang.IllegalArgumentException: JAAS config entry not terminated by semi-colon
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:121)
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:90)
	at org.apache.kafka.common.security.JaasContext.loadServerContext(JaasContext.java:70)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:121)
	at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:85)
	at kafka.network.Processor.<init>(SocketServer.scala:753)
	at kafka.network.SocketServer.newProcessor(SocketServer.scala:394)
	at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:279)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:278)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:241)
	at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:238)
	at kafka.network.SocketServer.startup(SocketServer.scala:121)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:263)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
	at kafka.Kafka$.main(Kafka.scala:84)
	at kafka.Kafka.main(Kafka.scala)
2020-02-10 13:43:08,476 INFO [KafkaServer id=2] shutting down (kafka.server.KafkaServer) [main]
2020-02-10 13:43:08,482 INFO [SocketServer brokerId=2] Stopping socket server request processors (kafka.network.SocketServer) [main]
2020-02-10 13:43:08,501 INFO [SocketServer brokerId=2] Stopped socket server request processors (kafka.network.SocketServer) [main]
```

Any feedback is appreciated!

Thanks!

**Comment by klalafaryan** [comment]
The issue was coming from the secret.

**Comment by rubenski** [comment]
A newline in the base64 encoded client secret caused this for me. Thanks for the pointer.
