### ISSUE TITLE
[Question] Configure TLS for Strimzi Kafka with AWS

### ISSUE THREAD

**Issue by klalafaryan** [strimzi/strimzi-kafka-operator#2629]
Hello!

We are trying to configure strimzi kafka TLS listener. And we would like to manage the certificates in AWS.

Is it possible to integrate TLS with AWS ?

For example something like this:

```
    #            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    #            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:accountId:certificate/uuid"
    #            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
```

Or what is the best way to configure the strimzi TLS with AWS certificate manager ?

Thanks in advance!

**Comment by scholzj** [comment]
Honestly, I never used the AWS certificates. So I have no experience with them. If you can use them through the annotations above, I think it should be possible. You just have to either disable TLS on the external listener in the Kafka CR and have the loadbalancer do TLS termination or configure the load balancer to do the re-encryption. Would be quite curious how it works our for you.

**Comment by klalafaryan** [comment]
@scholzj  Thanks a lot for your reply.

So we have tried two scenarios:

1. Disable TLS on the external listener in the Kafka CR and have the loadbalancer do TLS termination
**Context:** As the certificates from Strimzi are not recognised, the idea is to configure the certificates provided by AWS as annotations for the external bootstrap service. Thus disabling TLS from the external listeners and enabling the AWS certificate for the external bootstrap service.
```yaml
spec:
  kafka:
    listeners:
      external:
        type: loadbalancer
        tls: false
  ...
  template:
    externalBootstrapService:
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:...."
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
```
**Problem:** In order to communicate with the brokers, the `security.protocol` configured on the client side has to be `SASL_SSL`. Therefore, the listener is only supporting `EXTERNAL:9094-PLAINTEXT` on Strimzi side with SSL on the service side. The messages won't be correctly decoded resulting in the following error:
```java
2020-03-18 14:17:42,939 WARN [SocketServer brokerId=0] Unexpected error from /{IP_ADDRESS}; closing connection (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(EXTERNAL-9094)-SASL_PLAINTEXT-10]
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369296129 larger than 524288)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)
	at org.apache.kafka.common.security.authenticator.SaslServerAuthenticator.authenticate(SaslServerAuthenticator.java:268)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:173)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
	at kafka.network.Processor.poll(SocketServer.scala:890)
	at kafka.network.Processor.run(SocketServer.scala:789)
	at java.lang.Thread.run(Thread.java:748)
```
**Problem 2:** If the `security.protocol` configured on the client side is `SASL_PLAINTEXT`, then the following error is raised:
```log
2522 [main] WARN  o.a.kafka.clients.NetworkClient - [Consumer clientId=consumer-test-group1-1, groupId=test-group1] Connection to node -1 (kafka-bootstrap.example.com/{IP_ADDRESS}:9094) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```


2. Configure the load balancer to do the re-encryption
**Context:** The idea is to enable TLS on the Strimzi side along with the AWS certificate configured as an annotation. This would configure the listener on Strimzi side with `SSL` and expose only the AWS certificate.
```yaml
spec:
  kafka:
    listeners:
      external:
        type: loadbalancer
        tls: true
  ...
  template:
    externalBootstrapService:
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central..."
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
```

**Problem:** During debugging the SSL trace on the Java side of the testing client, it appears that in the first place the AWS certificate is correctly recognized, but then after the Strimzi certificate is forwarded to the client we are getting following exception:
```java
Exception in thread "main" org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeWrap(SslTransportLayer.java:448)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:313)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:265)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:170)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:540)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:212)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:400)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:340)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:471)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1267)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1231)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at com.example.handsonlab.strimzi.ConsumerApplication.main(ConsumerApplication.java:42)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:402)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:484)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:340)
	... 15 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
	... 30 more
```



To be able to use strimzi certificates we have to add this in all the clients (we have more than 100 clients), and this is not scalable solution for us.

Are we doing something wrong, or ???!!

I would really appreciate your input.

Thanks!

**Comment by scholzj** [comment]
Re 1) Interesting. I'm a bit surprised that the security protocol from the server is advertised to the client. I would have expected that it will be configured from the client. But if that is the case, this will clearly not work.

Re 2) This one is a bit weird. If you set the load balancer to re-encrypt, the TLS information from Strimzi should not be seen at all by the client. I would expect that you would need to tell the LoadBalancer to trust the Strimzi certificates (and have no idea how - never used that), but not the client. Could you run the client with `-Djavax.net.debug=tls` to get some more information about what is going on on the TLS level in the client?

**Comment by auswells** [comment]
I've been experimenting using AWS Certificates as well with strimzi-kafka-operator helm chart version 0.16.2 installed.

Here's an example of my kafka spec that uses an AWS Cert on the external listener:
```
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      external:
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
        overrides:
          bootstrap:
            dnsAnnotations:
              "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:us-east-1:..."
              "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp"
              "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "9094"
              "external-dns.alpha.kubernetes.io/hostname": "bootstrap.my-domain.com"
          brokers:
            - broker: 0
              dnsAnnotations:
                "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:aws:acm:us-east-1:..."
                "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp"
                "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "9094"
                "external-dns.alpha.kubernetes.io/hostname": "broker-0.my-domain.com"
```
This allows my external clients to connect to my strimzi kafka cluster, however one issue I noticed is that advertised-hostnames.config is automatically populated with the loadbalancer DNS name. This doesn't work with my certificate so I had to manually edit the advertised-hostnames.config to include broker-0.my-domain.com instead of the loadbalancer DNS name then recycle the kafka pod. 

In order to test that this works I had to extend the reconciliation time on the operator so my advertised-hostnames.config isn't reset until far in the future...

Is there a way to override the hostnames in advertised-hostnames.config?

**Comment by scholzj** [comment]
We do not really read the DNS annotation (since we do not really want to have to care about all the different applications which do the processing in the same way as External DNS does). So we just pass it over. But you can use this to override the dvertised hostnames: 

```
# ...
listeners:
  external:
    type: route
    authentication:
      type: tls
    overrides:
      brokers:
      - broker: 0
        advertisedHost: example.hostname.0
        advertisedPort: 12340
      - broker: 1
        advertisedHost: example.hostname.1
        advertisedPort: 12341
      - broker: 2
        advertisedHost: example.hostname.2
        advertisedPort: 12342
# ...
```

(see https://strimzi.io/docs/latest/full.html#con-kafka-broker-external-listeners-addresses-deployment-configuration-kafka)

So I think you just need to add the hostaame into the `advertisedHost` option as well and you should be set. If it doesn't work it would be a bug, so please let me know.

**Comment by auswells** [comment]
@scholzj Thanks! That worked.

**Comment by scholzj** [comment]
So, I guess we can close this issue?

BTW: If you would be interested, I think this could be a very nice topic for a short blog post on the Strimzi website ;-)

**Comment by auswells** [comment]
I'll let the OP respond regarding closing the ticket and if all is well I don't mind writing something up.

**Comment by klalafaryan** [comment]
@auswells  Thanks for your input.

I have tried with following configuration and it works. Thanks!

```
        overrides:
          bootstrap:
            dnsAnnotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:...."
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.example.com
            address: kafka-bootstrap.example.com
          brokers:
            - broker: 0
              dnsAnnotations:
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
                service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:...."
                service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.example.com
              advertisedHost: kafka-broker-0.example.com
```

Currently, for 3 brokers cluster we have 4 load balancers.  (for each broker separate LB and one for external bootstrap)
Do you know if we can achieve to the same result with kubernetes ingress ? 

BTW: I like the idea about the blog post.

**Comment by klalafaryan** [comment]
And one more question about the `kafka connect`:

As soon as I activate TLS encryption for my kafka brokers, I need to pass `security.protocol", "SASL_SSL"` to my `kafka-connect`. And from documentation I can see following:

```
The Kafka Connect configuration. Properties with the following prefixes cannot be set: ssl., sasl., security., listeners, plugin.path, rest., bootstrap.servers, consumer.interceptor.classes, producer.interceptor.classes.
```
Any suggestions ?

Thanks.

**Comment by scholzj** [comment]
> Currently, for 3 brokers cluster we have 4 load balancers. (for each broker separate LB and one for external bootstrap)
Do you know if we can achieve to the same result with kubernetes ingress ?

You mean to use Ingress in general? Or to use 4 loadbalancers with Ingress?

> As soon as I activate TLS encryption for my kafka brokers, I need to pass security.protocol", "SASL_SSL" to my kafka-connect. And from documentation I can see that it is not possible:

You have to configure it from the `authentication` and `tls` sections. Based on thsoe, the operator sets the right value in the configuration:
* https://strimzi.io/docs/latest/full.html#assembly-kafka-connect-tls-deployment-configuration-kafka-connect
* https://strimzi.io/docs/latest/full.html#assembly-kafka-connect-authentication-deployment-configuration-kafka-connect

**Comment by klalafaryan** [comment]
@scholzj  Thanks for your quick reply.

Yes, in general. I would prefer to use Ingress instead of LoadBalancer, because it is cheaper than AWS ELB. So basically whatever was mentioned before with LB configuration( with AWS certificates), I would like to achieve the same result with ingress.

I have checked the documentation and still I couldn't find a way to do it. What I understood is if I have manually generated certificate by adding `tls` section it will do it, but in my case I am using AWS certificate, and the only thing that I need to do is setting `security.protocol: SASL_SSL`.

I have the following configuration for kafkaconnect

```
  authentication:
    type: oauth
    tokenEndpointUri: {token_endpoint_url}
    clientId: {client_id}
    clientSecret:
      secretName: {secret}
      key: OAUTH_EXTERNAL_LISTENER_KAFKA_CONNECT_CLIENT_SECRET
```

**Comment by scholzj** [comment]
> Yes, in general. I would prefer to use Ingress instead of LoadBalancer, because it is cheaper than AWS ELB. So basically whatever was mentioned before with LB configuration( with AWS certificates), I would like to achieve the same result with ingress.

TBH, I'm not sure how that would work. Have you tried it? The problem with Ingress is that it by default supports HTTP traffic. And Kafka is not HTTP Traffic. So we need to use TLS passthrough on the Ingress level. But you anyway do not want tLS termination in Ingress but in the ELB which Ingress is using, right? In whihc case something like this might be possible:

```
Client -----------> Ingress ELB --------------> Ingress Nginx ---------------> Kafka Pod
         AWS Cert                   Strimzi cert with TLS passthrough
                    Reencryption
```

But I never tried it. Have you also considered Network Load Balancer? I pleayed with it, but I'm not sure how much cheaper it would be for you (https://strimzi.io/2020/01/02/using-strimzi-with-amazon-nlb-loadbalancers.html).

With Ingress you also need to be careful abotu performance. The Ingress will always add additional bottleneck.

---

> I have checked the documentation and still I couldn't find a way to do it. What I understood is if I have manually generated certificate by adding tls section it will do it, but in my case I am using AWS certificate, and the only thing that I need to do is setting security.protocol: SASL_SSL.

I now do not remember exactly. But you can do either:

```
  tls: {}
```

or

```
  tls:
    trustedCertificates: []
```

One of these will enable TLS without the need to provide certificate if the one you use is already trusted by default. Give it a try.

However - do you run Kafka and Connect in different cluster? If they are in the same cluster, you should really confider using the internal `tls` interface of the broker. Because if you take it through the external one with the loadbalancers, it will be slower and you will IIRC have higher traffic fees.

**Comment by klalafaryan** [comment]
I have tried to use external bootstrap DNS ($KAFKA_EXTERNAL_BOOTSTRAP_DNS:9094) to connect to kafka from kafka-connect, and it works fine with:

```
  tls:
    trustedCertificates: []

```
As my kafka brokers and kafka connect running on the same cluster, I would prefer to use TLS listener (9093) to connect to broker, but I am getting exception.

**_Kafka configuration:_**

```
      tls:
        authentication:
          type: oauth
          clientId: $OAUTH_EXTERNAL_LISTENER_BROKER_CLIENT_ID
          clientSecret:
            secretName: $CLUSTER_NAME
            key: OAUTH_EXTERNAL_LISTENER_BROKER_CLIENT_SECRET
          validIssuerUri: $CLUSTER_OAUTH_SERVER_URL/auth/realms/master
          jwksEndpointUri: $CLUSTER_OAUTH_SERVER_URL/auth/realms/master/protocol/openid-connect/certs
          userNameClaim: clientId
        configuration: {}
      external:
        type: loadbalancer
        tls: false
        authentication:
          type: oauth
          clientId: $OAUTH_EXTERNAL_LISTENER_BROKER_CLIENT_ID
          clientSecret:
            secretName: $CLUSTER_NAME
            key: OAUTH_EXTERNAL_LISTENER_BROKER_CLIENT_SECRET
          validIssuerUri: $CLUSTER_OAUTH_SERVER_URL/auth/realms/master
          jwksEndpointUri: $CLUSTER_OAUTH_SERVER_URL/auth/realms/master/protocol/openid-connect/certs
          userNameClaim: clientId
        overrides:
          bootstrap:
            dnsAnnotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1..."
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
              external-dns.alpha.kubernetes.io/hostname: $KAFKA_EXTERNAL_BOOTSTRAP_DNS
            address: $KAFKA_EXTERNAL_BOOTSTRAP_DNS
          brokers:
            - broker: 0
              dnsAnnotations:
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
                service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1..."
                service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.example.com
              advertisedHost: kafka-broker-0.example.com
            - broker: 1
              dnsAnnotations:
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
                service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1..."
                service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.example.com
              advertisedHost: kafka-broker-1.example.com
            - broker: 2
              dnsAnnotations:
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
                service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central..."
                service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.example.com
              advertisedHost: kafka-broker-2.example.com
```

**_Kafka-connect configuration:_**

```
spec:
  image: ...
  version: ...
  replicas: ...
  bootstrapServers: cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: db-credentials
  config:
    .....
  authentication:
    type: oauth
    tokenEndpointUri: $OAUTH_TOKEN_ENDPOINT_URL
    clientId: $OAUTH_EXTERNAL_LISTENER_KAFKA_CONNECT_CLIENT_ID
    clientSecret:
      secretName: $CLUSTER_NAME
      key: OAUTH_EXTERNAL_LISTENER_KAFKA_CONNECT_CLIENT_SECRET
  tls:
    trustedCertificates: []


```

And I am getting following exception:


```
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and security properties.
	at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
	at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:45)
	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:95)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:78)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:58)
	... 3 more
Caused by: org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeWrap(SslTransportLayer.java:448)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:313)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:265)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:170)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:540)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1196)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:402)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:484)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:340)
	... 7 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
	... 16 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
	... 22 more

```

And another question I have is about the `overrides` property in the external listener.  My understanding is that it will be common for all listeners, does it make sense to move outside of the `external` listener ? Or am I missing something ?

Thanks!

**Comment by scholzj** [comment]
Well, when you use in Connect the internal listener with port 9093, you do not go through the AWS certificates anymore. So the `trustedCertificates: []` is not enough enymore. You would need to use the Strimzi certificate:

```
  tls:
    trustedCertificates:
      - secretName: <cluster-name>-cluster-ca-cert
        certificate: ca.crt
```

---

> And another question I have is about the overrides property in the external listener. My understanding is that it will be common for all listeners, does it make sense to move outside of the external listener ? Or am I missing something ?

The overrides apply only to the external listener. They do not affect the other listeners.

**Comment by klalafaryan** [comment]
ok thanks, with the cluster certificate now it works. I am just wondering how certificate renewal is done ?  I am not sure also I can find much in the documentation.

One more question, Is it possible to use `java-consumer` application with the same certificate (without AWS) ? If yes, how the renewal of the certificate should be handled ?

**Comment by scholzj** [comment]
> ok thanks, with the cluster certificate now it works. I am just wondering how certificate renewal is done ? I am not sure also I can find much in the documentation.

The certificates are automatically renewed. More about it should be int he docs here: https://strimzi.io/docs/latest/full.html#con-certificate-renewal-str

> One more question, Is it possible to use java-consumer application with the same certificate (without AWS) ? If yes, how the renewal of the certificate should be handled ?

Yes, you can use the certificates with it. Here are some YAML files showing how to do it: https://github.com/strimzi/client-examples/tree/master/java/kafka

In the renewal, the pods will probably need to be restarted to reload new certificate. It depends a bit on the behaviour of the application,how do you get the certificates etc. I think with the new P12 certificates directly in the secrets it can work even without restart if you mount them as a volume.

**Comment by klalafaryan** [comment]
@scholzj  Thanks a lot for more details. 

1. My understanding is that if I read the P12 certificate from the secret, this will be loaded only once when I start my java application. (in the very beginning) 
But as soon as my certificate will expire, my application will not be healthy (will not be able to produce/consume), and I have to manually restart it.
Can you please elaborate more ?

2. And one thing I have realized is about the external listener with AWS certificate, if I want to scale the brokers(from 3 to 5) , I have to increase number of replicas, and also add overrides for every single broker. 

Maybe we can do this dynamically in the cluster operator, what do you think ?

Thanks.

**Comment by klalafaryan** [comment]
@scholzj  TBH, I didn't manage to try, but as soon as I check will share it here.
Thanks for clarification. And i think we can close this issue. Thanks again!
