### ISSUE TITLE
Failed to create cache dir

### ISSUE THREAD

**Issue by cameronbraid** [strimzi/strimzi-kafka-operator#2661]
deployed strimzi-cluster-operator-0.16.2 on kubernetes 1.17 (KinD)

strimzi-cluster-operator pod stacktrace :

```
Exception in thread "main" java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:332)
	at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:87)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:167)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
	at io.vertx.core.Vertx.vertx(Vertx.java:85)
	at io.strimzi.operator.cluster.Main.main(Main.java:64)
```

Strange because it has `-Dvertx.cacheDirBase=/tmp`

**Comment by cameronbraid** [comment]
I think I found the issue.. just KinD cluster ran out of space
