### ISSUE TITLE
[Failed to parse default container image configuration for Kafka from environment variable "STRIMZI_KAFKA_IMAGES"]

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#2793]
I'm trying to deploy Strimzi  with helm, but i'm trying to separate the values.yaml references from the files in template.
when i run the **050-Deployment-strimzi-cluster-operator.yaml** file, i get error '
```
`+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
/opt/strimzi/bin/launch_java.sh: line 5: /opt/strimzi/bin/dynamic_resources.sh: No such file or directory
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/com.github.luben.zstd-jni-1.4.3-1.jar:lib/io.netty.netty-handler-4.1.45.Final.jar:lib/org.keycloak.keycloak-core-7.0.0.jar:lib/io.netty.netty-codec-http-4.1.45.Final.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.jar:lib/org.quartz-scheduler.quartz-2.2.1.jar:lib/io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.netty.netty-buffer-4.1.45.Final.jar:lib/org.yaml.snakeyaml-1.24.jar:lib/io.fabric8.openshift-client-4.6.4.jar:lib/io.strimzi.api-0.18.0-SNAPSHOT.jar:lib/io.netty.netty-common-4.1.45.Final.jar:lib/org.apache.logging.log4j.log4j-api-2.13.0.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/org.hdrhistogram.HdrHistogram-2.1.11.jar:lib/io.prometheus.simpleclient-0.7.0.jar:lib/io.strimzi.kafka-oauth-common-0.4.0.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.2.jar:lib/org.keycloak.keycloak-common-7.0.0.jar:lib/io.strimzi.certificate-manager-0.18.0-SNAPSHOT.jar:lib/io.netty.netty-codec-4.1.45.Final.jar:lib/io.micrometer.micrometer-core-1.3.1.jar:lib/io.strimzi.kafka-oauth-server-0.4.0.jar:lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:lib/io.vertx.vertx-core-3.8.5.jar:lib/io.netty.netty-codec-dns-4.1.45.Final.jar:lib/io.fabric8.kubernetes-model-4.6.4.jar:lib/io.netty.netty-codec-socks-4.1.45.Final.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.netty.netty-resolver-4.1.45.Final.jar:lib/org.apache.zookeeper.zookeeper-jute-3.5.6.jar:lib/io.netty.netty-handler-proxy-4.1.45.Final.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/io.netty.netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:lib/io.netty.netty-transport-native-unix-common-4.1.45.Final.jar:lib/org.apache.zookeeper.zookeeper-3.5.6.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/io.vertx.vertx-micrometer-metrics-3.8.5.jar:lib/com.fasterxml.jackson.core.jackson-core-2.10.2.jar:lib/io.netty.netty-transport-4.1.45.Final.jar:lib/io.netty.netty-transport-native-epoll-4.1.45.Final.jar:lib/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.13.0.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.10.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/io.strimzi.crd-annotations-0.18.0-SNAPSHOT.jar:lib/io.fabric8.kubernetes-client-4.6.4.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.2.jar:lib/com.squareup.okhttp3.okhttp-3.12.6.jar:lib/io.netty.netty-codec-http2-4.1.45.Final.jar:lib/org.apache.logging.log4j.log4j-core-2.13.0.jar:lib/io.fabric8.kubernetes-model-common-4.6.4.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.10.2.jar:lib/io.netty.netty-resolver-dns-4.1.45.Final.jar:lib/io.strimzi.kafka-oauth-client-0.4.0.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/org.latencyutils.LatencyUtils-2.0.3.jar:lib/io.strimzi.config-model-0.18.0-SNAPSHOT.jar:lib/org.apache.kafka.kafka-clients-2.4.0.jar:lib/io.micrometer.micrometer-registry-prometheus-1.3.1.jar io.strimzi.operator.cluster.Main
2020-04-06 17:56:37 INFO  Main:58 - ClusterOperator 0.18.0-SNAPSHOT is starting
Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: Failed to parse default container image configuration for Kafka from environment variable STRIMZI_KAFKA_IMAGES
        at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:222)
        at io.strimzi.operator.cluster.ClusterOperatorConfig.fromMap(ClusterOperatorConfig.java:94)
        at io.strimzi.operator.cluster.Main.main(Main.java:59)
Caused by: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.4.0
        at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.image(KafkaVersion.java:163)
        at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.validateKafkaImages(KafkaVersion.java:195)
        at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:204)
        ... 2 more` 
```

in the yaml file i'm passing the env as 
```
`        - name: STRIMZI_KAFKA_IMAGES
           value: 2.3.1=strimzi/kafka:latest-kafka-2.3.1`
```

i'm not able to deploy the kafka-operator file, need asssitance

### **steps taken**
create **CRB**
`kubectl create clusterrolebinding strimzi-cluster-operator-namespaced --clusterrole=strimzi-cluster-operator-namespaced --serviceaccount kafka-operator:strimzi-cluster-operator
kubectl create clusterrolebinding strimzi-cluster-operator-entity-operator-delegation --clusterrole=strimzi-entity-operator --serviceaccount kafka-operator:strimzi-cluster-operator
kubectl create clusterrolebinding strimzi-cluster-operator-topic-operator-delegation --clusterrole=strimzi-topic-operator --serviceaccount kafka-operaror:strimzi-cluster-operator`

Separated the values.yaml references
 and execute
`kubectl apply -f install/cluster-operator '

**Comment by scholzj** [comment]
The valud needs to contain an image for every Kafka version the release supports. In your case, it is missing image for version 2.4.0. It needs to look something like this:

```yaml
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
            2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0
```

(see https://github.com/strimzi/strimzi-kafka-operator/blob/a5a3089d1dfd7d0341e335944e14ba38c2a2f857/install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml#L42)

What does _separate the values.yaml references from the files in template_ exactly mean?

**Comment by pashafirdous** [comment]
hello,
thanks for quick response.

i guess the error fixed and i got another error
```

`+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
/opt/strimzi/bin/launch_java.sh: line 5: /opt/strimzi/bin/dynamic_resources.sh: No such file or directory
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/com.github.luben.zstd-jni-1.4.3-1.jar:lib/io.netty.netty-handler-4.1.45.Final.jar:lib/org.keycloak.keycloak-core-7.0.0.jar:lib/io.netty.netty-codec-http-4.1.45.Final.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.jar:lib/org.quartz-scheduler.quartz-2.2.1.jar:lib/io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.netty.netty-buffer-4.1.45.Final.jar:lib/org.yaml.snakeyaml-1.24.jar:lib/io.fabric8.openshift-client-4.6.4.jar:lib/io.strimzi.api-0.18.0-SNAPSHOT.jar:lib/io.netty.netty-common-4.1.45.Final.jar:lib/org.apache.logging.log4j.log4j-api-2.13.0.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/org.hdrhistogram.HdrHistogram-2.1.11.jar:lib/io.prometheus.simpleclient-0.7.0.jar:lib/io.strimzi.kafka-oauth-common-0.4.0.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.2.jar:lib/org.keycloak.keycloak-common-7.0.0.jar:lib/io.strimzi.certificate-manager-0.18.0-SNAPSHOT.jar:lib/io.netty.netty-codec-4.1.45.Final.jar:lib/io.micrometer.micrometer-core-1.3.1.jar:lib/io.strimzi.kafka-oauth-server-0.4.0.jar:lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:lib/io.vertx.vertx-core-3.8.5.jar:lib/io.netty.netty-codec-dns-4.1.45.Final.jar:lib/io.fabric8.kubernetes-model-4.6.4.jar:lib/io.netty.netty-codec-socks-4.1.45.Final.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.netty.netty-resolver-4.1.45.Final.jar:lib/org.apache.zookeeper.zookeeper-jute-3.5.6.jar:lib/io.netty.netty-handler-proxy-4.1.45.Final.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/io.netty.netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:lib/io.netty.netty-transport-native-unix-common-4.1.45.Final.jar:lib/org.apache.zookeeper.zookeeper-3.5.6.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/io.vertx.vertx-micrometer-metrics-3.8.5.jar:lib/com.fasterxml.jackson.core.jackson-core-2.10.2.jar:lib/io.netty.netty-transport-4.1.45.Final.jar:lib/io.netty.netty-transport-native-epoll-4.1.45.Final.jar:lib/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.13.0.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.10.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/io.strimzi.crd-annotations-0.18.0-SNAPSHOT.jar:lib/io.fabric8.kubernetes-client-4.6.4.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.2.jar:lib/com.squareup.okhttp3.okhttp-3.12.6.jar:lib/io.netty.netty-codec-http2-4.1.45.Final.jar:lib/org.apache.logging.log4j.log4j-core-2.13.0.jar:lib/io.fabric8.kubernetes-model-common-4.6.4.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.10.2.jar:lib/io.netty.netty-resolver-dns-4.1.45.Final.jar:lib/io.strimzi.kafka-oauth-client-0.4.0.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/org.latencyutils.LatencyUtils-2.0.3.jar:lib/io.strimzi.config-model-0.18.0-SNAPSHOT.jar:lib/org.apache.kafka.kafka-clients-2.4.0.jar:lib/io.micrometer.micrometer-registry-prometheus-1.3.1.jar io.strimzi.operator.cluster.Main
2020-04-06 18:24:26 INFO  Main:58 - ClusterOperator 0.18.0-SNAPSHOT is starting
Exception in thread "main" java.lang.RuntimeException: Failed to parse Map from String
        at io.strimzi.operator.common.Util.parseMap(Util.java:126)
        at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:192)
        at io.strimzi.operator.cluster.ClusterOperatorConfig.fromMap(ClusterOperatorConfig.java:94)
        at io.strimzi.operator.cluster.Main.main(Main.java:59)`
```

i am not able to find the map it is referring to.

please help!

**Comment by scholzj** [comment]
I would need to see the full YAML to find out hat the problem is. But in general as I said before - the env vars should be as in this file: https://github.com/strimzi/strimzi-kafka-operator/blob/a5a3089d1dfd7d0341e335944e14ba38c2a2f857/install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml or as if you would installed the original Helm Chart. And it looks like right now you are missing some of the environment variables.

**Comment by pashafirdous** [comment]
my file is below.


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: strimzi/operator:latest
        args:
        - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          value: "*"
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.3.1=strimzi/kafka:latest-kafka-2.3.1
            2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0
            2.2.1=strimzi/kafka:2.2.1
            2.3.0=strimzi/kafka:2.3.0
#        - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
#          value: strimzi/kafka:2.3.0
        # - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          # value: strimzi/kafka:2.3.0
        # - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          # value: strimzi/kafka:2.3.0
        # - name: STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE
          # value: strimzi/kafka:2.3.0
        # - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
          # value: strimzi/kafka:2.3.0
        # - name: STRIMZI_KAFKA_CONNECT_IMAGES
          # value: |
            # 2.2.1=strimzi/kafka:2.2.1
            # 2.3.0=strimzi/kafka:2.3.0
        # - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
          # value: |
            # 2.2.1=strimzi/kafka:2.2.1
            # 2.3.0=strimzi/kafka:2.3.0
        # - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
          # value: |
            # 2.2.1=strimzi/kafka:2.2.1
            # 2.3.0=strimzi/kafka:2.3.0
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
          value: strimzi/kafka-bridge:latest
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
  strategy:
    type: Recreate

```

**Comment by scholzj** [comment]
Ok, so it looks like you are not editing the Helm Chart for the latest version. But you need to:
* Make sure all the vairables in the original one are defined
* In the maps you need to keep the original versions listed
* Linking to the `strimzi/operator:lates` image gives you the latest master build. That supports only Kafka 2.4.0 and 2.3.1 at this point. So these need to be in the maps. any others are useless there. But in general you should not use latest. We will add 2.4.1 this week and that will break it for you. You need to use one of the stable releases.

Right you have most of the environment variables commented out and that is causing your error.

**Comment by pashafirdous** [comment]
thanks Jakub.!!
i used the file referred by you, but i see there is new error now.

i am running the code in GKE, not openshift.

the code is failing in GKE. any guesses??
 ```
       KUBERNETES_PORT_443_TCP_PORT: 443
        STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE: strimzi/kafka:latest-kafka-2.4.0
        KUBERNETES_SERVICE_PORT_HTTPS: 443
        SHLVL: 0
        HOME: /home/strimzi
        STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE: strimzi/kafka:latest-kafka-2.4.0
        MALLOC_ARENA_MAX: 2

2020-04-06 18:52:34 INFO  Main:117 - The KafkaConnectS2I custom resource definition can only be used in environment which supports OpenShift build, image and apps APIs. These APIs do not seem to be supported in this environment.
2020-04-06 18:52:34 INFO  ClusterOperator:84 - Creating ClusterOperator for namespace kafka-operator
2020-04-06 18:52:34 INFO  ClusterOperator:101 - Starting ClusterOperator for namespace kafka-operator
2020-04-06 18:52:35 INFO  ClusterOperator:115 - Opened watch for Kafka operator
2020-04-06 18:52:35 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-04-06 18:52:35 INFO  AbstractOperator:303 - Watcher closed in namespace kafka-operator
2020-04-06 18:52:35 INFO  ClusterOperator:115 - Opened watch for KafkaConnect operator
2020-04-06 18:52:35 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-04-06 18:52:35 INFO  AbstractOperator:303 - Watcher closed in namespace kafka-operator
2020-04-06 18:52:35 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 403, Status: 403 - kafkamirrormaker2s.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafka-operator:strimzi-cluster-operator" cannot watch resource "kafkamirrormaker2s" in API group "kafka.strimzi.io" in the namespace "kafka-operator"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-04-06 18:52:35 INFO  AbstractOperator:303 - Watcher closed in namespace kafka-operator
2020-04-06 18:52:35 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 403, Status: 403 - kafkaconnectors.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafka-operator:strimzi-cluster-operator" cannot watch resource "kafkaconnectors" in API group "kafka.strimzi.io" in the namespace "kafka-operator"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-04-06 18:52:35 ERROR Main:148 - Cluster Operator verticle in namespace kafka-operator failed to start
io.fabric8.kubernetes.client.KubernetesClientException: 404 page not found

        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:206) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
        Suppressed: java.lang.Throwable: waiting here
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:135) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
                at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:354) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:759) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:738) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:69) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
                at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResourceOperator.java:63) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
                at io.strimzi.operator.common.AbstractOperator.lambda$createWatch$9(AbstractOperator.java:292) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
                at io.strimzi.operator.common.Util.lambda$async$0(Util.java:43) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
```

**Comment by scholzj** [comment]
Yeah:
* the HTTP 404 would mean you do not have the Custom Resource Definition files installed.
* the HTTP 403 means thet you didn't installed al lthe RBAC files (Clusterroles, RoleBindings, ClusterRoleBindings etc.)

**Comment by pashafirdous** [comment]
yes i guess, but still i am getting below.

```
2020-04-06 19:53:54 ERROR Main:148 - Cluster Operator verticle in namespace * failed to start
io.fabric8.kubernetes.client.KubernetesClientException: kafkamirrormaker2s.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafka-operator:strimzi-cluster-operator" cannot watch resource "kafkamirrormaker2s" in API group "kafka.strimzi.io" at the cluster scope
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:206) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
```

**Comment by scholzj** [comment]
You configured the cluster operator to watch the whole namespace. But you seem to be still missing some ClusterRoleBindings for it. To watch the whole cluster, you need to change all RoleBndings to ClusterRoleBindings. So you should check that. More details about how to deploy the RBACs to watch the whole cluster can be found here: https://strimzi.io/docs/latest/full.html#deploying-cluster-operator-to-watch-whole-cluster-str

**Comment by scholzj** [comment]
@pashafirdous Did you managed to solve it?

**Comment by pashafirdous** [comment]
Thanks a TONN!! 
Jakub, this was helpful.

**Comment by pashafirdous** [comment]
Yes we referred to the CRD's from the master recent release. 
that fixed the issue.

as you suggessted, we were actually referring to an old repo. there was teh problem

**Comment by scholzj** [comment]
Ok, so I take this issue can be closed, right?
