### ISSUE TITLE
Kafka unable to connect to zookeeper in a secluded environment

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#2811]
Hi,

I am running the Oeprator in a secured GKE and i get the below error, where kafka is not able to connect with zookeeper.

for the below error it seems the kafka is trying to zookeeper connect on localhost?????
`INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181`

could you advice how to alter the hooks/ if anyother issues what can be done to work this?

```
ibs/kafka-agent.jar:/opt/kafka/bin/../libs/kafka-clients-2.3.1.jar:/opt/kafka/bin/../libs/kafka-log4j-appender-2.3.1.jar:/opt/kafka/bin/../libs/kafka-oauth-client-0.4.0.jar
/opt/kafka/bin/../libs/kafka-oauth-common-0.4.0.jar:/opt/kafka/bin/../libs/kafka-oauth-keycloak-authorizer-0.4.0.jar:/opt/kafka/bin/../libs/kafka-oauth-server-0.4.0.jar:/op
/kafka/bin/../libs/kafka-streams-2.3.1.jar:/opt/kafka/bin/../libs/kafka-streams-examples-2.3.1.jar:/opt/kafka/bin/../libs/kafka-streams-scala_2.12-2.3.1.jar:/opt/kafka/bin/
./libs/kafka-streams-test-utils-2.3.1.jar:/opt/kafka/bin/../libs/kafka-tools-2.3.1.jar:/opt/kafka/bin/../libs/kafka_2.12-2.3.1-sources.jar:/opt/kafka/bin/../libs/kafka_2.12
2.3.1.jar:/opt/kafka/bin/../libs/keycloak-common-7.0.0.jar:/opt/kafka/bin/../libs/keycloak-core-7.0.0.jar:/opt/kafka/bin/../libs/libthrift-0.12.0.jar:/opt/kafka/bin/../libs
log4j-1.2.17.jar:/opt/kafka/bin/../libs/lz4-java-1.6.0.jar:/opt/kafka/bin/../libs/maven-artifact-3.6.1.jar:/opt/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka/bin/../l
bs/mirror-maker-agent.jar:/opt/kafka/bin/../libs/okhttp-3.9.0.jar:/opt/kafka/bin/../libs/okio-1.13.0.jar:/opt/kafka/bin/../libs/opentracing-api-0.33.0.jar:/opt/kafka/bin/..
libs/opentracing-kafka-client-0.1.4.jar:/opt/kafka/bin/../libs/opentracing-noop-0.33.0.jar:/opt/kafka/bin/../libs/opentracing-tracerresolver-0.1.8.jar:/opt/kafka/bin/../lib
/opentracing-util-0.33.0.jar:/opt/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/kafka/bin/../libs/paranamer-2.8.jar:/opt/kafka/bin/../libs/plexus-utils-3.2.0.jar:/
pt/kafka/bin/../libs/reflections-0.9.11.jar:/opt/kafka/bin/../libs/rocksdbjni-5.18.3.jar:/opt/kafka/bin/../libs/scala-library-2.12.10.jar:/opt/kafka/bin/../libs/scala-libra
y-2.12.8.jar:/opt/kafka/bin/../libs/scala-logging_2.12-3.9.0.jar:/opt/kafka/bin/../libs/scala-reflect-2.12.8.jar:/opt/kafka/bin/../libs/slf4j-api-1.7.26.jar:/opt/kafka/bin/
./libs/slf4j-log4j12-1.7.26.jar:/opt/kafka/bin/../libs/snappy-java-1.1.7.3.jar:/opt/kafka/bin/../libs/spotbugs-annotations-3.1.9.jar:/opt/kafka/bin/../libs/tracing-agent.ja
:/opt/kafka/bin/../libs/validation-api-2.0.1.Final.jar:/opt/kafka/bin/../libs/zkclient-0.11.jar:/opt/kafka/bin/../libs/zookeeper-3.4.14.jar:/opt/kafka/bin/../libs/zstd-jni-
.4.0-1.jar:/opt/kafka/libs/kafka-agent.jar (org.apache.zookeeper.ZooKeeper) [main]                                                                                          
2020-04-08 15:01:26,313 INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper) [main]      
2020-04-08 15:01:26,313 INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper) [main]                                                                 
2020-04-08 15:01:26,313 INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper) [main]                                                                  
2020-04-08 15:01:26,313 INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper) [main]                                                                       
2020-04-08 15:01:26,313 INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper) [main]                                                                       
2020-04-08 15:01:26,313 INFO Client environment:os.version=4.19.102+ (org.apache.zookeeper.ZooKeeper) [main]                                                                
2020-04-08 15:01:26,313 INFO Client environment:user.name=kafka (org.apache.zookeeper.ZooKeeper) [main]                                                                     
2020-04-08 15:01:26,313 INFO Client environment:user.home=/home/kafka (org.apache.zookeeper.ZooKeeper) [main]                                                               
2020-04-08 15:01:26,313 INFO Client environment:user.dir=/opt/kafka (org.apache.zookeeper.ZooKeeper) [main]                                                                 
2020-04-08 15:01:26,315 INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@
722c3c3 (org.apache.zookeeper.ZooKeeper) [main]                                                                                                                             
2020-04-08 15:01:26,329 INFO Starting poller (io.strimzi.kafka.agent.KafkaAgent) [main]                                                                                     
2020-04-08 15:01:26,331 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper
ClientCnxn) [main-SendThread(localhost:2181)]                                                                                                                               
2020-04-08 15:01:26,332 INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient) [main]                                               
2020-04-08 15:01:26,336 INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181
]                                                                                                                                                                           
2020-04-08 15:01:32,335 INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient) [main]                                                               
2020-04-08 15:01:32,338 WARN Client session timed out, have not heard from server in 6001ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2
81)]                                                                                                                                                                        
2020-04-08 15:01:32,444 INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper) [main]                                                                                    
2020-04-08 15:01:32,444 INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn) [main-EventThread]                                                    
2020-04-08 15:01:32,446 INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient) [main]                                                                
2020-04-08 15:01:32,450 ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]                                                 
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING                                                                
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:258)                                                                         
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)                                                                                           
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)                                                                                                               
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:254)                                                                                    
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:112)                                                                                                
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1826)                                                                                                          
        at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:364)                                                                                                 
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:387)                                                                                                     
        at kafka.server.KafkaServer.startup(KafkaServer.scala:207)                                                                                                          
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)                                                                                         
        at kafka.Kafka$.main(Kafka.scala:84)                                                                                                                                
        at kafka.Kafka.main(Kafka.scala)                                                                                                                                    
2020-04-08 15:01:32,452 INFO shutting down (kafka.server.KafkaServer) [main]                                                                                                
2020-04-08 15:01:32,459 INFO shut down completed (kafka.server.KafkaServer) [main]                                                                                          
2020-04-08 15:01:32,460 ERROR Exiting Kafka. (kafka.server.KafkaServerStartable) [main]                                                                                     
2020-04-08 15:01:32,462 INFO shutting down (kafka.server.KafkaServer) [kafka-shutdown-hook]                                                                                 
```

Help Please!!!

**Comment by scholzj** [comment]
This looks like it cannot connect to the Zookeeper cluster. But I cannot tell the reasons from jsut this log. I would need to have all the logs to be able to say more. If you can collect and provide them for example using this script: https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh 

Given this problem can be in many parts, the logs from the Kafka pods (both containers) and Zookeeper pods (both containers) toegther with the cluster operator.

Conneting to localhost:2181 is ok, because it connects to the sidecar which is repsonsible for security.

**Comment by pashafirdous** [comment]
Hi Jakub,

could you let me know if there is a pattern to run the script?

**Comment by scholzj** [comment]
Oh, sorry. You should run omething like this: `report.sh --namespace=<namespace> --cluster=<cluster>` where `<cluster>` is the name of your Kafka CR and `<namespace>` is the namespace where the cluster is installed.

**Comment by pashafirdous** [comment]
The issue was internal to GCP.
it fixed without our fix.

**Comment by pashafirdous** [comment]
Hi Team,

Reopening the issue.

i am again facing the problem, and its not related to the GCP.

i am getting the error with some service account permissions logs are below.

please help!!

```
2020-04-21 20:51:37 INFO  Main:117 - The KafkaConnectS2I custom resource definition can only be used in environment which supports OpenShift build, image and apps APIs. These APIs do not seem to be supported in this environment.
2020-04-21 20:51:37 INFO  ClusterOperator:84 - Creating ClusterOperator for namespace *
2020-04-21 20:51:37 INFO  ClusterOperator:101 - Starting ClusterOperator for namespace *
2020-04-21 20:51:37 INFO  ClusterOperator:115 - Opened watch for Kafka operator
2020-04-21 20:51:37 INFO  ClusterOperator:115 - Opened watch for KafkaMirrorMaker operator
2020-04-21 20:51:37 INFO  ClusterOperator:115 - Opened watch for KafkaConnect operator
2020-04-21 20:51:38 INFO  ClusterOperator:115 - Opened watch for KafkaBridge operator
2020-04-21 20:51:38 INFO  ClusterOperator:115 - Opened watch for KafkaMirrorMaker2 operator
2020-04-21 20:51:38 INFO  ClusterOperator:125 - Setting up periodic reconciliation for namespace *
2020-04-21 20:51:38 INFO  ClusterOperator:186 - ClusterOperator is now ready (health server listening on 8080)
2020-04-21 20:51:38 INFO  Main:146 - Cluster Operator verticle started in namespace *
2020-04-21 20:51:54 INFO  OperatorWatcher:40 - Reconciliation #0(watch) Kafka(kafka-operator/my-cluster): Kafka my-cluster in namespace kafka-operator was ADDED
2020-04-21 20:51:54 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta1'
2020-04-21 20:51:55 INFO  AbstractOperator:173 - Reconciliation #0(watch) Kafka(kafka-operator/my-cluster): Kafka my-cluster should be created or updated
2020-04-21 20:51:55 INFO  OperatorWatcher:40 - Reconciliation #1(watch) Kafka(kafka-operator/my-cluster): Kafka my-cluster in namespace kafka-operator was MODIFIED
2020-04-21 20:51:58 WARN  VersionUsageUtils:60 - The client is using resource type 'poddisruptionbudgets' with unstable version 'v1beta1'
2020-04-21 20:52:05 WARN  AbstractOperator:246 - Reconciliation #1(watch) Kafka(kafka-operator/my-cluster): Failed to acquire lock lock::kafka-operator::Kafka::my-cluster within 10000ms.
2020-04-21 20:52:14 WARN  Util:77 - Caught exception while waiting for Pods resource my-cluster-zookeeper-0 in namespace kafka-operator to get ready
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/kafka-operator/pods/my-cluster-zookeeper-0. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:337) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:318) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:833) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:226) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:170) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractReadyResourceOperator.isReady(AbstractReadyResourceOperator.java:56) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$waitFor$4(AbstractResourceOperator.java:340) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.strimzi.operator.common.Util$1.lambda$handle$0(Util.java:70) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-04-21 20:52:14 WARN  Util:77 - Caught exception while waiting for Pods resource my-cluster-zookeeper-1 in namespace kafka-operator to get ready
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/kafka-operator/pods/my-cluster-zookeeper-1. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:337) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:318) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:833) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:226) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:170) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractReadyResourceOperator.isReady(AbstractReadyResourceOperator.java:56) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$waitFor$4(AbstractResourceOperator.java:340) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.strimzi.operator.common.Util$1.lambda$handle$0(Util.java:70) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-04-21 20:52:14 WARN  Util:77 - Caught exception while waiting for Pods resource my-cluster-zookeeper-2 in
```

**Comment by scholzj** [comment]
This looks like some issue with the RBAC files. Are you sure that all the ClusterRoles, RoleBindings and ClusterRoleBindings from the installation fiels are installed? You should be able to check that with `kubectl get clusterroles`, `kubectl get clusterrolebindings` and `kubectl get rolebindings`.

In this case, the error would indicate problem with Cluster Role `strimzi-cluster-operator-namespaced` and RoleBinding `strimzi-cluster-operator`. (in the installation files, the two files with prefix `020-...`).

**Comment by pashafirdous** [comment]
Hi Jakub,
I've installed the RBAC files.
we have modiied the files a bit. 
just replaced strimzi-cluster with kafka in the rbac/sa files.

**Comment by scholzj** [comment]
For the operator it self, the role names or binding names are not important, so that should be fine. But the RBAC error suggests that maybe something went wrong during that?

**Comment by pashafirdous** [comment]
Hi Jakub,

thanks we could identify and fix the RBAC issue. thanks for directing right !!!


now we have another situation.

we have 2 deployments followed by kafka clusters in same cluster but in different namespaces.
the deployment is successfull but please the logs below.

```
 kubectl get kafka --all-namespaces
NAMESPACE             NAME         DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS
kafka-operator-demo   my-cluster   3                        3
kafka-operator        my-cluster   3                        3

```

the Strimzi operator gives error to unable to lock on kafka.



```

kafka-operator-demo          kafka-operator-0-1587625891-skpdq                                0/1     Completed          0          22m
kafka-operator-demo          my-cluster-entity-operator-cdd8f84d4-lkbjd                       3/3     Running            0          4m20s
kafka-operator-demo          my-cluster-kafka-0                                               2/2     Running            0          5m12s
kafka-operator-demo          my-cluster-kafka-1                                               2/2     Running            0          5m12s
kafka-operator-demo          my-cluster-kafka-2                                               2/2     Running            0          5m12s
kafka-operator-demo          my-cluster-zookeeper-0                                           2/2     Running            0          21m
kafka-operator-demo          my-cluster-zookeeper-1                                           2/2     Running            0          21m
kafka-operator-demo          my-cluster-zookeeper-2                                           2/2     Running            0          21m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                1/1     Running            1          22m
kafka-operator               kafka-operator-0-1587626892-hrmrx                                0/1     Completed          0          6m9s
kafka-operator               my-cluster-entity-operator-767cd7df5b-pmnkm                      3/3     Running            0          91s
kafka-operator               my-cluster-kafka-0                                               2/2     Running            0          2m19s
kafka-operator               my-cluster-kafka-1                                               2/2     Running            0          2m19s
kafka-operator               my-cluster-kafka-2                                               2/2     Running            0          2m19s
kafka-operator               my-cluster-zookeeper-0                                           2/2     Running            0          4m18s
kafka-operator               my-cluster-zookeeper-1                                           2/2     Running            0          3m36s
kafka-operator               my-cluster-zookeeper-2                                           2/2     Running            0          2m52s
kafka-operator               strimzi-operator-59b558758d-zxq5r                                1/1     Running            1          5m25s
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                0/1     OOMKilled          1          22m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                0/1     CrashLoopBackOff   1          23m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                0/1     Running            2          23m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                1/1     Running            2          23m
kafka-operator               strimzi-operator-59b558758d-zxq5r                                0/1     OOMKilled          1          7m15s
kafka-operator               strimzi-operator-59b558758d-zxq5r                                0/1     CrashLoopBackOff   1          7m29s
kafka-operator               strimzi-operator-59b558758d-zxq5r                                0/1     Running            2          7m30s
kafka-operator               strimzi-operator-59b558758d-zxq5r                                1/1     Running            2          7m42s
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                0/1     OOMKilled          2          25m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                0/1     CrashLoopBackOff   2          25m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                0/1     Running            3          25m
kafka-operator-demo          strimzi-operator-59b558758d-95vx5                                1/1     Running            3          26m
```


the error logs in one of the strimzi-cluster-operator are as 

```

erator::Kafka::my-cluster within 10000ms.
2020-04-23 08:25:17 INFO  AbstractOperator:317 - Reconciliation #29(watch) Kafka(kafka-operator/my-cluster): reconciled
2020-04-23 08:25:17 INFO  AbstractOperator:173 - Reconciliation #33(watch) Kafka(kafka-operator/my-cluster): Kafka my-cluster should be created or updated
2020-04-23 08:25:17 WARN  AbstractOperator:246 - Reconciliation #32(watch) Kafka(kafka-operator-demo/my-cluster): Failed to acquire lock lock::kafka-operator-demo::Kafka::my-cluster within 10000ms.
2020-04-23 08:25:18 INFO  AbstractOperator:317 - Reconciliation #31(watch) Kafka(kafka-operator-demo/my-cluster): reconciled
2020-04-23 08:25:18 INFO  AbstractOperator:173 - Reconciliation #35(watch) Kafka(kafka-operator-demo/my-cluster): Kafka my-cluster should be created or updated
2020-04-23 08:25:18 WARN  AbstractOperator:246 - Reconciliation #34(watch) Kafka(kafka-operator/my-cluster): Failed to acquire lock lock::kafka-operator::Kafka::my-cluster within 10000ms.
2020-04-23 08:25:20 INFO  AbstractOperator:317 - Reconciliation #33(watch) Kafka(kafka-operator/my-cluster): reconciled
2020-04-23 08:25:20 INFO  AbstractOperator:173 - Reconciliation #37(watch) Kafka(kafka-operator/my-cluster): Kafka my-cluster should be created or updated
2020-04-23 08:25:20 WARN  AbstractOperator:246 - Reconciliation #36(watch) Kafka(kafka-operator-demo/my-cluster): Failed to acquire lock lock::kafka-operator-demo::Kafka::my-cluster within 10000ms.
2020-04-23 08:25:21 INFO  AbstractOperator:317 - Reconciliation #35(watch) Kafka(kafka-operator-demo/my-cluster): reconciled
2020-04-23 08:25:21 INFO  AbstractOperator:173 - Reconciliation #38(watch) Kafka(kafka-operator-demo/my-cluster): Kafka my-cluster should be created or updated
2020-04-23 08:25:22 INFO  AbstractOperator:317 - Reconciliation #37(watch) Kafka(kafka-operator/my-cluster): reconciled
2020-04-23 08:25:23 INFO  AbstractOperator:317 - Reconciliation #38(watch) Kafka(kafka-operator-demo/my-cluster): reconciled
2020-04-23 08:26:40 INFO  ClusterOperator:127 - Triggering periodic reconciliation for namespace *...
2020-04-23 08:26:40 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormakers' with unstable version 'v1beta1'
2020-04-23 08:26:40 INFO  AbstractOperator:173 - Reconciliation #39(timer) Kafka(kafka-operator/my-cluster): Kafka my-cluster should be created or updated
2020-04-23 08:26:40 INFO  AbstractOperator:173 - Reconciliation #40(timer) Kafka(kafka-operator-demo/my-cluster): Kafka my-cluster should be created or updated
2020-04-23 08:26:40 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaconnects' with unstable version 'v1beta1'
2020-04-23 08:26:40 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormaker2s' with unstable version 'v1alpha1'
2020-04-23 08:26:40 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkabridges' with unstable version 'v1alpha1'
2020-04-23 08:26:42 INFO  AbstractOperator:317 - Reconciliation #40(timer) Kafka(kafka-operator-demo/my-cluster): reconciled
2
```

what could be the reason/action plan to address this issue?

**Comment by scholzj** [comment]
What exactly do you mean with the issue? The `Failed to acquire lock lock::kafka-operator-demo::Kafka::my-cluster within 10000ms.` messages?

From the log I can see one issue with your setup ... the log is from an operator watching namespace `*` => that means that it is watching the whole cluster. But from the list of pods above, I can see that you have two operators running. They will be both reconciling the same things and possibly sometimes fighting with each other. You have to either:

* Have just one operator watching the whole cluster (or several selected namespaces)
* Or have multiple operators installed in different namespaces, but make sure that they each watch different set of namespaces

That way you make sure they don't fight with each other.

As for the `Failed to acquire lock lock::kafka-operator-demo::Kafka::my-cluster within 10000ms.`, that is normal in some situation -> it happens when one reconciliation is still running when something tries to trigger another one. But maybe in your case these are triggered more often because of the ultiple operators operating the same resource.

**Comment by pashafirdous** [comment]
Yes you are right, the issue was identical to my previous comment.
the SA created in the namespace wasn't having permissions to create cluster(permissions limited by the Cluster)
the issue got fixed when we gave the SA access with strimzi-admin

**Comment by malikbenkirane** [comment]
> The issue was internal to GCP.
> it fixed without our fix.

any chance you can give us more insights on this internal issue to GCP

On my side the entity operator always restart complaining
```
2021-12-22 07:18:30,96606 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1181 - Opening socket connection to server localhost/127.0.0.1:2181.
2021-12-22 07:18:30,96757 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1183 - SASL config status: Will not attempt to authenticate using SASL (unknown error)
2021-12-22 07:18:30,96891 WARN  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1300 - Session 0x0 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) [org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
```
The logs above are coming from 

On the other hand, that would be really valuable to have some doc specific to this context.

Running gke-1.22 autopilot private cluster
