### ISSUE TITLE
[Question] Zookeeper Connection Problem

### ISSUE THREAD

**Issue by oassuncao** [strimzi/strimzi-kafka-operator#2916]
I have a cluster with 3 zookeepers, sometimes occur a problem with the connection of Zookeepers and my Kafka cluster going down.

I got the logs when the Zookeeper start the connection problem
```
Apr 29, 2020 @ 08:52:50.711	cluster-zookeeper-1	2020-04-29 11:52:50,711 INFO Processing ruok command from /127.0.0.1:55576 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:52:51.074	cluster-zookeeper-0	2020-04-29 11:52:51,074 INFO Processing ruok command from /127.0.0.1:53548 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:52:51.074	cluster-zookeeper-0	2020-04-29 11:52:51,074 INFO Processing ruok command from /127.0.0.1:53548 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:52:53.339	cluster-zookeeper-2	2020-04-29 11:52:53,339 INFO Processing ruok command from /127.0.0.1:38384 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:52:54.447	cluster-zookeeper-0	2020-04-29 11:52:54,445 INFO Processing ruok command from /127.0.0.1:53626 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:52:54.711	cluster-zookeeper-2	2020-04-29 11:52:54,711 INFO Processing ruok command from /127.0.0.1:38402 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-4]
Apr 29, 2020 @ 08:52:54.977	cluster-zookeeper-1	2020-04-29 11:52:54,976 INFO Processing ruok command from /127.0.0.1:55684 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:52:58.206	cluster-zookeeper-1	2020.04.29 11:52:58 LOG5[1:140023021143808]: Service [listener-2181] accepted connection from 10.244.16.225:53588
Apr 29, 2020 @ 08:52:58.223	cluster-zookeeper-1	2020.04.29 11:52:58 LOG5[1:140023021143808]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:52:58.223	cluster-zookeeper-1	2020.04.29 11:52:58 LOG5[1:140023021143808]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
Apr 29, 2020 @ 08:52:58.224	cluster-zookeeper-1	2020.04.29 11:52:58 LOG5[1:140023021143808]: connect_blocking: connected 127.0.0.1:21811
Apr 29, 2020 @ 08:52:58.224	cluster-zookeeper-1	2020.04.29 11:52:58 LOG5[1:140023021143808]: Service [listener-2181] connected remote server from 127.0.0.1:55766
Apr 29, 2020 @ 08:53:00.476	cluster-zookeeper-1	2020-04-29 11:53:00,476 WARN Unable to read additional data from client sessionid 0x2019f80b78d0009, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:00.476	cluster-zookeeper-1	2020.04.29 11:53:00 LOG5[1:140023020156672]: Connection closed: 9165390 byte(s) sent to SSL, 3259711 byte(s) sent to socket
Apr 29, 2020 @ 08:53:00.541	cluster-zookeeper-1	2020-04-29 11:53:00,541 WARN Unable to read additional data from client sessionid 0x1019f88642b0011, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:53:00.542	cluster-zookeeper-1	2020.04.29 11:53:00 LOG5[1:140023020267264]: Connection closed: 8982659 byte(s) sent to SSL, 3176460 byte(s) sent to socket
Apr 29, 2020 @ 08:53:00.620	cluster-zookeeper-1	2020-04-29 11:53:00,618 WARN Unable to read additional data from client sessionid 0x20180d963d30001, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:53:00.620	cluster-zookeeper-1	2020.04.29 11:53:00 LOG5[1:140023020046080]: Connection closed: 535440 byte(s) sent to SSL, 321312 byte(s) sent to socket
Apr 29, 2020 @ 08:53:00.660	cluster-zookeeper-1	2020-04-29 11:53:00,659 WARN Unable to read additional data from client sessionid 0x1019f88642b0003, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:00.660	cluster-zookeeper-1	2020.04.29 11:53:00 LOG5[1:140023020922624]: Connection closed: 4094437 byte(s) sent to SSL, 1885324 byte(s) sent to socket
Apr 29, 2020 @ 08:53:00.704	cluster-zookeeper-1	2020-04-29 11:53:00,703 INFO Processing ruok command from /127.0.0.1:55806 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:53:01.016	cluster-zookeeper-0	2020-04-29 11:53:01,015 INFO Processing ruok command from /127.0.0.1:53764 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:53:01.623	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623804856064]: Service [listener-2181] accepted connection from 10.244.13.87:50054
Apr 29, 2020 @ 08:53:01.630	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623804856064]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:01.631	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623804856064]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-entity-operator
Apr 29, 2020 @ 08:53:01.632	cluster-zookeeper-0	2020-04-29 11:53:01,632 WARN Connection request from old client /127.0.0.1:53778; will be dropped if server is in r-o mode (org.apache.zookeeper.server.ZooKeeperServer) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:01.632	cluster-zookeeper-0	2020-04-29 11:53:01,632 INFO Revalidating client: 0x20180d963d30001 (org.apache.zookeeper.server.quorum.Learner) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:01.632	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623804856064]: connect_blocking: connected 127.0.0.1:21810
Apr 29, 2020 @ 08:53:01.632	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623804856064]: Service [listener-2181] connected remote server from 127.0.0.1:53778
Apr 29, 2020 @ 08:53:01.822	cluster-zookeeper-0	2020-04-29 11:53:01,822 INFO Revalidating client: 0x1019f88642b0011 (org.apache.zookeeper.server.quorum.Learner) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:53:01.822	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623805671168]: Service [listener-2181] accepted connection from 10.244.13.194:47290
Apr 29, 2020 @ 08:53:01.822	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623805671168]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:01.822	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623805671168]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-kafka
Apr 29, 2020 @ 08:53:01.822	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623805671168]: connect_blocking: connected 127.0.0.1:21810
Apr 29, 2020 @ 08:53:01.822	cluster-zookeeper-0	2020.04.29 11:53:01 LOG5[1:140623805671168]: Service [listener-2181] connected remote server from 127.0.0.1:53790
Apr 29, 2020 @ 08:53:01.903	cluster-zookeeper-2	2020.04.29 11:53:01 LOG5[1:139833118459648]: Service [listener-2181] accepted connection from 10.244.16.225:49728
Apr 29, 2020 @ 08:53:01.919	cluster-zookeeper-2	2020.04.29 11:53:01 LOG5[1:139833118459648]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:01.919	cluster-zookeeper-2	2020.04.29 11:53:01 LOG5[1:139833118459648]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
Apr 29, 2020 @ 08:53:01.919	cluster-zookeeper-2	2020.04.29 11:53:01 LOG5[1:139833118459648]: connect_blocking: connected 127.0.0.1:21812
Apr 29, 2020 @ 08:53:01.919	cluster-zookeeper-2	2020.04.29 11:53:01 LOG5[1:139833118459648]: Service [listener-2181] connected remote server from 127.0.0.1:38496
Apr 29, 2020 @ 08:53:02.151	cluster-zookeeper-0	2020.04.29 11:53:02 LOG5[1:140623805892352]: Service [listener-2181] accepted connection from 10.244.14.73:52076
Apr 29, 2020 @ 08:53:02.155	cluster-zookeeper-0	2020.04.29 11:53:02 LOG5[1:140623805892352]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:02.155	cluster-zookeeper-0	2020.04.29 11:53:02 LOG5[1:140623805892352]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-entity-operator
Apr 29, 2020 @ 08:53:02.155	cluster-zookeeper-0	2020.04.29 11:53:02 LOG5[1:140623805892352]: connect_blocking: connected 127.0.0.1:21810
Apr 29, 2020 @ 08:53:02.155	cluster-zookeeper-0	2020.04.29 11:53:02 LOG5[1:140623805892352]: Service [listener-2181] connected remote server from 127.0.0.1:53804
Apr 29, 2020 @ 08:53:02.158	cluster-zookeeper-0	2020-04-29 11:53:02,158 INFO Revalidating client: 0x1019f88642b0003 (org.apache.zookeeper.server.quorum.Learner) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:53:02.235	cluster-zookeeper-2	2020.04.29 11:53:02 LOG5[1:139833118349056]: Service [listener-2181] accepted connection from 10.244.17.27:56052
Apr 29, 2020 @ 08:53:02.242	cluster-zookeeper-2	2020.04.29 11:53:02 LOG5[1:139833118349056]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:02.242	cluster-zookeeper-2	2020.04.29 11:53:02 LOG5[1:139833118349056]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-kafka
Apr 29, 2020 @ 08:53:02.243	cluster-zookeeper-2	2020.04.29 11:53:02 LOG5[1:139833118349056]: connect_blocking: connected 127.0.0.1:21812
Apr 29, 2020 @ 08:53:02.243	cluster-zookeeper-2	2020.04.29 11:53:02 LOG5[1:139833118349056]: Service [listener-2181] connected remote server from 127.0.0.1:38514
Apr 29, 2020 @ 08:53:02.244	cluster-zookeeper-2	2020-04-29 11:53:02,244 INFO Revalidating client: 0x2019f80b78d0009 (org.apache.zookeeper.server.quorum.Learner) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:53:03.385	cluster-zookeeper-2	2020-04-29 11:53:03,378 INFO Processing ruok command from /127.0.0.1:38528 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:04.364	cluster-zookeeper-0	2020-04-29 11:53:04,363 INFO Processing ruok command from /127.0.0.1:53856 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:53:04.682	cluster-zookeeper-2	2020.04.29 11:53:04 LOG5[1:139833117865728]: Connection closed: 1508569 byte(s) sent to SSL, 522465 byte(s) sent to socket
Apr 29, 2020 @ 08:53:04.684	cluster-zookeeper-2	2020-04-29 11:53:04,681 WARN Unable to read additional data from client sessionid 0x3019f83d2f60002, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:53:04.712	cluster-zookeeper-2	2020-04-29 11:53:04,712 INFO Processing ruok command from /127.0.0.1:38546 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:53:04.966	cluster-zookeeper-1	2020-04-29 11:53:04,966 INFO Processing ruok command from /127.0.0.1:55904 (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-4]
Apr 29, 2020 @ 08:53:05.484	cluster-zookeeper-0	2020.04.29 11:53:05 LOG5[1:140623806002944]: Service [listener-2181] accepted connection from 10.244.16.225:52016
Apr 29, 2020 @ 08:53:05.504	cluster-zookeeper-0	2020.04.29 11:53:05 LOG5[1:140623806002944]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:05.504	cluster-zookeeper-0	2020.04.29 11:53:05 LOG5[1:140623806002944]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
Apr 29, 2020 @ 08:53:05.504	cluster-zookeeper-0	2020.04.29 11:53:05 LOG5[1:140623806002944]: connect_blocking: connected 127.0.0.1:21810
Apr 29, 2020 @ 08:53:05.504	cluster-zookeeper-0	2020.04.29 11:53:05 LOG5[1:140623806002944]: Service [listener-2181] connected remote server from 127.0.0.1:53878
Apr 29, 2020 @ 08:53:06.250	cluster-zookeeper-2	2020-04-29 11:53:06,250 WARN Unable to read additional data from client sessionid 0x2019f80b78d0009, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-4]
Apr 29, 2020 @ 08:53:06.250	cluster-zookeeper-2	2020.04.29 11:53:06 LOG5[1:139833118349056]: Connection closed: 41 byte(s) sent to SSL, 127 byte(s) sent to socket
Apr 29, 2020 @ 08:53:06.728	cluster-zookeeper-1	2020.04.29 11:53:06 LOG5[1:140023020922624]: Service [listener-2181] accepted connection from 10.244.14.73:52140
Apr 29, 2020 @ 08:53:06.733	cluster-zookeeper-1	2020.04.29 11:53:06 LOG5[1:140023020922624]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:06.734	cluster-zookeeper-1	2020.04.29 11:53:06 LOG5[1:140023020922624]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-entity-operator
Apr 29, 2020 @ 08:53:06.735	cluster-zookeeper-1	2020.04.29 11:53:06 LOG5[1:140023020922624]: connect_blocking: connected 127.0.0.1:21811
Apr 29, 2020 @ 08:53:06.735	cluster-zookeeper-1	2020.04.29 11:53:06 LOG5[1:140023020922624]: Service [listener-2181] connected remote server from 127.0.0.1:55934
Apr 29, 2020 @ 08:53:07.641	cluster-zookeeper-0	2020-04-29 11:53:07,641 WARN Unable to read additional data from client sessionid 0x20180d963d30001, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-2]
Apr 29, 2020 @ 08:53:07.642	cluster-zookeeper-0	2020.04.29 11:53:07 LOG5[1:140623804856064]: Connection closed: 60 byte(s) sent to SSL, 84 byte(s) sent to socket
Apr 29, 2020 @ 08:53:07.834	cluster-zookeeper-0	2020-04-29 11:53:07,833 WARN Unable to read additional data from client sessionid 0x1019f88642b0011, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-3]
Apr 29, 2020 @ 08:53:07.834	cluster-zookeeper-0	2020.04.29 11:53:07 LOG5[1:140623805671168]: Connection closed: 81 byte(s) sent to SSL, 139 byte(s) sent to socket
Apr 29, 2020 @ 08:53:08.053	cluster-zookeeper-1	2020.04.29 11:53:08 LOG5[1:140023020046080]: Service [listener-2181] accepted connection from 10.244.17.27:56130
Apr 29, 2020 @ 08:53:08.057	cluster-zookeeper-1	2020.04.29 11:53:08 LOG5[1:140023020046080]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
Apr 29, 2020 @ 08:53:08.058	cluster-zookeeper-1	2020.04.29 11:53:08 LOG5[1:140023020046080]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-kafka
Apr 29, 2020 @ 08:53:08.058	cluster-zookeeper-1	2020.04.29 11:53:08 LOG5[1:140023020046080]: connect_blocking: connected 127.0.0.1:21811
Apr 29, 2020 @ 08:53:08.058	cluster-zookeeper-1	2020.04.29 11:53:08 LOG5[1:140023020046080]: Service [listener-2181] connected remote server from 127.0.0.1:55970
Apr 29, 2020 @ 08:53:08.153	cluster-zookeeper-0	2020-04-29 11:53:08,152 WARN Unable to read additional data from client sessionid 0x1019f88642b0003, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:08.154	cluster-zookeeper-0	2020.04.29 11:53:08 LOG5[1:140623805892352]: Connection closed: 61 byte(s) sent to SSL, 73 byte(s) sent to socket
Apr 29, 2020 @ 08:53:08.453	cluster-zookeeper-0	2020-04-29 11:53:08,453 WARN Unable to read additional data from client sessionid 0x3019f83d2f6000c, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-4]
Apr 29, 2020 @ 08:53:08.453	cluster-zookeeper-0	2020.04.29 11:53:08 LOG5[1:140623805781760]: Connection closed: 9495079 byte(s) sent to SSL, 3398084 byte(s) sent to socket
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1		at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1		at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1		at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1		at org.apache.zookeeper.server.quorum.LearnerHandler.shutdown(LearnerHandler.java:926)
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1		at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:647)
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1	2020-04-29 11:53:08,465 WARN Closing connection to peer due to transaction timeout. (org.apache.zookeeper.server.quorum.LearnerHandler) [QuorumPeer[myid=2](plain=/127.0.0.1:21811)(secure=disabled)]
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1	2020-04-29 11:53:08,465 WARN Closing connection to peer due to transaction timeout. (org.apache.zookeeper.server.quorum.LearnerHandler) [QuorumPeer[myid=2](plain=/127.0.0.1:21811)(secure=disabled)]
Apr 29, 2020 @ 08:53:08.466	cluster-zookeeper-1	2020-04-29 11:53:08,465 WARN ******* GOODBYE /127.0.0.1:52750 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [LearnerHandler-/127.0.0.1:52750]
```

After the first logs, my cluster doesn't work properly.
```
Apr 29, 2020 @ 08:53:00.476	cluster-zookeeper-1	2020-04-29 11:53:00,476 WARN Unable to read additional data from client sessionid 0x2019f80b78d0009, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn) [NIOWorkerThread-1]
Apr 29, 2020 @ 08:53:00.476	cluster-zookeeper-1	2020.04.29 11:53:00 LOG5[1:140023020156672]: Connection closed: 9165390 byte(s) sent to SSL, 3259711 byte(s) sent to socket
```

My cluster take a long time to goes up again and work properly

**Comment by oassuncao** [comment]
https://github.com/strimzi/strimzi-kafka-operator/issues/1934

**Comment by scholzj** [comment]
The log is really hard to read because it mixes 6 containers into one stream of messages. It might be more useful as 6 separate logs.

I do not see any obvious errors in there. Have you configured the memory and CPU request for the Zookeeper and Kafka pods? Also, what exactly does _Kafka cluster going down_ mean? The Kafka pods normally keep runnign even without Zookeeper.

**Comment by oassuncao** [comment]
I put all the log together to see the timeline of the logs

I have configured the Memory and CPU request.

Zookeeper resources:
```yaml
    resources:
      limits:
        cpu: 2000m
        memory: 3072Mi
      requests:
        cpu: 500m
        memory: 1536Mi
```

Kafka resources:
```yaml
    resources:
      limits:
        cpu: 3000m
        memory: 3072Mi
      requests:
        cpu: 750m
        memory: 1536Mi
```

My Kafka pods receive the error bellow:
```
2020-04-29 11:53:00,541 WARN Client session timed out, have not heard from server in 4002ms for sessionid 0x1019f88642b0011 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:00,541 INFO Client session timed out, have not heard from server in 4002ms for sessionid 0x1019f88642b0011, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:01,812 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:01,813 INFO Socket connection established, initiating session, client: /127.0.0.1:34142, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:01,826 INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1019f88642b0011, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:07,833 WARN Client session timed out, have not heard from server in 4002ms for sessionid 0x1019f88642b0011 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:07,833 INFO Client session timed out, have not heard from server in 4002ms for sessionid 0x1019f88642b0011, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:09,167 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:09,168 INFO Socket connection established, initiating session, client: /127.0.0.1:34340, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:09,187 WARN Session 0x1019f88642b0011 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
2020-04-29 11:53:11,042 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:11,042 INFO Socket connection established, initiating session, client: /127.0.0.1:34402, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-04-29 11:53:11,055 WARN Session 0x1019f88642b0011 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
```

**Comment by oassuncao** [comment]
The resource utilization of Zookeeper
![image](https://user-images.githubusercontent.com/3209775/80612643-9f026480-8a12-11ea-90d5-c11ee572f115.png)

The resource utilization of Kafka
![image](https://user-images.githubusercontent.com/3209775/80612708-b80b1580-8a12-11ea-9168-d40d1f14d9b5.png)

**Comment by scholzj** [comment]
Not saying it is related, but some notes to your config:
* The Kubernetes request is the guaranteed memory -> so that is what you should plan with in your pod. The pods can use the memeory up to the limit, the limit memory is not guaranteed and can be taken away which will not work well for something like Kafka or Zookeeper. So I in general recommend for Kafka and Zoo to not set the memory limit or set it to the saem as the request.
* The -Xmx should be driven by the guaranteed memory, but Kafka and Zoo need also other memory. So with `request: 1536Mi` I would for example set `-Xmx: 512M`.

Not sure this helps, but might be worth trying. But the error could be caused by many different things -> such as some network glitches etc.

**Comment by oassuncao** [comment]
I changed my memory requests and `-Xmx`.

I will check if the problem occurs after these changes

**Comment by scholzj** [comment]
@oassuncao Did changing the memeory settings help? Can we close this?

**Comment by oassuncao** [comment]
The problem was resolved. I'm closing the issue
