### ISSUE TITLE
[Bug] Detection of Kuberetes version failed.

### ISSUE THREAD

**Issue by harjis** [strimzi/strimzi-kafka-operator#2920]
Hi!

I'm following the steps in quick start and they worked earlier this week but now for some reason cluster operator fails to start. I have tried to delete and re-create minikube but no luck so far.

**To Reproduce**
I have copied the yaml files here: https://github.com/harjis/strimzi-quick-start
I execute that repositories init.sh
```sh
kubectl create ns kafka
kubectl create ns my-kafka-project
kubectl apply -f cluster-operator/ -n kafka
kubectl apply -f cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n my-kafka-project
kubectl apply -f cluster-operator/032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml -n my-kafka-project
kubectl apply -f cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n my-kafka-project
kubectl create -n my-kafka-project -f my-kafka.yaml
kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n my-kafka-project
kubectl create -n my-kafka-project -f my-topic.yaml
```

**Expected behavior**
Before cluster and topic was created successfully but at the moment the operator fails to start.

**Environment (please complete the following information):**
 - Strimzi version: I guess master
 - Installation method: YAML
 - Kubernetes cluster: minikube v1.8.2 on Darwin 10.15.3 Kubernetes v1.17.3 on Docker 19.03.6
 - Infrastructure: Minikube

**YAML files and logs**
```
❯ kubectl logs strimzi-cluster-operator-59f7944b46-pmh25 -n kafka
+ shift
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/io.netty.netty-handler-4.1.45.Final.jar:lib/org.keycloak.keycloak-core-7.0.0.jar:lib/io.netty.netty-codec-http-4.1.45.Final.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.jar:lib/org.quartz-scheduler.quartz-2.2.1.jar:lib/io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.netty.netty-buffer-4.1.45.Final.jar:lib/org.yaml.snakeyaml-1.24.jar:lib/io.fabric8.openshift-client-4.6.4.jar:lib/io.strimzi.api-0.18.0-SNAPSHOT.jar:lib/io.netty.netty-common-4.1.45.Final.jar:lib/org.apache.logging.log4j.log4j-api-2.13.0.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/org.hdrhistogram.HdrHistogram-2.1.11.jar:lib/io.prometheus.simpleclient-0.7.0.jar:lib/io.strimzi.kafka-oauth-common-0.4.0.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.2.jar:lib/org.keycloak.keycloak-common-7.0.0.jar:lib/io.strimzi.certificate-manager-0.18.0-SNAPSHOT.jar:lib/io.netty.netty-codec-4.1.45.Final.jar:lib/io.micrometer.micrometer-core-1.3.1.jar:lib/io.strimzi.kafka-oauth-server-0.4.0.jar:lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:lib/io.vertx.vertx-core-3.8.5.jar:lib/io.netty.netty-codec-dns-4.1.45.Final.jar:lib/io.fabric8.kubernetes-model-4.6.4.jar:lib/io.netty.netty-codec-socks-4.1.45.Final.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.netty.netty-resolver-4.1.45.Final.jar:lib/com.github.luben.zstd-jni-1.4.4-7.jar:lib/io.netty.netty-handler-proxy-4.1.45.Final.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/org.lz4.lz4-java-1.7.1.jar:lib/io.netty.netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:lib/io.netty.netty-transport-native-unix-common-4.1.45.Final.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/io.vertx.vertx-micrometer-metrics-3.8.5.jar:lib/org.apache.kafka.kafka-clients-2.5.0.jar:lib/com.fasterxml.jackson.core.jackson-core-2.10.2.jar:lib/io.netty.netty-transport-4.1.45.Final.jar:lib/org.apache.zookeeper.zookeeper-jute-3.5.7.jar:lib/io.netty.netty-transport-native-epoll-4.1.45.Final.jar:lib/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.13.0.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.10.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/org.apache.zookeeper.zookeeper-3.5.7.jar:lib/io.strimzi.crd-annotations-0.18.0-SNAPSHOT.jar:lib/io.fabric8.kubernetes-client-4.6.4.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.2.jar:lib/com.squareup.okhttp3.okhttp-3.12.6.jar:lib/io.netty.netty-codec-http2-4.1.45.Final.jar:lib/org.apache.logging.log4j.log4j-core-2.13.0.jar:lib/io.fabric8.kubernetes-model-common-4.6.4.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.10.2.jar:lib/io.netty.netty-resolver-dns-4.1.45.Final.jar:lib/io.strimzi.kafka-oauth-client-0.4.0.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/org.latencyutils.LatencyUtils-2.0.3.jar:lib/io.strimzi.config-model-0.18.0-SNAPSHOT.jar:lib/io.micrometer.micrometer-registry-prometheus-1.3.1.jar io.strimzi.operator.cluster.Main
2020-04-29 19:52:18 INFO  Main:58 - ClusterOperator 0.18.0-SNAPSHOT is starting
2020-04-29 19:52:19 ERROR PlatformFeaturesAvailability:124 - Detection of Kuberetes version failed.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:293) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:122) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_252]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_252]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_252]
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[?:1.8.0_252]
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[?:1.8.0_252]
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:894) ~[?:1.8.0_252]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:865) ~[?:1.8.0_252]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[?:1.8.0_252]
	at okio.Okio$1.write(Okio.java:79) ~[com.squareup.okio.okio-1.15.0.jar:?]
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[com.squareup.okio.okio-1.15.0.jar:?]
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224) ~[com.squareup.okio.okio-1.15.0.jar:?]
	at okhttp3.internal.http2.Http2Writer.settings(Http2Writer.java:203) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:514) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:504) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RealConnection.startHttp2(RealConnection.java:299) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:288) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:111) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:46) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	... 8 more
2020-04-29 19:52:19 ERROR Main:85 - Failed to gather environment facts
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:293) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:122) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_252]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_252]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_252]
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[?:1.8.0_252]
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[?:1.8.0_252]
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:894) ~[?:1.8.0_252]
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:865) ~[?:1.8.0_252]
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[?:1.8.0_252]
	at okio.Okio$1.write(Okio.java:79) ~[com.squareup.okio.okio-1.15.0.jar:?]
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[com.squareup.okio.okio-1.15.0.jar:?]
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224) ~[com.squareup.okio.okio-1.15.0.jar:?]
	at okhttp3.internal.http2.Http2Writer.settings(Http2Writer.java:203) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:514) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:504) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RealConnection.startHttp2(RealConnection.java:299) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:288) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:111) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:93) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:46) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	... 8 more
```
[report-29-04-2020_22-58-05.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4554293/report-29-04-2020_22-58-05.zip)

**Comment by scholzj** [comment]
This looks like some environment issue. The error basically says that it failed to connect to the Kuebrnetes API server. Minikube normally works fine for me on MacOS. So TBH I have no idea what the problem could be.

**Comment by harjis** [comment]
Thanks for the quick response! I suppose the problem might be with KubernetesClient and too new Kubernetes version. I tried to start minikube with an older version: `minikube start --kubernetes-version v1.15.3` and now everything is working as expected.

**Comment by harjis** [comment]
I'll close the issue as the problem doesn't seem to be in this library.

**Comment by scholzj** [comment]
I'm using Strimzi without any problems with Kube 1.18.2. So I do not think that is a problem. From the error it looks more like some TCP issue. Have you tried just deting the Minikube and starting it again? Or giving it more cpu/memeory?

**Comment by harjis** [comment]
Yeah I tried `minikube delete` and `minikube start` many times but nothing changed.

**Comment by harjis** [comment]
Minikube has these resources:
```
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
```

If you think this is too little I can try out increasing them

**Comment by harjis** [comment]
I tried increasing the resources but I get the same error message:

```sh
❯ minikube start --cpus=4 --memory=8000
😄  minikube v1.9.2 on Darwin 10.15.3
✨  Automatically selected the hyperkit driver. Other choices: docker, virtualbox
👍  Starting control plane node m01 in cluster minikube
🔥  Creating hyperkit VM (CPUs=4, Memory=8000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

❗  /usr/local/bin/kubectl is v1.15.5, which may be incompatible with Kubernetes v1.18.0.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version

```

**Comment by iamkousik** [comment]
I have resolved the issue by adding the following environment variable to the Strimzi Operator deployment configuration:

```
- name: STRIMZI_KUBERNETES_VERSION
   value: "major=1,minor=33"
```
