### ISSUE TITLE
[Can we add delay to pod startup?]

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#2936]
Hi Folks!

With regards to [Designating Strimzi administrators](https://strimzi.io/docs/operators/master/using.html#adding-users-the-strimzi-admin-role-str) for `strimzi-admin`.
when i launch a cluster with `Cluster-role-binding` with below command, the operator gives error

```kubectl create clusterrolebinding cluster-admin-kafka --clusterrole=strimzi-admin --serviceaccount kafka-ns:kafka-sa```

ERROR
```
2020-05-02 16:50:32 INFO  Main:117 - The KafkaConnectS2I custom resource definition can only be used in environment which supports OpenShift build, image and apps APIs. These APIs do not seem to be supported in this environment.
2020-05-02 16:50:32 INFO  ClusterOperator:82 - Creating ClusterOperator for namespace kafka-operator-demo-11
2020-05-02 16:50:32 INFO  ClusterOperator:99 - Starting ClusterOperator for namespace kafka-operator-demo-11
2020-05-02 16:50:32 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 403, Status: 403 - kafkas.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafka-operator-demo-11:kafka-sa" cannot watch resource "kafkas" in API group "kafka.strimzi.io" in the namespace "kafka-operator-demo-11"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-05-02 16:50:32 INFO  AbstractOperator:250 - Watcher closed in namespace kafka-operator-demo-11
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@77c06545 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6b8a1fdd[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
        at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:318)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:50)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:221)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

but when i create a `clusterrolebinding` with _**cluster-admin**_ the strimzi-operator works perfect.

please advice on the designating permissions to serviceaccount.

**Comment by scholzj** [comment]
TBH, it is not completely clear to me what are you trying to do. The strimzi-admin roles are expected to be given to users who will be creating and manageging the Kafka resources (clusters, topics etc.). It has nothing to do with the operator it self. The log you shard is from the operator but suggests that the operator it self is missing some rights. The operator should be installed with the RBAC files from the `install/cluster-operator` directory. Not with the `strimzi-admin` roles.

**Comment by pashafirdous** [comment]
Hello Jakub,

so i have a GKE cluster deployment of strimzi kafka.
the deployment is so managed that we need Designated Cluster roles to bind the SA **`kafka-ns:kafka-sa`** so it can perform the cluster admin activities.

so far we were using *`cluster-admin`* to provide the permissions. however when we are trying to leverage 'strimzi-admin' account in below command, we get the error as posted above.
`kubectl create clusterrolebinding cluster-admin-kafka --clusterrole=strimzi-admin --serviceaccount kafka-ns:kafka-sa`


Just to clear, the cluster is installed with all RBAC's and CRD's. 
we are only trying to apply a designated role **`strimzi-admin`** [LINK](https://github.com/strimzi/strimzi-kafka-operator/tree/master/install/strimzi-admin)

**Comment by scholzj** [comment]
But as I said, the `strimzi-admin` roles are not supposed to be used by the operator. The operator has its own roles which it uses which are part of its own installation files. The `strimzi-admin` roles are there to give right to users to create and manage the Kafka clusters - not to the operator.

From your log it is clear that the cluster operator is no installed with its own RBAC files. It has a non-standrd service account and it does not have the RBAC rights it needs.

**Comment by pashafirdous** [comment]
Thanks Jakub,

the cluster had restrictions on using the Strimzi-admin role as designated role.
we had to visit the issue to fix it.

we can close the case, but want to check is there a way to keep timer between starting/rolling up of broker nodes when they are updated?
for example if i want to add a 20 minute starting time between 2 broker nodes?

**Comment by scholzj** [comment]
No, there is no way to add such timer. What would it be useful for?

**Comment by pashafirdous** [comment]
we observed that the kafka broker nodes if upgraded/rebooted right one after other, the cluster gets a bit shaky as the data on our nodes is huge about 10 TB per node.
it is requested to us to add or look up for this functionality.

**Comment by scholzj** [comment]
I think it would be great if you can provide more information about what does _a bit shaky_ mean. In general, we want to have a solution which works out of the box without figuring out how much timeout you need to have  depending on your broker size etc. 

Currently, when the brokers are rolled up we observe the partitions to make sure they re-sync before we restart the next pod, thatthey don't get under-replicated where possible etc. That should ensure that the rolling update is as smooth as possible. And if it isn't the case, we want to understand the problem and fix it the way which works for everyone and not just after some additional timeout settings.

**Comment by pashafirdous** [comment]
thanks for your explaination.
we dont have a example now. will reopen or link to this case once we have more info
