### ISSUE TITLE
[Question]  Contains object at path spec.kafka.storage with an unknown property: volumes

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#2986]
Hello;
I've a bare-metal Kubernetes 1.18.2 and using Vsphere CPI/CNS drivers to access storage.
I've installed Strimzi as described in OperatorHub in a custom namespace "kafka".
Then I've installed a Kafka cluster in the same namespace with the operator by using following yaml:

kafka-persistent.yaml
```
	apiVersion: kafka.strimzi.io/v1beta1
	kind: Kafka
	metadata:
	  name: kafka-beytepe
	spec:
	  kafka:
	    version: 2.4.0
	    replicas: 3
	    listeners:
	      plain: {}
	      tls: {}
	    config:
	      offsets.topic.replication.factor: 3
	      transaction.state.log.replication.factor: 3
	      transaction.state.log.min.isr: 2
	      log.message.format.version: "2.4"
	    storage:
	      type: persistent-claim
	      volumes:
	      - id: 1
	        type: persistent-claim
	        size: 10Gi
	        class: sata
	        deleteClaim: false
	  zookeeper:
	    replicas: 3
	    storage:
	      type: persistent-claim
	      size: 10Gi
	      class: sata
	      deleteClaim: false
	  entityOperator:
	    topicOperator: {}
	    userOperator: {}
```
It looks like Kafka pods weren't created.

```
devadmin@vdi-mk2-ubn:~$ kubectl get kafka -n kafka
NAME            DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS
kafka-beytepe   3                        3
devadmin@vdi-mk2-ubn:~$ kubectl get pods -n kafka
NAME                                        READY   STATUS    RESTARTS   AGE
kafka-beytepe-zookeeper-0                   2/2     Running   2          4d6h
kafka-beytepe-zookeeper-1                   2/2     Running   2          4d6h
kafka-beytepe-zookeeper-2                   2/2     Running   2          4d6h
strimzi-cluster-operator-6c8d574d49-7th6c   1/1     Running   4          4d6h
devadmin@vdi-mk2-ubn:~$ kubectl get svc -n kafka
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kafka-beytepe-zookeeper-client   ClusterIP   10.110.193.200   <none>        2181/TCP                     4d6h
kafka-beytepe-zookeeper-nodes    ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   4d6h
devadmin@vdi-mk2-ubn:~$ kubectl logs strimzi-cluster-operator-6c8d574d49-7th6c -n kafka | grep -A 5 -B 2 WARN | head -n20
2020-05-11 01:26:18 INFO  Main:145 - Cluster Operator verticle started in namespace kafka
2020-05-11 01:26:18 INFO  OperatorWatcher:40 - Reconciliation #0(watch) Kafka(kafka/kafka-beytepe): Kafka kafka-beytepe in namespace kafka was ADDED
2020-05-11 01:26:18 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta1'
2020-05-11 01:26:19 WARN  AbstractOperator:106 - Kafka resource kafka-beytepe in namespace kafka: Contains object at path spec.kafka.storage with an unknown property: volumes
2020-05-11 01:26:19 INFO  AbstractOperator:122 - Reconciliation #0(watch) Kafka(kafka/kafka-beytepe): Kafka kafka-beytepe should be created or updated
2020-05-11 01:26:24 WARN  VersionUsageUtils:60 - The client is using resource type 'poddisruptionbudgets' with unstable version 'v1beta1'
2020-05-11 01:26:29 ERROR AbstractOperator:124 - Reconciliation #0(watch) Kafka(kafka/kafka-beytepe): createOrUpdate failed
io.strimzi.operator.cluster.model.InvalidResourceException: The size is mandatory for a persistent-claim storage
        at io.strimzi.operator.cluster.model.AbstractModel.checkPersistentStorageSize(AbstractModel.java:464) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.AbstractModel.validatePersistentStorage(AbstractModel.java:445) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.AbstractModel.setStorage(AbstractModel.java:433) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
--
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-05-11 01:26:29 WARN  AbstractOperator:268 - Reconciliation #0(watch) Kafka(kafka/kafka-beytepe): Failed to reconcile
io.strimzi.operator.cluster.model.InvalidResourceException: The size is mandatory for a persistent-claim storage
        at io.strimzi.operator.cluster.model.AbstractModel.checkPersistentStorageSize(AbstractModel.java:464) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.AbstractModel.validatePersistentStorage(AbstractModel.java:445) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.AbstractModel.setStorage(AbstractModel.java:433) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.KafkaCluster.fromCrd(KafkaCluster.java:479) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
devadmin@vdi-mk2-ubn:~$ kubectl describe pod strimzi-cluster-operator-6c8d574d49-7th6c -n kafka
Name:         strimzi-cluster-operator-6c8d574d49-7th6c
Namespace:    kafka
Priority:     0
Node:         dev1-worker2/192.168.215.148
Start Time:   Thu, 07 May 2020 02:28:44 +0300
Labels:       name=strimzi-cluster-operator
              pod-template-hash=6c8d574d49
              strimzi.io/kind=cluster-operator
Annotations:  <none>
Status:       Running
IP:           10.244.2.37
IPs:
  IP:           10.244.2.37
Controlled By:  ReplicaSet/strimzi-cluster-operator-6c8d574d49
Containers:
  strimzi-cluster-operator:
    Container ID:  docker://d641eae3d311d5d14f610f51af673d452bda7a5c9b4b9bd3a7679e7f068dd034
    Image:         strimzi/operator:0.17.0
    Image ID:      docker-pullable://strimzi/operator@sha256:a789a21d93e73fb2fcc1981e721697296696f8900c7dd7a018838f54e62ea0ac
    Port:          <none>
    Host Port:     <none>
    Args:
      /opt/strimzi/bin/cluster_operator_run.sh
    State:          Running
      Started:      Mon, 11 May 2020 04:26:02 +0300
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Sun, 10 May 2020 00:47:25 +0300
      Finished:     Mon, 11 May 2020 04:26:00 +0300
    Ready:          True
    Restart Count:  4
    Limits:
      cpu:     1
      memory:  256Mi
    Requests:
      cpu:      200m
      memory:   256Mi
    Liveness:   http-get http://:8080/healthy delay=10s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/ready delay=10s timeout=1s period=30s #success=1 #failure=3
    Environment:
      STRIMZI_NAMESPACE:                                  kafka (v1:metadata.namespace)
      STRIMZI_FULL_RECONCILIATION_INTERVAL_MS:            120000
      STRIMZI_OPERATION_TIMEOUT_MS:                       300000
      STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE:  strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE:            strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE:        strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE:               strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_KAFKA_IMAGES:                               2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_CONNECT_IMAGES:                       2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_CONNECT_S2I_IMAGES:                   2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_MIRROR_MAKER_IMAGES:                  2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES:                2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE:               strimzi/operator:0.17.0
      STRIMZI_DEFAULT_USER_OPERATOR_IMAGE:                strimzi/operator:0.17.0
      STRIMZI_DEFAULT_KAFKA_INIT_IMAGE:                   strimzi/operator:0.17.0
      STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE:                 strimzi/kafka-bridge:0.15.2
      STRIMZI_DEFAULT_JMXTRANS_IMAGE:                     strimzi/jmxtrans:0.17.0
      STRIMZI_LOG_LEVEL:                                  INFO
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from strimzi-cluster-operator-token-jzccn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  strimzi-cluster-operator-token-jzccn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  strimzi-cluster-operator-token-jzccn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

What am I missing? Where should I look for the problem?

**Comment by scholzj** [comment]
This is caused by a typo in your YAML. You have:

```yaml
	    storage:
	      type: persistent-claim
	      volumes:
	      - id: 1
	        type: persistent-claim
	        size: 10Gi
	        class: sata
	        deleteClaim: false
```

but it should really be:

```yaml
	    storage:
	      type: jbod
	      volumes:
	      - id: 1
	        type: persistent-claim
	        size: 10Gi
	        class: sata
	        deleteClaim: false
```

See for exampel here: https://github.com/strimzi/strimzi-kafka-operator/blob/5929226f9ee57e6453f0f050675434b5c9e1445e/examples/kafka/kafka-jbod.yaml#L18

**Comment by tirelibirefe** [comment]
thanks for the advise; I tried what you advised. Now I don't have even zookeepers.

```
[devadmin@vdi-mk4-cnt ~]$ cat kafka-persistent-custom.yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-beytepe
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        class: sata
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      class: sata
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
	
[devadmin@vdi-mk4-cnt ~]$ kubectl get all -n kafka
NAME                                            READY   STATUS    RESTARTS   AGE
pod/strimzi-cluster-operator-6c8d574d49-7th6c   1/1     Running   4          4d7h

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/strimzi-cluster-operator   1/1     1            1           4d7h

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/strimzi-cluster-operator-6c8d574d49   1         1         1       4d7h
[devadmin@vdi-mk4-cnt ~]$ kubectl describe replicaset.apps/strimzi-cluster-operator-6c8d574d49 -n kafka
Name:           strimzi-cluster-operator-6c8d574d49
Namespace:      kafka
Selector:       name=strimzi-cluster-operator,pod-template-hash=6c8d574d49,strimzi.io/kind=cluster-operator
Labels:         name=strimzi-cluster-operator
                pod-template-hash=6c8d574d49
                strimzi.io/kind=cluster-operator
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 1
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/strimzi-cluster-operator
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           name=strimzi-cluster-operator
                    pod-template-hash=6c8d574d49
                    strimzi.io/kind=cluster-operator
  Service Account:  strimzi-cluster-operator
  Containers:
   strimzi-cluster-operator:
    Image:      strimzi/operator:0.17.0
    Port:       <none>
    Host Port:  <none>
    Args:
      /opt/strimzi/bin/cluster_operator_run.sh
    Limits:
      cpu:     1
      memory:  256Mi
    Requests:
      cpu:      200m
      memory:   256Mi
    Liveness:   http-get http://:8080/healthy delay=10s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/ready delay=10s timeout=1s period=30s #success=1 #failure=3
    Environment:
      STRIMZI_NAMESPACE:                                   (v1:metadata.namespace)
      STRIMZI_FULL_RECONCILIATION_INTERVAL_MS:            120000
      STRIMZI_OPERATION_TIMEOUT_MS:                       300000
      STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE:  strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE:            strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE:        strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE:               strimzi/kafka:0.17.0-kafka-2.4.0
      STRIMZI_KAFKA_IMAGES:                               2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_CONNECT_IMAGES:                       2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_CONNECT_S2I_IMAGES:                   2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_MIRROR_MAKER_IMAGES:                  2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
                                                          2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES:                2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0

      STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE:               strimzi/operator:0.17.0
      STRIMZI_DEFAULT_USER_OPERATOR_IMAGE:                strimzi/operator:0.17.0
      STRIMZI_DEFAULT_KAFKA_INIT_IMAGE:                   strimzi/operator:0.17.0
      STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE:                 strimzi/kafka-bridge:0.15.2
      STRIMZI_DEFAULT_JMXTRANS_IMAGE:                     strimzi/jmxtrans:0.17.0
      STRIMZI_LOG_LEVEL:                                  INFO
    Mounts:                                               <none>
  Volumes:                                                <none>
Events:                                                   <none>


```

**Comment by scholzj** [comment]
Can you share the log from the cluster operator? What does it mean that "you don't have even Zookeeper"? Were the pods which existed deleted?

**Comment by scholzj** [comment]
Oh, I can see the problem. I didn't suggested you use the whole example. I suggested you to change the type of the storage. Now you are trying to deploy Kafka 2.5.0 which is not supported in 0.17.0. Just use the original YAML you had and fix the type in the storage.

**Comment by tirelibirefe** [comment]
I've deleted existing kafka cluster, reinstalled by using corrected first yaml file:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-beytepe
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
    storage:
      type: jbod
      volumes:
      - id: 1
        type: persistent-claim
        size: 10Gi
        class: sata
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      class: sata
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

```
[devadmin@vdi-mk4-cnt ~]$ kubectl get all -n kafka
NAME                                            READY   STATUS    RESTARTS   AGE
pod/strimzi-cluster-operator-6c8d574d49-7th6c   1/1     Running   4          4d8h

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/strimzi-cluster-operator   1/1     1            1           4d8h

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/strimzi-cluster-operator-6c8d574d49   1         1         1       4d8h
[devadmin@vdi-mk4-cnt ~]$
```

Also I added the logs as attached.
[kafka-operator-logs.log](https://github.com/strimzi/strimzi-kafka-operator/files/4608160/kafka-operator-logs.log)

**Comment by scholzj** [comment]
From the log, it seems like the new resource was never created. It ends up with deletion of the old one:

```
2020-05-11 07:29:39 INFO  OperatorWatcher:40 - Reconciliation #188(watch) Kafka(kafka/kafka-beytepe): Kafka kafka-beytepe in namespace kafka was DELETED
```

But the new one is never added. Are you sure you created it in the right namespace etc.?

**Comment by tirelibirefe** [comment]
it must be old.
Now, I re-applied the yaml, pls look at the result:

```
[devadmin@vdi-mk4-cnt ~]$ kubectl apply -f kafka-persistent-custom.yaml
kafka.kafka.strimzi.io/kafka-beytepe unchanged
```

**Comment by scholzj** [comment]
Is it in the right namespace?

**Comment by tirelibirefe** [comment]
Ahhh... Shaming! it was not.

```
[devadmin@vdi-mk4-cnt ~]$ kubectl get pods -n kafka
NAME                                             READY   STATUS    RESTARTS   AGE
kafka-beytepe-entity-operator-6649f64587-bjrnl   1/3     Running   0          20s
kafka-beytepe-kafka-0                            2/2     Running   0          66s
kafka-beytepe-kafka-1                            2/2     Running   0          66s
kafka-beytepe-kafka-2                            2/2     Running   0          66s
kafka-beytepe-zookeeper-0                        2/2     Running   0          111s
kafka-beytepe-zookeeper-1                        2/2     Running   0          111s
kafka-beytepe-zookeeper-2                        2/2     Running   0          111s
strimzi-cluster-operator-6c8d574d49-7th6c        1/1     Running   4          4d8h
```

**Comment by tirelibirefe** [comment]
@scholzj last question.
In this installation, where can I find my bootstrap server name/address?

**Comment by tirelibirefe** [comment]
kafka-beytepe-kafka-bootstrap:9092

**Comment by scholzj** [comment]
You can always find the bootstrap addresses and ports in the Status section of the Kafka resource. So if you do `kubectl get kafka -o yaml` you should always find them.
