### ISSUE TITLE
[Bug] "Detection of Kuberetes version failed." on OCP 4.3.18 @ IBM Cloud

### ISSUE THREAD

**Issue by davivcgarcia** [strimzi/strimzi-kafka-operator#3000]
**Describe the bug**
The operator fails to verify the K8s version when deployed on Red Hat OpenShift at IBM Cloud (managed-service). I see the following error in operator's pod logs:

`2020-05-12 20:03:24 ERROR PlatformFeaturesAvailability:124 - Detection of Kuberetes version failed.`

**To Reproduce**
1. Create a OpenShift cluster
2. Install the operator from OperatorHub
3. Check operator's pod logs

**Expected behavior**
Operator is functional.

**Environment (please complete the following information):**
 - Strimzi version: 0.17.0.GA-redhat-00006
 - Installation method: OperatorHub.io
 - Kubernetes cluster: Red Hat OpenShift, 4.3.18 (managed-service)
 - Infrastructure: IBM Cloud

**YAML files and logs**

```
+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
++ get_heap_size
+++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
++ CONTAINER_MEMORY_IN_BYTES=268435456
++ DEFAULT_MEMORY_CEILING=32505856
++ '[' 268435456 -lt 32505856 ']'
+ MAX_HEAP=
+ '[' -n '' ']'
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.17.0.GA-redhat-00006.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.redhat-00001.jar:lib/io.strimzi.kafka-oauth-client-0.3.0.redhat-00001.jar:lib/io.netty.netty-resolver-4.1.45.Final-redhat-00002.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.2.redhat-00003.jar:lib/io.prometheus.simpleclient-0.5.0.redhat-00001.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:lib/dk.brics.automaton.automaton-1.11.8.redhat-1.jar:lib/com.github.luben.zstd-jni-1.4.3.1-redhat-00002.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.2.redhat-00003.jar:lib/io.netty.netty-codec-4.1.45.Final-redhat-00002.jar:lib/org.apache.kafka.kafka-clients-2.4.0.redhat-00005.jar:lib/io.micrometer.micrometer-registry-prometheus-1.1.0.redhat-00002.jar:lib/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.redhat-00001.jar:lib/io.strimzi.crd-annotations-0.17.0.GA-redhat-00006.jar:lib/io.netty.netty-handler-proxy-4.1.45.Final-redhat-00002.jar:lib/org.quartz-scheduler.quartz-2.2.1.redhat-1.jar:lib/org.latencyutils.LatencyUtils-2.0.3.redhat-00001.jar:lib/io.vertx.vertx-micrometer-metrics-3.8.5.redhat-00005.jar:lib/io.netty.netty-transport-4.1.45.Final-redhat-00002.jar:lib/io.netty.netty-codec-socks-4.1.45.Final-redhat-00002.jar:lib/io.netty.netty-common-4.1.45.Final-redhat-00002.jar:lib/org.keycloak.keycloak-common-7.0.0.redhat-00002.jar:lib/io.netty.netty-codec-dns-4.1.45.Final-redhat-00002.jar:lib/com.fasterxml.jackson.core.jackson-core-2.10.2.redhat-00003.jar:lib/jakarta.activation.jakarta.activation-api-1.2.1.redhat-00002.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.10.2.redhat-00003.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.0.redhat-00001.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.10.2.redhat-00003.jar:lib/io.netty.netty-codec-http2-4.1.45.Final-redhat-00002.jar:lib/io.fabric8.openshift-client-4.6.4.redhat-00001.jar:lib/io.strimzi.operator-common-0.17.0.GA-redhat-00006.jar:lib/org.yaml.snakeyaml-1.24.0.redhat-00001.jar:lib/io.strimzi.kafka-oauth-server-0.3.0.redhat-00001.jar:lib/com.github.mifmif.generex-1.0.2.redhat-1.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.redhat-00001.jar:lib/io.strimzi.config-model-0.17.0.GA-redhat-00006.jar:lib/io.fabric8.kubernetes-model-common-4.6.4.redhat-00001.jar:lib/io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:lib/org.keycloak.keycloak-core-7.0.0.redhat-00002.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.0.redhat-00001.jar:lib/org.slf4j.slf4j-api-1.7.25.redhat-00001.jar:lib/io.fabric8.zjsonpatch-0.3.1.redhat-00001.jar:lib/io.netty.netty-codec-http-4.1.45.Final-redhat-00002.jar:lib/io.vertx.vertx-core-3.8.5.redhat-00005.jar:lib/io.strimzi.certificate-manager-0.17.0.GA-redhat-00006.jar:lib/io.fabric8.kubernetes-model-4.6.4.redhat-00001.jar:lib/io.strimzi.api-0.17.0.GA-redhat-00006.jar:lib/com.squareup.okio.okio-1.15.0.redhat-00001.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.redhat-00001.jar:lib/org.xerial.snappy.snappy-java-1.1.7.2-redhat-00002.jar:lib/io.micrometer.micrometer-core-1.1.0.redhat-00002.jar:lib/org.lz4.lz4-java-1.6.0.redhat-00001.jar:lib/io.netty.netty-buffer-4.1.45.Final-redhat-00002.jar:lib/org.hdrhistogram.HdrHistogram-2.1.9.redhat-003.jar:lib/io.netty.netty-handler-4.1.45.Final-redhat-00002.jar:lib/io.netty.netty-resolver-dns-4.1.45.Final-redhat-00002.jar:lib/io.strimzi.kafka-oauth-common-0.3.0.redhat-00001.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.0.redhat-00001.jar:lib/io.prometheus.simpleclient_common-0.5.0.redhat-00001.jar io.strimzi.operator.cluster.Main
2020-05-12 20:03:22 INFO  Main:58 - ClusterOperator 0.17.0.GA-redhat-00006 is starting
2020-05-12 20:03:24 ERROR PlatformFeaturesAvailability:124 - Detection of Kuberetes version failed.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:293) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:122) ~[io.strimzi.operator-common-0.17.0.GA-redhat-00006.jar:0.17.0.GA-redhat-00006]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final-redhat-00002.jar:4.1.45.Final-redhat-00002]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:158) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:111) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.execute(RealCall.java:92) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:46) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	... 8 more
2020-05-12 20:03:24 ERROR Main:85 - Failed to gather environment facts
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:293) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:122) ~[io.strimzi.operator-common-0.17.0.GA-redhat-00006.jar:0.17.0.GA-redhat-00006]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final-redhat-00002.jar:4.1.45.Final-redhat-00002]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:158) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:111) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.execute(RealCall.java:92) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:46) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	... 8 more
```

**Comment by scholzj** [comment]
This is related to https://github.com/fabric8io/kubernetes-client/issues/2212. This does not affect Strimzi 0.17.0 which is using older version of Java. Issues related to Red Hat AMQ Streams should be reaised within Red Hat.

**Comment by davivcgarcia** [comment]
@scholzj thanks for the feedback! And sorry for opening the Issue here instead of in the Jira. I thought both would be interchangeable, like it is the case for other products.
