### ISSUE TITLE
HTTP 403, Status: 403 - kafkarebalances.kafka.strimzi.io is forbidden

### ISSUE THREAD

**Issue by zvazquez** [strimzi/strimzi-kafka-operator#3016]
**Describe the bug**
While the operator starts, I am getting the following error and I am not able to install a cluster:

**2020-05-13 22:24:08 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 403, Status: 403 - kafkarebalances.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafkaoper:strimzi-cluster-operator" cannot watch resource "kafkarebalances" in API group "kafka.strimzi.io" in the namespace "kafkasandbox"**

**To Reproduce**
After prepare YAMLs just try to install the operator as:

kubectl create ns kafkaoper
kubectl create ns kafkasandbox
kubectl apply -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n kafkasandbox
kubectl apply -f install/cluster-operator -n kafkaoper

**Expected behavior**
Operator to be up and running and then be able to install a Kafka cluster

**Environment (please complete the following information):**
 - Strimzi version: 0.17.0
 - Installation method: YAML
 - Kubernetes cluster: 1.15.9
 - Infrastructure: onprem

While the operator try to starts I am getting the following exception:

2020-05-13 22:24:07 INFO  Main:119 - The KafkaConnectS2I custom resource definition can only be used in environment which supports OpenShift build, image and apps APIs. These APIs do not seem to be supported in this environment.
2020-05-13 22:24:07 INFO  ClusterOperator:87 - Creating ClusterOperator for namespace kafkasandbox
2020-05-13 22:24:08 INFO  ClusterOperator:87 - Creating ClusterOperator for namespace kafkadev
2020-05-13 22:24:08 INFO  ClusterOperator:105 - Starting ClusterOperator for namespace kafkasandbox
2020-05-13 22:24:08 INFO  ClusterOperator:105 - Starting ClusterOperator for namespace kafkadev
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for Kafka operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for Kafka operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaMirrorMaker operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaMirrorMaker operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaConnect operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaConnect operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaBridge operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaBridge operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaMirrorMaker2 operator
2020-05-13 22:24:08 INFO  ClusterOperator:119 - Opened watch for KafkaMirrorMaker2 operator
**2020-05-13 22:24:08 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 403, Status: 403 - kafkarebalances.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafkaoper:strimzi-cluster-operator" cannot watch resource "kafkarebalances" in API group "kafka.strimzi.io" in the namespace "kafkasandbox"**
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29b3cd59 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@821b8e1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:318)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:221)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-05-13 22:24:08 WARN  WatchConnectionManager:202 - Exec Failure: HTTP 403, Status: 403 - kafkarebalances.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafkaoper:strimzi-cluster-operator" cannot watch resource "kafkarebalances" in API group "kafka.strimzi.io" in the namespace "kafkadev"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-05-13 22:24:08 ERROR Main:154 - Cluster Operator verticle in namespace kafkasandbox failed to start
io.fabric8.kubernetes.client.KubernetesClientException: kafkarebalances.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafkaoper:strimzi-cluster-operator" cannot watch resource "kafkarebalances" in API group "kafka.strimzi.io" in the namespace "kafkasandbox"
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:206) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:135) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:354) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:759) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:738) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:69) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watchInNamespace(AbstractWatchableResourceOperator.java:46) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
		at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResourceOperator.java:53) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
		at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$createRebalanceWatch$2(KafkaRebalanceAssemblyOperator.java:181) ~[io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
		at io.strimzi.operator.common.Util.lambda$async$0(Util.java:42) ~[io.strimzi.operator-common-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
		at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
		at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
		at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by scholzj** [comment]
The `kafkarebalances` custom resource does not exist in 0.17.0 release. So most probably you are not using that release but the master images. In that case, you should:
* either pull the updated installation files if you want to keep using master (recommended only if you want to do some Strimzi development)
* or download the actual 0.17.0 release from https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.17.0 and use that (recommended if you want something stable)

**Comment by zvazquez** [comment]
Thank you, that was the problem, seems I sync the repo without knowing in the last couple of days and it stopped working.
