### ISSUE TITLE
[Zookeeper is crashing with no quorums while launching kafka.]

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3033]
Hello Team,

I have enabled Kafka with a simple type of authorization with replicas as 3 for both Kafka and zookeeper.

```yaml
  apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: cluster1
  spec:
    clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true
    kafka:
      version: 2.4.0
      replicas: 3
      listeners:
         plain: {}
         tls:
           authentication:
             type: tls
         external:
           type: loadbalancer
           tls:  true
      authorization:
        type: simple
      storage:
        type: persistent-claim
        size: 10Gi
        deleteClaim: false        
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

I am facing an issue while the zookeeper nodes are coming up with the following issue.  Could you please suggest the reason and workaround for this. 

```
# Zookeeper nodes configuration
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThre
ads=N
2020-05-15 13:34:27,868 INFO Reading configuration from: /tmp/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-05-15 13:34:27,879 INFO clientPortAddress is /127.0.0.1:12181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-05-15 13:34:27,879 INFO secureClientPortAddress is 0.0.0.0/0.0.0.0:2181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-05-15 13:34:27,888 INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util) [main]
2020-05-15 13:34:27,891 ERROR Invalid config, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain) [main]
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /tmp/zookeeper.properties
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:154)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:113)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.lang.IllegalArgumentException: standaloneEnabled = false then number of participants should be >0
```

**Comment by scholzj** [comment]
What version are you using? Can you share the whole log of the Zookeeper containr from the beginning? It prints the configuration there on the beginning as it is generated.

**Comment by vperi1730** [comment]
`kubectl logs -f my-cluster-zookeeper-0 -n kafka-operator1 zookeeper
cat: /opt/kafka/custom-config/zookeeper.node-count: No such file or directory
Detected Zookeeper ID 1
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/*.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias *
Illegal option:  NOTICE
Key and Certificate Management Tool
Commands:

 -certreq            Generates a certificate request
 -changealias        Changes an entry's alias
 -delete             Deletes an entry
 -exportcert         Exports certificate
 -genkeypair         Generates a key pair
 -genseckey          Generates a secret key
 -gencert            Generates certificate from a certificate request
 -importcert         Imports a certificate or a certificate chain
 -importpass         Imports a password
 -importkeystore     Imports one or all entries from another keystore
 -keypasswd          Changes the key password of an entry
 -list               Lists entries in a keystore
 -printcert          Prints the content of a certificate
 -printcertreq       Prints the content of a certificate request
 -printcrl           Prints the content of a CRL file
 -storepasswd        Changes the store password of a keystore
Use "keytool -command_name -help" for usage of command_name
Preparing truststore is complete
Looking for the right CA
No CA found. Thus exiting.
Starting Zookeeper with configuration:
# The directory where the snapshot is stored.
dataDir=/var/lib/zookeeper/data

# Other options
4lw.commands.whitelist=*
standaloneEnabled=false
reconfigEnabled=true
clientPort=12181
clientPortAddress=127.0.0.1
# TLS options
serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
ssl.clientAuth=need
ssl.quorum.clientAuth=need
secureClientPort=2181
sslQuorum=true
ssl.trustStore.location=/tmp/zookeeper/cluster.truststore.p12
ssl.trustStore.password=pkeD26Ew-NQgq4HsiECXX5swYmoyY6Rw
ssl.trustStore.password=pkeD26Ew-NQgq4HsiECXX5swYmoyY6Rw
ssl.trustStore.type=PKCS12
ssl.quorum.trustStore.location=/tmp/zookeeper/cluster.truststore.p12
ssl.quorum.trustStore.password=pkeD26Ew-NQgq4HsiECXX5swYmoyY6Rw
ssl.quorum.trustStore.type=PKCS12
ssl.keyStore.location=/tmp/zookeeper/cluster.keystore.p12
ssl.keyStore.password=pkeD26Ew-NQgq4HsiECXX5swYmoyY6Rw
ssl.keyStore.type=PKCS12
ssl.quorum.keyStore.location=/tmp/zookeeper/cluster.keystore.p12
ssl.quorum.keyStore.password=pkeD26Ew-NQgq4HsiECXX5swYmoyY6Rw
ssl.quorum.keyStore.type=PKCS12
# Provided configuration
autopurge.purgeInterval=1
tickTime=2000
initLimit=5
syncLimit=2

# Zookeeper nodes configuration
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThre
ads=N
2020-05-15 13:34:27,868 INFO Reading configuration from: /tmp/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-05-15 13:34:27,879 INFO clientPortAddress is /127.0.0.1:12181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-05-15 13:34:27,879 INFO secureClientPortAddress is 0.0.0.0/0.0.0.0:2181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-05-15 13:34:27,888 INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util) [main]
2020-05-15 13:34:27,891 ERROR Invalid config, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain) [main]
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /tmp/zookeeper.properties
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:154)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:113)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.lang.IllegalArgumentException: standaloneEnabled = false then number of participants should be >0
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseDynamicConfig(QuorumPeerConfig.java:634)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.setupQuorumPeerConfig(QuorumPeerConfig.java:601)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:420)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)`

**Comment by scholzj** [comment]
What about the other question? What version of the operator are you using? Judging from the code, it is master? Can you make sure that you downloaded all the latest installation files and pulled the latest images? This could be caused by old operator image and new Zookeeper/Kafka image or the other way around. Normally, unless you do some development, you should always use the stable release such as 0.17 and not master which is unstable and changing all the time.

**Comment by vperi1730** [comment]
Missed it, sorry.

Operator - 0.17.0
Kafka - 2.4.0

**Comment by scholzj** [comment]
I don't think this is 0.17 ... 0.17 does not have any TLs configuration in Zookeper directly, it is using the sidecars for that. So this has to be master. If you change the container image used, I'm sure it will have the tag `latest-kafka-2.4.0` which is master image.

**Comment by vperi1730** [comment]
Perfect. It worked, Yes you are correct, we were using the latest image which caused this issue.

Thanks for the help.
