### ISSUE TITLE
[Issue with Kafka upgrade from 2.3.1 to 2.4.0 - Operator-0.17.0] ...

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3053]
Hello Team,

we are facing issues when we are upgrading Kafka version from 2.3.1 to 2.4.0

error below.

with the deployment, we see the zookeeper respawns, but kafka doesnt.

```
2020-05-18 13:51:30 WARN  AbstractOperator:268 - Reconciliation #55(timer) Kafka(qa-kafka-operator-demo/my-cluster4): Failed to reconcile
io.strimzi.operator.cluster.KafkaUpgradeException: Kafka version upgrade from KafkaVersion{version='2.3.1', protocolVersion='2.3', messageVersion='2.3', zookeeperVersion='3.4.14', isDefault=false, unsupportedFeatures='kafkaMirrorMaker2'} to KafkaVersion{version='2.4.0', protocolVersion='2.4', messageVersion='2.4', zookeeperVersion='3.5.6', isDefault=true, unsupportedFeatures='null'} requires a message format change from 2.3 to 2.4. log.message.format.version: "2.3" must be explicitly set.
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.kafkaUpgradePhase1(KafkaAssemblyOperator.java:964) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$null$24(KafkaAssemblyOperator.java:924) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.vertx.core.Future.lambda$compose$3(Future.java:360) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.SucceededFuture.setHandler(SucceededFuture.java:41) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.Future.compose(Future.java:356) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.Future.compose(Future.java:328) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$null$28(KafkaAssemblyOperator.java:924) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.vertx.core.Future.lambda$compose$3(Future.java:360) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$null$1(KafkaRoller.java:156) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by scholzj** [comment]
Before starting the upgrade, you need to fix the `log.message.format.version` on the old version. Otherwise the cluster might not really sync during the upgrade when you have some brokers as 2.3.1 and some as 2.4.0 and the upgrade might interupt the clients etc.

So basically, before starting the upgrade, you need to add `log.message.format.version: "2.3` to `Kafka.spec.kafka.config`. See https://strimzi.io/docs/latest/full.html#proc-upgrading-brokers-newer-kafka-str for more details.

**Comment by pashafirdous** [comment]
Hi Jakub,

Thanks that was the solution.

regards,
pasha
