### ISSUE TITLE
[Bug] ...AMQ Streams Kafka Operator installation failed on Openshift 4.3.18 Version

### ISSUE THREAD

**Issue by rajansh5** [strimzi/strimzi-kafka-operator#3059]
**Describe the bug**
install failed: Timeout: deployment amq-streams-cluster-operator-v1.4.1 not ready before timeout: deployment "amq-streams-cluster-operator-v1.4.1" exceeded its progress deadline

**To Reproduce**
1. Login to Openshift Cluster 4.3
2. Go to Operatorhub  
3. Click Red Hat Integration - AMQ Streams
4. Select the below details 
Installation Mode : All namespaces
Channel : stable
Approval Strategy : Automatic
5. Click Subscription 

**Expected behavior**
Kafka operator should installed without any issue.

**Environment (please complete the following information):**
 - Strimzi version: OPERATOR VERSION 1.4.1
 - Installation method: OperatorHub.io
 - Kubernetes cluster: OpenShift 4.3 (ROKS: 4.3.18) 
 - Infrastructure: IBM Cloud

**YAML files and logs**

```

oc logs amq-streams-cluster-operator-v1.4.1-77bc9ff7cc-t6fzl
+ shift
+ . /opt/strimzi/bin/dynamic_resources.sh
++ get_heap_size
+++ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
++ CONTAINER_MEMORY_IN_BYTES=268435456
++ DEFAULT_MEMORY_CEILING=32505856
++ '[' 268435456 -lt 32505856 ']'
+ MAX_HEAP=
+ '[' -n '' ']'
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
+ exec java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.17.0.GA-redhat-00006.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.redhat-00001.jar:lib/io.strimzi.kafka-oauth-client-0.3.0.redhat-00001.jar:lib/io.netty.netty-resolver-4.1.45.Final-redhat-00002.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.2.redhat-00003.jar:lib/io.prometheus.simpleclient-0.5.0.redhat-00001.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:lib/dk.brics.automaton.automaton-1.11.8.redhat-1.jar:lib/com.github.luben.zstd-jni-1.4.3.1-redhat-00002.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.2.redhat-00003.jar:lib/io.netty.netty-codec-4.1.45.Final-redhat-00002.jar:lib/org.apache.kafka.kafka-clients-2.4.0.redhat-00005.jar:lib/io.micrometer.micrometer-registry-prometheus-1.1.0.redhat-00002.jar:lib/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.redhat-00001.jar:lib/io.strimzi.crd-annotations-0.17.0.GA-redhat-00006.jar:lib/io.netty.netty-handler-proxy-4.1.45.Final-redhat-00002.jar:lib/org.quartz-scheduler.quartz-2.2.1.redhat-1.jar:lib/org.latencyutils.LatencyUtils-2.0.3.redhat-00001.jar:lib/io.vertx.vertx-micrometer-metrics-3.8.5.redhat-00005.jar:lib/io.netty.netty-transport-4.1.45.Final-redhat-00002.jar:lib/io.netty.netty-codec-socks-4.1.45.Final-redhat-00002.jar:lib/io.netty.netty-common-4.1.45.Final-redhat-00002.jar:lib/org.keycloak.keycloak-common-7.0.0.redhat-00002.jar:lib/io.netty.netty-codec-dns-4.1.45.Final-redhat-00002.jar:lib/com.fasterxml.jackson.core.jackson-core-2.10.2.redhat-00003.jar:lib/jakarta.activation.jakarta.activation-api-1.2.1.redhat-00002.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.10.2.redhat-00003.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.60.0.redhat-00001.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.10.2.redhat-00003.jar:lib/io.netty.netty-codec-http2-4.1.45.Final-redhat-00002.jar:lib/io.fabric8.openshift-client-4.6.4.redhat-00001.jar:lib/io.strimzi.operator-common-0.17.0.GA-redhat-00006.jar:lib/org.yaml.snakeyaml-1.24.0.redhat-00001.jar:lib/io.strimzi.kafka-oauth-server-0.3.0.redhat-00001.jar:lib/com.github.mifmif.generex-1.0.2.redhat-1.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.redhat-00001.jar:lib/io.strimzi.config-model-0.17.0.GA-redhat-00006.jar:lib/io.fabric8.kubernetes-model-common-4.6.4.redhat-00001.jar:lib/io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:lib/org.keycloak.keycloak-core-7.0.0.redhat-00002.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.0.redhat-00001.jar:lib/org.slf4j.slf4j-api-1.7.25.redhat-00001.jar:lib/io.fabric8.zjsonpatch-0.3.1.redhat-00001.jar:lib/io.netty.netty-codec-http-4.1.45.Final-redhat-00002.jar:lib/io.vertx.vertx-core-3.8.5.redhat-00005.jar:lib/io.strimzi.certificate-manager-0.17.0.GA-redhat-00006.jar:lib/io.fabric8.kubernetes-model-4.6.4.redhat-00001.jar:lib/io.strimzi.api-0.17.0.GA-redhat-00006.jar:lib/com.squareup.okio.okio-1.15.0.redhat-00001.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.redhat-00001.jar:lib/org.xerial.snappy.snappy-java-1.1.7.2-redhat-00002.jar:lib/io.micrometer.micrometer-core-1.1.0.redhat-00002.jar:lib/org.lz4.lz4-java-1.6.0.redhat-00001.jar:lib/io.netty.netty-buffer-4.1.45.Final-redhat-00002.jar:lib/org.hdrhistogram.HdrHistogram-2.1.9.redhat-003.jar:lib/io.netty.netty-handler-4.1.45.Final-redhat-00002.jar:lib/io.netty.netty-resolver-dns-4.1.45.Final-redhat-00002.jar:lib/io.strimzi.kafka-oauth-common-0.3.0.redhat-00001.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.0.redhat-00001.jar:lib/io.prometheus.simpleclient_common-0.5.0.redhat-00001.jar io.strimzi.operator.cluster.Main
2020-05-19 13:25:33 INFO  Main:58 - ClusterOperator 0.17.0.GA-redhat-00006 is starting
2020-05-19 13:25:35 ERROR PlatformFeaturesAvailability:124 - Detection of Kuberetes version failed.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:293) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:122) ~[io.strimzi.operator-common-0.17.0.GA-redhat-00006.jar:0.17.0.GA-redhat-00006]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final-redhat-00002.jar:4.1.45.Final-redhat-00002]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: okhttp3.internal.http2.ConnectionShutdownException
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:248) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:111) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.execute(RealCall.java:92) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:46) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	... 8 more
2020-05-19 13:25:35 ERROR Main:85 - Failed to gather environment facts
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:51) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:293) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:122) ~[io.strimzi.operator-common-0.17.0.GA-redhat-00006.jar:0.17.0.GA-redhat-00006]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final-redhat-00002.jar:4.1.45.Final-redhat-00002]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: okhttp3.internal.http2.ConnectionShutdownException
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:248) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:111) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at okhttp3.RealCall.execute(RealCall.java:92) ~[com.squareup.okhttp3.okhttp-3.12.0.redhat-00001.jar:3.12.0.redhat-00001]
	at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:46) ~[io.fabric8.kubernetes-client-4.6.4.redhat-00001.jar:?]
	... 8 more




```

**Comment by scholzj** [comment]
This is related to JDK8u252 and fabric8io/kubernetes-client#2212. This does not affect Strimzi 0.17.0 which is using older version of Java. Issues related to Red Hat AMQ Streams should be reaised within Red Hat.

You should be able to workaround it by disabling HTTP2:
* For the Cluster Operator, you can just add it to the deployment to the list of other environment variables:

```yaml
        - name: HTTP2_DISABLE
          value: "true"
```

* You also need to configure it for the User and Topic operator and for the Kafka initializer (if used for node ports or rack awareness). To do so, you should have something like this in the Kafka CR:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ...
    template:
      initContainer:
        env:
          - name: HTTP2_DISABLE
            value: true
  zookeeper:
    # ...
  entityOperator:
    topicOperator:
      # ...
    userOperator:
      # ...
    template:
      topicOperatorContainer:
        env:
          - name: HTTP2_DISABLE
            value: true
      userOperatorContainer:
        env:
          - name: HTTP2_DISABLE
            value: true
```

**Comment by bandrade** [comment]
For Openshift 4.x, I could address this issue by adding the environment variable at subscription object, that would add this into all the containers that are managed by the Operator.
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 2
  name: amq-streams
  namespace: openshift-operators
spec:
  channel: stable
  config:
    env:
    - name: HTTP2_DISABLE
      value: "true"
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v1.4.1
```
oc get csv -n openshift-operators                                 
```
NAME                DISPLAY                             VERSION   REPLACES            PHASE
amqstreams.v1.4.1   Red Hat Integration - AMQ Streams   1.4.1     amqstreams.v1.4.0   Succeeded
```
oc get pods -n openshift-operators
```
NAME                                                   READY   STATUS    RESTARTS   AGE
amq-streams-cluster-operator-v1.4.1-65d5796ffb-8ttv7   1/1     Running   0          13m
my-cluster-entity-operator-58ccbf5fb7-lbgxd            3/3     Running   0          33s
my-cluster-kafka-0                                     2/2     Running   0          66s
my-cluster-kafka-1                                     2/2     Running   0          66s
my-cluster-kafka-2                                     2/2     Running   0          66s
my-cluster-zookeeper-0                                 2/2     Running   0          116s
my-cluster-zookeeper-1                                 2/2     Running   0          116s
my-cluster-zookeeper-2                                 2/2     Running   0          116s
```

**Comment by scholzj** [comment]
That is a neat trick ... I didn't knew about it. Thanks for sharing.

**Comment by rajansh5** [comment]
Thanks for Subscription trick.. its working fine.
