### ISSUE TITLE
Kafka Rolling upgrade

### ISSUE THREAD

**Issue by saneera** [strimzi/strimzi-kafka-operator#3087]
Hi 

I m using strimzi operator on openshidft .3.11 with kafka cluster , I m able to deploy kafka cluster without any problem and it working fine, I created helm chart to create kafka cluster 

as an example I executed kafka with 2 replicas initially , but I need to increase the number of kafka pods 

so I followed the following steps 
1) kubectl annotate statefulset kafka-kafka strimzi.io/manual-rolling-update=true -n kafka-test
2) do the helm upgrade command by changing the number of replicas 

after run 
`kubectl edit kafka -n <namespace>`

i can see the replicas updated in yaml , but now of pods is same

but it doesn't work 
kafka operator version 0.16.2

```
2020-05-25 07:56:42 WARN  AbstractOperator:193 - Reconciliation #54(timer) Kafka(kafka-test/kafka): Failed to acquire lock lock::kafka-test::Kafka::kafka within 10000ms.
2020-05-25 07:56:44 INFO  KafkaRoller:201 - Could not restart pod 0, giving up after 10 attempts/127750ms
io.strimzi.operator.cluster.operator.resource.KafkaRoller$FatalProblem: Error while waiting for restarted pod kafka-kafka-0 to become ready
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$restartAndAwaitReadiness$10(KafkaRoller.java:342) ~[io.strimzi.cluster-operator-0.16.2.jar:0.16.2]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.await(KafkaRoller.java:375) ~[io.strimzi.cluster-operator-0.16.2.jar:0.16.2]
	at 
io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartAndAwaitReadiness(KafkaRoller.java:342) ~[io.strimzi.cluster-operator-0.16.2.jar:0.16.2]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartIfNecessary(KafkaRoller.java:270) ~[io.strimzi.cluster-operator-0.16.2.jar:0.16.2]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$schedule$5(KafkaRoller.java:195) ~[io.strimzi.cluster-operator-0.16.2.jar:0.16.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_242]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[?:1.8.0_242]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_242]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.await(KafkaRoller.java:371) ~[io.strimzi.cluster-operator-0.16.2.jar:0.16.2]
	... 10 more
2020-05-25 07:56:44 ERROR Util:78 - Exceeded timeout of 300000ms while waiting for Pods resource kafka-kafka-0 in namespace kafka-test to be ready
```

Any idea

Thanks

Saneera

**Comment by scholzj** [comment]
Hi,

Can you be a bit more specific about some more details:
* What exactly do you mean with _I need to upgrade cluster replicas once deployed_? As in upgrade Kafka version? Or just to roll the pods? If just to roll the pods - why?
* Can you double check the Strimzi version? There is no 0.62 version.
* Can you share the logs from the Kafka pods?

The log basically means thatthe operator restarted the Kafka broker, but it wasn't ready in 5 minutes. At which point the operator gives up and will get back to it in the next reconciliation loop. But for the reasons, you would need to check the Kafka logs.

**Comment by saneera** [comment]
> Hi,
> 
> Can you be a bit more specific about some more details:
> 
>     * What exactly do you mean with _I need to upgrade cluster replicas once deployed_? As in upgrade Kafka version? Or just to roll the pods? If just to roll the pods - why?
> 
>     * Can you double check the Strimzi version? There is no 0.62 version.
> 
>     * Can you share the logs from the Kafka pods?
> 
> 
> The log basically means thatthe operator restarted the Kafka broker, but it wasn't ready in 5 minutes. At which point the operator gives up and will get back to it in the next reconciliation loop. But for the reasons, you would need to check the Kafka logs.

@scholzj  updated question

**Comment by scholzj** [comment]
Ok, I better understand the problem now. But as I said, this will definitely need also the Kafka broker logs.

**Comment by saneera** [comment]
@scholzj  Thanks

kafka pod is running fine but its not changing the replicas

operator-log
```
2020-05-25 14:48:32 INFO  ClusterOperator:122 - Triggering periodic reconciliation for namespace *...
2020-05-25 14:48:32 INFO  AbstractOperator:122 - Reconciliation #470(timer) KafkaBridge(default/kafka-bridge): KafkaBridge kafka-bridge should be created or updated
2020-05-25 14:48:32 INFO  AbstractOperator:262 - Reconciliation #470(timer) KafkaBridge(default/kafka-bridge): reconciled
2020-05-25 14:48:42 WARN  AbstractOperator:193 - Reconciliation #469(timer) Kafka(kafka-test/kafka): Failed to acquire lock lock::kafka-test::Kafka::kafka within 10000ms.
2020-05-25 14:50:32 INFO  ClusterOperator:122 - Triggering periodic reconciliation for namespace *...
2020-05-25 14:50:32 INFO  AbstractOperator:122 - Reconciliation #472(timer) KafkaBridge(default/kafka-bridge): KafkaBridge kafka-bridge should be created or updated
2020-05-25 14:50:32 INFO  AbstractOperator:262 - Reconciliation #472(timer) KafkaBridge(default/kafka-bridge): reconciled
2020-05-25 14:50:42 WARN  AbstractOperator:193 - Reconciliation #471(timer) Kafka(kafka-test/kafka): Failed to acquire lock lock::kafka-test::Kafka::kafka within 10000ms.
2020-05-25 14:52:32 INFO  ClusterOperator:122 - Triggering periodic reconciliation for namespace *...
2020-05-25 14:52:32 INFO  AbstractOperator:122 - Reconciliation #474(timer) KafkaBridge(default/kafka-bridge): KafkaBridge kafka-bridge should be created or updated
2020-05-25 14:52:32 INFO  AbstractOperator:262 - Reconciliation #474(timer) KafkaBridge(default/kafka-bridge): reconciled
2020-05-25 14:52:42 WARN  AbstractOperator:193 - Reconciliation #473(timer) Kafka(kafka-test/kafka): Failed to acquire lock lock::kafka-test::Kafka::kafka within 10000ms.
2020-05-25 14:54:32 INFO  ClusterOperator:122 - Triggering periodic reconciliation for namespace *...
2020-05-25 14:54:32 INFO  AbstractOperator:122 - Reconciliation #476(timer) KafkaBridge(default/kafka-bridge): KafkaBridge kafka-bridge should be created or updated
2020-05-25 14:54:32 INFO  AbstractOperator:262 - Reconciliation #476(timer) KafkaBridge(default/kafka-bridge): reconciled
2020-05-25 14:54:42 WARN  AbstractOperator:193 - Reconciliation #475(timer) Kafka(kafka-test/kafka): Failed to acquire lock lock::kafka-test::Kafka::kafka within 10000ms.
2020-05-25 14:56:32 INFO  ClusterOperator:122 - Triggering periodic reconciliation for namespace *...
2020-05-25 14:56:32 INFO  AbstractOperator:122 - Reconciliation #478(timer) KafkaBridge(default/kafka-bridge): KafkaBridge kafka-bridge should be created or updated
2020-05-25 14:56:32 INFO  AbstractOperator:262 - Reconciliation #478(timer) KafkaBridge(default/kafka-bridge): reconciled
2020-05-25 14:56:42 WARN  AbstractOperator:193 - Reconciliation #477(timer) Kafka(kafka-test/kafka): Failed to acquire lock lock::kafka-test::Kafka::kafka within 10000ms.
```



kafka-log
```
2020-05-25 14:47:36,423 INFO Logs loading complete in 197 ms. (kafka.log.LogManager) [main]
2020-05-25 14:47:36,468 INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager) [main]
2020-05-25 14:47:36,469 INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager) [main]
2020-05-25 14:47:36,472 INFO Starting the log cleaner (kafka.log.LogCleaner) [main]
2020-05-25 14:47:36,607 INFO [kafka-log-cleaner-thread-0]: Starting (kafka.log.LogCleaner) [kafka-log-cleaner-thread-0]
2020-05-25 14:47:37,378 INFO Awaiting socket connections on 0.0.0.0:9091. (kafka.network.Acceptor) [main]
2020-05-25 14:47:39,201 INFO [SocketServer brokerId=0] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9091,ListenerName(REPLICATION-9091),SSL) (kafka.network.SocketServer) [main]
2020-05-25 14:47:39,203 INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor) [main]
2020-05-25 14:47:39,274 INFO [SocketServer brokerId=0] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9092,ListenerName(PLAIN-9092),PLAINTEXT) (kafka.network.SocketServer) [main]
2020-05-25 14:47:39,275 INFO Awaiting socket connections on 0.0.0.0:9093. (kafka.network.Acceptor) [main]
2020-05-25 14:47:39,370 INFO [SocketServer brokerId=0] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9093,ListenerName(TLS-9093),SSL) (kafka.network.SocketServer) [main]
2020-05-25 14:47:39,371 INFO Awaiting socket connections on 0.0.0.0:9094. (kafka.network.Acceptor) [main]
2020-05-25 14:47:40,196 INFO Retrieved token with principal thePrincipalName (org.apache.kafka.common.security.oauthbearer.internals.unsecured.OAuthBearerUnsecuredLoginCallbackHandler) [main]
2020-05-25 14:47:40,198 INFO Successfully logged in. (org.apache.kafka.common.security.authenticator.AbstractLogin) [main]
2020-05-25 14:47:40,682 INFO [SocketServer brokerId=0] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9094,ListenerName(EXTERNAL-9094),SASL_SSL) (kafka.network.SocketServer) [main]
2020-05-25 14:47:40,685 INFO [SocketServer brokerId=0] Started 4 acceptor threads for data-plane (kafka.network.SocketServer) [main]
2020-05-25 14:47:40,772 INFO [ExpirationReaper-0-Produce]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-Produce]
2020-05-25 14:47:40,773 INFO [ExpirationReaper-0-Fetch]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-Fetch]
2020-05-25 14:47:40,774 INFO [ExpirationReaper-0-DeleteRecords]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-DeleteRecords]
2020-05-25 14:47:40,775 INFO [ExpirationReaper-0-ElectLeader]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-ElectLeader]
2020-05-25 14:47:40,793 INFO [LogDirFailureHandler]: Starting (kafka.server.ReplicaManager$LogDirFailureHandler) [LogDirFailureHandler]
2020-05-25 14:47:40,894 INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient) [main]
2020-05-25 14:47:40,968 INFO Stat of the created znode at /brokers/ids/0 is: 1009,1009,1590418060902,1590418060902,1,0,0,72248367460253762,517,0,1009
 (kafka.zk.KafkaZkClient) [main]
2020-05-25 14:47:40,969 INFO Registered broker 0 at path /brokers/ids/0 with addresses: ArrayBuffer(EndPoint(kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc,9091,ListenerName(REPLICATION-9091),SSL), EndPoint(kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc,9092,ListenerName(PLAIN-9092),PLAINTEXT), EndPoint(kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc,9093,ListenerName(TLS-9093),SSL), EndPoint(23.101.221.207,9094,ListenerName(EXTERNAL-9094),SASL_SSL)), czxid (broker epoch): 1009 (kafka.zk.KafkaZkClient) [main]
2020-05-25 14:47:41,085 INFO [ControllerEventThread controllerId=0] Starting (kafka.controller.ControllerEventManager$ControllerEventThread) [controller-event-thread]
2020-05-25 14:47:41,092 INFO [ExpirationReaper-0-topic]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-topic]
2020-05-25 14:47:41,096 INFO [ExpirationReaper-0-Heartbeat]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-Heartbeat]
2020-05-25 14:47:41,097 INFO [ExpirationReaper-0-Rebalance]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-Rebalance]
2020-05-25 14:47:41,173 INFO [Controller id=0] 0 successfully elected as the controller. Epoch incremented to 3 and epoch zk version is now 3 (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,174 INFO [Controller id=0] Registering handlers (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,180 INFO [Controller id=0] Deleting log dir event notifications (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,184 INFO [Controller id=0] Deleting isr change notifications (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,186 INFO [Controller id=0] Initializing controller context (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,192 INFO [GroupCoordinator 0]: Starting up. (kafka.coordinator.group.GroupCoordinator) [main]
2020-05-25 14:47:41,193 INFO [GroupCoordinator 0]: Startup complete. (kafka.coordinator.group.GroupCoordinator) [main]
2020-05-25 14:47:41,271 INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 78 milliseconds. (kafka.coordinator.group.GroupMetadataManager) [group-metadata-manager-0]
2020-05-25 14:47:41,277 INFO [Controller id=0] Initialized broker epochs cache: Map(0 -> 1009) (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,283 INFO [ProducerId Manager 0]: Acquired new producerId block (brokerId:0,blockStartProducerId:2000,blockEndProducerId:2999) by writing to Zk with path version 3 (kafka.coordinator.transaction.ProducerIdManager) [main]
2020-05-25 14:47:41,294 DEBUG [Controller id=0] Register BrokerModifications handler for Set(0) (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,386 DEBUG [Channel manager on controller 0]: Controller 0 trying to connect to broker 0 (kafka.controller.ControllerChannelManager) [controller-event-thread]
2020-05-25 14:47:41,866 INFO [TransactionCoordinator id=0] Starting up. (kafka.coordinator.transaction.TransactionCoordinator) [main]
2020-05-25 14:47:41,869 INFO [Transaction Marker Channel Manager 0]: Starting (kafka.coordinator.transaction.TransactionMarkerChannelManager) [TxnMarkerSenderThread-0]
2020-05-25 14:47:41,870 INFO [TransactionCoordinator id=0] Startup complete. (kafka.coordinator.transaction.TransactionCoordinator) [main]
2020-05-25 14:47:41,879 INFO [RequestSendThread controllerId=0] Starting (kafka.controller.RequestSendThread) [Controller-0-to-broker-0-send-thread]
2020-05-25 14:47:41,879 INFO [Controller id=0] Currently active brokers in the cluster: Set(0) (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,880 INFO [Controller id=0] Currently shutting brokers in the cluster: Set() (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,880 INFO [Controller id=0] Current list of topics in the cluster: Set(test-topic) (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,881 INFO [Controller id=0] Fetching topic deletions in progress (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,887 INFO [Controller id=0] List of topics to be deleted:  (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,887 INFO [Controller id=0] List of topics ineligible for deletion:  (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,887 INFO [Controller id=0] Initializing topic deletion manager (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,888 INFO [Topic Deletion Manager 0] Initializing manager with initial deletions: Set(), initial ineligible deletions: Set() (kafka.controller.TopicDeletionManager) [controller-event-thread]
2020-05-25 14:47:41,888 INFO [ZooKeeperClient ACL authorizer] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient) [main]
2020-05-25 14:47:41,888 INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@1b5bc39d (org.apache.zookeeper.ZooKeeper) [main]
2020-05-25 14:47:41,889 INFO [Controller id=0] Sending update metadata request (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:41,889 INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket) [main]
2020-05-25 14:47:41,889 INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn) [main]
2020-05-25 14:47:41,890 INFO [ZooKeeperClient ACL authorizer] Waiting until connected. (kafka.zookeeper.ZooKeeperClient) [main]
2020-05-25 14:47:41,967 INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-05-25 14:47:41,968 INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-05-25 14:47:41,977 INFO [ReplicaStateMachine controllerId=0] Initializing replica state (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-05-25 14:47:41,982 INFO [ReplicaStateMachine controllerId=0] Triggering online replica state changes (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-05-25 14:47:42,072 TRACE [Controller id=0 epoch=3] Changed state of replica 0 for partition test-topic-0 from OnlineReplica to OnlineReplica (state.change.logger) [controller-event-thread]
2020-05-25 14:47:42,075 TRACE [Controller id=0 epoch=3] Sending become-leader LeaderAndIsr request LeaderAndIsrPartitionState(topicName='test-topic', partitionIndex=0, controllerEpoch=1, leader=0, leaderEpoch=0, isr=[0], zkVersion=0, replicas=[0], addingReplicas=[], removingReplicas=[], isNew=false) to broker 0 for partition test-topic-0 (state.change.logger) [controller-event-thread]
2020-05-25 14:47:42,078 TRACE [Controller id=0 epoch=3] Sending UpdateMetadata request UpdateMetadataPartitionState(topicName='test-topic', partitionIndex=0, controllerEpoch=1, leader=0, leaderEpoch=0, isr=[0], zkVersion=0, replicas=[0], offlineReplicas=[]) to brokers Set(0) for partition test-topic-0 (state.change.logger) [controller-event-thread]
2020-05-25 14:47:42,079 INFO [ReplicaStateMachine controllerId=0] Triggering offline replica state changes (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-05-25 14:47:42,080 DEBUG [ReplicaStateMachine controllerId=0] Started replica state machine with initial state -> Map([Topic=test-topic,Partition=0,Replica=0] -> OnlineReplica) (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-05-25 14:47:42,080 INFO [PartitionStateMachine controllerId=0] Initializing partition state (kafka.controller.ZkPartitionStateMachine) [controller-event-thread]
2020-05-25 14:47:42,083 INFO [PartitionStateMachine controllerId=0] Triggering online partition state changes (kafka.controller.ZkPartitionStateMachine) [controller-event-thread]
2020-05-25 14:47:42,086 DEBUG [PartitionStateMachine controllerId=0] Started partition state machine with initial state -> Map(test-topic-0 -> OnlinePartition) (kafka.controller.ZkPartitionStateMachine) [controller-event-thread]
2020-05-25 14:47:42,086 INFO [Controller id=0] Ready to serve as the new controller with epoch 3 (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:42,092 INFO [Controller id=0] Partitions undergoing preferred replica election:  (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:42,093 INFO [Controller id=0] Partitions that completed preferred replica election:  (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:42,093 INFO [Controller id=0] Skipping preferred replica election for partitions due to topic deletion:  (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:42,094 INFO [Controller id=0] Resuming preferred replica election for partitions:  (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:42,095 INFO [Controller id=0] Starting replica leader election (PREFERRED) for partitions  triggered by ZkTriggered (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:42,106 INFO [Controller id=0] Starting the controller scheduler (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:43,069 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-05-25 14:47:43,070 INFO Socket connection established, initiating session, client: /127.0.0.1:59120, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-05-25 14:47:43,078 INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x100ad81e6120043, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-05-25 14:47:43,079 INFO [ZooKeeperClient ACL authorizer] Connected. (kafka.zookeeper.ZooKeeperClient) [main]
2020-05-25 14:47:43,167 INFO [/kafka-acl-changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread) [/kafka-acl-changes-event-process-thread]
2020-05-25 14:47:43,168 INFO [/kafka-acl-extended-changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread) [/kafka-acl-extended-changes-event-process-thread]
2020-05-25 14:47:43,293 INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper) [ExpirationReaper-0-AlterAcls]
2020-05-25 14:47:43,311 INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread) [/config/changes-event-process-thread]
2020-05-25 14:47:43,379 INFO [SocketServer brokerId=0] Started data-plane processors for 4 acceptors (kafka.network.SocketServer) [main]
2020-05-25 14:47:43,382 INFO Kafka version: 2.4.0 (org.apache.kafka.common.utils.AppInfoParser) [main]
2020-05-25 14:47:43,382 INFO Kafka commitId: 77a89fcf8d7fa018 (org.apache.kafka.common.utils.AppInfoParser) [main]
2020-05-25 14:47:43,382 INFO Kafka startTimeMs: 1590418063380 (org.apache.kafka.common.utils.AppInfoParser) [main]
2020-05-25 14:47:43,384 INFO [KafkaServer id=0] started (kafka.server.KafkaServer) [main]
2020-05-25 14:47:43,478 INFO [RequestSendThread controllerId=0] Controller 0 connected to kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc:9091 (id: 0 rack: null) for sending state change requests (kafka.controller.RequestSendThread) [Controller-0-to-broker-0-send-thread]
2020-05-25 14:47:43,566 INFO Running as server according to kafka.server:type=KafkaServer,name=BrokerState => ready (io.strimzi.kafka.agent.KafkaAgent) [KafkaAgentPoller]
2020-05-25 14:47:43,770 TRACE [Controller id=0 epoch=3] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 0 sent to broker kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-05-25 14:47:43,784 TRACE [Broker id=0] Received LeaderAndIsr request LeaderAndIsrPartitionState(topicName='test-topic', partitionIndex=0, controllerEpoch=1, leader=0, leaderEpoch=0, isr=[0], zkVersion=0, replicas=[0], addingReplicas=[], removingReplicas=[], isNew=false) correlation id 1 from controller 0 epoch 3 (state.change.logger) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,876 TRACE [Broker id=0] Handling LeaderAndIsr request correlationId 1 from controller 0 epoch 3 starting the become-leader transition for partition test-topic-0 (state.change.logger) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,878 INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions Set(test-topic-0) (kafka.server.ReplicaFetcherManager) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,912 INFO [Partition test-topic-0 broker=0] Log loaded for partition test-topic-0 with initial high watermark 3 (kafka.cluster.Partition) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,913 INFO [Partition test-topic-0 broker=0] test-topic-0 starts at Leader Epoch 0 from offset 3. Previous Leader Epoch was: -1 (kafka.cluster.Partition) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,972 TRACE [Broker id=0] Stopped fetchers as part of become-leader request from controller 0 epoch 3 with correlation id 1 for partition test-topic-0 (last update controller epoch 1) (state.change.logger) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,974 TRACE [Broker id=0] Completed LeaderAndIsr request correlationId 1 from controller 0 epoch 3 for the become-leader transition for partition test-topic-0 (state.change.logger) [data-plane-kafka-request-handler-4]
2020-05-25 14:47:43,988 TRACE [Controller id=0 epoch=3] Received response {error_code=0,partition_errors=[{topic_name=test-topic,partition_index=0,error_code=0,_tagged_fields={}}],_tagged_fields={}} for request LEADER_AND_ISR with correlation id 1 sent to broker kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-05-25 14:47:43,998 TRACE [Broker id=0] Cached leader info UpdateMetadataPartitionState(topicName='test-topic', partitionIndex=0, controllerEpoch=1, leader=0, leaderEpoch=0, isr=[0], zkVersion=0, replicas=[0], offlineReplicas=[]) for partition test-topic-0 in response to UpdateMetadata request sent by controller 0 epoch 3 with correlation id 2 (state.change.logger) [data-plane-kafka-request-handler-5]
2020-05-25 14:47:43,999 TRACE [Controller id=0 epoch=3] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 2 sent to broker kafka-kafka-0.kafka-kafka-brokers.kafka-test.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-05-25 14:47:47,107 INFO [Controller id=0] Processing automatic preferred replica leader election (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:47,108 TRACE [Controller id=0] Checking need to trigger auto leader balancing (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:47,110 DEBUG [Controller id=0] Preferred replicas by broker Map(0 -> Map(test-topic-0 -> Vector(0))) (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:47,112 DEBUG [Controller id=0] Topics not in preferred replica for broker 0 Map() (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:47:47,113 TRACE [Controller id=0] Leader imbalance ratio for broker 0 is 0.0 (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:52:47,114 INFO [Controller id=0] Processing automatic preferred replica leader election (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:52:47,114 TRACE [Controller id=0] Checking need to trigger auto leader balancing (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:52:47,114 DEBUG [Controller id=0] Preferred replicas by broker Map(0 -> Map(test-topic-0 -> Vector(0))) (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:52:47,115 DEBUG [Controller id=0] Topics not in preferred replica for broker 0 Map() (kafka.controller.KafkaController) [controller-event-thread]
2020-05-25 14:52:47,115 TRACE [Controller id=0] Leader imbalance ratio for broker 0 is 0.0 (kafka.controller.KafkaController) [controller-event-thread]
```

**Comment by scholzj** [comment]
The log from the cluster operator says that pod `kafka-kafka-0` is not ready. So you should check whether that is the case or not. The log looks ok, so it is a bit weird why is it not ready.

**Comment by saneera** [comment]
@scholzj  sorry my bad I upgraded cluster with different helm properties because of that kafka is not started 
resolved it 
Thanks for your help
