### ISSUE TITLE
ERROR Unable to load database on disk on Zookeeper.

### ISSUE THREAD

**Issue by vikneshgs** [strimzi/strimzi-kafka-operator#3222]
Hello,

I am using 3 replicas for kafka and zookeeper along with persistent volume. Once the kafka-persistent.yaml manifest is applied, I am continuously getting one or two zookeeper pods in error state and it get restarted and crashed. While checking the logs i am getting the following error. 

```
INFO Reading snapshot /var/lib/zookeeper/data/version-2/snapshot.500000000 (org.apache.zookeeper.server.persistence.FileSnap) [main]
2020-06-22 07:24:55,665 ERROR Unable to load database on disk (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:84)
        at org.apache.zookeeper.server.persistence.FileHeader.deserialize(FileHeader.java:66)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.inStreamCreated(FileTxnLog.java:640)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.createInputArchive(FileTxnLog.java:659)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.goToNextLog(FileTxnLog.java:625)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.next(FileTxnLog.java:705)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.fastForwardFromEdits(FileTxnSnapLog.java:294)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.lambda$restore$0(FileTxnSnapLog.java:229)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:253)
        at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:240)
        at org.apache.zookeeper.server.quorum.QuorumPeer.loadDataBase(QuorumPeer.java:901)
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:887)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
2020-06-22 07:24:55,696 ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain) [main]
java.lang.RuntimeException: Unable to run quorum server
        at org.apache.zookeeper.server.quorum.QuorumPeer.loadDataBase(QuorumPeer.java:938)
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:887)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:84)
        at org.apache.zookeeper.server.persistence.FileHeader.deserialize(FileHeader.java:66)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.inStreamCreated(FileTxnLog.java:640)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.createInputArchive(FileTxnLog.java:659)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.goToNextLog(FileTxnLog.java:625)
        at org.apache.zookeeper.server.persistence.FileTxnLog$FileTxnIterator.next(FileTxnLog.java:705)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.fastForwardFromEdits(FileTxnSnapLog.java:294)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.lambda$restore$0(FileTxnSnapLog.java:229)
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.restore(FileTxnSnapLog.java:253)
        at org.apache.zookeeper.server.ZKDatabase.loadDataBase(ZKDatabase.java:240)
        at org.apache.zookeeper.server.quorum.QuorumPeer.loadDataBase(QuorumPeer.java:901)
```

But I am able to fix this by moving the snapshot manually inside the zookeeper pods as soon as i restart and mv /var/lib/zookeeper/data/version-2, but after a while its crashes again.Thus i would like to know if there is any fix which can be implemented and fixed this error permanently.

**Comment by scholzj** [comment]
I have never seen this error. Looks like the data are somehoe messed up on the disk? What kind of storage are you using?

**Comment by vikneshgs** [comment]
We are using NFS storageclass for the pv.

**Comment by scholzj** [comment]
I'm not sure how well does NFS work with Zookeeper. But for example with Kafka it does not work so well. So it might be worth trying it with some block storage instead of NFS.

**Comment by vikneshgs** [comment]
@scholzj : I could see the storage class supports values: "ephemeral", "persistent-claim", "jbod"
can you please tell me how can i add rbd in this manifest file (kafka-persistent.yaml)

**Comment by scholzj** [comment]
Not sure what rdb is - but the jbod and persistent-claim types allow you to specify the storage class you want to use in the `class` field: https://strimzi.io/docs/operators/latest/full/using.html#ref-persistent-storage-deployment-configuration-kafka

**Comment by vikneshgs** [comment]
@scholzj : rbd refers to ceph storage. I have changed to rbd as you mentioned and now none of the containers go to error state but i could see all the pods are restarting within 5 minutes, though i am using replication, one among the 3 pods of kafka and zookeeper goes for a restart always. Is there any way we can keep the pods in a steady state

---------------------------------------------------------------------------------------
NAME                                                 READY   STATUS    RESTARTS   AGE
pod/kafka-cluster-entity-operator-84d456c68f-bq4mz   3/3     Running   0          48s
pod/kafka-cluster-kafka-0                            2/2     Running   0          4m38s
pod/kafka-cluster-kafka-1                            2/2     Running   0          3m7s
pod/kafka-cluster-kafka-2                            2/2     Running   0          107s
pod/kafka-cluster-zookeeper-0                        1/1     Running   0          7m28s
pod/kafka-cluster-zookeeper-1                        1/1     Running   0          6m44s
pod/kafka-cluster-zookeeper-2                        1/1     Running   0          6m2s
pod/kafka-connect-cluster-connect-7546d4b69d-z64jk   0/1     Running   0          17s
pod/kafka-connect-cluster-connect-f4fcccc7c-fg9v7    1/1     Running   0          87s
pod/strimzi-cluster-operator-57d66b694d-flvj5        1/1     Running   0          8h.

**Comment by scholzj** [comment]
That really depends on why they are restrting. It cannot be answered without any logs etc.

**Comment by vikneshgs** [comment]
@scholzj : While checking the logs i could see the following error.

------------------------------------------------------
ERROR Util:114 - Exceeded timeout of 300000ms while waiting for Deployment resource kafka-connect-cluster-connect in namespace kafka-operator to be ready
2020-06-22 15:47:15 ERROR AbstractConnectOperator:673 - Reconciliation #921(watch) KafkaConnect(kafka-operator/kafka-connect-cluster): Current KafkaConnect resource not found
2020-06-22 15:47:15 ERROR AbstractOperator:175 - Reconciliation #921(watch) KafkaConnect(kafka-operator/kafka-connect-cluster): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Deployment resource kafka-connect-cluster-connect in namespace kafka-operator to be ready

**Comment by scholzj** [comment]
Maybe you can try to change the log level in the Strimzi Cluster Operator to DEBUG and the logs will show some more information (Change the `STRIMZI_LOG_LEVEL` env var in the Cluster Operator deployment to `DEBUG`)

**Comment by scholzj** [comment]
@vikneshgs Is this still a problem? Or can we close this?

**Comment by vikneshgs** [comment]
@scholzj  Sure, please close the issue. The issue was fixed when i added memory and cpu and xms value in my manifest file. Thanks!!

**Comment by scholzj** [comment]
Thanks
