### ISSUE TITLE
[PVC Storage updation in Kafka Operator] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3298]
Hi Team,

I have updated the Size of the zookeeper in kafka.yaml from 20GB to 21GB with storage class as standard-v2. My updated cluster shows the following config, However, when I do kubectl get PVC on my namespace it is still showing me the old value.

```
zookeeper:
    jmxOptions: {}
    logging:
      loggers:
        zookeeper.root.logger: DEBUG
      type: inline
    metrics: {}
    replicas: 3
    storage:
      class: standard-v2
      deleteClaim: false
      size: 21Gi
      type: persistent-claim
```

```
kubectl get pvc -n kafka-mirror-tgt                                                                             

NAME                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-mm-backup-cluster-kafka-0       Bound    pvc-647ef248-e7e3-4641-b022-cb0d5397dd3e   20Gi       RWO            standard-v2    30h
data-mm-backup-cluster-kafka-1       Bound    pvc-2b31cbe7-e8c8-483a-a9e6-58f187f17473   20Gi       RWO            standard-v2    30h
data-mm-backup-cluster-kafka-2       Bound    pvc-c6d5aa99-d580-4d05-aceb-7efafd0ce7f2   20Gi       RWO            standard-v2    30h
data-mm-backup-cluster-zookeeper-0   Bound    pvc-9ad7c10d-c8d9-49fe-b667-a9a19f97bedc   20Gi       RWO            standard       30h
data-mm-backup-cluster-zookeeper-1   Bound    pvc-99bc6462-ddb7-4d8a-aa22-78e23f41964c   20Gi       RWO            standard       30h
data-mm-backup-cluster-zookeeper-2   Bound    pvc-b56e9f01-78d9-43c9-9f8d-8c0abc7eb11c   20Gi       RWO            standard       30h

```

Need help if any configuration is required to immediately have this updated?

**Comment by scholzj** [comment]
A lot depends on your infrastructure whether it supports the resizing or not. Can you:
* Check and share the cluster operator log for any messages about resizing?
* Get the PVCs in YAML so that we see the whole structure?

**Comment by vperi1730** [comment]
Here is the PVC YAML.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    strimzi.io/delete-claim: "false"
  creationTimestamp: "2020-07-08T07:12:29Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: mm-backup-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: strimzi
    strimzi.io/cluster: mm-backup-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: mm-backup-cluster-zookeeper
  name: data-mm-backup-cluster-zookeeper-0
  namespace: kafka-mirror-tgt
  resourceVersion: "144109477"
  selfLink: /api/v1/namespaces/kafka-mirror-tgt/persistentvolumeclaims/data-mm-backup-cluster-zookeeper-0
  uid: 9ad7c10d-c8d9-49fe-b667-a9a19f97bedc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-9ad7c10d-c8d9-49fe-b667-a9a19f97bedc
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound

```

There is nothing in the operator log. 
```
kubectl logs -f kafka-operator-0-1594300374-bk5bm -n kafka-mirror-tgt
Processing update-cluster request at 20200709-131240
Testing connection to Kubernetes namespace
NAME               STATUS    AGE
kafka-mirror-tgt   Active    30h
Found the running operator pod strimzi-operator in kafka-mirror-tgt
Applying kafka.yaml in kafka-mirror-tgt namespace
kafka.kafka.strimzi.io/mm-backup-cluster configured

```

**Comment by scholzj** [comment]
There always has to be something in the operator log - it should reconcile the cluster every 2 minutes and it should show at least the reconciliation without any errors. What log level do you have to configured it at? It should be at least at INFO.

**Comment by vperi1730** [comment]
This can help as it says changes are ignored. Is this at infra level or any miss in the config, How can we know?

```
020-07-09 18:13:39 INFO  AbstractOperator:262 - Reconciliation #13(watch) KafkaMirrorMaker2(kafka-mirror-tgt/brcm-mm2): reconciled
2020-07-09 18:13:46 WARN  AbstractOperator:193 - Reconciliation #4(timer) Kafka(kafka-mirror-tgt/mm-backup-cluster): Failed to acquire lock lock::kafka-mirror-tgt::Kafka::mm-backup-cluster within 10000ms.
2020-07-09T18:13:57.002+0000: 144.700: [GC (Allocation Failure) 2020-07-09T18:13:57.002+0000: 144.700: [DefNew: 13095K->567K(14144K), 0.0049238 secs] 53891K->41364K(61348K), 0.0050441 secs] [Times: user=0.00 sys=0.00, real=0.01 secs]
2020-07-09T18:14:31.657+0000: 179.355: [GC (Allocation Failure) 2020-07-09T18:14:31.657+0000: 179.355: [DefNew: 13175K->434K(14144K), 0.0043282 secs] 53972K->41231K(61348K), 0.0044111 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
2020-07-09T18:14:31.891+0000: 179.588: [GC (Allocation Failure) 2020-07-09T18:14:31.891+0000: 179.588: [DefNew: 13042K->1535K(14144K), 0.0068126 secs] 53839K->42536K(61348K), 0.0068924 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-07-09 18:14:31 INFO  AbstractOperator:262 - Reconciliation #1(watch) Kafka(kafka-mirror-tgt/mm-backup-cluster): reconciled
2020-07-09 18:14:31 INFO  OperatorWatcher:40 - Reconciliation #14(watch) Kafka(kafka-mirror-tgt/mm-backup-cluster): Kafka mm-backup-cluster in namespace kafka-mirror-tgt was MODIFIED
2020-07-09 18:14:31 WARN  AbstractOperator:106 - Kafka resource mm-backup-cluster in namespace kafka-mirror-tgt: Contains object at path spec.zookeeper with an unknown property: jmxOptions
2020-07-09 18:14:31 INFO  AbstractOperator:122 - Reconciliation #14(watch) Kafka(kafka-mirror-tgt/mm-backup-cluster): Kafka mm-backup-cluster should be created or updated
2020-07-09 18:14:32 WARN  AbstractModel:257 - Only the following changes to Zookeeper storage are allowed: changing the deleteClaim flag and increasing size of persistent claim volumes (depending on the volume type and used storage class).
2020-07-09 18:14:32 WARN  AbstractModel:258 - Your desired Zookeeper storage configuration contains changes which are not allowed. As a result, all storage changes will be ignored. Use DEBUG level logging for more information about the detected changes.
2020-07-09T18:14:32.438+0000: 180.136: [GC (Allocation Failure) 2020-07-09T18:14:32.438+0000: 180.136: [DefNew: 14143K->434K(14144K), 0.0074042 secs] 55144K->42184K(61348K), 0.0074850 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-07-09T18:14:32.676+0000: 180.374: [GC (Allocation Failure) 2020-07-09T18:14:32.676+0000: 180.374: [DefNew: 13042K->470K(14144K), 0.0539313 secs] 54792K->42220K(61348K), 0.0540250 secs] [Times: user=0.00 sys=0.00, real=0.05 secs]
2020-07-09T18:14:33.838+0000: 181.536: [GC (Allocation Failure) 2020-07-09T18:14:33.838+0000: 181.536: [DefNew: 13076K->1156K(14144K), 0.0042192 secs] 54826K->42906K(61348K), 0.0042956 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
2020-07-09 18:14:34 INFO  AbstractOperator:262 - Reconciliation #14(watch) Kafka(kafka-mirror-tgt/mm-backup-cluster): reconciled

```

**Comment by scholzj** [comment]
Well, if really all you did was just change the size and it was change the size from 10Gi to 21Gi and you get this error, than probably your storage class does not support volume resizing. Can you do `kubectl get storageclass standard-v2 -o yaml` and share the output? Or did you change also something else apart form the size?

**Comment by vperi1730** [comment]
Ya, I have only changed the disk size as it was a requirement to update the size. Here is the output for the command, Sorry I am in IST zone hence the little delay to answer back.

```
kubectl get storageclass standard-v2 -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"standard-v2"},"parameters":{"fstype":"ext4","replication-type":"none","type":"pd-standard"},"provisioner":"kubernetes.io/gce-pd","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
  creationTimestamp: "2020-06-05T16:33:19Z"
  name: standard-v2
  resourceVersion: "61455005"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/standard-v2
  uid: 86f5dc68-3aae-4a5c-875e-7daf56fd9304
parameters:
  fstype: ext4
  replication-type: none
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by pashafirdous** [comment]
@scholzj  what level of permissions are needed in the cluster role strimzi-cluster-namespaced at cluster level?

**Comment by scholzj** [comment]
@vperi1730 Could you change the log level in the Cluster Operator to DEBUG and share the output? It looks like the operator thinks you changed something more than just the size. Can you also share the YAML of the Zookeeper StatefulSet to see what storage configuration is in there? Thanks.

**Comment by scholzj** [comment]
@pashafirdous I'm not sure I really understand the question and how it relates to this issue. So maybe I answer it wrongly. But the `strimzi-cluster-operator-namespaced` role is by default only used within a namespace scope and none of the rules from it are cluster scoped. When you install the Cluster Operator to watch multiple or all namespaces, you will need to assign this role in all of the namespaces the operator needs to handle. That is why it is ClusterRole and not just Role - to make the installation easier.

All the cluster scoped RBAC rights are in `strimzi-cluster-operator-global` role.

**Comment by vperi1730** [comment]
> @vperi1730 Could you change the log level in the Cluster Operator to DEBUG and share the output? It looks like the operator thinks you changed something more than just the size. Can you also share the YAML of the Zookeeper StatefulSet to see what storage configuration is in there? Thanks.

Here are the Cluster operator logs after enabling DEBUG.

```
2020-07-11 03:19:12 WARN  AbstractModel:257 - Only the following changes to Zookeeper storage are allowed: changing the deleteClaim flag and increasing the size of persistent claim volumes (depending on the volume type and used storage class).
2020-07-11 03:19:12 WARN  AbstractModel:258 - Your desired Zookeeper storage configuration contains changes that are not allowed. As a result, all storage changes will be ignored. Use DEBUG level logging for more information about the detected changes.
2020-07-11T03:19:12.631+0000: 416.542: [GC (Allocation Failure) 2020-07-11T03:19:12.631+0000: 416.542: [DefNew: 14435K->838K(14464K), 0.0077046 secs] 53988K->40998K(62484K), 0.0078127 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-07-11T03:19:12.940+0000: 416.851: [GC (Allocation Failure) 2020-07-11T03:19:12.940+0000: 416.851: [DefNew: 13702K->113K(14464K), 0.0036343 secs] 53862K->40611K(62484K), 0.0037087 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
2020-07-11 03:19:13 ERROR KafkaAssemblyOperator:2369 - Reconciliation #15(watch) Kafka(kafka-mirror-tgt/mm-backup-cluster): Storage Class standard-v2 not found. PVC data-mm-backup-cluster-kafka-0 cannot be resized.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/storage.k8s.io/v1/storageclasses/standard-v2. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. storageclasses.storage.k8s.io "standard-v2" is forbidden: User "system:serviceaccount:kafka-mirror-tgt:kafka-operator" cannot get resource "storageclasses" in API group "storage.k8s.io" at the cluster scope.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:337) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:318) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:833) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:226) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:170) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.strimzi.operator.common.operator.resource.AbstractNonNamespacedResourceOperator.get(AbstractNonNamespacedResourceOperator.java:219) ~[io.strimzi.operator-common-0.17.0.jar:0.17.0]
        at io.strimzi.operator.common.operator.resource.AbstractNonNamespacedResourceOperator.lambda$getAsync$3(AbstractNonNamespacedResourceOperator.java:231) ~[io.strimzi.operator-common-0.17.0.jar:0.17.0]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-07-11 03:19:13 ERROR KafkaAssemblyOperator:2369 - Reconciliation #15(watch) Kafka(kafka-mirror-tgt/mm-backup-cluster): Storage Class standard-v2 not found. PVC data-mm-backup-cluster-kafka-1 cannot be resized.

```

In the ClusterRole.yaml we have the following configuration accepting all the resources which should have access to all the APIs in this role. Isn't it?

```
- apiGroups:
  - rbac.authorization.k8s.io
  - roles.rbac.authorization.k8s.io
  - authorization.k8s.io
  verbs: ["*"] 
  resources: ["*"]
```

Here is the zookeeper statefulset YAML.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    strimzi.io/storage: '{"type":"persistent-claim","size":"20Gi","deleteClaim":false}'
  creationTimestamp: "2020-07-08T07:12:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: mm-backup-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: strimzi
    strimzi.io/cluster: mm-backup-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: mm-backup-cluster-zookeeper
  name: mm-backup-cluster-zookeeper
  namespace: kafka-mirror-tgt
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: mm-backup-cluster
    uid: ab87eebf-aa00-407a-8e6e-40398cbec7d3
  resourceVersion: "139895571"
  selfLink: /apis/apps/v1/namespaces/kafka-mirror-tgt/statefulsets/mm-backup-cluster-zookeeper
  uid: 65d51e2f-d05b-4098-ba24-e7a6bf39b8dc
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      strimzi.io/cluster: mm-backup-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: mm-backup-cluster-zookeeper
  serviceName: mm-backup-cluster-zookeeper-nodes
  template:
    metadata:
      annotations:
        strimzi.io/cluster-ca-cert-generation: "0"
        strimzi.io/generation: "0"
        strimzi.io/logging-hash: 18e608b48f0842c28b62e08475db265a9f96b5f8efae4d4f6db1fe6bb1b50884a467d37517daa4ad7b6f043a4def86923b1c79fb15ff9fdd4c4057d1f894006d
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mm-backup-cluster
        app.kubernetes.io/managed-by: strimzi-cluster-operator
        app.kubernetes.io/name: strimzi
        strimzi.io/cluster: mm-backup-cluster
        strimzi.io/kind: Kafka
        strimzi.io/name: mm-backup-cluster-zookeeper
      name: mm-backup-cluster-zookeeper
    spec:
      containers:
      - command:
        - /opt/kafka/zookeeper_run.sh
        env:
        - name: ZOOKEEPER_NODE_COUNT
          value: "3"
        - name: ZOOKEEPER_METRICS_ENABLED
          value: "true"
        - name: ZOOKEEPER_SNAPSHOT_CHECK_ENABLED
          value: "true"
        - name: STRIMZI_KAFKA_GC_LOG_ENABLED
          value: "false"
        - name: KAFKA_HEAP_OPTS
          value: -Xms128M
        - name: ZOOKEEPER_CONFIGURATION
          value: |
            autopurge.purgeInterval=1
            tickTime=2000
            initLimit=5
            syncLimit=2
        image: gcr.io/saaspoc-gtso-enterprise-gke/gkegtsoent/kafka-operator/strimzi-kafka:2.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /opt/kafka/zookeeper_healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: zookeeper
        ports:
        - containerPort: 9404
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/kafka/zookeeper_healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/zookeeper
          name: data
        - mountPath: /opt/kafka/custom-config/
          name: zookeeper-metrics-and-logging
      - command:
        - /opt/stunnel/zookeeper_stunnel_run.sh
        env:
        - name: ZOOKEEPER_NODE_COUNT
          value: "3"
        - name: TLS_SIDECAR_LOG_LEVEL
          value: notice
        image: gcr.io/saaspoc-gtso-enterprise-gke/gkegtsoent/kafka-operator/strimzi-kafka:2.4.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/stunnel/zookeeper_stunnel_pre_stop.sh
        livenessProbe:
          exec:
            command:
            - /opt/stunnel/stunnel_healthcheck.sh
            - "2181"
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: tls-sidecar
        ports:
        - containerPort: 2888
          name: clustering
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        - containerPort: 2181
          name: clients
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/stunnel/stunnel_healthcheck.sh
            - "2181"
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls-sidecar/zookeeper-nodes/
          name: zookeeper-nodes
        - mountPath: /etc/tls-sidecar/cluster-ca-certs/
          name: cluster-ca-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
      serviceAccount: mm-backup-cluster-zookeeper
      serviceAccountName: mm-backup-cluster-zookeeper
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mm-backup-cluster-zookeeper-config
        name: zookeeper-metrics-and-logging
      - name: zookeeper-nodes
        secret:
          defaultMode: 292
          secretName: mm-backup-cluster-zookeeper-nodes
      - name: cluster-ca-certs
        secret:
          defaultMode: 292
          secretName: mm-backup-cluster-cluster-ca-cert
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: mm-backup-cluster-zookeeper-74dd97f789
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: mm-backup-cluster-zookeeper-74dd97f789
  updatedReplicas: 3
```

**Comment by scholzj** [comment]
Ok, great. So, it looks like you have the RBAC for whatever reason wrong - it needs access to read storage classes to verify whether the storage class supports resizing or not. These are normally the cluster rights the operator needs: https://github.com/strimzi/strimzi-kafka-operator/blob/0.18.0/install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml ... they do not seem to match the role you listed above. I'm not sure how you installed the operator, but you will need to give it these rights.

Another problem is that from the STS, it seems like your original configuration was this:

```yaml
    storage:
      deleteClaim: false
      size: 20Gi
      type: persistent-claim
```

And you changed it to this:

```yaml
    storage:
      class: standard-v2
      deleteClaim: false
      size: 21Gi
      type: persistent-claim
```

So you changed more than just the size - you also added a storage class. So I think you should remove it.

**Comment by vperi1730** [comment]
OK, that's correct, we somewhere read standard-v2 would be a better option to use for re-sizing and other aspects, hence along with the size we have changed the storage class. Sure, let me try the approach you have suggested. Thanks, Scholzj, Will revert back to you on this again.

**Comment by scholzj** [comment]
Unfortunately, we cannot change the storage class of a volume. That is not possible.

When you shared the `standard-v2` storage class, it has the `allowVolumeExpansion: true` which is needed for the resizing. You should check the `standard` storage class as well and double check it had it set to `true` as well. Without that the resizing will not work.

**Comment by scholzj** [comment]
@vperi1730 Is there still something we can do for you here? Or can we close this?

**Comment by vperi1730** [comment]
Closing for now.
