### ISSUE TITLE
[Kafka Broker Level Information inside GKE cluster] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3315]
Hi Team,

I want to get the information about the Kafka brokers in the cluster for which I have tried the following command. Somehow it didn't work. Need help here.

```
./bin/kafka-configs.sh --bootstrap-server mm-src-cluster-kafka-bootstrap.kafka-mirror-src.svc:9092 --entity-type brokers --entity-name 0 --describe
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Error while executing config command with args '--bootstrap-server mm-src-cluster-kafka-bootstrap.kafka-mirror-src.svc:9092 --entity-type brokers --entity-name 0 --describe'
java.util.concurrent.TimeoutException
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
        at kafka.admin.ConfigCommand$.brokerConfig(ConfigCommand.scala:365)
        at kafka.admin.ConfigCommand$.describeBrokerConfig(ConfigCommand.scala:344)
        at kafka.admin.ConfigCommand$.processBrokerConfig(ConfigCommand.scala:290)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:84)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)

```

**Comment by scholzj** [comment]
Sorry we didn't get to this sooner. Do you still have this problem?
