### ISSUE TITLE
0.18.0-2.5.0 Topic Operator can't connect to zookeeper

### ISSUE THREAD

**Issue by mugugnu** [strimzi/strimzi-kafka-operator#3356]
Hi,
i've just deployed a 0.18.0-2.5.0 cluster operator and got a 3 broker kafka cluster along with its 3 node zookeeper cluster running with no issues at all.
I thought that the hardest part was done, but then i deployed the topic operator and with my surprise i found out it's not able to connect to the zookeeper-client service, the same service that is being used by kafka brokers.
I wonder if the out of the box zookeeper network policy are aware that also topic operator needs to connect to zookeeper (and soon i'll have to add kafka connect!)

I've got these running pods:
pod/xxx-kafka-entity-operator-5845544556-rsh2j   3/3     Running   0          12m
pod/xxx-kafka-kafka-0                            2/2     Running   0          12m
pod/xxx-kafka-kafka-1                            2/2     Running   0          12m
pod/xxx-kafka-kafka-2                            2/2     Running   0          12m
pod/xxx-kafka-zookeeper-0                        1/1     Running   0          13m
pod/xxx-kafka-zookeeper-1                        1/1     Running   0          13m
pod/xxx-kafka-zookeeper-2                        1/1     Running   0          13m
pod/strimzi-cluster-operator-6957f4b96d-hchnk    1/1     Running   0          5h26m
pod/strimzi-topic-operator-78844585b8-dbx4p      0/1     Running   3          5m41s

these services:
service/xxx-kafka-kafka-bootstrap    ClusterIP      10.100.200.188   <none>          9091/TCP,9092/TCP,9093/TCP            12m
service/xxx-kafka-kafka-brokers      ClusterIP      None             <none>          9091/TCP,9092/TCP,9093/TCP            12m
service/xxx-kafka-zookeeper-client   ClusterIP      10.100.200.139   <none>          2181/TCP                              13m
service/xxx-kafka-zookeeper-nodes    ClusterIP      None             <none>          2181/TCP,2888/TCP,3888/TCP            13m

these deployments:
NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/xxx-kafka-entity-operator   1/1     1            1           12m
deployment.apps/strimzi-cluster-operator    1/1     1            1           5h26m
deployment.apps/strimzi-topic-operator      0/1     1            0           5m41s

These replicaset:

NAME                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/xxx-kafka-entity-operator-5845544556   1         1         1       12m
replicaset.apps/strimzi-cluster-operator-6957f4b96d    1         1         1       5h26m
replicaset.apps/strimzi-topic-operator-78844585b8      1         1         0       5m41s

thse statefulset:

statefulset.apps/xxx-kafka-kafka       3/3     12m
statefulset.apps/xxx-kafka-zookeeper   3/3     13m

The topic operator strimzi-topic-operator-78844585b8-dbx4p logs this error at the startup:

2020-07-21 16:57:46 INFO  ZooKeeper:868 - Initiating client connection, connectString=xxx-kafka-zookeeper-client:2181 sessionTimeout=20000 watcher=org.I0Itec.zkclient.ZkClient@31846cb4
2020-07-21 16:57:46 INFO  X509Util:79 - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2020-07-21 16:57:46 INFO  ClientCnxnSocket:237 - jute.maxbuffer value is 4194304 Bytes
2020-07-21 16:57:46 INFO  ClientCnxn:1653 - zookeeper.request.timeout value is 0. feature enabled=
2020-07-21 16:57:46 INFO  ZkClient:936 - Waiting for keeper state SyncConnected
2020-07-21 16:57:46 INFO  ClientCnxn:1112 - Opening socket connection to server xxx-kafka-zookeeper-client/10.100.200.139:2181. Will not attempt to authenticate using SASL (unknown error)
2020-07-21 16:58:06 INFO  ZkEventThread:83 - Terminate ZkClient event thread.
2020-07-21 16:58:06 WARN  ClientCnxn:1190 - Client session timed out, have not heard from server in 20003ms for sessionid 0x0
2020-07-21 16:58:06 INFO  ZooKeeper:1422 - Session: 0x0 closed
2020-07-21 16:58:06 INFO  ClientCnxn:524 - EventThread shut down for session: 0x0
2020-07-21 16:58:07 ERROR Main:62 - Error deploying Session
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'xxx-kafka-zookeeper-client:2181' with timeout of 20000 ms
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98) ~[com.101tec.zkclient-0.11.jar:?]
        at io.strimzi.operator.topic.zk.Zk.createSync(Zk.java:36) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.zk.Zk.lambda$create$0(Zk.java:27) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

I've noticed that cluster operator created two network policies:
xxx-kafka-network-policy-kafka
xxx-kafka-network-policy-zookeeper 

The latter reads:
Name:         xxx-kafka-network-policy-zookeeper
Namespace:    xxx-dev
Created on:   2020-07-21 18:49:20 +0200 CEST
Labels:       app.kubernetes.io/instance=xxx-kafka
              app.kubernetes.io/managed-by=strimzi-cluster-operator
              app.kubernetes.io/name=zookeeper
              app.kubernetes.io/part-of=strimzi-xxx-kafka
              strimzi.io/cluster=xxx-kafka
              strimzi.io/kind=Kafka
              strimzi.io/name=strimzi
Annotations:  <none>
Spec:
  PodSelector:     strimzi.io/name=xxx-kafka-zookeeper
  Allowing ingress traffic:
    To Port: 2888/TCP
    To Port: 3888/TCP
    From:
      PodSelector: strimzi.io/name=xxx-kafka-zookeeper
    ----------
    To Port: 2181/TCP
    From:
      PodSelector: strimzi.io/name=xxx-kafka-kafka
    From:
      PodSelector: strimzi.io/name=xxx-kafka-zookeeper
    From:
      PodSelector: strimzi.io/name=xxx-kafka-entity-operator
    From:
      NamespaceSelector: <none>
      PodSelector: strimzi.io/kind=cluster-operator
    From:
      PodSelector: strimzi.io/name=xxx-kafka-cruise-control
  Allowing egress traffic:
    <none> (Selected pods are isolated for egress connectivity)
  Policy Types: Ingress

is there a chance that this network policy is not enabling traffic from topic operator into zookeeper ?
if so, how can this network policy be changed at cluster operator level?

**Comment by scholzj** [comment]
If I get it right you installed the Topic Operator from the separate installation? (`install/topic-operator`) That is used when you want to use the Topic Operator with some cluster not managed by Strimzi - for example there are users using it with Amazon MSK etc. If you want to use it with Strimzi Kafka cluster, then it is deployed as part of the `entity-operator` hub together with the user operator and automatically configured to connect to Kafka / Zookeeper. It looks like you have that already running in the `pod/xxx-kafka-entity-operator-5845544556-rsh2j` pod. The standalone operator installed separately cannot be used this way and you can just delete it.

**Comment by mugugnu** [comment]
Actually, that explains why i was able to create a topic by defining a KafkaTopic resource, i was starting to think i was missing something !!

Infact, i totally missed the
  entityOperator:
    topicOperator: {}
    userOperator: {}
part at the end of the kafka manifest !!

Thanks!

**Comment by scholzj** [comment]
No worries. I guess I can close this issue, right?

**Comment by mugugnu** [comment]
Of course!!

Inviato dal mio dispositivo mobile Huawei

-------- Messaggio originale --------
Oggetto: Re: [strimzi/strimzi-kafka-operator] 0.18.0-2.5.0 Topic Operator can't connect to zookeeper (#3356)
Da: Jakub Scholz
A: strimzi/strimzi-kafka-operator
CC: Spelta Edoardo ,Author


No worries. I guess I can close this issue, right?
