### ISSUE TITLE
[Question] KC does not auto recover from connection issues

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3425]
This our setup

```
mysql -> KC (with KCTR) - > KAFKA
```

When I stop the mysql service and later start it after 10minutes. The streams from the database does not reach the Kafka Topics until i manually restart the KC pod.

Here is the KCTR describe output after the mysql was brought down.
```
ubuntu@staging-pop:~$ k describe kctr
Name:         inventory
Namespace:    pop
Labels:       app=stream-producer
              strimzi.io/cluster=mysql
              timestamp=20200801-085544
              type=stream
Annotations:  <none>
API Version:  kafka.strimzi.io/v1alpha1
Kind:         KafkaConnector
Metadata:
  Creation Timestamp:  2020-08-01T08:56:58Z
  Generation:          1
  Resource Version:    109946862
  Self Link:           /apis/kafka.strimzi.io/v1alpha1/namespaces/pop/kafkaconnectors/inventory
  UID:                 310e74f3-2584-4785-b1fe-b7b59a2d8e72
Spec:
  Class:  io.debezium.connector.mysql.MySqlConnector
  Config:
    Database . History . Kafka . Bootstrap . Servers:  k8s-kafka-bootstrap.kafka:9092
    Database . History . Kafka . Topic:                ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.history.kafka.topic}
    Database . Hostname:                               ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.hostname}
    Database . Password:                               ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.password}
    Database . Port:                                   ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.port}
    Database . Server . Id:                            ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.server.id}
    Database . Server . Name:                          ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.server.name}
    Database . User:                                   ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.user}
    Database . Whitelist:                              ${file:/opt/kafka/external-configuration/stream-inventory/inventory.yaml:database.whitelist}
    Include . Schema . Changes:                        true
  Tasks Max:                                           1
Status:
  Conditions:
    Last Transition Time:  2020-08-01T09:07:52.155Z
    Status:                True
    Type:                  Ready
  Connector Status:
    Connector:
      State:      RUNNING
      Worker Id:  100.97.0.38:8083
    Name:         inventory
    Tasks:
      Id:     0
      State:  FAILED
      Trace:  org.apache.kafka.connect.errors.ConnectException: Error reading MySQL variables: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:339)
  at io.debezium.connector.mysql.MySqlJdbcContext.readMySqlSystemVariables(MySqlJdbcContext.java:318)
  at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:79)
  at io.debezium.connector.mysql.MySqlTaskContext.<init>(MySqlTaskContext.java:52)
  at io.debezium.connector.mysql.MySqlConnectorTask.createAndStartTaskContext(MySqlConnectorTask.java:357)
  at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:78)
  at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:101)
  at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:213)
  at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
  at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
  at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
  at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
  at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
  at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
  at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:190)
  at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:788)
  at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:783)
  at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:329)
  at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:325)
  ... 14 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
  at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
  at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
  at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
  at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
  at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
  at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
  at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
  ... 22 more
Caused by: java.net.SocketTimeoutException: connect timed out
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
  at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
  ... 25 more

      Worker Id:        100.97.0.38:8083
    Type:               source
  Observed Generation:  1
Events:                 <none>
```

**Expectation**
Expect KC to auto recover when mysql service comes back up. May be we can use Kubernetes readiness probes to restart and recover.

Please suggest if this is possible and configurable at present.

**Comment by scholzj** [comment]
The Kafka Connect is fine in this case. But your connector fails. Right now, you will have to manually restart it using the Connect REST API. There is a [proposal](https://github.com/strimzi/proposals/blob/master/007-restarting-kafka-connect-connectors-and-tasks.md) to do it automatically, but it is not implemented so far.
