### ISSUE TITLE
[Question] Issue while launching Kafka with type as ingress

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3440]
Hi Team,

I am trying to launch the Kafka cluster with external type configured as ingress and it's related configurations. However, Kafka pods are not coming up, and below is the error observed. 

Would need help to know what went wrong.

```
 listeners:
        plain: {}
        tls:
          authentication:
            type: tls
        external:
          type: ingress
          authentication:
            type: tls
          configuration:
            bootstrap:
              host: kafka-ingress-kafka-external-bootstrap.kafka-ingress-cluster.svc.cluster.local
            brokers:
            - broker: 0
              host: kafka-ingress-kafka-0
            - broker: 1
              host: kafka-ingress-kafka-1
            - broker: 2
              host: kafka-ingress-kafka-2  
```

```
2020-08-03 13:15:28 DEBUG ServiceOperator:102 - Service kafka-ingress-cluster/kafka-ingress-kafka-bootstrap already exists, patching it
2020-08-03 13:15:28 DEBUG ServiceOperator:168 - Service kafka-ingress-kafka-bootstrap in namespace kafka-ingress-cluster has been patched
2020-08-03 13:15:28 DEBUG ServiceOperator:102 - Service kafka-ingress-cluster/kafka-ingress-kafka-brokers already exists, patching it
2020-08-03 13:15:28 DEBUG ServiceOperator:168 - Service kafka-ingress-kafka-brokers in namespace kafka-ingress-cluster has been patched
2020-08-03 13:15:28 DEBUG ServiceOperator:102 - Service kafka-ingress-cluster/kafka-ingress-kafka-external-bootstrap already exists, patching it
2020-08-03 13:15:28 DEBUG ServiceOperator:168 - Service kafka-ingress-kafka-external-bootstrap in namespace kafka-ingress-cluster has been patched
2020-08-03 13:15:28 DEBUG ServiceOperator:102 - Service kafka-ingress-cluster/kafka-ingress-kafka-2 already exists, patching it
2020-08-03 13:15:28 DEBUG ServiceOperator:102 - Service kafka-ingress-cluster/kafka-ingress-kafka-1 already exists, patching it
2020-08-03 13:15:28 DEBUG ServiceOperator:102 - Service kafka-ingress-cluster/kafka-ingress-kafka-0 already exists, patching it
2020-08-03 13:15:28 DEBUG ServiceOperator:168 - Service kafka-ingress-kafka-2 in namespace kafka-ingress-cluster has been patched
2020-08-03 13:15:28 DEBUG ServiceOperator:168 - Service kafka-ingress-kafka-1 in namespace kafka-ingress-cluster has been patched
2020-08-03 13:15:28 DEBUG ServiceOperator:168 - Service kafka-ingress-kafka-0 in namespace kafka-ingress-cluster has been patched
2020-08-03 13:15:28 DEBUG IngressOperator:99 - Ingress kafka-ingress-cluster/kafka-ingress-kafka-bootstrap does not exist, creating it
2020-08-03 13:15:30 DEBUG PoolThreadCache:250 - Freed 17 thread-local buffer(s) from thread: epollEventLoopGroup-33-1
2020-08-03 13:15:38 DEBUG IngressOperator:198 - Caught exception while creating Ingress kafka-ingress-kafka-bootstrap in namespace kafka-ingress-cluster
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Ingress]  with name: [kafka-ingress-kafka-bootstrap]  in namespace: [kafka-ingress-cluster]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]

```

**Comment by scholzj** [comment]
Can you share more about your environment? Kubernetes versions, Ingress class / version etc.?

**Comment by vperi1730** [comment]
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}


By default we are using Ingress class as Nginx.

**Comment by scholzj** [comment]
That is weird. Does the operator have the rights to create Ingress resources? Can you share the whole log?

**Comment by vperi1730** [comment]
[error_kafka.log](https://github.com/strimzi/strimzi-kafka-operator/files/5016901/error_kafka.log)

Attaching the error log.

**Comment by scholzj** [comment]
Honestly, I haven't seen this kind of error before. Did you checked the RBAC settings? Can you create Ingress resources manually?

**Comment by scholzj** [comment]
Also, any errors in the Kubernetes API server? It looks like the API server doesn't like something and terminates the connection.

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks
