### ISSUE TITLE
[Question] CertificateException: Failed to verify both host address and host name

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3441]
I'm seeing a persistent error in a new strimzi 0.18 installation. I did follow the strimzi external cert deployment instructions.  The external cert was applied and I could see it on the listener. We found the below error and rolled back the external cert change to the default cluster self signed cert. 

Any ideas? 

```  
kafka:
    version: 2.5.0
    replicas: 13
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: https://REDACT/auth/realms/pro-realm/protocol/openid-connect/certs
          validIssuerUri: https://REDACT/auth/realms/pro-realm
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
          jwksExpirySeconds: 960
          jwksRefreshSeconds: 300
      external:
        type: loadbalancer
        tls: true
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: https://REDACT/auth/realms/pro-realm/protocol/openid-connect/certs
          validIssuerUri: https://REDACT/auth/realms/pro-realm
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
          jwksExpirySeconds: 960
          jwksRefreshSeconds: 300
        overrides:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: int-kafka-bootstrap.dev.REDACT.
              external-dns.alpha.kubernetes.io/ttl: "60"
              address: int-kafka-bootstrap.dev.us-east-1.REDACT
```

```
2020-08-03 14:48:35,705 INFO Accepted TLS connection from 100-80-47-205.kafka-cluster-zookeeper-client.REDACT.svc.cluster.local/100.80.47.205:50472 - NONE - SSL_NULL_WITH_NULL_NULL (org.apache.zookeeper.server.quorum.UnifiedServerSocket) [kafka-cluster-zookeeper-0.kafka-cluster-zookeeper-nodes.REDACT.svc/100.80.46.195:3888]
2020-08-03 14:48:35,705 WARN Exception reading or writing challenge: {} (org.apache.zookeeper.server.quorum.QuorumCnxManager) [kafka-cluster-zookeeper-0.kafka-cluster-zookeeper-nodes.REDACT.svc/100.80.46.195:3888]
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Failed to verify both host address and host name
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1554)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:95)
	at org.apache.zookeeper.server.quorum.UnifiedServerSocket$UnifiedInputStream.read(UnifiedServerSocket.java:694)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.handleConnection(QuorumCnxManager.java:524)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.receiveConnection(QuorumCnxManager.java:478)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:934)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Failed to verify both host address and host name
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
	at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:2055)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:233)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	at sun.security.ssl.SSLSocketImpl.getSession(SSLSocketImpl.java:2309)
	at org.apache.zookeeper.server.quorum.UnifiedServerSocket$UnifiedSocket.detectMode(UnifiedServerSocket.java:273)
	at org.apache.zookeeper.server.quorum.UnifiedServerSocket$UnifiedSocket.getSocket(UnifiedServerSocket.java:301)
	at org.apache.zookeeper.server.quorum.UnifiedServerSocket$UnifiedSocket.access$400(UnifiedServerSocket.java:180)
	at org.apache.zookeeper.server.quorum.UnifiedServerSocket$UnifiedInputStream.getRealInputStream(UnifiedServerSocket.java:700)
	... 9 more
Caused by: java.security.cert.CertificateException: Failed to verify both host address and host name
	at org.apache.zookeeper.common.ZKTrustManager.performHostVerification(ZKTrustManager.java:145)
	at org.apache.zookeeper.common.ZKTrustManager.checkClientTrusted(ZKTrustManager.java:74)
	at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:2037)
	... 20 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <100-80-47-205.kafka-cluster-zookeeper-client.REDACT.svc.cluster.local> doesn't match any of the subject alternative names: [kafka-cluster-zookeeper-2.kafka-cluster-zookeeper-nodes.REDACT.svc.cluster.local, kafka-cluster-zookeeper-2.kafka-cluster-zookeeper-nodes.REDACT.svc, kafka-cluster-zookeeper-client.REDACT.svc, kafka-cluster-zookeeper-client.REDACT.svc.cluster.local, kafka-cluster-zookeeper-client, kafka-cluster-zookeeper-client.REDACT]
	at org.apache.zookeeper.common.ZKHostnameVerifier.matchDNSName(ZKHostnameVerifier.java:224)
	at org.apache.zookeeper.common.ZKHostnameVerifier.verify(ZKHostnameVerifier.java:170)
	at org.apache.zookeeper.common.ZKTrustManager.performHostVerification(ZKTrustManager.java:141)
	... 22 more
```

**Comment by scholzj** [comment]
Is that coming from a Zookeeper pod? Also, with external cert you mean what? custom listener certificates? Custom CA?

**Comment by jrivers96** [comment]
I'm reading through the following similar thread: https://github.com/strimzi/strimzi-kafka-operator/issues/3099

1. The error is coming from the zookeeper pod
2. By external cert, I mean custom listener certificates with a  custom CA ( I'm however not sure that this is related to the problem though)

**Comment by scholzj** [comment]
Ok. The custom listener certificates should be unrelated to this. They are not used in Zookeeper.

This is related to your DNS settings in your cluster and to the weird way Zookeeper is doing TLS authentication. This comment should be the workaround for 0.18.0: https://github.com/strimzi/strimzi-kafka-operator/issues/3099#issuecomment-636480754 ... in 0.19.0 I added some improvements to the certificate hostnames which in your case might actually help. So it might be worth trying.

**Comment by jrivers96** [comment]
Yeah, this looks like a reproduction of #3099 problem. I'm going to install 0.19 and see if that helps at all.

**Comment by jrivers96** [comment]
The upgrade to 0.19 has made the warning and error go away.

**Comment by scholzj** [comment]
Great, I'm glad the improvements we did in 0.19.0 helped. Thanks for letting us know!
