### ISSUE TITLE
Error while creating topics using Kafka CLI

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3454]
When i create user from within the Kafka cli i get below error on a kafka deployment with authorization enabled

` bin/kafka-topics.sh --create --bootstrap-server cluster-kafka-bootstrap:9092 --replication-factor 3 --partitions 2 --topic topic1`

```
Error while executing topic command : org.apache.kafka.common.errors.TopicAuthorizationException: Authorization failed.
[2020-08-04 10:20:21,623] ERROR java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicAuthorizationException: Authorization failed.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
        at kafka.admin.TopicCommand$AdminClientTopicService.createTopic(TopicCommand.scala:244)
        at kafka.admin.TopicCommand$TopicService.createTopic(TopicCommand.scala:196)
        at kafka.admin.TopicCommand$TopicService.createTopic$(TopicCommand.scala:191)
        at kafka.admin.TopicCommand$AdminClientTopicService.createTopic(TopicCommand.scala:219)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:62)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.errors.TopicAuthorizationException: Authorization failed.
 (kafka.admin.TopicCommand$)
```

when i was investigating the error i found some suggestion.
[reference](https://www.adaltas.com/en/2020/01/22/intro-open-policy-agent-with-kafka/)

```
**As enforced by our strict “deny all” policy, we are not able to create a topic. Let’s what happens if we try again after modifying the policy to allow everything:**

cat <<EOF >  /opt/opa/data/kafka/authz/allow.rego
package kafka.authz

default allow = true

EOF
```

need some advice to address this issue with auth enabled, but i need to create topics using bootstrap server on port **9092**

**Comment by scholzj** [comment]
Wait ... so are you using Open Policy Agent for authorization? Can you share your Kafka CR?

**Comment by pashafirdous** [comment]
nope! i'm not using OPA agent.
i just go tthis suggestion.

i want to know how can i fix this error if i want to use Kafka cli with authorization enabled

**Comment by scholzj** [comment]
Well, you didn't shared your custom resources. But in general, in your command, you do not do any authentication. So if you enable authorization but not authentication you will be logged in as ANONYMOUS which has no rights. So you will need to fix the authentication -> possibly both in Kafka CR and in the kafka-topics.sh command. And once you do it, you will need to add the rights to create topics to the user you are using for authentication. Some example of how to configure authentication and authorization and create user with ACLs are for example here: https://github.com/strimzi/strimzi-kafka-operator/tree/master/examples/security

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks

**Comment by pashafirdous** [comment]
Thanks Jakub,

closing case
