### ISSUE TITLE
[Bug] Kafka with external Nodeport Listener won't start on Nodes with mutliple external IP's

### ISSUE THREAD

**Issue by kofl91** [strimzi/strimzi-kafka-operator#3458]
**Describe the bug**
When deploying Kafka with an external listener of type nodeport,
the kafka-init pod will throw an error.

**To Reproduce**
1. Configure multiple external IP Adresses on your Kubernetes Worker
2. Create a Kafka Resource with external listener of type nodeport

**Expected behavior**
A Kafka Cluster will be created with external listeners for each external IP address that the worker node provided.

**Environment (please complete the following information):**
 - Strimzi version: 0.19
 - Installation method: helm chart
 - Kubernetes cluster: Openshift 4.4.8
 - Infrastructure: vSphere

**YAML files and logs**

`2020-08-05 12:40:37 INFO  Main:19 - Init-kafka 0.19.0 is starting
2020-08-05 12:40:38 INFO  Main:30 - Init-kafka started with config: InitWriterConfig(nodeName=ocp02-242xg-worker-1,rackTopologyKey=null,externalAddress=true,initFolder=/opt/kafka/init,addressType=null)
2020-08-05 12:40:39 INFO  InitWriter:64 - NodeLabels = [NodeAddress(address=10.5.33.32, type=ExternalIP, additionalProperties={}), NodeAddress(address=100.66.176.32, type=ExternalIP, additionalProperties={}), NodeAddress(address=10.5.33.32, type=InternalIP, additionalProperties={}), NodeAddress(address=100.66.176.32, type=InternalIP, additionalProperties={}), NodeAddress(address=ocp02-242xg-worker-1, type=Hostname, additionalProperties={})]
Exception in thread "main" java.lang.IllegalStateException: Duplicate key ExternalIP (attempted merging values 10.5.33.32 and 100.66.176.32)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.strimzi.operator.cluster.model.NodeUtils.findAddress(NodeUtils.java:32)
	at io.strimzi.kafka.init.InitWriter.writeExternalAddress(InitWriter.java:65)
	at io.strimzi.kafka.init.Main.main(Main.java:41)`

**Additional context**
https://github.com/strimzi/strimzi-kafka-operator/blob/a4a55e2d263d35f644116bda73fb654a1c60bc63/operator-common/src/main/java/io/strimzi/operator/cluster/model/NodeUtils.java#L32

**Comment by kofl91** [comment]
Here the status of the worker node. to see that multiple externalIP's are possible.

`status:
  allocatable:
    cpu: 3500m
    ephemeral-storage: '113912664284'
    hugepages-1Gi: '0'
    hugepages-2Mi: '0'
    memory: 31785408Ki
    pods: '250'
  addresses:
    - type: ExternalIP
      address: 10.5.33.31
    - type: ExternalIP
      address: 100.66.176.31
    - type: InternalIP
      address: 10.5.33.31
    - type: InternalIP
      address: 100.66.176.31
    - type: Hostname
      address: ocp02-242xg-worker-0`

**Comment by scholzj** [comment]
I think it would be easy to fix the error. But it makes it basically impossible to decide which address should be used. From your example I also wonder why are the External and Internal addresses the same? Isn't this really an OCP bug where the `10.5.33.31` should be `InternalIP` and `100.66.176.31` as `ExternalIP`

**Comment by scholzj** [comment]
FYI: I opened a PR to fix this.

**Comment by koflTS** [comment]
Thanks. That was a quick fix.
I still found an issue. Your test did not catch that the writeExternalAddress function does not use the same findAddress function that is declared in the Class. It uses NodeUtils.findAddress.
I was able to build the image and test it after modifying the other findAddress aswell. Thanks again, that was really fast :)

`String externalAddress = NodeUtils.findAddress(addresses, config.getAddressType());`

https://github.com/strimzi/strimzi-kafka-operator/blob/32b5905c5e8e1b48518d5d0653b7dad8191f53ce/kafka-init/src/main/java/io/strimzi/kafka/init/InitWriter.java#L65

**Comment by scholzj** [comment]
Ok, I try to look at that as well. Thanks for pointing it out. I do not have any real environment with this setup where I can test it. So I have to rely on the unit tests.

**Comment by scholzj** [comment]
Ok, attempt number 2 is in #3491

**Comment by jakerbeck** [comment]
We hit a bug like this running Strimzi on EKS.  By using an alternative network plugin each instance only has a single IP now, and the pods were able to initiate.  The lame part was that we pretty much had to recreate the cluster to transition to the new CNI.

https://docs.aws.amazon.com/eks/latest/userguide/alternate-cni-plugins.html
