### ISSUE TITLE
[Question] strimzi-kafka-operator v.0.18.0 - io.strimzi.operator.cluster.model.NoImageException: No image for version 2.6.0 

### ISSUE THREAD

**Issue by Hashfyre** [strimzi/strimzi-kafka-operator#3498]
**Describe the bug**
Kafka operator deployment crashloops with error:
`io.strimzi.operator.cluster.model.NoImageException: No image for version 2.6.0 `

**To Reproduce**
1. install helm chart with either 0.18.0 or 0.19.0

**Expected behavior**
Operator deployment should not crashloop.

**Environment (please complete the following information):**
 - Strimzi version: 0.18.0, 0.19.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.15
 - Infrastructure: Azure AKS

**YAML files and logs**

<details>
1. Logs

 ```
Configuration file log4j2.properties not found. Using default static logging setting. Dynamic updates of logging configuration will not work.
+ export MALLOC_ARENA_MAX=2
+ MALLOC_ARENA_MAX=2
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom'
++ get_gc_opts
++ '[' '' == true ']'
++ echo ''
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom '
++ sed -E -n 's/.* version "([0-9]*).*$/\1/p'
++ java -version
+ JAVA_MAJOR_VERSION=11
+ '[' 11 -ge 9 ']'
+ JAVA_OPTS=' -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom  --illegal-access=deny'
+ exec /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom --illegal-access=deny -classpath lib/io.strimzi.cluster-operator-0.20.0-SNAPSHOT.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/io.vertx.vertx-micrometer-metrics-3.9.1.jar:lib/io.strimzi.kafka-oauth-client-0.5.0.jar:lib/org.apache.zookeeper.zookeeper-3.5.8.jar:lib/org.apache.logging.log4j.log4j-api-2.13.3.jar:lib/com.zaxxer.HikariCP-java7-2.4.13.jar:lib/org.bouncycastle.bcprov-jdk15on-1.60.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/org.keycloak.keycloak-core-10.0.0.jar:lib/org.yaml.snakeyaml-1.24.jar:lib/io.fabric8.openshift-client-4.6.4.jar:lib/io.netty.netty-codec-http2-4.1.50.Final.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/org.hdrhistogram.HdrHistogram-2.1.11.jar:lib/io.prometheus.simpleclient-0.7.0.jar:lib/io.strimzi.certificate-manager-0.20.0-SNAPSHOT.jar:lib/com.sun.activation.jakarta.activation-1.2.1.jar:lib/javax.xml.bind.jaxb-api-2.3.0.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/javax.annotation.javax.annotation-api-1.3.2.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.10.2.jar:lib/io.strimzi.crd-annotations-0.20.0-SNAPSHOT.jar:lib/io.netty.netty-handler-proxy-4.1.50.Final.jar:lib/io.netty.netty-codec-dns-4.1.50.Final.jar:lib/io.micrometer.micrometer-core-1.3.1.jar:lib/org.keycloak.keycloak-common-10.0.0.jar:lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:lib/io.netty.netty-transport-native-epoll-4.1.50.Final.jar:lib/io.netty.netty-transport-4.1.50.Final.jar:lib/io.strimzi.kafka-oauth-common-0.5.0.jar:lib/io.strimzi.kafka-oauth-server-0.5.0.jar:lib/io.fabric8.kubernetes-model-4.6.4.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.operator-common-0.20.0-SNAPSHOT.jar:lib/io.netty.netty-common-4.1.50.Final.jar:lib/io.netty.netty-transport-native-unix-common-4.1.50.Final.jar:lib/io.vertx.vertx-core-3.9.1.jar:lib/com.github.luben.zstd-jni-1.4.4-7.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.6.jar:lib/io.netty.netty-resolver-dns-4.1.50.Final.jar:lib/org.bouncycastle.bcpkix-jdk15on-1.62.jar:lib/io.netty.netty-resolver-4.1.50.Final.jar:lib/org.lz4.lz4-java-1.7.1.jar:lib/org.apache.kafka.kafka-clients-2.6.0.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.13.3.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/io.netty.netty-codec-4.1.50.Final.jar:lib/io.netty.netty-codec-socks-4.1.50.Final.jar:lib/com.fasterxml.jackson.core.jackson-core-2.10.2.jar:lib/io.strimzi.config-model-0.20.0-SNAPSHOT.jar:lib/com.mchange.c3p0-0.9.5.4.jar:lib/jakarta.xml.bind.jakarta.xml.bind-api-2.3.2.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.10.2.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/io.fabric8.kubernetes-client-4.6.4.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.2.jar:lib/com.mchange.mchange-commons-java-0.2.15.jar:lib/com.squareup.okhttp3.okhttp-3.12.6.jar:lib/io.netty.netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar:lib/io.netty.netty-handler-4.1.50.Final.jar:lib/io.fabric8.kubernetes-model-common-4.6.4.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.10.2.jar:lib/io.strimzi.api-0.20.0-SNAPSHOT.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/org.latencyutils.LatencyUtils-2.0.3.jar:lib/org.apache.zookeeper.zookeeper-jute-3.5.8.jar:lib/io.netty.netty-buffer-4.1.50.Final.jar:lib/org.apache.logging.log4j.log4j-core-2.13.3.jar:lib/io.netty.netty-codec-http-4.1.50.Final.jar:lib/io.micrometer.micrometer-registry-prometheus-1.3.1.jar:lib/org.quartz-scheduler.quartz-2.3.2.jar io.strimzi.operator.cluster.Main
2020-08-12 07:11:54 INFO  Main:60 - ClusterOperator 0.20.0-SNAPSHOT is starting
2020-08-12 07:11:54 WARN  ClusterOperatorConfig:111 - Kafka TLS sidecar container has been removed and the environment variable STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE is not used anymore. You can remove it from the Strimzi Cluster Operator deployment.
Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: Failed to parse default container image configuration for Kafka from environment variable STRIMZI_KAFKA_IMAGES
	at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:240)
	at io.strimzi.operator.cluster.ClusterOperatorConfig.fromMap(ClusterOperatorConfig.java:100)
	at io.strimzi.operator.cluster.Main.main(Main.java:61)
Caused by: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.6.0 in {2.4.0=strimzi/kafka:2.5.0-kafka-2.4.0, 2.4.1=strimzi/kafka:2.5.0-kafka-2.4.1, 2.5.0=strimzi/kafka:2.5.0-kafka-2.5.0}
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.image(KafkaVersion.java:163)
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.validateKafkaImages(KafkaVersion.java:195)
	at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:222)
	... 2 more

 ```
operator.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: controlplane
  creationTimestamp: "2020-08-08T11:58:54Z"
  generation: 1
  labels:
    app: strimzi
    app.kubernetes.io/managed-by: Helm
    chart: strimzi-kafka-operator-0.19.0
    component: deployment
    heritage: Helm
    release: kafka
  name: strimzi-cluster-operator
  namespace: controlplane
  resourceVersion: "13004199"
  selfLink: /apis/extensions/v1beta1/namespaces/controlplane/deployments/strimzi-cluster-operator
  uid: 40b95c95-1821-45ad-8057-35781cdaed13
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      containers:
      - args:
        - /opt/strimzi/bin/cluster_operator_run.sh
        env:
        - name: STRIMZI_NAMESPACE
          value: '*'
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          value: strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
          value: strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
          value: strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
          value: strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.4.0=strimzi/kafka:latest-kafka-2.4.0
            2.4.1=strimzi/kafka:latest-kafka-2.4.1
            2.5.0=strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_KAFKA_CONNECT_IMAGES
          value: |
            2.4.0=strimzi/kafka:latest-kafka-2.4.0
            2.4.1=strimzi/kafka:latest-kafka-2.4.1
            2.5.0=strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.4.0=strimzi/kafka:latest-kafka-2.4.0
            2.4.1=strimzi/kafka:latest-kafka-2.4.1
            2.5.0=strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.4.0=strimzi/kafka:latest-kafka-2.4.0
            2.4.1=strimzi/kafka:latest-kafka-2.4.1
            2.5.0=strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
          value: |
            2.4.0=strimzi/kafka:latest-kafka-2.4.0
            2.4.1=strimzi/kafka:latest-kafka-2.4.1
            2.5.0=strimzi/kafka:latest-kafka-2.5.0
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: strimzi/operator:latest
        - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
          value: strimzi/kafka-bridge:0.18.0
        - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
          value: strimzi/jmxtrans:latest
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        image: strimzi/operator:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthy
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: strimzi-cluster-operator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 384Mi
          requests:
            cpu: 200m
            memory: 384Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: strimzi-cluster-operator
      serviceAccountName: strimzi-cluster-operator
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-08-08T11:58:54Z"
    lastUpdateTime: "2020-08-08T11:59:29Z"
    message: ReplicaSet "strimzi-cluster-operator-7d647bdcc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-08-11T18:57:15Z"
    lastUpdateTime: "2020-08-11T18:57:15Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

```
</details>

**Comment by Hashfyre** [comment]
The `2.6.0` is not part of the image map in any of the config variables, but neither am I passing any config through values.yaml that explicitly asks the operator to pull `2.6.0`, shouldn't it just try and deploy the highest version available in it's config?

**Comment by Hashfyre** [comment]
I tried fixing version through values.yaml `tagPrefix`, but the operator still wants to pull `2.6.0`
```
# Default values for strimzi-kafka-operator.

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: true

image:
  repository: strimzi
  name: operator
  tag: latest
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local

tolerations: []
affinity: {}
nodeSelector: {}

# Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
# repository name with your registry URL.
# Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
zookeeper:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: latest
kafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 2.5.0
kafkaConnect:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 2.5.0
kafkaConnects2i:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 2.5.0
topicOperator:
  image:
    repository: strimzi
    name: operator
    tag: 2.5.0
userOperator:
  image:
    repository: strimzi
    name: operator
    tag: latest
kafkaInit:
  image:
    repository: strimzi
    name: operator
    tag: latest
tlsSidecarKafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 2.5.0
tlsSidecarEntityOperator:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 2.5.0
kafkaMirrorMaker:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 2.5.0
kafkaBridge:
  image:
    repository: strimzi
    name: kafka-bridge
    tag: 0.18.0
kafkaExporter:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: latest
jmxTrans:
  image:
    repository: strimzi
    name: jmxtrans
    tag: latest
kafkaMirrorMaker2:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: latest
cruiseControl:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: latest
tlsSidecarCruiseControl:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: latest
resources:
  limits:
    memory: 384Mi
    cpu: 1000m
  requests:
    memory: 384Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

# Override the docker image repository used by all Strimzi images
imageRepositoryOverride: ""
# Override the docker image tag used by all Strimzi images
imageTagOverride: ""
createGlobalResources: true

```

**Comment by scholzj** [comment]
2.6.0 is not supported in 0.18.0 or 0.19.0 releases since it didn't exist when they were released. So this is not a bug. 2.6.0 is supported only on master. 

If you get this error by using the exampels from the master branch, you have to use the examples from the tag corresponding to your Strimzi release (e.g. https://github.com/strimzi/strimzi-kafka-operator/tree/0.18.0) or downloaded from the release page.

**Comment by Hashfyre** [comment]
So, why does the v.18.0 and v.19.0 helm chart try to pull 2.6.0? How is that not a bug?

**Comment by scholzj** [comment]
How did you installed the helm chart for that version?

**Comment by Hashfyre** [comment]
with standard helm install command
```
helm install kafka strimzi/strimzi-kafka-operator --version 0.18.0 -f values.yaml -n controlplane
NAME: kafka
LAST DEPLOYED: Wed Aug 12 13:16:16 2020
NAMESPACE: controlplane
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing strimzi-kafka-operator-0.18.0

To create a Kafka cluster refer to the following documentation.

https://strimzi.io/docs/0.18.0/#kafka-cluster-str
```

**Comment by scholzj** [comment]
So what is in your `values.yaml` file?

**Comment by scholzj** [comment]
Do 0.18.0 release, it has to correspond to this one: https://github.com/strimzi/strimzi-kafka-operator/blob/0.18.0/helm-charts/strimzi-kafka-operator/values.yaml

**Comment by Hashfyre** [comment]
Initially nothing. I went with defaults. After that I tried pinning versions to `2.5.0` with `tagPrefix: 2.5.0`, which I posted above
https://github.com/strimzi/strimzi-kafka-operator/issues/3498#issuecomment-672692327

**Comment by scholzj** [comment]
But what does it mean "nothing" and "I went with defaults"? You passed in the file which has the values. So the question is whether it was the right file for 0.18.0 release (https://github.com/strimzi/strimzi-kafka-operator/blob/0.18.0/helm-charts/strimzi-kafka-operator/values.yaml) or the one for master branch which would not pull in 0.18.0 release but master.

**Comment by Hashfyre** [comment]
It means I did not pass a values.yaml, when one does that the chart respects default values. The chart version should dictate what those default values are, since passing values are optional.

**Comment by scholzj** [comment]
So was the `values.yaml` file empty in your `helm install` command from https://github.com/strimzi/strimzi-kafka-operator/issues/3498#issuecomment-672700944?

**Comment by Hashfyre** [comment]
I just used the `/v0.18.0/values.yaml` and installed once again, the same error persists.

**Comment by Hashfyre** [comment]
OK, just rehashing the runs since there seems to be a confusion:
trial01:
`helm install kafka strimzi/strimzi-kafka-operator --version 0.18.0 -n controlplane`
# expected to use sane defaults from v0.18.0 release, the above posted log was the output

trial02:
`helm install kafka strimzi/strimzi-kafka-operator --version 0.18.0 -f values.yaml -n controlplane`
with `values.yaml` `tagPrefix: 2.5.0`, this was me figuring out what tag was needed, clearly wrong. And obviously did nothing. Error persisted

trial03:
`helm install kafka strimzi/strimzi-kafka-operator --version 0.18.0 -f values.yaml -n controlplane`
with:  (https://github.com/strimzi/strimzi-kafka-operator/blob/0.18.0/helm-charts/strimzi-kafka-operator/values.yaml)
No change in issue, error persists.

**Comment by scholzj** [comment]
So I'm trying to reproduce it, so I did the following:

```
minikube start
helm2 init
helm2 repo add strimzi https://strimzi.io/charts/
helm2 install strimzi/strimzi-kafka-operator --version 0.18.0
```

The result is that the operator is running without any issues for me. In the operator log during the startup, I can see this:

```
2020-08-12 08:17:53 INFO  Main:60 - ClusterOperator 0.18.0 is starting
```

which is important as it confirms it installed Strimzi 0.18.0. Also in the operator deployment I can see that it is using the `strimzi/operator:0.18.0` image. Can you check yours? I assume that for whatever reason your is trying to pull the `strimzi/operator:latest` image which is wrong.

Also, what version of Helm are you using? Is that Helm 3? Or what version is it?

**Comment by Hashfyre** [comment]
after trial03 it eventually came back around. Albeit after a significant delay of crashloops.
