### ISSUE TITLE
[Question] Cluster roles required to use default storage class? 

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3581]
I was provisioning a Kafka cluster with storage type.= jbod.

Getting this error
```
$ k describe kafka -n kafka
Name:         k8s
Namespace:    kafka
Labels:       <none>
Annotations:  <none>
API Version:  kafka.strimzi.io/v1beta1
Kind:         Kafka
Metadata:
  Creation Timestamp:  2020-09-01T13:54:58Z
  Generation:          1
  Resource Version:    542308395
  Self Link:           /apis/kafka.strimzi.io/v1beta1/namespaces/kafka/kafkas/k8s
  UID:                 5cccdada-7f24-491e-beda-572238e87810
Spec:
  Entity Operator:
    Topic Operator:
      Template:
        Pod:
          Tolerations:
            Effect:    NoSchedule
            Key:       dedicated
            Operator:  Equal
            Value:     prometheus
    User Operator:
      Template:
        Pod:
          Tolerations:
            Effect:    NoSchedule
            Key:       dedicated
            Operator:  Equal
            Value:     prometheus
  Kafka:
    Config:
      log.message.format.version:                2.5
      offsets.topic.replication.factor:          3
      transaction.state.log.min.isr:             2
      transaction.state.log.replication.factor:  3
    Listeners:
      External:
        Tls:   true
        Type:  nodeport
    Replicas:  3
    Storage:
      Type:  jbod
      Volumes:
        Delete Claim:  false
        Id:            0
        Size:          10Gi
        Type:          persistent-claim
        Delete Claim:  false
        Id:            1
        Size:          10Gi
        Type:          persistent-claim
    Template:
      Pod:
        Tolerations:
          Effect:    NoSchedule
          Key:       dedicated
          Operator:  Equal
          Value:     prometheus
    Version:         2.5.0
  Zookeeper:
    Replicas:  3
    Storage:
      Delete Claim:  false
      Size:          30Gi
      Type:          persistent-claim
    Template:
      Pod:
        Tolerations:
          Effect:    NoSchedule
          Key:       dedicated
          Operator:  Equal
          Value:     prometheus
Status:
  Conditions:
    Last Transition Time:  2020-09-01T13:55:01+0000
    Message:               Failure executing: POST at: https://100.64.0.1/api/v1/namespaces/kafka/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims "data-k8s-zookeeper-0" is forbidden: Internal error occurred: 2 default StorageClasses were found.
    Reason:                KubernetesClientException
    Status:                True
    Type:                  NotReady
  Observed Generation:     1
Events:                    <none>
```
- What is the service account used by Kafka CRD and what are the roles required for it?
- Also what is difference between persistent type and jbod types was not very clear from the documentation. When to choose one over the other?

**Comment by scholzj** [comment]
Can you provide the operator log file?I'm quite curious in which part did this error happened. Also, the most interesting part seems to be at the end where it says `2 default StorageClasses were found.`. So I'm wondering what is really the problem ... is it two default storage classes? (only one can be default, if you have two defaults nobody knows which one should be used). Or is it actually an RBAC issue?

The CR does not have a service account. The operator does. You can find it all in the installation YAMLs here: https://github.com/strimzi/strimzi-kafka-operator/tree/0.19.0/install/cluster-operator ... but unless you changes some RBAC files, I would start by checking the storage classes before the RBAC.

**Comment by alok87** [comment]
Yes my cluster has started with default configuration and somehow it is showing 2 defaults.
```
ubuntu @ kuber-mumbai :~ $ k get storageclass
NAME                        PROVISIONER             AGE
aws-efs                     example.com/aws-efs     96d
default                     kubernetes.io/aws-ebs   285d
gp2 (default)               kubernetes.io/aws-ebs   285d
gp2-ap-south-1b (default)   kubernetes.io/aws-ebs   159d
```


The log is pretty huge
```
2020-09-02 05:17:45 WARN  AbstractOperator:330 - Reconciliation #617(timer) Kafka(kafka/k8s): Failed to reconcile
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://100.64.0.1/api/v1/namespaces/kafka/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims "data-k8s-zookeeper-0" is forbidden: Internal error occurred: 2 default StorageClasses were found.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:241) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:819) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:330) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
        at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalCreate(AbstractResourceOperator.java:194) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:100) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:3
```

But why could this happen, we never changed anything manually? 🤔  I would go about by manually specifying the storage class. thanks.

**Comment by alok87** [comment]
After removing the other default, now getting this. 

I have actually applied all these YAMLs for cluster roles. https://github.com/strimzi/strimzi-kafka-operator/tree/0.19.0/install/cluster-operator

```
2020-09-02 07:53:49 WARN  AbstractOperator:330 - Reconciliation #4(timer) Kafka(kafka/k8s): Failed to reconcile
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://100.64.0.1/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/strimzi-kafka-k8s-kafka-init. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. clusterrolebindings.rbac.authorization.k8s.io "strimzi-kafka-k8s-kafka-init" is forbidden: User "system:serviceaccount:kafka:strimzi-cluster-operator" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:447) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:337) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:318) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:833) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:226) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:170) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractNonNamespacedResourceOperator.lambda$reconcile$0(AbstractNonNamespacedResourceOperator.java:95) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by alok87** [comment]
Closing this `namespace: myproject` was the issue. 

Changing the default to one fixed the issue, thanks yet again :)
