### ISSUE TITLE
[Bug] __consumer_offsets is being constantly deleted by topic-operator

### ISSUE THREAD

**Issue by synepolskyi** [strimzi/strimzi-kafka-operator#3586]
**Describe the bug**
Kafka topic __consumer_offsets is being deleted by TopicOperator every 3 minutes.
Kafka was re-deployed before it started to happen.

**To Reproduce**
Steps to reproduce the behavior (I'll describe it on the current setup):
1. Have existing Kafka cluster with 3 brokers and 1 ZooKeeper. All the storages are persistent-claims:
```
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        deleteClaim: false
```
2. Delete Kafka CRD
3. Verify that all pods are deleted, but 4 PVCs are in place
4. Deploy cluster with absolutely the same configuration
5. Go to topics-operator logs and see error:
`kubectl logs entity-operator-xxxxxxxx-yyyyy -c topic-operator`
```[2020-09-02 08:41:40,253] INFO  <opicsWatcher:96> [calhost:2181] Created topics: [__consumer_offsets]
[2020-09-02 08:41:40,286] WARN  <Util        :77> [-ops-pool-19] Caught exception while waiting for deleted sync __consumer_offsets to get deleted
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.LeaderNotAvailableException: There is no leader for this topic-partition as we are in the middle of a leadership election.
	at io.strimzi.operator.topic.KafkaImpl.lambda$null$0(KafkaImpl.java:235) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
	at io.strimzi.operator.common.Util$1.lambda$handle$0(Util.java:70) ~[io.strimzi.operator-common-0.18.0.jar:0.18.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.LeaderNotAvailableException: There is no leader for this topic-partition as we are in the middle of a leadership election.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45) ~[org.apache.kafka.kafka-clients-2.5.0.jar:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32) ~[org.apache.kafka.kafka-clients-2.5.0.jar:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89) ~[org.apache.kafka.kafka-clients-2.5.0.jar:?]
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260) ~[org.apache.kafka.kafka-clients-2.5.0.jar:?]
	at io.strimzi.operator.topic.KafkaImpl.lambda$null$0(KafkaImpl.java:230) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
	... 7 more
Caused by: org.apache.kafka.common.errors.LeaderNotAvailableException: There is no leader for this topic-partition as we are in the middle of a leadership election.
[2020-09-02 08:42:10,170] WARN  <opicOperator:496> [oop-thread-0] 189|/brokers/topics -__consumer_offsets: Lock not acquired within 30000ms: action onTopicDeleted will not be run
[2020-09-02 08:42:10,170] WARN  <opicsWatcher:89> [oop-thread-0] 189|/brokers/topics -__consumer_offsets: Error responding to deletion of topic __consumer_offsets
io.vertx.core.impl.NoStackTraceThrowable: Failed to acquire lock for topic __consumer_offsets after 30000ms. Not executing action onTopicDeleted
[2020-09-02 08:42:10,254] WARN  <opicOperator:496> [oop-thread-0] 190|/brokers/topics +__consumer_offsets: Lock not acquired within 30000ms: action onTopicCreated will not be run
[2020-09-02 08:42:10,255] WARN  <opicsWatcher:105> [oop-thread-0] 190|/brokers/topics +__consumer_offsets: Error responding to creation of topic __consumer_offsets
io.vertx.core.impl.NoStackTraceThrowable: Failed to acquire lock for topic __consumer_offsets after 30000ms. Not executing action onTopicCreated
[2020-09-02 08:43:39,263] ERROR <Util        :90> [oop-thread-0] Exceeded timeout of 120000ms while waiting for deleted sync __consumer_offsets to be deleted
[2020-09-02 08:43:39,264] ERROR <opicOperator:616> [oop-thread-0] Topic deletion failed with (class io.strimzi.operator.common.operator.resource.TimeoutException) error: Exceeded timeout of 120000ms while waiting for deleted sync __consumer_offsets to be deleted
[2020-09-02 08:43:39,264] ERROR <opicOperator:1374> [oop-thread-0] Error reconciling KafkaTopic null
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 120000ms while waiting for deleted sync __consumer_offsets to be deleted
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:91) ~[io.strimzi.operator-common-0.18.0.jar:0.18.0]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Expected behavior**
STRs are not lead to __consumer_offsets topic re-creation.

**Environment:**
 - Strimzi version: 0.18.0
 - Installation method: helm-chart
 - Kubernetes cluster: kubernetes 1.16
 - Infrastructure: Google Kubernetes Engine

**Part of configuration that may be related to the issue**:
```
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    replicas: 3
    version: 2.5.0
    config:
      default.replication.factor: 3
      log.message.format.version: 2.5
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
```
Also, we use the auto-creation of topics and do not use KafkaTopic custom resources at all.

**Comment by scholzj** [comment]
Can you share the full log file and not just some small snippet? That doesn't really help to understand what is going on. 

Also, if you are not using the topic operator, you should just remove the `topicOperator: {}` line from your Kafka cluster to disable it.

**Comment by cuddlyporcupine** [comment]
i see this issue as well.... looks like the topic operator is "reconciling" and then decides to delete the `__consumer_offsets` topic

```
[2020-11-19 19:48:38,042] INFO  <opicOperator:535> [oop-thread-0] 148176|periodic kafka __consumer_offsets: Reconciling topic __consumer_offsets, k8sTopic:null, kafkaTopic:nonnull, privateTopic:nonnull
[2020-11-19 19:48:38,042] INFO  <opicOperator:361> [oop-thread-0] 148176|periodic kafka __consumer_offsets: Deleting topic '__consumer_offsets'
[2020-11-19 19:48:38,110] WARN  <Util        :77> [-ops-pool-15] Caught exception while waiting for deleted sync __consumer_offsets to get deleted
```

**Comment by scholzj** [comment]
@tombentley @ppatierno @sknot-rh Any ideas? ^^^

**Comment by vutkin** [comment]
Hi, I confirm the bug.

**Comment by tombentley** [comment]
Is this reproducible using the current master? It's possible that the changes in https://github.com/strimzi/strimzi-kafka-operator/pull/3982 have fixed this.

**Comment by tombentley** [comment]
If it is reproducible it would be great to have some `TRACE`-level logs from the TO.
