### ISSUE TITLE
[Question] Brokers roll and then don't pass readiness during peak feed times

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3591]
I went to add 3 brokers to the cluster by modifying the resource during a high point during the day for feeds.  The brokers began to roll over and then didn't come back continually failing readiness checks. 

What's the best way to fix this? Temporarily increase the readiness time for the brokers?

**Comment by jrivers96** [comment]
`k logs kafka-broker -c kafka logs --follow`

```2020-09-02 15:35:21,061 INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient) [main]
2020-09-02 15:35:21,065 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-02 15:35:21,069 INFO Socket connection established, initiating session, client: /127.0.0.1:46312, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-02 15:35:31,081 WARN Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
2020-09-02 15:35:32,519 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-02 15:35:32,520 INFO Socket connection established, initiating session, client: /127.0.0.1:46378, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-02 15:35:39,063 INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient) [main]
2020-09-02 15:35:42,628 INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper) [main]
2020-09-02 15:35:42,629 INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn) [main-EventThread]
2020-09-02 15:35:42,631 INFO [ZooKeeperClient Kafka server] Closed. (kafka.zookeeper.ZooKeeperClient) [main]
2020-09-02 15:35:42,634 ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:262)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:258)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:119)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1863)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:378)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:403)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:210)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
	at kafka.Kafka$.main(Kafka.scala:82)
	at kafka.Kafka.main(Kafka.scala)
2020-09-02 15:35:42,634 INFO shutting down (kafka.server.KafkaServer) [main]
2020-09-02 15:35:42,649 INFO shut down completed (kafka.server.KafkaServer) [main]
2020-09-02 15:35:42,650 ERROR Exiting Kafka. (kafka.server.KafkaServerStartable) [main]```

**Comment by scholzj** [comment]
The error suggests problems with your Zookeeper cluster. So you should probably start by checking that. From this log it doesn't seem to be the readiness probe shutting them down - instead they don't start because they cannot connect to Zookeeper.

**Comment by jrivers96** [comment]
You are correct. I didn't notice zookeeper being down because I didn't see any zookeeper down alerts. There also were no liveness restarts which is interesting. 

``` 
k -n namespace logs kafka-cluster-zookeeper-1
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-02 15:56:59,607 INFO Authenticated Id 'CN=kafka-cluster-entity-operator,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-2]
2020-09-02 15:56:59,608 WARN Closing connection to /100.80.23.99:46648 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-7-2]
java.io.IOException: ZK down
	at org.apache.zookeeper.server.NettyServerCnxn.receiveMessage(NettyServerCnxn.java:474)
	at org.apache.zookeeper.server.NettyServerCnxn.processMessage(NettyServerCnxn.java:360)
	at org.apache.zookeeper.server.NettyServerCnxnFactory$CnxnChannelHandler.channelRead(NettyServerCnxnFactory.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-02 15:57:00,353 INFO Authenticated Id 'CN=kafka-cluster-kafka,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-1]
2020-09-02 15:57:00,356 WARN Closing connection to /100.80.47.142:58256 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-7-1]

```

**Comment by jrivers96** [comment]
A networking tool called CALICO caused the kafka connection to zookeeper to fail. The same tool may have kept the alerts from going out.

**Comment by scholzj** [comment]
Interesting. I'm using Calico in my cluster as well, but never saw this problem so far. I will watch out for it.

**Comment by RooSoft** [comment]
Having the same problem as we speak... how do you guys know it's caused by calico?

I am also using it...

**Comment by RooSoft** [comment]
Only happens when I ask for more than one replica...

**Comment by scholzj** [comment]
More than one replica of what? Zookeeper? That might indicate that the the Zookeeper cluster does not form and that is why your Kafka cannot connet.

**Comment by RooSoft** [comment]
Exactly...

I'd really like to know why...

**Comment by scholzj** [comment]
Well, I suggest you start a new topic in https://github.com/strimzi/strimzi-kafka-operator/discussions and share there all your configurations, logs etc. Nobody will be able to help you just from _it does not work_.

**Comment by RooSoft** [comment]
Will try harder tomorrow and then report back in the appropriate channel

**Comment by RooSoft** [comment]
Although not ideal, [this solution](https://github.com/strimzi/strimzi-kafka-operator/issues/3692#issuecomment-696952238) worked for me on our test cluster.

**Comment by lanzhiwang** [comment]
Have you considered the influence of networkpolicy? Different cni plugins handle networkpolicy differently?

**Comment by lanzhiwang** [comment]
From the current point of view, the networkpolicy created by strimzi operators does not seem to have much work?

**Comment by lanzhiwang** [comment]
Why create a networkpolicy?

**Comment by scholzj** [comment]
We use network policy as well. But network policy alone is far away from sufficient in terms of security.

**Comment by scholzj** [comment]
TBH, if you wanna keep discussing this, it might be best to start a new discussion for it or discuss it on Slack. Discussing it on completely unrelated issue which is closed is not the right way.
