### ISSUE TITLE
[bug] Operators fails to connect to zookeeper and deploy Kafka pod in OpenShift 4.4 and 4.5

### ISSUE THREAD

**Issue by msfrucht** [strimzi/strimzi-kafka-operator#3616]
The operator pod is unable to reach the Zookeeper pods and therefore never spawns the Kafka pod and cluster specific operator. Deleting the zookeeper network policy causes the operator to sometimes create the Kafka pods and cluster specific operator.

Tested with both Red Hat AMQ Streams 1.5.3 based on Strimzi 0.18.x and tried with Strimzi 0.18 directly. So this appears to be an underlying issue in Strimzi.

I applied the kafka-ephemeral-single.yaml example. The 3 zookeeper pods came up. the Kafka pod did not get created.

Logs and YAMLs are from Red Hat AMQ Streams

Environment:
Openshift Client Version: 4.5.5
Openshift Server Version: 4.5.5
Kubernetes Version: v1.18.3+08c38ef

Software Versions:
Red Hat AMQ Streams 1.5.3
Strimzi: 0.18.0

[labuser@oakmont3vm33 Downloads]$ oc get all
NAME                                                       READY   STATUS    RESTARTS   AGE
pod/amq-streams-cluster-operator-v1.5.3-5fc8d47f84-j8vsm   1/1     Running   0          2m10s
pod/my-cluster-zookeeper-0                                 1/1     Running   0          51s
pod/my-cluster-zookeeper-1                                 1/1     Running   0          51s
pod/my-cluster-zookeeper-2                                 1/1     Running   0          51s

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/my-cluster-zookeeper-client   ClusterIP   172.30.200.181   <none>        2181/TCP                     53s
service/my-cluster-zookeeper-nodes    ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   52s

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/amq-streams-cluster-operator-v1.5.3   1/1     1            1           2m11s

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/amq-streams-cluster-operator-v1.5.3-5fc8d47f84   1         1         1       2m10s

NAME                                    READY   AGE
statefulset.apps/my-cluster-zookeeper   3/3     51s

Partial Operator logs:
2020-09-08 18:38:38 WARN  KafkaAssemblyOperator:1595 - {}: Failed to verify Zookeeper configuration
io.strimzi.operator.cluster.operator.resource.ZookeeperScalingException: Failed to connect to Zookeeper my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.baas.svc:2181. Connection was not ready in 300000 ms.
	at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.lambda$connect$5(ZookeeperScaler.java:157) ~[io.strimzi.cluster-operator-0.18.0.redhat-00003.jar:0.18.0.redhat-00003]
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:197) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:127) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:115) ~[io.strimzi.operator-common-0.18.0.redhat-00003.jar:0.18.0.redhat-00003]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for ZooKeeperAdmin connection to my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.baas.svc:2181 to be connected
	... 11 more
2020-09-08 18:38:38 INFO  OperatorWatcher:40 - Reconciliation #5(watch) Kafka(baas/my-cluster): Kafka my-cluster in namespace baas was MODIFIED
2020-09-08 18:38:38 ERROR AbstractOperator:175 - Reconciliation #0(watch) Kafka(baas/my-cluster): createOrUpdate failed
io.strimzi.operator.cluster.operator.resource.ZookeeperScalingException: Failed to connect to Zookeeper my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.baas.svc:2181. Connection was not ready in 300000 ms.
	at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.lambda$connect$5(ZookeeperScaler.java:157) ~[io.strimzi.cluster-operator-0.18.0.redhat-00003.jar:0.18.0.redhat-00003]
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:197) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:127) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:115) ~[io.strimzi.operator-common-0.18.0.redhat-00003.jar:0.18.0.redhat-00003]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for ZooKeeperAdmin connection to my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.baas.svc:2181 to be connected
	... 11 more
2020-09-08 18:38:38 WARN  AbstractOperator:330 - Reconciliation #0(watch) Kafka(baas/my-cluster): Failed to reconcile
io.strimzi.operator.cluster.operator.resource.ZookeeperScalingException: Failed to connect to Zookeeper my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.baas.svc:2181. Connection was not ready in 300000 ms.
	at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.lambda$connect$5(ZookeeperScaler.java:157) ~[io.strimzi.cluster-operator-0.18.0.redhat-00003.jar:0.18.0.redhat-00003]
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:197) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:127) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:115) ~[io.strimzi.operator-common-0.18.0.redhat-00003.jar:0.18.0.redhat-00003]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.redhat-00005.jar:3.8.5.redhat-00005]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.48.Final-redhat-00001.jar:4.1.48.Final-redhat-00001]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for ZooKeeperAdmin connection to my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.baas.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.baas.svc:2181 to be connected
	... 11 more
2020-09-08 18:38:38 INFO  AbstractOperator:173 - Reconciliation #5(watch) Kafka(baas/my-cluster): Kafka my-cluster should be created or updated
2020-09-08 18:39:58 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace baas...
2020-09-08 18:40:09 WARN  AbstractOperator:247 - Reconciliation #6(timer) Kafka(baas/my-cluster): Failed to acquire lock lock::baas::Kafka::my-cluster within 10000ms.
2020-09-08 18:41:58 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace baas...
2020-09-08 18:42:09 WARN  AbstractOperator:247 - Reconciliation #7(timer) Kafka(baas/my-cluster): Failed to acquire lock lock::baas::Kafka::my-cluster within 10000ms.

Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2020-09-08T18:33:08Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: strimzi-my-cluster
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: strimzi
  managedFields:
  - apiVersion: networking.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:strimzi.io/cluster: {}
          f:strimzi.io/kind: {}
          f:strimzi.io/name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"99e952f1-3600-489f-9e1a-8f732cee98d7"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ingress: {}
        f:podSelector:
          f:matchLabels:
            .: {}
            f:strimzi.io/name: {}
        f:policyTypes: {}
    manager: okhttp
    operation: Update
    time: "2020-09-08T18:33:08Z"
  name: my-cluster-network-policy-zookeeper
  namespace: baas
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: my-cluster
    uid: 99e952f1-3600-489f-9e1a-8f732cee98d7
  resourceVersion: "15742656"
  selfLink: /apis/networking.k8s.io/v1/namespaces/baas/networkpolicies/my-cluster-network-policy-zookeeper
  uid: d14791aa-7e54-437a-8d97-d79556b3eb3b
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/name: my-cluster-zookeeper
    ports:
    - port: 2888
      protocol: TCP
    - port: 3888
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/name: my-cluster-kafka
    - podSelector:
        matchLabels:
          strimzi.io/name: my-cluster-zookeeper
    - podSelector:
        matchLabels:
          strimzi.io/name: my-cluster-entity-operator
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          strimzi.io/kind: cluster-operator
    - podSelector:
        matchLabels:
          strimzi.io/name: my-cluster-cruise-control
    ports:
    - port: 2181
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: my-cluster-zookeeper
  policyTypes:
  - Ingress

Services:
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-09-08T18:58:04Z"
    labels:
      app.kubernetes.io/instance: my-cluster
      app.kubernetes.io/managed-by: strimzi-cluster-operator
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/part-of: strimzi-my-cluster
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-zookeeper-client
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:strimzi.io/cluster: {}
            f:strimzi.io/kind: {}
            f:strimzi.io/name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a7b0cdb4-dd83-4e10-b040-a8c2134f1c33"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":2181,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:strimzi.io/cluster: {}
            f:strimzi.io/kind: {}
            f:strimzi.io/name: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: okhttp
      operation: Update
      time: "2020-09-08T18:58:04Z"
    name: my-cluster-zookeeper-client
    namespace: baas
    ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta1
      blockOwnerDeletion: false
      controller: false
      kind: Kafka
      name: my-cluster
      uid: a7b0cdb4-dd83-4e10-b040-a8c2134f1c33
    resourceVersion: "15755210"
    selfLink: /api/v1/namespaces/baas/services/my-cluster-zookeeper-client
    uid: b3696913-90ce-4470-85b3-f707b9f0d467
  spec:
    clusterIP: 172.30.128.175
    ports:
    - name: tcp-clients
      port: 2181
      protocol: TCP
      targetPort: 2181
    selector:
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-zookeeper
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: "2020-09-08T18:58:04Z"
    labels:
      app.kubernetes.io/instance: my-cluster
      app.kubernetes.io/managed-by: strimzi-cluster-operator
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/part-of: strimzi-my-cluster
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-zookeeper-nodes
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:service.alpha.kubernetes.io/tolerate-unready-endpoints: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:strimzi.io/cluster: {}
            f:strimzi.io/kind: {}
            f:strimzi.io/name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a7b0cdb4-dd83-4e10-b040-a8c2134f1c33"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            .: {}
            k:{"port":2181,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":2888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":3888,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:publishNotReadyAddresses: {}
          f:selector:
            .: {}
            f:strimzi.io/cluster: {}
            f:strimzi.io/kind: {}
            f:strimzi.io/name: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: okhttp
      operation: Update
      time: "2020-09-08T18:58:04Z"
    name: my-cluster-zookeeper-nodes
    namespace: baas
    ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta1
      blockOwnerDeletion: false
      controller: false
      kind: Kafka
      name: my-cluster
      uid: a7b0cdb4-dd83-4e10-b040-a8c2134f1c33
    resourceVersion: "15755218"
    selfLink: /api/v1/namespaces/baas/services/my-cluster-zookeeper-nodes
    uid: d2e55d5d-824c-4542-a21f-285916bce97a
  spec:
    clusterIP: None
    ports:
    - name: tcp-clients
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: tcp-clustering
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: tcp-election
      port: 3888
      protocol: TCP
      targetPort: 3888
    publishNotReadyAddresses: true
    selector:
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-zookeeper
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by msfrucht** [comment]
Followed up with Jakob Scholz on Slack.

Believed to be a bug with OpenShift 4.4 and 4.5 network plugin. Adding additional networkpolicy allowed operator to connect to zookeeper.

Requirements: operator is installed in same namespace as Kafka cluster to be deployed.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test
  namespace: baas<--- change to appropriate namespace
spec:
  ingress: 
  - {}
  podSelector:
    matchLabels:
      strimzi.io/name: my-cluster-zookeeper <-- change based on name of kafka cluster
  policyTypes:
  - Ingress

An bug report with Red Hat will be opened to address this issue.

**Comment by rareddy** [comment]
@msfrucht I am running into a similar issue in OpenShift 4.8, did you by chance have the BZ you filed with Redhat for reference?

**Comment by msfrucht** [comment]
@rareddy We did not open an issue with Red Hat. We found the issue was fixed in 4.6.

Recent issues with connecting to Zookeeper by the operator in our environments was due to our networkpolicy pod selector labels interacting with Zookeeper container labels.

**Comment by rareddy** [comment]
@msfrucht thank you. Was there a specific issue in 4.6 fixed this?

>Recent issues with connecting to Zookeeper by the operator in our environments was due to our networkpolicy pod selector >labels interacting with Zookeeper container labels.

That seems to indicate you will have an issue when this is was not configured correctly, in my case I am seeing the issue intermittently at random times. Did u also encounter anything like that?

**Comment by msfrucht** [comment]
No. The connection failures to zookeeper due to networkpolicy configuration was not intermittent. It either worked or didn't. 

At least part of the configuration issue turned out to be the difference between OpenshiftSDN and OVNKubernetes network types. OpenshiftSDN ignores egress statements while OVNKubernetes implements them correctly.

The offending overlapping network policy that blocked connections only happened on OVNKubernetes and not OpenshiftSDN.

You can check the type by running 'oc get network -o yaml'. Some cloud providers use calico instead.

**Comment by rareddy** [comment]
@msfrucht  thanks. I am using OpenShift Dedicated (OSD) it is using the network type `OpenshiftSDN`. it is very random I see it once every other day or so, then it recovers the connection soon after.

**Comment by valencetech** [comment]
I observe this same issue with AKS cluster using Cilium CNI. It is not consistent with a very high likelihood of about 80%.
Removing the Zookeeper Network Policy resolves this as mentioned in previous posts.

**Comment by thpham** [comment]
Actually, I've the same issue with openshift 4.9, I investigated a bit and I'm wondering if it could be related to NetworkPolicy automatically created by the operator:
![strimzi-default-networkpolicy-issue](https://user-images.githubusercontent.com/224674/153237949-58bbed39-b00e-4242-b401-08ecbe5ce77a.png)

and combining `podSelector` and `namespaceSelector` are not available in OpenShift Container Platform.

[Source](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_networking.html#admin-guide-networking-networkpolicy), it reference openshift 3.11, I'm not sure if it changed since ?

**Comment by scholzj** [comment]
AFAIK this is 3.11 speciality. I never had any issues with this on OCP 4.9.

**Comment by scholzj** [comment]
I'm not aware of any `openshift-strimzi` namespace. When you install it using OperatorHub UI, it will end up in the namespace it watches or in `openshift-operators`. When you install it from YAMLs, you can install it whereever you want (but need to adjust the installation files accordingly).

**Comment by thpham** [comment]
I totally understand that it is not recommended and I agree we should let the operator create the NetworkPolicy. This was only to highlight there might be an issue with the policy the operator creates.

I'm using the default ROSA setup, I don't use multitenant SDN and neither any specific project template with NetworkPolicies.

I will try to build a custom image of the operator in the coming days to check what I said about `combining podSelector and namespaceSelector are not available in OpenShift Container Platform.`

I will keep you posted. thank you !

**Comment by thpham** [comment]
Sorry me again, I tried to apply manually the default networkpolicy that the operator would have created while having `STRIMZI_NETWORK_POLICY_GENERATION: false`, and I had the same behaviour. But then, I was able to apply some change to it without having the operator doing the reconciliation.

And instead of:

```
- podSelector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector: {}
```

having a `matchLabels` on the `namespaceSeletor` fixed the issue.

```
- podSelector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: openshift-operators
```

So IMHO, it might be that we need to add some logic in the operator in which namespace he is deployed and which namespace label to choose to distinguish its source to generate the NetworkPolicy correctly.

**Comment by scholzj** [comment]
The operator works fine. We cannot use some special label `kubernetes.io/metadata.name: openshift-operators` because we do not know:
* What labels will the namespace where it runs have
* Whether it will have any labels at all

**Comment by thpham** [comment]
Oh sorry, stupid me ! I miss this env variable !

**Comment by scholzj** [comment]
Triaged on 7th July 2022: It looks like some users managed to resolve the issues. In latest Strimzi versions, you can also completely disable the creation of the network policies and manage them your self. Should be closed.
