### ISSUE TITLE
Help with cruise control

### ISSUE THREAD

**Issue by mugugnu** [strimzi/strimzi-kafka-operator#3650]
Hello, i'm on strimzi 0.18 and kafka2.5.
I've deployed the cruise control adding the cruiseControl: {} to the Kafka manifest
The cruise controls shows as running:

```shell
NAME                                                 READY   STATUS    RESTARTS   AGE
kafka-connect-cluster-connect-558666f6df-hwhf5   1/1     Running   63         40d
kafka-cruise-control-56b689c44d-xv2ck            2/2     Running   0          3d23h
kafka-entity-operator-5845544556-qg5kc           3/3     Running   0          39d
```

Now i scaled down my kafka cluster, from 5 brokers to 3. I now need to rebalance the topics. So i apply a sample manifest for rebalancing:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaRebalance
metadata:
  name: rebalance
  namespace: dev
  labels:
    strimzi.io/cluster: kafka
  spec: {}
```

After this it seems to me that nothing happens. If i ask the dscribtion of the KafkaRebalance object i always get this:

```shell
Name:         rebalance
Namespace:    pem-dev
Labels:       strimzi.io/cluster=pem-kafka
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kafka.strimzi.io/v1alpha1","kind":"KafkaRebalance","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"pem-kafka"}...
              strimzi.io/rebalance: approve
API Version:  kafka.strimzi.io/v1alpha1
Kind:         KafkaRebalance
Metadata:
  Creation Timestamp:  2020-09-15T13:51:48Z
  Generation:          1
  Resource Version:    20699939
  Self Link:           /apis/kafka.strimzi.io/v1alpha1/namespaces/pem-dev/kafkarebalances/rebalance
  UID:                 f7929359-902c-433d-a6a8-f08f02886bf7
Events:                <none>
```

Logs from cruise controls show alwyas this (i'm not considering all the errors due to the removed brokers)

```shell
fka.clients.NetworkClient) [kafka-producer-network-thread | KafkaCruiseControlSampleStoreProducer]
2020-09-15 14:18:59,694 INFO Expiring the session associated with SessionKey{_httpSession=Session@28450c2e{id=node012l1fi4etyg321hhrvfu9z854q68545,x=node012l1fi4etyg321hhrvfu9z854q68545.node0,req=0,res=true},_requestUrl=GET /kafkacruisecontrol/state,_queryParams={}}. (com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager) [UserTaskScanner-0]
2020-09-15 14:18:59,694 INFO UserTask 3ed844b1-d10b-4a75-8d42-435850680f01 is completed and removed from active tasks list (com.linkedin.kafka.cruisecontrol.servlet.UserTaskManager) [UserTaskScanner-0]
2020-09-15 14:18:59,694 INFO Task [3ed844b1-d10b-4a75-8d42-435850680f01] calculation finishes, result:
MonitorState: {state: RUNNING(20.000% trained), NumValidWindows: (0/1) (0.000%), NumValidPartitions: 142/151 (94.040%), flawedPartitions: 0}
ExecutorState: {state: NO_TASK_IN_PROGRESS}
AnalyzerState: {isProposalReady: true, readyGoals: [ReplicaDistributionGoal, PreferredLeaderElectionGoal, RackAwareGoal, TopicReplicaDistributionGoal, LeaderReplicaDistributionGoal, ReplicaCapacityGoal]}
AnomalyDetectorState: {selfHealingEnabled:[], selfHealingDisabled:[DISK_FAILURE, BROKER_FAILURE, METRIC_ANOMALY, GOAL_VIOLATION, TOPIC_ANOMALY], selfHealingEnabledRatio:{DISK_FAILURE=0.0, BROKER_FAILURE=0.0, METRIC_ANOMALY=0.0, GOAL_VIOLATION=0.0, TOPIC_ANOMALY=0.0}, recentGoalViolations:[], recentBrokerFailures:[{anomalyId=8122849a-0bb1-4056-85d2-5bcefa6f5f63, failedBrokersByTimeMs={2=1599841603259}, detectionDate=2020-09-11_16:26:43 UTC, status=IGNORED, statusUpdateDate=2020-09-11_16:26:43 UTC}, {anomalyId=f77a6f03-1e98-4012-8b34-084ee620d8a5, failedBrokersByTimeMs={3=1599841650932}, detectionDate=2020-09-11_16:27:30 UTC, status=IGNORED, statusUpdateDate=2020-09-11_16:27:30 UTC}, {anomalyId=7b529202-5283-44af-a2c3-02dd5aa25efa, failedBrokersByTimeMs={1=1599841554470}, detectionDate=2020-09-11_16:25:54 UTC, status=IGNORED, statusUpdateDate=2020-09-11_16:25:54 UTC}, {anomalyId=6e1e09c1-6024-4ab4-90e4-8f5d5d66cc5d, failedBrokersByTimeMs={4=1600177271769, 3=1600177297537}, detectionDate=2020-09-15_13:44:46 UTC, status=IGNORED, statusUpdateDate=2020-09-15_13:44:46 UTC}, {anomalyId=d2f94b45-9ca5-47f2-8204-85069f36dcec, failedBrokersByTimeMs={0=1599841503185}, detectionDate=2020-09-11_16:25:03 UTC, status=IGNORED, statusUpdateDate=2020-09-11_16:25:03 UTC}, {anomalyId=d1c8da94-a7af-4381-9325-494fcf1626a0, failedBrokersByTimeMs={0=1600177460105, 3=1600177297537, 4=1600177271769}, detectionDate=2020-09-15_13:44:20 UTC, status=IGNORED, statusUpdateDate=2020-09-15_13:44:20 UTC}, {anomalyId=34a177af-0b9b-4842-8054-fe30d7ab3f46, failedBrokersByTimeMs={4=1599841701488}, detectionDate=2020-09-11_16:28:21 UTC, status=IGNORED, statusUpdateDate=2020-09-11_16:28:21 UTC}, {anomalyId=30b5308c-ed7d-4a92-85a6-d63a1f1473d0, failedBrokersByTimeMs={4=1600177271769}, detectionDate=2020-09-15_13:41:11 UTC, status=IGNORED, statusUpdateDate=2020-09-15_13:41:11 UTC}, {anomalyId=889bb8b5-630c-4d70-87de-2f6de9b2cd5b, failedBrokersByTimeMs={4=1600177271769, 3=1600177297537}, detectionDate=2020-09-15_13:41:37 UTC, status=IGNORED, statusUpdateDate=2020-09-15_13:41:37 UTC}], recentMetricAnomalies:[], recentDiskFailures:[], recentTopicAnomalies:[], metrics:{meanTimeBetweenAnomalies:{GOAL_VIOLATION:0.00 milliseconds, BROKER_FAILURE:0.03 milliseconds, METRIC_ANOMALY:0.00 milliseconds, DISK_FAILURE:0.00 milliseconds, TOPIC_ANOMALY:0.00 milliseconds}, meanTimeToStartFix:0.00 milliseconds, numSelfHealingStarted:0, numSelfHealingFailedToStart:0, ongoingAnomalyDuration=3.91 days}, ongoingSelfHealingAnomaly:None, balancednessScore:100.000}
```

It's always no_task_in_progress

How do i wake it up ?

**Comment by scholzj** [comment]
@tomncooper @kyguy @ppatierno Can you help?

**Comment by ppatierno** [comment]
From the CC log it seems there are no valid windows so with enough data for rebalancing.

1. What the `status` of the `KafkaRebalance` when you apply the YAML. There should be something showing the state of the rebalancing in progress and if it's ready you should see a proposal.
2. How long the cluster was running after scaling down and before you applied the `KafkaRebalance` ?
3. How many topics and partitions (and replicas) do you have in the cluster?

**Comment by mugugnu** [comment]
Hello,
these are the topics:

kubectl get KafkaTopic                                                                               
NAME                                                          PARTITIONS   REPLICATION FACTOR
connect-cluster-offsets                                       25           1
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a   50           3
mon-xxxx                                                        1            1
mon-yyyy                                                     3            2
mon-zzzz                                                      1            1
strimzi.cruisecontrol.metrics                                 1            1
strimzi.cruisecontrol.modeltrainingsamples                    32           2
strimzi.cruisecontrol.partitionmetricsamples                  32           2


This is the kafkarebalance resource:

kubectl describe kafkarebalance rebalance                                                           
Name:         rebalance
Namespace:    xxxx
Labels:       strimzi.io/cluster=xxxxx
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kafka.strimzi.io/v1alpha1","kind":"KafkaRebalance","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"pem-kafka"}...
API Version:  kafka.strimzi.io/v1alpha1
Kind:         KafkaRebalance
Metadata:
  Creation Timestamp:  2020-09-15T16:36:25Z
  Generation:          1
  Resource Version:    20728858
  Self Link:           /apis/kafka.strimzi.io/v1alpha1/namespaces/pem-dev/kafkarebalances/rebalance
  UID:                 a83355ab-e0f5-4a8a-827f-b1ff769e0bde
Events:                <none>

It's lacking the status part....it has been like this since the creation !

**Comment by tomncooper** [comment]
@mugugnu Can you try deleting the rebalance resource and recreating it. The initial issue seemed to be due to a lack of sufficient data.

**Comment by mugugnu** [comment]
i already have done it several times !
Actually, i think that when i apply changes to strimzi objects, they don't get really applied.

For example: i've deployed a KafkTopic with 3 partitions and 2 replicas. The KafkaTopic shows those settings, but if log into a kafka pod and describe the topic, it's still partitions:1 and replica:1 (which was previous topic setting).

Here's the kafka-topic output:
        Topic: strimzi.cruisecontrol.metrics    Partition: 0    Leader: 2       Replicas: 2     Isr: 2
Topic: xxxxx        PartitionCount: 1       ReplicationFactor: 1    Configs: segment.bytes=4194304,retention.ms=900000,message.format.vers
ion=2.5-IV0
        Topic: xxxxxx       Partition: 0    Leader: 1       Replicas: 1     Isr: 1

**Comment by tomncooper** [comment]
This could be an issue with your cluster then? What are you running on (platform and k8s version) and how did you deploy strimzi (yaml, helm, etc)

**Comment by ppatierno** [comment]
@mugugnu for sure increasing the replicas is not supported right now, so it's not going to work anyway.
It would be interesting to see Topic Operator log why the partitions weren't increased.

**Comment by mugugnu** [comment]
Looking into the topic operator logs i get this error:
[2020-09-17 07:36:57,899] ERROR <opicOperator:690> [oop-thread-0] 307334|periodic kafka xxxx|19598832: Number of partitions cannot be decreased
[2020-09-17 07:36:57,899] ERROR <opicOperator:1374> [oop-thread-0] Error reconciling KafkaTopic xxxxx
io.strimzi.operator.topic.PartitionDecreaseException: Number of partitions cannot be decreased
        at io.strimzi.operator.topic.TopicOperator.update3Way(TopicOperator.java:693) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.TopicOperator.reconcile(TopicOperator.java:596) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.TopicOperator.lambda$getKafkaAndReconcile$36(TopicOperator.java:1369) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.vertx.core.Future.lambda$compose$3(Future.java:360) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.strimzi.operator.topic.KafkaImpl.lambda$topicMetadata$2(KafkaImpl.java:268) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.KafkaImpl$MetadataWork.complete(KafkaImpl.java:191) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.KafkaImpl$Work.run(KafkaImpl.java:59) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.KafkaImpl$Work.handle(KafkaImpl.java:66) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.topic.KafkaImpl$Work.handle(KafkaImpl.java:56) ~[io.strimzi.topic-operator-0.18.0.jar:0.18.0]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]


The reason is that the topic formerly had 3 partitions and now applying the manifests again, it's back to 1.
Could this maybe be blocking everyhting ?

**Comment by mugugnu** [comment]
Small update: since i just realized that the only operation permitted is increasing the number of partitions, i did it, switching from 1 to 3 and the change got applied. (and topic operator logs show that the topic has been reconciled)
Now, back to my starting issue: what about the cruise control f
i deleted the kadkarebalance object and recreated it (with default goals), still it does not do anything.

The cluster operator is always showing these errors which appear when i create the kafkarebalance object:

2020-09-17 08:09:18 INFO  AbstractOperator:173 - Reconciliation #5878(timer) KafkaRebalance(xxx/rebalance): KafkaRebalance rebalance should be created or updated
2020-09-17 08:09:18 ERROR AbstractOperator:175 - Reconciliation #5878(timer) KafkaRebalance(xxx/rebalance): createOrUpdate failed
java.lang.NullPointerException: null
        at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.reconcile(KafkaRebalanceAssemblyOperator.java:366) ~[io.strimzi.cluster-operator-0.18.0.jar:0.18.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$null$14(KafkaRebalanceAssemblyOperator.java:846) ~[io.strimzi.cluster-operator-0.18.0.jar:0.18.0]
        at io.vertx.core.Future.lambda$compose$3(Future.java:360) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-09-17 08:09:18 WARN  AbstractOperator:330 - Reconciliation #5878(timer) KafkaRebalance(xxx/rebalance): Failed to reconcile

**Comment by ppatierno** [comment]
When the number of partitions is increased, it's done by the Kafka cluster and the partitions should be distributed across the brokers so cruise control doesn't jump into the picture here.
For sure, it's useful when you increase the number of brokers and you want to distribute the topic partitions across the new brokers; it's not done by Kafka itself, so cruise control comes into the picture.
Anyway applying a `KafkaRebalance` in your use case I would expect a status updated with an optimization summary describing to do ... nothing more or less.

**Comment by ppatierno** [comment]
can you first try to update to Strimzi 0.19.0, the `KafkaRebalance` operator is changed. Let us know, thanks.

**Comment by mugugnu** [comment]
Upgrading now would be a mess....anyway the cluster operator logs erros for not being able to reconcile kafkarebalance, that's why it doesn't get a stuatus update and does nothing..Is there nything i can check further ?

The error is this:
2020-09-17 09:17:18 INFO  AbstractOperator:173 - Reconciliation #5960(timer) KafkaRebalance(xxx/rebalance): KafkaRebalance rebalance should be created or updated
2020-09-17 09:17:18 ERROR AbstractOperator:175 - Reconciliation #5960(timer) KafkaRebalance(xxx/rebalance): createOrUpdate failed

**Comment by ppatierno** [comment]
> Upgrading now would be a mess....anyway the cluster operator logs erros for not being able to reconcile kafkarebalance, that's why it doesn't get a stuatus update and does nothing.

Of course, I know that :-)
Just tried 0.18.0 as your version and it works fine for me even using your `KafkaRebalance` resource.
You could try to scale down and up the cluster operator pod and see if it helps.

**Comment by kyguy** [comment]
After working together with @mugugnu on Slack, we found malformed yaml syntax to be the core of the issue. The `spec` section was indented so the Cluster Operator was unable to find it causing a NPE.

After applying the following yaml, the issue was corrected:
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaRebalance
metadata:
  name: rebalance
  namespace: dev
  labels:
    strimzi.io/cluster: kafka
spec: {}
```
