### ISSUE TITLE
[Bug] Wrong metrics check on tests in the Topic Operator

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3659]
There are some tests that are checking wrong metrics values that could warn about a potential bug in the TO where metrics are not updated in the right way in some cases.

- `testOnKafkaTopicAdded_invalidResource` the topic resource is created and it's invalid. The failed reconciliation should be 1.0, not 0.0. If we are checking 0.0 it means that the counter is not incremented properly.
- `testOnTopicCreated_retry` at the end the topic resource is created so the successful reconciliation should be 1.0, not 0.0. If we are checking 0.0 it means that the counter is not incremented properly.
- `testOnTopicCreated_retryTimeout`  at the end the topic resource is created so the successful reconciliation should be 1.0, not 0.0. If we are checking 0.0 it means that the counter is not incremented properly.
- `testReconcile_noResource_withKafka_noPrivate`  at the end the topic resource is created so the successful reconciliation should be 1.0, not 0.0. If we are checking 0.0 it means that the counter is not incremented properly.
- `testReconcile_withResource_withKafka_noPrivate_configsReconcilable` at the end the topic resource is created so the successful reconciliation should be 1.0, not 0.0. If we are checking 0.0 it means that the counter is not incremented properly.
- `testReconcileMetrics` a reconciliation happen but it's not successful or failed?
- `testReconcileMetricsDeletedTopic` a reconciliation was done due to deletion, why the reconciliations is compared with 0.0 and the test passes?

So I would say that in general, when a reconciliation happen and the corresponding counter is increased it should be "successful" or "failed" so one of them should be increased while in the tests above they are always compared with 0.0 allowing the tests to pass. I think it warns about bugs.

**Comment by stanlyDoge** [comment]
So the issue is this. When running, the TO calls `getKafkaAndReconcile()`, which calls `reconcile()` internally. Depending on the result, the failed/succeeded counter is incremented in the `getKafkaAndReconcile()` method. However, in the test we call "internal" methods (e.g. `reconcile()`) , so we never reach the handler which is hitting the counters.

**Comment by stanlyDoge** [comment]
I think the solution is just to remove the metrics part from the tests which are calling some "internal" methods like `reconcile`.

**Comment by ppatierno** [comment]
I would not agree with that. A reconcile is happening, a KafkaTopic resource is there and it's reconciled successfully or not. The number of the resource is updated, it's a matter of finding in the TO the right places where metrics have to be updated. I see different flows in the TO. Maybe @tombentley can help on this?

**Comment by stanlyDoge** [comment]
Yeah, that is true. I just do not know how to do this technically as the counters are updated in the code above the `reconcile`.

**Comment by scholzj** [comment]
I do not know the details of the TO, but what Standa says makes some sense to me. In UO or CO, the metrics are handled in the `AbstractOperator` and any tests using the `createOrUpdate` method which is below that level (for example calling `KafkaAssemblyOperator.createOrUpdate(...)`) would not have the metrics either. Only the tests calling `AbstractOperator.reconcile()` will capture the metrics. So you need to use the right level for the right test. However, the tests testing the metrics should of course then call the right methods to actually test them and not the wrong methods and expect things to be 0.

**Comment by ppatierno** [comment]
I don't know the TO code so well but as far as I can see there are different paths where "something" can happen during reconcile but ... reconcile method is not called or the flow doesn't get the metrics update. The tests I am referring to do an actual reconcile or we should update the metrics where the flow is going. If you see the tests above, all of them should have a KafkaTopic reconciled successfully or not.
For example, `testReconcileMetrics` calls `reconcileAllTopics` so it's testing a reconciliation right? Why the test check that the number of resource is 1 (so one topic) but then successful or failed against 0 ?? The reconcile can go ok or ko ... so one of them should be 1.

**Comment by tombentley** [comment]
@ppatierno this is an issue about the tests, right. Or is there evidence that the metrics are wrong in production?

**Comment by ppatierno** [comment]
@tombentley I would say that the problem is in production as well and the tests are just confirming that.
For example, I just tried to create the following `KafkaTopic` resource:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "aaa"
    segment.bytes: 1073741824
```

Which has an invalid `retention.ms`. The topic operator logs the error on each reconcile:

```shell
2020-10-12 08:12:14,576] INFO  <opicOperator:1215> [oop-thread-0] Starting periodic  reconciliation
[2020-10-12 08:12:14,592] INFO  <opicOperator:536> [oop-thread-1] 12|periodic kube my-topic|4202: Reconciling topic my-topic, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
Oct 12, 2020 8:12:14 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
io.strimzi.operator.topic.OperatorException
	at io.strimzi.operator.topic.TopicOperator$CreateKafkaTopic.lambda$handle$0(TopicOperator.java:263)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.strimzi.operator.topic.KafkaImpl.lambda$mapFuture$7(KafkaImpl.java:166)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Invalid value aaa for configuration retention.ms: Not a number of type LONG

[2020-10-12 08:13:44,688] INFO  <opicOperator:1215> [oop-thread-0] Starting periodic  reconciliation
[2020-10-12 08:13:44,712] INFO  <opicOperator:536> [oop-thread-1] 13|periodic kube my-topic|4202: Reconciling topic my-topic, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
Oct 12, 2020 8:13:44 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
io.strimzi.operator.topic.OperatorException
	at io.strimzi.operator.topic.TopicOperator$CreateKafkaTopic.lambda$handle$0(TopicOperator.java:263)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.strimzi.operator.topic.KafkaImpl.lambda$mapFuture$7(KafkaImpl.java:166)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Invalid value aaa for configuration retention.ms: Not a number of type LONG
```

but as you can see, the corresponding reconciliation failed total metric is still 0.0

```shell
# HELP strimzi_reconciliations_failed_total Number of reconciliations done by the operator for individual topics which failed
# TYPE strimzi_reconciliations_failed_total counter
strimzi_reconciliations_failed_total{kind="KafkaTopic",} 0.0
```
