### ISSUE TITLE
[Bug] Kafka pods are infinitely rolling when the version of Kafka is not specified

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#3685]
**Describe the bug**

When we deploy Kafka without version on strimzi-0.19.0 and then we want to upgrade it to our master, the Kafka pods will infinitely roll. It can be caused by new listeners or by removing `tls-sidecar`.

The whole scenario you can see in `StrimziUpgradeST.testUpgradeKafkaWithoutVersion` -> that also the way how to reproduce it.

**To Reproduce**
1. Deploy CO and Kafka (without version) from Strimzi version 0.19.0 
2. Upgrade the CO
3. The pods will infinitely roll

**Expected behavior**
After upgrading to master/HEAD the pod should roll only once and the image of Kafka should be `2.6.0`.

**Environment (please complete the following information):**
 - Strimzi version: 0.19.0 and master
 - Installation method: yaml
 - Kubernetes cluster: OCP3.11, OCP4.5 (tested here)

**YAML files and logs**

https://gist.github.com/im-konge/83e5697d9944755f09b491c90b3d3160
https://gist.github.com/im-konge/68f4862452f517536b9d42b1601817f1

Don't know how much related is this:
```
2020-09-10 14:30:58,504 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main]
org.apache.kafka.common.config.ConfigException: Missing required configuration "zookeeper.connect" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:478)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:468)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1270)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1273)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1221)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29)
	at kafka.Kafka$.main(Kafka.scala:68)
	at kafka.Kafka.main(Kafka.scala)
```

**Comment by stanlyDoge** [comment]
Mentioned ST is wrong. It installs 0.19 with master kafka example. Because the listeners have changed, the kafka will not be deployed. After this is fixed, there is an issue with order of operations in KAO. The upgrade phase rolls kafka, which is during the starting consuming data from the ConfigMap. This ConfigMap is upgraded after the upgrade process, however. Putting `kafkaVersionChange` after the `kafkaAncillaryCm` in the future chain fixes the test but I am quite sure it will break other things (it is not waiting for the listeners' readiness for example). Any ideas?
