### ISSUE TITLE
[Bug] unable to load certificates when cruise control is turn on 

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3694]
**Certificate problem when cruise control turned on**

I have a 35 kafka broker 5 zookeeper cluster on strimzi 0.19 that has been running for awhile. 

I did `k edit Kafka kafka-cluster` and turned on cruise control with default settings `{}`.  The brokers roll over and I see the below error. The cluster is setup with oauth authentication with external and internal certs. 

Any ideas? The cluster seems to be fully operational otherwise. 

k -n system-strimzi-dev logs kafka-cluster-cruise-control-6795f646b8-75lmb -c cruise-control
Preparing certificates for internal communication
Adding /etc/tls-sidecar/cluster-ca-certs/ca.crt to truststore /tmp/cruise-control/replication.truststore.p12 with alias ca
Certificate was added to keystore
unable to load certificates

**Comment by scholzj** [comment]
So, just to clarify ... the Cruise Control pod is crash looping after the `unable to load certificates` error? Is the `tls-sidecar` container in the same pod seem to run ok or does it have also some error? Can you check that the secret `kafka-cluster-cruise-control-certs` is not empty and contains the `crt` and `key` files?

**Comment by jrivers96** [comment]
Yes, the cruise control pod is crash looping after the `unable to load certificates`.

It looks like the sidecar fails as well. 

```
k -n system-strimzi-dev logs kafka-cluster-cruise-control-6795f646b8-zrhx6 -c tls-sidecar
Starting Stunnel with configuration:
pid = /usr/local/var/run/stunnel.pid
foreground = yes
debug = notice
sslVersion = TLSv1.2
[zookeeper-2181]
client = yes
CAfile = /tmp/cluster-ca.crt
cert = /etc/tls-sidecar/cc-certs/cruise-control.crt
key = /etc/tls-sidecar/cc-certs/cruise-control.key
accept = 127.0.0.1:2181
connect = kafka-cluster-zookeeper-client:2181
delay = yes
verify = 2


Clients allowed=504187
stunnel 4.56 on x86_64-redhat-linux-gnu platform
Compiled/running with OpenSSL 1.0.1e-fips 11 Feb 2013
Threading:PTHREAD Sockets:POLL,IPv6 SSL:ENGINE,OCSP,FIPS Auth:LIBWRAP
Reading configuration from file /tmp/stunnel.conf
FIPS mode is enabled
Compression not enabled
PRNG seeded successfully
Initializing service [zookeeper-2181]
Insecure file permissions on /etc/tls-sidecar/cc-certs/cruise-control.key
Certificate: /etc/tls-sidecar/cc-certs/cruise-control.crt
Error reading certificate file: /etc/tls-sidecar/cc-certs/cruise-control.crt
error queue: 140DC009: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib
SSL_CTX_use_certificate_chain_file: 906D06C: error:0906D06C:PEM routines:PEM_read_bio:no start line
Service [zookeeper-2181]: Failed to initialize SSL context
str_stats: 12 block(s), 1053 data byte(s), 696 control byte(s)
```
It appears the crt file is empty. 

```k  describe secret kafka-cluster-cruise-control-certs
Name:         kafka-cluster-cruise-control-certs
Namespace:    mdic-strimzi-pro
Labels:       app.kubernetes.io/instance=kafka-cluster
              app.kubernetes.io/managed-by=strimzi-cluster-operator
              app.kubernetes.io/name=cruise-control
              app.kubernetes.io/part-of=strimzi-kafka-cluster
              strimzi.io/cluster=kafka-cluster
              strimzi.io/kind=Kafka
              strimzi.io/name=strimzi
Annotations:  <none>

Type:  Opaque

Data
====
cruise-control.crt:       0 bytes
cruise-control.key:       1704 bytes
cruise-control.p12:       0 bytes
cruise-control.password:  12 bytes
```

**Comment by jrivers96** [comment]
I kept the dev cluster up and running and today at 1:30 EST various kafka broker processes started to disappear.  Look below - `kafka-cluster-kafka-0` doesn't exist. 

The only new feature I've added is cruise control. Cruise control is still in crash loop backoff from last night. The number of brokers are disappearing slowly....  broker-0 went away, broker-4... etc and then they don't come back ( the process is physically not there and it's not in a crashloop backoff state) 

I'm actually wondering if I'm watching this live: https://github.com/strimzi/strimzi-kafka-operator/issues/3537

Below is an example of showing the missing brokers. broker-0 is not there. 
```
k get pods 

           kafka-cluster-cruise-control-6795f646b8-zjbs7                        0/2     CrashLoopBackOff   52         110m
           kafka-cluster-entity-operator-64d6db69d-hkkbw                     3/3     Running            0          8d
           kafka-cluster-kafka-1                                                                             2/2     Running            0          22h
           kafka-cluster-kafka-11                                            2/2     Running            0          22h
           kafka-cluster-kafka-13                                            2/2     Running            0          22h
           kafka-cluster-kafka-14                                            2/2     Running            0          21h
           kafka-cluster-kafka-17                                            2/2     Running            0          21h
           kafka-cluster-kafka-18                                            2/2     Running            0          21h
           kafka-cluster-kafka-19                                            2/2     Running            0          21h
           kafka-cluster-kafka-21                                            2/2     Running            0          21h
           kafka-cluster-kafka-23                                            2/2     Running            0          21h
           kafka-cluster-kafka-25                                            2/2     Running            0          22h
           kafka-cluster-kafka-26                                            2/2     Running            0          21h
           kafka-cluster-kafka-27                                            2/2     Running            0          22h
           kafka-cluster-kafka-29                                            2/2     Running            0          21h
           kafka-cluster-kafka-3                                             2/2     Running            0          21h
           kafka-cluster-kafka-30                                            2/2     Running            0          21h
           kafka-cluster-kafka-31                                            2/2     Running            0          22h
           kafka-cluster-kafka-33                                            2/2     Running            0          21h
           kafka-cluster-kafka-34                                            2/2     Running            0          21h
           kafka-cluster-kafka-5                                             2/2     Running            0          21h
           kafka-cluster-kafka-6                                             2/2     Running            0          22h
           kafka-cluster-kafka-7                                             2/2     Running            0          21h
           kafka-cluster-kafka-9                                             2/2     Running            0          21h
           kafka-cluster-kafka-exporter-5d67c9865d-27pz9                     0/1     CrashLoopBackOff   33         8d
           kafka-cluster-zookeeper-0                                         1/1     Running            0          124m
           kafka-cluster-zookeeper-1                                         1/1     Running            0          8d
           kafka-cluster-zookeeper-2                                         1/1     Running            2          8d
           kafka-cluster-zookeeper-3                                         1/1     Running            0          8d
           kafka-cluster-zookeeper-4                                         1/1     Running            0          126m
           strimzi-cluster-operator-57869945dd-4qqfx                         1/1     Running            0          116m
```

**Comment by scholzj** [comment]
It looks like something went wrong when generating the certificates - the `.crt` and `.p12` files are empty. Could you:
* Check the cluster-ca secrets (but the `<cluster-name>-cluster-ca` and `<cluster-name>-cluster-ca-cert`) whether they exist and have some actual certificate and key? 
* If you have a log from the Cluster Operator from when you enabled Cruise Control it might tell us what went wrong and fix it.

If the Cluster CA secrets look ok, I think you should just delete the `kafka-cluster-cruise-control-certs` secret and wait until it is recreated (and afterwards delete the CC pod). If the CA secrets are also broken, that might possibly be related to the issues from the comment you deleted and the other issues.

**Comment by jrivers96** [comment]
I deleted my comment because I realized there are were changes that I didn't realize were made to the cluster this afternoon. 

A cyber security engineer applied this to all svcs: 
`service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags:`

I looked at the persistent volumes and they were all in a terminating state. I'm not sure why. I didn't get to verify if the cluster ca looked okay. ( but all consumers and producers were operational) 

 I'll stand the cluster back up and turn on cruise control as I did before and see if it works this time.

**Comment by scholzj** [comment]
Hmm, that sounds weird. Normally if you apply a label or annotation to a service it should not touch the pods at all unless it causes the loadbalancer to recreate (which would roll them but not delete them).

**Comment by jrivers96** [comment]
I think at 1:30 EST we had a broker down and 2:30 EST cyber security came by and applied that tag while broker was still down. I then looked at cluster and noticed brokers were missing and persistent volumes were in a terminating state.

**Comment by scholzj** [comment]
I think I probably asked about it already ... but in your storage configuration, you do not use the `deleteClaim: true`, right?

**Comment by jrivers96** [comment]
storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: aws-ssd
        size: 250Gi
        deleteClaim: false

**Comment by jrivers96** [comment]
strange - I wiped out the cluster. 
```
k -n -strimzi-pro delete -f kafka-persistent-pro-deployed.yaml
k -n -strimzi-pro get PersistentVolumeClaim | awk '{ print $1 }' | grep kafka | xargs kubectl -n-strimzi-pro delete PersistentVolumeClaim
k -n -strimzi-pro get PersistentVolume | awk '{ print $1,$6 }' | grep kafka | awk '{ print $1 }'| xargs kubectl -n-strimzi-pro delete PersistentVolume
k -n -strimzi-pro apply -f kafka-persistent-pro-deployed.yaml 	
```

I can't even seem to put the cluster back...

```
k -n mdic-strimzi-pro logs strimzi-cluster-operator-57869945dd-rnv42

2020-09-23 22:55:28 INFO  KafkaRoller:260 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 9 due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: An error while try to create an admin client for pod kafka-cluster-kafka-9, retrying after at least 16000ms
2020-09-23 22:55:28 INFO  KafkaRoller:260 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 8 due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: An error while try to create an admin client for pod kafka-cluster-kafka-8, retrying after at least 16000ms
2020-09-23 22:55:28 INFO  KafkaRoller:260 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 7 due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: An error while try to create an admin client for pod kafka-cluster-kafka-7, retrying after at least 16000ms
2020-09-23 22:55:28 INFO  KafkaRoller:260 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 6 due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: An error while try to create an admin client for pod kafka-cluster-kafka-6, retrying after at least 16000ms
```

Can the CRDs get corrupted somehow or in some sort of state?

**Comment by scholzj** [comment]
Can you share the whole log? Do the pods exist? When the cluster is deleted, it can happen that it is deleted during the reconciliation ... in which case the Cluster Operator might need some time to figure it out and finish the old reconciliation of the _deleted_ cluster and start the new one with the new cluster. This could be the case maybe? I would need the full log to confirm.

> Can the CRDs get corrupted somehow or in some sort of state?

I haven't seen anything like that. But TBH we use the CRDs and know how they work from the user perspective ... but I cannot say I understand the details of the CRD implementation in Kubernetes and all the was how they can go wrong. In any case, deleting the CRD triggers deletion of the CRs which trigger deletion of the cluster. So if there would be something wrong, everything is possible.

**Comment by jrivers96** [comment]
I unfortunately have the cluster operator still in INFO ( I can't change to DEBUG) and the logs aren't that interesting except for:

```
2020-09-24 13:06:56 INFO  KafkaRoller:260 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 0 due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: An error while try to create an admin client for pod kafka-cluster-kafka-0, retrying after at least 64000ms
2020-09-24 13:07:28 ERROR AbstractOperator:301 - Watcher closed with exception in namespace *
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 134425499 (136586984)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:263) [io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-24 13:07:28 INFO  OperatorWatcher:40 - Reconciliation #3(watch) KafkaConnect(/-kafka-connect-cluster): KafkaConnect-kafka-connect-cluster in namespace was ADDED
2020-09-24 13:07:28 INFO  AbstractOperator:173 - Reconciliation #3(watch) KafkaConnect(/-kafka-connect-cluster): KafkaConnect-kafka-connect-cluster should be created or updated
2020-09-24 13:07:28 INFO  AbstractOperator:318 - Reconciliation #3(watch) KafkaConnect(/-kafka-connect-cluster): reconciled
2020-09-24 13:07:34 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace *...
2020-09-24 13:07:34 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormakers' with unstable version 'v1beta1'
2020-09-24 13:07:34 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormaker2s' with unstable version 'v1alpha1'
2020-09-24 13:07:34 INFO  AbstractOperator:173 - Reconciliation #5(timer) KafkaConnect(/-kafka-connect-cluster): KafkaConnect-kafka-connect-cluster should be created or updated
2020-09-24 13:07:34 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkabridges' with unstable version 'v1alpha1'
2020-09-24 13:07:34 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkarebalances' with unstable version 'v1alpha1'
2020-09-24 13:07:34 INFO  AbstractOperator:318 - Reconciliation #5(timer) KafkaConnect(/-kafka-connect-cluster): reconciled
2020-09-24 13:07:44 WARN  AbstractOperator:247 - Reconciliation #4(timer) Kafka(mdic-strimzi-pro/kafka-cluster): Failed to acquire lock lock::mdic-strimzi-pro::Kafka::kafka-cluster within 10000ms.
2020-09-24 13:07:57 WARN  KafkaRoller:349 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Pod kafka-cluster-kafka-34 will be force-rolled
2020-09-24 13:07:57 INFO  KafkaRoller:253 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 34, giving up after 10 attempts/127750ms
java.lang.NullPointerException: null
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartAndAwaitReadiness(KafkaRoller.java:518) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartIfNecessary(KafkaRoller.java:350) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$schedule$5(KafkaRoller.java:238) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-24 13:07:58 WARN  KafkaRoller:349 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Pod kafka-cluster-kafka-33 will be force-rolled
2020-09-24 13:07:58 INFO  KafkaRoller:253 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 33, giving up after 10 attempts/127750ms
java.lang.NullPointerException: null
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartAndAwaitReadiness(KafkaRoller.java:518) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartIfNecessary(KafkaRoller.java:350) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$schedule$5(KafkaRoller.java:238) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-24 13:07:58 WARN  KafkaRoller:349 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Pod kafka-cluster-kafka-32 will be force-rolled
2020-09-24 13:07:58 INFO  KafkaRoller:253 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 32, giving up after 10 attempts/127750ms
java.lang.NullPointerException: null
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartAndAwaitReadiness(KafkaRoller.java:518) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartIfNecessary(KafkaRoller.java:350) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$schedule$5(KafkaRoller.java:238) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-24 13:07:58 WARN  KafkaRoller:349 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Pod kafka-cluster-kafka-31 will be force-rolled
2020-09-24 13:07:58 INFO  KafkaRoller:253 - Reconciliation #1(watch) Kafka(mdic-strimzi-pro/kafka-cluster): Could not roll pod 31, giving up after 10 attempts/127750ms
java.lang.NullPointerException: null
```

I'm seeing some work done on k8s 1.15 related to CRDs. I'm not quite sure what a panic means. 

* Fixed panic when accessing CustomResources of a CRD with x-kubernetes-int-or-string. ([#83790](https://github.com/kubernetes/kubernetes/pull/83790), [@sttts](https://github.com/sttts))

**Comment by jrivers96** [comment]
Here is the cluster operator with the DEBUG logs turned on in the cluster's current state. 

[operator.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5277420/operator.zip)

**Comment by scholzj** [comment]
Yeah, if the secret was empty it was probably some bug. Hard to find the exact cause without the logs. Did deleting the secret helped? Or did it this _resolved_ by the other problem?

**Comment by jrivers96** [comment]
yeah, we resolved this by causing a bigger problem and having to reset the cluster unfortunately.  I'll try to reproduce this at some point before we go into production with it.

**Comment by scholzj** [comment]
@jrivers96 Did you managed to reproduce this again?
