### ISSUE TITLE
kafka cluster crashloopbackoff

### ISSUE THREAD

**Issue by yuyanto** [strimzi/strimzi-kafka-operator#3703]
Tried to startup strimzi using quickstart guide
the kafka operator is started normally, but the kafka cluster keep on restarting 
    Message:               Error while waiting for restarted pod my-cluster-kafka-0 to become ready

when I check the logs on "my-cluster-kafka-0", i got this error
2020-09-24 05:54:11,368 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-24 05:54:11,369 INFO Socket connection established, initiating session, client: /127.0.0.1:33312, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-24 05:54:21,384 WARN Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
2020-09-24 05:54:22,756 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-24 05:54:22,757 INFO Socket connection established, initiating session, client: /127.0.0.1:33372, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-09-24 05:54:23,901 INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler) [SIGTERM handler]
2020-09-24 05:54:23,906 INFO shutting down (kafka.server.KafkaServer) [kafka-shutdown-hook]
2020-09-24 05:54:23,917 ERROR Fatal error during KafkaServer shutdown. (kafka.server.KafkaServer) [kafka-shutdown-hook]
java.lang.IllegalStateException: Kafka server is still starting up, cannot shut down!
	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:602)
	at kafka.server.KafkaServerStartable.shutdown(KafkaServerStartable.scala:54)
	at kafka.Kafka$.$anonfun$main$3(Kafka.scala:80)
	at kafka.utils.Exit$.$anonfun$addShutdownHook$1(Exit.scala:38)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-24 05:54:23,919 ERROR Halting Kafka. (kafka.server.KafkaServerStartable) [kafka-shutdown-hook]

Here is my configuration versions

![image](https://user-images.githubusercontent.com/12112526/94222966-f866b500-ff18-11ea-93d9-e5665ede467e.png)

I have also attached the report generated by 
https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh
[report-24-09-2020_10-13-20.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5273740/report-24-09-2020_10-13-20.zip)

**Comment by stanlyDoge** [comment]
Did you start your cluster and did some changes which caused a rolling update? Using single node ZK cluster might cause issues like this.

**Comment by yuyanto** [comment]
Hi,
I tried as suggested and add the Zookeeper replica to 2, and now it works..

thanks
