### ISSUE TITLE
[Question] WARN WatchConnectionManager:202 - Exec Failure: HTTP 404

### ISSUE THREAD

**Issue by piyush94** [strimzi/strimzi-kafka-operator#3723]
While installing a fresh strimzi kafka operator v0.19.0, i am getting this error:
```
2020-09-30 06:14:03 INFO ClusterOperator:81 - Creating ClusterOperator for namespace kafka
2020-09-30 06:14:03 INFO ClusterOperator:98 - Starting ClusterOperator for namespace kafka
2020-09-30 06:14:03 WARN WatchConnectionManager:202 - Exec Failure: HTTP 404, Status: 404 - 404 page not found
java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-30 06:14:03 INFO AbstractOperator:304 - Watcher closed in namespace kafka
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@22b97f30[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@30a824d5[Wrapped task = io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2@50f6921e]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@46c51831[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:715)
at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714)
at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:318)
at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:50)
at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:221)
at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-30 06:14:03 WARN WatchConnectionManager:202 - Exec Failure: HTTP 404, Status: 404 - 404 page not found
java.net.ProtocolException: Expected HTTP 101 response but was '404 Not Found'
at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-30 06:14:03 INFO AbstractOperator:304 - Watcher closed in namespace kafka
2020-09-30 06:14:03 WARN WatchConnectionManager:202 - Exec Failure: HTTP 404, Status: 404 - 404 page not found
```

Any help would be appreciated.

v0.18.0 works fine.

K8s version: v1.17.3

**Comment by scholzj** [comment]
This message normally means that the Custom Resource Definitions are not installed and the operator cannot watch for them. The best way to check them would be to do `kubectl get crds`. It looks like when you installed it, the CRDs did not get installed, so I think you should to to reinstall them.

**Comment by itga** [comment]
i also came across this issue and fixed it by ensuring all custom resource definitions are created before other type of resources, which @scholzj mentions. In case of me, I place all of `kind: CustomResourceDefinition` resources on the top of the yaml file.

**Comment by scholzj** [comment]
From my experience, some parts of the CRD installation happen asynchronously and having them on the top of your file does not always help. But in any case, if it is just a timing issue, the operator should recover from it once the CRDs are installed. If they problem persists, then they were probably not installed at all.

**Comment by piyush94** [comment]
For some reason, the v0.18.0 chart gets installed successfully, only facing issue with v0.19.0. Also tried to upgrade from 18 to 19 but still the same issue happened. I agree some issue with my cluster is there. Either some cleanup is required of previous operator installations?

**Comment by morozov** [comment]
For the reference, at the bottom of the stacktrace, a specific operator may be mentioned pointing to the missing resource:
```
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:135) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:354) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:759) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:738) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:69) ~[io.fabric8.kubernetes-client-4.6.4.jar:?]
		at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watchInAnyNamespace(AbstractWatchableResourceOperator.java:42) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
		at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResourceOperator.java:51) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
		at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$createRebalanceWatch$0(KafkaRebalanceAssemblyOperator.java:183) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
```
In my case, it was the missing `KafkaRebalance` CRD which was mistakenly not deployed as part of the upgrade from 0.17 to 0.19.

**Comment by piyush94** [comment]
Thanks all, I'll have a look at the missing CRDs.
