### ISSUE TITLE
Every few hours the K8sTopicWatcher is getting closed - is it issue with the environment?

### ISSUE THREAD

**Issue by dineshudayakumar** [strimzi/strimzi-kafka-operator#3771]
We are using only the topic operator in K8s environment. After few hours I see that the K8sTopicWatcher is getting closed and after that we dont get any events only the periodic audit is creating/updating/deleting the topics in Kafka if the K8s KafkaTopic resource was updated.

The actual log was just mentioning that the K8sTopicWatcher is getting closed. We just updated the log to print the exception and this is what we saw. And looking further in the fabric8 library there is already some details related to this

But we are not clear why we get this every few hours - can you provide some details on why we are getting this often? Also how to fix this?

INFO  _ACUSER:root 2020-10-09 03:44:57 K8sTopicWatcher:73 - Closing io.strimzi.operator.topic.K8sTopicWatcher@56329100
ERROR _ACUSER:root 2020-10-09 03:44:57 K8sTopicWatcher:75 - too old resource version: 31633 (213312)
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 31633 (213312)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:254) [topic-operator.jar:0.11.4]
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310) [topic-operator.jar:0.11.4]
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) [topic-operator.jar:0.11.4]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) [topic-operator.jar:0.11.4]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) [topic-operator.jar:0.11.4]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) [topic-operator.jar:0.11.4]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) [topic-operator.jar:0.11.4]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [topic-operator.jar:0.11.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by scholzj** [comment]
Can you share the full log from the topic operator?

**Comment by dineshudayakumar** [comment]
[log.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5353310/log.zip)
Zip contains 2 logs - just 2 instances of the same issue. I dont have the debug logs enabled. Let me know if that required and I can enable and get the debug logs.. thank you

**Comment by scholzj** [comment]
@tombentley @ppatierno @stanlyDoge You are the experts on TO ... any ideas?

**Comment by dineshudayakumar** [comment]
Any inputs on this? Let me know please

**Comment by tombentley** [comment]
Looks to me like there's at least one bug here: The `K8sTopicWatcher` should automatically reconnect when it gets closed with an exception, and that does not seem to be working. Its would also be good to understand the behaviour of fabric8 here, since it is apparentl a mismatch of the resource version that's the problem, rather than the apiserver closing the websocket. That suggests that someone some state has gotten out of sync. @stanlyDoge any chance you could look into this?

**Comment by stanlyDoge** [comment]
Sure, I can take a look.
