### ISSUE TITLE
Kafka Connect crashing because of the default installation steps

### ISSUE THREAD

**Issue by Miyurz** [strimzi/strimzi-kafka-operator#3780]
**Suggestion / Problem**
While installing Kafka connect following the steps https://strimzi.io/docs/operators/0.19.0/deploying.html 
I observed that the connect pod started crashing with the below error. It was quite obvious from the error that the connect install required 3 kafka brokers which in turn meant that I had to reinstall the Kafka cluster with 3 brokers i.e., 
`**kubectl apply -f examples/kafka/kafka-persistent.yaml** `

The documentation doesn't talk about that so can we actually add this as a note to the doc or make it a bit more verbose?
Another way could be to deploy connect with  `**examples/connect/kafka-connect-single-node-kafka.yaml**` since it needs a replication factor of 1?
```
 ERROR [Worker clientId=connect-1, groupId=connect-cluster] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-1-1]
org.apache.kafka.connect.errors.ConnectException: Error while attempting to create/find topic(s) 'connect-cluster-offsets'
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:262)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore$1.run(KafkaOffsetBackingStore.java:99)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:128)
	at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:109)
	at org.apache.kafka.connect.runtime.Worker.start(Worker.java:186)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:123)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:284)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:229)
	... 11 more
Caused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```

**Documentation Link**
https://strimzi.io/docs/operators/0.19.0/deploying.html#deploying-kafka-connect-str

**Comment by scholzj** [comment]
Sorry, I'm a bit confused. Does the docs tell you to install single node Kafka? I cannot find it there.

**Comment by Miyurz** [comment]
@scholzj The docs do not talk about single node Kafka. By the time, one reaches to Kafka connect install section and runs the default install of kafka connect(as mentioned in docs) which in fact requires a Kafka with 3 brokers, connect pods start failing. If we could just let users know this beforehand, it would help so that they don't have to backtrack after demystifying the error logs.

**Comment by scholzj** [comment]
Ok, thanks for the clarification.

**Comment by neemiasjnr** [comment]
Here you can find more information about how Kafka Connect works: https://docs.confluent.io/current/connect/references/allconfigs.html#distributed-worker-configuration. You should set the replication factor to 1 on each topic used by kafka connect, in case you want to keep 1 Kafka broker. Strimzi by default runs Kafka Connect on distributed mode which is the recommended one, and I think most of the users would use at least 3 brokers and if possible I would recommend you to do the same
