### ISSUE TITLE
Vert.x event loop blocked due to no connection with Zookeeper

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#383]
Let's consider the following scenario ...

Deploy the CC and then provide a cluster ConfigMap for deploying a Kafka cluster. The ZK StatefulSet is deployed with the Kafka StatefulSet as well but just after that you delete the ZK StatefulSet. The CC continues with deploying the TC which fails with current exception : 

```
[2018-04-16 13:19:14,367] INFO  <ZooKeeper   :438> [oop-thread-0] Initiating client connection, connectString=my-cluster-zookeeper:2181 sessionTimeout=20000 watcher=io.strimzi.controller.topic.zk.ZkImpl$$Lambda$11/530826996@1b395d0c
--
  | [2018-04-16 13:19:15,025] INFO  <ClientCnxn  :1032> [.local:2181)] Opening socket connection to server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.21.171:2181. Will not attempt to authenticate using SASL (unknown error)
  | Apr 16, 2018 1:19:17 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2890 ms, time limit is 2000
  | Apr 16, 2018 1:19:18 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3890 ms, time limit is 2000
  | Apr 16, 2018 1:19:19 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4891 ms, time limit is 2000
  | Apr 16, 2018 1:19:20 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5891 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at sun.misc.Unsafe.park(Native Method)
  | at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
  | at io.strimzi.controller.topic.zk.ZkImpl.<init>(ZkImpl.java:101)
  | at io.strimzi.controller.topic.zk.Zk.create(Zk.java:22)
  | at io.strimzi.controller.topic.Session.start(Session.java:121)
  | at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
  | at io.vertx.core.impl.DeploymentManager$$Lambda$9/1485955886.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$10/334203599.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | Apr 16, 2018 1:19:21 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6891 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at sun.misc.Unsafe.park(Native Method)
  | at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
  | at io.strimzi.controller.topic.zk.ZkImpl.<init>(ZkImpl.java:101)
  | at io.strimzi.controller.topic.zk.Zk.create(Zk.java:22)
  | at io.strimzi.controller.topic.Session.start(Session.java:121)
  | at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
  | at io.vertx.core.impl.DeploymentManager$$Lambda$9/1485955886.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$10/334203599.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | Apr 16, 2018 1:19:22 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 7891 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at sun.misc.Unsafe.park(Native Method)
  | at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
  | at io.strimzi.controller.topic.zk.ZkImpl.<init>(ZkImpl.java:101)
  | at io.strimzi.controller.topic.zk.Zk.create(Zk.java:22)
  | at io.strimzi.controller.topic.Session.start(Session.java:121)
  | at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
  | at io.vertx.core.impl.DeploymentManager$$Lambda$9/1485955886.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$10/334203599.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | Apr 16, 2018 1:19:23 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 8890 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked
  | at sun.misc.Unsafe.park(Native Method)
  | at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  | at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
  | at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
  | at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
  | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
  | at io.strimzi.controller.topic.zk.ZkImpl.<init>(ZkImpl.java:101)
  | at io.strimzi.controller.topic.zk.Zk.create(Zk.java:22)
  | at io.strimzi.controller.topic.Session.start(Session.java:121)
  | at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
  | at io.vertx.core.impl.DeploymentManager$$Lambda$9/1485955886.handle(Unknown Source)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.vertx.core.impl.ContextImpl$$Lambda$10/334203599.run(Unknown Source)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | Apr 16, 2018 1:19:24 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 9890 ms, time limit is 2000
  | io.vertx.core.VertxException: Thread blocked


```
the Vert.x event loop is blocked due to a failing connection to ZK.

**Comment by ppatierno** [comment]
In some cases it could not happen (Vert.x event loop blocked) but the following retries which should be something right ...

```
[2018-04-16 13:31:55,397] INFO  <ClientCnxn  :1032> [.local:2181)] Opening socket connection to server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.107.59:2181. Will not attempt to authenticate using SASL (unknown error)
--
  | [2018-04-16 13:32:13,865] WARN  <ClientCnxn  :1108> [.local:2181)] Client session timed out, have not heard from server in 20010ms for sessionid 0x162cea6eb2d0003
  | [2018-04-16 13:32:13,865] INFO  <ClientCnxn  :1156> [.local:2181)] Client session timed out, have not heard from server in 20010ms for sessionid 0x162cea6eb2d0003, closing socket connection and attempting reconnect
  | [2018-04-16 13:32:13,972] ERROR <opicsWatcher:67> [oop-thread-7] Error on znode /brokers/topics children
  | org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for for path: /brokers/topics
  | at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
  | at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
  | at io.strimzi.controller.topic.zk.ZkImpl.mapResult(ZkImpl.java:135)
  | at io.strimzi.controller.topic.zk.ZkImpl.lambda$children$10(ZkImpl.java:343)
  | at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:601)
  | at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
  | [2018-04-16 13:32:15,873] INFO  <ClientCnxn  :1032> [.local:2181)] Opening socket connection to server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.107.59:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-04-16 13:32:35,893] WARN  <ClientCnxn  :1108> [.local:2181)] Client session timed out, have not heard from server in 21926ms for sessionid 0x162cea6eb2d0003
  | [2018-04-16 13:32:35,894] INFO  <ClientCnxn  :1156> [.local:2181)] Client session timed out, have not heard from server in 21926ms for sessionid 0x162cea6eb2d0003, closing socket connection and attempting reconnect
  | [2018-04-16 13:32:37,811] INFO  <ClientCnxn  :1032> [.local:2181)] Opening socket connection to server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.107.59:2181. Will not attempt to authenticate using SASL (unknown error)
  | [2018-04-16 13:32:57,828] WARN  <ClientCnxn  :1108> [.local:2181)] Client session timed out, have not heard from server in 21834ms for sessionid 0x162cea6eb2d0003
  | [2018-04-16 13:32:57,828] INFO  <ClientCnxn  :1156> [.local:2181)] Client session timed out, have not heard from server in 21834ms for sessionid 0x162cea6eb2d0003, closing socket connection and attempting reconnect
  | [2018-04-16 13:32:59,170] INFO  <ClientCnxn  :1032> [.local:2181)] Opening socket connection to server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.107.59:2181. Will not attempt to authenticate using SASL (unknown error)
```

**Comment by tombentley** [comment]
I would expect this to eventually recover, because the CC periodic reconciliation would kick-in and the ZK cluster would get created, and the TC should recover once it can connect to the ZK ensemble.

Obviously It's not desirable to block the even loop while this happens, but as currently set up (single verticle deployed, happens when starting that verticle) blocking the event look shouldn't be *harmful*.

The `ZooKeeper`-level watch used in `ZkImp`l assumes the `ZooKeeper` instance itself handles reconnnection attempts (see http://zookeeper.apache.org/doc/r3.4.11/zookeeperProgrammers.html#ch_zkSessions), so it's not clear to me that we should do anything special either to try to reconnect, or to exit the process and let k8s restart the pod.

**Comment by ppatierno** [comment]
Well ....

I think that we should avoid to fill the log with the blocked thread messages from Vert.x.
It seems to recover when the ZK instance is re-created on CC reconcile but it still doesn't work ...

```
[2018-04-16 14:25:28,381] INFO  <ClientCnxn  :1032> [.local:2181)] Opening socket connection to server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.106.46:2181. Will not attempt to authenticate using SASL (unknown error)
--
  | [2018-04-16 14:25:28,382] INFO  <ClientCnxn  :876> [.local:2181)] Socket connection established to my-cluster-zookeeper.myproject.svc.cluster.local/172.30.106.46:2181, initiating session
  | [2018-04-16 14:25:28,414] INFO  <ClientCnxn  :1299> [.local:2181)] Session establishment complete on server my-cluster-zookeeper.myproject.svc.cluster.local/172.30.106.46:2181, sessionid = 0x162ced85ff20000, negotiated timeout = 20000
  | [2018-04-16 14:25:28,432] INFO  <Session     :165> [oop-thread-0] Starting initial reconciliation
  | [2018-04-16 14:25:28,454] INFO  <Session     :161> [oop-thread-0] Started
  | [2018-04-16 14:25:28,460] INFO  <Main        :42> [oop-thread-3] Session deployed
  | [2018-04-16 14:25:28,461] ERROR <opicsWatcher:110> [oop-thread-4] Error on znode /brokers/topics children
  | org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for for path: /brokers/topics
  | at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
  | at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
  | at io.strimzi.controller.topic.zk.ZkImpl.mapResult(ZkImpl.java:135)
  | at io.strimzi.controller.topic.zk.ZkImpl.lambda$children$10(ZkImpl.java:343)
  | at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:601)
  | at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505)
```

as we see from #339 the ZK session/reconnection doesn't work properly or we are handling that in a bad way.

**Comment by tombentley** [comment]
This code was refactored a while back and the blocking of the event loop should no longer be possible.
