### ISSUE TITLE
Kafka not starting in OKD 3.11

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#3836]
Kafka not starting in OKD 3.11

- Secrets

```
NAME                                       TYPE                                  DATA      AGE
builder-dockercfg-r64nc                    kubernetes.io/dockercfg               1         2h
builder-token-7gnvs                        kubernetes.io/service-account-token   4         2h
builder-token-nwdpx                        kubernetes.io/service-account-token   4         2h
default-dockercfg-cxd8w                    kubernetes.io/dockercfg               1         2h
default-token-58dm6                        kubernetes.io/service-account-token   4         2h
default-token-x29pc                        kubernetes.io/service-account-token   4         2h
deployer-dockercfg-dcksh                   kubernetes.io/dockercfg               1         2h
deployer-token-b75h7                       kubernetes.io/service-account-token   4         2h
deployer-token-mwfcj                       kubernetes.io/service-account-token   4         2h
kafka-restic-dockercfg-s8zfx               kubernetes.io/dockercfg               1         1h
kafka-restic-token-kw5dc                   kubernetes.io/service-account-token   4         1h
kafka-restic-token-plkw7                   kubernetes.io/service-account-token   4         1h
prod-cluster-clients-ca                    Opaque                                1         2h
prod-cluster-clients-ca-cert               Opaque                                1         2h
prod-cluster-cluster-ca                    Opaque                                1         2h
prod-cluster-cluster-ca-cert               Opaque                                1         2h
prod-cluster-cluster-operator-certs        Opaque                                4         6m
prod-cluster-listener-cert                 Opaque                                3         2h
prod-cluster-zookeeper-dockercfg-kh6gn     kubernetes.io/dockercfg               1         6m
prod-cluster-zookeeper-nodes               Opaque                                12        6m
prod-cluster-zookeeper-token-6glst         kubernetes.io/service-account-token   4         6m
prod-cluster-zookeeper-token-xz6gd         kubernetes.io/service-account-token   4         6m
strimzi-cluster-operator-dockercfg-dnkrs   kubernetes.io/dockercfg               1         1h
strimzi-cluster-operator-token-hrwgv       kubernetes.io/service-account-token   4         1h
strimzi-cluster-operator-token-q6b5b       kubernetes.io/service-account-token   4         1h
```

- PODS

```
[root@prod-cluster ocp-setup-files]# oc get po
NAME                                        READY     STATUS    RESTARTS   AGE
restic-kafka-0                              1/1       Running   0          1h
strimzi-cluster-operator-597c48675d-57tsg   1/1       Running   0          34m
```

- Kafka YAML

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: prod-cluster
spec:
  clusterCa:
    generateCertificateAuthority: false
  clientsCa:
    generateCertificateAuthority: false
  kafka:
    version: 2.5.0
    replicas: 3
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsGroup: 0
          runAsUser: 0
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
      external:
        type: route
        authentication:
          type: scram-sha-512
        configuration:
          brokerCertChainAndKey:
            secretName: prod-cluster-listener-cert
            certificate: listener.pem
            key: listener.key
    authorization:
      type: simple
      superUsers:
        - CN=admin-in
        - admin-ex
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: kubenfs-storage
        size: 500Mi
        deleteClaim: false
  zookeeper:
    replicas: 3
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsGroup: 0
          runAsUser: 0
    storage:
      type: persistent-claim
      class: kubenfs-storage
      size: 500Mi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

- Operator logs 

```
.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-19 02:10:54 WARN  AbstractOperator:330 - Reconciliation #13(watch) Kafka(streaming/prod-cluster): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource prod-cluster-zookeeper-0 in namespace streaming to be ready
        at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:121) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-19 02:12:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:14:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:16:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:17:35 INFO  OperatorWatcher:40 - Reconciliation #17(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster in namespace streaming was ADDED
2020-10-19 02:17:35 INFO  AbstractOperator:173 - Reconciliation #17(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster should be created or updated
2020-10-19 02:17:35 INFO  OperatorWatcher:40 - Reconciliation #18(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster in namespace streaming was MODIFIED
2020-10-19 02:17:45 WARN  AbstractOperator:247 - Reconciliation #18(watch) Kafka(streaming/prod-cluster): Failed to acquire lock lock::streaming::Kafka::prod-cluster within 10000ms.
2020-10-19 02:18:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:18:18 WARN  AbstractOperator:247 - Reconciliation #19(timer) Kafka(streaming/prod-cluster): Failed to acquire lock lock::streaming::Kafka::prod-cluster within 10000ms.
2020-10-19 02:19:09 INFO  OperatorWatcher:40 - Reconciliation #20(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster in namespace streaming was DELETED
2020-10-19 02:19:19 WARN  AbstractOperator:247 - Reconciliation #20(watch) Kafka(streaming/prod-cluster): Failed to acquire lock lock::streaming::Kafka::prod-cluster within 10000ms.
2020-10-19 02:20:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:22:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:22:36 ERROR Util:120 - Exceeded timeout of 300000ms while waiting for StatefulSet resource prod-cluster-zookeeper in namespace streaming to be ready
2020-10-19 02:22:36 ERROR KafkaAssemblyOperator:498 - Reconciliation #17(watch) Kafka(streaming/prod-cluster): Current Kafka resource not found
2020-10-19 02:22:36 ERROR KafkaAssemblyOperator:244 - Failed to set status for prod-cluster
2020-10-19 02:22:36 ERROR AbstractOperator:175 - Reconciliation #17(watch) Kafka(streaming/prod-cluster): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource prod-cluster-zookeeper in namespace streaming to be ready
        at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:121) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-19 02:22:36 WARN  AbstractOperator:330 - Reconciliation #17(watch) Kafka(streaming/prod-cluster): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource prod-cluster-zookeeper in namespace streaming to be ready
        at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:121) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-19 02:24:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:24:11 INFO  OperatorWatcher:40 - Reconciliation #21(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster in namespace streaming was ADDED
2020-10-19 02:24:11 INFO  AbstractOperator:173 - Reconciliation #21(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster should be created or updated
2020-10-19 02:24:11 INFO  OperatorWatcher:40 - Reconciliation #22(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster in namespace streaming was MODIFIED
2020-10-19 02:24:21 WARN  AbstractOperator:247 - Reconciliation #22(watch) Kafka(streaming/prod-cluster): Failed to acquire lock lock::streaming::Kafka::prod-cluster within 10000ms.
2020-10-19 02:26:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:26:18 WARN  AbstractOperator:247 - Reconciliation #23(timer) Kafka(streaming/prod-cluster): Failed to acquire lock lock::streaming::Kafka::prod-cluster within 10000ms.
2020-10-19 02:28:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace streaming...
2020-10-19 02:28:18 WARN  AbstractOperator:247 - Reconciliation #24(timer) Kafka(streaming/prod-cluster): Failed to acquire lock lock::streaming::Kafka::prod-cluster within 10000ms.
2020-10-19 02:29:12 ERROR Util:120 - Exceeded timeout of 300000ms while waiting for StatefulSet resource prod-cluster-zookeeper in namespace streaming to be ready
2020-10-19 02:29:12 INFO  OperatorWatcher:40 - Reconciliation #25(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster in namespace streaming was MODIFIED
2020-10-19 02:29:12 ERROR AbstractOperator:175 - Reconciliation #21(watch) Kafka(streaming/prod-cluster): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource prod-cluster-zookeeper in namespace streaming to be ready
        at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:121) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-19 02:29:12 WARN  AbstractOperator:330 - Reconciliation #21(watch) Kafka(streaming/prod-cluster): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource prod-cluster-zookeeper in namespace streaming to be ready
        at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:121) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-19 02:29:12 INFO  AbstractOperator:173 - Reconciliation #25(watch) Kafka(streaming/prod-cluster): Kafka prod-cluster should be created or updated
```

**Comment by scholzj** [comment]
I think you would need to share the ore than just this. In particular
* The logs form the pods not becoming ready
* If the pods were not created, then the events from the StatefulSet which is responsible for creating them.

Aside from that, as mentioned before ... do not use NFS to run Kafka. Also, on OpenShift / OKD the best is to run Kafka under the SCC Restricted policy and not run it as root.

**Comment by cloudcafetech** [comment]
This is test environment, so far same yaml I am able to run in Vanila Kubernetes .... 

> Also, on OpenShift / OKD the best is to run Kafka under the SCC Restricted policy and not run it as root. 

Please help me to set right SCC Restricted policy ...

**Comment by scholzj** [comment]
> 2020-10-19 08:11:35 WARN AbstractOperator:247 - Reconciliation #28(timer) Kafka(test/prod-cluster): Failed to acquire lock lock::test::Kafka::prod-cluster within 10000ms.

Please see https://strimzi.io/docs/operators/latest/full/using.html#what_do_the_failed_to_acquire_lock_warnings_in_the_log_mean

> Please help me to set right SCC Restricted policy ...

You will have to do this with your OKD administrator. This is basically OpenShift / OKD setting. I do not really know how it is configured. In any case, I'm not sure how this is related without any other logs.
