### ISSUE TITLE
[Bug] Failed to acquire lock within 10000ms.

### ISSUE THREAD

**Issue by adacaccia** [strimzi/strimzi-kafka-operator#3844]
**Describe the bug**
Unable to install Kafka because Zookeeper keeps failing with "ZK down"

**To Reproduce**
1. kubectl apply -f kafka-persistent-0.20.0.yaml -n <namespace>
2. zookepper cluster spins up
3. See error: "Failed to acquire lock within 10000ms" in strimzi-cluster-operator log, then also "io.strimzi.operator.cluster.operator.resource.ZookeeperScalingException: Failed to connect to Zookeeper sk-zookeeper-0.sk-zookeeper-nodes.ingestion.svc:2181,sk-zookeeper-1.sk-zookeeper-nodes.ingestion.svc:2181,sk-zookeeper-2.sk-zookeeper-nodes.ingestion.svc:2181. Connection was not ready in 300000 ms."

4. See error in each zookeeper node's log:
2020-10-19 20:43:42,021 INFO Authenticated Id 'CN=cluster-operator,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-1]
2020-10-19 20:43:42,022 WARN Closing connection to /10.42.5.1:44722 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-7-1]
java.io.IOException: ZK down

**Expected behavior**
zookeeper cluster up and running + kafka cluster up and running.

**Environment (please complete the following information):**
 - Strimzi version: 0.20-rc2
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.17.12
 - Infrastructure: OCI VM's with RKE installed and managed by Rancher v2.4.4

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily 
**(but how exactly?)** 
attached to this issue.
The usage of this script is:
`./report.sh [--namespace=<string>] [--cluster=<string>]`*

**Additional context**

**Comment by scholzj** [comment]
Can you share the full log from the Zookeeper pods? I do not think the log ou pasted here are really the cause why the Zookeepers are not running.

If I should guess it could be similar to #3155 / #3099 ... but I cannot say that for sure without the complete logs of course.

> See error: "Failed to acquire lock within 10000ms" in strimzi-cluster-operator log

Just FYI, here is the explanation for this: https://strimzi.io/docs/operators/latest/full/using.html#what_do_the_failed_to_acquire_lock_warnings_in_the_log_mean

**Comment by dbonino** [comment]
@scholzj 

sorry to jump directly in the conversation without introdcing myself. I am working with Adalberto on this issue. Please find attached the report generated by the suggested report script.

Let us know if you spot something wrong in our set-up,

Best regards
Dario

[report-19-10-2020_23-10-32.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5407143/report-19-10-2020_23-10-32.zip)

**Comment by scholzj** [comment]
Thanks for the logs. But to be honest, I don't know what the problem is here. You already have disabled the hostname verification, so it is not what I expected. But it looks like for whatever reason the Zookeeper nodes cannot connect with each other. 

The `java.io.IOException: ZK down` exceptions are IMHO just telling the Cluster Operator that the cluster did not formed and cannot be used.  But for the follower / leader connections, they seem to have some communication issues:

```
2020-10-19 21:09:53,398 WARN Exception when following the leader (org.apache.zookeeper.server.quorum.Learner) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:958)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:84)
	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:118)
	at org.apache.zookeeper.server.quorum.Learner.readPacket(Learner.java:158)
	at org.apache.zookeeper.server.quorum.Learner.registerWithLeader(Learner.java:336)
	at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:78)
	at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1253)
```

**Comment by scholzj** [comment]
One thing I noticed through ... your Kafka CR seems to be created yesterday:
```
creationTimestamp: "2020-10-19T21:03:17Z"
```

But lot of the Zookeeper PVCs are already older:
```
creationTimestamp: "2020-10-15T14:28:57Z"
```

Sometimes, old data from other cluster with different configuration etc. can cause problems. So you should make sure the old PVs / PVCs are gone before deploying a new cluster. 

The PVCs also suggest that you are using `storageClassName: host-path` ... I'm not completely sure what exactly does this mean in your case. If this has anything to do with the hostPath volume types, you should make sure that:
* Each pod has its own volume/path
* When the pod is rescheduled to another node, it needs to start either with no data / empty volume or with its own data. Not with data from other pods.

These things could cause mess as well.

**Comment by adacaccia** [comment]
Hello @scholzj ,
thanks for your help.
Actually host-path is a custom storageClass I've made for having PV deployed on an iSCSI multi-read/write volume provided by OCI and formatted with the cluster aware OCFS2 filesystem; every node is mounting it, so K8s is free to move PODs around at will.
So I don't think a zookeper-0 pod has taken over the PV for zookeeper-1, as namespace/POD name are attached to the PV.
But we've just discovered the previously fabulous performance of that shared volume, has dropped at ridiculous levels today (60kB/s writing!), so I'm currently after Oracle Support on that...

**Comment by adacaccia** [comment]
Oracle Support discovered a memory spike which in turn led the node to get a slower network connection to the iSCSI storage, which made EVERY operation from ANY pod on than node slow as hell...
So, nothing to do with Strimzi!
Keep up the good work!
Best regards,
Adalberto
