### ISSUE TITLE
[Question]  HELP! Why does the kafka broker pod stop itself after a period of time

### ISSUE THREAD

**Issue by AllenZMC** [strimzi/strimzi-kafka-operator#3920]
I followed the quickstart in the document to do a small example, the following problems occurred
```
k get pod -n my-kafka-project -w
NAME                                         READY   STATUS    RESTARTS   AGE
my-cluster-entity-operator-99c546c94-vn5rw   3/3     Running   0          153m
my-cluster-kafka-0                           1/1     Running   0          42s
my-cluster-zookeeper-0                       1/1     Running   0          155m

my-cluster-kafka-0                           1/1     Terminating   0          115s
my-cluster-kafka-0                           1/1     Terminating   0          116s
my-cluster-kafka-0                           0/1     Terminating   0          2m
my-cluster-kafka-0                           0/1     Terminating   0          2m8s
my-cluster-kafka-0                           0/1     Terminating   0          2m8s
my-cluster-kafka-0                           0/1     Pending       0          0s
my-cluster-kafka-0                           0/1     Pending       0          0s
my-cluster-kafka-0                           0/1     Init:0/1      0          0s
my-cluster-kafka-0                           0/1     Init:0/1      0          1s
my-cluster-kafka-0                           0/1     Init:0/1      0          2s
my-cluster-kafka-0                           0/1     PodInitializing   0          7s
my-cluster-kafka-0                           0/1     Running           0          8s
my-cluster-kafka-0                           1/1     Running           0          30s
my-cluster-kafka-0                           1/1     Terminating       0          107s
my-cluster-kafka-0                           1/1     Terminating       0          108s
```

```
k logs -f strimzi-cluster-operator-595b45f59b-mss89 -n kafka
2020-11-05 06:13:10 INFO  PodOperator:65 - Rolling update of my-kafka-project/my-cluster-kafka: Rolling pod my-cluster-kafka-0
2020-11-05 06:13:50 INFO  AbstractOperator:455 - Reconciliation #78(timer) Kafka(my-kafka-project/my-cluster): reconciled
2020-11-05 06:15:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace my-kafka-project...
2020-11-05 06:15:08 INFO  AbstractOperator:217 - Reconciliation #79(timer) Kafka(my-kafka-project/my-cluster): Kafka my-cluster will be checked for creation or modification
2020-11-05 06:15:10 INFO  PodOperator:65 - Rolling update of my-kafka-project/my-cluster-kafka: Rolling pod my-cluster-kafka-0
2020-11-05 06:15:44 INFO  AbstractOperator:455 - Reconciliation #79(timer) Kafka(my-kafka-project/my-cluster): reconciled
2020-11-05 06:17:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace my-kafka-project...
2020-11-05 06:17:08 INFO  AbstractOperator:217 - Reconciliation #80(timer) Kafka(my-kafka-project/my-cluster): Kafka my-cluster will be checked for creation or modification
2020-11-05 06:17:10 INFO  PodOperator:65 - Rolling update of my-kafka-project/my-cluster-kafka: Rolling pod my-cluster-kafka-0
2020-11-05 06:17:46 INFO  AbstractOperator:455 - Reconciliation #80(timer) Kafka(my-kafka-project/my-cluster): reconciled
2020-11-05 06:19:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace my-kafka-project...
2020-11-05 06:19:08 INFO  AbstractOperator:217 - Reconciliation #81(timer) Kafka(my-kafka-project/my-cluster): Kafka my-cluster will be checked for creation or modification
2020-11-05 06:19:10 INFO  PodOperator:65 - Rolling update of my-kafka-project/my-cluster-kafka: Rolling pod my-cluster-kafka-0
2020-11-05 06:19:54 INFO  AbstractOperator:455 - Reconciliation #81(timer) Kafka(my-kafka-project/my-cluster): reconciled
2020-11-05 06:21:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace my-kafka-project...
2020-11-05 06:21:08 INFO  AbstractOperator:217 - Reconciliation #82(timer) Kafka(my-kafka-project/my-cluster): Kafka my-cluster will be checked for creation or modification
2020-11-05 06:21:10 INFO  PodOperator:65 - Rolling update of my-kafka-project/my-cluster-kafka: Rolling pod my-cluster-kafka-0
2020-11-05 06:21:41 INFO  AbstractOperator:455 - Reconciliation #82(timer) Kafka(my-kafka-project/my-cluster): reconciled
2020-11-05 06:23:08 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace my-kafka-project...
2020-11-05 06:23:08 INFO  AbstractOperator:217 - Reconciliation #83(timer) Kafka(my-kafka-project/my-cluster): Kafka my-cluster will be checked for creation or modification
2020-11-05 06:23:10 INFO  PodOperator:65 - Rolling update of my-kafka-project/my-cluster-kafka: Rolling pod my-cluster-kafka-0
```

**Comment by scholzj** [comment]
That looks like the operator is rolling the pod every reconciliation. If you can provide DEBUG logs from the operator, that should show why. You can change the log level in the strimzi-cluster-operator config map.

**Comment by AllenZMC** [comment]
```
listener='EXTERNAL-9094', securityProtocol=0)], rack=null)) to broker my-cluster-kafka-0.my-cluster-kafka-brokers.my-kafka-project.svc:9091 (id: 0 rack: null). Reconnecting to broker. (kafka.controller.RequestSendThread) [Controller-1-to-broker-0-send-thread]
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1367)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at kafka.utils.ShutdownableThread.pause(ShutdownableThread.scala:82)
	at kafka.controller.RequestSendThread.backoff$1(ControllerChannelManager.scala:231)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:245)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
2020-11-05 09:31:47,624 TRACE [RequestSendThread controllerId=1] shutdownInitiated latch count reached zero. Shutdown called. (kafka.controller.RequestSendThread) [Controller-1-to-broker-0-send-thread]
```

**Comment by scholzj** [comment]
Sorry, but copying few lines from some log - where it is not even clear what log it is - does not help. You would need to share the full logs.

**Comment by AllenZMC** [comment]
2020-11-05 10:09:27 DEBUG KafkaSetOperator:168 - StatefulSet my-cluster-kafka in namespace my-kafka-project has been patched
2020-11-05 10:09:27 DEBUG KafkaAssemblyOperator:927 - Kafka.spec.kafka.version unchanged
2020-11-05 10:09:28 DEBUG KafkaRoller:203 - Reconciliation #0(watch) Kafka(my-kafka-project/my-cluster): Initial order for rolling restart [0, 1]
2020-11-05 10:09:28 DEBUG KafkaRoller:270 - Reconciliation #0(watch) Kafka(my-kafka-project/my-cluster): Considering restart of pod 0 after delay of 0 MILLISECONDS
2020-11-05 10:09:28 DEBUG KafkaAssemblyOperator:3111 - Rolling update of my-kafka-project/my-cluster-kafka: pod my-cluster-kafka-0 has strimzi.io/generation=1; sts has strimzi.io/generation=1
2020-11-05 10:09:28 DEBUG KafkaAssemblyOperator:3213 - Rolling update of my-kafka-project/my-cluster-kafka: pod my-cluster-kafka-0 has strimzi.io/custom-listener-cert-thumbprints=; sts has strimzi.io/custom-listener-cert-thumbprints=

**Comment by scholzj** [comment]
I'm sorry, but I'm afraid you really need to share the whole log to see why it is rolling.

**Comment by AllenZMC** [comment]
I followed the steps in the document(https://strimzi.io/docs/operators/latest/quickstart.html) step by step, but this problem occurred and there was no idea.

**Comment by AllenZMC** [comment]
By the way, how to get the whole log?

**Comment by AllenZMC** [comment]
`2020-11-06 01:52:00,093 INFO [Controller id=0] Registering handlers (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,099 INFO [Controller id=0] Deleting log dir event notifications (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,104 INFO [Controller id=0] Deleting isr change notifications (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,107 INFO [Controller id=0] Initializing controller context (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,116 INFO [Controller id=0] Initialized broker epochs cache: Map(0 -> 4294999970) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,123 DEBUG [Controller id=0] Register BrokerModifications handler for Set(0) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,130 DEBUG [Channel manager on controller 0]: Controller 0 trying to connect to broker 0 (kafka.controller.ControllerChannelManager) [controller-event-thread]
2020-11-06 01:52:00,263 INFO [Controller id=0] Currently active brokers in the cluster: Set(0) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,264 INFO [RequestSendThread controllerId=0] Starting (kafka.controller.RequestSendThread) [Controller-0-to-broker-0-send-thread]
2020-11-06 01:52:00,264 INFO [Controller id=0] Currently shutting brokers in the cluster: Set() (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,265 INFO [Controller id=0] Current list of topics in the cluster: Set() (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,265 INFO [Controller id=0] Fetching topic deletions in progress (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,271 INFO [Controller id=0] List of topics to be deleted:  (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,272 INFO [Controller id=0] List of topics ineligible for deletion:  (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,272 INFO [Controller id=0] Initializing topic deletion manager (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,273 INFO [Topic Deletion Manager 0] Initializing manager with initial deletions: Set(), initial ineligible deletions: Set() (kafka.controller.TopicDeletionManager) [controller-event-thread]
2020-11-06 01:52:00,273 INFO [Controller id=0] Sending update metadata request (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,276 INFO [Controller id=0 epoch=1227] Sending UpdateMetadata request to brokers Set(0) for 0 partitions (state.change.logger) [controller-event-thread]
2020-11-06 01:52:00,283 INFO [ReplicaStateMachine controllerId=0] Initializing replica state (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-11-06 01:52:00,284 INFO [ReplicaStateMachine controllerId=0] Triggering online replica state changes (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-11-06 01:52:00,291 INFO [ReplicaStateMachine controllerId=0] Triggering offline replica state changes (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-11-06 01:52:00,292 DEBUG [ReplicaStateMachine controllerId=0] Started replica state machine with initial state -> Map() (kafka.controller.ZkReplicaStateMachine) [controller-event-thread]
2020-11-06 01:52:00,292 INFO [PartitionStateMachine controllerId=0] Initializing partition state (kafka.controller.ZkPartitionStateMachine) [controller-event-thread]
2020-11-06 01:52:00,293 INFO [PartitionStateMachine controllerId=0] Triggering online partition state changes (kafka.controller.ZkPartitionStateMachine) [controller-event-thread]
2020-11-06 01:52:00,299 DEBUG [PartitionStateMachine controllerId=0] Started partition state machine with initial state -> Map() (kafka.controller.ZkPartitionStateMachine) [controller-event-thread]
2020-11-06 01:52:00,300 INFO [Controller id=0] Ready to serve as the new controller with epoch 1227 (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,314 INFO [Controller id=0] Partitions undergoing preferred replica election:  (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,314 INFO [Controller id=0] Partitions that completed preferred replica election:  (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,315 INFO [Controller id=0] Skipping preferred replica election for partitions due to topic deletion:  (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,316 INFO [Controller id=0] Resuming preferred replica election for partitions:  (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,318 INFO [Controller id=0] Starting replica leader election (PREFERRED) for partitions  triggered by ZkTriggered (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,335 INFO [Controller id=0] Starting the controller scheduler (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:00,353 INFO [RequestSendThread controllerId=0] Controller 0 connected to my-cluster-kafka-0.my-cluster-kafka-brokers.my-kafka-project.svc:9091 (id: 0 rack: null) for sending state change requests (kafka.controller.RequestSendThread) [Controller-0-to-broker-0-send-thread]
2020-11-06 01:52:00,372 TRACE [Controller id=0 epoch=1227] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 0 sent to broker my-cluster-kafka-0.my-cluster-kafka-brokers.my-kafka-project.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-11-06 01:52:05,338 INFO [Controller id=0] Processing automatic preferred replica leader election (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:05,339 TRACE [Controller id=0] Checking need to trigger auto leader balancing (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:26,637 INFO [Controller id=0] Newly added brokers: 1, deleted brokers: , bounced brokers: , all live brokers: 0,1 (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:26,637 DEBUG [Channel manager on controller 0]: Controller 0 trying to connect to broker 1 (kafka.controller.ControllerChannelManager) [controller-event-thread]
2020-11-06 01:52:26,760 INFO [RequestSendThread controllerId=0] Starting (kafka.controller.RequestSendThread) [Controller-0-to-broker-1-send-thread]
2020-11-06 01:52:26,765 INFO [Controller id=0] New broker startup callback for 1 (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:26,766 INFO [Controller id=0 epoch=1227] Sending UpdateMetadata request to brokers Set(0) for 0 partitions (state.change.logger) [controller-event-thread]
2020-11-06 01:52:26,767 INFO [Controller id=0 epoch=1227] Sending UpdateMetadata request to brokers Set(1) for 0 partitions (state.change.logger) [controller-event-thread]
2020-11-06 01:52:26,774 TRACE [Controller id=0 epoch=1227] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 1 sent to broker my-cluster-kafka-0.my-cluster-kafka-brokers.my-kafka-project.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-11-06 01:52:26,774 DEBUG [Controller id=0] Register BrokerModifications handler for Vector(1) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:26,779 INFO [Controller id=0] Updated broker epochs cache: Map(1 -> 4294999989, 0 -> 4294999970) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-06 01:52:27,073 INFO [RequestSendThread controllerId=0] Controller 0 connected to my-cluster-kafka-1.my-cluster-kafka-brokers.my-kafka-project.svc:9091 (id: 1 rack: null) for sending state change requests (kafka.controller.RequestSendThread) [Controller-0-to-broker-1-send-thread]
2020-11-06 01:52:27,141 TRACE [Controller id=0 epoch=1227] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 0 sent to broker my-cluster-kafka-1.my-cluster-kafka-brokers.my-kafka-project.svc:9091 (id: 1 rack: null) (state.change.logger) [Controller-0-to-broker-1-send-thread]
`

**Comment by AllenZMC** [comment]
#https://github.com/strimzi/strimzi-kafka-operator/issues/1478

**Comment by scholzj** [comment]
No, as I said before, it looks like the operator rolls the pod. But the log snippet you provided from the cluster operator was not long enough to show why.

**Comment by AllenZMC** [comment]
I have a new problem:
```
 k get po -n my-kafka-project
NAME                                         READY   STATUS             RESTARTS   AGE
my-cluster-entity-operator-99c546c94-qz6dg   3/3     Running            196        37h
my-cluster-kafka-0                           0/1     CrashLoopBackOff   44         16h
my-cluster-kafka-1                           0/1     CrashLoopBackOff   260        15h
my-cluster-zookeeper-0                       1/1     Running            0          16h
```

**Comment by scholzj** [comment]
This suggests the connection to Zookeeper failed.

**Comment by AllenZMC** [comment]
Thanks @scholzj

**Comment by scholzj** [comment]
It could be a network problem, yes. But to be honest I do not have any advice how to debug those. I guess good start would be to see if you can connect to Zookeeper from inside the Zookeeper pod (to localhost:12181 or localhost:21810 depending on your Strimzi version). Checking the Zookeeper and operator logs would be good as well -> Maybe the Zookeeper cluster does not work.

**Comment by scholzj** [comment]
Did you managed to solve this?
