### ISSUE TITLE
cluster-operator service Failed 

### ISSUE THREAD

**Issue by hhy5861** [strimzi/strimzi-kafka-operator#3971]
```
2020-11-18 09:32:44 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kafka-system...
2020-11-18 09:33:06 INFO  OperatorWatcher:40 - Reconciliation #290(watch) Kafka(kafka-system/spider-kafka): Kafka spider-kafka in namespace kafka-system was ADDED
2020-11-18 09:33:16 WARN  AbstractOperator:377 - Reconciliation #290(watch) Kafka(kafka-system/spider-kafka): Failed to acquire lock lock::kafka-system::Kafka::spider-kafka within 10000ms.
2020-11-18 09:33:21 ERROR Util:124 - Exceeded timeout of 300000ms while waiting for StatefulSet resource spider-kafka-kafka in namespace kafka-system to be ready
2020-11-18 09:33:21 ERROR AbstractOperator:238 - Reconciliation #286(watch) Kafka(kafka-system/spider-kafka): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource spider-kafka-kafka in namespace kafka-system to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:125) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-18 09:33:22 INFO  OperatorWatcher:40 - Reconciliation #291(watch) Kafka(kafka-system/spider-kafka): Kafka spider-kafka in namespace kafka-system was MODIFIED
2020-11-18 09:33:22 WARN  AbstractOperator:470 - Reconciliation #286(watch) Kafka(kafka-system/spider-kafka): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource spider-kafka-kafka in namespace kafka-system to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:125) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-18 09:33:22 WARN  AbstractOperator:96 - Kafka resource spider-kafka in namespace kafka-system: In API version kafka.strimzi.io/v1beta1 the property affinity at path spec.zookeeper.affinity has been deprecated. This feature should now be configured at path spec.zookeeper.template.pod.affinity.
2020-11-18 09:33:22 WARN  AbstractOperator:139 - Kafka resource spider-kafka in namespace kafka-system: Contains object at path spec.kafka.listeners.genericKafkaListeners with an unknown property: useServiceDnsDomain
2020-11-18 09:33:22 WARN  AbstractOperator:96 - Kafka resource spider-kafka in namespace kafka-system: In API version kafka.strimzi.io/v1beta1 the property affinity at path spec.kafka.affinity has been deprecated. This feature should now be configured at path spec.kafka.template.pod.affinity.
2020-11-18 09:33:22 WARN  AbstractOperator:96 - Kafka resource spider-kafka in namespace kafka-system: In API version kafka.strimzi.io/v1beta1 the property externalTrafficPolicy at path spec.kafka.template.externalBootstrapService.externalTrafficPolicy has been deprecated.
2020-11-18 09:33:22 WARN  AbstractOperator:96 - Kafka resource spider-kafka in namespace kafka-system: In API version kafka.strimzi.io/v1beta1 the property affinity at path spec.zookeeper.affinity has been deprecated. This feature should now be configured at path spec.zookeeper.template.pod.affinity.
2020-11-18 09:33:22 WARN  AbstractOperator:139 - Kafka resource spider-kafka in namespace kafka-system: Contains object at path spec.kafka.listeners.genericKafkaListeners with an unknown property: useServiceDnsDomain
```

version
0.20.0

**Comment by scholzj** [comment]
From this log, we can't tell you anything more than what you can read there. The Kafka pods do not seem to be ready. You would need to look into the StatefulSet / Pod events and into the Pod logs to see why it is the case.

**Comment by Juandavi1** [comment]
Hi, i've the same issue. Can you help me ? 
here is the log of zookeeper

> broker-zookeeper-1 zookeeper java.net.UnknownHostException: broker-zookeeper-1.broker-zookeeper-nodes.kafka-system.svc
broker-zookeeper-1 zookeeper 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
broker-zookeeper-1 zookeeper 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
broker-zookeeper-1 zookeeper 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
broker-zookeeper-1 zookeeper 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
broker-zookeeper-1 zookeeper 	at java.base/java.net.InetAddress.getByName(InetAddress.java:1248)
broker-zookeeper-1 zookeeper 	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:197)
broker-zookeeper-1 zookeeper 	at org.apache.zookeeper.server.quorum.QuorumPeer.recreateSocketAddresses(QuorumPeer.java:746)
broker-zookeeper-1 zookeeper 	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:926)
broker-zookeeper-1 zookeeper 2020-11-18 16:10:27,492 WARN Failed to resolve address: broker-zookeeper-1.broker-zookeeper-nodes.kafka-system.svc (org.apache.zookeeper.server.quorum.QuorumPeer) [broker-zookeeper-1.broker-zookeeper-nodes.kafka-system.svc:3888]
broker-zookeeper-1 zookeeper java.net.UnknownHostExcep 

logs of cluster operator

> 2020-11-18 16:13:56 ERROR AbstractOperator:238 - Reconciliation #0(watch) Kafka(kafka-system/broker): createOrUpdate failed                                                        │             │               │                  │                       │                           │                                  │                                             │
│ io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StatefulSet resource broker-zookeeper in namespace kafka-system to b │             │               │                  │                       │                           │                                  │                                             │
│     at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:125) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]                                                            │             │               │                  │                       │                           │                                  │                                             │
│     at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]                                                                   │             │               │                  │                       │                           │                                  │                                             │
│     at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]                                                                     │             │               │                  │                       │                           │                                  │                                             │
│     at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]                                                  │             │               │                  │                       │                           │                                  │                                             │
│     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]                            │             │               │                  │                       │                           │                                  │                                             │
│     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]                    │             │               │                  │                       │                           │                                  │                                             │
│     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]                                                       │             │               │                  │                       │                           │                                  │                                             │
│     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]                          │             │               │                  │                       │                           │                                  │                                             │
│     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]                                             │             │               │                  │                       │                           │                                  │                                             │
│     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]                                 │             │               │                  │                       │                           │                                  │                                             │
│     at java.lang.Thread.run(Thread.java:834) [?:?]             

this is the yaml configuration 

`
kafka:
  version: 2.6.0
  replicas: 3
  listeners:
    - name: external
      port: 9094
      type: loadbalancer
      tls: false
  config:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    log.message.format.version: '2.6'
  storage:
    type: ephemeral
    
zookeeper:
  replicas: 3
  storage:
    type: ephemeral
  
entityOperator:
  topicOperator: {}
  userOperator: {}
`

Im using the operator version 0.20.0

Thanks in advance

**Comment by scholzj** [comment]
@Juandavi1 In your case it looks like some DNS issue. The Zookeeper nodes cannot resolve the DNS addresses and form the cluster. But I'm afraid Kubernetes DNS goes a bit beyond my know-how.

**Comment by Juandavi1** [comment]
hi, thanks for replying.

Yes, but I didn't change the default settings. It has always worked well for me, now that I updated to 0.20.0 it generates this exception

**Comment by scholzj** [comment]
The address it is connecting to is correct. This is how statefulsets and headless services work. I do not think we changed anything what could affect this in 0.20.0.

**Comment by hhy5861** [comment]
> From this log, we can't tell you anything more than what you can read there. The Kafka pods do not seem to be ready. You would need to look into the StatefulSet / Pod events and into the Pod logs to see why it is the case.

  Normal   Killing         17m (x2 over 18m)     kubelet            Container zookeeper failed liveness probe, will be restarted
  Normal   Pulled          17m (x3 over 18m)     kubelet            Container image "strimzi/kafka:0.20.0-kafka-2.6.0" already present on machine
  Normal   Created         17m (x3 over 18m)     kubelet            Created container zookeeper
  Normal   Started         17m (x3 over 18m)     kubelet            Started container zookeeper
  Warning  Unhealthy       17m (x7 over 18m)     kubelet            Liveness probe failed: Ncat: Connection refused.
  Warning  BackOff         8m45s (x27 over 14m)  kubelet            Back-off restarting failed container
  Warning  Unhealthy       3m50s (x26 over 18m)  kubelet            Readiness probe failed: Ncat: Connection refused

**Comment by pavansai8** [comment]
I am also facing similar or different issue, After I ran deployment command I am not seeing Kafka object set being deployed. I am only able to see zookeeper object set.

And I have strimzi operator deployed

NAME                                        READY   STATUS    RESTARTS   AGE
strimzi-cluster-operator-677fb648f4-rtf9x   1/1     Running   0          9d

After that I am trying to create kafka cluster.

Below are the steps I have performed:

copied the yaml file for deployment to kafka_deployment.yaml file

****** apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {} *****

2. Ran kubectl apply -f kafka_deployment.yaml -n kafka-soa-ns

3. when I run kubectl get pod command it is only showing strimzi operator but when I ran kubectl get kafka command it is showing below.
4. kubectl get kafka
NAME         DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS
my-cluster   1                        1
5. kubectl get services
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
my-cluster-zookeeper-client   ClusterIP   <IP>   <none>        2181/TCP                     33m
my-cluster-zookeeper-nodes    ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   33m

And it is not showing kafka objects or pods at all. Can anyone help me here. I am new to kubernetes deployment. Thanks in advance.

**Comment by scholzj** [comment]
@pavansai8 From the error, it might be an issue with storage. You should check the Zookeeper statefulset (if it was created and if it has any events) and the PVCs and PVs (whether they exist and are bound).

**Comment by pavansai8** [comment]
@scholzj Hi Jakub, Thank you for replying. Can you help me to understand it better. Is there a document guide you can refer me to perform list of steps. I might be missing something.  And since I never worked on kubernetes deployments I am finding it hard to identify the issue. Please don't mind.

**Comment by pavansai8** [comment]
@scholzj Also I am getting this error when trying run wait command to deploy kafka cluster

# kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka-soa-ns
error: timed out waiting for the condition on kafkas/my-cluster

**Comment by scholzj** [comment]
I guess the Kubernetes documentation should help you to get started. I'm afraid it is too long ago since I started. So not sure what are the best sources today. 

As for the things I asked about ... these would be the commands you can run and provide output:
* `kubectl describe statefulset my-cluster-zookeeper`
* `kubectl get statefulset my-cluster-zookeeper -o yaml`
* `kubectl get pvc`
* `kubectl get pv`
* `kubectl get storageclass`

**Comment by pavansai8** [comment]
@scholzj I am able to figure out the issue by using the commands you have shared and deployed it.

And can we deploy Envoy side car proxy on strimzi kafka operator?

**Comment by scholzj** [comment]
No, that would most probably not work. Especially if the Envoy proxy is the Istio one. Not sure whether this applies to any possible configurations of Envoy - there might be some which are ot intrusive and don't break things.

**Comment by pavansai8** [comment]
@scholzj  I am getting this error when I try to run producer on sample topic.

./kafka-console-producer.sh --broker-list 172.20.189.147:9092 --topic my-topic
>hi
[2021-01-21 07:04:28,483] ERROR Error when sending message to topic my-topic with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)


Can you please help me.

**Comment by scholzj** [comment]
Where did you got the IP address? Do you still use the same configuration as you shared here before?

**Comment by pavansai8** [comment]
I have made couple of modifications by adding resources and IP is the shows when I run below command.

kubectl get svc
NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kafka-cluster-1-kafka-0                    NodePort    <IP Address>    <none>        9094:30650/TCP               23h
kafka-cluster-1-kafka-1                    NodePort    <IP Address>    <none>        9094:30229/TCP               23h
kafka-cluster-1-kafka-2                    NodePort   <IP Address>      <none>        9094:30913/TCP               23h
kafka-cluster-1-kafka-bootstrap            ClusterIP   <IP Address>   <none>        9091/TCP,9092/TCP,9093/TCP   23h
kafka-cluster-1-kafka-brokers              ClusterIP   None             <none>        9091/TCP,9092/TCP,9093/TCP   23h
kafka-cluster-1-kafka-external-bootstrap   NodePort    <IP Address>    <none>        9094:30998/TCP               23h
kafka-cluster-1-zookeeper-client           ClusterIP   <IP Address>    <none>        2181/TCP                     23h
kafka-cluster-1-zookeeper-nodes            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   23h


And below is the deployment file I have used.

apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster-1
spec:
  kafka:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: "0.5"
      limits:
        memory: 4Gi
        cpu: "1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: "0.5"
      limits:
        memory: 4Gi
        cpu: "1"
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}

**Comment by scholzj** [comment]
Well, the port 9092 is in your CR configured as internal listener. So to connect to it, you can use `kafka-cluster-1-kafka-bootstrap:9092` or from other namespace as `kafka-cluster-1-kafka-bootstrap.<namespace>:9092`.

**Comment by pavansai8** [comment]
Thank you @scholzj  Now I got this error when I run this command.

./kafka-console-producer.sh --broker-list kafka-cluster-1-kafka-bootstrap:9092:9092 --topic my-topic
[2021-01-21 10:12:20,486] WARN Removing server kafka-cluster-1-kafka-bootstrap:9092:9092 from bootstrap.servers as DNS resolution failed for kafka-cluster-1-kafka-bootstrap:9092 (org.apache.kafka.clients.ClientUtils)

And what is the best way to create topic on strimzi kafka?

When I try this way 
cat << EOF | kubectl create -n kafka-soa-ns -f -                                                                                        apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: "kafka-cluster-1"
spec:
  partitions: 3
  replicas: 1
EOF


it is giving this error



Error from server (Forbidden): error when creating "STDIN": kafkatopics.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafka-soa-ns:kafka-soa-svc" cannot create resource "kafkatopics" in API group "kafka.strimzi.io" in the namespace "kafka-soa-ns"

**Comment by scholzj** [comment]
You seem to have way too many port numbers in the address: `kafka-cluster-1-kafka-bootstrap:9092:9092` - the `9092` is twice there.

As for the second error, you need to give the service account the RBAC rights to use the custom resources. For example using the strimzi-admin role: https://strimzi.io/docs/operators/latest/full/deploying.html#adding-users-the-strimzi-admin-role-str

**Comment by 4sif-adnan** [comment]
Hi,
I have been facing the same issue after upgrading k8s version from 1.21 to 1.22 last night
below is deployement file of mine

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: noice-dev
  namespace: strimzi-dev
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          brokers:
            - broker: 0
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
            - broker: 1
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
            - broker: 2
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"

```
NAME                                        READY   STATUS             RESTARTS         AGE
noice-dev-zookeeper-0                       0/1     CrashLoopBackOff   21 (3m32s ago)   58m
noice-dev-zookeeper-1                       0/1     CrashLoopBackOff   21 (2m50s ago)   58m
noice-dev-zookeeper-2                       0/1     CrashLoopBackOff   21 (3m22s ago)   58m
strimzi-cluster-operator-585f6fd9d7-8x9fk   1/1     Running            0                59m


Cluster operator logs below
```

2022-07-08 14:00:30 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace strimzi-dev
2022-07-08 14:00:30 INFO  AbstractOperator:226 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Kafka noice-dev will be checked for creation or modification
2022-07-08 14:01:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:02:30 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace strimzi-dev
2022-07-08 14:02:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:03:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:04:30 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace strimzi-dev
2022-07-08 14:04:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:05:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:05:31 ERROR Util:153 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-1 in namespace strimzi-dev to be ready
2022-07-08 14:05:31 ERROR Util:153 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-2 in namespace strimzi-dev to be ready
2022-07-08 14:05:31 ERROR Util:153 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-0 in namespace strimzi-dev to be ready
2022-07-08 14:05:31 ERROR AbstractOperator:247 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-0 in namespace strimzi-dev to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:154) ~[io.strimzi.operator-common-0.29.0.jar:0.29.0]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-07-08 14:05:31 WARN  AbstractOperator:532 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-0 in namespace strimzi-dev to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:154) ~[io.strimzi.operator-common-0.29.0.jar:0.29.0]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```
