### ISSUE TITLE
[Question] Cruise Control Stuck in CrashLoopBack 

### ISSUE THREAD

**Issue by ihatemodels** [strimzi/strimzi-kafka-operator#4012]
Hello, 

   I am not sure if this should be considered as bug or a question, so sorry if this is not in the right category. In version 0.20.0 of strimzi operator the cruise control is unable to start due to "**[ INFO ] Will not attempt to authenticate using SASL (unknown error)**". I had similar issue before with strimzi-operator 0.18.0 but magically the cruise control started after 70-80 restart.  The magic is gone now and I think the problem is bound tо wrong or missing configuration of my kafka deployment. 

**To Reproduce**

_Steps of how kafka is deployed_

1. kubectl create namespace kafka
2. helm install kafka-strimzi -n kafka strimzi-kafka-operator/ 
3. kubectl apply -f kafka.yaml

**Environment (please complete the following information):**
 - Strimzi version: 0.20.0
 - Installation method: Strimzi Operator: helm v3 and kafka.yaml 
 - Kubernetes cluster: kubernets 1.19.2 (deployed with rke )
 - Infrastructure: bare metal 

**YAML files and logs**

**kafka.yaml**

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    image: registry1.mydomain.com/kafka/kafka:2.5.0
    version: 2.5.0
    replicas: 5
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources:
      requests:
        memory: 16Gi
        cpu: "8"
      limits:
        memory: 24Gi
        cpu: "12"  
    jvmOptions:
      -Xms: "6g"
      -Xmx: "6g"
      -XX:
        UseG1GC: true
        InitiatingHeapOccupancyPercent: 35
        MinMetaspaceFreeRatio: 50
        MaxMetaspaceFreeRatio: 80
        MaxGCPauseMillis: 20
        MetaspaceSize: "96m"
        G1HeapRegionSize: "16M"
    listeners:
      external:
        type: loadbalancer
        tls: false
        overrides:
          bootstrap:
            address: kafka1.mydomain.com 
          brokers:
          - broker: 0
            advertisedHost: kafka1-broker0.mydomain.com
          - broker: 1
            advertisedHost: kafka1-broker1.mydomain.com
          - broker: 2
            advertisedHost: kafka1-broker2.mydomain.com
          - broker: 3
            advertisedHost: kafka1-broker3.mydomain.com
          - broker: 4
            advertisedHost: kafka1-broker4.mydomain.com
      plain: {}
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      default.replication.factor: 3
      log.retention.hours: 168
      num.network.threads: 3
      num.io.threads: 8
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    metrics: {}
  zookeeper:
    image: registry1.mydomain.com/kafka/kafka:2.5.0
    replicas: 5
    resources:
      requests:
        memory: 4Gi
        cpu: "2"
      limits:
        memory: 8Gi
        cpu: "4"  
    jvmOptions:
      -Xms: "4g"
      -Xmx: "4g"
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
    metrics: {}
    jmxOptions: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    image: registry1.mydomain.com/kafka/kafka:2.5.0
    groupRegex: ".*"
    topicRegex: ".*"
    logging: debug
    enableSaramaLogging: true
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  cruiseControl:
    image: registry1.mydomain.com/kafka/kafka:2.5.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "DEBUG"
```

**Cruise Control LOG**
 
```txt
INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient) [main]
2020-11-27 17:41:34,614 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:34,615 INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:35,719 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:35,721 INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:36,822 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:36,824 INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:37,925 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:37,926 INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:41:39,028 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]

2020-11-27 17:42:02,718 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:42:02,719 INFO Socket connection established, initiating session, client: /127.0.0.1:53526, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-27 17:42:12,734 WARN Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
```

**Cruise Control tls-sidecar LOG**

```txt
2020.11.27 15:47:12 LOG5[10:139703294883584]: Service [zookeeper-2181] accepted connection from 127.0.0.1:55702
2020.11.27 15:47:22 LOG3[10:139703294883584]: connect_blocking: s_poll_wait 10.43.139.57:2181: TIMEOUTconnect exceeded
2020.11.27 15:47:22 LOG5[10:139703294883584]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
2020.11.27 15:47:25 LOG5[10:139703294883584]: Service [zookeeper-2181] accepted connection from 127.0.0.1:55790
2020.11.27 15:47:25 LOG5[10:139703294883584]: connect_blocking: connected 10.43.139.57:2181
2020.11.27 15:47:25 LOG5[10:139703294883584]: Service [zookeeper-2181] connected remote server from 10.30.209.73:39248
2020.11.27 15:47:25 LOG5[10:139703294883584]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.11.27 15:47:25 LOG5[10:139703294883584]: Certificate accepted: depth=0, /O=io.strimzi/CN=kafka-cluster-zookeeper
2020.11.27 15:47:25 LOG5[10:139703294813952]: Service [zookeeper-2181] accepted connection from 127.0.0.1:55794
2020.11.27 15:47:25 LOG5[10:139703294813952]: connect_blocking: connected 10.43.139.57:2181
2020.11.27 15:47:25 LOG5[10:139703294813952]: Service [zookeeper-2181] connected remote server from 10.30.209.73:39252
2020.11.27 15:47:25 LOG5[10:139703294813952]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.11.27 15:47:25 LOG5[10:139703294813952]: Certificate accepted: depth=0, /O=io.strimzi/CN=kafka-cluster-zookeeper
2020.11.27 15:47:25 LOG5[10:139703294744320]: Service [zookeeper-2181] accepted connection from 127.0.0.1:55806
2020.11.27 15:47:35 LOG3[10:139703294744320]: connect_blocking: s_poll_wait 10.43.139.57:2181: TIMEOUTconnect exceeded
2020.11.27 15:47:35 LOG5[10:139703294744320]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
2020.11.27 15:47:36 LOG5[10:139703294744320]: Service [zookeeper-2181] accepted connection from 127.0.0.1:55882
2020.11.27 15:47:36 LOG5[10:139703294744320]: connect_blocking: connected 10.43.139.57:2181
2020.11.27 15:47:36 LOG5[10:139703294744320]: Service [zookeeper-2181] connected remote server from 10.30.209.73:39340
2020.11.27 15:47:36 LOG5[10:139703294744320]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.11.27 15:47:36 LOG5[10:139703294744320]: Certificate accepted: depth=0, /O=io.strimzi/CN=kafka-cluster-zookeeper
2020.11.27 15:47:48 LOG5[10:139703294813952]: Connection closed: 61 byte(s) sent to SSL, 61 byte(s) sent to socket
2020.11.27 15:47:48 LOG5[10:139703294744320]: Connection closed: 49 byte(s) sent to SSL, 41 byte(s) sent to socket
2020.11.27 15:47:48 LOG5[10:139703294883584]: Connection closed: 61 byte(s) sent to SSL, 61 byte(s) sent to socket
```

**Comment by tomncooper** [comment]
You appear to be using your own kafka image? Is that based on the official strimzi kafka image?

**Comment by ihatemodels** [comment]
I want to use private registry, so i just retaget the offical strimzi docker image. No changes made.

**Comment by tomncooper** [comment]
Are Kafka and Zookeeper able to come up ok and function?

**Comment by ihatemodels** [comment]
Yes. Kafka runs smooth as expected and I managed to connect from outside and inside the cluster. I also deployed Kafka connect and several user interfaces such as topics-ui and Kafdrop. It all connects and runs without disconnecting unexpectedly or experiencing any other problems. I also ran performance tests ( 20 k throutput/s ) on this deployment set. I have another cluster on the same infrastracture with 3 zookeeper replicas and strimzi operator 0.18 where Cruise Control runs without problems. 

The problems first popped up a month ago. I deployed strimzi 0.18 with 5 zookeeper replicas and the Cruise Control acted as it does now. I tried the strimzi-operator 0.20 but with no result. 

Please let me know if there's anything else you need.

**Comment by scholzj** [comment]
Some things you can check:
* It would be interesting to see what errors will be int he Zookeeper logs.
* Doublecheck that 10.43.139.57 is really the zookeeper-client service
* Check the the secret with the Cruise Control certificate is not empty and has similar age to the other certificate secrets
* Try to exec into the pod and see if you can open TCP connection to Zookeeper

**Comment by ihatemodels** [comment]
There are no errors in the Zookeeper logs. It seems the cruise control can authenticate successfully. The zookeper-client service ip is 10.43.139.57 but im not sure how to check a TCP connection. I tried netcat ( nc -zv kafka-cluster-zookeeper-client 2181/10.43.139.57 2181 ) from kafka and cruise-control/tls-sidecar pods but got time out. 

**Zookeeper logs**

```bash
2020-11-29 14:23:26,742 INFO Processing ruok command from /127.0.0.1:34450 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-4]
2020-11-29 14:23:33,611 INFO Processing ruok command from /127.0.0.1:34512 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-5]
2020-11-29 14:23:35,778 INFO Authenticated Id 'CN=kafka-cluster-cruise-control,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-5]
2020-11-29 14:23:35,945 INFO Authenticated Id 'CN=kafka-cluster-cruise-control,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-6]
2020-11-29 14:23:36,743 INFO Processing ruok command from /127.0.0.1:34544 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-6]
2020-11-29 14:23:43,611 INFO Processing ruok command from /127.0.0.1:34612 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-7]
2020-11-29 14:23:46,747 INFO Processing ruok command from /127.0.0.1:34630 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-8]
2020-11-29 14:23:47,626 INFO Authenticated Id 'CN=kafka-cluster-cruise-control,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-7]
2020-11-29 14:23:53,606 INFO Processing ruok command from /127.0.0.1:34700 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-1]
2020-11-29 14:23:56,742 INFO Processing ruok command from /127.0.0.1:34718 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-2]
```

Today i saw something new. The first attempt from the cruise control is returning the following log. 

```bash

**Comment by ihatemodels** [comment]
There are no errors in the Zookeeper logs. It seems the cruise control can authenticate successfully. The zookeper-client service ip is 10.43.139.57, but I am not sure how to check a TCP connection. I tried netcat ( nc -zv kafka-cluster-zookeeper-client 2181/10.43.139.57 2181 ) from kafka and cruise-control/tls-sidecar pods, but I got timeouts. 

**Zookeeper logs**

```bash
2020-11-29 14:23:26,742 INFO Processing ruok command from /127.0.0.1:34450 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-4]
2020-11-29 14:23:33,611 INFO Processing ruok command from /127.0.0.1:34512 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-5]
2020-11-29 14:23:35,778 INFO Authenticated Id 'CN=kafka-cluster-cruise-control,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-5]
2020-11-29 14:23:35,945 INFO Authenticated Id 'CN=kafka-cluster-cruise-control,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-6]
2020-11-29 14:23:36,743 INFO Processing ruok command from /127.0.0.1:34544 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-6]
2020-11-29 14:23:43,611 INFO Processing ruok command from /127.0.0.1:34612 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-7]
2020-11-29 14:23:46,747 INFO Processing ruok command from /127.0.0.1:34630 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-8]
2020-11-29 14:23:47,626 INFO Authenticated Id 'CN=kafka-cluster-cruise-control,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-7]
2020-11-29 14:23:53,606 INFO Processing ruok command from /127.0.0.1:34700 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-1]
2020-11-29 14:23:56,742 INFO Processing ruok command from /127.0.0.1:34718 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-2]
```

Today I saw something new. The first attempt from the cruise control is returning the following log. After the first restart of the pod logs are for timeout again. 

**First Attempt Cruise Control logs**
```bash
2020-11-29 14:28:51,766 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-29 14:28:51,767 INFO Socket connection established, initiating session, client: /127.0.0.1:60600, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2020-11-29 14:28:52,556 INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread) [ZkClient-EventThread-12-localhost:2181]
2020-11-29 14:29:01,889 INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper) [main]
2020-11-29 14:29:01,889 ERROR Uncaught exception on thread Thread[main,5,main] (com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain) [main]
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'localhost:2181' with timeout of 60000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at com.linkedin.kafka.cruisecontrol.detector.BrokerFailureDetector.<init>(BrokerFailureDetector.java:66)
	at com.linkedin.kafka.cruisecontrol.detector.AnomalyDetector.<init>(AnomalyDetector.java:110)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControl.<init>(KafkaCruiseControl.java:111)
	at com.linkedin.kafka.cruisecontrol.async.AsyncKafkaCruiseControl.<init>(AsyncKafkaCruiseControl.java:34)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlApp.<init>(KafkaCruiseControlApp.java:43)
	at com.linkedin.kafka.cruisecontrol.KafkaCruiseControlMain.main(KafkaCruiseControlMain.java:38)
2020-11-29 14:29:01,890 INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn) [main-EventThread]
```

I deployed another kafka with 1 zookeeper and 3 brokers without retaging the strimzi official docker image. I got the same result and the same log entries from cruise-control.

**Comment by scholzj** [comment]
It is weird if the `nc` command gives you timeout but at the same time the Zookeeper logs suggest that Cruise Control can authenticate there.

**Comment by scholzj** [comment]
This issue looks quite old. Is there still something we can help with? Or does it seem to work fine now?

**Comment by ihatemodels** [comment]
I am still against it. The Cruise Control is starting after at least 100 restarts. It is not only the first run after fresh deploy like I thought before. I faced the same issue running strimzi in one of the major cloud providers.  It does work fine after successful start  but for example when i reboot my kubernetes cluster I have to wait 2 hours ( around 200 pod restarts ) for Cruise Control to fire up.  Errors are still same as described in my previous answers. I am surprised how no one faced this issue, because I can reproduce the same behavior on different infrastructures with different strimzi versions. My advice is to keep the issue open. As soon as I have solution or any better idea I will post about it.

**Comment by scholzj** [comment]
Have you tried the solutions such as configure resources for CruiseControl and its TLS sidecar?

**Comment by jriv96** [comment]
I'm having this problem as well. 
EKS 1.18.9 and strimzi 0.20.1.

**Comment by scholzj** [comment]
Is there still something to do here? The last comments seem quite old and the Strimzi version as well. Is this still an issue with latest Strimzi versions?

**Comment by jrivers96** [comment]
I ran cruise control successfully on strimzi 0.25. 

Doesn't seem to have this problem anymore on my side...
