### ISSUE TITLE
[Bug] [Question] connecting to kafka-cluster from outside the pod

### ISSUE THREAD

**Issue by Bar0hayon** [strimzi/strimzi-kafka-operator#4042]
**Describe the bug**
I have configured a kafka cluster and a topic using your docs,
when I'm connecting to the cluster pod I am able to run the producer and consumer using bootstrap-server: localhost:9092,
in order to produce/consume from outside the pod I port forwarded port 9092 to port 9096, but when I'm trying to run the producer/consumer I'm getting the following error:
```
[2020-12-03 12:53:00,193] WARN [Consumer clientId=consumer-console-consumer-83408-1, groupId=console-consumer-83408] Error connecting to node my-cluster-kafka-0.my-cluster-kafka-brokers.my-kafka-project.svc:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.UnknownHostException: my-cluster-kafka-0.my-cluster-kafka-brokers.my-kafka-project.svc: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:403)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:363)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:151)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:958)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:294)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.tryConnect(ConsumerNetworkClient.java:575)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:816)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$FindCoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:796)
        at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:206)
        at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:169)
        at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:129)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:602)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:412)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:297)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:237)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:485)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1268)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1230)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
        at kafka.tools.ConsoleConsumer$ConsumerWrapper.receive(ConsoleConsumer.scala:438)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:104)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:78)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:55)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
``` 

I will appreciate your assistance, also, I will gladly try your best practice for connecting to the cluster if you can direct me to the right doc because I didn't find it... 

**To Reproduce**
1. ```kubectl get all -n my-kafka-project```
```
NAME                                              READY   STATUS    RESTARTS   AGE
pod/my-cluster-entity-operator-788cdfdd6d-b2x4k   3/3     Running   0          20h
pod/my-cluster-kafka-0                            1/1     Running   0          20h
pod/my-cluster-zookeeper-0                        1/1     Running   0          20h

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/my-cluster-kafka-bootstrap    ClusterIP   10.97.142.132   <none>        9091/TCP,9092/TCP,9093/TCP   20h
service/my-cluster-kafka-brokers      ClusterIP   None            <none>        9091/TCP,9092/TCP,9093/TCP   20h
service/my-cluster-zookeeper-client   ClusterIP   10.96.33.240    <none>        2181/TCP                     20h
service/my-cluster-zookeeper-nodes    ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   20h

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-cluster-entity-operator   1/1     1            1           20h

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/my-cluster-entity-operator-788cdfdd6d   1         1         1       20h

NAME                                    READY   AGE
statefulset.apps/my-cluster-kafka       1/1     20h
statefulset.apps/my-cluster-zookeeper   1/1     20h
```
2. ```kubectl port-forward pods/my-cluster-kafka-0 -n my-kafka-project 9096:9092```
3. from a different terminal: ```kafka-console-producer --bootstrap-server 127.0.0.1:9096 --topic my-topic```
4. See error above

**Expected behavior**
kafka-producer prompt for sending messages

**Environment (please complete the following information):**
 - Strimzi version: 0.20.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.13
 - Infrastructure: fedora VM

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
    storage:
      type: persistent-claim
      class: local-storage
      size: 1Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: local-storage
      size: 1Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Comment by scholzj** [comment]
I'm afraid Kafka is too complex to be accessed with port-forward. It has its own discovery mechanism for the brokers which advertises their addresses. So when you use port-forward, it still advertised the original address where the client cannot connect. You have to external listener to connect from outside of your Kubernetes cluster. Depending on your environment for example using node ports or load balancers. See more here: https://strimzi.io/docs/operators/latest/full/using.html#assembly-configuring-external-listeners-str or for example here: https://youtu.be/4bKSPrENDQQ

**Comment by Bar0hayon** [comment]
Thank you, that was very helpful 👍

**Comment by amitkbaid** [comment]
I faced similar error so I updated my /etc/hosts on my local pointing `127.0.0.1` to DNS of the kafka broker pods `(pod-name.headless-service.namespace.svc)` and I was able to connect to the kafka cluster from my local.
