### ISSUE TITLE
 I am not able to upload any new clusters on kafka-operator

### ISSUE THREAD

**Issue by ronanfmesquita2020** [strimzi/strimzi-kafka-operator#4043]
Good Morning;
This problem happened after I deleted the kafka-dev cluster and now I can't climb any more clusters.

kafka-operator log:

```
2020-12-03 11:39:04 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kafka-operator...
--
  | 2020-12-03 11:39:04 ERROR AbstractOperator:207 - Reconciliation #5216(timer) Kafka(kafka-operator/desenvolvimento): desenvolvimento spec cannot be null
  | 2020-12-03 11:39:04 ERROR AbstractOperator:207 - Reconciliation #5217(timer) Kafka(kafka-operator/kafka-dev): kafka-dev spec cannot be null
  | 2020-12-03 11:39:04 ERROR AbstractOperator:207 - Reconciliation #5218(timer) Kafka(kafka-operator/kfk-dev): kfk-dev spec cannot be null
  | 2020-12-03 11:39:04 ERROR AbstractOperator:207 - Reconciliation #5219(timer) Kafka(kafka-operator/kafka-hom): kafka-hom spec cannot be null
  | 2020-12-03 11:39:04 WARN  AbstractOperator:470 - Reconciliation #5216(timer) Kafka(kafka-operator/desenvolvimento): Failed to reconcile
  | io.strimzi.operator.cluster.model.InvalidResourceException: Spec cannot be null
  | at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$6(AbstractOperator.java:194) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
  | at io.strimzi.operator.common.AbstractOperator.lambda$withLock$13(AbstractOperator.java:360) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
  | at io.vertx.core.shareddata.impl.LocalAsyncLocks$LockWaiter.lambda$acquireLock$1(LocalAsyncLocks.java:65) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at java.lang.Thread.run(Thread.java:834) [?:?]
  | 2020-12-03 11:39:04 WARN  AbstractOperator:470 - Reconciliation #5217(timer) Kafka(kafka-operator/kafka-dev): Failed to reconcile
  | io.strimzi.operator.cluster.model.InvalidResourceException: Spec cannot be null
  | at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$6(AbstractOperator.java:194) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
  | at io.strimzi.operator.common.AbstractOperator.lambda$withLock$13(AbstractOperator.java:360) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
  | at io.vertx.core.shareddata.impl.LocalAsyncLocks$LockWaiter.lambda$acquireLock$1(LocalAsyncLocks.java:65) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at java.lang.Thread.run(Thread.java:834) [?:?]
  | 2020-12-03 11:39:04 WARN  AbstractOperator:470 - Reconciliation #5218(timer) Kafka(kafka-operator/kfk-dev): Failed to reconcile
  | io.strimzi.operator.cluster.model.InvalidResourceException: Spec cannot be null
  | at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$6(AbstractOperator.java:194) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
  | at io.strimzi.operator.common.AbstractOperator.lambda$withLock$13(AbstractOperator.java:360) ~[io.strimzi.operator-common-0.20.0.jar:0.20.0]
  | at io.vertx.core.shareddata.impl.LocalAsyncLocks$LockWaiter.lambda$acquireLock$1(LocalAsyncLocks.java:65) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
```

**Comment by scholzj** [comment]
So can you share the custom resources? The log says they all exist, but have no spec section.

**Comment by ronanfmesquita2020** [comment]
We managed to solve the problem, we were trying to upload two clusters in the same project and it wasn't working very well, we removed them all and created two separate projects and we put up the kafka in each one and it worked.
Thanks for the help.
