### ISSUE TITLE
[bug] strimzi operator 0.19 fails update to 0.20

### ISSUE THREAD

**Issue by fsoppelsa** [strimzi/strimzi-kafka-operator#4148]
**Describe the bug**
0.19 upstream Strimzi operator installed on a metal OpenShift 4.4 cluster (K8s 1.17).

The update to 0.20 fails apparently due to:

```
2020-11-29 13:23:21 ERROR AbstractOperator:301 - Watcher closed with exception in namespace kafka-si-dev
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 235964884 (246914617)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java
:263) [io.fabric8.kubernetes-client-4.6.4.jar:?]
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323) [com.squareup.okhttp3.okhttp-3.1
2.6.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) [com.squareup.okhttp3.okh
ttp-3.12.6.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) [com.squareup.okhttp3.okh
ttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [com.squareup.okhttp3.okhttp-3.12.6
.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [com.squareup.okhttp3.okhttp-3.12
.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

May be close to [3999](https://github.com/strimzi/strimzi-kafka-operator/issues/3999)

I also found [https://stackoverflow.com/questions/61409596/kubernetes-too-old-resource-version](https://stackoverflow.com/questions/61409596/kubernetes-too-old-resource-version) that may explain something but as rusty in Java I'm clueless in general.

And

```
2020-11-30 15:38:48 WARN  AbstractOperator:106 - Kafka resource kafka-si-dev-0 in namespace kafka-si-dev: Contains
object at path spec with unknown properties: template, livenessProbe
2020-11-30 15:38:48 WARN  AbstractOperator:106 - Kafka resource kafka-si-dev-0 in namespace kafka-si-dev: Contains
object at path spec.kafka with an unknown property: authentication
2020-11-30 15:38:48 WARN  AbstractOperator:106 - Kafka resource kafka-si-dev-0 in namespace kafka-si-dev: Contains object at path spec.kafka.listeners.external with an unknown property: tls
2020-11-30 15:38:48 INFO  AbstractOperator:173 - Reconciliation #16010(timer) Kafka(kafka-si-dev/kafka-si-dev-0): Kafka kafka-si-dev-0 should be created or updated
2020-11-30 15:38:51 INFO  AbstractOperator:318 - Reconciliation #16010(timer) Kafka(kafka-si-dev/kafka-si-dev-0): reconciled
```

[A.1.4. What do the failed to acquire lock warnings in the log mean?](https://strimzi.io/docs/operators/latest/full/using.html#what_do_the_failed_to_acquire_lock_warnings_in_the_log_mean)

_Should this message appear periodically, even in situations when there should be no other operations running for a given cluster, it might indicate that the lock was not properly released due to an error. If this is the case, try restarting the Cluster Operator._

**Comment by scholzj** [comment]
I do not think any of these errors are actual problems or suggest any issues with your update. They are both explain in the SO answer and in the FAQ. 

Why do you think your upgrade to 0.20 failed? Are some pods or Kafka clusters in not-ready state?

**Comment by fsoppelsa** [comment]
Hi Jakub,

Might it be that some Kafka objects were in a degraded state before? After the operator update, Strimzi Operator Details:

_Failed: install failed: deployment strimzi-cluster-operator-v0.20.0 n ot ready before timeout: deployment "strimzi-cluster-operator-v0.20.0" exceeded its progress deadline._

So currently there are both 0.19 and 0.20 here, with 0.19: "Cannot update" and 0.20 "Failed"

**Comment by scholzj** [comment]
The readiness of the operator is independent on the readiness of the operands. Where does this error come from? Is that from the Operator Hub? I'm not sure the OperatorHub in OCP 4.4 supports the ConfigMap resource used in Strimzi 0.20. So maybe that could be the problem. But you would probably need to look into the OperatorHub / OLM logs to see what the actual issue is.

**Comment by scholzj** [comment]
Just an update: It is indeed the case that the version of the Operator Hub bundled in OCP 4.4 does not support the Config Map. Strimzi still seems to work fine on OCP 4.4, but it has to be installed from the YAML files.
