### ISSUE TITLE
NotControllerException when creating a new topic configmap

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#422]
When a new topic configmap is created, it could happen the following exception in the topic controller.

```
2018-05-04 10:35:51,018] ERROR <igMapWatcher:47> [oop-thread-7] Failure processing ConfigMap watch event ADDED on map my-topic with labels {app=strimzi-topic, strimzi.io/cluster=my-cluster, strimzi.io/kind=topic}: This is not the correct controller for this cluster.
org.apache.kafka.common.errors.NotControllerException: This is not the correct controller for this cluster.
io.strimzi.controller.topic.ControllerException
    at io.strimzi.controller.topic.Controller$CreateKafkaTopic.lambda$handle$0(Controller.java:193)
    at io.strimzi.controller.topic.BaseKafkaImpl$UniWork.complete(BaseKafkaImpl.java:97)
    at io.strimzi.controller.topic.BaseKafkaImpl$Work.run(BaseKafkaImpl.java:54)
    at io.strimzi.controller.topic.BaseKafkaImpl$Work.handle(BaseKafkaImpl.java:61)
    at io.strimzi.controller.topic.BaseKafkaImpl$Work.handle(BaseKafkaImpl.java:51)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.NotControllerException: This is not the correct controller for this cluster.
```

**Comment by scholzj** [comment]
Isn't this already covered somewhere? BEcasue we already had a discussion about old metadata in TO.

**Comment by tombentley** [comment]
There's [KAFKA-6299](https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-6299?filter=allopenissues) for this in Kafka. When that's fixed NotControllerException shouldn't propagate out of the AdminClient.

**Comment by sherl0cks** [comment]
Just hit this myself. Looks like https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-6299?filter=allopenissues is resolved, but in kafka 2.0.0 which is still on release candidate. Once we see 2.0.0 ga, should that change propagate here?

Deleting and recreating the topic config map resolved the issue. Is that the correct fix for now?

**Comment by scholzj** [comment]
Once 2.0.0 is released, we will update to it. Until then the workaround you mentioned is probably the best one.

**Comment by sherl0cks** [comment]
Thanks @scholzj

**Comment by EricGregMiller** [comment]
I'm getting org.apache.kafka.common.errors.NotControllerException when I try to create a topic. I don't understand the work around. How does one delete and recreate the topic config map?

**Comment by sherl0cks** [comment]
```
$ oc project <project where the strimzi operator lives>
$ oc delete cm <name of your config map>
```

you can then just recreate it after you delete it with

`$ oc create -f <your config map>`

**Comment by scholzj** [comment]
Thsi wasn't seen for a long time. So it was probably fixed by some other work in TO or in Kafka. We should close this.
