### ISSUE TITLE
Missing 0.21.1 images in Quay.io for Kafka 2.5.0

### ISSUE THREAD

**Issue by ggrames** [strimzi/strimzi-kafka-operator#4316]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
The Strimzi operator 0.21.1 is installed. During Creation of a Kafka instance for Version 2.5.0 with the operator GUI 2 errors occured:
1.)  Error: has invalid spec.kafka.config: inter.broker.protocol.version has value '2.7' which does not match the required pattern
      in Instance:
          apiVersion: kafka.strimzi.io/v1beta1
          kind: Kafka

      inter.broker.protocol.version: '2.7'
      log.message.format.version: '2.7'

      I have fixed this by changing the values to 2.5
2.)  Error: ImagePull
      in Instance:
          apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion

      - name: STRIMZI_KAFKA_IMAGES
         value: >
                          2.5.0=quay.io/strimzi/kafka@sha256:5d3f4313b465b6a987b0de398969342b31157cacde1b06ed9b5f2e7d08e73549
                          ...
       - name: STRIMZI_KAFKA_CONNECT_IMAGES
         value: >
                          2.5.0=quay.io/strimzi/kafka@sha256:5d3f4313b465b6a987b0de398969342b31157cacde1b06ed9b5f2e7d08e73549
						  ...
				      ...

      I have fixed the issue by changing the image tag to the existing image: f1268f53ce158ceaed3b93c6449e7318853f3d9eefbfe125dc19e58db8c76f99

**Expected behavior**
Running kafka/zookeper cluster for kafka version 2.5.0

**Environment (please complete the following information):**
 - Strimzi version: 0.21.1
 - Installation method: OperatorHub.io
 - Kubernetes cluster: OpenShift 4.6
 - Infrastructure: Vsphere virtualization

**Comment by scholzj** [comment]
The second problem looks like a bad digest. I will look into it. The 2.5.0 image is in Quay, but the digest seems to be `sha256:f1268f53ce158ceaed3b93c6449e7318853f3d9eefbfe125dc19e58db8c76f99`.  

For the first problem ... Can you elaborate more on the steps you did? Kafka 2.5.0 indeed cannot have 2.7 message and protocol versions. But the operator would not add it to the custom resource. So, are you talking about the example YAMLs in the Operator Hub UI?

**Comment by ggrames** [comment]
No, i am talking about a new created Kafka Instance. I have created it with the GUI. There i changed only the Kafka Version from default 2.7.0 to 2.5.0

**Steps to reproduce**
  Operator is installed
  On the GUI: Installed Operators --> Strimzi --> Kafka --> Create Kafka
  Name: my-cluster1
  Kafka --> Version: 2.5.0
  PRESS Create

In the strimzi-cluster-operator-v0.21.1-* i can see following logs:
`2021-01-26 11:16:54 INFO  OperatorWatcher:40 - Reconciliation #79(watch) Kafka(kafka-test-ns/my-cluster1): Kafka my-cluster1 in namespace kafka-test-ns was ADDED
2021-01-26 11:16:54 INFO  AbstractOperator:219 - Reconciliation #79(watch) Kafka(kafka-test-ns/my-cluster1): Kafka my-cluster1 will be checked for creation or modification
2021-01-26 11:16:54 INFO  OperatorWatcher:40 - Reconciliation #80(watch) Kafka(kafka-test-ns/my-cluster1): Kafka my-cluster1 in namespace kafka-test-ns was MODIFIED
2021-01-26 11:16:55 WARN  AbstractModel:468 - Kafka kafka-test-ns/my-cluster1 has invalid spec.kafka.config: inter.broker.protocol.version has value '2.7' which does not match the required pattern: \Q0.8.0\E(\.[0-9]+)*|\Q0.8.0\E|\Q0.8.1\E(\.[0-9]+)*|\Q0.8.1\E|\Q0.8.2\E(\.[0-9]+)*|\Q0.8.2\E|\Q0.9.0\E(\.[0-9]+)*|\Q0.9.0\E|\Q0.10.0\E(\.[0-9]+)*|\Q0.10.0-IV0\E|\Q0.10.0-IV1\E|\Q0.10.1\E(\.[0-9]+)*|\Q0.10.1-IV0\E|\Q0.10.1-IV1\E|\Q0.10.1-IV2\E|\Q0.10.2\E(\.[0-9]+)*|\Q0.10.2-IV0\E|\Q0.11.0\E(\.[0-9]+)*|\Q0.11.0-IV0\E|\Q0.11.0-IV1\E|\Q0.11.0-IV2\E|\Q1.0\E(\.[0-9]+)*|\Q1.0-IV0\E|\Q1.1\E(\.[0-9]+)*|\Q1.1-IV0\E|\Q2.0\E(\.[0-9]+)*|\Q2.0-IV0\E|\Q2.0-IV1\E|\Q2.1\E(\.[0-9]+)*|\Q2.1-IV0\E|\Q2.1-IV1\E|\Q2.1-IV2\E|\Q2.2\E(\.[0-9]+)*|\Q2.2-IV0\E|\Q2.2-IV1\E|\Q2.3\E(\.[0-9]+)*|\Q2.3-IV0\E|\Q2.3-IV1\E|\Q2.4\E(\.[0-9]+)*|\Q2.4-IV0\E|\Q2.4-IV1\E|\Q2.5\E(\.[0-9]+)*|\Q2.5-IV0\E
2021-01-26 11:16:55 WARN  AbstractModel:468 - Kafka kafka-test-ns/my-cluster1 has invalid spec.kafka.config: log.message.format.version has value '2.7' which does not match the required pattern: \Q0.8.0\E(\.[0-9]+)*|\Q0.8.0\E|\Q0.8.1\E(\.[0-9]+)*|\Q0.8.1\E|\Q0.8.2\E(\.[0-9]+)*|\Q0.8.2\E|\Q0.9.0\E(\.[0-9]+)*|\Q0.9.0\E|\Q0.10.0\E(\.[0-9]+)*|\Q0.10.0-IV0\E|\Q0.10.0-IV1\E|\Q0.10.1\E(\.[0-9]+)*|\Q0.10.1-IV0\E|\Q0.10.1-IV1\E|\Q0.10.1-IV2\E|\Q0.10.2\E(\.[0-9]+)*|\Q0.10.2-IV0\E|\Q0.11.0\E(\.[0-9]+)*|\Q0.11.0-IV0\E|\Q0.11.0-IV1\E|\Q0.11.0-IV2\E|\Q1.0\E(\.[0-9]+)*|\Q1.0-IV0\E|\Q1.1\E(\.[0-9]+)*|\Q1.1-IV0\E|\Q2.0\E(\.[0-9]+)*|\Q2.0-IV0\E|\Q2.0-IV1\E|\Q2.1\E(\.[0-9]+)*|\Q2.1-IV0\E|\Q2.1-IV1\E|\Q2.1-IV2\E|\Q2.2\E(\.[0-9]+)*|\Q2.2-IV0\E|\Q2.2-IV1\E|\Q2.3\E(\.[0-9]+)*|\Q2.3-IV0\E|\Q2.3-IV1\E|\Q2.4\E(\.[0-9]+)*|\Q2.4-IV0\E|\Q2.4-IV1\E|\Q2.5\E(\.[0-9]+)*|\Q2.5-IV0\E
2021-01-26 11:16:55 ERROR AbstractOperator:240 - Reconciliation #79(watch) Kafka(kafka-test-ns/my-cluster1): createOrUpdate failed
io.strimzi.operator.cluster.model.InvalidResourceException: Kafka kafka-test-ns/my-cluster1 has invalid spec.kafka.config: inter.broker.protocol.version has value '2.7' which does not match the required pattern: \Q0.8.0\E(\.[0-9]+)*|\Q0.8.0\E|\Q0.8.1\E(\.[0-9]+)*|\Q0.8.1\E|\Q0.8.2\E(\.[0-9]+)*|\Q0.8.2\E|\Q0.9.0\E(\.[0-9]+)*|\Q0.9.0\E|\Q0.10.0\E(\.[0-9]+)*|\Q0.10.0-IV0\E|\Q0.10.0-IV1\E|\Q0.10.1\E(\.[0-9]+)*|\Q0.10.1-IV0\E|\Q0.10.1-IV1\E|\Q0.10.1-IV2\E|\Q0.10.2\E(\.[0-9]+)*|\Q0.10.2-IV0\E|\Q0.11.0\E(\.[0-9]+)*|\Q0.11.0-IV0\E|\Q0.11.0-IV1\E|\Q0.11.0-IV2\E|\Q1.0\E(\.[0-9]+)*|\Q1.0-IV0\E|\Q1.1\E(\.[0-9]+)*|\Q1.1-IV0\E|\Q2.0\E(\.[0-9]+)*|\Q2.0-IV0\E|\Q2.0-IV1\E|\Q2.1\E(\.[0-9]+)*|\Q2.1-IV0\E|\Q2.1-IV1\E|\Q2.1-IV2\E|\Q2.2\E(\.[0-9]+)*|\Q2.2-IV0\E|\Q2.2-IV1\E|\Q2.3\E(\.[0-9]+)*|\Q2.3-IV0\E|\Q2.3-IV1\E|\Q2.4\E(\.[0-9]+)*|\Q2.4-IV0\E|\Q2.4-IV1\E|\Q2.5\E(\.[0-9]+)*|\Q2.5-IV0\E, log.message.format.version has value '2.7' which does not match the required pattern: \Q0.8.0\E(\.[0-9]+)*|\Q0.8.0\E|\Q0.8.1\E(\.[0-9]+)...
	at io.strimzi.operator.cluster.model.KafkaCluster.fromCrd(KafkaCluster.java:476) ~[io.strimzi.cluster-operator-0.21.1.jar:0.21.1]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$getKafkaClusterDescription$84(KafkaAssemblyOperator.java:1829) ~[io.strimzi.cluster-operator-0.21.1.jar:0.21.1]
	at io.vertx.core.Future.lambda$compose$3(Future.java:368) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:176) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by ggrames** [comment]
When i edit the yaml of the Kafkas Instance "my-cluster1" 

from
`  ...
  name: my-cluster1
  resourceVersion: '291100099'
  selfLink: >-
    /apis/kafka.strimzi.io/v1beta1/namespaces/playground-ggrames/kafkas/my-cluster1
  uid: caa8ed7e-5ab7-4b97-ada6-ddecfb7c4597
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: '2.7'
      log.message.format.version: '2.7'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    ...`

to
` name: my-cluster1
  resourceVersion: '291100099'
  selfLink: >-
    /apis/kafka.strimzi.io/v1beta1/namespaces/playground-ggrames/kafkas/my-cluster1
  uid: caa8ed7e-5ab7-4b97-ada6-ddecfb7c4597
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: '2.5'
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3`

it is working.

**Comment by scholzj** [comment]
Well, that is expected. The example is written for Kafka 2.7.0 => so if you want to use older Kafka version, you have to change it everywhere - including the `inter.broker.protocol.version` and `log.message.format.version`.

**Comment by ggrames** [comment]
Ok. Than the first one is not a bug. 
The second one is the digest problem.
Thanks for the clarification.
I think you will provide a new minor release with the fix?

**Comment by scholzj** [comment]
New release should IMHO not be needed. I opened operator-framework/community-operators#3052 and operator-framework/community-operators#3053 to fix this.

**Comment by Aldjinn** [comment]
Hi,
I'm currently affected by this problem as well: I'm running the strimzi-cluster-operator-v0.21.1 providing a Kafka 2.5.0 cluster for about 9 month and since a few days exactly the same image is missing: quay.io/strimzi/kafka@sha256:5d3f4313b465b6a987b0de398969342b31157cacde1b06ed9b5f2e7d08e73549

I would like to avoid manually changing the digest values in the ClusterServiceVersion. Is there a better way to fix this issue?

**Comment by scholzj** [comment]
I think you just need to refresh the catalog to get the updated CSV files from the PRs above.

**Comment by Aldjinn** [comment]
Yes, but how? I forced an update of operatorhubio-catalog by using the approach mentioned in [1]. This has been successful and the pod is running with upstream-community-operators:sha256:3c8ea6e7140cf672a56c1493b9102f1d4c5dc0f5990da072e483d923e7ed09eb

But how and when does the strimzi-kafka-operator poll for updates from upstream-community-operators? Am I able to force this?

[1] https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/catalog-polling.md

**Comment by scholzj** [comment]
The operator does not poll for it. It has to be the OLM which updates it. But TBH I do not know enough about OLM ... I would assume it should update the CSV when it gets the updated catalog and that should update the operator.

**Comment by Aldjinn** [comment]
Finally, I was able to "force" the update by removing the subscription and the CSV and then subscribe again.

```bash
k -n operators delete subscriptions.operators.coreos.com my-strimzi-kafka-operator
k -n operators delete clusterserviceversions.operators.coreos.com strimzi-cluster-operator.v0.21.1
k delete -f https://operatorhub.io/install/strimzi-kafka-operator.yaml
k create -f https://operatorhub.io/install/strimzi-kafka-operator.yaml
```
Then after a few seconds the Kafka related pods are restarted with the desired image version: quay.io/strimzi/kafka@sha256:f1268f53ce158ceaed3b93c6449e7318853f3d9eefbfe125dc19e58db8c76f99

Thanks again, @scholzj. Without your hints, I would not have been able to solve this issue.

**Comment by scholzj** [comment]
Glad it works ... and sorry for the issue :-/
