### ISSUE TITLE
entity-operator Back-off restarting failed container

### ISSUE THREAD

**Issue by kovalyukm** [strimzi/strimzi-kafka-operator#4419]
**Describe the bug**
When specifying in Kafka resource in entityOperator field resources for userOperator and topicOperator these containers are going to CrashLoopBackOff with Readiness/Liveness probe failed: connection refused.

**To Reproduce**
Specify resources sections like:
```yaml
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 15m
        limits:
          memory: 512Mi
          cpu: 50m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 15m
        limits:
          memory: 512Mi
          cpu: 50m
```

**Expected behavior**
Pod with running and ready containers.

**Environment (please complete the following information):**
 - Strimzi version: 0.21.0
 - Installation method: Helm chart
 - Kubernetes cluster: 1.18
 - Infrastructure: Amazon EKS

**YAML files and logs**
Log of strimzi operator:
```
2021-02-15 19:01:05 ERROR Util:125 - Exceeded timeout of 300000ms while waiting for Deployment resource kafka-main-entity-operator in namespace kafka to be ready
2021-02-15 19:01:05 ERROR AbstractOperator:240 - Reconciliation #3213(timer) Kafka(kafka/kafka-main): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Deployment resource kafka-main-entity-operator in namespace kafka to be ready
at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:126) ~[io.strimzi.operator-common-0.21.0.jar:0.21.0]
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-15 19:01:05 WARN AbstractOperator:472 - Reconciliation #3213(timer) Kafka(kafka/kafka-main): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Deployment resource kafka-main-entity-operator in namespace kafka to be ready
at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:126) ~[io.strimzi.operator-common-0.21.0.jar:0.21.0]
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-15 19:02:03 INFO ClusterOperator:125 - Triggering periodic reconciliation for namespace *...
2021-02-15 19:02:03 INFO AbstractOperator:219 - Reconciliation #3219(timer) Kafka(kafka/kafka-main): Kafka kafka-main will be checked for creation or modification
```
Thanks!

**Comment by scholzj** [comment]
You would need to share the logs from the pod which is not ready. But my initial assumption would be 15m/50m CPU is not enough. I normally run it with 200m request / 500m limit for each (but I never tested whether that is the bare minimum or not).

**Comment by kovalyukm** [comment]
Thanks, @scholzj !
It works with:
```yaml
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 250m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 75m
        limits:
          memory: 512Mi
          cpu: 250m
```

**Comment by scholzj** [comment]
Great. So I guess we can close this?
