### ISSUE TITLE
Missing `consumer-offsets` kt when having more than one cluster in the same ns

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#4660]
**Description**

When using a single namespaced cluster operator to handle more than one cluster, all with producer/consumer activity, only one `consumer_offsets` KafkaTopic resource is created.

Example with 2 clusters:
```sh
$ kubectl get kt --show-labels
NAME                                                          CLUSTER       PARTITIONS   REPLICATION FACTOR   READY   LABELS
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a   my-cluster    50           3                    True    strimzi.io/cluster=my-cluster
foo-topic                                                     foo-cluster   2            3                    True    strimzi.io/cluster=foo-cluster
my-topic                                                      my-cluster    2            3                    True    strimzi.io/cluster=my-cluster
```

Error on 2nd topic-operator (topic already exists):
```log
2021-03-28 08:56:31,89055 INFO  [vert.x-eventloop-thread-1] TopicOperator:537 - 10|periodic -__consumer_offsets: Reconciling topic __consumer_offsets, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
2021-03-28 08:56:32,17840 ERROR [vert.x-eventloop-thread-1] TopicOperator:1414 - Error reconciling KafkaTopic null
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/apis/kafka.strimzi.io/v1beta1/namespaces/test/kafkatopics. Message: kafkatopics.kafka.strimzi.io "consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=kafka.strimzi.io, kind=kafkatopics, name=consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=kafkatopics.kafka.strimzi.io "consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:509) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:250) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:881) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:341) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:84) ~[io.fabric8.kubernetes-client-4.13.0.jar:?]
	at io.strimzi.operator.topic.K8sImpl.lambda$createResource$0(K8sImpl.java:53) ~[io.strimzi.topic-operator-0.21.1.jar:0.21.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Steps to reproduce**

0. Deploy cluster operator
1. Deploy 1st cluster `my-cluster` with topic `my-topic` and send/receive some data
2. Deploy 2nd cluster `foo-cluster` with topic `foo-topic` and send/receive some data
3. Run command `kubectl get kt --show-labels` to check KafkaTopic resources

**Expected behavior**

The expected behavior is to have one `consumer_offsets` topic labeled `strimzi.io/cluster=$CLUSTER_NAME` for each Kafka cluster watched by a single namespaced cluster operator.

**Environment**

 - Strimzi version: 0.21.1
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.16
 - Infrastructure: Minikube

**YAML files and logs**
- [my-cluster-topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/6217077/my-cluster-topic-operator.log)
- [foo-cluster-topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/6217078/foo-cluster-topic-operator.log)

**Comment by scholzj** [comment]
This is more or less expected. When you want to run multiple Kafka clusters in the same namespace, you might not be able to use the Topic and User operators because the resources would conflict.

**Comment by fvaleri** [comment]
Well, given that each cluster has it's own entity-operator, we can use labels to avoid conflicts. I didn't have time to look into the code yet, but I guess we could create another KafkaTopic resource named `consumer-offsets--$UUID` with label `strimzi.io/cluster=foo-cluster`.

**Comment by scholzj** [comment]
The labels do not solve the real problems that the custom resource can exist only once. So for example, with User Operator, you would never be able to have user with the same username in both clusters. The Topic Operator allows you to specify the topic name inside the CR. But it is still very awkward since you need to keep in mind and rename the resources based on where you are deploying it.

**Comment by fvaleri** [comment]
I understand this, but the internal `consumer_offsets` CR is auto created, so I would expect the 2nd topic-operator to use a different uuid in the topic name.

**Comment by scholzj** [comment]
It can, but IMHO it would be quite a lot of effort and complexity for something what still doesn't really work well.

**Comment by scholzj** [comment]
Triaged on 7th July 2022: Ideally, one one Kafka cluster should be in one namespace. If that is not possible, only one of the clusters should have TO enabled. In #6986, we updated the docs about this to make it more clear.
