### ISSUE TITLE
Prometheus metrics to capture outbound request information to the Kubernetes API

### ISSUE THREAD

**Issue by obrienrobert** [strimzi/strimzi-kafka-operator#4703]
**Is your feature request related to a problem? Please describe.**
We recently encountered an issue where the operator was failing to communicate with the Kubernetes API, caused by a `SocketTimeoutException` exception which originates from the `fabric.io` client:
```
SEVERE: Unhandled exception
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:244)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:196)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:477)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:935)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84)
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.get(AbstractResourceOperator.java:233)
	at io.strimzi.operator.common.AbstractOperator.updateResourceState(AbstractOperator.java:496)
	at io.strimzi.operator.common.AbstractOperator.handleResult(AbstractOperator.java:467)
	at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$7(AbstractOperator.java:269)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.strimzi.operator.common.AbstractOperator.lambda$withLock$12(AbstractOperator.java:364)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$2(AbstractOperator.java:241)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at io.vertx.core.impl.FailedFuture.onComplete(FailedFuture.java:49)
	at io.vertx.core.Future.lambda$compose$3(Future.java:382)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:234)
	... 39 more
```

**Describe the solution you'd like**
Prometheus metrics that capture outbound requests from the operator (request duration and status) to the K8s API to allow alerts that notify us when the operator is unable to communicate with K8s for an extended period to be created.

**Describe alternatives you've considered**
I looked at the existing operator metrics to see if they could alert us when this issue occurs.

**Comment by obrienrobert** [comment]
@ppatierno as discussed, FYI.

**Comment by obrienrobert** [comment]
@ppatierno just following up on this to see if there will be any actions/follow up on this issue? (it was discussed as part of the RTS backlog refinement)

**Comment by ppatierno** [comment]
@obrienrobert I don't think there was any follow up on this. Is it something reproducible or it happens time to time?

**Comment by obrienrobert** [comment]
@ppatierno we don't currently have a way to reproduce it. I haven't heard any reports of it occurring since either.
