### ISSUE TITLE
Unable to connect to zookeeper server 'my-cluster-zookeeper-client:2181'

### ISSUE THREAD

**Issue by kumarlinux** [strimzi/strimzi-kafka-operator#4783]
Hi Team,

$ kubectl logs -f strimzi-topic-operator-799bb85885-gb4qp -n kafka-zookeeper-dev3

2021-04-21 05:06:57 INFO  ZooKeeper:868 - Initiating client connection, connectString=my-cluster-zookeeper-client:2181 sessionTimeout=20000 watcher=org.I0Itec.zkclient.ZkClient@44f059f0
2021-04-21 05:06:58 INFO  X509Util:79 - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2021-04-21 05:06:58 INFO  ClientCnxnSocket:237 - jute.maxbuffer value is 4194304 Bytes
2021-04-21 05:06:59 INFO  ClientCnxn:1653 - zookeeper.request.timeout value is 0. feature enabled=
2021-04-21 05:06:59 INFO  ZkClient:936 - Waiting for keeper state SyncConnected
2021-04-21 05:06:59 INFO  ClientCnxn:1112 - Opening socket connection to server my-cluster-zookeeper-client/10.0.176.176:2181. Will not attempt to authenticate using SASL (unknown error)
2021-04-21 05:07:19 INFO  ZkEventThread:83 - Terminate ZkClient event thread.
2021-04-21 05:07:19 WARN  ClientCnxn:1190 - Client session timed out, have not heard from server in 20108ms for sessionid 0x0
2021-04-21 05:07:19 INFO  ZooKeeper:1422 - Session: 0x0 closed
2021-04-21 05:07:19 INFO  ClientCnxn:524 - EventThread shut down for session: 0x0
2021-04-21 05:07:19 ERROR Main:56 - Error deploying Session
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'my-cluster-zookeeper-client:2181' with timeout of 20000 ms
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98) ~[com.101tec.zkclient-0.11.jar:?]
        at io.strimzi.operator.topic.zk.Zk.createSync(Zk.java:36) ~[io.strimzi.topic-operator-0.22.1.jar:0.22.1]
        at io.strimzi.operator.topic.zk.Zk.lambda$create$0(Zk.java:27) ~[io.strimzi.topic-operator-0.22.1.jar:0.22.1]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]

Clusterinfo:

$ kubectl get pods -n kafka-zookeeper-dev3
NAME                                         READY   STATUS             RESTARTS   AGE
my-cluster-entity-operator-d8bc76496-8bhmx   3/3     Running            0          40m
my-cluster-kafka-0                           1/1     Running            0          34m
my-cluster-kafka-1                           1/1     Running            0          33m
my-cluster-kafka-2                           1/1     Running            0          33m
my-cluster-zookeeper-0                       1/1     Running            0          42m
my-cluster-zookeeper-1                       1/1     Running            0          35m
my-cluster-zookeeper-2                       1/1     Running            0          35m
strimzi-cluster-operator-698944bf78-b68px    1/1     Running            0          47m
strimzi-topic-operator-799bb85885-gb4qp      0/1     CrashLoopBackOff   9          23m

**Comment by scholzj** [comment]
The Topic Operator runs already as part of the entity-operator pod. You do not need / should not install it separately to use it with Strimzi deployed Kafka cluster. The standalone installation is supposed to be used with other Kafka installations such as Amazon MSK etc.
