### ISSUE TITLE
Spurious errors during reconcile if cluster gets deleted

### ISSUE THREAD

**Issue by rareddy** [strimzi/strimzi-kafka-operator#4856]
**Describe the bug**
When working with a large number of Kafka clusters that are managed by Strimzi, if one the cluster is deleted during the reconcile cycle (default every 2mins) the log will show different errors. For example:

```
java.lang.RuntimeException: Secret mk-test-user-webui-outage-1rowkljacpm59waugpmzwajrqhc/test-user-cluster-ca-cert does not exist
	at io.strimzi.operator.common.Util.missingSecretException(Util.java:194) ~[io.strimzi.operator-common-0.22.1.redhat-00005.jar:0.22.1.redhat-00005]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$adminClientSecrets$28(KafkaAssemblyOperator.java:1073) ~[io.strimzi.cluster-operator-0.22.1.redhat-00005.jar:0.22.1.redhat-00005]
	at io.vertx.core.Future.lambda$compose$3(Future.java:368) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:176) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.4.redhat-00001.jar:3.9.4.redhat-00001]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) [io.netty.netty-transport-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The above exception is just an example, it can be on any other resource. I do see that during the start of the reconcile cycle the code does check some labels to see the cluster is being deleted, but may not be stopping all scenarios. There is no effect due to this but there are a lot of false exceptions in log

**To Reproduce**
1. create a few kafka clusters
2. delete a cluster during reconcile
3. watch logs

**Environment :**
 - Strimzi version: [0.22.1]

**Comment by scholzj** [comment]
This just happens when you delete the resources in the middle of some calls and changes. Kube API does not have any transactions or resource locking. so I do not think there is an easy way to avoid it.

**Comment by tombentley** [comment]
I guess the length of a reconciliation has a bearing on how commonly this would be seen. If your reconciliations take a long time then it's much more likely you'd see this, since the window for the race between the operator and the kube GC is large. Maybe we should have a specific exception type for missing dependent resources like this, so that we only log them after checking for the continued existence of the CR.

**Comment by scholzj** [comment]
Triaged on 21.7.2022: This issue is used to track the behavior that an ongoin reconciliation does not end when the CR is deleted. This in general is a niche issue, but it happens. We need to find some solution which does not add too much complexity to the code given how much value it adds. Proposal needed.

#4869 is used to track the long timeout in KafkaRoller when this happens.
