### ISSUE TITLE
ZooKeeperAdmin lock contention on ClientCnxnSocketNetty connectLock

### ISSUE THREAD

**Issue by MikeEdgar** [strimzi/strimzi-kafka-operator#4939]
**Describe the bug**
Zookeeper client has an apparent deadlock occasionally when managing a high load of Kafka instances (observed with 50 instances). It is not clear whether the load causes the issue or simply increases the odds of it occurring. The thread dump below shows that the Strimzi worker thread is waiting during the close operation after the initial connect operation has timed out (lock held). My understanding of this is that it seems to be an upstream bug in either Zookeeper or Netty, but would ultimately require a dependency update here if that is the case.

**To Reproduce**
- Observed while following the steps details in #4869 

**Expected behavior**
- Zookeeper operations complete or timeout within a certain amount of time.

**Environment (please complete the following information):**
 - Strimzi version: `main` @ 96ad0bf

**Additional context**
Thread dump of the threads involved. The second and third threads are internal to the `ZooKeeperAdmin`.
- Strimzi worker thread (this would have been an event-loop thread prior to #4894), waiting on  `ClientCnxnSocketNetty#connectLock`
- ZooKeeper `SendThread` (holds the `ClientCnxnSocketNetty#connectLock` lock)
- ZooKeeper Epoll event loop thread, also waiting on  `ClientCnxnSocketNetty#connectLock`
```
&quot;vert.x-worker-thread-1&quot; #23 prio=5 os_prio=0 cpu=394.79ms elapsed=749.08s tid=0x000055dc93f7d800 nid=0x24 waiting on condition  [0x00007fe27c80d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  &lt;0x00000000fc0ac920&gt; (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.11/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.11/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.11/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.11/ReentrantLock.java:267)
	at org.apache.zookeeper.ClientCnxnSocketNetty.cleanup(ClientCnxnSocketNetty.java:205)
	at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1338)
	at org.apache.zookeeper.ClientCnxn$SendThread.cleanAndNotifyState(ClientCnxn.java:1276)
	at org.apache.zookeeper.ClientCnxn$SendThread.access$2800(ClientCnxn.java:805)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1534)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1512)
	at org.apache.zookeeper.ClientCnxn.close(ClientCnxn.java:1481)
	at org.apache.zookeeper.ZooKeeper.close(ZooKeeper.java:1415)
	- locked &lt;0x00000000fc0aaf58&gt; (a org.apache.zookeeper.admin.ZooKeeperAdmin)
	at org.apache.zookeeper.ZooKeeper.close(ZooKeeper.java:1437)
	at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.lambda$closeConnection$10(ZookeeperScaler.java:244)
	at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler$$Lambda$507/0x00000008405fc440.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.ContextImpl$$Lambda$209/0x00000008402ef040.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.ContextImpl$$Lambda$205/0x00000008402e9040.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11/ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

&quot;vert.x-eventloop-thread-0-SendThread(foo-x5o42xqw4dl1wb7-zookeeper-2.foo-x5o42xqw4dl1wb7-zookeeper-nodes.foo-x5o42xqw4dl1wb7.svc:2181)&quot; #110 daemon prio=5 os_prio=0 cpu=12.57ms elapsed=733.50s tid=0x000055dc93806800 nid=0x7a in Object.wait()  [0x00007fe275987000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.11/Native Method)
	- waiting on &lt;no object reference available&gt;
	at java.lang.Object.wait(java.base@11.0.11/Object.java:328)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:275)
	- waiting to re-lock in wait() &lt;0x00000000fd1bea08&gt; (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:411)
	at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
	at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
	at org.apache.zookeeper.ClientCnxnSocketNetty.cleanup(ClientCnxnSocketNetty.java:212)
	at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1338)
	at org.apache.zookeeper.ClientCnxn$SendThread.cleanAndNotifyState(ClientCnxn.java:1276)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1254)

&quot;epollEventLoopGroup-11-1&quot; #116 prio=10 os_prio=0 cpu=1404.77ms elapsed=733.10s tid=0x00007fe29907e800 nid=0x83 waiting on condition  [0x00007fe27507d000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.11/Native Method)
	- parking to wait for  &lt;0x00000000fc0ac920&gt; (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.11/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.11/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.11/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.11/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.11/ReentrantLock.java:267)
	at org.apache.zookeeper.ClientCnxnSocketNetty$1.operationComplete(ClientCnxnSocketNetty.java:151)
	at org.apache.zookeeper.ClientCnxnSocketNetty$1.operationComplete(ClientCnxnSocketNetty.java:146)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:653)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:691)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)
```
CC: @ppatierno , @rareddy , @k-wall

**Comment by k-wall** [comment]
Do you have the full output from jstack -l when this problem occurs?

**Comment by MikeEdgar** [comment]
@scholzj , @tombentley - I want to draw your attention to this issue to point out that the changes for #4894, while now executing the blocking IO on a worker thread, leave the door open for these threads to be stuck without the compensating effect of the liveness probe being unresponsive as it was when the event-loop threads were used for the IO.

**Comment by MikeEdgar** [comment]
@k-wall - I was able to capture a better thread dump. This log contains *three* occurrences of the problem.
[strimzi-jstack-1620754431.log](https://github.com/strimzi/strimzi-kafka-operator/files/6461014/strimzi-jstack-1620754431.log)

**Comment by k-wall** [comment]
@MikeEdgar you use the word deadlock in this issue's title, but not on ZOOKEEPER-4293, is that deliberate?

I don't understand the problem sufficiently well to know myself at the moment.   I think I see the  problem is that the channel's closefuture is never being completed even though close?  Do you have deeper insight?

I also notice here you mention that it is occuring during a connection failure, but you don't mention that on the Zookeeper issue.   Aside - can you tell if Netty's CONNECT_TIMEOUT_MILLIS is being configured?  Is there something in particular happening to zookeeper server when this problem occurs?

**Comment by MikeEdgar** [comment]
@k-wall 
> the channel's closefuture is never being completed even though close

That's right based on my observations. It wasn't clear enough to me where the future would be completed to know if it was a true deadlock, but I did now update the title of the ZK issue to indicate a possible deadlock.

> I also notice here you mention that it is occuring during a connection failure, but you don't mention that on the Zookeeper issue.

The client internally starts up a thread and attempts to connect immediately (and repeatedly) upon construction (the `SendThread`). The timeout is from a Strimzi perspective waiting for the ZooKeeperAdmin to be connected.

As far as I see Netty's `CONNECT_TIMEOUT_MILLIS` is not used, only `SO_LINGER=-1` and `TCP_NODELAY=true`. The only thing notable on the Zookeeper side is a single message that a handshake has failed. Even with that, the client should be able to recover though.

I have some additional options for gathering more log information which I will attach here and on the ZK issue.

**Comment by tombentley** [comment]
What `operationTimeoutMs` are you using in Strimzi? What's the message about the failed handshake?

**Comment by MikeEdgar** [comment]
@tombentley , timeout configured via `STRIMZI_OPERATION_TIMEOUT_MS` is `300000`.

Zookeeper message: `2021-06-09T09:05:16Z ERROR [nioEventLoopGroup-7-1] [NettyServerCnxnFactory:363] Unsuccessful handshake with session 0x0`

**Comment by scholzj** [comment]
So, is there anything to do about this on Strimzi side? My understanding is that the issue is in ZooKeeper and Strimzi just waits for ZooKeeper to be removed or to fix this. Or did I missed something?

**Comment by MikeEdgar** [comment]
@scholzj - that's right. At most this would be a dependency update in Strimzi.
