### ISSUE TITLE
Strimzi operator is not applying the changes that they pushed to their Kafka instance

### ISSUE THREAD

**Issue by mmurphy30** [strimzi/strimzi-kafka-operator#5269]
### Discussed in https://github.com/strimzi/strimzi-kafka-operator/discussions/5268

<div type='discussions-op-text'>

<sup>Originally posted by **mmurphy30** July  7, 2021</sup>
Running Strimz 0.17.0
Kafka 2.4

Operator is unable to reconcile kafka instances.   Seeing below errors in operator logs:

2021-07-07 22:48:11 ERROR AbstractOperator:124 - Reconciliation #4301(timer) Kafka(sc-soh-mlab01/sc-soh-kafka-mlab01): createOrUpdate failed
java.lang.NullPointerException: null
        at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:348) ~[io.strimzi.operator-common-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.ClusterCa.generateZkCerts(ClusterCa.java:139) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.model.ZookeeperCluster.generateNodesSecret(ZookeeperCluster.java:505) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.zkNodesSecret(KafkaAssemblyOperator.java:1347) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$reconcile$15(KafkaAssemblyOperator.java:267) ~[io.strimzi.cluster-operator-0.17.0.jar:0.17.0]
        at io.vertx.core.Future.lambda$compose$3(Future.java:360) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.Future.lambda$map$5(Future.java:429) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.5.jar:3.8.5]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

</div>

**Comment by scholzj** [comment]
How does this differ from the discussion? Why does one thing need to be discussed on multiple places? (Including Slack I guess)
