### ISSUE TITLE
Operation cannot be fulfilled errors during install

### ISSUE THREAD

**Issue by shawkins** [strimzi/strimzi-kafka-operator#5326]
**Describe the bug**
During an installation that is eventually successful, we see the Kafka with a NotReady condition with the message corresponding to:

```
2021-07-19 15:02:45 INFO  OperatorWatcher:40 - Reconciliation #0(watch) Kafka(mk-test-create/mk-test-create): Kafka mk-test-create in namespace mk-test-create was ADDED
2021-07-19 15:02:45 INFO  AbstractOperator:255 - Reconciliation #0(watch) Kafka(mk-test-create/mk-test-create): Kafka mk-test-create will be checked for creation or modification
2021-07-19 15:02:46 INFO  OperatorWatcher:40 - Reconciliation #1(watch) Kafka(mk-test-create/mk-test-create): Kafka mk-test-create in namespace mk-test-create was MODIFIED
2021-07-19 15:02:46 ERROR KafkaAssemblyOperator:483 - Reconciliation #0(watch) Kafka(mk-test-create/mk-test-create): Failed to update status
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.96.0.1/apis/kafka.strimzi.io/v1beta2/namespaces/mk-test-create/kafkas/mk-test-create/status. Message: Operation cannot be fulfilled on kafkas.kafka.strimzi.io "mk-test-create": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=kafka.strimzi.io, kind=kafkas, name=mk-test-create, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on kafkas.kafka.strimzi.io "mk-test-create": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:522) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:487) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:431) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleStatusUpdate(OperationSupport.java:305) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.updateStatus(BaseOperation.java:745) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.updateStatus(BaseOperation.java:86) ~[io.fabric8.kubernetes-client-5.3.0.jar:?]
        at io.strimzi.operator.common.operator.resource.CrdOperator.lambda$updateStatusAsync$2(CrdOperator.java:107) ~[io.strimzi.operator-common-0.23.0.jar:0.23.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**
We are creating the Kafka resource through another operator.  Our operator may make updates to the Kafka CR - that is probably the source of the 2021-07-19 15:02:46 modification.

**Expected behavior**
An error updating the status should not put the install into a NotReady condition.  It should be retried or another status update method should be used - there are now additional options in fabric8 kubernetes-client 5.4+ https://github.com/fabric8io/kubernetes-client/issues/3066

**Environment (please complete the following information):**
 - Strimzi version: 0.23
 - Installation method: fabric8 kubernetes-client
 - Kubernetes cluster: Kubernetes 1.20
 - Infrastructure: Minikube

**YAML files and logs**

**Additional context**

**Comment by scholzj** [comment]
I think this is fairly normal in Kubernetes - to not update changed resource and rather do another recocniliation. So I'm not sure I consider this a bug. Patching might have negative consequences if you are not sure what and where changed.

**Comment by shawkins** [comment]
It's normal that there can be a conflict on an update yes - the question is does this mean the Kafka is truly NotReady?  When we are monitoring the progress of the Kafka install and reporting our own status based upon the Kafka status, this will temporarily flip our status to an Error state - which does not seem correct.

**Comment by scholzj** [comment]
Well, `NotReady` means something went wrong during the reconciliation. We do not distinguish right now which part of it is not ready (which might be questionable for sure). But it is also one of the good ways how to report some potential issues to the users.
