### ISSUE TITLE
Create/post failure during install

### ISSUE THREAD

**Issue by shawkins** [strimzi/strimzi-kafka-operator#5357]
**Describe the bug**
With a kafka that is effective the same as shown in #5325 I saw another exception during the installation.  This was a fresh namespace - no prior instance with the same name existed in that namespace.

The install ultimately is successful.

**To Reproduce**
The kafka cr was created via our operator.

**Expected behavior**
Ideally this could be handled differently rather than producing a temporary error state.

**Environment (please complete the following information):**
 - Strimzi version: 0.23.0-1
 - Installation method: fabric8 kubernetes client
 - Kubernetes cluster: OpenShift 4.7
 - Infrastructure: aws

**YAML files and logs**

[strimzi-log.txt](https://github.com/strimzi/strimzi-kafka-operator/files/6871623/strimzi-log.txt)

**Comment by scholzj** [comment]
Maybe you should be more specific about what do you mean. The only error I see in the log suggests that either there was some problem with your Kubernetes API server or that someone / something was created the network policies in parallel. This might correspond for example to situation when multiple operators run and monitor the same CR.

**Comment by shawkins** [comment]
> Maybe you should be more specific about what do you mean.

I'm sorry if I'm not being clear - it's unexpected to see this exception.  Since this is a straight-forward installation - a fresh namespace and only a single strimzi operator running - it seems odd for the install to be temporarily in what appears to be an error state.

**Comment by scholzj** [comment]
I guess my main point was to clarify that this is the issue we talk about here:

```
2021-07-24 00:00:58 ERROR AbstractOperator:276 - Reconciliation #0(watch) Kafka(kafka/instance): createOrUpdate failed
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/apis/networking.k8s.io/v1/namespaces/kafka/networkpolicies. Message: networkpolicies.networking.k8s.io "instance-network-policy-zookeeper" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=networking.k8s.io, kind=networkpolicies, name=instance-network-policy-zookeeper, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=networkpolicies.networking.k8s.io "instance-network-policy-zookeeper" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:509) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:250) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:871) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:366) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:85) ~[io.fabric8.kubernetes-client-5.1.1.redhat-00001.jar:?]
        at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalCreate(AbstractResourceOperator.java:256) ~[io.strimzi.operator-common-0.23.0.managedsvc-redhat-00002.jar:0.23.0.managedsvc-redhat-00002]
        at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:109) ~[io.strimzi.operator-common-0.23.0.managedsvc-redhat-00002.jar:0.23.0.managedsvc-redhat-00002]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179) ~[io.vertx.vertx-core-4.0.3.redhat-00002.jar:4.0.3.redhat-00002]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[io.vertx.vertx-core-4.0.3.redhat-00002.jar:4.0.3.redhat-00002]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177) ~[io.vertx.vertx-core-4.0.3.redhat-00002.jar:4.0.3.redhat-00002]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.60.Final-redhat-00001.jar:4.1.60.Final-redhat-00001]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

That suggests that something created it while this operator instance was trying to create it. I'm not sure this can be fixed. There is no atomic _get and create_ operation in the Kubernetes API so a race condition like this can always happen. The question is why did it happened ... who is creating the network policies in parallel to the operator? Hence the idea of two operators misconfigured to operate the same resource in parallel which is something what can cause this. (I think this could create also something like #5362)

**Comment by shawkins** [comment]
This looks to the same causality as #5362 so resolving this as well.
