### ISSUE TITLE
Unable to upgrade strimzi-kafka-operator from version 0.20.0 to 0.24.0

### ISSUE THREAD

**Issue by soleimaniamir** [strimzi/strimzi-kafka-operator#5406]
Hello
I'm trying to upgrade strimzi-kafka-operator from version 0.20 to 0.24, this is list of my CRDs on cluster:
```
kubectl get crd
NAME                                                  CREATED AT
bgpconfigurations.crd.projectcalico.org               2021-08-08T13:27:20Z
bgppeers.crd.projectcalico.org                        2021-08-08T13:27:20Z
blockaffinities.crd.projectcalico.org                 2021-08-08T13:27:20Z
clusterinformations.crd.projectcalico.org             2021-08-08T13:27:20Z
felixconfigurations.crd.projectcalico.org             2021-08-08T13:27:20Z
globalnetworkpolicies.crd.projectcalico.org           2021-08-08T13:27:20Z
globalnetworksets.crd.projectcalico.org               2021-08-08T13:27:20Z
hostendpoints.crd.projectcalico.org                   2021-08-08T13:27:20Z
ipamblocks.crd.projectcalico.org                      2021-08-08T13:27:20Z
ipamconfigs.crd.projectcalico.org                     2021-08-08T13:27:20Z
ipamhandles.crd.projectcalico.org                     2021-08-08T13:27:20Z
ippools.crd.projectcalico.org                         2021-08-08T13:27:20Z
kafkabridges.kafka.strimzi.io                         2021-08-08T13:34:13Z
kafkaconnectors.kafka.strimzi.io                      2021-08-08T13:34:13Z
kafkaconnects.kafka.strimzi.io                        2021-08-08T13:34:13Z
kafkaconnects2is.kafka.strimzi.io                     2021-08-08T13:34:13Z
kafkamirrormaker2s.kafka.strimzi.io                   2021-08-08T13:34:11Z
kafkamirrormakers.kafka.strimzi.io                    2021-08-08T13:34:14Z
kafkarebalances.kafka.strimzi.io                      2021-08-08T13:34:10Z
kafkas.kafka.strimzi.io                               2021-08-08T13:34:09Z
kafkatopics.kafka.strimzi.io                          2021-08-08T13:34:13Z
kafkausers.kafka.strimzi.io                           2021-08-08T13:34:10Z
kubecontrollersconfigurations.crd.projectcalico.org   2021-08-08T13:27:20Z
networkpolicies.crd.projectcalico.org                 2021-08-08T13:27:20Z
networksets.crd.projectcalico.org                     2021-08-08T13:27:21Z
```
before upgrading, my CRDs version is:
```
kubectl get crd kafkas.kafka.strimzi.io -o jsonpath="{.spec.versions[*].name}"
v1beta1 v1alpha1
```
According to the instructions, I started to upgrade from 0.20.0 to 0.22.0 with `api-conversion-0.22.0` tool, first I converted all resources in the Kubernetes cluster:
```
.\api-conversion-0.22.0\bin\api-conversion.cmd  convert-resource  --all-namespaces 
Converting Kafka resource named kafka-cluster from namespace kafka
Kafka resource named kafka-cluster in namespace kafka has been converted
```
after that when I tried to upgrade CRDs, there is an error:
```
.\api-conversion-0.22.0\bin\api-conversion.cmd  crd-upgrade --debug
Changing stored version in all Strimzi CRDs to v1beta2:
Updating v1beta1 version of Kind KafkaTopic to be served but not stored
Updating v1alpha1 version of Kind KafkaTopic to be served but not stored
Updating KafkaTopic CRD
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.18.53.156:8443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/kafkatopics.kafka.strimzi.io. Message: CustomResourceDefinition.apiextensions.k8s.io "kafkatopics.kafka.strimzi.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1beta1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}, apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: must have exactly one version marked as storage version. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.versions, message=Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1beta1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}, apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: must have 
exactly one version marked as storage version, reason=FieldValueInvalid, additionalProperties={})], group=apiextensions.k8s.io, kind=CustomResourceDefinition, name=kafkatopics.kafka.strimzi.io, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=CustomResourceDefinition.apiextensions.k8s.io "kafkatopics.kafka.strimzi.io" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1beta1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}, apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: must have exactly one version marked as storage version, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:509)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:312)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:881)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$1(HasMetadataOperation.java:121)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:126)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:30)
        at io.strimzi.kafka.api.conversion.cli.CrdUpgradeCommand.changeStoredVersionInSpecForKind(CrdUpgradeCommand.java:100)
        at io.strimzi.kafka.api.conversion.cli.CrdUpgradeCommand.changeStoredVersionInSpec(CrdUpgradeCommand.java:112)
        at io.strimzi.kafka.api.conversion.cli.CrdUpgradeCommand.run(CrdUpgradeCommand.java:162)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at io.strimzi.kafka.api.conversion.cli.EntryCommand.main(EntryCommand.java:31)
```
My Kubernetes cluster version:
```
kubectl version     
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by scholzj** [comment]
You cannot run the conversion when you have only the `v1beta1` and `v1alpha1` installed. It needs the `v1beta2` as well. You need to do it after upgrading to 0.22 or at least after installing the 0.22 CRDs.

**Comment by soleimaniamir** [comment]
@scholzj How should I Upgrade to 0.22? I used `https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.22.0/api-conversion-0.22.0.zip` to upgrade resource and CRDs from 0.20.0 to 0.22.0.

**Comment by scholzj** [comment]
The upgrade to 0.22 does not require anything special. Only after the 0.22 upgrade / before the upgrade to Strimzi 0.23 or anything newer you need to convert the CRDs.

**Comment by scholzj** [comment]
@soleimaniamir Did you managed to complete the upgrade? Can this be closed?

**Comment by scholzj** [comment]
You would not necessarily see any difference visually. In some CRs (for example the `Kafka` CR) you might as there were somne structural changes. But you might not in KafkaTopic or KafkaUser.
