### ISSUE TITLE
TLS support for Zookeeper client in Topic Operator

### ISSUE THREAD

**Issue by mikekamornikov** [strimzi/strimzi-kafka-operator#5459]
**Is your feature request related to a problem? Please describe.**
We use Strimzi Topic Operator (TO) with an external AWS MSK cluster configured to allow only TLS connections to the brokers. Additionally MSK provides both Plaintext and TLS endpoints for Zookeeper. We managed to make TO work with TLS brokers in #2761. And it looks like the issue should be resolved after #5201.
Now it's time to switch to TLS Zookeeper endpoints. But simple switch to proper hosts/ports doesn't work. Looking through the code I don't even see anything related to TLS in both [configuration](https://github.com/strimzi/strimzi-kafka-operator/blob/a5d074ef8989573d5adf448c43ffc930c2a12391/topic-operator/src/main/java/io/strimzi/operator/topic/Config.java#L150-L157) and [client initialization](https://github.com/strimzi/strimzi-kafka-operator/blob/a5d074ef8989573d5adf448c43ffc930c2a12391/topic-operator/src/main/java/io/strimzi/operator/topic/zk/Zk.java#L23-L39).

**Describe the solution you'd like**
I'd like to see an analogue of `STRIMZI_TLS_ENABLED` and `STRIMZI_PUBLIC_CA` for Zookeeper in TO. In case of enabled TLS Zookeeper client should be properly configured. See:
- [Zookeeper SSL user guide](https://cwiki.apache.org/confluence/display/zookeeper/zookeeper+ssl+user+guide)
- [Related Strimzi discussion](https://github.com/strimzi/strimzi-kafka-operator/discussions/4289)

**Describe alternatives you've considered**
The following change to deployment works for me:
```yaml
- name: STRIMZI_JAVA_SYSTEM_PROPERTIES
  value: "-Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true"
```

**Additional context**
Without any tweaks I get lots of these:
```text
2021-08-18 11:40:48 DEBUG SaslServerPrincipal:80 - Canonicalized address to ip-***.us-west-2.compute.internal
2021-08-18 11:40:48 INFO  ClientCnxn:1112 - Opening socket connection to server z-1.***.c6.kafka.us-west-2.amazonaws.com/***:2182. Will not attempt to authenticate using SASL (unknown error)
2021-08-18 11:40:48 INFO  ClientCnxn:959 - Socket connection established, initiating session, client: /***:50486, server: z-1.***.c6.kafka.us-west-2.amazonaws.com/***:2182
2021-08-18 11:40:48 DEBUG ClientCnxn:1027 - Session establishment request sent on z-1.***.c6.kafka.us-west-2.amazonaws.com/***:2182
2021-08-18 11:40:48 INFO  ClientCnxn:1240 - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
```
And finally:
```text
2021-08-18 11:41:06 ERROR Main:55 - Error deploying Session
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'z-1.cxp-k8s-usw2-dev.rhr4zs.c6.kafka.us-west-2.amazonaws.com:2182,z-2.cxp-k8s-usw2-dev.rhr4zs.c6.kafka.us-west-2.amazonaws.com:2182,z-3.cxp-k8s-usw2-dev.rhr4zs.c6.kafka.us-west-2.amazonaws.com:2182' with timeout of 18000 ms
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131) ~[com.101tec.zkclient-0.11.jar:?]
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98) ~[com.101tec.zkclient-0.11.jar:?]
        at io.strimzi.operator.topic.zk.Zk.createSync(Zk.java:36) ~[io.strimzi.topic-operator-0.24.0.jar:0.24.0]
        at io.strimzi.operator.topic.zk.Zk.lambda$create$0(Zk.java:27) ~[io.strimzi.topic-operator-0.24.0.jar:0.24.0]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160) ~[io.vertx.vertx-core-4.1.0.jar:4.1.0]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[io.vertx.vertx-core-4.1.0.jar:4.1.0]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158) ~[io.vertx.vertx-core-4.1.0.jar:4.1.0]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.1.0.jar:4.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.65.Final.jar:4.1.65.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by mikekamornikov** [comment]
I see these ones in the log:
```
2021-08-20 07:27:24 WARN  X509Util:330 - zookeeper.ssl.keyStore.location not specified
2021-08-20 07:27:24 WARN  X509Util:354 - zookeeper.ssl.trustStore.location not specified
```
I guess in my case (no TLS auth) that's ok.

**Comment by mikekamornikov** [comment]
Not directly related but it looks like some inconsistency:
```java
    public static final String TC_ZK_CONNECT = "STRIMZI_ZOOKEEPER_CONNECT";
    public static final String TC_ZK_SESSION_TIMEOUT_MS = "STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS";
    public static final String TC_ZK_CONNECTION_TIMEOUT_MS = "TC_ZK_CONNECTION_TIMEOUT_MS";
```

**Comment by scholzj** [comment]
When deployed as part of the full Strimzi deployment, the TO is using a TLS sidecar with Stunnel to deal with ZooKeeper TLS. This is because for a long time ZooKeeper client had no support for TLS. So this could be an option for you. Our focus in Strimzi team on TO is to remove its need to use ZooKeeper completely (since it is removed from Kafka) and not just have it use TLS natively. So I do not think anyone from use will get to it. But if you want to open an PR, we will definitely review it.

The logs you have ... I'm not sure what exactly is the problem. I would read it as that either you do not have TLS enabled at all in the client or you have some networking issue (maybe some SG settings?)

> I guess in my case (no TLS auth) that's ok.

You should not need keystore without TLS client auth. The truststore will depend on the CA used by your Kafka cluster. ARAIK Amazon certificates signed by a public CA, so you might not need it either. But not 100% sure whether it is always the case with Amazon MSK.

**Comment by mikekamornikov** [comment]
Assuming TO works with the following JAVA_OPTS it's definitely about client not being configured for TLS:
```yaml
- name: STRIMZI_JAVA_SYSTEM_PROPERTIES
  value: "-Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true"
```
We'll migrate to Kafka 3+ once it's released by AWS MSK team. So everything ^^^ is a minor temporary thing.

**Comment by anil9030** [comment]
@scholzj ,
the TO is using a TLS sidecar with Stunnel to deal with ZooKeeper TLS .
 do we have any documentation on what changes need to be done or on configuring TLS sidecar?

I'm also getting below error on my zookeeper pods:

 ERROR Unsuccessful handshake with session 0x0 (org.apache.zookeeper.server.NettyServerCnxnFactory) [nioEventLoopGroup-7-2]
zookeeper
2021-12-28 11:39:27,205 WARN Exception caught (org.apache.zookeeper.server.NettyServerCnxnFactory) [nioEventLoopGroup-7-2]
zookeeper
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0000002d000000000000000000000000000075300000000000000000000000100000000000000000000000000000000000
zookeeper
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
zookeeper
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)


and the status of zookeeper is showing offline on our kafka UI , is it because of this certificate error?

**Comment by scholzj** [comment]
Sorry, @anil9030, I'm not entirely sure what exactly you mean and what exactly are you asking for.

**Comment by anil9030** [comment]
you have provided a workaround that  TO is using a TLS sidecar with Stunnel to deal with ZooKeeper TLS.
is there any documentation for this to follow and make changes?
hope you saw error in my zookeeper pod, is there any solution for it

**Comment by scholzj** [comment]
Triaged on 28. 4. 2022: The plan is to remove the dependency on ZooKeeper in Topic Operator rather then invest into improving how it communicates. But if someone strongly wants to have this feature and replace the sidecar and wants to contribute it, we are open to the PR.
