### ISSUE TITLE
TopicOperator not connecting to ZooKeeper

### ISSUE THREAD

**Issue by gambcl** [strimzi/strimzi-kafka-operator#5535]
**Describe the bug**
Deployed a fresh kafka cluster, with 3 kafka replicas and 3 zookeeper replicas.
All kafka and zookeeper replicase are Running and green, but the entity-operator is showing red with the following error message:
```
Startup probe failed: Get "http://10.36.0.3:8080/healthy": dial tcp 10.36.0.3:8080: connect: connection refused
Back-off restarting failed container
```

"get pods" reports entity-operator as Running or CrashLoopBackOff with 2/3 Ready.

When I look at the failed pod's logs I see
```
2021-09-07 22:32:59,67058 INFO  [main] Main:29 - TopicOperator 0.25.0 is starting
...
2021-09-07 22:33:01,35523 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1112 - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2021-09-07 22:33:01,35680 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:959 - Socket connection established, initiating session, client: /127.0.0.1:49952, server: localhost/127.0.0.1:2181
2021-09-07 22:33:11,37231 WARN  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1246 - Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77) ~[org.apache.zookeeper.zookeeper-3.5.9.jar:3.5.9]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:365) ~[org.apache.zookeeper.zookeeper-3.5.9.jar:3.5.9]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223) [org.apache.zookeeper.zookeeper-3.5.9.jar:3.5.9]
```

**To Reproduce**
1. Create 'kafka' namespace
2. Deploy Strimzi using YAML from curl "https://strimzi.io/install/latest?namespace=kafka"
3. View Kubernetes Dashboard

**Expected behavior**
All Strimzi containers should start successfully.

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.20.5
 - Infrastructure: Private VMs

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/main/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
Can you share the full logs? Definitely from the Topic Operator and from the tls-sidecar container in the same pod. But probably also from the ZooKeepers?

**Comment by gambcl** [comment]
Some more details in case they are useful...

I have 4 worker nodes in my cluster, the kafka brokers and zookeepers (3 of each) are all running on nodes 1, 2 & 3, however the entity-operator is being scheduled on node 4 (where there is no zookeeper running locally) and is trying to reach zookeeper on localhost:2181.

Do I need to force the scheduler to schedule the entity-operator onto a node where zookeeper is running? Or is there a way to make it contact zookeeper on a different node?

I have also opened the following ports in firewall on all worker nodes: 2181, 2888, 3888, 9092, 9093

I ran the report.sh script, please find zip file attached.
[report-08-09-2021_09-53-31.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7127546/report-08-09-2021_09-53-31.zip)

**Comment by gambcl** [comment]
Hello @scholzj thanks for getting back.

I have added the logs.
[logs.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7127622/logs.zip)

Thanks for any help, I'm pretty new to Kubernetes (although going well so far) and completely new to Kafka/Strimzi. I did search for any similar issues but didn't find anything that seemed to fit.

**Comment by scholzj** [comment]
It looks like the TLS sidecar cannot connect:

```
2021.09.08 08:51:33 LOG5[226]: Service [zookeeper-2181] accepted connection from 127.0.0.1:60608
2021.09.08 08:51:43 LOG3[226]: s_connect: s_poll_wait 10.104.139.96:2181: TIMEOUTconnect exceeded
2021.09.08 08:51:43 LOG3[226]: No more addresses to connect
2021.09.08 08:51:43 LOG5[226]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
```

And it looks like the same applies to the User Operator for example when connecting to Kafka:

```
2021-09-07 23:51:42 INFO  AdminMetadataManager:235 - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1631058632527, tries=1, nextAllowedTryMs=1631058702621) timed out at 1631058702521 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: fetchMetadata
```

Normally, it should not be an issue when the entity operator runs on a different node. It connects over the Kubernetes networking so it should not matter on which worker node it runs. But it looks like the Entity Operator is the only part having some issues. So maybe there is something wrong with the worker node it runs on? Maybe trying to schedule it on the other nodes can show if there is some issue with the node.

**Comment by gambcl** [comment]
If it helps, I am using the weave network layer on the Kubernetes cluster.
The node4 seems ok otherwise, there are other microservices running on it fine.

Would you be able to tell me how I force the entity-operator onto a specific node?

**Comment by scholzj** [comment]
I do not use Weave myself, but I do not see a reason why that would be a problem. But my best guess is that it would be something on the Kubernetes level - I do not see any other reason why this would not work and the rest of the Kafka cluster would be fine.

The TLS sidecar just encrypts the connection to ZooKeeper (since until recently ZooKeeper did not support TLS natively). But the Kafka connection in the User Operator does not go through it. In theory, you could break the client certificates used by the entity operator. But I do not think that would cause timeout errors. That suggests something lower on the network level.

You should be able to configure the node affinit of the entity operator pod using something like this:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
spec:
  # ...
  entityOperator:
    # ...
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                    - fast-network
    # ...
```

**Comment by gambcl** [comment]
Thanks for that. I can see it starting now on node1, where there is definitely a zookeeper running but it still gives the same error.
[logs-from-topic-operator-in-myproject-kafka-cluster-entity-operator-57898d8b6f-2lv8x.txt](https://github.com/strimzi/strimzi-kafka-operator/files/7128585/logs-from-topic-operator-in-myproject-kafka-cluster-entity-operator-57898d8b6f-2lv8x.txt)

**Comment by scholzj** [comment]
Is the same error also in the tls-sidecar container log?

**Comment by gambcl** [comment]
Ok something weird going on. I came back from lunch to check the tls-sidecar log, and it was all green across the board.
I have just killed the entity-operator pod to see if it repeats, and now I'm getting errors again.
Fresh logs attached.
Could there be some weird race condition going on?
[logs.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7129483/logs.zip)

**Comment by gambcl** [comment]
After 6 restarts, it has gone green again.
Is this normal?
[logs.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7129748/logs.zip)

**Comment by scholzj** [comment]
Well, if you check the TLS sidecar from the last archive, you can see that some connections are timing out and some are getting through. I have seen Kafka or ZooKeeper behave weirdly, but not in the way that it affects only some components like this. You would for example see that everything starts failing because ZooKeeper stops working etc. Maybe something somewhere running out of resources or out of some limits, but I have no specific ideas since I never saw this and do not know your environment I'm afraid.

**Comment by gambcl** [comment]
Ok, thanks for the help, I'll keep playing with it.

**Comment by fanux** [comment]
```
[root@iZ2zeaxzynknewlf0dkin9Z ~]# kubectl get pod -n kafka
NAME                                          READY   STATUS    RESTARTS      AGE
my-cluster-entity-operator-67cbb8f86f-vhkl8   2/3     Running   2 (87s ago)   5m47s
```
```
kubectl logs -n kafka         my-cluster-entity-operator-67cbb8f86f-vhkl8 -c topic-operator
```
```
2022-04-19 08:37:30,41645 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 30675 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194) ~[?:?]
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998) ~[?:?]
	at io.apicurio.registry.utils.ConcurrentUtil.get(ConcurrentUtil.java:35) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.apicurio.registry.utils.ConcurrentUtil.get(ConcurrentUtil.java:27) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.apicurio.registry.utils.ConcurrentUtil.result(ConcurrentUtil.java:54) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.strimzi.operator.topic.Session.lambda$start$9(Session.java:198) ~[io.strimzi.topic-operator-0.28.0.jar:0.28.0]
	at io.strimzi.operator.topic.Session$$Lambda$278/0x0000000840327040.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase$$Lambda$294/0x0000000840321440.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
```
I got the issue too.

**Comment by tooptoop4** [comment]
@gambcl did u solve?
