### ISSUE TITLE
Invalid DNS name

### ISSUE THREAD

**Issue by Fattouh92** [strimzi/strimzi-kafka-operator#5621]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
Apply a new kafka resource gives me the error
```
2021-09-28 06:42:27 WARN  AbstractOperator:481 - Reconciliation #27(timer) Kafka(strimzi/my-cluster): Failed to reconcile
java.lang.IllegalArgumentException: Invalid DNS name: my-cluster-zookeeper-client.strimzi.svc.cluster.local kubernetes.default.strimzi.svc.cluster.local
	at io.strimzi.certs.Subject$Builder.addDnsName(Subject.java:47) ~[io.strimzi.certificate-manager-0.25.0.jar:0.25.0]
	at io.strimzi.operator.cluster.model.ClusterCa.lambda$generateZkCerts$0(ClusterCa.java:132) ~[io.strimzi.cluster-operator-0.25.0.jar:0.25.0]
	at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:422) ~[io.strimzi.operator-common-0.25.0.jar:0.25.0]
	at io.strimzi.operator.cluster.model.ClusterCa.generateZkCerts(ClusterCa.java:143) ~[io.strimzi.cluster-operator-0.25.0.jar:0.25.0]
	at io.strimzi.operator.cluster.model.ZookeeperCluster.generateCertificates(ZookeeperCluster.java:486) ~[io.strimzi.cluster-operator-0.25.0.jar:0.25.0]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$zkGenerateCertificates$54(KafkaAssemblyOperator.java:1441) ~[io.strimzi.cluster-operator-0.25.0.jar:0.25.0]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160) ~[io.vertx.vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[io.vertx.vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158) ~[io.vertx.vertx-core-4.1.2.jar:4.1.2]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.1.2.jar:4.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**To Reproduce**
1. Create and Apply Custom Resource Kafka
2. See error in operator logs

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.20
 - Infrastructure: AliCloud

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kmon-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Additional context**

**Comment by scholzj** [comment]
I think this is related to #5444. Until that is released, you should be able to override it by setting the `KUBERNETES_SERVICE_DNS_DOMAIN` environment variable in the operator to whatever your cluster DNS suffix is (e.g. `cluster.local`)

**Comment by Fattouh92** [comment]
@scholzj I am not sure. I tried the following from inside one of the cluster pods
```
[strimzi@strimzi-cluster-operator-687fdd6f77-6rspz strimzi]$ cat /etc/resolv.conf
nameserver 172.25.0.10
search strimzi.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
[strimzi@strimzi-cluster-operator-687fdd6f77-6rspz strimzi]$ getent hosts kubernetes.default
172.25.0.1      kubernetes.default.svc.cluster.local kubernetes.default.strimzi.svc.cluster.local
```

**Comment by Fattouh92** [comment]
it was related to https://github.com/strimzi/strimzi-kafka-operator/issues/5519 I disable sidecar injection and the operator worked just fine

**Comment by scholzj** [comment]
Ok, great. Can we close this then?
