### ISSUE TITLE
Kafka Streams API is not working with tracing and Kafka 3.0.0

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#5680]
When we try to use Kafka Streams application together with Jaeger tracing and Kafka 3.0.0, it always ends with exception:
```
2021-10-05 07:01:55.458.81512692563118 DEBUG InternalTopologyBuilder:1339 - No source topics using pattern subscription found, initializing consumer's subscription collection.
Exception in thread "main" java.lang.UnsupportedOperationException: Implementations of KafkaClientSupplier should implement the getAdmin() method.
	at org.apache.kafka.streams.KafkaClientSupplier.getAdmin(KafkaClientSupplier.java:40)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:846)
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:711)
	at Main.main(Main.java:48)
```

It seems that OpenTracing doesn't support Kafka 3.0.0

**Comment by im-konge** [comment]
PR with adding support for Kafka 3.0.0 opened by @scholzj  [Opentracing-contrib/java-kafka-client#91](https://github.com/opentracing-contrib/java-kafka-client/pull/91).

**Comment by hsargsyan** [comment]
Any updates on this?

**Comment by scholzj** [comment]
Triaged on 21.7.2022: OpenTracing moved into OpenTelemetry and it looks like the PR with the Kafka 3.0 support will not be merged/released anymore. The plan is to migrate to OpenTelemetry which is the replacement for OpenTracing. Strimzi does not provide any direct support for OpenTracing in its operands, it was only used in system tests. This PR should be closed and over time we should migrate to OpenTelemetry.
