### ISSUE TITLE
Strimzi Pod goes to Crashloop state, if STRIMZI_NAMESPACE is configured with around 15 namespaces

### ISSUE THREAD

**Issue by shivakumargowda12** [strimzi/strimzi-kafka-operator#5853]
2021-11-08 06:12:18 INFO  AbstractOperator:219 - Reconciliation #1(watch) Kafka(namespace1/test-kafka-role-cluster): Kafka test-kafka-role-cluster will be checked for creation or modification
2021-11-08 06:12:18 INFO  AbstractOperator:219 - Reconciliation #2(watch) Kafka(space1project/test-kafka-role-cluster): Kafka test-kafka-role-cluster will be checked for creation or modification
2021-11-08 06:12:19 WARN  VersionUsageUtils:60 - The client is using resource type 'poddisruptionbudgets' with unstable version 'v1beta1'
2021-11-08 06:12:47 ERROR Main:153 - **Cluster Operator verticle in namespace namespace2 failed to start**
**io.fabric8.kubernetes.client.KubernetesClientException: not ready after 10 SECONDS**
        at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:176) ~[io.fabric8.kubernetes-client-5.6.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.waitUntilReady(WatcherWebSocketListener.java:120) ~[io.fabric8.kubernetes-client-5.6.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:80) ~[io.fabric8.kubernetes-client-5.6.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:702) ~[io.fabric8.kubernetes-client-5.6.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:675) ~[io.fabric8.kubernetes-client-5.6.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:88) ~[io.fabric8.kubernetes-client-5.6.0.jar:?]
        at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResourceOperator.java:61) ~[io.strimzi.operator-common-0.25.0.jar:0.25.0]
        at io.strimzi.operator.common.AbstractOperator.lambda$createWatch$18(AbstractOperator.java:440) ~[io.strimzi.operator-common-0.25.0.jar:0.25.0]
        at io.strimzi.operator.common.Util.lambda$async$0(Util.java:65) ~[io.strimzi.operator-common-0.25.0.jar:0.25.0]

Looks like timeout issue. Is there anyway, we can override this timeout value of 10 seconds ?

**Comment by scholzj** [comment]
Discussed in https://cloud-native.slack.com/archives/CMH3Q3SNP/p1636353435326100

**Comment by shivakumargowda12** [comment]
@scholzj , thank you

**Comment by vutkin** [comment]
Hi @scholzj , I am unable login into slack workspace, is any solution? I have same problem.

**Comment by scholzj** [comment]
Watching individual namespaces is fairly expensive. You can try to increase the operator resources, but I think the best way is to just configure the operator to watch the whole cluster.

**Comment by vutkin** [comment]
By the way how to get an invite to this slack channel?
Increasing resources didn't help by the way.

**Comment by vutkin** [comment]
Upgrading strimzi is always a challenge:( Why it was not a fairly expensive on 0.23.0 version? It works like a charm.

**Comment by scholzj** [comment]
> By the way how to get an invite to this slack channel?

You should just go to http://slack.cncf.io/ and register

> Increasing resources didn't help by the way.

Well, not sure why it wouldn't help. But I never tried anything like 10 or 15 namespaces. One thing to keep in mind is that each namespace is basically running a separate operator. So the resources increase might need to be significant.

**Comment by vutkin** [comment]
Well, I've got an error:

```
 helm upgrade --install strimzi strimzi/strimzi-kafka-operator --atomic --wait --timeout 1800s --namespace strimzi --values strimzi/values.yaml --version 0.25.0 --set 'watchAnyNamespace=true,watchNamespaces={}'
Error: UPGRADE FAILED: release strimzi failed, and has been rolled back due to atomic being set: no ClusterRoleBinding with the name "strimzi-cluster-operator-entity-operator-delegation" found
```

**Comment by scholzj** [comment]
I have no clue about Helm Charts, sorry. So I'm not sure what this does or what does the error mean.
