### ISSUE TITLE
TLS enabled listeners with Strimzi generated Private CAs use the cluster keystore in listener

### ISSUE THREAD

**Issue by aszac** [strimzi/strimzi-kafka-operator#5875]
**Bug description**
We have two TLS authenticated listeners in our cluster: one internal listener and other external listener type NodePort.
The cluster and client CAs are generated by Stimzi. We have noticed that the broker config for the listeners uses cluster.keystore.p12 as the ssl.keystore.location. This keystore does not contain the certificate and the private key for the client CA, therefore the authentication with the clients fail. The clients.keystore.p12 file containing the private key and certificate for the clients CA is not present on the brokers.

> listener.name.internal-9030.ssl.client.auth=required
> listener.name.internal-9030.ssl.truststore.location=/tmp/kafka/clients.truststore.p12
> listener.name.internal-9030.ssl.truststore.password=***
> listener.name.internal-9030.ssl.truststore.type=PKCS12
> ​
> listener.name.internal-9030.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
> listener.name.internal-9030.ssl.keystore.password=***
> listener.name.internal-9030.ssl.keystore.type=PKCS12
> ​
> listener.name.external-9031.ssl.client.auth=required
> listener.name.external-9031.ssl.truststore.location=/tmp/kafka/clients.truststore.p12
> listener.name.external-9031.ssl.truststore.password=***
> listener.name.external-9031.ssl.truststore.type=PKCS12
> ​
> listener.name.external-9031.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
> listener.name.external-9031.ssl.keystore.password=***
> listener.name.external-9031.ssl.keystore.type=PKCS12

We have work around the issue by creating a new secret containing the clients-ca and clients-ca-cert secret contents and adding the 

> configuration:
>     brokerCertChainAndKey:

section (intended to be used when using externally managed CAs) to the listeners using the newly created secret. 

**To Reproduce**
1. Create a kafka broker with a listener

>       - name: tls
>         port: 9093
>         type: internal
>         tls: true
>         authentication:
>           type: tls

2. Check the broker config for the listener(listener.name.external-9093.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12) 
3. Inspect the cluster.keystore.p12 with "keytool -list -v -keystore /tmp/kafka/cluster.keystore.p12" command to see the contents of the keystore.
4. Confirm the keystore does not have entries for client CAs

**Expected behavior**
The correct behaviour would be to have a clients.keystore.p12 generated and used in the broker listener config when using clients CAs generated by strimzi.

**Environment (please complete the following information):**
 - Strimzi version: 0.26.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.18
 - Infrastructure: Amazon EKS

**YAML files and logs**

Stack trace thrown by the kafka console consumer when trying to connect to the broker:
`org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:245)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:480)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1261)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1230)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
        at kafka.tools.ConsoleConsumer$ConsumerWrapper.receive(ConsoleConsumer.scala:443)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:102)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:76)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:53)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
        ... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 35 more`

**Comment by scholzj** [comment]
* The `ssl.keystore...` options is used to configure the server TLS certificate => i.e. a server certificate signed by the Cluster CA. That is what is in the `cluster.keystore.p12`. So that is correctly configured. 
* The `ssl.truststore...` options contain the public keys of the CAs which signed the user certificates which will be allowed to connect => i.e. the public key of the Clients CA. The private key is not needed here, because it just verifies the certificates. So this is configured correctly as well.
* The listener certificate (whcih you configure with `brokerCertChainAndKey`) is a custom server certificate. It is used for `ssl.keystore...` and has again nothing to do with the client authentication or with the Clients CA.

The error you listed seems to suggest that instead of Strimzi badly configured the broker, you badly configured your client. Normally, this error means that it does not trust the server certificate. So you need to add the public key of the CA which signed it to the clients truststore and configure the truststore in the client. If you use the Strimzi certs, the public key for the truststore will be in the secret named something like `<cluster-name>-cluster-ca-cert`. If you use custom server certificate (i.e. using `brokerCertChainAndKey`) you need to know yourself which CA signed it and use that CA public certificate.

**Comment by aszac** [comment]
Thank you! I must have been confused by the fact that when Strimzi creates the client user secrets it adds the client CA together with the certificate and the private key.

**Comment by scholzj** [comment]
Ahh, ok. Yeah, that is a bit confusing sometimes. The Clients CA is there since some clients need(ed) it to be able to use the user certificate (to have the full chain there).
