### ISSUE TITLE
Cluster Reconciliation Deadlock on Invalid inter.broker.protocol.version / log.message.format.version

### ISSUE THREAD

**Issue by fuchstim** [strimzi/strimzi-kafka-operator#6048]
**Describe the bug**
Whilst upgrading Kafka to v2.8.0, due to a misunderstanding I entered `2.8-IV1` as the `inter.broker.protocol.version` and `log.message.format.version` config (see YAML extract below).

Being an invalid version number, this resulted in the operator being unable to complete reconciliation (see stack trace below).

However, trying to roll back / fix this mistake proved a bit difficult, because even after updating and applying the Kafka Object to fix the bad version string, the operator still refused to complete reconciliation.

Finally what resolved this issue for us was to manually edit the `strimzi.io/log-message-format-version` and `strimzi.io/inter-broker-protocol-version` annotations on the existing Kafka Broker pods (edited to be a valid version number), allowing the operator to successfully complete reconciliation and roll back the change.

**To Reproduce**
1. Deploy a Strimzi Kafka resource with an invalid inter.broker.protocol.version / log.message.format.version version number
2. Wait for the operator to trigger a periodic reconciliation
3. Reconciliation fails, as expected
4. Rolling back config change is impossible without manual intervention

**Expected behavior**
Strimzi should validate the version number being configured on the `strimzi.io/log-message-format-version` and `strimzi.io/inter-broker-protocol-version` annotations *before* starting to update resources, to avoid this deadlock scenario

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1, 0.23.0, 0.26.0, 0.26.1
 - Installation method: Helm Chart
 - Kubernetes cluster: Kubernetes v1.21.2-eks
 - Infrastructure: EKS

**YAML files and logs**
Kafka Cluster YAML:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}-cluster
  namespace: {{ .Release.Namespace }}
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple
      superUsers: []
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8-IV1"
      inter.broker.protocol.version: "2.8-IV1"
    storage:
      type: ephemeral
    jmxOptions: {}
```

Operator Log:
```
2021-12-16 08:44:09 INFO  ClusterOperator:118 - Triggering periodic reconciliation for namespace kafka                                                                                                           
2021-12-16 08:44:09 INFO  AbstractOperator:219 - Reconciliation #1384(timer) Kafka(kafka/kafka-cluster): Kafka kafka-cluster will be checked for creation or modification                                        
2021-12-16 08:44:09 ERROR AbstractOperator:240 - Reconciliation #1384(timer) Kafka(kafka/kafka-cluster): createOrUpdate failed                                                                                   
java.lang.NumberFormatException: For input string: "8-IV1"                                                                                                                                                       
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]                                                                                                                      
    at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]                                                                                                                                                       
    at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]                                                                                                                                                       
    at io.strimzi.operator.cluster.model.KafkaVersion.compareDottedVersions(KafkaVersion.java:430) ~[io.strimzi.cluster-operator-0.26.1.jar:0.26.1]                                                              
    at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$getKafkaClusterDescription$57(KafkaAssemblyOperator.java:1517) ~[io.strimzi.cluster-operator-0.26.1.jar:0.2
    at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                               
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                               
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                              
    at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                             
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                               
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                              
    at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                             
    at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                               
    at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]                                                                                      
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]                                                          
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]                                                  
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.68.Final.jar:4.1.68.Final]                                                                                     
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]                                                        
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]                                                                           
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]                                                               
    at java.lang.Thread.run(Thread.java:829) [?:?]                                                                                                                                                               
2021-12-16 08:44:09 WARN  AbstractOperator:481 - Reconciliation #1384(timer) Kafka(kafka/kafka-cluster): Failed to reconcile
```

**Comment by scholzj** [comment]
Can you pease provide a full log from the operator? I guess you might not have it on DEBUG level which is fine, but having the full log from the time you did the first change would be important to understand this. Thanks.

**Comment by fuchstim** [comment]
For sure, find the full logs below. I've remove reconciliation runs 21 to 1386 because they were repeating the same log lines.

[strimzi-cluster-operator-logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/7726122/strimzi-cluster-operator-logs.txt)

**Comment by fuchstim** [comment]
As you can see, reconciliation runs 1-5 completed successfully, until the config change was made causing subsequent runs to fail.
After manually editing the Kafka pod annotations, reconciliation runs 1387 onwards succeeded.

**Comment by scholzj** [comment]
Great, thanks. We will have a look at it.
