### ISSUE TITLE
Cluster operator failed to renew auto-generated certs leading to broker failure

### ISSUE THREAD

**Issue by mariusstaicu** [strimzi/strimzi-kafka-operator#6649]
**Describe the bug**

We are using a strimzi controlled kafka cluster for more than 3 years in production. 
Yesterday, the operator generated certificates expired (they were created on 06-04-2019) and this caused the cluster to stop working.
Also we were using all prometheus alerting rules with kafka-exporter & kafka metrics defined in documentation and no alert went off.
This deployment was first created using operator version 0.14.0 which I guess first generated the certificates. 
Then it was upgraded step by step up to 0.26.1.

**Expected behavior**
We were expecting those certificates to auto renew since they are auto generated by the operator.

**Environment (please complete the following information):**
 - Strimzi version: 0.26.1
 - Installation method: YAML files
 - Kubernetes cluster: GKE 1.20.15-gke.1000
 - Infrastructure: GCP

**YAML files and logs**

Cluster yaml file:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kf
  namespace: infrastructure
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      delete.topic.enable: true
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.8"
    storage:
      type: persistent-claim
      size: 200Gi
      deleteClaim: false
    jvmOptions:
      gcLoggingEnabled: false
      "-Xmx": 1g
      "-Xms": 1g
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    resources:
      requests:
        memory: "5Gi"
        cpu: "2"
      limits:
        memory: "5Gi"
        cpu: "2"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kf-kafka-metrics
          key: kf-kafka-metrics.yml
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 8Gi
      deleteClaim: false
    resources:
      requests:
        memory: "1Gi"
        cpu: "400m"
      limits:
        memory: "1Gi"
        cpu: "400m"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kf-zookeeper-metrics
          key: kf-zookeeper-metrics.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    logging: info
    enableSaramaLogging: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
```

Kafka logs:

```
2022-04-06 12:18:13,124 INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Failed authentication with /10.56.25.25 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-1-ListenerName(REPLICATION-9091)-SSL-3]
```

Zookeeper logs after restarting zk pod:
```bash
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:478)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:700)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:411)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:375)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1074)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1008)
	at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1565)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1579)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1463)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1290)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1337)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	... 17 more
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:263)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:135)
	at org.apache.zookeeper.common.ZKTrustManager.checkClientTrusted(ZKTrustManager.java:88)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:682)
	... 32 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:224)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:144)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:83)
	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
	... 39 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Apr 06 12:21:35 GMT 2022
	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:675)
	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 44 more
```

**Additional context**
I believe that certificates were never renewed because they expired exactly 3 years after cluster was created.

There is nothing in the logs of the operator that resembles anything other than normal operation. I know renewal interval is by default 30 days before expiration now. So I checked 30 days prior and nothing out of the ordinary.

Is there anything that can be done to monitor the certificate expiration ? If it fails auto-renewal at least we can try to do it manually.
Thanks

**Comment by scholzj** [comment]
Do you have the operator logs from the time the renewal was expected to happen? They will be needed to do any kind of investigation. I'm not aware of any known issues in the renewal in 0.26.

**Comment by scholzj** [comment]
With _Do you have the operator logs from the time the renewal was expected to happen?_ I mean if you can share them.

**Comment by mariusstaicu** [comment]
No, unfortunately retention of our logs is only 30 days and now we are 31 days away from th

**Comment by mariusstaicu** [comment]
what happens if the operator is down when time comes to renew certificates ? will it retry once it is back on  ?

**Comment by scholzj** [comment]
In every reconciliation, it will check if the certificates are within the renewal period and if they are it will try to renew them. So if you have the renewalDays setting set to 30 days, it would need to be down for 30 days. But if it is down only during the first day of the 30 day renewal period, that is no issue and it will renew it a day later still 29 days before the expiration. The maintenance windows are handled in a similar way.

**Comment by mariusstaicu** [comment]
ok, thanks
certailny wasn't down for more than a few seconds

**Comment by scholzj** [comment]
Yeah, that should not matter ... at least by design.

**Comment by scholzj** [comment]
Triaged on 25.8.2022: Without the logs from when it was expected to renew, it is hard to analyze why did the renewal not happen. did you manage to reproduce this (for example with some shorter certificate validity period) with a recent Strimzi version?

**Comment by mariusstaicu** [comment]
No, I didn't. We have a certificate monitoring solution in place and if this happens again, I will reopen a ticket.
We also upgraded to a more recent version of the operator.
I will close this issue.

**Comment by jim-cooley** [comment]
We have had a similar issue with 0.31.1, where one node failed to renew the certs and for some (yet unknown) reason caused the cluster to be inaccessible.  we're still troubleshooting, not sure if there are logs from the renewal as they too are > 30d old.

**Comment by scholzj** [comment]
That sounds weird. The certificates are renewed by the operator. So I would be quite curious if just one of them was not renewed or if just the broker was not rolled. The first seems unlikely. But if it was the second, just a restart of the pod should fix it.

And in general yes, my expectation would be that one node would be out - this can of course cause issues to rolling updates etc. But it should not take down the whole cluster.

**Comment by jim-cooley** [comment]
from looking at the metrics, it was the active controller that failed to update the cert and didn't fail over (split-brain?).  there seems to be some intermittent network issues in the cluster; most likely the root cause.  I've annotated the strimzipodset for a rolling restart which it is working through now.  we also restarted the operator to be sure.

**Comment by elvis-cai** [comment]
Hi @scholzj  we got the simliar issue yesterday, and the renew only occur after we restart the operator, we did have logs could share it out, if you don't mind checking here's the logs between Sep 30 to Oct 4. the cert expired on Nov 1 so I would assume renew occur since Oct 1
[strimzi-cluster-operator-log.txt](https://github.com/user-attachments/files/18000909/strimzi-cluster-operator-log.txt)

 
 also attached two screenshot with old and new cert 
<img width="476" alt="image" src="https://github.com/user-attachments/assets/d125f63d-caaf-478c-addf-7a9e909f8ebe">
<img width="748" alt="image" src="https://github.com/user-attachments/assets/9ea7db53-681e-48f2-b2b7-8a6b1a6a6d40">

**Comment by scholzj** [comment]
It looks like there is a stuck reconciliation:
```
2024-10-04 13:58:04 INFO  AbstractOperator:380 - Reconciliation #150263(timer) Kafka(strimzi/kafka-operator): Reconciliation is in progress
```

But it is already there at the start of the log, so there is nothing to suggest what might have caused it. What Strimzi version is this?

**Comment by elvis-cai** [comment]
> It looks like there is a stuck reconciliation:
> 
> ```
> 2024-10-04 13:58:04 INFO  AbstractOperator:380 - Reconciliation #150263(timer) Kafka(strimzi/kafka-operator): Reconciliation is in progress
> ```
> 
> But it is already there at the start of the log, so there is nothing to suggest what might have caused it. What Strimzi version is this?

thanks @scholzj for the quick reply, we are using chart version 0.35.1 along with kafka 3.3.2, let me check if I can find more logs before stuck

**Comment by elvis-cai** [comment]
kk, I found it stuck since Sep 18 
[Uploading strimzi-operator-stuck-sep-18.txt…]()

**Comment by elvis-cai** [comment]
kk, I found it stuck since Sep 18
[strimzi-operator-stuck-sep-18.txt](https://github.com/user-attachments/files/18001123/strimzi-operator-stuck-sep-18.txt)

**Comment by elvis-cai** [comment]
[strimzi-operator-stuck-sep-18(full).txt](https://github.com/user-attachments/files/18001130/strimzi-operator-stuck-sep-18.full.txt)
sorry for the filtered one above, here's the whole log of the operator

**Comment by scholzj** [comment]
0.35 is pretty old, but if there would be something to catch on we can see if it is still relevant part of code. But the log, unfortunately, does not seem to have anything interesting inside - no exception, no error, nothing 😞. It just starts the reconciliation and gets _stuck_. In the past, there often was some unhandled exception or something that got it stuck. Those are things that we can fix. But there is nothing to get started from here.

But in any case, thanks for providing the log - in most cases people do not have the logs anymore so we actually do not know if it was similar or if it had some more obvious errors or not.

Maybe if it happens to you again, you can try to get a thread dump first before restarting the operator. That might also show us something useful 🤔.

**Comment by elvis-cai** [comment]
> 0.35 is pretty old, but if there would be something to catch on we can see if it is still relevant part of code. But the log, unfortunately, does not seem to have anything interesting inside - no exception, no error, nothing 😞. It just starts the reconciliation and gets _stuck_. In the past, there often was some unhandled exception or something that got it stuck. Those are things that we can fix. But there is nothing to get started from here.
> 
> But in any case, thanks for providing the log - in most cases people do not have the logs anymore so we actually do not know if it was similar or if it had some more obvious errors or not.
> 
> Maybe if it happens to you again, you can try to get a thread dump first before restarting the operator. That might also show us something useful 🤔.

will do, thanks for helping check logs. 
This happens in prod only, probably because we haven't restarted the kafka/zk or operator for a long time, in staging env, we did not see it since the operator or kafka/zk pod will be restarted randomly by node pool change, in prod in are using static node pool
