### ISSUE TITLE
Startup probe faile

### ISSUE THREAD

**Issue by fanux** [strimzi/strimzi-kafka-operator#6701]
**Describe the bug**
The my-cluster-entity-operator can't start, one container start failed:
```
[root@iZ2zeaxzynknewlf0dkin9Z ~]# kubectl get pod -n kafka -owide
NAME                                          READY   STATUS    RESTARTS      AGE   IP               NODE                      NOMINATED NODE   READINESS GATES
my-cluster-entity-operator-67cbb8f86f-vhkl8   2/3     Running   8 (81s ago)   21m   100.84.137.8     iz2zeaxzynknewlf0dkinbz   <none>           <none>
my-cluster-kafka-0                            1/1     Running   0             32m   100.73.225.10    iz2zeaxzynknewlf0dkindz   <none>           <none>
my-cluster-kafka-1                            1/1     Running   0             32m   100.121.221.73   iz2zeaxzynknewlf0dkincz   <none>           <none>
my-cluster-kafka-2                            1/1     Running   0             32m   100.84.137.7     iz2zeaxzynknewlf0dkinbz   <none>           <none>
my-cluster-zookeeper-0                        1/1     Running   0             34m   100.121.221.71   iz2zeaxzynknewlf0dkincz   <none>           <none>
my-cluster-zookeeper-1                        1/1     Running   1 (34m ago)   34m   100.73.225.9     iz2zeaxzynknewlf0dkindz   <none>           <none>
my-cluster-zookeeper-2                        1/1     Running   0             34m   100.84.137.5     iz2zeaxzynknewlf0dkinbz   <none>           <none>
strimzi-cluster-operator-7599bc57cb-2dt5m     1/1     Running   0             63m   100.84.137.3     iz2zeaxzynknewlf0dkinbz   <none>           <none>
```
Describe the pod:
```
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  20m                 default-scheduler  Successfully assigned kafka/my-cluster-entity-operator-67cbb8f86f-vhkl8 to iz2zeaxzynknewlf0dkinbz
  Normal   Pulled     20m                 kubelet            Container image "quay.io/strimzi/kafka:0.28.0-kafka-3.1.0" already present on machine
  Normal   Created    20m                 kubelet            Created container tls-sidecar
  Normal   Started    20m                 kubelet            Started container tls-sidecar
  Normal   Pulled     20m                 kubelet            Container image "quay.io/strimzi/operator:0.28.0" already present on machine
  Normal   Created    20m                 kubelet            Created container user-operator
  Normal   Started    20m                 kubelet            Started container user-operator
  Normal   Killing    18m                 kubelet            Container topic-operator failed startup probe, will be restarted
  Normal   Pulled     18m (x2 over 20m)   kubelet            Container image "quay.io/strimzi/operator:0.28.0" already present on machine
  Normal   Created    18m (x2 over 20m)   kubelet            Created container topic-operator
  Normal   Started    18m (x2 over 20m)   kubelet            Started container topic-operator
  Warning  Unhealthy  37s (x96 over 20m)  kubelet            Startup probe failed: Get "http://100.84.137.8:8080/healthy": dial tcp 100.84.137.8:8080: connect: connection refused
```
The container log:
```
kubectl logs -n kafka my-cluster-entity-operator-67cbb8f86f-vhkl8 -c topic-operator

2022-04-19 08:54:59,78134 INFO  [vert.x-worker-thread-0] ZkClient:936 - Waiting for keeper state SyncConnected
2022-04-19 08:54:59,78536 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1181 - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181.
2022-04-19 08:54:59,78562 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1183 - SASL config status: Will not attempt to authenticate using SASL (unknown error)
2022-04-19 08:54:59,78615 WARN  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1300 - Session 0x0 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) [org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
2022-04-19 08:55:00,89244 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1181 - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181.
2022-04-19 08:55:00,89265 INFO  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1183 - SASL config status: Will not attempt to authenticate using SASL (unknown error)
2022-04-19 08:55:00,89318 WARN  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1300 - Session 0x0 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) [org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
```
The zookeeper dns is fine:
```
bash-5.1# nslookup my-cluster-zookeeper-nodes.kafka.svc.cluster.local
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	my-cluster-zookeeper-nodes.kafka.svc.cluster.local
Address: 100.73.225.9
Name:	my-cluster-zookeeper-nodes.kafka.svc.cluster.local
Address: 100.84.137.5
Name:	my-cluster-zookeeper-nodes.kafka.svc.cluster.local
Address: 100.121.221.71
```

**To Reproduce**
```
[root@iZ2zeaxzynknewlf0dkin9Z ~]# cat kafka-instance.yaml 
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type:  persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
Just apply it.

**Environment (please complete the following information):**
 - Strimzi version: [e.g. main, 0.28.0]
 - Installation method: yaml
 - Kubernetes cluster: 1.23.5
 - Infrastructure: alicloud

**Comment by scholzj** [comment]
That is not startup probe failure. If it cannot connect to ZooKeeper, it is not running and restarts. So you have to investigate why it cannot conennct to ZooKeeper.

**Comment by fanux** [comment]
It seems the zookeeper worked fine, I can resolve the zookeeper DNS.

**Comment by fanux** [comment]
```
Session 0x0 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused

```

**Comment by scholzj** [comment]
But resolving DNS doesn't say anything about ZooKeeper working or not. The error is not complaining about resolving ZooKeeper DNS.

**Comment by fanux** [comment]
OH, it seems I can't ping the zookeeper IP...

**Comment by scholzj** [comment]
Not sure the ping is expected to work in Kubernetes. But maybe you can start by:
* Checking the ZooKeeper logs
* Checking the TLS sidecar in the EO pod which is where the Topic Operator connects and which connects to ZooKeeper
* See if you can connect manually

**Comment by fanux** [comment]
It seems cause by the network policy:
```
[root@iZ2zeaxzynknewlf0dkin9Z ~]# kubectl get networkpolicy -A -owide
NAMESPACE   NAME                                  POD-SELECTOR                           AGE
kafka       my-cluster-network-policy-kafka       strimzi.io/name=my-cluster-kafka       11s
kafka       my-cluster-network-policy-zookeeper   strimzi.io/name=my-cluster-zookeeper   12s
```
How can I delete those policy, the operator will recreate it when I delete it?

**Comment by fanux** [comment]
1. zookeeper logs:
```
2022-04-19 13:30:54,445 INFO The list of known four letter word commands is : [{1936881266=srvr, 1937006964=stat, 2003003491=wchc, 1685417328=dump, 1668445044=crst, 1936880500=srst, 1701738089=envi, 1668247142=conf, -720899=telnet close, 1751217000=hash, 2003003507=wchs, 2003003504=wchp, 1684632179=dirs, 1668247155=cons, 1835955314=mntr, 1769173615=isro, 1920298859=ruok, 1735683435=gtmk, 1937010027=stmk}] (org.apache.zookeeper.server.command.FourLetterCommands) [nioEventLoopGroup-4-2]
2022-04-19 13:30:54,445 INFO The list of enabled four letter word commands is : [[wchs, stat, wchp, dirs, stmk, conf, ruok, mntr, srvr, wchc, envi, srst, isro, dump, gtmk, telnet close, crst, hash, cons]] (org.apache.zookeeper.server.command.FourLetterCommands) [nioEventLoopGroup-4-2]
2022-04-19 13:30:54,445 INFO Processing ruok command from /127.0.0.1:53654 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-2]
2022-04-19 13:30:54,446 INFO Processing ruok command from /127.0.0.1:53652 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-1]
```

2. The TLS sidecar:
```
2022.04.19 13:30:50 LOG5[68]: Service [zookeeper-2181] accepted connection from 127.0.0.1:48660
2022.04.19 13:30:50 LOG5[68]: s_connect: connected 10.100.244.194:2181
2022.04.19 13:30:50 LOG5[68]: Service [zookeeper-2181] connected remote server from 100.84.137.8:37512
2022.04.19 13:30:50 LOG5[68]: Certificate accepted at depth=0: O=io.strimzi, CN=my-cluster-zookeeper
2022.04.19 13:31:40 LOG3[66]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2022.04.19 13:31:40 LOG5[66]: Connection closed: 309 byte(s) sent to TLS, 421 byte(s) sent to socket
2022.04.19 13:32:57 LOG5[68]: Connection closed: 333 byte(s) sent to TLS, 481 byte(s) sent to socket
```

**Comment by scholzj** [comment]
But the network policy allows the connection. Plus the TLS sidecar seems to connect and then disconnect. So I think this is more some general networking issue rather than network policy.

**Comment by fanux** [comment]
So how can I solve this issue or how to trouble shouting it ?

**Comment by fanux** [comment]
I delete the pod, now the TLS sidecar seems work now:
```
2022.04.20 03:07:39 LOG5[1]: Service [zookeeper-2181] accepted connection from 127.0.0.1:48714
2022.04.20 03:07:39 LOG5[1]: s_connect: connected 10.100.244.194:2181
2022.04.20 03:07:39 LOG5[1]: Service [zookeeper-2181] connected remote server from 100.121.221.78:37684
2022.04.20 03:07:39 LOG5[1]: Certificate accepted at depth=0: O=io.strimzi, CN=my-cluster-zookeeper
2022.04.20 03:09:46 LOG5[1]: Connection closed: 333 byte(s) sent to TLS, 481 byte(s) sent to socket
2022.04.20 03:09:49 LOG5[2]: Service [zookeeper-2181] accepted connection from 127.0.0.1:51034
2022.04.20 03:09:49 LOG5[2]: s_connect: connected 10.100.244.194:2181
2022.04.20 03:09:49 LOG5[2]: Service [zookeeper-2181] connected remote server from 100.121.221.78:40004
2022.04.20 03:09:49 LOG5[2]: Certificate accepted at depth=0: O=io.strimzi, CN=my-cluster-zookeeper
2022.04.20 03:11:56 LOG5[2]: Connection closed: 333 byte(s) sent to TLS, 481 byte(s) sent to socket
2022.04.20 03:11:58 LOG5[3]: Service [zookeeper-2181] accepted connection from 127.0.0.1:53352
2022.04.20 03:11:58 LOG5[3]: s_connect: connected 10.100.244.194:2181
2022.04.20 03:11:58 LOG5[3]: Service [zookeeper-2181] connected remote server from 100.121.221.78:42322
2022.04.20 03:11:58 LOG5[3]: Certificate accepted at depth=0: O=io.strimzi, CN=my-cluster-zookeeper
```
But the topic operator still can't start:
```
2022-04-20 03:14:08,64883 WARN  [vert.x-worker-thread-0-SendThread(localhost:2181)] ClientCnxn:1300 - Session 0x0 for sever localhost/0:0:0:0:0:0:0:1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) [org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
```
```
2022-04-20 03:14:09,88219 WARN  [kafka-admin-client-thread | adminclient-2] KafkaStreamsTopicStoreService:152 - Durability of the topic [__strimzi_store_topic] is not sufficient for production use - replicationFactor: 1, min.insync.replicas: 1. Increase the replication factor to at least 3 and configure the min.insync.replicas to 1.
```
```
2022-04-20 03:14:12,34335 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2574 ms, time limit is 2000 ms
2022-04-20 03:14:13,34395 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3575 ms, time limit is 2000 ms
2022-04-20 03:14:14,34337 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4574 ms, time limit is 2000 ms
2022-04-20 03:14:15,34410 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5574 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194) ~[?:?]
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998) ~[?:?]
	at io.apicurio.registry.utils.ConcurrentUtil.get(ConcurrentUtil.java:35) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.apicurio.registry.utils.ConcurrentUtil.get(ConcurrentUtil.java:27) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.apicurio.registry.utils.ConcurrentUtil.result(ConcurrentUtil.java:54) ~[io.apicurio.apicurio-registry-common-1.3.2.Final.jar:?]
	at io.strimzi.operator.topic.Session.lambda$start$9(Session.java:198) ~[io.strimzi.topic-operator-0.28.0.jar:0.28.0]
	at io.strimzi.operator.topic.Session$$Lambda$278/0x0000000840327040.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase$$Lambda$424/0x0000000840433040.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by scholzj** [comment]
Once again, you would need to share the full logs in order to get any help. Not just some snippets you find interesting.
