### ISSUE TITLE
Topic operator will create KafkaTopic twice in K8s

### ISSUE THREAD

**Issue by Yansongsongsong** [strimzi/strimzi-kafka-operator#6773]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
i was using strimzi with version 0.27.1. when i apply kafka topic with metadata.name different from spec.topic_name, topic operator helps to create two KafkaTopic in K8s.

**To Reproduce**
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  annotations:
    meta.helm.sh/release-name: yansong-zxcqwxcf
    meta.helm.sh/release-namespace: my-space
  labels:
    app.kubernetes.io/managed-by: Helm
    strimzi.io/cluster: my-kafka
  name: yansong-zxcqwxcf
  namespace: my-space
spec:
  config:
    retention.bytes: 524288000
    retention.ms: 604800000
    segment.bytes: 104857600
  partitions: 3
  replicas: 3
  topicName: amazingName
```
apply this yaml file.

the result is as follows:
```
root@main-node-k8s:~# kc get kafkatopic | grep my-kafka
amazingname---7351c69ea3cafc02b5777c3f17784b810626098     oms-kafka           3            3
yansong-zxcqwxcf                                                                                    oms-kafka           3            3                    True
```

**Expected behavior**
Only one Kafkatopic was created in k8s.

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1
 - Installation method: helm chart
 - Kubernetes cluster: Kubernetes 1.23.1
 - Infrastructure: phsical machine

**YAML files and logs**

**Additional context**

my yaml file is above. the point is the meatadata.name  is different from spec.topicName . And after i applied it to k8s, operator help to create two kafkatopics CR, and one of them is always non-ready. the  error is `the topic is managed by others`

i tried to dig it out. and find some clues.
1. When we submit yaml to k8s, the k8s will create one KafkaTopic CR
2. topic operator will watch on the change of it.
3. topic will trigger the process of reconcile  with `k8sTopic:nonnull, kafkaTopic:null, privateTopic:null`
4. and then the operator will 
    a. create ZK node of this topic in zookeeper
    b. produce the new topic to `KafkaSteamsTopicStore`
    c. and balabala

due to topic operator also watch on the change of ZK Nodes, new node of topic in ZK will trigger the process of reconcile  with `k8sTopic:null, kafkaTopic:nonnull, privateTopic:null`
and then the operator will 
1. create related KafkaTopic in k8s.

When I review the log, i found step 4.b was failed due to `InvalidStateException` . I think this should be the key to this problem.

My analysis is

1. due to 4.b failed, no data was submitted to `KafkaSteamsTopicStore` , so the `privateTopic` is null.
2. due to `privateTopic` is null, the reconciliation will create KafkaTopic again.

All i know for reason of 4.b failed is that during execution of `io.strimzi.operator.topic.KafkaStreamsTopicStore#handleTopicCommand`The code is as follows:

```
    private Future<Void> handleTopicCommand(TopicCommand cmd) {
        LOGGER.debug("Handling topic command [{}]: {}", cmd.getType(), cmd.getKey());
        String key = cmd.getKey();
        CompletionStage<Throwable> result = resultService.apply(key, cmd.getUuid())
                .thenApply(KafkaStreamsTopicStore::toThrowable);
        //! IMPORTANT:
        // Kafka Streams can re-balance in-between these two calls ...
        producer.apply(new ProducerRecord<>(storeTopic, key, cmd))
                .whenComplete((r, t) -> {
                    if (t != null) {
                        LOGGER.error("Error sending topic command", t);
                    }
                });
        return Future.fromCompletionStage(result).compose(
            t -> t != null ? Future.failedFuture(t) : Future.succeededFuture()
        );
    }
```

During the execution of

```
CompletionStage<Throwable> result = resultService.apply(key, cmd.getUuid())
        .thenApply(KafkaStreamsTopicStore::toThrowable);
```

`WaitForResultService$checkStaleResults` check the result periodically, which raised `InvalidStateException` to avoid block tasks too long.

So i have some options:

1. choose one larger parameters `STRIMZI_STALE_RESULT_TIMEOUT_MS`
2. make `metadata.name` and `spec.topicName` be the same
3. add some code to check when zkwatcher trigger the workflow.

My question is

1. Is my analysis correct?
2. i have no idea on how to choose, would you mind giving some advice?
3. There is no much documents for them. Can anyone help to explain that why do we need `WaitForResultService` to do so?

**Comment by scholzj** [comment]
> would you mind giving the details of the reason why it can work? very appreciate it !

Sorry, not sure what you mean. You want to know how does the topic auto-creation relate to it?

**Comment by Yansongsongsong** [comment]
> > would you mind giving the details of the reason why it can work? very appreciate it !
> 
> Sorry, not sure what you mean. You want to know how does the topic auto-creation relate to it?

yes. I wanna know why `auto.create.topics.enable: "false"` this param will prevent topic creation in parallels.

**Comment by Yansongsongsong** [comment]
And just now after I checked status of cluster, I found this issue happened again. The timeline is:

1. 2022-05-06 enable `auto.create.topics.enable: "false"`
2. apply kafkatopic in cluster with topic name is `freeName` and KafKaTopic name is `yansong-free123123`
3. everything goes fine until 2022-05-08
4. topic opertaor began periodic task for all topics
5. it can not find privatetopic from kafka stream with name `freeName`

the log is as follows:
```
2022-05-08 08:06:09,20795 INFO  [vert.x-eventloop-thread-2] TopicOperator:1314 - Starting periodic  reconciliation
2022-05-08 08:06:09,20805 DEBUG [vert.x-eventloop-thread-2] KafkaImpl:127 - Listing topics
2022-05-08 08:06:09,21136 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1398 - Reconciling kafka topics [__strimzi_store_topic, strimzi.cruisecontrol.partitio
nmetricsamples, __strimzi-topic-operator-kstreams-topic-store-changelog, strimzi.cruisecontrol.modeltrainingsamples, strimzi.cruisecontrol.metrics, freeName, __
consumer_offsets]
2022-05-08 08:06:09,21401 DEBUG [vert.x-eventloop-thread-2] TopicOperator:472 - Reconciliation #436804(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Queuing action reconcile-from-kafka on topic freeName
2022-05-08 08:06:09,21405 DEBUG [vert.x-eventloop-thread-2] TopicOperator:475 - Reconciliation #436805(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Adding first waiter reconcile-from-kafka
2022-05-08 08:06:09,21409 DEBUG [vert.x-eventloop-thread-2] TopicOperator:484 - Reconciliation #436806(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Lock acquired
2022-05-08 08:06:09,21413 DEBUG [vert.x-eventloop-thread-2] TopicOperator:485 - Reconciliation #436807(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Executing action reconcile-from-kafka on topic freeName
2022-05-08 08:06:09,21425 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1419 - Reconciliation #436808(periodic kafka freeName) KafkaTopic(cloud/freename---29f
58b63b27943eb4536b61e927629286c429a9b): Have private topic for topic freeName in Kafka


2022-05-08 08:06:09,25655 DEBUG [vert.x-eventloop-thread-2] K8sTopicWatcher:85 - 32573|periodic kafka freeName: Concurrent modification in kube: new version 972
39754
2022-05-08 08:06:09,25661 DEBUG [vert.x-eventloop-thread-2] KafkaImpl:108 - Reconciliation #436848(periodic kafka freeName) KafkaTopic(cloud/freename---29f58b63
b27943eb4536b61e927629286c429a9b): Getting metadata for topic freeName
2022-05-08 08:06:09,26005 INFO  [vert.x-eventloop-thread-2] TopicOperator:576 - Reconciliation #436849(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Reconciling topic freeName, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
2022-05-08 08:06:09,26011 DEBUG [vert.x-eventloop-thread-2] TopicOperator:639 - Reconciliation #436850(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): 3 way diff
2022-05-08 08:06:09,26016 DEBUG [vert.x-eventloop-thread-2] TopicOperator:730 - Reconciliation #436851(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): topicStore->kafkaTopic: TopicDiff{differences={}}
2022-05-08 08:06:09,26020 DEBUG [vert.x-eventloop-thread-2] TopicOperator:732 - Reconciliation #436852(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): topicStore->k8sTopic: TopicDiff{differences={}}
2022-05-08 08:06:09,26025 DEBUG [vert.x-eventloop-thread-2] TopicOperator:741 - Reconciliation #436853(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Diffs do not conflict, merged diff: TopicDiff{differences={}}
2022-05-08 08:06:09,26030 INFO  [vert.x-eventloop-thread-2] TopicOperator:743 - Reconciliation #436854(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): All three topics are identical
2022-05-08 08:06:09,26039 INFO  [vert.x-eventloop-thread-2] TopicOperator:1493 - Reconciliation #436855(periodic kafka freeName) KafkaTopic(cloud/freename---29f
58b63b27943eb4536b61e927629286c429a9b): Success reconciling KafkaTopic cloud/yanosng-free123123
2022-05-08 08:06:09,26044 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1422 - Reconciliation #436856(periodic kafka freeName) KafkaTopic(cloud/freename---29f
58b63b27943eb4536b61e927629286c429a9b): freeName reconcile success -> succeeded
2022-05-08 08:06:09,26049 DEBUG [vert.x-eventloop-thread-2] TopicOperator:487 - Reconciliation #436857(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Executing handler for action reconcile-from-kafka on topic freeName
2022-05-08 08:06:09,26063 DEBUG [vert.x-eventloop-thread-2] TopicOperator:500 - Reconciliation #436858(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Removed metric strimzi..resource.state{cloud:KafkaTopic/freename---29f58b63b27943eb4536b61e927629286c429a9b}
2022-05-08 08:06:09,26073 DEBUG [vert.x-eventloop-thread-2] TopicOperator:513 - Reconciliation #436859(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Updated metric strimzi.resource.state[tag(kind=KafkaTopic),tag(name=yanosng-free123123),tag(reason=none),tag(resource-nam
espace=cloud)] = 1
2022-05-08 08:06:09,26078 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1050 - Reconciliation #436860(periodic kafka freeName) KafkaTopic(cloud/freename---29f
58b63b27943eb4536b61e927629286c429a9b): There is a KafkaTopic to set status on, rv=97239754, generation=1
2022-05-08 08:06:09,26090 DEBUG [vert.x-eventloop-thread-2] StatusDiff:42 - Ignoring Status diff {"op":"replace","path":"/conditions/0/lastTransitionTime","valu
e":"2022-05-08T08:06:09.260794Z"}
2022-05-08 08:06:09,26103 DEBUG [vert.x-eventloop-thread-2] TopicOperator:530 - Reconciliation #436861(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Lock released
2022-05-08 08:06:09,26107 DEBUG [vert.x-eventloop-thread-2] TopicOperator:461 - Reconciliation #436862(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Removing last waiter reconcile-from-kafka



// -------------------------------- for now everything is fine, and then next periodic reconciliation began



2022-05-08 08:07:09,36862 INFO  [vert.x-eventloop-thread-2] TopicOperator:1314 - Starting periodic  reconciliation
2022-05-08 08:07:09,36871 DEBUG [vert.x-eventloop-thread-2] KafkaImpl:127 - Listing topics
2022-05-08 08:07:09,37131 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1398 - Reconciling kafka topics [__strimzi_store_topic, strimzi.cruisecontrol.partitio
nmetricsamples, __strimzi-topic-operator-kstreams-topic-store-changelog, strimzi.cruisecontrol.modeltrainingsamples, strimzi.cruisecontrol.metrics, freeName, __
consumer_offsets]


2022-05-08 08:07:09,38495 DEBUG [vert.x-eventloop-thread-2] TopicOperator:472 - Reconciliation #436975(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Queuing action reconcile-from-kafka on topic freeName
2022-05-08 08:07:09,38503 DEBUG [vert.x-eventloop-thread-2] TopicOperator:475 - Reconciliation #436976(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Adding first waiter reconcile-from-kafka
2022-05-08 08:07:09,38509 DEBUG [vert.x-eventloop-thread-2] TopicOperator:484 - Reconciliation #436977(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Lock acquired
2022-05-08 08:07:09,38513 DEBUG [vert.x-eventloop-thread-2] TopicOperator:485 - Reconciliation #436978(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Executing action reconcile-from-kafka on topic freeName
2022-05-08 08:07:09,38532 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1415 - Reconciliation #436979(periodic kafka freeName) KafkaTopic(cloud/freename---29f
58b63b27943eb4536b61e927629286c429a9b): No private topic for topic freeName in Kafka -> undetermined
2022-05-08 08:07:09,38538 DEBUG [vert.x-eventloop-thread-2] TopicOperator:487 - Reconciliation #436980(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Executing handler for action reconcile-from-kafka on topic freeName
2022-05-08 08:07:09,38549 DEBUG [vert.x-eventloop-thread-2] TopicOperator:1087 - Reconciliation #436981(periodic kafka freeName) KafkaTopic(cloud/freename---29f
58b63b27943eb4536b61e927629286c429a9b): No KafkaTopic to set status
2022-05-08 08:07:09,38553 DEBUG [vert.x-eventloop-thread-2] TopicOperator:530 - Reconciliation #436982(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Lock released
2022-05-08 08:07:09,38558 DEBUG [vert.x-eventloop-thread-2] TopicOperator:461 - Reconciliation #436983(periodic kafka freeName) KafkaTopic(cloud/freename---29f5
8b63b27943eb4536b61e927629286c429a9b): Removing last waiter reconcile-from-kafka

// ---------------- it said `No private topic for topic freeName in Kafka -> undetermined` which lead to creation of Kafkatopic


2022-05-08 08:07:09,41152 INFO  [vert.x-eventloop-thread-2] TopicOperator:576 - Reconciliation #437051(periodic -freeName) KafkaTopic(cloud/freename---29f58b63b
27943eb4536b61e927629286c429a9b): Reconciling topic freeName, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
2022-05-08 08:07:09,41157 DEBUG [vert.x-eventloop-thread-2] TopicOperator:589 - Reconciliation #437052(periodic -freeName) KafkaTopic(cloud/freename---29f58b63b
27943eb4536b61e927629286c429a9b): topic created in kafka, will create KafkaTopic in k8s and topicStore
2022-05-08 08:07:09,41161 DEBUG [vert.x-eventloop-thread-2] TopicOperator:819 - Reconciliation #437053(periodic -freeName) KafkaTopic(cloud/freename---29f58b63b
27943eb4536b61e927629286c429a9b): Enqueuing event CreateResource(topicName=freeName,ctx=32593|periodic -freeName)

// --------------- and began to create it
```


and during the periodic task, i also found some error log for other topics:

```
2022-05-08 08:06:09,30344 ERROR [vert.x-eventloop-thread-2] TopicOperator:1490 - Reconciliation #436916(periodic -__strimzi-topic-operator-kstreams-topic-store-
changelog) KafkaTopic(cloud/strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b): Error reconciling KafkaTopic null
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://11.127.64.1/apis/kafka.strimzi.io/v1beta2/namespaces/cloud/kafkatopi
cs. Message: kafkatopics.kafka.strimzi.io "strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b" already exists. Rec
eived status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=kafka.strimzi.io, kind=kafkatopics, name=strimzi-topic-operator-kstreams-to
pic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=kafkatopics.kaf
ka.strimzi.io "strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b" already exists, metadata=ListMeta(_continue=nul
l, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:697) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:676) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:629) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:566) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:315) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:651) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:91) ~[io.fabric8.kubernetes-client-5.10.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:61) ~[io.fabric8.kubernetes-client-5.10.2.j
ar:?]
        at io.strimzi.operator.topic.K8sImpl.lambda$createResource$0(K8sImpl.java:51) ~[io.strimzi.topic-operator-0.27.1.jar:0.27.1]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```


I guess it was that the operator failed to get topics from KafkaStream, so the topic was created twice. Do you have any idea about that?

**Comment by Yansongsongsong** [comment]
And the topic yaml is like:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  annotations:
    meta.helm.sh/release-name: yanosng-free123123
    meta.helm.sh/release-namespace: cloud
  creationTimestamp: "2022-05-06T10:56:14Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    strimzi.io/cluster: oms-kafka
  name: yanosng-free123123
  namespace: cloud
  resourceVersion: "98252559"
  uid: 8fe6200c-c0b9-4b8c-b8b3-a6ed364662ca
spec:
  config:
    retention.bytes: 524288000
    retention.ms: 604800000
    segment.bytes: 104857600
  partitions: 3
  replicas: 3
  topicName: freeName
status:
  conditions:
  - lastTransitionTime: "2022-05-08T20:27:24.830552Z"
    status: "True"
    type: Ready
  observedGeneration: 1
  topicName: freeName
```

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  creationTimestamp: "2022-05-08T08:07:09Z"
  generation: 1
  labels:
    strimzi.io/cluster: oms-kafka
  name: freename---29f58b63b27943eb4536b61e927629286c429a9b
  namespace: cloud
  resourceVersion: "98251879"
  uid: fe8bb345-840f-4880-a02e-85d34f2ff9e2
spec:
  config:
    retention.bytes: "524288000"
    retention.ms: "604800000"
    segment.bytes: "104857600"
  partitions: 3
  replicas: 3
  topicName: freeName
status:
  conditions:
  - lastTransitionTime: "2022-05-08T20:26:21.882272Z"
    eason: InvalidStateException
    status: "True"
    type: NotReady
  observedGeneration: 1
  topicName: freeName
```

**Comment by Yansongsongsong** [comment]
the `creationTimestamp` can indicate that topics were not created at the same time. And with the log we can ensure that it was created in one periodic reconciliation.

**Comment by Yansongsongsong** [comment]
> and during the periodic task, i also found some error log for other topics:

for these topics. The error is the same. They are all `already exists` error. And I released that I deploy two Kafka cluster instances under the same k8s namespace. 

Is it the problem?  BTW, may I know whether we support to initialise two clusters under one same namespace?

**Comment by scholzj** [comment]
> yes. I wanna know why auto.create.topics.enable: "false" this param will prevent topic creation in parallels. Thank you so much for your reply!

When the topic auto-creation is enabled, your consumer / producer causes the topic to be created in Kafka when they connect. So unless you really wait for the KafkaTopic to be created, they can easily create the topic first.

The general recommendation we give is also to:
* Use topic names which are valid Kubernetes names
* If you have to use topic names which are not valid Kubernetes names, you should name the KafkaTopic resource in sync with the Strimzi convention.

As I said before, this seems like a duplicate of #6578, so I will suggest to close it.

**Comment by Yansongsongsong** [comment]
> When the topic auto-creation is enabled, your consumer / producer causes the topic to be created in Kafka when they connect. So unless you really wait for the KafkaTopic to be created, they can easily create the topic first.

hi scholzj, thank you so much for your reply. your explanation is clear. But actually, for this case, i didn't have any producer or consumer when i apply KafkaTopic yaml to k8s. I am not sure whether it is the root casue.

and for the name recommendation, thank you for your reply so much. For digging into this issue, how can I help you to do so? And why don't we just skip the topic creation if we found such one error:
```
2022-05-08 08:07:09,66127 DEBUG [vert.x-eventloop-thread-2] StatusDiff:49 - Desired Status path /conditions/0/message has value "Topic 'freeName' is already managed via KafkaTopic 'yanosng-free123123' it cannot also be managed via the KafkaTopic 'freename---29f58b63b27943eb4536b61e927629286c429a9b'"
```

**Comment by scholzj** [comment]
> But actually, for this case, i didn't have any producer or consumer when i apply KafkaTopic yaml to k8s. I am not sure whether it is the root casue.

No, that is not root cause. But if there are no consumers / producers, then it has nothing to do with the autocreation and it is not related to it. (keep in mind that even things such as Kafka Connect etc. are at the end just some consumers and producers)

**Comment by Yansongsongsong** [comment]
> > But actually, for this case, i didn't have any producer or consumer when i apply KafkaTopic yaml to k8s. I am not sure whether it is the root casue.
> 
> No, that is not root cause. But if there are no consumers / producers, then it has nothing to do with the autocreation and it is not related to it. (keep in mind that even things such as Kafka Connect etc. are at the end just some consumers and producers)

Okay cool. I found the code in topic operator to create topic with kafka client library. It should be included in `autocreation`. For this issue i have kept the debug level log. If it is needed to dig out root cause, i am free to provide it.

Thank you for your time and reply. I will close the issue. Thank you again.

( BTW i am afraid that it is the problem of kafka stream store.
