### ISSUE TITLE
NullPointerException after update of replicas count for topic

### ISSUE THREAD

**Issue by asorokhtey** [strimzi/strimzi-kafka-operator#691]
Steps to Reproduce:
- Start Kafka cluster
- Create topic: oc create -f examples/topic/kafka-topic.yaml
- Edit replicas count for topic: oc edit kafkatopic my-topic
- Check topic operator logs

```
[2018-07-31 15:27:25,388] INFO  <opicOperator:416> [oop-thread-2] Reconciling topic my-topic, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-07-31 15:27:25,388] ERROR <opicOperator:569> [oop-thread-2] Changes replication factor
[2018-07-31 15:27:25,389] INFO  <nedKafkaImpl:83> [oop-thread-2] Changing replication factor of topic my-topic to 1
[2018-07-31 15:27:25,399] INFO  <nedKafkaImpl:342> [ker-thread-4] Started process java.lang.UNIXProcess@4caff132 with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64/jre/bin/java, -cp, /topic-operator-0.6.0-SNAPSHOT.jar, kafka.admin.ReassignPartitionsCommand, --zookeeper, localhost:2181, --topics-to-move-json-file, /tmp/io.strimzi.operator.topic.OperatorAssignedKafkaImpl5926506753893672106-topics-to-move.json, --broker-list, 0,1,2, --generate]
[2018-07-31 15:27:25,520] INFO  <nedKafkaImpl:346> [ker-thread-4] Process java.lang.UNIXProcess@4caff132: exited with status 1
Jul 31, 2018 3:27:25 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
	at io.strimzi.operator.topic.TopicOperator$ChangeReplicationFactor.lambda$handle$1(TopicOperator.java:292)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$3(Future.java:330)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$compose$0(Future.java:235)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$compose$0(Future.java:235)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:289)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

[2018-07-31 15:27:25,523] WARN  <opicOperator:95> [oop-thread-2] java.lang.NullPointerException
[2018-07-31 15:27:25,536] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event MODIFIED on resource my-topic with labels {strimzi.io/cluster=my-cluster}
[2018-07-31 15:27:25,541] INFO  <TopicWatcher:40> [oop-thread-3] Success processing KafkaTopic watch event MODIFIED on resource my-topic with labels {strimzi.io/cluster=my-cluster}
[2018-07-31 15:27:25,554] INFO  <opicOperator:416> [oop-thread-3] Reconciling topic my-topic, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-07-31 15:27:25,555] ERROR <opicOperator:563> [oop-thread-3] Number of partitions cannot be decreased
[2018-07-31 15:27:25,555] ERROR <TopicWatcher:49> [oop-thread-3] Failure processing KafkaTopic watch event MODIFIED on resource my-topic with labels {strimzi.io/cluster=my-cluster}: Number of partitions cannot be decreased
java.lang.Exception: Number of partitions cannot be decreased
	at io.strimzi.operator.topic.TopicOperator.update3Way(TopicOperator.java:566) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.TopicOperator.reconcile(TopicOperator.java:482) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.TopicOperator.lambda$reconcileOnResourceChange$17(TopicOperator.java:818) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl.lambda$topicMetadata$0(BaseKafkaImpl.java:244) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$MetadataWork.complete(BaseKafkaImpl.java:186) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$Work.run(BaseKafkaImpl.java:54) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$Work.handle(BaseKafkaImpl.java:61) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.strimzi.operator.topic.BaseKafkaImpl$Work.handle(BaseKafkaImpl.java:51) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [topic-operator-0.6.0-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [topic-operator-0.6.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[2018-07-31 15:27:25,556] INFO  <opicOperator:92> [oop-thread-3] Number of partitions cannot be decreased
[2018-07-31 15:27:25,556] WARN  <opicOperator:95> [oop-thread-3] Failure processing KafkaTopic watch event MODIFIED on resource my-topic with labels {strimzi.io/cluster=my-cluster}: Number of partitions cannot be decreased

```

**Comment by ppatierno** [comment]
From the log I even see "Number of partitions cannot be decreased", are you changing "replicas" field or "partitions" ... or both in this test? :-)

**Comment by asorokhtey** [comment]
@ppatierno I'm changing replicas from 1 to 2
