### ISSUE TITLE
strimzi kafka failing after k8s version upgrade to 1.22

### ISSUE THREAD

**Issue by 4sif-adnan** [strimzi/strimzi-kafka-operator#7033]
Hi,
I have been facing the same issue after upgrading k8s version from 1.21 to 1.22 last night
below is deployement file of mine

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: noice-dev
  namespace: strimzi-dev
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          brokers:
            - broker: 0
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
            - broker: 1
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
            - broker: 2
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"

```
```
NAME                                        READY   STATUS             RESTARTS         AGE
noice-dev-zookeeper-0                       0/1     CrashLoopBackOff   21 (3m32s ago)   58m
noice-dev-zookeeper-1                       0/1     CrashLoopBackOff   21 (2m50s ago)   58m
noice-dev-zookeeper-2                       0/1     CrashLoopBackOff   21 (3m22s ago)   58m
strimzi-cluster-operator-585f6fd9d7-8x9fk   1/1     Running            0                59m
```

Cluster operator logs below
```

2022-07-08 14:00:30 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace strimzi-dev
2022-07-08 14:00:30 INFO  AbstractOperator:226 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Kafka noice-dev will be checked for creation or modification
2022-07-08 14:01:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:02:30 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace strimzi-dev
2022-07-08 14:02:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:03:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:04:30 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace strimzi-dev
2022-07-08 14:04:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:05:30 INFO  AbstractOperator:373 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Reconciliation is in progress
2022-07-08 14:05:31 ERROR Util:153 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-1 in namespace strimzi-dev to be ready
2022-07-08 14:05:31 ERROR Util:153 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-2 in namespace strimzi-dev to be ready
2022-07-08 14:05:31 ERROR Util:153 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-0 in namespace strimzi-dev to be ready
2022-07-08 14:05:31 ERROR AbstractOperator:247 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-0 in namespace strimzi-dev to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:154) ~[io.strimzi.operator-common-0.29.0.jar:0.29.0]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-07-08 14:05:31 WARN  AbstractOperator:532 - Reconciliation #31(timer) Kafka(strimzi-dev/noice-dev): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource noice-dev-zookeeper-0 in namespace strimzi-dev to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:154) ~[io.strimzi.operator-common-0.29.0.jar:0.29.0]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

_Originally posted by @4sif-adnan in https://github.com/strimzi/strimzi-kafka-operator/issues/3971#issuecomment-1179030208_

**Comment by scholzj** [comment]
The log is quite clear -> the ZooKeeper pods are not ready. So you will need to look into the ZooKeeper pods what their problem is.

**Comment by 4sif-adnan** [comment]
Yeah..but can't figure out why? zookeeper pod logs showing below. With same deployment files and same setup it works in k8s v1.21

```
Detected Zookeeper ID 1
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for client and quorum listeners
Preparing keystore for client and quorum listeners is complete
Starting Zookeeper with configuration:
# The directory where the snapshot is stored.
dataDir=/var/lib/zookeeper/data

# Other options
4lw.commands.whitelist=*
standaloneEnabled=false
reconfigEnabled=true
clientPort=12181
clientPortAddress=127.0.0.1

# TLS options
serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
ssl.clientAuth=need
ssl.quorum.clientAuth=need
secureClientPort=2181
sslQuorum=true

ssl.trustStore.location=/tmp/zookeeper/cluster.truststore.p12
ssl.trustStore.password=[hidden]
ssl.trustStore.type=PKCS12
ssl.quorum.trustStore.location=/tmp/zookeeper/cluster.truststore.p12
ssl.quorum.trustStore.password=[hidden]
ssl.quorum.trustStore.type=PKCS12

ssl.keyStore.location=/tmp/zookeeper/cluster.keystore.p12
ssl.keyStore.password=[hidden]
ssl.keyStore.type=PKCS12
ssl.quorum.keyStore.location=/tmp/zookeeper/cluster.keystore.p12
ssl.quorum.keyStore.password=[hidden]
ssl.quorum.keyStore.type=PKCS12

# Provided configuration
tickTime=2000
initLimit=5
syncLimit=2
autopurge.purgeInterval=1


# Zookeeper nodes configuration
server.1=noice-dev-zookeeper-0.noice-dev-zookeeper-nodes.strimzi-dev.svc:2888:3888:participant;127.0.0.1:12181
server.2=noice-dev-zookeeper-1.noice-dev-zookeeper-nodes.strimzi-dev.svc:2888:3888:participant;127.0.0.1:12181
server.3=noice-dev-zookeeper-2.noice-dev-zookeeper-nodes.strimzi-dev.svc:2888:3888:participant;127.0.0.1:12181

+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/zookeeper-server-start.sh /tmp/zookeeper.properties
```

**Comment by scholzj** [comment]
Is that a full log? If it is, maybe its lack of resources causing the issue? Try to configure resource requests / limits in your Kafka CR.

**Comment by 4sif-adnan** [comment]
added but still restarting even before reaching the request level usage

```
NAME                                        CPU(cores)   MEMORY(bytes)   
noice-dev-zookeeper-0                       138m         32Mi            
noice-dev-zookeeper-1                       231m         3Mi             
noice-dev-zookeeper-2                       364m         28Mi            
strimzi-cluster-operator-585f6fd9d7-8x9fk   6m           195Mi 
```
```
NAME                                        READY   STATUS             RESTARTS      AGE
noice-dev-zookeeper-0                       0/1     CrashLoopBackOff   5 (45s ago)   4m57s
noice-dev-zookeeper-1                       0/1     CrashLoopBackOff   5 (45s ago)   4m57s
noice-dev-zookeeper-2                       0/1     Running            5 (85s ago)   4m57s
strimzi-cluster-operator-585f6fd9d7-8x9fk   1/1     Running            0             110m
```
Deployment file with req, limit below

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: noice-dev
  namespace: strimzi-dev
spec:
  kafka:
    resources:
      requests:
        memory: 200Mi
        cpu: 400m
      limits:
        memory: 200Mi
        cpu: 500m
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          brokers:
            - broker: 0
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
            - broker: 1
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
            - broker: 2
              annotations:
                cloud.google.com/load-balancer-type: "Internal"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```

**Comment by scholzj** [comment]
Well, you added them to Kafka and not to ZooKeeper. So you would need to do the same for ZooKeeper. It is also rather small what you gave to Kafka. I use normally for development:
* Kafka: 
  ```yaml
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
  ```
* ZooKeeper:
  ```yaml
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
      limits:
        memory: 1Gi
        cpu: "0.5"
  ```

**Comment by scholzj** [comment]
Well, 1.21 is a different situation -> without limits it depends where it gets scheduled, how many resources you have, if you have some limit ranges configured or not etc. If the ZooKeeper log does not show anything more, than it is hard to point it anywhere else because there is not much to work with.

**Comment by 4sif-adnan** [comment]
Adjusting the Kafka & ZooKeeper request, limit fixed the issue.
Thanks for the help.
