### ISSUE TITLE
A value is required

### ISSUE THREAD

**Issue by haf** [strimzi/strimzi-kafka-operator#7170]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**

Basic KafkaConnect - Debezium config fails without a proper error message.

```
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator io.strimzi.operator.cluster.operator.assembly.ConnectRestException: PUT /connectors/pg/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator A value is required
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 	at io.strimzi.operator.cluster.operator.assembly.KafkaConnectApiImpl.lambda$createOrUpdatePutRequest$1(KafkaConnectApiImpl.java:96) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
```

**To Reproduce**
1. Set up a crunchydata postgres
2. Get name of its secret; here user=db for dbname=db
3. Create Custom Resource
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: pg
  labels:
    strimzi.io/cluster: cdc

spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1

  config:
    database.host: ${secrets:cdc/db-pguser-db:host}
    database.port: ${secrets:cdc/db-pguser-db:port}
    database.user: ${secrets:cdc/db-pguser-db:user}
    database.password: ${secrets:cdc/db-pguser-db:password}
    database.dbname: ${secrets:cdc/db-pguser-db:dbname}
    database.server.name: analytics-db
    schema.include.list: public
```
5. Deploy it
6. See error

```
apiVersion: v1
data:
  dbname: ZGI=
  host: ZGItcHJpbWFyeS5jZGMuc3Zj
  jdbc-uri: amRiYzpwb3N0Z3Jlc3FsOi8vZGItcHJpbWFyeS5jZGMuc3ZjOjU0MzIvZGI/cGFzc3dvcmQ9SWUlMkJlNllfVVcwJTI4R2VrRkZhcnluJTJGU0hLJnVzZXI9ZGI=
  password: SWUrZTZZX1VXMChHZWtGRmFyeW4vU0hL
  port: NTQzMg==
  uri: cG9zdGdyZXNxbDovL2RiOkllK2U2WV9VVzAlMjhHZWtGRmFyeW4lMkZTSEtAZGItcHJpbWFyeS5jZGMuc3ZjOjU0MzIvZGI=
  user: ZGI=
  verifier: U0NSQU0tU0hBLTI1NiQ0MDk2OjJ1MXd6YitRQ2Jzd09NWDNwZVRTTFE9PSRCQmtlWGdSdUphcmlSTk1vd0V0L3NzSElqSkVxNnZieTB5UDJqRWFmMGdBPTp4WUlzWE5ZL3NVVTNHNlM3RlJSRTlXdUlPMmY4UE1YYW91bDZOZFQzdFNNPQ==
kind: Secret
metadata:
  creationTimestamp: "2022-08-01T16:33:21Z"
  labels:
    postgres-operator.crunchydata.com/cluster: db
    postgres-operator.crunchydata.com/pguser: db
    postgres-operator.crunchydata.com/role: pguser
  name: db-pguser-db
  namespace: cdc
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PostgresCluster
    name: db
    uid: ba55cb59-2837-4af4-8799-7d0d2e18fe85
  resourceVersion: "24328"
  uid: 9a018b57-b288-4348-b2f8-1eb54ba8715c
type: Opaque

```

**Expected behavior**
1. Not to error, OR
2. To show the configuration JSON so I can use the message's hint, to try to post the configuration, OR
3. To actually validate the configuration itself

**Environment (please complete the following information):**
 - Strimzi version: 0.30.0
 - Installation method: yaml / kustomize
 - Kubernetes cluster: latest kind
 - Infrastructure: kind

**YAML files and logs**

```
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 2022-08-08 10:40:26 INFO  AbstractOperator:517 - Reconciliation #29(timer) KafkaConnect(cdc/cdc): reconciled
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 2022-08-08 10:42:16 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace cdc
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 2022-08-08 10:42:16 INFO  AbstractOperator:226 - Reconciliation #30(timer) Kafka(cdc/cdc): Kafka cdc will be checked for creation or modification
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 2022-08-08 10:42:16 INFO  AbstractOperator:226 - Reconciliation #31(timer) KafkaConnect(cdc/cdc): KafkaConnect cdc will be checked for creation or modification
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 2022-08-08 10:42:16 INFO  AbstractConnectOperator:466 - Reconciliation #31(timer) KafkaConnect(cdc/cdc): creating/updating connector: pg
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 2022-08-08 10:42:16 WARN  AbstractConnectOperator:729 - Reconciliation #31(timer) KafkaConnect(cdc/cdc): Error reconciling connector pg
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator io.strimzi.operator.cluster.operator.assembly.ConnectRestException: PUT /connectors/pg/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator A value is required
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
strimzi-cluster-operator-5dbfdbd66c-z6wsp strimzi-cluster-operator 	at io.strimzi.operator.cluster.operator.assembly.KafkaConnectApiImpl.lambda$createOrUpdatePutRequest$1(KafkaConnectApiImpl.java:96) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
```

```
cdc-connect-5659d67599-9ntxl cdc-connect 2022-08-08 11:27:21,114 WARN Configuration property 'truncate.handling.mode' is deprecated and will be removed in future versions. Please use 'skipped.operations' instead. (io.debezium.connector.postgresql.PostgresConnectorConfig) [pool-3-thread-18]
cdc-connect-5659d67599-9ntxl cdc-connect 2022-08-08 11:27:21,114 WARN Configuration property 'toasted.value.placeholder' is deprecated and will be removed in future versions. Please use 'unavailable.value.placeholder' instead. (io.debezium.connector.postgresql.PostgresConnectorConfig) [pool-3-thread-18]
cdc-connect-5659d67599-9ntxl cdc-connect 2022-08-08 11:27:21,115 INFO AbstractConfig values:
cdc-connect-5659d67599-9ntxl cdc-connect  (org.apache.kafka.common.config.AbstractConfig) [pool-3-thread-18]
```

**Comment by scholzj** [comment]
I don't think this is a Strimzi bug. The error comes from Connect. So Strimzi does not know which value is required. The JSON request is based on the custom CR. So you should know what is inside by getting `kubectl get kctr -o yaml`.

**Comment by haf** [comment]
<img width="320" alt="bild" src="https://user-images.githubusercontent.com/193115/183411957-7180fa55-dd6b-42a5-afce-70200d7119cf.png">

But it doesn't show what it posts, so I can't debug it. Am I supposed to reverse-proxy the kafka connect API so I can see what Strimzi posts to it?

**Comment by scholzj** [comment]
> But it doesn't show what it posts, so I can't debug it. Am I supposed to reverse-proxy the kafka connect API so I can see what Strimzi posts to it?

If we show it, other people will complain that it is listing their passwords etc.. As I said, the JSON request is based on your KafkaConnector resource. It is the `config` section + the class + the task count. So I do not think you need to reverse engineer what is wrong in the JSON. You control what is in the JSON from the KafkaConnector resource.

I'm not sure why `kubectl get kctr -o yaml` does't show anything for you if you have the connector created. Maybe wrong namespace or something?

**Comment by haf** [comment]
Yes, it shows the config-ish now (without secrets); and that did indeed help debug it. Now I need to figure out permissions. Thanks!
