### ISSUE TITLE
Periodic failure to reconcile a difference in Service .spec.internalTrafficPolicy

### ISSUE THREAD

**Issue by morozov** [strimzi/strimzi-kafka-operator#7442]
**Describe the bug**

The issue looks similar to https://github.com/strimzi/strimzi-kafka-operator/issues/2691.

1. As of Kubernetes 1.23, service resources have `.spec.internalTrafficPolicy` set to `Cluster` by default ([reference](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/)). When reconciling KafkaConnect resources, Strimizi continuously attempts to unset the default value and fails.
   
   ![image](https://user-images.githubusercontent.com/59683/194406140-17bba52a-cda4-44b7-8a3f-d5d06733ca57.png)

3. Additionally, the details being logged are slightly misleading. The following example is formatted for readability, see the full fragment below.

   ```
   Service acme-connect-api differs: {"op":"remove","path":"/spec/internalTrafficPolicy"}
   Current Service acme-connect-api path /spec/internalTrafficPolicy has value "Cluster"
   Desired Service acme-connect-api path /spec/internalTrafficPolicy has value 
   ```

   The last message reads as "the desired value is something non-printable (e.g. an empty string)", which in turn leads to the understanding that the operator will attempt to apply a patch like `{"op":"replace","path":"/spec/internalTrafficPolicy","value":""}` which might be the root cause of the issue but it's not according to the first line.

**How To Reproduce**

I didn't manage to reproduce the issue in minikube (Kubernetes 1.23.3). When I deployed Strimzi as described the in [[documentation](https://strimzi.io/quickstarts/)](https://strimzi.io/quickstarts/) and created a `KafkaConnect` resource below, it didn't lead to Strimzi creating an `-api` service. In the environment where the issue is reproducible, we use the Topic and Cluster operators.

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    app: kc
  name: kc
spec:
  bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9093
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  image: strimzi/kafka:0.30.0-kafka-3.2.0
  replicas: 1
  template:
    deployment:
      deploymentStrategy: Recreate
  tls:
    trustedCertificates: []
  version: 3.2.0
```

I can try to reproduce the issue in isolation or provide more details upon request.

**Expected behavior**

Strimzi ignores the default value and does not attempt to patch the service.

**Environment (please complete the following information):**

 - Strimzi version: 0.30.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.23
 - Infrastructure: AWS EC2, kOps

**YAML files and logs**

```
2022-10-05 20:56:07 DEBUG AbstractResourceOperator:115 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Service acme/acme-connect-api already exists, patching it
2022-10-05 20:56:07 DEBUG ResourceDiff:33 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/metadata/managedFields"}
2022-10-05 20:56:07 DEBUG ResourceDiff:33 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/spec/clusterIP"}
2022-10-05 20:56:07 DEBUG ResourceDiff:33 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/spec/clusterIPs"}
2022-10-05 20:56:07 DEBUG ResourceDiff:38 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Service acme-connect-api differs: {"op":"remove","path":"/spec/internalTrafficPolicy"}
2022-10-05 20:56:07 DEBUG ResourceDiff:39 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Current Service acme-connect-api path /spec/internalTrafficPolicy has value "Cluster"
2022-10-05 20:56:07 DEBUG ResourceDiff:40 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Desired Service acme-connect-api path /spec/internalTrafficPolicy has value 
2022-10-05 20:56:07 DEBUG AbstractResourceOperator:249 - Reconciliation #12897(timer) KafkaConnect(acme/acme): Caught exception while patching Service acme-connect-api in namespace acme
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://100.64.0.1/api/v1/namespaces/acme/services/acme-connect-api. Message: the server rejected our request due to an error in our request. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server rejected our request due to an error in our request, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:411) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:654) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$3(HasMetadataOperation.java:243) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:248) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:258) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:43) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.Patchable.patch(Patchable.java:35) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:245) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:239) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
	at io.strimzi.operator.common.operator.resource.ServiceOperator.internalPatch(ServiceOperator.java:95) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
	at io.strimzi.operator.common.operator.resource.ServiceOperator.internalPatch(ServiceOperator.java:29) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:116) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Additional context**
Applying the same patch to the same resource via `kubectl` results in a 200 response (not a 422):

```shell
kubectl -v6 \
    patch svc acme-connect-api \
    --type=json \
    -p='[{"op":"remove","path":"/spec/internalTrafficPolicy"}]'
...
I1006 22:12:29.502240   73865 round_trippers.go:553] PATCH https://api.example.com/api/v1/namespaces/acme/services/acme-connect-api?fieldManager=kubectl-patch 200 OK in 223 milliseconds
service/acme-connect-api patched
```

But the patch still shouldn't be attempted because it doesn't lead to any changes:

```shell
kubectl \
    get svc acme-connect-api \
    -o jsonpath="{.spec.internalTrafficPolicy}"

Cluster
```

**Comment by scholzj** [comment]
I was not able to reproduce it with latest Strimzi version and I do not see any reason for why this patch would be rejected. In any case, I opened #7448 which should ignore this property => if nothing else, it should help to minimize the number of unnecessary requests issued to the API server.

**Comment by morozov** [comment]
> I do not see any reason for why this patch would be rejected.

Unfortunately, I don't either 🤷 

> Was it happening persistently? Or was it one-time error?

It's been happening consistently across all our environments running Strimzi and Kafka Connect for the past 7 days according to JMX metrics. Unfortunately, our Strimzi logs are persisted, but I can tell that the reconciliation errors as in the description have been consistently happening for the last few days.

> In any case, I opened #7448 which should ignore this property => if nothing else, it should help to minimize the number of unnecessary requests issued to the API server.

In my understanding, it should help. Thanks for considering this, @scholzj!

**Comment by scholzj** [comment]
Out of curiosity, what Kubernetes distribution are you using?

**Comment by morozov** [comment]
It's kOps 1.23.3. But as I said, if I just do the patch, it works fine. In theory, it's possible that Strimzi sends some additional headers or whatever with the patch that make it fail but I didn't dig that deep.

**Comment by scholzj** [comment]
Hmm, interesting. I expected something special. kOps should be fairly clean Kubernetes. Do you have any chance to try if the images from the main branch fixed the issue on your cluster? If it really helps and if you need it, maybe we can do some patch release. But I'm a bit reluctant to do it without actually knowing it fixes something. (That said I think we were hoping for next release end of October or early November.

**Comment by morozov** [comment]
> Do you have any chance to try if the images from the main branch fixed the issue on your cluster?

Would it be `quay.io/strimzi/operator:latest` or there are other nightly image builds? I should be able to. I see these patches periodically happening in a dev cluster but unfortunately, they don't fail:

```
2022-10-10 23:26:39 DEBUG ResourceDiff:38 - Reconciliation #55416(timer) KafkaConnect(acme/acme): Service acme-connect-api differs: {"op":"remove","path":"/spec/internalTrafficPolicy"}
2022-10-10 23:26:39 DEBUG ResourceDiff:39 - Reconciliation #55416(timer) KafkaConnect(acme/acme): Current Service acme-connect-api path /spec/internalTrafficPolicy has value "Cluster"
2022-10-10 23:26:39 DEBUG ResourceDiff:40 - Reconciliation #55416(timer) KafkaConnect(acme/acme): Desired Service acme-connect-api path /spec/internalTrafficPolicy has value
2022-10-10 23:26:39 DEBUG AbstractResourceOperator:246 - Reconciliation #55416(timer) KafkaConnect(acme/acme): Service acme-connect-api in namespace acme has been patched
```

I could at least verify that they no longer happen, so they won't fail either.

I dug a bit more and collected a few more data points:

1. The "Failure executing: PATCH" messages are preceded by `{"op":"remove","path":"/spec/internalTrafficPolicy"}` only in one if our clusters. Although there are patch failures peceeded by "createOrUpdate failed" across all clusters.

2. The failures of the latter type don't have the details of what exactly is being updated. For instance:

   ```
   2022-10-10 23:56:07 DEBUG AbstractResourceOperator:249 - Reconciliation #164228(timer) KafkaConnect(acme/acme): Caught exception while patching Service acme-connect-api in namespace acme
   io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://100.64.0.1/api/v1/namespaces/acme/services/acme-connect-api. Message: the server rejected our request due to an error in our request. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server rejected our request due to an error in our request, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:411) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:654) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$3(HasMetadataOperation.java:243) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:248) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:258) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:43) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.fabric8.kubernetes.client.dsl.Patchable.patch(Patchable.java:35) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
   	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:245) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
   	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:239) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
   	at io.strimzi.operator.common.operator.resource.ServiceOperator.internalPatch(ServiceOperator.java:95) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
   	at io.strimzi.operator.common.operator.resource.ServiceOperator.internalPatch(ServiceOperator.java:29) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
   	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:116) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
   	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
   	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
   	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
   	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
   	at java.lang.Thread.run(Thread.java:829) ~[?:?]
   ```

3. All patch failures are exclusively related to the Service resources owned by Strimzi.

4. The Kubernetes and Strimzi versions are consistent across all clusters. I haven't checked if Strimzi CRDs are consistent across them all but the failure looks unrelated since it's not a custom resource being patched.

So there's definitely some homework for me to do and see why the behavior across clusters is different. In terms of software versions and configuration in general, they should be all the same.

Is there an option in the Cluster Operator to make it log the response body from the Kubernetes API in the case of a failure?

**Comment by scholzj** [comment]
Are you sure you have the _latest_ `latest` version? Can't it be some stale container image or something? I get this in my logs for the latest `main` branch build:

```
2022-10-12 10:17:21 DEBUG AbstractResourceOperator:121 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Service myproject/my-connect-connect-api already exists, patching it
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #11(timer) Kafka(myproject/my-cluster): Ignoring Secret my-cluster-cluster-operator-certs diff {"op":"remove","path":"/metadata/creationTimestamp"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #11(timer) Kafka(myproject/my-cluster): Ignoring Secret my-cluster-cluster-operator-certs diff {"op":"remove","path":"/metadata/managedFields"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #11(timer) Kafka(myproject/my-cluster): Ignoring Secret my-cluster-cluster-operator-certs diff {"op":"remove","path":"/metadata/resourceVersion"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #11(timer) Kafka(myproject/my-cluster): Ignoring Secret my-cluster-cluster-operator-certs diff {"op":"remove","path":"/metadata/uid"}
2022-10-12 10:17:21 DEBUG AbstractResourceOperator:255 - Reconciliation #11(timer) Kafka(myproject/my-cluster): Secret my-cluster-cluster-operator-certs in namespace myproject did not changed and doesn't need patching
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/metadata/creationTimestamp"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/metadata/managedFields"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/metadata/resourceVersion"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/metadata/uid"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/spec/clusterIP"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/spec/clusterIPs"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/spec/internalTrafficPolicy"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/spec/sessionAffinity"}
2022-10-12 10:17:21 DEBUG ResourceDiff:31 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Ignoring Service my-connect-connect-api diff {"op":"remove","path":"/status"}
2022-10-12 10:17:21 DEBUG AbstractResourceOperator:255 - Reconciliation #12(timer) KafkaConnect(myproject/my-connect): Service my-connect-connect-api in namespace myproject did not changed and doesn't need patching
```

As you can see, it ignores bunch of the differences and does not proceed with the patch (this is on Kube 1.25 -> so the ignored fields might not be identical in your case, but it ignores them).

----

As for the original issue, I do not think it has to be the `internalTrafficPolicy` what causes the issue. It prints the first difference it finds. But that does not mean it is the only one. I wonder if you might have some custom admission webhook which does some additional checks or something. That would be something would could explain why is it hard to reproduce elsewhere. But I don't know why would you have such admission webhook. So not sure.

**Comment by morozov** [comment]
> Are you sure you have the _latest_ `latest` version?

Sorry for the confusion. We use Strimzi 0.30.0 right now (as stated in the description) and I planned to test the main branch using `latest` image (if that's what you suggested) but I haven't done that yet. The logs I posted under the "dug a bit more" statement are also from Strimzi 0.30.0.

> As you can see, it ignores bunch of the differences and does not proceed with the patch [...]

Is this logic available in a stable release after 0.30.0 or it's only available as of https://github.com/strimzi/strimzi-kafka-operator/pull/7448?

I was hesitant to update Strimzi to the latest stable before I understand the root cause of the ongoing issue since the update itself can destabilize the service even more. But if it's possible that the update will improve the behavior (not necessarily address the issue), I can definitely update to 0.31.1 first. Should I? Or I just should test using the `latest` image first?

> As for the original issue, I do not think it has to be the `internalTrafficPolicy` what causes the issue. It prints the first difference it finds. But that does not mean it is the only one.

Thanks for the clarification. It wasn't obvious.

> I wonder if you might have some custom admission webhook which does some additional checks or something. That would be something would could explain why is it hard to reproduce elsewhere. But I don't know why would you have such admission webhook. So not sure.

There are no such webhooks that I'm aware of but it does look related to our infrastructure (not just Strimzi) since it behaves differently in different environments.

**Comment by scholzj** [comment]
> Is this logic available in a stable release after 0.30.0 or it's only available as of [#7448](https://github.com/strimzi/strimzi-kafka-operator/pull/7448)?
>
> I was hesitant to update Strimzi to the latest stable before I understand the root cause of the ongoing issue since the update itself can destabilize the service even more. But if it's possible that the update will improve the behavior (not necessarily address the issue), I can definitely update to 0.31.1 first. Should I? Or I just should test using the latest image first?

No, this is from the #7448 PR (the logic was there already, but the set of ignored fields was improved. But this is only in the main branch.

Strimzi 0.31 is compared to Strimzi 0.30 using a new version of the Fabric8 Kubernetes client. That might affect it as well. But not sure if it fixes it in some way or not. But 0.31 does not have the PR => that will flow into 0.32 (+ it is in the development builds from the main branch).

**Comment by morozov** [comment]
@scholzj we got the dev Cluster Operator deployed to the a dev environment and I can confirm that the unexpected reconciliations don't happen there. Here's an excerpt from the logs:
```
2022-10-19 17:53:26 DEBUG AbstractResourceOperator:121 - Reconciliation #584(timer) KafkaConnect(acme/acme): Service acme/acme-connect-api already exists, patching it
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/metadata/creationTimestamp"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/metadata/managedFields"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/metadata/resourceVersion"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/metadata/uid"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/spec/clusterIP"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/spec/clusterIPs"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/spec/internalTrafficPolicy"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/spec/sessionAffinity"}
2022-10-19 17:53:26 DEBUG ResourceDiff:31 - Reconciliation #584(timer) KafkaConnect(acme/acme): Ignoring Service acme-connect-api diff {"op":"remove","path":"/status"}
2022-10-19 17:53:26 DEBUG AbstractResourceOperator:255 - Reconciliation #584(timer) KafkaConnect(acme/acme): Service acme-connect-api in namespace acme did not changed and doesn't need patching
```

Unfortunately, the deployment took quite a while, and I lost the logs of the previous operator version in the same environment to compare them side-by-side. I cannot quickly roll back to the previous version either because it requires deploying the old cluster-level resources, and this process is insufficiently automated on our end.

To the best of my knowledge, we did have the "Failure executing: PATCH" errors there unrelated to `/spec/internalTrafficPolicy` and I no longer see them.

Would you consider tagging a stable release so that we could roll it out to all environments? In case it doesn't help and we still see the failures, I'll do more troubleshooting on our side and file a new issue with more details.

**Comment by scholzj** [comment]
Thanks for the feedback on this. We are planning to do 0.32 next week -> so you should be able to move to that once it is out.

**Comment by scholzj** [comment]
@morozov Did the 0.32 help with this? Can we close it?

**Comment by morozov** [comment]
@scholzj sorry for not getting back to you on this. Yes, it looks like that. Our metrics and logs for the past two weeks do not contain any signs of the issue. Thank you!

**Comment by scholzj** [comment]
Great, glad it looks ok now. Thanks
