### ISSUE TITLE
[systemtest] Issues with creating and using Cert-manager in `TracingAbstractST`

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#7622]
During the tracing tests, in both `OpenTracingST` and `OpenTelemetryST`, we are configuring `cert-manager`, which is needed for running Jaeger version `1.35.0` and above.

But it seems that there are few issues, which current implementation contains:

` Wait Timeout after 480000 ms waiting for Wait for Deployment: cert-manager-webhook will be ready`
```
io.strimzi.test.k8s.exceptions.KubeClusterException: 
`kubectl --namespace open-tracing-st apply -f -` got status code 1 and stderr:
------
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "[https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s"](https://cert-manager-webhook.cert-manager.svc/mutate?timeout=10s%22): x509: certificate signed by unknown authority
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "[https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s"](https://cert-manager-webhook.cert-manager.svc/mutate?timeout=10s%22): x509: certificate signed by unknown authority

------
and stdout:
------
customresourcedefinition.apiextensions.k8s.io/jaegers.jaegertracing.io configured
serviceaccount/jaeger-operator created
role.rbac.authorization.k8s.io/leader-election-role created
role.rbac.authorization.k8s.io/prometheus created
clusterrole.rbac.authorization.k8s.io/jaeger-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/manager-role configured
clusterrole.rbac.authorization.k8s.io/proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/leader-election-rolebinding created
rolebinding.rbac.authorization.k8s.io/prometheus created
clusterrolebinding.rbac.authorization.k8s.io/jaeger-operator-proxy-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding unchanged
service/jaeger-operator-metrics created
service/jaeger-operator-webhook-service created
deployment.apps/jaeger-operator created
mutatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-mutating-webhook-configuration configured
validatingwebhookconfiguration.admissionregistration.k8s.io/jaeger-operator-validating-webhook-configuration configured

------
	at io.strimzi.test.executor.Exec.exec(Exec.java:223)
	at io.strimzi.test.executor.Exec.exec(Exec.java:149)
	at io.strimzi.test.k8s.cmdClient.BaseCmdKubeClient.applyContent(BaseCmdKubeClient.java:223)
	at io.strimzi.test.k8s.cmdClient.BaseCmdKubeClient.applyContent(BaseCmdKubeClient.java:37)
	at io.strimzi.systemtest.tracing.TracingAbstractST.deployJaegerContent(TracingAbstractST.java:571)
	at io.strimzi.systemtest.tracing.TracingAbstractST.deployJaegerOperator(TracingAbstractST.java:580)
	at io.strimzi.systemtest.tracing.TracingAbstractST.setup(TracingAbstractST.java:673
```

I wasn't able to reproduce these issues locally, but it's failing on all nightly builds and AZPs.

**Comment by im-konge** [comment]
Issue seems to be fixed by #7631
