### ISSUE TITLE
KafkaRebalanceOperator does not check for cluster readiness before creating KafkaRebalance resources

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#7643]
**Describe the bug**

The KafkaRebalanceAssemblyOperator does not check for Kafka cluster readiness before attempting to create `KafkaRebalance` resources. It currently checks if the `Kafka` resource exists and has Cruise Control enabled but not for Kafka cluster readiness itself. This causes the operator  to throw misleading errors like this:

```
2022-11-16 17:47:10 ERROR AbstractOperator:264 - Reconciliation #75(timer) KafkaRebalance(myproject/my-rebalance): createOrUpdate failed
java.lang.RuntimeException: Secret myproject/my-cluster-cruise-control-certs does not exist
	at io.strimzi.operator.common.Util.missingSecretException(Util.java:217) ~[io.strimzi.operator-common-0.31.1.jar:0.31.1]
	at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$reconcileRebalance$31(KafkaRebalanceAssemblyOperator.java:1184) ~[io.strimzi.cluster-operator-0.31.1.jar:0.31.1]
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.CompositeFutureImpl.complete(CompositeFutureImpl.java:172) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.CompositeFutureImpl.lambda$join$3(CompositeFutureImpl.java:109) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

To make matters worse, the `KafkaRebalance` status section remains blank without any error message describing what is wrong.

**To Reproduce**
1. Create a `Kafka` custom resource with Cruise Control enabled and resource requests that are higher than what is currently available to the nodes i.e.:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  cruiseControl: {}
  kafka:
    resources:
      requests:
        cpu: 1000
    version: 3.2.3
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
2. Create a `KafkaRebalance` custom resource
3. Check the Strimzi cluster operator logs for error

**Expected behavior**
The KafkaRebalanceAssemblyOperator should check for Kafka cluster readiness before attempting to create a `KafkaRebalance` resource and log an error that it cannot create the `KafkaRebalance` resource when the Kafka cluster it is assigned to is not ready.

**Environment (please complete the following information):**
 - Strimzi version:  0.32.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.20,
 - Infrastructure: Minikube

**Comment by ShubhamRwt** [comment]
@kyguy When the error occurs does it move the `KafkaRebalance` resource into `NotReady` state? or does it only throw these misleading errors? If I recall correctly the exception we used to get when CC was not ready was `ConnectException` which was handled.

**Comment by ShubhamRwt** [comment]
We can definitely add something to `KafkaRebalance` status for better clarity

**Comment by ShubhamRwt** [comment]
I reproduced this but I also see that with the periodic reconciliation the `KakfaRebalance` resource gets back into the ready state. Even if we add something in the status we will still get these errors. I wonder if its any good to add some `reason` in the status. @ppatierno wdyt?

**Comment by kyguy** [comment]
>  I also see that with the periodic reconciliation the KakfaRebalance resource gets back into the ready state

After the `Kafka` resource `requests` is fixed, right?

**Comment by kyguy** [comment]
> Yes, as soon as the KafkaCluster becomes Ready, the KR resource moves to PendingProposal state

That is good at least! However, we should still cover the case for when the KafkaCluster is not ready, preventing `KafkaRebalance` resources from being created when that happens and logging an error about the cluster not being ready

**Comment by ppatierno** [comment]
Not sure we can prevent the `KafkaRebalance` resource creation. It's done by the user. At least, we should track the error in the status for sure. The fact that when the Kafka cluster is ready, the `KafkaRebalance` is handled automatically is good because it highlights the resiliency of the operator handling the reconcile.

**Comment by kyguy** [comment]
Thanks @ShubhamRwt that would awesome!
