### ISSUE TITLE
[Bug]: Topic operator is not coming up with Thread blocked error

### ISSUE THREAD

**Issue by azhagesanr** [strimzi/strimzi-kafka-operator#8318]
### Bug Description

**Strimzi version used** : 0.31.1

**Spec used:**

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: check-cluster
spec:
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: "3"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 1Gi
    userOperator:
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 512Mi
  kafka:
    authorization:
      superUsers:
      - sample-superuser
      type: simple
    listeners:
    - authentication:
        type: tls
      name: siptls
      networkPolicyPeers:
      - podSelector:
          matchLabels:
            check-cluster-access: "true"
      port: 9093
      tls: true
      type: internal
    livenessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 10
    readinessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 10
    replicas: 1
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
    storage:
      class: network-block
      size: 15Gi
      type: persistent-claim
    version: 3.2.3
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 10
    readinessProbe:
      initialDelaySeconds: 20
      timeoutSeconds: 10
    replicas: 1
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
    storage:
      class: network-block
      size: 15Gi
      type: persistent-claim

**Error:**
2023-03-29 15:53:26,27051 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[blocking-startup-ops-0,5,main] has been blocked for 60872 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
    at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194) ~[?:?]
    at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796) ~[?:?]
    at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128) ~[?:?]
    at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998) ~[?:?]
    at io.strimzi.operator.topic.Session.createTopicStore(Session.java:324) ~[io.strimzi.topic-operator-0.31.1.jar:0.31.1]
    at io.strimzi.operator.topic.Session$$Lambda$215/0x0000000100346840.apply(Unknown Source) ~[?:?]
    at io.strimzi.operator.topic.Session.lambda$createTopicStoreAsync$15(Session.java:254) ~[io.strimzi.topic-operator-0.31.1.jar:0.31.1]
    at io.strimzi.operator.topic.Session$$Lambda$304/0x0000000100428840.handle(Unknown Source) ~[?:?]
    at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.ContextImpl$$Lambda$303/0x0000000100429440.handle(Unknown Source) ~[?:?]
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.ContextImpl$$Lambda$300/0x000000010042a440.run(Unknown Source) ~[?:?]
    at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.TaskQueue$$Lambda$219/0x0000000100345840.run(Unknown Source) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-03-29 15:53:27,27023 WARN  [vertx-blocked-thread-checker] BlockedThreadChecker: - Thread Thread[blocking-startup-ops-0,5,main] has been blocked for 61872 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
    at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194) ~[?:?]
    at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796) ~[?:?]
    at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128) ~[?:?]
    at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998) ~[?:?]
    at io.strimzi.operator.topic.Session.createTopicStore(Session.java:324) ~[io.strimzi.topic-operator-0.31.1.jar:0.31.1]
    at io.strimzi.operator.topic.Session$$Lambda$215/0x0000000100346840.apply(Unknown Source) ~[?:?]
    at io.strimzi.operator.topic.Session.lambda$createTopicStoreAsync$15(Session.java:254) ~[io.strimzi.topic-operator-0.31.1.jar:0.31.1]
    at io.strimzi.operator.topic.Session$$Lambda$304/0x0000000100428840.handle(Unknown Source) ~[?:?]
    at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.ContextImpl$$Lambda$303/0x0000000100429440.handle(Unknown Source) ~[?:?]
    at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.ContextImpl$$Lambda$300/0x000000010042a440.run(Unknown Source) ~[?:?]
    at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.TaskQueue$$Lambda$219/0x0000000100345840.run(Unknown Source) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]

### Steps to reproduce

1. Deploy strimzi cluster operator (version  0.31.1)
2. Apply the provided Kafka kind Spec.
3. Check the log of topic operator container

### Expected behavior

Topic operator should be running

### Strimzi version

0.31.1

### Kubernetes version

Kubernetes 1.21.2

### Installation method

Kubectl

### Infrastructure

Bare-metal

**Comment by scholzj** [comment]
You should probably share the full log from the start since thie error message is not really a root cause, it just means that something blocked it.

**Comment by scholzj** [comment]
Triaged on 6.4.2023: Without the log, there is no way to analyze what the actual issue it. Feel free to re-open the issue with a full log from the Topic Operator.
