### ISSUE TITLE
[Bug]: Cluster Operator Restarts with  LeaseLock-Exception

### ISSUE THREAD

**Issue by Brandt1930** [strimzi/strimzi-kafka-operator#8426]
### Bug Description

Once in a while the Operator stops with the exception down below. No manual intervention

### Strimzi version

0.32.0

### Kubernetes version

v1.26.3+IKS

### Installation method

Helm

### Infrastructure

IBM Cloud

### Configuration files and logs

```
2023-04-20 22:43:41 ERROR LeaderElector:142 - Exception occurred while releasing lock 'LeaseLock: kafka - strimzi-cluster-operator (strimzi-cluster-operator-56d64c8584-v47fr)'
io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LockException: Unable to update LeaseLock
        at io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LeaseLock.update(LeaseLock.java:102) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.release(LeaderElector.java:139) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.stopLeading(LeaderElector.java:120) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$null$1(LeaderElector.java:94) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$renewWithTimeout$6(LeaderElector.java:169) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$loop$8(LeaderElector.java:253) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.21.0.1/apis/coordination.k8s.io/v1/namespaces/kafka/leases/strimzi-cluster-operator. Message: Operation cannot be fulfilled on leases.coordination.k8s.io "strimzi-cluster-operator": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=coordination.k8s.io, kind=leases, name=strimzi-cluster-operator, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on leases.coordination.k8s.io "strimzi-cluster-operator": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:517) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:551) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleUpdate(OperationSupport.java:347) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleUpdate(BaseOperation.java:680) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$replace$0(HasMetadataOperation.java:167) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:172) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:113) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.replace(HasMetadataOperation.java:41) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.replace(BaseOperation.java:1043) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.replace(BaseOperation.java:88) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.LeaseLock.update(LeaseLock.java:100) ~[io.fabric8.kubernetes-client-api-6.2.0.jar:?]
        ... 13 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.21.0.1/apis/coordination.k8s.io/v1/namespaces/kafka/leases/strimzi-cluster-operator. Message: Operation cannot be fulfilled on leases.coordination.k8s.io "strimzi-cluster-operator": the object has been modified; please apply your changes to the latest version and try again. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=coordination.k8s.io, kind=leases, name=strimzi-cluster-operator, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on leases.coordination.k8s.io "strimzi-cluster-operator": the object has been modified; please apply your changes to the latest version and try again, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:709) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:689) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:640) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:576) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$retryWithExponentialBackoff$2(OperationSupport.java:618) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:277) ~[io.fabric8.kubernetes-httpclient-okhttp-6.2.0.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
2023-04-20 22:43:41 INFO  LeaderElectionManager:110 - Stopped being a leader
2023-04-20 22:43:41 INFO  Main:238 - Stopped being a leader => exiting
2023-04-20 22:43:41 INFO  ShutdownHook:40 - Shutdown started

```

**Comment by scholzj** [comment]
I'm not sure this can be avoided. The 409 error normally means a race condition -> when a resource the operator is trying to modify was modified in the meantime. I guess it can happen if for example two instances of the operator try to lock the lease at the same time. Since Kubernetes API has no locking or transactions, I'm not sure there is a way to avoid this issue. In the case of the Lease, I guess exiting the operator might be the best reaction to it.

**Comment by Brandt1930** [comment]
Ok thanks. And restarting the operator does not imply restarting all Kafka/ZK components or does it? Because after the restart I get a lot of `org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x0 is lost` and 
```2023-04-20 22:43:58 WARN  ClientCnxn:1300 - Session 0x0 for sever test-zookeeper-0.test-zookeeper-nodes.kafka.svc/172.17.16.7:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 3410ms for session id 0x0
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
2023-04-20 22:44:01 WARN  ClientCnxn:1257 - Client session timed out, have not heard from server in 3335ms for session id 0x0
2023-04-20 22:44:01 WARN  ClientCnxn:1300 - Session 0x0 for sever test-zookeeper-2.test-zookeeper-nodes.kafka.svc/172.17.47.7:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
```

**Comment by scholzj** [comment]
The operator restart itself should not affect any working Kafka or ZooKeeper clusters. In the end, it shut down, so there is not much more it can do. You can check the log of the other operator instance which took over to see what it did. But I would not expect to see any restarts there unless this happened e.g. during a Strimzi upgrade etc.

But the operator log is not complete (from start to finish). You also did not share the log from the other instance of the operator which I assume is there somewhere. If these things happen at the same time, it IMHO suggests more some outside issues -> e.g. networking (causing problems in communication with ZooKeeper as well as operator) etc. But without understanding the infrastructure, it is a bit hard to comment on what is happening.

**Comment by Brandt1930** [comment]
Thanks Jakub, unfortunately I dont have the logs of the failed ZK instance because it restarted 3 or 4 times. In the operator logs I only see the standard Reconciliation Logs and sometimes a WARNING: 
``` 2023-04-20 20:56:38 WARN  ClientCnxn:1294 - An exception was thrown while closing send thread for session 0x3000009b0f20045.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x3000009b0f20045 is lost
        at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:285) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
``` 
But I think this is out of scope for this issue. 
I just wanted to make sure the restart does not affect the Kafka/ZK Cluster stability.

**Comment by scholzj** [comment]
No, it should not affect the Kafka / ZK stability.
