### ISSUE TITLE
[Bug]: strimzi operator cannot detect actual number of kafka replica in strimzipodset

### ISSUE THREAD

**Issue by Sakib37** [strimzi/strimzi-kafka-operator#8450]
### Bug Description

We deployed kafka in GKE and it was running fine. However, recently due to a node crash we lost a kafka pod and it never came back. From the logs it seems like a DNS issue inside the GKE cluster (as reported [here](https://github.com/strimzi/strimzi-kafka-operator/issues/3971) ) but that is wrong. The actual issue is when a kafka pod is gone (kafka-2 in our case), the internal kubernetes DNS is not valid anymore. So the DNS resolution fails as shown in the log. However, the actual issue is `strimzipodset` for kafka is completely unaware of the missing kafka pod. 

So we had 3 kafka pod and our kafka-2 pod got deleted from the cluster. 
```
$ k get pod | grep kafka 
stg-eu-kafka-0                              1/1     Running            0                20h
stg-eu-kafka-1                              1/1     Running            0                20h
```

However, Strimzipodset for kafka still not aware that one pod is not available for Kafka and I think that's why operator is not trying to brought up the missing kafka pod 
```
$ k get strimzipodsets.core.strimzi.io
NAME               PODS   READY PODS   CURRENT PODS   AGE
stg-eu-kafka       3      3            3              20h
stg-eu-zookeeper   5      5            5              20h
```
I think if Strimzipodset does not detect that one pod is missing and the operator will not try to create a new pod for the missing kafka-2

### Steps to reproduce

1. Create a kafka cluster with 3 replica.
2. Delete the node where one kafka pod is scheduled (ex- kafka-2 )
3. If for some reason the pod is not becoming ready again, try `k get strimzipodsets.core.strimzi.io` command and it will show a wrong ready pod of the kafka cluster

### Expected behavior

When a pod in the Strimzipodset is missing, `k get strimzipodsets.core.strimzi.io` command shows the correct status of the pod count in the output. To elaborate, when `kafka-2` pod is not available in a cluster with 3 desired replica of kafka, the following should be the output of the command
```
$ k get strimzipodsets.core.strimzi.io
NAME               PODS   READY PODS   CURRENT PODS   AGE
stg-eu-kafka       3      2            2              20h
stg-eu-zookeeper   5      5            5              20h
```

### Strimzi version

0.34.0

### Kubernetes version

GKE v1.24.10-gke.2300

### Installation method

Helm chart

### Infrastructure

GKE 

### Configuration files and logs

logs from operator:

```
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-04-28 08:57:51 WARN  AbstractOperator:525 - Reconciliation #1258(timer) Kafka(kafka/stg-eu): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource stg-eu-kafka-2 in namespace kafka to be ready
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:167) ~[io.strimzi.operator-common-0.34.0.jar:0.34.0]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-04-28 08:58:47 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace kafka-topic
2023-04-28 08:58:47 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace kafka-user
2023-04-28 08:58:48 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace kafka
2023-04-28 08:58:48 INFO  AbstractOperator:239 - Reconciliation #1267(timer) Kafka(kafka/stg-eu): Kafka stg-eu will be checked for creation or modification
2023-04-28 08:58:48 INFO  AbstractOperator:239 - Reconciliation #1269(timer) KafkaConnect(kafka/stg-eu): KafkaConnect stg-eu will be checked for creation or modification
2023-04-28 08:58:48 INFO  AbstractOperator:380 - Reconciliation #1262(timer) KafkaConnect(kafka/kafka-connect): Reconciliation is in progress
2023-04-28 08:58:48 INFO  AbstractOperator:510 - Reconciliation #1269(timer) KafkaConnect(kafka/stg-eu): reconciled
2023-04-28 08:58:51 WARN  ClientUtils:75 - Couldn't resolve server stg-eu-kafka-2.stg-eu-kafka-brokers.kafka.svc.cluster.local:9091 from bootstrap.servers as DNS resolution failed for stg-eu-kafka-2.stg-eu-kafka-brokers.kafka.svc.cluster.local
2023-04-28 08:59:48 INFO  AbstractOperator:380 - Reconciliation #1267(timer) Kafka(kafka/stg-eu): Reconciliation is in progress
2023-04-28 08:59:48 INFO  AbstractOperator:380 - Reconciliation #1262(timer) KafkaConnect(kafka/kafka-connect): Reconciliation is in progress
2023-04-28 08:59:48 ERROR Util:166 - Reconciliation #1262(timer) KafkaConnect(kafka/kafka-connect): Exceeded timeout of 300000ms while waiting for Deployment resource kafka-connect-connect in namespace kafka to be ready

```

### Additional context

I attach a storage from a storageclass which has the following spec

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 ....
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

This was done so same volume get attached with the kafka pod when it comes back. Not sure if this can be the issue but in any case Strimzipodset should reflect actual replica count in the cluster

**Comment by scholzj** [comment]
It's not easy to say without the full logs. But it looks like the Pod informer died/is not getting any new events.

**Comment by Sakib37** [comment]
While fixing the cluster, I removed all the components and logs. Closing this issue as it is now difficult to provide more resources to debug this issue.

**Comment by djetelina** [comment]
We encountered the same issue, where after node upgrade one of our pods didn't come back. The operator logs/status only showed that it's waiting for the pod to be ready, nothing else suspicious in logs or kubernetes events. 


```
Exceeded timeout of 300000ms while waiting for Pods resource kafka-cluster-zookeeper-0 in namespace event-store to be ready  
```

We were about to remove the entire cluster (thankfully no important data on it yet), but as a last hurrah thanks to this issue I thought to restart the operator pod, which fixed the issue. 

I don't know whether we can provide any more information, but my assumption with zero knowledge of the internals (:D), I assume that the pod informing part of code there's something that probably crashed and the entire part of code stopped working.
