### ISSUE TITLE
[Bug]: unable to add trailing dot to fqdn

### ISSUE THREAD

**Issue by rjrooke** [strimzi/strimzi-kafka-operator#8520]
### Bug Description

I am trying to add trailing dots to FQDNs in my strimzi configuration - I need this to address excessive dns searches on kubernetes cluster where I am running kafka producers.  When I try to add trailing dots, the operator throws an exception:

2023-05-17 00:29:52 WARN  AbstractOperator:525 - Reconciliation #555(watch) Kafka(kafka/vcmp): Failed to reconcile
java.lang.IllegalArgumentException: Invalid DNS name: tpavcpaw112s12.vici.verizon.com.
	at io.strimzi.certs.Subject$Builder.addDnsNames(Subject.java:83) ~[io.strimzi.certificate-manager-0.33.2.jar:0.33.2]

### Steps to reproduce

in kafka resource, try to use an fqdn with a trailing dot:

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafkaresource
  namespace: kafka
spec:
  kafka:
    listeners:
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          preferredNodePortAddressType: Hostname
          bootstrap:
            nodePort: 32261
            alternativeNames:
              - 'host.mydomain.com.'

config trimmed for clarity...

### Expected behavior

I would like FQDNs with trailing dots to me allowed by the DNS name validation - I believe it is here: https://github.com/strimzi/strimzi-kafka-operator/blob/9aa9cd3143e57a3e0e9a3138ce680c3a87b2b534/certificate-manager/src/main/java/io/strimzi/certs/IpAndDnsValidation.java#L23

### Strimzi version

0.33.2

### Kubernetes version

v1.26.3

### Installation method

yaml files

### Infrastructure

bare-metal

### Configuration files and logs

2023-05-17 00:29:50 INFO  AbstractOperator:239 - Reconciliation #555(watch) Kafka(kafka/vcmp): Kafka vcmp will be checked for creation or modification
2023-05-17 00:29:52 ERROR AbstractOperator:260 - Reconciliation #555(watch) Kafka(kafka/vcmp): createOrUpdate failed
java.lang.IllegalArgumentException: Invalid DNS name: mybroker.mydomain.com.
	at io.strimzi.certs.Subject$Builder.addDnsNames(Subject.java:83) ~[io.strimzi.certificate-manager-0.33.2.jar:0.33.2]
	at io.strimzi.certs.Subject$Builder.addDnsName(Subject.java:66) ~[io.strimzi.certificate-manager-0.33.2.jar:0.33.2]
	at io.strimzi.operator.cluster.model.ClusterCa.lambda$generateBrokerCerts$4(ClusterCa.java:230) ~[io.strimzi.cluster-operator-0.33.2.jar:0.33.2]
	at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:454) ~[io.strimzi.operator-common-0.33.2.jar:0.33.2]
	at io.strimzi.operator.cluster.model.ClusterCa.generateBrokerCerts(ClusterCa.java:248) ~[io.strimzi.cluster-operator-0.33.2.jar:0.33.2]
	at io.strimzi.operator.cluster.model.KafkaCluster.generateCertificatesSecret(KafkaCluster.java:1212) ~[io.strimzi.cluster-operator-0.33.2.jar:0.33.2]
	at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.lambda$certificateSecret$48(KafkaReconciler.java:726) ~[io.strimzi.cluster-operator-0.33.2.jar:0.33.2]
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by scholzj** [comment]
Can you please explain the logic? Why should a trailing dot be in the SAN? The certificate SAN does not do any DNS searches.

**Comment by rjrooke** [comment]
Thats a good point - I wonder if there is a better way to accomplish my goal - I need the hostnames used by the producers to include the trailing dot (search kubernetes dns ndots for background) - to do so, I'm trying to set the alternativenames parameter to set the broker list for the kafka bootstrapper...  Setting the alternativenames parameter appears to have the side affect of modifying the hostnames in the cert to match - I don't know if the trailing dot affects cert validation or not.

**Comment by fvaleri** [comment]
Hi @rjrooke, one alternative could be to add the dnsConfig pod property to your client apps, but I see that this may be inconvenient if you have lots of clients.

Example:

```sh
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
  dnsConfig:
    options:
      - name: ndots
        value: "1"
```

**Comment by fvaleri** [comment]
I did some more tests enabling the trailing dot and the result is that the host is resolved:

```sh
[kafka-producer-network-thread | client-a3d3dad5-3771-40b3-b35b-b90682f4bf22] DEBUG ClientUtils - Resolved host my-cluster-kafka-1-test.apps.foo.example.com. as 192.168.1.122
```

But then you have a TLS handshake error:

```sh
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Digging a bit more I found that the generated broker certificates contain both SNAs, with and without the trailing period, so it should work. The problem is that the trailing period is not valid as SNI hostname. In recent JDK versions there is a fix for that.

https://bugs.openjdk.org/browse/JDK-8065422

I witched my client's JDK from 17.0.5 to 17.0.7 and it worked fine. 

I'll open a PR to enable the trailing period.

**Comment by rjrooke** [comment]
I set my kafka to unmanaged and updated the hostnames manually - simple test with kafdrop gave me invalid cert with hostname mis-match.  Thanks for that dnsconfig idea - I didn't know that parameter and will try for sure.  Also appreciate the PR.  Strimzi is a great operator - thanks for what you do!
