### ISSUE TITLE
[Bug]: keystore password was incorrect with MM2

### ISSUE THREAD

**Issue by ArGJolan** [strimzi/strimzi-kafka-operator#8691]
### Bug Description

The error `keystore password was incorrect` is thrown when running MirrorMaker 2 with the Kafka Connect Avro converter plugin.
It is working properly with the base image.

### Steps to reproduce

We're building a custom MirrorMaker2 image via strimzi with the following builder:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-avro-converter-build
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  bootstrapServers: kafka-production.aivencloud.com:23912
  build:
    output:
      type: docker
      image: xxxxx.dkr.ecr.eu-west-1.amazonaws.com/kafka-connect-avro-converter:7.4.0
    plugins:
      - name: kafka-connect-avro-converter
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-avro-converter/versions/7.4.0/confluentinc-kafka-connect-avro-converter-7.4.0.zip
```

Then we run it:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mirror-maker-2
spec:
  version: 3.4.0
  replicas: 1
  image: xxxxx.dkr.ecr.eu-west-1.amazonaws.com/kafka-connect-avro-converter:7.4.0
  connectCluster: "kafka-cluster-dev"
  clusters:
  #Source cluster: configuration to consume data from the source cluster
  - alias: "kafka-cluster-prod"
    bootstrapServers: kafka-production.aivencloud.com:23912
    authentication:
      type: plain
      username: avnadmin
      passwordSecret:
        secretName: aiven-kafka-prod-credentials
        password: KAFKA_PASSWORD
    tls:
      trustedCertificates:
        - secretName: aiven-kafka-prod-credentials
          certificate: ca.pem
  #Target cluster: configuration to output data to the target cluster
  - alias: "kafka-cluster-dev"
    bootstrapServers: kafka-dev.aivencloud.com:23912
    authentication:
      type: plain
      username: avnadmin
      passwordSecret:
        secretName: aiven-kafka-dev-credentials
        password: KAFKA_PASSWORD
    tls:
      trustedCertificates:
        - secretName: aiven-kafka-dev-credentials
          certificate: ca.pem
    config:
      group.id: mirror-maker-2
      config.providers: env
      config.providers.env.class: io.strimzi.kafka.EnvVarConfigProvider
      key.converter: org.apache.kafka.connect.storage.StringConverter
      value.converter: io.confluent.connect.avro.AvroConverter
      key.converter.schemas.enable: true
      value.converter.schemas.enable: true
      value.converter.schema.registry.url: "https://kafka-dev.aivencloud.com:23904"
      value.converter.basic.auth.credentials.source: "USER_INFO"
      value.converter.schema.registry.basic.auth.user.info: 'avnadmin:${env:SCHEMA_REGISTRY_DEV_PASSWORD}'
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "kafka-cluster-prod"
    targetCluster: "kafka-cluster-dev"
    sourceConnector:
      config:
        key.converter: org.apache.kafka.connect.storage.StringConverter
        value.converter: io.confluent.connect.avro.AvroConverter
        key.converter.schemas.enable: true
        value.converter.schemas.enable: true
        value.converter.schema.registry.url: "https://kafka-production.aivencloud.com:23904"
        value.converter.basic.auth.credentials.source: "USER_INFO"
        value.converter.schema.registry.basic.auth.user.info: 'avnadmin:${env:SCHEMA_REGISTRY_PROD_PASSWORD}'
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
        producer.override.batch.size: 327680
        producer.override.linger.ms: 100
        socket.connection.setup.timeout.max.ms: 90000
        socket.connection.setup.timeout.ms: 90000
        session.timeout.ms: 60000
        producer.request.timeout.ms: 60000
        consumer.request.timeout.ms: 500000
        consumer.fetch.max.bytes: 52428800
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
      tasksMax: 1
    topicsPattern: "my-topic"
  externalConfiguration:
    env:
      - name: SCHEMA_REGISTRY_PROD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: aiven-kafka-prod-credentials
            key: KAFKA_PASSWORD
      - name: SCHEMA_REGISTRY_DEV_PASSWORD
        valueFrom:
          secretKeyRef:
            name: aiven-kafka-dev-credentials
            key: KAFKA_PASSWORD
```

We then get the `keystore password was incorrect` for the dev & prod keystore. It seems that the third keystore (The Kafka Connect one that uses the dev certificate from what I understand) doesn't have this issue.

### Expected behavior

Mirrormaker starts properly.

### Strimzi version

0.35.0

### Kubernetes version

1.23

### Installation method

Helm chart

### Infrastructure

Amazon EKS

### Configuration files and logs

Stacktrace of MirrorMaker error:

```
2023-06-15 12:15:31,500 ERROR [kafka-cluster-prod->kafka-cluster-dev.MirrorHeartbeatConnector|worker] WorkerConnector{id=kafka-cluster-prod->kafka-cluster-dev.MirrorHeartbeatConnector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector) [connector-thread-kafka-cluster-prod->kafka-cluster-dev.MirrorHeartbeatConnector]
org.apache.kafka.common.KafkaException: The constructor of org.apache.kafka.clients.admin.ForwardingAdmin threw an exception
	at org.apache.kafka.common.utils.Utils.newParameterizedInstance(Utils.java:469)
	at org.apache.kafka.connect.mirror.MirrorConnectorConfig.forwardingAdmin(MirrorConnectorConfig.java:211)
	at org.apache.kafka.connect.mirror.MirrorHeartbeatConnector.start(MirrorHeartbeatConnector.java:51)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:190)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:215)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:360)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:343)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:143)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:121)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:551)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
	at org.apache.kafka.clients.admin.ForwardingAdmin.<init>(ForwardingAdmin.java:51)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.apache.kafka.common.utils.Utils.newParameterizedInstance(Utils.java:458)
	... 14 more
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/clusters/kafka-cluster-dev.truststore.p12 of type PKCS12
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:522)
	... 22 more
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/clusters/kafka-cluster-dev.truststore.p12 of type PKCS12
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:375)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:347)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createTruststore(DefaultSslEngineFactory.java:320)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:168)
	at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:140)
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180)
	... 26 more
Caused by: java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2159)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:372)
	... 32 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 36 more
```

**Comment by scholzj** [comment]
Please share the full log from the Mirror Maker as well as Cluster Operator pods to properly understand what is going on.

**Comment by ArGJolan** [comment]
Here are the logs:
[mm2.log](https://github.com/strimzi/strimzi-kafka-operator/files/11830714/mm2.log)
[strimzi-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/11830715/strimzi-operator.log)

**Comment by scholzj** [comment]
So, what is the pod doing? Is it crash looping? Restarting?

**Comment by scholzj** [comment]
I'm also not sure I follow the relationship between the Connect and Mirror Maker. You seem to be somehow mixing it together? Why? It is not really expected to mix that together in that way, so it is not really clear how that might interfere.

I doublecheck how are the files generated - if they have proper cleanup checks since that was doing similar problems. But they do seem to have them. So that should not be the case. I also wonder if there can be something wrong in your container image given the build seems to be failing. Can you reproduce it with regular Mirror Maker 2 deployment without any special stuff around some converters?

**Comment by ArGJolan** [comment]
> So, what is the pod doing? Is it crash looping? Restarting?

The pod is Running and never exiting but nothing seems to be mirrored. We saw those errors in the Mirror Maker pod and they seemed quite worrying hence the issue.

> I'm also not sure I follow the relationship between the Connect and Mirror Maker. You seem to be somehow mixing it together? Why? It is not really expected to mix that together in that way, so it is not really clear how that might interfere.
> 
> I doublecheck how are the files generated - if they have proper cleanup checks since that was doing similar problems. But they do seem to have them. So that should not be the case. I also wonder if there can be something wrong in your container image given the build seems to be failing. Can you reproduce it with regular Mirror Maker 2 deployment without any special stuff around some converters?

The context is the following: 
- We have a topic in kafka cluster A we'd like replicated in cluster B
- Topic is serialised using Avro
- Each cluster have their own Avro schema registry
- When we use Mirror Maker 2 by itself, we observe serialisation issues but the data seems to be mirrored properly
- We added Avro converter to the image and change the Connect config to use `io.confluent.connect.avro.AvroConverter` as a converter to try solve this issue

**Comment by scholzj** [comment]
So, what you might try to do to see if it fixes it is to simply delete the Pod with `kubectl`. That might solve it but might not help to figure out the actual issue. 

The custom image is problematic for me because I do not know what is inside it (especially given the build is failing in the log). But I assume that the image alone is not enough to reproduce it anyway.

**Comment by ArGJolan** [comment]
Unfortunately we have restarted the pods many times during investigation and it didn't solve the issue.

On an additional note, I'm not fully sure the image build failed. The Operator seems to be unhappy about something but the builder pod seems to have completed successfully.

```
$ kubectl get pod
NAME                                                              READY   STATUS      RESTARTS   AGE
kafka-connect-avro-converter-build-connect-build                  0/1     Completed   0          2d12h
```

```
$ kubectl logs kafka-connect-avro-converter-build-connect-build
INFO[0000] Retrieving image manifest quay.io/strimzi/kafka:0.35.0-kafka-3.4.0
INFO[0000] Retrieving image quay.io/strimzi/kafka:0.35.0-kafka-3.4.0 from registry quay.io
INFO[0001] Built cross stage deps: map[]
INFO[0001] Retrieving image manifest quay.io/strimzi/kafka:0.35.0-kafka-3.4.0
INFO[0001] Returning cached image manifest
INFO[0001] Executing 0 build triggers
INFO[0001] Building stage 'quay.io/strimzi/kafka:0.35.0-kafka-3.4.0' [idx: '0', base-idx: '-1']
INFO[0001] Unpacking rootfs as cmd RUN 'mkdir' '-p' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'curl' '-f' '-L' '--output' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' 'https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-avro-converter/versions/7.4.0/confluentinc-kafka-connect-avro-converter-7.4.0.zip'       && 'unzip' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' '-d' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'find' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a' '-type' 'l' | 'xargs' 'rm' '-f'       && 'rm' '-vf' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' requires it.
INFO[0011] USER root:root
INFO[0011] Cmd: USER
INFO[0011] RUN 'mkdir' '-p' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'curl' '-f' '-L' '--output' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' 'https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-avro-converter/versions/7.4.0/confluentinc-kafka-connect-avro-converter-7.4.0.zip'       && 'unzip' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' '-d' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'find' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a' '-type' 'l' | 'xargs' 'rm' '-f'       && 'rm' '-vf' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip'
INFO[0011] Initializing snapshotter ...
INFO[0011] Taking snapshot of full filesystem...
INFO[0015] Cmd: /bin/sh
INFO[0015] Args: [-c 'mkdir' '-p' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'curl' '-f' '-L' '--output' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' 'https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-avro-converter/versions/7.4.0/confluentinc-kafka-connect-avro-converter-7.4.0.zip'       && 'unzip' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' '-d' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'find' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a' '-type' 'l' | 'xargs' 'rm' '-f'       && 'rm' '-vf' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip']
INFO[0015] Util.Lookup returned: &{Uid:0 Gid:0 Username:root Name: HomeDir:/root}
INFO[0015] Performing slow lookup of group ids for root
INFO[0015] Running: [/bin/sh -c 'mkdir' '-p' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'curl' '-f' '-L' '--output' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' 'https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-avro-converter/versions/7.4.0/confluentinc-kafka-connect-avro-converter-7.4.0.zip'       && 'unzip' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip' '-d' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a'       && 'find' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a' '-type' 'l' | 'xargs' 'rm' '-f'       && 'rm' '-vf' '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip']
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4258k  100 4258k    0     0  84.8M      0 --:--:-- --:--:-- --:--:-- 84.8M
Archive:  /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip
   creating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/kafka-avro-serializer-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/kafka-schema-converter-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/doc/version.txt
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/commons-compress-1.21.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/doc/README.md
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/snakeyaml-2.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/doc/LICENSE-Apache
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/common-utils-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/kafka-connect-avro-converter-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/kafka-schema-registry-client-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/doc/LICENSE-ConfluentCommunity
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/swagger-annotations-2.1.10.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/doc/LICENSE
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/kafka-schema-serializer-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/manifest.json
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/logredactor-1.0.11.jar
   creating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/assets/
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/re2j-1.6.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/assets/confluent.png
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/minimal-json-0.9.5.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/logredactor-metrics-1.0.11.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/slf4j-api-1.7.36.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/kafka-connect-avro-data-7.4.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/avro-1.11.0.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/jackson-core-2.14.2.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/jackson-databind-2.14.2.jar
  inflating: /opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a/confluentinc-kafka-connect-avro-converter-7.4.0/lib/jackson-annotations-2.14.2.jar
removed '/opt/kafka/plugins/kafka-connect-avro-converter/0c9b276a.zip'
INFO[0016] Taking snapshot of full filesystem...
INFO[0016] USER 1001
INFO[0016] Cmd: USER
INFO[0016] Pushing image to xxxx.dkr.ecr.eu-west-1.amazonaws.com/kafka-connect-avro-converter:7.4.0
INFO[0017] Pushed xxxx.dkr.ecr.eu-west-1.amazonaws.com/kafka-connect-avro-converter@sha256:0870820029c6f670d5de0c49249867aca4787a22bc877347ea74c0eb4de82354
```

**Comment by scholzj** [comment]
That is strange. DEBUG logs might give you more details. But I think it simply takes the information from the pod. So, when you exec into the Mirror Maker pod, can you make sure it is using the right image with the right version? For example by running `ls -l libs/`?

**Comment by scholzj** [comment]
Triaged on 29.6.2023: Let's try to get some more information and get back to it next time.

@ArGJolan Did you had a chance to run the command as I suggested in your environment?

**Comment by scholzj** [comment]
Triaged on 13.7.2023: We didn't get any of additional information we requested, so this should be closed.
