### ISSUE TITLE
Downgrade across Kafka versions is not possible

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8869]
It seems that a downgrade of the Strimzi operator which would also require change of a Kafka version is not possible because the new Kafka versions will be considered invalid by the old operator. For example:
* Install Strimzi 0.36
* Deploy Kafka 3.5.0 with `inter.broker.protocol.version` set to `3.4`
* Once the Kafka cluster is deployed, downgrade the operator to Strimzi 0.35 and change the `Kafka.spec.kafka.version` to Kafka 3.4.0` supported by Strimzi 0.35.0.

Expected behavior would be that it downgrades the Kafka cluster. But instead, it fails because the current Kafka version is invalid (Kafka 3.5.0 read from the StrimziPodSet / Pod annotations):
```
2023-07-19 18:13:48 WARN  AbstractOperator:525 - Reconciliation #15(timer) Kafka(myproject/my-cluster): Failed to reconcile
io.strimzi.operator.cluster.KafkaUpgradeException: Unsupported Kafka.spec.kafka.version: 3.5.0. Supported versions are: [3.0.0, 3.2.3, 3.3.2, 3.0.1, 3.1.0, 3.1.1, 3.2.0, 3.1.2, 3.2.1, 3.3.1, 3.4.0, 2.1.0, 2.6.2, 2.7.1, 2.8.0, 2.8.1, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.1.1, 2.2.0, 2.2.1, 2.3.0]
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.version(KafkaVersion.java:151) ~[io.strimzi.cluster-operator-0.35.0.jar:0.35.0]
	at io.strimzi.operator.cluster.operator.assembly.VersionChangeCreator.detectToAndFromVersions(VersionChangeCreator.java:228) ~[io.strimzi.cluster-operator-0.35.0.jar:0.35.0]
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.3.8.jar:4.3.8]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The only direct workaround it is to delete the Kafka StrimziPodSet to get rid of the KAfka 3.5.0 version in the annotation and then let the Strimzi 0.35.0 operator roll out Kafka 3.4.0.

Another option is to downgrade step-by-step ... First downgrade Kafka, then operator. But when downgrading accross multiple versions, this can get quite long as described in https://github.com/orgs/strimzi/discussions/8868#discussioncomment-6491829.

**Comment by Sai-Charan-Madhvaraj** [comment]
@scholzj , One More observation is if we downgrade kafka version which is supported by same operator, then only brokers, zookeepers and exporters are getting restarted with correct version and cruise control, entity operator are not getting restarted and running with previous version of kafka.

**Comment by scholzj** [comment]
They do not depend on the version in any way. So there is no need to restart them. So that is fine.

**Comment by ppatierno** [comment]
Triaged on 27.7.2023: we agreed that maybe there is no ST covering this scenario (despite we have a lot of downgrade related tests). @im-konge will go and take a look why it's not covered and adding a new one in case. Anyway, this is an actual bug which needs to be fixed.

**Comment by im-konge** [comment]
I checked our STs and we don't have such a scenario.
I created #8930 , so it will be added to our tests, and the next time, it will be found earlier.

Sorry for the issues.

**Comment by scholzj** [comment]
Digging through the history, this was never intended to be supported. The downgrade flow in this scenario is the following:
* First downgrade Kafka within the current operator version.
* Then downgrade the operator without downgrading Kafka at the same time.
* Repeat if you need to go back multiple versions.

Jumping mutiple operator versions and KAfka versions in one go is supported only for upgrades.

We can try to improve this in the future with KRaft, but I do not think we should aim to fix it for ZooKeeper-based clusters.

**Comment by sgn2607** [comment]
@scholzj Do we have any backlog for this support in Kraft? Also can this be documented in the deployment section so that users are kept informed.

**Comment by scholzj** [comment]
I don't think there is any backlog item currently. Feel free to open one. That said, Kafka does not allow you to downgrade metadata versions, so not sure how useful it would really be.
