### ISSUE TITLE
[Bug]: MirrorMaker2 data serialization/deserializer eror

### ISSUE THREAD

**Issue by viscory** [strimzi/strimzi-kafka-operator#9147]
### Bug Description

We have two environments/ kafka clusters: a confluent kafka cluster (v6.0.1-ccs) with confluent schema registry, and a strimzi kafka (v3.5.1) cluster with an apicurio schema registry.  We are trying to migrate our data from our confluent cluster to the strimzi cluster. 

We first create the strimzi kafka cluster, then we (https://github.com/Apicurio/apicurio-registry/tree/main/utils/exportConfluent) tool to export the schemas from the confluent schema registry to the apicurio schema registry (the schema IDs no longer match after this step.) 

After this, for a specific topic, we have a connector that takes records from the topic and dumps it to our object storage service. When we replicate data using mirrormaker2, these records are replicated, but there is a problem with it such that trying to deserialize the data using schemas from apicurio yields EOFExceptions or ArrayIndexOutOfBoundsExceptions.

However, when we manually sent data to this topic, our connectors were able to successful deserialize this data using the same schema from apicurio. We believe this is an issue of the data actually replicated to the target cluster by mirrormaker. Please provide guidance on how to solve this issue:

 We are facing this error in our connections when deserializing data from our strimzi cluster 
`org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:230)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:522)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:499)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:335)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic kmon_v1_raw_specif to Avro: 
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:148)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:522)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:180)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:214)
	... 14 more
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 11
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer$DeserializationContext.read(AbstractKafkaAvroDeserializer.java:537)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:263)
	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:199)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:126)
	... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -25 out of bounds for length 2
	
`

### Strimzi version

0.36.1

### Kubernetes version

1.26

**Comment by scholzj** [comment]
I'm not sure I understand why do you expect this to be a Strimzi bug. The error seems to come from some Confluent JAR and Strimzi in general doesn't do anything with the schema registries. So I thin you would need to explain what exactly does Strimzi do wrong and how should it be fixed.

**Comment by scholzj** [comment]
Triaged on community call on 5.10.2023: Does not seem to be a Strimzi bug as Strimzi does not do anything with schema registries and (de)serialization. This should be closed. Feel free to open a discussion if you want to have a general discussion on how that might be solved.
