### ISSUE TITLE
[Bug]: zookeeper incapable to reach a quorum after a k3d cluster stop/start

### ISSUE THREAD

**Issue by mederel** [strimzi/strimzi-kafka-operator#9217]
### Bug Description

Hi,

I am reporting the issue though I have a hard time assessing whether it is only due to a local machine using in a k3d setup, or hiding a more broader issue that could happen in real world kubernetes clusters. To be proactive, I prefer reporting.

After a k3d cluster initialization and install of the provided helm chart with a strimzi kafka operator and a custom kafka cluster custom object, we perform k3d cluster stop, follow by start. In that case the zookeeper is stuck printing very often this block of lines with:

```
Couldn't bind to blabla-zookeeper-0.blabla-zookeeper-nodes.default.svc/<unresolved>:2888 (org.apache.zookeeper.server.quorum.Leader) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
java.net.SocketException: Unresolved address
```

helm chart for reproducing: [zookeeper-quorum-k3d-reproducer.zip](https://github.com/strimzi/strimzi-kafka-operator/files/12831935/zookeeper-quorum-k3d-reproducer.zip)

### Steps to reproduce

1. install k3d from https://k3d.io
2. k3d cluster create blabla
3. download and unzip helm chart
4. helm dependency update unzipped-folder
5. helm install blabla unzipped-folder
6. wait for stabilization
7. k3d cluster stop
8. k3d cluster start
9. kubectl logs blabla-zookeeper-0

### Expected behavior

Zookeeper is able to restart properly and followingly the rest of the mono-nodes cluster: kafka broker and co.

### Strimzi version

0.37.0

### Kubernetes version

Kubernetes Version: v1.27.4+k3s1

### Installation method

Helm chart (with custom object aforementioned)

### Infrastructure

k3d, kubernetes cluster running in a docker container

### Configuration files and logs

The full repeating log block is:

```
2023-10-06 14:05:54,221 INFO LOOKING (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,221 INFO New election. My id = 1, proposed zxid=0x1000000e7 (org.apache.zookeeper.server.quorum.FastLeaderElection) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,222 INFO Notification: my state:LOOKING; n.sid:1, n.state:LOOKING, n.leader:1, n.round:0x39eb, n.peerEpoch:0x1, n.zxid:0x1000000e7, message format version:0x2, n.config version:0x0 (org.apache.zookeeper.server.quorum.FastLeaderElection) [WorkerReceiver[myid=1]]
2023-10-06 14:05:54,249 INFO Authenticated Id 'CN=cluster-operator,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-14]
2023-10-06 14:05:54,249 WARN Closing connection to /10.42.0.21:59064 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-7-14]
java.io.IOException: ZK down
        at org.apache.zookeeper.server.NettyServerCnxn.receiveMessage(NettyServerCnxn.java:519)
        at org.apache.zookeeper.server.NettyServerCnxn.processMessage(NettyServerCnxn.java:368)
        at org.apache.zookeeper.server.NettyServerCnxnFactory$CnxnChannelHandler.channelRead(NettyServerCnxnFactory.java:343)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-10-06 14:05:54,422 INFO Peer state changed: leading (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO LEADING (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO minSessionTimeout set to 4000 (org.apache.zookeeper.server.ZooKeeperServer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO maxSessionTimeout set to 40000 (org.apache.zookeeper.server.ZooKeeperServer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO Response cache size is initialized with value 400. (org.apache.zookeeper.server.ResponseCache) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO Response cache size is initialized with value 400. (org.apache.zookeeper.server.ResponseCache) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO zookeeper.pathStats.slotCapacity = 60 (org.apache.zookeeper.server.util.RequestPathMetricsCollector) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO zookeeper.pathStats.slotDuration = 15 (org.apache.zookeeper.server.util.RequestPathMetricsCollector) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO zookeeper.pathStats.maxDepth = 6 (org.apache.zookeeper.server.util.RequestPathMetricsCollector) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO zookeeper.pathStats.initialDelay = 5 (org.apache.zookeeper.server.util.RequestPathMetricsCollector) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO zookeeper.pathStats.delay = 5 (org.apache.zookeeper.server.util.RequestPathMetricsCollector) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO zookeeper.pathStats.enabled = false (org.apache.zookeeper.server.util.RequestPathMetricsCollector) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO The max bytes for all large requests are set to 104857600 (org.apache.zookeeper.server.ZooKeeperServer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO The large request threshold is set to -1 (org.apache.zookeeper.server.ZooKeeperServer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 INFO Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 clientPortListenBacklog -1 datadir /var/lib/zookeeper/data/version-2 snapdir /var/lib/zookeeper/data/version-2 (org.apache.zookeeper.server.ZooKeeperServer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 ERROR Couldn't bind to blabla-zookeeper-0.blabla-zookeeper-nodes.default.svc/<unresolved>:2888 (org.apache.zookeeper.server.quorum.Leader) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
java.net.SocketException: Unresolved address
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:380)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:342)
        at org.apache.zookeeper.server.quorum.Leader.createServerSocket(Leader.java:315)
        at org.apache.zookeeper.server.quorum.Leader.lambda$new$0(Leader.java:294)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3573)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.apache.zookeeper.server.quorum.Leader.<init>(Leader.java:297)
        at org.apache.zookeeper.server.quorum.QuorumPeer.makeLeader(QuorumPeer.java:1272)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1479)
2023-10-06 14:05:54,422 WARN Unexpected exception (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
java.io.IOException: Leader failed to initialize any of the following sockets: [blabla-zookeeper-0.blabla-zookeeper-nodes.default.svc/<unresolved>:2888]
        at org.apache.zookeeper.server.quorum.Leader.<init>(Leader.java:300)
        at org.apache.zookeeper.server.quorum.QuorumPeer.makeLeader(QuorumPeer.java:1272)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1479)
2023-10-06 14:05:54,422 INFO Peer state changed: looking (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
2023-10-06 14:05:54,422 WARN PeerState set to LOOKING (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)(secure=0.0.0.0:2181)]
```

**Comment by scholzj** [comment]
`Unresolved address`? This might be related to the order in which the things start in combination with how ZooKeeper handles DNS issues (that does not seem to be great). I'm not sure Strimzi can fix anything about this.

**Comment by mederel** [comment]
I have installed different versions of the operator to find what is the ticking point.

I see the issue happening when going from strimzi-kafka-operator 0.32.0 to 0.33.0, which means from Kafka 3.3 to 3.4.

And the difference is that with kafka 3.3, the log lines are still appearing, but somehow the readiness is down, the container replaced, and from there it starts working again. So actually the bottom issue could be something a readiness change for zookeeper.

**Comment by mederel** [comment]
And looking at the healthcheck script: https://github.com/strimzi/strimzi-kafka-operator/blob/main/docker-images/kafka-based/kafka/scripts/zookeeper_healthcheck.sh script, it is clearly a change of the zookeeper healthcheck, in the java code.

So not a strimzi operator issue. I am closing.

**Comment by scholzj** [comment]
We do a lot of these issues with the updated ZooKeeper in Kafka 3.5. @ppatierno was looking into it back when it was new. But to be honest, I'm not aware of these issues with the older ZooKeeper version. I think he might have opened some ZooKeeper issues as well for it.

----

On a general note, I'm not entirely sure what your use case is. If it is just trying to do a planned shutdown of the server for the weekend and start it back on Monday. Or whether this is more a recovery after a crash. In the past, I saw problems with this "shutdown and start again the Kubernetes cluster" scenario with other Kubernetes distributions as well. They were not the same as yours -> the issues were different for example involving storage. But the core issue was the same -> the things in the Kube cluster were not started in the right order and the ZooKeeper / Kafka pods were suffering from some of the infrastructure being broken. So if this is a planed shutdown, it might be best to first shutdown the Kafka cluster in a controlled way (Pause reconciliation, Delete the Kafka StrimziPodSet, Delete the ZooKeper PodSet would be the easiest way I guess). And after the Kubernetes cluster is running again start the cluster again (by unpausing the reconciliation). This obviously does not help if it is an unplanned shutdown / crash of the Kube cluster.

**Comment by ppatierno** [comment]
Jakub is right we started to face DNS issues with ZooKeeper 3.6.4 coming with Kafka 3.5.0. Everything was working fine with older ZooKeeper used in Kafka 3.4.0. This issue is now fixed in future ZooKeeper releases so it's going to be included in newer Kafka (not 3.6.0 but possibly 3.7.0). Meanwhile, the operator has some workarounds to deal with this DNS issue. You could see some errors in the ZooKeeper log but they disappear eventually and the cluster comes up.

**Comment by adamj-m** [comment]
I sometimes (30-40% of test runs) hit the same problem running `TopicST#testDeleteTopicEnableFalse` on OSX (M2) with kind and kafka `3.6.1`. Not sure what the exact problem is, I just wanted to highlight that it's happening for system tests as well which might affect its stability.

Let's wait for kafka `3.7.0`!

**Comment by j4real2208** [comment]
@ppatierno I am curious to explore the work arounds you have mentioned in the comment above, As this would be helpful to resolve an issue I have been hitting. Thanks in advance.
