### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mibollma** [strimzi/strimzi-kafka-operator#9239]
### Bug Description

Occasionally the cluster operator seems to get stuck in a state where it can't instantiate zookeeper anymore.
This means the Strimzipodset exists but the state is empty and does not change.
The log of the cluster operator says "reconciliation in progress" and after a while "timeout waiting for Strimzipodset", not much else.
If the cluster operator pod is restarted, the Strimzipodset state changes and the zookeeper pods are started immediately.

We are currently running this operation nightly on 3 clusters on AKS and in about three months it happened four times.

Whats the best way to gather more information about whats causing the issue once we reach that state again?
The default cluster operator logs don't tell much.

### Strimzi version

0.33.2

### Kubernetes version

1.26.6

### Installation method

Helm chart

### Infrastructure

AKS

**Comment by scholzj** [comment]
You would need to share the full logs and explain what empty state means. 0.33.2 is also quite old, and several fixes related to it happened since. So I think ou should upgrade and try to reproduce it with the latest version.

**Comment by mibollma** [comment]
I'll share some more logs the next time it happens, but there is likely not more information apart from the two entries above.

**Comment by mibollma** [comment]
Bewlo you find the related logs. I'll update the issue, once we tried the latests version but it may take a few weeks/months as updating the associated CRDs on a live system is tricky sometimes.

```
2023-10-16 02:06:05 INFO  AbstractOperator:380 - Reconciliation #7642(watch) Kafka(kafka-stack-validation/kafka-stack): Reconciliation is in progress
2023-10-16 02:09:50 INFO  StrimziPodSetController:292 - Reconciliation #7687(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): StrimziPodSet will be reconciled
2023-10-16 02:09:50 INFO  StrimziPodSetController:328 - Reconciliation #7687(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): reconciled
2023-10-16 02:09:50 INFO  StrimziPodSetController:292 - Reconciliation #7688(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): StrimziPodSet will be reconciled
2023-10-16 02:09:50 INFO  StrimziPodSetController:328 - Reconciliation #7688(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): reconciled
2023-10-16 02:10:00 ERROR Util:167 - Reconciliation #7642(watch) Kafka(kafka-stack-validation/kafka-stack): Exceeded timeout of 300000ms while waiting for StrimziPodSet resource kafka-stack-kafka in namespace kafka-stack-validation to be ready
2023-10-16 02:10:00 ERROR AbstractOperator:260 - Reconciliation #7642(watch) Kafka(kafka-stack-validation/kafka-stack): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StrimziPodSet resource kafka-stack-kafka in namespace kafka-stack-validation to be ready
    at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:168) ~[io.strimzi.operator-common-0.33.2.jar:0.33.2]
    at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
    at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-10-16 02:10:00 INFO  CrdOperator:133 - Reconciliation #7642(watch) Kafka(kafka-stack-validation/kafka-stack): Status of Kafka kafka-stack in namespace kafka-stack-validation has been updated
2023-10-16 02:10:00 WARN  AbstractOperator:525 - Reconciliation #7642(watch) Kafka(kafka-stack-validation/kafka-stack): Failed to reconcile
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for StrimziPodSet resource kafka-stack-kafka in namespace kafka-stack-validation to be ready
    at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:168) ~[io.strimzi.operator-common-0.33.2.jar:0.33.2]
    at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
    at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:69) ~[io.vertx.vertx-core-4.3.7.jar:4.3.7]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.86.Final.jar:4.1.86.Final]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-10-16 02:10:00 INFO  OperatorWatcher:38 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack in namespace kafka-stack-validation was MODIFIED
2023-10-16 02:10:00 INFO  AbstractOperator:239 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:10:02 WARN  ClientCnxn:1294 - An exception was thrown while closing send thread for session 0x100802ab0880003.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x100802ab0880003 is lost
    at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:285) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
2023-10-16 02:10:03 WARN  NetworkClient:775 - [AdminClient clientId=adminclient-14297] Connection to node -3 (kafka-stack-kafka-2.kafka-stack-kafka-brokers.kafka-stack-validation.svc.cluster.local/172.18.19.168:9091) could not be established. Broker may not be available.
2023-10-16 02:10:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:10:33 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-2} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Error getting broker config, retrying after at least 250ms
2023-10-16 02:10:49 INFO  StrimziPodSetController:292 - Reconciliation #7692(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): StrimziPodSet will be reconciled
2023-10-16 02:10:49 INFO  StrimziPodSetController:328 - Reconciliation #7692(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): reconciled
2023-10-16 02:10:49 INFO  StrimziPodSetController:292 - Reconciliation #7693(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): StrimziPodSet will be reconciled
2023-10-16 02:10:49 INFO  StrimziPodSetController:328 - Reconciliation #7693(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): reconciled
2023-10-16 02:11:00 INFO  AbstractOperator:380 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Reconciliation is in progress
2023-10-16 02:11:03 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-1} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Error getting broker config, retrying after at least 250ms
2023-10-16 02:11:03 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Pod kafka-stack-kafka-0 is currently the controller and there are other pods still to roll, retrying after at least 250ms
2023-10-16 02:11:05 INFO  KafkaAvailability:135 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): issue-analysis.event.ticket-assignment.0/0 will be under-replicated (ISR={0,2}, replicas=[1,0,2], min.insync.replicas=2) if broker 2 is restarted.
2023-10-16 02:11:05 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-2} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod kafka-stack-kafka-2 is currently not rollable, retrying after at least 500ms
2023-10-16 02:11:35 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-1} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Error getting broker config, retrying after at least 500ms
2023-10-16 02:11:35 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Pod kafka-stack-kafka-0 is currently the controller and there are other pods still to roll, retrying after at least 500ms
2023-10-16 02:11:36 INFO  KafkaAvailability:135 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): issue-analysis.event.ticket-assignment.0/0 will be under-replicated (ISR={0,2}, replicas=[1,0,2], min.insync.replicas=2) if broker 2 is restarted.
2023-10-16 02:11:36 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-2} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod kafka-stack-kafka-2 is currently not rollable, retrying after at least 1000ms
2023-10-16 02:11:56 INFO  KafkaRoller:594 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Dynamic reconfiguration for broker 1 was successful.
2023-10-16 02:11:59 INFO  StrimziPodSetController:292 - Reconciliation #7694(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): StrimziPodSet will be reconciled
2023-10-16 02:11:59 INFO  StrimziPodSetController:328 - Reconciliation #7694(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): reconciled
2023-10-16 02:11:59 INFO  StrimziPodSetController:292 - Reconciliation #7695(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): StrimziPodSet will be reconciled
2023-10-16 02:11:59 INFO  StrimziPodSetController:328 - Reconciliation #7695(watch) StrimziPodSet(kafka-stack-validation/kafka-stack-kafka): reconciled
2023-10-16 02:12:00 INFO  AbstractOperator:380 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Reconciliation is in progress
2023-10-16 02:12:00 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Pod kafka-stack-kafka-0 is currently the controller and there are other pods still to roll, retrying after at least 1000ms
2023-10-16 02:12:02 INFO  KafkaAvailability:135 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): issue-analysis.event.ticket-assignment.0/0 will be under-replicated (ISR={0,2}, replicas=[1,0,2], min.insync.replicas=2) if broker 2 is restarted.
2023-10-16 02:12:02 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-2} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod kafka-stack-kafka-2 is currently not rollable, retrying after at least 2000ms
2023-10-16 02:12:02 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Pod kafka-stack-kafka-0 is currently the controller and there are other pods still to roll, retrying after at least 2000ms
2023-10-16 02:12:05 INFO  KafkaAvailability:135 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): issue-analysis.event.ticket-assignment.0/0 will be under-replicated (ISR={0,2}, replicas=[1,0,2], min.insync.replicas=2) if broker 2 is restarted.
2023-10-16 02:12:05 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-2} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod kafka-stack-kafka-2 is currently not rollable, retrying after at least 4000ms
2023-10-16 02:12:05 INFO  KafkaRoller:327 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Could not roll pod {kafka-stack-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Pod kafka-stack-kafka-0 is currently the controller and there are other pods still to roll, retrying after at least 4000ms
2023-10-16 02:12:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:12:12 INFO  KafkaRoller:594 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Dynamic reconfiguration for broker 2 was successful.
2023-10-16 02:12:14 INFO  KafkaRoller:594 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Dynamic reconfiguration for broker 0 was successful.
2023-10-16 02:12:15 INFO  Ca:363 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Generating certificate Subject(organizationName='io.strimzi', commonName='kafka-stack-entity-topic-operator', dnsNames=[], ipAddresses=[]), signed by CA cluster-ca
2023-10-16 02:12:15 INFO  Ca:363 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Generating certificate Subject(organizationName='io.strimzi', commonName='kafka-stack-entity-user-operator', dnsNames=[], ipAddresses=[]), signed by CA cluster-ca
2023-10-16 02:12:37 INFO  Ca:363 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Generating certificate Subject(organizationName='io.strimzi', commonName='kafka-stack-kafka-exporter', dnsNames=[], ipAddresses=[]), signed by CA cluster-ca
2023-10-16 02:13:00 INFO  AbstractOperator:380 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Reconciliation is in progress
2023-10-16 02:13:09 INFO  OperatorWatcher:38 - Reconciliation #7698(watch) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack in namespace kafka-stack-validation was MODIFIED
2023-10-16 02:13:09 INFO  CrdOperator:133 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): Status of Kafka kafka-stack in namespace kafka-stack-validation has been updated
2023-10-16 02:13:09 INFO  AbstractOperator:510 - Reconciliation #7689(watch) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:13:09 INFO  AbstractOperator:239 - Reconciliation #7698(watch) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:13:14 INFO  AbstractOperator:510 - Reconciliation #7698(watch) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:14:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:14:07 INFO  AbstractOperator:239 - Reconciliation #7699(timer) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:14:13 INFO  AbstractOperator:510 - Reconciliation #7699(timer) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:16:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:16:07 INFO  AbstractOperator:239 - Reconciliation #7701(timer) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:16:13 INFO  AbstractOperator:510 - Reconciliation #7701(timer) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:18:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:18:07 INFO  AbstractOperator:239 - Reconciliation #7703(timer) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:18:14 INFO  AbstractOperator:510 - Reconciliation #7703(timer) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:20:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:20:07 INFO  AbstractOperator:239 - Reconciliation #7705(timer) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:20:10 WARN  ClientCnxn:1294 - An exception was thrown while closing send thread for session 0x2008036e0c30002.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x2008036e0c30002 is lost
    at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:285) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
2023-10-16 02:20:14 INFO  AbstractOperator:510 - Reconciliation #7705(timer) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:22:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:22:07 INFO  AbstractOperator:239 - Reconciliation #7707(timer) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:22:09 WARN  ClientCnxn:1294 - An exception was thrown while closing send thread for session 0x2008036e0c30003.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x2008036e0c30003 is lost
    at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:285) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
2023-10-16 02:22:13 INFO  AbstractOperator:510 - Reconciliation #7707(timer) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:24:07 INFO  ClusterOperator:139 - Triggering periodic reconciliation for namespace *
2023-10-16 02:24:07 INFO  AbstractOperator:239 - Reconciliation #7709(timer) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack will be checked for creation or modification
2023-10-16 02:24:14 INFO  AbstractOperator:510 - Reconciliation #7709(timer) Kafka(kafka-stack-validation/kafka-stack): reconciled
2023-10-16 02:24:24 INFO  OperatorWatcher:38 - Reconciliation #7711(watch) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack in namespace kafka-stack-validation was DELETED
2023-10-16 02:24:24 INFO  AbstractOperator:274 - Reconciliation #7711(watch) Kafka(kafka-stack-validation/kafka-stack): Kafka kafka-stack should be deleted
2023-10-16 02:24:24 INFO  AbstractOperator:279 - Reconciliation #7711(watch) Kafka(kafka-stack-validation/kafka-stack): Assembly kafka-stack or some parts of it will be deleted by garbage collection
2023-10-16 02:24:24 INFO  AbstractOperator:510 - Reconciliation #7711(watch) Kafka(kafka-stack-validation/kafka-stack): reconciled
```

**Comment by scholzj** [comment]
This might be related to https://github.com/strimzi/strimzi-kafka-operator/issues/8528. Does restarting the Cluster Operator help?

**Comment by mibollma** [comment]
Yes, restarting helps.

**Comment by scholzj** [comment]
In that case it is likely the bug I linked above. The way to address it would be to upgrade.

**Comment by mibollma** [comment]
Thanks, we'll try that at some point and I'll update the issue then.

**Comment by bmanuel1974** [comment]
It looks like this problem exists even in 0.37.0.  We started to see this exact issue in 0.36.x and have upgrading hoping it would be resolved.  
* We are managing around 40+ Kafka clusters in a development cluster
* I had enabled trace logging hoping to find some information on what was stuck but I am unable to find anything in the controller logs
* Zookeeper will not get provisioned
* I have not seen this issue in clusters with a smaller number of namespaces (1 per cluster)
* We are using Karpenter to provision spot instances.

Restarting works every time.
