### ISSUE TITLE
[Enhancement]: Validate unique listener names

### ISSUE THREAD

**Issue by mausch** [strimzi/strimzi-kafka-operator#9338]
### Related problem

```
listeners:
  - name: plain
    port: 9092
    type: internal
    tls: false
  - name: plain
    port: 9093
    type: internal
    tls: false
```

This makes the operator crash with:

```
io.strimzi.operator.common.model.InvalidResourceException: Listener configuration is not valid: [every listener needs to have a unique name]
 at io.strimzi.operator.cluster.model.ListenersValidator.validate(ListenersValidator.java:48) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
 at io.strimzi.operator.cluster.model.KafkaCluster.fromCrd(KafkaCluster.java:321) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
 at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.<init>(KafkaReconciler.java:204) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
 at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.kafkaReconciler(KafkaAssemblyOperator.java:549) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
 at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$kafkaReconciler$8(KafkaAssemblyOperator.java:618) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
 at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.CompositeFutureImpl.complete(CompositeFutureImpl.java:172) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.CompositeFutureImpl.lambda$join$3(CompositeFutureImpl.java:109) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
 at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.100.Final.jar:4.1.100.Final]
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
 at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

It would be nice to validate this when submitting the resource so users don't have to go digging in the operator logs to find why things aren't working.

### Suggested solution

Validate resource when submitting

**Comment by ppatierno** [comment]
> It would be nice to validate this when submitting the resource so users don't have to go digging in the operator logs to find why things aren't working.

When you submit a resource to the Kubernetes API, it goes through the CRD validation looking for fields and valid corresponding value types. Specifically in your case it can validate that `name` field is there and it's a string but nothing more than that. It can't go through the entire list and check for duplicates, it's not part of a base CRD validation by K8S.
For this reason, it's an operator logic to validate it.
I am not sure we can do better here.

**Comment by scholzj** [comment]
Discussed on the community call on 30.11.2023: There does not seem to be any simple way to validate this within the CRD. (Can a CEL validation rule be written for it?) If you are aware of any option, please let us know. But we do not see anything we can do about this right now.
