### ISSUE TITLE
[Bug]: Optional Kafka Authentication Properties Cause Repeated NullPointerException in Cluster Operator

### ISSUE THREAD

**Issue by MarkintoshZ** [strimzi/strimzi-kafka-operator#9398]
### Bug Description

The `strimzi-cluster-operator` throws `NullPointerException` in a loop when optional Kafka authentication properties (e.g. `checkIssuer`) for authentication type `oauth` are set when authentication type is `custom`.

### Steps to reproduce

Deploy a Kafka cluster with one of the listerns' authentication to be `custom` type, while setting the checkIssuer to be `true`

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    replicas: 1
    listeners:
    - authentication:
        type: custom
        checkIssuer: true
      name: plain
      port: 9092
      tls: false
      type: internal
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
```
Deploy with version 0.38.0
```bash
kubectl create namespace kafka
kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka'
kubectl apply -f cr.yaml -n kafka
```
Observe the exception logs from `strimzi-cluster-operator` pod

### Expected behavior

According to the [docs](https://strimzi.io/docs/operators/latest/deploying#:~:text=Depending%20on%20how%20you%20apply%20OAuth%202.0%20authentication%2C%20and%20the%20type%20of%20authorization%20server%2C%20there%20are%20additional%20(optional)%20configuration%20settings%20you%20can%20use), `checkIssuer` is one of many optional configurations that could be applied when the authentication type is `oauth`.  When `checkIssuer` is provided without `oauth` authentication type (e.g. using `custom` instead), it is expected for the operator to reject the config through apiserver-side validation. However in reality, the additional (optional) config causes the `strimzi-cluster-operator` to throw `NullPointerException` in a loop and the state would never reconcile.

### Strimzi version

0.38.0

### Kubernetes version

Kubernetes v1.27.3

### Installation method

YAML strimzi.io/install

### Infrastructure

Kind

### Configuration files and logs

The exception logs from `strimzi-cluster-operator` pod
```java
2023-11-22 23:34:24 INFO  AbstractOperator:511 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Kafka test-cluster in namespace kafka was ADDED
2023-11-22 23:34:24 WARN  StatusUtils:159 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Resource Kafka(kafka/test-cluster) contains object at path spec.kafka.listeners.auth with an unknown property: checkIssuer
2023-11-22 23:34:24 WARN  StatusUtils:159 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Resource Kafka(kafka/test-cluster) contains object at path spec.kafka.listeners.auth with an unknown property: checkIssuer
2023-11-22 23:34:24 INFO  AbstractOperator:265 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Kafka test-cluster will be checked for creation or modification
2023-11-22 23:34:24 INFO  CrdOperator:131 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Status of Kafka test-cluster in namespace kafka has been updated
2023-11-22 23:34:24 INFO  AbstractOperator:511 - Reconciliation #2(watch) Kafka(kafka/test-cluster): Kafka test-cluster in namespace kafka was MODIFIED
2023-11-22 23:34:24 INFO  Ca:988 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Generating CA with subject=Subject(organizationName='io.strimzi', commonName='cluster-ca v0', dnsNames=[], ipAddresses=[])
2023-11-22 23:34:24 INFO  Ca:988 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Generating CA with subject=Subject(organizationName='io.strimzi', commonName='clients-ca v0', dnsNames=[], ipAddresses=[])
2023-11-22 23:34:25 INFO  Ca:417 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Generating certificate Subject(organizationName='io.strimzi', commonName='cluster-operator', dnsNames=[], ipAddresses=[]), signed by CA cluster-ca
2023-11-22 23:34:25 INFO  Ca:417 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Generating certificate Subject(organizationName='io.strimzi', commonName='test-cluster-zookeeper', dnsNames=[test-cluster-zookeeper-client.kafka, test-cluster-zookeeper-client.kafka.svc, *.test-cluster-zookeeper-nodes.kafka.svc, test-cluster-zookeeper-0.test-cluster-zookeeper-nodes.kafka.svc.cluster.local, *.test-cluster-zookeeper-nodes.kafka.svc.cluster.local, test-cluster-zookeeper-0.test-cluster-zookeeper-nodes.kafka.svc, test-cluster-zookeeper-client, test-cluster-zookeeper-0, test-cluster-zookeeper-client.kafka.svc.cluster.local, *.test-cluster-zookeeper-client.kafka.svc, *.test-cluster-zookeeper-client.kafka.svc.cluster.local], ipAddresses=[]), signed by CA cluster-ca
2023-11-22 23:34:26 INFO  StrimziPodSetController:378 - Reconciliation #3(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:34:26 INFO  StrimziPodSetController:414 - Reconciliation #3(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:34:26 INFO  StrimziPodSetController:378 - Reconciliation #4(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:34:26 INFO  StrimziPodSetController:414 - Reconciliation #4(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:34:26 INFO  StrimziPodSetController:378 - Reconciliation #5(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:34:26 INFO  StrimziPodSetController:414 - Reconciliation #5(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:34:30 INFO  StrimziPodSetController:378 - Reconciliation #6(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:34:30 INFO  StrimziPodSetController:414 - Reconciliation #6(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:34:30 INFO  StrimziPodSetController:378 - Reconciliation #7(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:34:30 INFO  StrimziPodSetController:414 - Reconciliation #7(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:34:53 INFO  StrimziPodSetController:378 - Reconciliation #8(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:34:53 INFO  StrimziPodSetController:414 - Reconciliation #8(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:35:10 INFO  StrimziPodSetController:378 - Reconciliation #9(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:35:10 INFO  StrimziPodSetController:414 - Reconciliation #9(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:35:10 INFO  StrimziPodSetController:378 - Reconciliation #10(watch) StrimziPodSet(kafka/test-cluster-zookeeper): StrimziPodSet will be reconciled
2023-11-22 23:35:10 INFO  StrimziPodSetController:414 - Reconciliation #10(watch) StrimziPodSet(kafka/test-cluster-zookeeper): reconciled
2023-11-22 23:35:12 INFO  Ca:417 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Generating certificate Subject(organizationName='io.strimzi', commonName='test-cluster-kafka', dnsNames=[test-cluster-kafka-brokers.kafka.svc, test-cluster-kafka-brokers.kafka.svc.cluster.local, test-cluster-kafka-0.test-cluster-kafka-brokers.kafka.svc, test-cluster-kafka-brokers.kafka, test-cluster-kafka-brokers, test-cluster-kafka-bootstrap.kafka.svc, test-cluster-kafka-bootstrap.kafka.svc.cluster.local, test-cluster-kafka-bootstrap.kafka, test-cluster-kafka-0.test-cluster-kafka-brokers.kafka.svc.cluster.local, test-cluster-kafka-bootstrap], ipAddresses=[]), signed by CA cluster-ca
2023-11-22 23:35:12 ERROR AbstractOperator:284 - Reconciliation #1(watch) Kafka(kafka/test-cluster): createOrUpdate failed
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "io.strimzi.api.kafka.model.listener.KafkaListenerAuthenticationCustom.getListenerConfig()" is null
        at io.strimzi.operator.cluster.model.KafkaBrokerConfigurationBuilder.configureAuthentication(KafkaBrokerConfigurationBuilder.java:498) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.model.KafkaBrokerConfigurationBuilder.withListeners(KafkaBrokerConfigurationBuilder.java:294) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.model.KafkaCluster.generatePerBrokerConfiguration(KafkaCluster.java:1619) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.model.KafkaCluster.generatePerBrokerConfigurationConfigMaps(KafkaCluster.java:1662) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.lambda$perBrokerKafkaConfiguration$42(KafkaReconciler.java:632) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
2023-11-22 23:35:12 INFO  CrdOperator:131 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Status of Kafka test-cluster in namespace kafka has been updated
2023-11-22 23:35:12 INFO  AbstractOperator:511 - Reconciliation #11(watch) Kafka(kafka/test-cluster): Kafka test-cluster in namespace kafka was MODIFIED
2023-11-22 23:35:12 WARN  StatusUtils:159 - Reconciliation #11(watch) Kafka(kafka/test-cluster): Resource Kafka(kafka/test-cluster) contains object at path spec.kafka.listeners.auth with an unknown property: checkIssuer
2023-11-22 23:35:12 WARN  StatusUtils:159 - Reconciliation #11(watch) Kafka(kafka/test-cluster): Resource Kafka(kafka/test-cluster) contains object at path spec.kafka.listeners.auth with an unknown property: checkIssuer
2023-11-22 23:35:12 INFO  AbstractOperator:265 - Reconciliation #11(watch) Kafka(kafka/test-cluster): Kafka test-cluster will be checked for creation or modification
2023-11-22 23:35:12 WARN  AbstractOperator:557 - Reconciliation #1(watch) Kafka(kafka/test-cluster): Failed to reconcile
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "io.strimzi.api.kafka.model.listener.KafkaListenerAuthenticationCustom.getListenerConfig()" is null
        at io.strimzi.operator.cluster.model.KafkaBrokerConfigurationBuilder.configureAuthentication(KafkaBrokerConfigurationBuilder.java:498) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.model.KafkaBrokerConfigurationBuilder.withListeners(KafkaBrokerConfigurationBuilder.java:294) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.model.KafkaCluster.generatePerBrokerConfiguration(KafkaCluster.java:1619) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.model.KafkaCluster.generatePerBrokerConfigurationConfigMaps(KafkaCluster.java:1662) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.lambda$perBrokerKafkaConfiguration$42(KafkaReconciler.java:632) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
...
```

### Potential Fix
One potential fix could be using the Kubernetes CRD [validation rules](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules) to reject semantically incorrect configs to avoid runtime errors caused by unexpected input configurations.

We have tried this fix and confirmed this can fix the problem. We are happy to submit a PR to fix this.

For example
```yaml
authentication:
  type: object
  x-kubernetes-validations:
    - rule: "self.type != 'oauth' && !has(self.checkIssuer)"
      message: "checkIssuer property is only valid when authentication type is 'oauth'."
  properties:
    type:
      type: string
      enum:
      - tls
      - scram-sha-512
      - oauth
      - custom
    checkIssuer:
      type: boolean
      description: Enable or disable issuer checking. By default issuer is checked using the value configured by `validIssuerUri`. Default value is `true`.
    ...
```

**Comment by scholzj** [comment]
Having some CEL validation rules support would be definitely a nice contribution. But:
* It would be good to understand first how you plan to generate the validation rules from the Java code (as you cannot simply just edit the CRD and add it there -> they are all generated from the code)
* We have to make sure it scales well when used for all fields like this which there are quite a many
* We have to make sure it does not break the CRDs on the older Kubernetes versions. I'm not sure if this breaks support of older versions or not - but some new features in the past did it. So we need to be careful about it.

The NPE exception itself is not nice, but I actually don't think it has anything to do with the `checkIssuer` field you set there but rather with the missing `listenerConfig` field. So actually, the fix for it is completely different. So if you want, you can open PR for that as well, it would be great. If not, please let me know and I will fix it.

**Comment by MarkintoshZ** [comment]
You are right. The problem is with the missing `listenerConfig` field. I will try to submit a PR some time this week.

Thanks for highlighting the potential challenges with adding support for CEL validation rules as well. Sounds like it is not a trivial project. I might look into it if I have time this holiday season.

**Comment by scholzj** [comment]
I opened #9417 for the CEL validation.

**Comment by MarkintoshZ** [comment]
Hi, @scholzj. I was busy with schoolwork in the past few weeks so I'm sorry for not getting back to you sooner. I'll try to make a PR in the next few days.

**Comment by scholzj** [comment]
@MarkintoshZ Great. No worries.
