### ISSUE TITLE
Failed to register kafka connect plugin

### ISSUE THREAD

**Issue by gaozuo** [strimzi/strimzi-kafka-operator#9570]
### Bug Description
An error [rg.apache.kafka.common.errors.InvalidOffsetException] will occur when registering an oracle debezium plug-in using kafka connect rest api

### Steps to reproduce

[Dockerfile](https://github.com/strimzi/strimzi-kafka-operator/files/13988081/Dockerfile.txt)
[kafka-stream-connect.yaml](https://github.com/strimzi/strimzi-kafka-operator/files/13988082/kafka-stream-connect.txt)
[kafka-stream-single.yaml](https://github.com/strimzi/strimzi-kafka-operator/files/13988083/kafka-stream-single.txt)
[kafka-stream-registry-values.yaml](https://github.com/strimzi/strimzi-kafka-operator/files/13988084/kafka-stream-registry-values.txt)

**Build kafka connect image**
`docker build -t repo:tag .`

**Install kafka environment**
```
kubectl apply -f kafka-stream-single.yaml

git clone https://github.com/confluentinc/cp-helm-charts.git
helm install cp-helm-charts
helm install kafka-stream-registry --values kafka-stream-registry-values.yaml cp-helm-charts/charts/cp-schema-registry
```

**This image was built using the dockerfile **
`kubectl apply -f kafka-stream-connect.yaml  `

**register a oracle debezium plugin**

```
curl -X POST -H "Content-Type: application/json" --data '{
    "name": "HR_DB_CDC",
    "config": {
        "connector.class": "io.debezium.connector.oracle.OracleConnector",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "topic.prefix": "HR",
        "database.hostname": "***",
        "database.port": "1521",
        "database.user": "dbzuser",
        "database.password": "***",
        "database.dbname": "ORCL",
        "log.mining.strategy": "online_catalog",
        "decimal.handling.mode": "string",
        "schema.history.internal.store.only.captured.tables.ddl": "true",
        "schema.history.internal.store.only.captured.databases.ddl": "true",
        "table.include.list": "***",
        "schema.history.internal.kafka.bootstrap.servers": "kafka-stream-bk-kafka-bootstrap:9092",
        "value.converter.schema.registry.url": "http://kafka-stream-registry-cp-schema-registry:8081",
        "schema.history.internal.kafka.topic": "schema-changes.inventory",
        "key.converter.schema.registry.url": "http://kafka-stream-registry-cp-schema-registry:8081"
    }
}' http://<kafka-connect-host>:<kafka-connect-port>/connectors
```

`kubectl logs -f <kafka-connect-pod-name>`
2024-01-18 08:02:37,474 INFO 10.42.0.58 - - [18/Jan/2024:08:02:37 +0000] "GET /connectors?expand=info&expand=status HTTP/1.1" 200 4038 "-" "Redpanda Console" 6 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1839644942-52]
2024-01-18 08:02:37,476 INFO 10.42.0.58 - - [18/Jan/2024:08:02:37 +0000] "GET / HTTP/1.1" 200 91 "-" "Redpanda Console" 1 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1839644942-52]
2024-01-18 08:02:37,544 INFO 10.42.0.58 - - [18/Jan/2024:08:02:37 +0000] "GET / HTTP/1.1" 200 91 "-" "Redpanda Console" 2 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1839644942-36]
2024-01-18 08:02:37,545 INFO 10.42.0.58 - - [18/Jan/2024:08:02:37 +0000] "GET /connector-plugins HTTP/1.1" 200 911 "-" "Redpanda Console" 1 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1839644942-36]
2024-01-18 08:02:37,948 INFO SourceConnectorConfig values:
        config.action.reload = restart
        connector.class = io.debezium.connector.oracle.OracleConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        exactly.once.support = requested
        header.converter = class org.apache.kafka.connect.storage.SimpleHeaderConverter
        key.converter = class io.confluent.connect.avro.AvroConverter
        name = HR_DB_CDC
        offsets.storage.topic = null
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transaction.boundary = poll
        transaction.boundary.interval.ms = null
        transforms = []
        value.converter = class io.confluent.connect.avro.AvroConverter
 (org.apache.kafka.connect.runtime.SourceConnectorConfig) [DistributedHerder-connect-1-1]
2024-01-18 08:02:37,948 INFO EnrichedConnectorConfig values:
        config.action.reload = restart
        connector.class = io.debezium.connector.oracle.OracleConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        exactly.once.support = requested
        header.converter = class org.apache.kafka.connect.storage.SimpleHeaderConverter
        key.converter = class io.confluent.connect.avro.AvroConverter
        name = HR_DB_CDC
        offsets.storage.topic = null
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transaction.boundary = poll
        transaction.boundary.interval.ms = null
        transforms = []
        value.converter = class io.confluent.connect.avro.AvroConverter
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig) [DistributedHerder-connect-1-1]
2024-01-18 08:02:37,954 ERROR Failed to write task configurations to Kafka (org.apache.kafka.connect.storage.KafkaConfigBackingStore) [DistributedHerder-connect-1-1]
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownServerException: The server experienced an unexpected error when processing the request.
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:97)
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:79)
        at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30)
        at org.apache.kafka.connect.storage.KafkaConfigBackingStore.sendPrivileged(KafkaConfigBackingStore.java:805)
        at org.apache.kafka.connect.storage.KafkaConfigBackingStore.putTaskConfigs(KafkaConfigBackingStore.java:594)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$writeTaskConfigs$46(DistributedHerder.java:2139)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.writeToConfigTopicAsLeader(DistributedHerder.java:1625)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.writeTaskConfigs(DistributedHerder.java:2139)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.publishConnectorTaskConfigs(DistributedHerder.java:2095)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:2082)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithExponentialBackoffRetries(DistributedHerder.java:2025)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$null$42(DistributedHerder.java:2038)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.runRequest(DistributedHerder.java:2232)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:470)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:371)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.kafka.common.errors.UnknownServerException: The server experienced an unexpected error when processing the request.
2024-01-18 08:02:37,955 ERROR [Worker clientId=connect-1, groupId=kafka-stream-connect-cluster] Failed to reconfigure connector's tasks 

`kubectl logs -f <kafka-pod-name>`

2024-01-18 08:02:39,004 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-1]
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at org.apache.kafka.storage.internals.log.OffsetIndex.append(OffsetIndex.java:155)
        at kafka.log.LogSegment.append(LogSegment.scala:168)
        at kafka.log.LocalLog.append(LocalLog.scala:439)
        at kafka.log.UnifiedLog.append(UnifiedLog.scala:911)
        at kafka.log.UnifiedLog.appendAsLeader(UnifiedLog.scala:719)
        at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:1313)
        at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:1301)
        at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$6(ReplicaManager.scala:1282)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
        at scala.collection.mutable.HashMap.map(HashMap.scala:35)
        at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:1270)
        at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:873)
        at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:686)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:180)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:153)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-01-18 08:02:41,012 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-6]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:02:45,021 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-5]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:02:53,027 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-1]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:03:09,033 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-6]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:03:41,041 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-3]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:04:41,050 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-7]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:05:41,058 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-5]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:06:41,067 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-0]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:07:41,075 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-4]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:08:41,083 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-0]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:09:41,091 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-2]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:10:41,098 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-3]
org.apache.kafka.common.errors.InvalidOffsetException: Attempt to append an offset 3 to position 1 no larger than the last offset appended (3) to /var/lib/kafka/data-0/kafka-log1/kafka-stream-connect-cluster-configs-0/00000000000000000000.index
2024-01-18 08:11:41,106 ERROR [ReplicaManager broker=1] Error processing append operation on partition kafka-stream-connect-cluster-configs-0 (kafka.server.ReplicaManager) [data-plane-kafka-request-handler-3]

### Strimzi version

quay.io/strimzi/operator:0.39.0

### Kubernetes version

v1.27.4+k3s1

**Comment by gaozuo** [comment]
I just closed the duplicate discussion [https://github.com/orgs/strimzi/discussions/9565]

**Comment by scholzj** [comment]
Why are you opening yet another issue? You already had #9566 closed because of the discussion. Issues should be opened for Strimzi issues. not for user configuration issues or users needing help. So please explain what on this is a Strimzi issue. Maybe there is something, but what you shared has no proper formatting and is pretty unreadable, there are no complete logs and no explanation where or what `fails to register a connect plugin`.

**Comment by gaozuo** [comment]
OK, I'll open a discussion next time, but this question only has a small amount of internal error messages. There's not a lot of information to go by, and I'm using the simplest configuration possible. I have now re-edited the question, please check.

**Comment by gaozuo** [comment]
storage:
      type:jbod
      volumes:
      -id: 0
        type: persistent-claim
        class: nfs-client
        size: 100Gi
        deleteClaim: true

I have found the problem. The problem is class: nfs-client. I commented this line and it works normally. nfs-client uses https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.
