### ISSUE TITLE
[KRaft]: Allow KafkaRoller directly connect to controllers 

### ISSUE THREAD

**Issue by tinaselenge** [strimzi/strimzi-kafka-operator#9692]
### Related problem

KafkaRoller currently connects to the controller via brokers to get the quorum health information. 

### Suggested solution

With Strimzi supporting Kafka 3.7 which includes [KIP 919](https://cwiki.apache.org/confluence/display/KAFKA/KIP-919%3A+Allow+AdminClient+to+Talk+Directly+with+the+KRaft+Controller+Quorum+and+add+Controller+Registration), we should create a service for controller pods and make KafkaRoller connect to it for quorum information.

**Comment by scholzj** [comment]
Triaged on the community call on 22.2.2024: This should be done once Kafka 3.7 is released. Unless the implementation is trivial, it should have a proposal.

**Comment by tinaselenge** [comment]
When working on this, I discovered that we need to configure controller listeners with hostnames in order for Admin client to bootstrap. This was not clearly stated in the KIP, so I raised an upstream [issue](https://issues.apache.org/jira/browse/KAFKA-16612). 

Reconfiguring the controller listeners do work and allows the operator to talk to the controller directly. I have raised a draft PR #10016. However, this causes controller pods to crash once or twice until the DNS is updated. When a pod gets terminated, pod's IP address changes and the DNS needs to be updated to resolve the hostnames to the new IP address. It looks like controller start up is much quicker than normal brokers, therefore binding happens before the DNS is updated which results in a controller pod crashing a couple of times before it runs ok. 

Despite the crash, the controller pod eventually runs and works fine but this is the side effect we have currently. It's not clear how or whether it would get fixed in Kafka upstream.

**Comment by tinaselenge** [comment]
This issue is blocked until https://issues.apache.org/jira/browse/KAFKA-16781 is completed.

**Comment by tinaselenge** [comment]
We currently cannot update logging configuration dynamically for controllers because we cannot talk to controllers directly. If the logging config is not dynamic, the controllers would not be rolled either.  Looks like the user need to trigger manual rolling update for controllers to change the log level. This can be solved once we can talk to the controller directly. However, in the meantime, should this be opened as a separate issue to track it and potentially add a workaround similar to how we handle controller config changes (we extract the controller-relevant configurations and use it in the configuration annotations)? 
(cc @scholzj)

**Comment by scholzj** [comment]
@tinaselenge Yeah, if you could open a separate issue it would be great. Looks like the controller access won't be fixed anytime soon. So I will try to look at it and put together some workaround until we can talk with the controllers. Thanks for noticing and raising this!

**Comment by hari819** [comment]
will we not face this issue in 0.46 version if i point the cluster to use kafka version 3.9.0?

**Comment by hari819** [comment]
nope i get the same issue which i faced with 4.0.0 version from here, 

![Image](https://github.com/user-attachments/assets/e9901d5c-66b5-4e76-a434-4298c63fee36)

**Comment by tinaselenge** [comment]
@hari819 can you please elaborate more on what issue you are encountering? Currently the operator is not talking directly to the controller yet (the implementation for that was reverted) so the error you highlighted would be an issue connecting to brokers.

**Comment by hari819** [comment]
while trying to deploy kafka cluster in KRAFT mode with 0.46.0 version,  adminclient could not be created with the below exception

```2025-06-09 09:55:24 DEBUG KafkaRoller:921 - Reconciliation #314(timer) Kafka(kafka-test/kafka): 1 kafka nodes are []  
2025-06-09 09:55:24 DEBUG KafkaRoller:923 - Reconciliation #314(timer) Kafka(kafka-test/kafka): 2 kafka nodes are []  
2025-06-09 09:55:24 DEBUG KafkaRoller:930 - Reconciliation #314(timer) Kafka(kafka-test/kafka): Creating AdminClient for kafka-kafka-bootstrap.kafka-test.svc.xxx.yyy.zzz:9091
2025-06-09 09:55:24 WARN ClientUtils:90 - Couldn't resolve server kafka-kafka-bootstrap.kafka-test.svc.xxx.yyy.zzz:9091 from bootstrap.servers as DNS resolution failed for kafka-kafka-bootstrap.kafka-test.svc.xxx.yyy.zzz
2025-06-09 09:55:24 WARN KafkaRoller:220 - Reconciliation #314(timer) Kafka(kafka-test/kafka): Failed to create controllerAdminClient.
io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: An error while try to create an admin client with bootstrap brokers kafka-kafka-bootstrap.kafka-test.svc.xxx.yyy.zzz:9091
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.adminClient(KafkaRoller.java:937) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.maybeInitControllerAdminClient(KafkaRoller.java:218) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.checkIfRestartOrReconfigureRequired(KafkaRoller.java:606) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartIfNecessary(KafkaRoller.java:454) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$schedule$7(KafkaRoller.java:363) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:572) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:517) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.admin.Admin.create(Admin.java:138) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at io.strimzi.operator.common.DefaultAdminClientProvider.createAdminClient(DefaultAdminClientProvider.java:47) ~[io.strimzi.operator-common-0.46.0.jar:0.46.0]
at io.strimzi.operator.common.DefaultAdminClientProvider.createAdminClient(DefaultAdminClientProvider.java:21) ~[io.strimzi.operator-common-0.46.0.jar:0.46.0]
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.adminClient(KafkaRoller.java:931) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
... 10 more
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:104) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:63) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.admin.internals.AdminBootstrapAddresses.fromConfig(AdminBootstrapAddresses.java:72) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:536) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:517) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at org.apache.kafka.clients.admin.Admin.create(Admin.java:138) ~[org.apache.kafka.kafka-clients-4.0.0.jar:?]
at io.strimzi.operator.common.DefaultAdminClientProvider.createAdminClient(DefaultAdminClientProvider.java:47) ~[io.strimzi.operator-common-0.46.0.jar:0.46.0]
at io.strimzi.operator.common.DefaultAdminClientProvider.createAdminClient(DefaultAdminClientProvider.java:21) ~[io.strimzi.operator-common-0.46.0.jar:0.46.0]
at io.strimzi.operator.cluster.operator.resource.KafkaRoller.adminClient(KafkaRoller.java:931) ~[io.strimzi.cluster-operator-0.46.0.jar:0.46.0]
... 10 more```

**Comment by ppatierno** [comment]
@hari819 you should use a GitHub discussion to talk about an issue you are facing and not polluting this one which is about an "enhancement" issue. Can you please move to discussions? Thanks ;-)
